Repository gardener/gardener, pull requests merged in 2018-07, with the labels that each got.

#252 Add documentation about how shoot updates handled
  docs/README.md
  docs/usage/shoots.md
Labels: area/documentation, component/gardener, size/xs

#261 Ensure Shoot names and worker names are DNS-1123 label compatible
  pkg/apis/garden/validation/validation.go
  pkg/apis/garden/validation/validation_test.go
Labels: component/gardener, kind/bug, needs/review, platform/all, reviewed/ok-to-test, size/xs, status/under-investigation, topology/shoot

#266 Add network policy to restrict traffic from kube-apiserver
  charts/_versions.tpl
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/network-policy.yaml
  charts/seed-controlplane/charts/kube-apiserver/values.yaml
  pkg/client/kubernetes/base/namespaces.go
  pkg/client/kubernetes/types.go
  pkg/operation/hybridbotanist/controlplane.go
  pkg/operation/seed/seed.go
Labels: area/security, component/gardener, platform/all, topology/shoot

#274 Change maxUnavailable parameter in machineDeployment to 0.
  charts/seed-machines/charts/machines/values.yaml
  pkg/operation/hybridbotanist/machines.go
Labels: area/high-availability, component/machine-controller-manager, platform/all, topology/seed

#271 Adds generation of password for the monitoring stack
  charts/seed-monitoring/charts/grafana/templates/grafana-deployment.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-secret.yaml
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/secrets.go
Labels: area/monitoring, area/security, component/gardener, topology/seed

#295 Use k8s.io/kube-deploy/cmd/openapi-gen for generation
  Gopkg.lock
  Gopkg.toml
  hack/generate-code
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  vendor/k8s.io/kube-openapi/.gitignore
  vendor/k8s.io/kube-openapi/.travis.yml
  vendor/k8s.io/kube-openapi/CONTRIBUTING.md
  vendor/k8s.io/kube-openapi/Godeps/Godeps.json
  vendor/k8s.io/kube-openapi/Godeps/Readme
  vendor/k8s.io/kube-openapi/OWNERS
  vendor/k8s.io/kube-openapi/README.md
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
  vendor/k8s.io/kube-openapi/code-of-conduct.md
  vendor/k8s.io/kube-openapi/pkg/aggregator/aggregator.go
  vendor/k8s.io/kube-openapi/pkg/generators/README
  vendor/k8s.io/kube-openapi/pkg/generators/rules/names_match.go
  vendor/k8s.io/kube-openapi/pkg/idl/doc.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/testdata/swagger.json
  vendor/k8s.io/kube-openapi/pkg/util/proto/testdata/swagger_next.json
  vendor/k8s.io/kube-openapi/pkg/util/proto/testing/openapi.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/errors.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/types.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/validation.go
  vendor/k8s.io/kube-openapi/pkg/util/sets/empty.go
  vendor/k8s.io/kube-openapi/pkg/util/sets/string.go
  vendor/k8s.io/kube-openapi/test/integration/README.md
  vendor/k8s.io/kube-openapi/test/integration/builder/main.go
  vendor/k8s.io/kube-openapi/test/integration/pkg/generated/openapi_generated.go
  vendor/k8s.io/kube-openapi/test/integration/testdata/golden.json
  vendor/k8s.io/kube-openapi/test/integration/testdata/listtype/atomic-list.go
  vendor/k8s.io/kube-openapi/test/integration/testdata/listtype/map-list.go
  vendor/k8s.io/kube-openapi/test/integration/testdata/listtype/set-list.go
Labels: area/dev-productivity, component/gardener, kind/bug, platform/all, topology/garden

#301 minikube auth. mode extra propety name updated
  docs/deployment/kubernetes-minikube.md
Labels: area/documentation

#267 Reserve excess capacity in seed cluster
  charts/_versions.tpl
  charts/images.yaml
  charts/seed-bootstrap/templates/reserve-excess-capacity/deployment.yaml
  charts/seed-bootstrap/templates/reserve-excess-capacity/priorityclass.yaml
  charts/seed-controlplane/charts/cluster-autoscaler/templates/deployment.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/_helpers.tpl
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver.yaml
  charts/seed-controlplane/charts/kube-scheduler/templates/_helpers.tpl
  charts/shoot-cloud-config/charts/original/templates/kubelet/_kubelet.flags
  pkg/controller/seed/seed_control.go
  pkg/operation/seed/seed.go
Labels: area/deployment, area/high-availability, area/operations, area/scalability, area/security, component/gardener, kind/enhancement, platform/all, reviewed/lgtm, topology/seed, topology/shoot

#294 Care Controller: Remove evicted pods in Shoots control plane namespace on a Seed.
  pkg/operation/botanist/garbage_collection.go
Labels: area/operations, needs/review, platform/all, topology/seed

#302 use docker multi-stage build
  .ci/build
  .ci/pipeline_definitions
  .dockerignore
  Dockerfile
  Makefile
  build/gardener-apiserver/Dockerfile
  build/gardener-controller-manager/Dockerfile
Labels: area/dev-productivity, kind/enhancement, platform/all, priority/normal, reviewed/lgtm, size/s, status/accepted
