Repository gardener/gardener, pull requests merged in 2019-05, with the labels that each got.

#971 kubelet config has podPidsLimit instead of podPIDsLimit
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet-config-file
Labels: kind/bug, needs/ok-to-test

#970 Change node-exporter's port
  charts/shoot-core/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
  charts/shoot-core/charts/monitoring/charts/node-exporter/values.yaml
Labels: needs/ok-to-test

#967 Scrape CCM via HTTP on Alicloud
  charts/seed-monitoring/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/prometheus/values.yaml
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#976 Fix contextified Sleep
  pkg/utils/retry.go
  pkg/utils/retry_test.go
Labels: kind/bug, needs/lgtm, needs/ok-to-test, needs/review, platform/all, size/xs, status/under-investigation

#977 Delete hibernate shoot cluster on alicloud
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/cloudbotanist/alicloudbotanist/controlplane.go
  pkg/operation/hybridbotanist/controlplane.go
Labels: needs/ok-to-test

#975 Delete hibernate shoot cluster on alicloud
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/cloudbotanist/alicloudbotanist/controlplane.go
  pkg/operation/hybridbotanist/controlplane.go
Labels: needs/ok-to-test

#973 Hotfix nil pointer in plant health check
  pkg/controllermanager/controller/plant/plant_control.go
  pkg/controllermanager/controller/plant/plant_health.go
  pkg/controllermanager/controller/plant/plant_test.go
  pkg/controllermanager/controller/plant/plant_utils.go
Labels: area/robustness, component/gardener, kind/bug, needs/ok-to-test, platform/all, size/s, topology/plant

#974 Fix imagevector Merge + types
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/factory_test.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/cloudbotanist/alicloudbotanist/controlplane.go
  pkg/operation/cloudbotanist/awsbotanist/controlplane.go
  pkg/operation/hybridbotanist/addon_manager.go
  pkg/operation/hybridbotanist/addons.go
  pkg/operation/hybridbotanist/cloud_config.go
  pkg/operation/hybridbotanist/controlplane.go
  pkg/operation/operation.go
  pkg/operation/seed/seed.go
  pkg/utils/chart/chart.go
  pkg/utils/chart/chart_test.go
  pkg/utils/imagevector/imagevector.go
  pkg/utils/imagevector/imagevector_test.go
  pkg/utils/imagevector/types.go
  pkg/utils/test/test.go
  pkg/utils/version.go
Labels: exp/expert, kind/cleanup, needs/lgtm, needs/ok-to-test, needs/review, platform/all, priority/normal, size/xl, status/in-progress, topology/garden

#978 Fix versions -> runtimeVersion
  charts/images.yaml
Labels: needs/ok-to-test

#979 Remove chart.Values type, fix type conversion
  pkg/operation/operation.go
  pkg/utils/chart/chart.go
  pkg/utils/chart/chart_test.go
Labels: area/robustness, component/gardener, kind/bug, needs/ok-to-test, platform/all, size/s

#983 revisionHistoryLimit was contained twice in the deployment spec
  charts/seed-monitoring/charts/kube-state-metrics-shoot/templates/kube-state-metrics.yaml
Labels: area/monitoring, needs/ok-to-test, platform/all, reviewed/lgtm, size/xs, status/accepted, topology/seed

#986 Increase node-exporter CPU
  charts/shoot-core/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
Labels: needs/ok-to-test

#980 Improve logrotate config
  charts/seed-operatingsystemconfig/original/templates/logrotate/_docker-logrotate.timer
  charts/seed-operatingsystemconfig/original/templates/logrotate/docker.conf
  pkg/client/kubernetes/horizontalpodautoscaler.go
Labels: needs/ok-to-test

#982 integrate vpa exporter
  charts/images.yaml
  charts/seed-bootstrap/charts/vpa/templates/vpa-exporter-rbac.yaml
  charts/seed-bootstrap/charts/vpa/templates/vpa-exporter.yaml
  charts/seed-bootstrap/charts/vpa/values.yaml
  charts/seed-monitoring/charts/grafana/dashboards/vpa-dashboard.json
  charts/seed-monitoring/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/prometheus/values.yaml
  pkg/operation/common/types.go
  pkg/operation/common/utils.go
  pkg/operation/seed/seed.go
Labels: needs/ok-to-test

#988 updated golang image for testdefs
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/PlantTest.yaml
  .test-defs/SeedLoggingTest.yaml
  .test-defs/ShootAppTest.yaml
Labels: needs/ok-to-test

#989 Fix Shoot cleanup for extended API groups
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/operation/botanist/cleanup.go
  pkg/utils/flow/flow_test.go
  pkg/utils/flow/taskfn.go
Labels: area/robustness, component/gardener, kind/bug, needs/ok-to-test, platform/all, priority/normal, size/s, topology/shoot

#992 Reduce excess capacity for Shoot CP on seed
  pkg/operation/seed/seed.go
Labels: needs/ok-to-test

#960 Network policy for KubeApiserver on Alicloud
  charts/seed-controlplane/charts/kube-apiserver/templates/network-policy.yaml
  charts/seed-controlplane/charts/kube-apiserver/values.yaml
  pkg/operation/hybridbotanist/controlplane.go
Labels: needs/ok-to-test

#997 Clean up cluster-service label
  Dockerfile
  charts/shoot-addons/charts/kubernetes-dashboard/templates/deployment.yaml
  example/30-cloudprofile-alicloud.yaml
  example/30-cloudprofile-aws.yaml
  example/30-cloudprofile-azure.yaml
  example/30-cloudprofile-gcp.yaml
  example/30-cloudprofile-openstack.yaml
  example/90-shoot-alicloud.yaml
  hack/templates/resources/30-cloudprofile.yaml.tpl
  hack/templates/resources/90-shoot.yaml.tpl
  pkg/apis/core/types_plant.go
  pkg/apis/core/types_utils.go
  pkg/apis/core/v1alpha1/types_plant.go
  pkg/apis/extensions/v1alpha1/types_worker.go
  pkg/chartrenderer/sorter.go
  pkg/controllermanager/controller/secretbinding/secretbinding.go
  pkg/controllermanager/controller/seed/seed.go
Labels: needs/ok-to-test, reviewed/ok-to-test

#998 slack channel badge, virtual installer
  README.md
Labels: needs/ok-to-test

#990 Added dependency-watchdog
  charts/images.yaml
  charts/seed-controlplane/charts/dependency-watchdog/Chart.yaml
  charts/seed-controlplane/charts/dependency-watchdog/charts/utils-templates
  charts/seed-controlplane/charts/dependency-watchdog/templates/configmap.yaml
  charts/seed-controlplane/charts/dependency-watchdog/templates/deployment.yaml
  charts/seed-controlplane/charts/dependency-watchdog/templates/rbac.yaml
  charts/seed-controlplane/charts/dependency-watchdog/values.yaml
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/botanist_suite_test.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/common/types.go
Labels: needs/ok-to-test

#994 Change Alicloud EIP type PayByTraffic
  charts/seed-terraformer/charts/alicloud-infra/templates/_main.tf
  charts/seed-terraformer/charts/alicloud-infra/values.yaml
  pkg/client/alicloud/client.go
  pkg/client/alicloud/types.go
  pkg/operation/cloudbotanist/alicloudbotanist/infrastructure.go
Labels: needs/ok-to-test

#937 Etcd storageclass migration
  charts/images.yaml
  charts/seed-controlplane/charts/etcd-storageclass/Chart.yaml
  charts/seed-controlplane/charts/etcd-storageclass/charts/utils-templates
  charts/seed-controlplane/charts/etcd-storageclass/templates/storageclass.yaml
  charts/seed-controlplane/charts/etcd-storageclass/values.yaml
  charts/seed-controlplane/charts/etcd/templates/configmap-etcd-bootstrap.yaml
  charts/seed-controlplane/charts/etcd/templates/etcd-client-service.yaml
  charts/seed-controlplane/charts/etcd/templates/etcd-statefulset.yaml
  charts/seed-controlplane/charts/etcd/values.yaml
  charts/shoot-storageclasses/templates/storageclasses.yaml
  charts/utils-templates/templates/_versions.tpl
  docs/usage/supported_k8s_versions.md
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/waiter.go
  pkg/operation/cloudbotanist/alicloudbotanist/controlplane.go
  pkg/operation/cloudbotanist/awsbotanist/controlplane.go
  pkg/operation/cloudbotanist/azurebotanist/controlplane.go
  pkg/operation/cloudbotanist/gcpbotanist/controlplane.go
  pkg/operation/cloudbotanist/localbotanist/controlplane.go
  pkg/operation/cloudbotanist/openstackbotanist/controlplane.go
  pkg/operation/cloudbotanist/types.go
  pkg/operation/hybridbotanist/controlplane.go
Labels: area/control-plane, component/etcd-backup-restore, needs/ok-to-test, priority/critical, topology/seed

#1007 [ci:component:github.com/gardener/etcd-backup-restore:0.6.2->0.6.3]
  charts/images.yaml
Labels: needs/ok-to-test

#1005 [ci:component:github.com/gardener/machine-controller-manager:0.16.0->0.17.0]
  charts/images.yaml
Labels: needs/ok-to-test

#952 Support for labels, annotations, taints for worker pools
  charts/seed-machines/charts/machines/templates/machinedeployment.yaml
  charts/seed-machines/charts/machines/values.yaml
  example/90-shoot-alicloud.yaml
  example/90-shoot-aws.yaml
  example/90-shoot-azure.yaml
  example/90-shoot-gcp.yaml
  example/90-shoot-openstack.yaml
  example/90-shoot-packet.yaml
  hack/templates/resources/90-shoot.yaml.tpl
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/validation/validation.go
  pkg/apis/garden/validation/validation_test.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/cloudbotanist/alicloudbotanist/machines.go
  pkg/operation/cloudbotanist/awsbotanist/machines.go
  pkg/operation/cloudbotanist/azurebotanist/machines.go
  pkg/operation/cloudbotanist/gcpbotanist/machines.go
  pkg/operation/cloudbotanist/openstackbotanist/machines.go
  pkg/operation/hybridbotanist/machines.go
  pkg/operation/types.go
Labels: needs/ok-to-test

#1011 Increase machine drain and scale down timeouts
  charts/seed-controlplane/charts/cluster-autoscaler/templates/deployment.yaml
  charts/seed-controlplane/charts/machine-controller-manager/templates/deployment.yaml
Labels: needs/ok-to-test

#1009 Add GetExtensionType method to ControlPlane
  pkg/apis/extensions/v1alpha1/types_controlplane.go
Labels: component/gardener, kind/enhancement, platform/all, reviewed/lgtm, size/xs, status/accepted

#1015 Wait for Nodes clean-up when entering hibernation
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/common/utils.go
  pkg/operation/hybridbotanist/controlplane.go
  pkg/operation/operation.go
Labels: area/quality, component/gardener, kind/bug, needs/ok-to-test, needs/review, platform/all, priority/critical, size/s, topology/shoot

#1003 Change blackbox exporter listen address to 127.0.0.1
  charts/seed-monitoring/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/prometheus/templates/prometheus.yaml
Labels: needs/ok-to-test, reviewed/lgtm, status/accepted

#1001 Prevent volume usage alerts
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/curator-es/_resource.tpl
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/curator-es/curator-cronjob.yml
  charts/seed-bootstrap/charts/elastic-kibana-curator/values.yaml
  charts/seed-monitoring/charts/prometheus/rules/kube-kubelet.rules.yaml
  docs/usage/shoots.md
  pkg/apis/core/v1alpha1/types_utils.go
  pkg/operation/botanist/secrets.go
  pkg/operation/common/types.go
  pkg/operation/garden/garden_test.go
  pkg/operation/seed/seed.go
Labels: needs/ok-to-test, reviewed/lgtm

#1017 Prevent seed controller and HPA thrashing
  charts/seed-bootstrap/charts/fluentd-es/templates/fluentd-es-hpa.yaml
  charts/seed-bootstrap/charts/fluentd-es/templates/fluentd-es-statefulset.yaml
  charts/seed-bootstrap/charts/fluentd-es/values.yaml
  pkg/operation/seed/seed.go
  pkg/operation/seed/seed_suite_test.go
  pkg/operation/seed/seed_test.go
Labels: needs/ok-to-test

#1022 Improve helm lint
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-ingress-auth-secret.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-ingress.yaml
  charts/seed-bootstrap/charts/vpa/templates/admission-controller-deployment.yaml
  charts/seed-bootstrap/charts/vpa/templates/recommender-deployment.yaml
  charts/seed-bootstrap/charts/vpa/templates/updater-deployment.yaml
  charts/seed-bootstrap/charts/vpa/templates/vpa-crd.yaml
  charts/seed-bootstrap/charts/vpa/templates/vpa-exporter-rbac.yaml
  charts/seed-bootstrap/charts/vpa/templates/vpa-exporter.yaml
  charts/seed-bootstrap/charts/vpa/templates/vpa-rbac.yaml
  charts/seed-bootstrap/charts/vpa/values.yaml
  charts/seed-monitoring/charts/alertmanager/templates/ingress-auth-secret.yaml
  charts/seed-monitoring/charts/alertmanager/templates/ingress.yaml
  charts/seed-monitoring/charts/alertmanager/values.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-ingress-auth-secret.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-ingress.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-service.yaml
  charts/seed-monitoring/charts/prometheus/templates/ingress-auth-secret.yaml
  charts/seed-monitoring/charts/prometheus/templates/ingress.yaml
  charts/seed-monitoring/charts/prometheus/templates/rbac.yaml
  charts/seed-monitoring/charts/prometheus/templates/rules.yaml
  charts/seed-monitoring/values.yaml
  pkg/controllermanager/controller/shoot/shoot_control.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/hybridbotanist/controlplane.go
Labels: component/gardener, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, size/s, status/accepted

#1018 Upgrade calico to v3.7.2
  charts/images.yaml
  charts/shoot-core/charts/calico/templates/calico.yaml
  charts/shoot-core/charts/calico/templates/config.yaml
  charts/shoot-core/charts/calico/templates/rbac.yaml
  pkg/operation/common/types.go
  pkg/operation/hybridbotanist/addons.go
Labels: area/networking, component/gardener, kind/enhancement, needs/ok-to-test, platform/all, reviewed/lgtm, size/m, topology/shoot

#1023 Fix issue empty OSS buckets cannot be deleted
  pkg/operation/cloudbotanist/alicloudbotanist/infrastructure.go
Labels: component/gardener, kind/bug, needs/ok-to-test, platform/ali, size/xs, topology/shoot

#1025 Support FlexVolume in Alicloud for etcd
  pkg/operation/cloudbotanist/alicloudbotanist/controlplane.go
  pkg/operation/common/types.go
  pkg/operation/seed/seed.go
Labels: component/gardener, kind/bug, needs/ok-to-test, platform/ali, reviewed/lgtm, size/s, status/accepted, topology/seed

#1016 Configure prometheus to scrape metrics for elasticsearch
  charts/images.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/service.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/statefulset.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/values.yaml
  charts/seed-monitoring/charts/prometheus/optional-rules/elasticsearch.rules.yaml
  charts/seed-monitoring/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/prometheus/values.yaml
  pkg/operation/botanist/controlplane.go
  pkg/operation/common/types.go
  pkg/operation/seed/seed.go
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, size/m, status/accepted, topology/seed

#1028 Propagate usage of controller-runtime client
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/curator-es/curator-configmap.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/curator-es/curator-cronjob.yml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/configmap.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/service.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-ingress-auth-secret.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-ingress.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-objects-registration-config.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-saved-objects-config.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-service.yaml
  charts/seed-bootstrap/charts/fluentd-es/templates/fluent-bit-role-binding.yaml
  charts/seed-bootstrap/charts/fluentd-es/templates/fluent-bit-role.yaml
  charts/seed-bootstrap/charts/fluentd-es/templates/fluent-bit-service-account.yaml
  charts/seed-bootstrap/charts/fluentd-es/templates/fluentd-es-hpa.yaml
  charts/seed-bootstrap/charts/fluentd-es/templates/fluentd-es-service.yaml
  docs/development/local_setup.md
  pkg/client/kubernetes/types.go
  pkg/operation/common/utils.go
  pkg/operation/seed/seed.go
Labels: needs/ok-to-test

#1039 Use host-local IPAM for Calico
  charts/shoot-core/charts/calico/templates/calico.yaml
  charts/shoot-core/charts/calico/templates/config.yaml
Labels: area/networking, kind/bug, platform/az, priority/blocker, reviewed/ok-to-test, size/s, topology/shoot

#1012 Add configmap-reloader to Prometheus
  charts/seed-bootstrap/templates/prometheus/statefulset.yaml
  charts/seed-monitoring/charts/prometheus/templates/prometheus.yaml
Labels: needs/ok-to-test

#1036 Increased failedProposal count to 80 for an alert
  charts/seed-monitoring/charts/prometheus/rules-tests/kube-etcd3.rules.test.yaml
  charts/seed-monitoring/charts/prometheus/rules/kube-etcd3.rules.yaml
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, size/s, topology/seed

#1042 [ci:component:github.com/gardener/machine-controller-manager:0.17.0->0.18.0]
  charts/images.yaml
Labels: needs/ok-to-test

#1046 disable node-exporter netclass collector
  charts/shoot-core/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
Labels: area/monitoring, exp/intermediate, needs/ok-to-test, size/s

#1033 Added scale down flag to cluster autoscaler
  charts/seed-controlplane/charts/cluster-autoscaler/templates/deployment.yaml
  charts/seed-controlplane/charts/cluster-autoscaler/values.yaml
  example/90-shoot-alicloud.yaml
  example/90-shoot-aws.yaml
  example/90-shoot-azure.yaml
  example/90-shoot-gcp.yaml
  example/90-shoot-local.yaml
  example/90-shoot-openstack.yaml
  example/90-shoot-packet.yaml
  hack/templates/resources/90-shoot.yaml.tpl
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/validation/validation.go
  pkg/apis/garden/validation/validation_test.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#1040 Allow disabling CPU throttling
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet-config-file
  charts/seed-operatingsystemconfig/original/values.yaml
  example/90-shoot-alicloud.yaml
  example/90-shoot-aws.yaml
  example/90-shoot-azure.yaml
  example/90-shoot-gcp.yaml
  example/90-shoot-local.yaml
  example/90-shoot-openstack.yaml
  example/90-shoot-packet.yaml
  hack/templates/resources/90-shoot.yaml.tpl
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/hybridbotanist/cloud_config.go
Labels: needs/ok-to-test

#1035 Update maintenance window docs
  docs/usage/shoots.md
  pkg/apis/core/v1alpha1/helper/helpers_test.go
  pkg/apis/garden/validation/validation.go
  pkg/apis/garden/validation/validation_test.go
  pkg/controllermanager/controller/project/project.go
  pkg/operation/cloudbotanist/alicloudbotanist/alicloudbotanist.go
  pkg/operation/common/types.go
  test/integration/seeds/logging/seed_log_test.go
Labels: needs/ok-to-test

#1053 Respect deletion grace period over syncPeriod for backupInfra
  pkg/controllermanager/controller/backupinfrastructure/backup_infrastructure_control.go
Labels: needs/ok-to-test

#1041 Add k8s conformance test results grid to the documentation
  README.md
Labels: needs/ok-to-test, reviewed/ok-to-test

#1044 Add Gardener network extension resource
  docs/proposals/03-networking.md
  pkg/apis/extensions/v1alpha1/register.go
  pkg/apis/extensions/v1alpha1/types_network.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/extensions_client.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_extensions_client.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_network.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/generated_expansion.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/network.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/interface.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/network.go
  pkg/client/extensions/informers/externalversions/generic.go
  pkg/client/extensions/listers/extensions/v1alpha1/expansion_generated.go
  pkg/client/extensions/listers/extensions/v1alpha1/network.go
Labels: needs/ok-to-test, reviewed/ok-to-test
