Repository gardener/gardener, pull requests merged in 2019-12, with the labels that each got.

#1678 Handling case when deleting HVPA resource, but the CRD itself is missing
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#1646 Use ManagedResources to deploy ControllerInstallations
  docs/extensions/controllerregistration.md
  pkg/controllermanager/controller/controllerinstallation/controllerinstallation_control.go
  pkg/controllermanager/controller/controllerinstallation/controllerinstallation_types.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/resource_manager.go
Labels: needs/ok-to-test

#1677 Clean up deletion of legacy ManagedResource
  pkg/operation/botanist/addons.go
Labels: needs/ok-to-test

#1679 Allow to skip certain cleanup steps
  pkg/apis/core/v1alpha1/constants/types_constants.go
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/operation/botanist/cleanup.go
Labels: needs/ok-to-test

#1686 Fix kube-proxy PodSecurityPolicy to use hostPort
  charts/shoot-core/components/charts/kube-proxy/templates/psp/kube-proxy-psp.yaml
Labels: needs/ok-to-test

#1687 [ci:component:github.com/gardener/gardener-resource-manager:v0.8.0->v0.8.1]
  charts/images.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/gardener-resource-manager/pkg/manager/managedresources.go
  vendor/github.com/gardener/gardener-resource-manager/pkg/manager/managedsecrets.go
  vendor/modules.txt
Labels: needs/ok-to-test

#1689 Fixes shoot care controller panic
  pkg/controllermanager/controller/shoot/shoot_care_control.go
Labels: needs/ok-to-test

#1696 Fix link to Node-details dashboard
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-pool-dashboard.json
Labels: needs/ok-to-test

#1693 remove redis-slave from test, as this is not required for test success. Upgrade redis chart
  test/integration/framework/applications/guestbooktest.go
Labels: needs/ok-to-test, reviewed/ok-to-test

#1695 Prevent potential nil pointer in shoot validator admission plugin
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: needs/ok-to-test

#1692 Add external label "name" to prometheus.
  charts/seed-bootstrap/dashboards/alerts-dashboard.json
  charts/seed-bootstrap/dashboards/cluster-overview.json
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
Labels: needs/ok-to-test

#1694 add merge patch strategy to apis
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/garden.md
  hack/api-reference/settings.md
  pkg/apis/core/v1alpha1/types_cloudprofile.go
  pkg/apis/core/v1alpha1/types_controllerinstallation.go
  pkg/apis/core/v1alpha1/types_plant.go
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/types_shootstate.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/apis/extensions/v1alpha1/types_worker.go
  pkg/apis/garden/v1beta1/types.go
  pkg/openapi/openapi_generated.go
Labels: needs/ok-to-test

#1690 Add shoot-info configmap to kube-system namespace
  charts/shoot-core/components/charts/shoot-info/Chart.yaml
  charts/shoot-core/components/charts/shoot-info/templates/configmap.yaml
  charts/shoot-core/components/charts/shoot-info/values.yaml
  charts/shoot-core/components/values.yaml
  pkg/operation/botanist/addons.go
Labels: needs/ok-to-test

#1698 Improve shoot care controller status updates
  pkg/controllermanager/controller/shoot/shoot_care_control.go
  pkg/utils/kubernetes/shoot.go
Labels: needs/ok-to-test

#1699 Set add cpu and memory graphs to use a linear scale
  charts/seed-monitoring/charts/grafana/dashboards/operators/coredns-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/kubernetes-pods-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/vpn-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-control-plane-status-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-details-dashboard.json
Labels: needs/ok-to-test

#1688 Add network policies to shoot
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
  charts/shoot-core/components/charts/network-policies/Chart.yaml
  charts/shoot-core/components/charts/network-policies/charts/utils-templates
  charts/shoot-core/components/charts/network-policies/templates/allow-from-seed.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-to-dns.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-to-public-networks.yaml
  charts/shoot-core/components/charts/network-policies/values.yaml
  pkg/operation/botanist/addons.go
Labels: needs/ok-to-test

#1701 Update nginx-ingress version and allow configurability of `externalTrafficPolicy`
  charts/images.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/clusterrole.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/role.yaml
  example/90-deprecated-shoot-alicloud.yaml
  example/90-deprecated-shoot-aws.yaml
  example/90-deprecated-shoot-azure.yaml
  example/90-deprecated-shoot-gcp.yaml
  example/90-deprecated-shoot-openstack.yaml
  example/90-deprecated-shoot-packet.yaml
  example/90-shoot.yaml
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/garden.md
  hack/api-reference/settings.md
  hack/templates/resources/90-deprecated-shoot.yaml.tpl
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/zz_generated.defaults.go
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/defaults.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/v1beta1/zz_generated.defaults.go
  pkg/apis/garden/validation/validation_shoot.go
  pkg/apis/garden/validation/validation_shoot_test.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/addons.go
  test/integration/framework/applications/guestbooktest.go
Labels: needs/ok-to-test

#1641 Added dependency-watchdog as a bootstrap component
  .ci/test
  charts/global-network-policies/templates/allow-to-all-shoot-apiservers.yaml
  charts/images.yaml
  charts/seed-bootstrap/charts/dependency-watchdog/Chart.yaml
  charts/seed-bootstrap/charts/dependency-watchdog/charts/utils-templates
  charts/seed-bootstrap/charts/dependency-watchdog/templates/endpoint-configmap.yaml
  charts/seed-bootstrap/charts/dependency-watchdog/templates/endpoint-deployment.yaml
  charts/seed-bootstrap/charts/dependency-watchdog/templates/endpoint-rbac.yaml
  charts/seed-bootstrap/charts/dependency-watchdog/templates/probe-configmap.yaml
  charts/seed-bootstrap/charts/dependency-watchdog/templates/probe-deployment.yaml
  charts/seed-bootstrap/charts/dependency-watchdog/templates/probe-rbac.yaml
  charts/seed-bootstrap/charts/dependency-watchdog/values.yaml
  charts/seed-controlplane/charts/dependency-watchdog/templates/rbac.yaml
  charts/seed-controlplane/charts/dependency-watchdog/values.yaml
  charts/seed-controlplane/charts/kube-controller-manager/templates/kube-controller-manager.yaml
  pkg/apis/core/v1alpha1/constants/types_constants.go
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/secrets.go
  pkg/operation/common/types.go
  pkg/operation/seed/seed.go
Labels: needs/ok-to-test

#1685 Restrict validity of browser certs to 2 years
  charts/seed-monitoring/charts/grafana/templates/grafana-ingress.yaml
  pkg/operation/botanist/secrets.go
  pkg/utils/secrets/certificates.go
  pkg/utils/secrets/generate.go
Labels: needs/ok-to-test

#1700 Vendor sigs.k8s.io/controller-runtime@v0.2.2
  go.mod
  go.sum
  pkg/apis/core/v1alpha1/types_cloudprofile.go
  pkg/operation/botanist/cleanup.go
  pkg/operation/botanist/etcdencryption.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/common/utils.go
  pkg/utils/errors/errors.go
  pkg/utils/kubernetes/client/options.go
  plugin/pkg/shoot/oidc/clusteropenidconnectpreset/admission_test.go
  plugin/pkg/shoot/oidc/openidconnectpreset/admission_test.go
  test/integration/framework/utils.go
  test/integration/shoots/maintenance/maintenance_test.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/compiler/reader.go
  vendor/github.com/googleapis/gnostic/extensions/COMPILE-EXTENSION.sh
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
  vendor/gomodules.xyz/jsonpatch/v2/.gitignore
  vendor/gomodules.xyz/jsonpatch/v2/.travis.yml
  vendor/gomodules.xyz/jsonpatch/v2/CHANGELOG.md
  vendor/gomodules.xyz/jsonpatch/v2/README.md
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.travis.yml
  vendor/sigs.k8s.io/controller-runtime/Gopkg.lock
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/eventhandler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/recorder/recorder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go
Labels: needs/ok-to-test

#1617 Enable tainting seeds to disable DNS
  charts/shoot-addons/charts/nginx-ingress/values.yaml
  charts/shoot-core/components/charts/kube-proxy/values.yaml
  charts/shoot-core/components/values.yaml
  docs/usage/configuration.md
  example/50-seed.yaml
  go.sum
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/garden.md
  hack/api-reference/settings.md
  pkg/apis/core/v1alpha1/conversions_test.go
  pkg/apis/core/v1alpha1/helper/helper.go
  pkg/apis/core/v1alpha1/helper/helpers_test.go
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/garden/helper/helpers.go
  pkg/apis/garden/helper/helpers_test.go
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/conversion_test.go
  pkg/apis/garden/v1beta1/conversions.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/validation/validation_seed.go
  pkg/apis/roundtrip_seed_migration_test.go
  pkg/apis/roundtrip_shoot_migration_test.go
  pkg/controllermanager/controller/controllerinstallation/controllerinstallation_control.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/dns.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/secrets.go
  pkg/operation/garden/garden.go
  pkg/operation/garden/garden_test.go
  pkg/operation/operation.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/shoot_test.go
  pkg/operation/shoot/types.go
  pkg/scheduler/controller/shoot/scheduler_control.go
  pkg/utils/kubernetes/kubernetes.go
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/global/resourcereferencemanager/admission_test.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: needs/ok-to-test

#1703 Update integration tests docs
  docs/testing/integration_tests.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/botanist_suite_test.go
  pkg/operation/common/types.go
  test/integration/framework/applications/guestbooktest.go
  test/integration/shoots/applications/shoot_app_test.go
  test/integration/shoots/creation/create_test.go
Labels: needs/ok-to-test

#1706 Set error in ShootStatus if operation cannot be initialized
  pkg/controllermanager/controller/shoot/shoot_control.go
  pkg/operation/shoot/shoot.go
Labels: needs/ok-to-test

#1707 Implement etcd encryption (at REST) for Gardener API server
  cmd/gardener-apiserver/app/gardener_apiserver.go
  example/21-encryptionconfiguration.yaml
  go.sum
  pkg/apiserver/storage/storage.go
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/cryptobyte/asn1/asn1.go
  vendor/golang.org/x/crypto/cryptobyte/builder.go
  vendor/golang.org/x/crypto/cryptobyte/string.go
  vendor/golang.org/x/crypto/nacl/secretbox/secretbox.go
  vendor/golang.org/x/crypto/salsa20/salsa/hsalsa20.go
  vendor/golang.org/x/crypto/salsa20/salsa/salsa208.go
  vendor/golang.org/x/crypto/salsa20/salsa/salsa20_amd64.go
  vendor/golang.org/x/crypto/salsa20/salsa/salsa20_amd64.s
  vendor/golang.org/x/crypto/salsa20/salsa/salsa20_noasm.go
  vendor/golang.org/x/crypto/salsa20/salsa/salsa20_ref.go
  vendor/k8s.io/apiserver/pkg/server/options/encryptionconfig/OWNERS
  vendor/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go
  vendor/k8s.io/apiserver/pkg/storage/value/encrypt/aes/aes.go
  vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/envelope.go
  vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/grpc_service.go
  vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/v1beta1/service.pb.go
  vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/v1beta1/service.proto
  vendor/k8s.io/apiserver/pkg/storage/value/encrypt/identity/identity.go
  vendor/k8s.io/apiserver/pkg/storage/value/encrypt/secretbox/secretbox.go
  vendor/modules.txt
Labels: needs/ok-to-test

#1712 Remove health check for calico typha
  pkg/operation/botanist/botanist_suite_test.go
  pkg/operation/common/types.go
Labels: area/networking, needs/ok-to-test

#1714 Fix volume type conversion for shoot workers
  pkg/apis/garden/v1beta1/conversions.go
  pkg/apis/roundtrip_shoot_migration_test.go
Labels: needs/ok-to-test

#1715 Adapt integration tests to core.gardener.cloud/v1beta1
  test/integration/framework/common.go
  test/integration/framework/dump.go
  test/integration/framework/errors.go
  test/integration/framework/framework_test.go
  test/integration/framework/garden_operation.go
  test/integration/framework/helm_utils.go
  test/integration/framework/plant_operations.go
  test/integration/framework/scheduler_operations.go
  test/integration/framework/shoot_maintenance_operations.go
  test/integration/framework/shoot_operations.go
  test/integration/framework/types.go
  test/integration/framework/utils.go
  test/integration/framework/worker_operations.go
  test/integration/gardener/rbac/gardener_rbac_suite_test.go
  test/integration/gardener/rbac/gardener_rbac_test.go
  test/integration/gardener/reconcile/gardener_reconcile_test.go
  test/integration/plants/plant_suite_test.go
  test/integration/scheduler/scheduler_suite_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/seeds/logging/seed_log_test.go
  test/integration/seeds/logging/seedlogging_suite_test.go
  test/integration/shoots/applications/shoot_app_test.go
  test/integration/shoots/applications/shootapplications_suite_test.go
  test/integration/shoots/creation/create_suite_test.go
  test/integration/shoots/creation/create_test.go
  test/integration/shoots/deletion/delete_suite_test.go
  test/integration/shoots/deletion/delete_test.go
  test/integration/shoots/hibernation/hibernation_suite_test.go
  test/integration/shoots/hibernation/hibernation_test.go
  test/integration/shoots/maintenance/maintenance_suite_test.go
  test/integration/shoots/maintenance/maintenance_test.go
  test/integration/shoots/networking/shoot_networking_test.go
  test/integration/shoots/networking/shootnetworking_suite_test.go
  test/integration/shoots/reconcile/shoot_reconcile_test.go
  test/integration/shoots/reconcile/shootreconcile_suite_test.go
  test/integration/shoots/update/shoot_update_test.go
  test/integration/shoots/update/shootupdate_suite_test.go
  test/integration/shoots/worker/scaleout/shoot_scaleout_test.go
  test/integration/shoots/worker/scaleout/shootscaleout_suite_test.go
  test/integration/shoots/worker/worker_suite_test.go
  test/integration/shoots/worker/worker_test.go
Labels: needs/ok-to-test

#1716 Adopt v prefixes in go.mod
  Dockerfile
  go.mod
  go.sum
  vendor/github.com/gardener/external-dns-management/LICENSE.md
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/dnsentry.go
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/dnsprovider.go
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/doc.go
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/state.go
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/scheme/doc.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/scheme/register.go
  vendor/modules.txt
Labels: needs/ok-to-test

#1718 Minor nit about hibernation doc
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/garden.md
  hack/api-reference/settings.md
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/openapi/openapi_generated.go
Labels: needs/ok-to-test

#1719 Revert nginx-ingress version to 0.22.0
  charts/images.yaml
Labels: needs/ok-to-test

#1728 Fix feature gate handling for gardenlet
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/logging.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/secrets.go
Labels: kind/bug, needs/ok-to-test

#1730 Fix computation of component descriptor
  .ci/component_descriptor
Labels: needs/ok-to-test

#1729 Let end users read events
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
Labels: area/ops-productivity, area/usability, component/gardener, kind/enhancement, needs/ok-to-test, platform/all, size/xs, topology/garden

#1733 [ci:component:github.com/gardener/logging:0.19.0->v0.20.0]
  charts/images.yaml
Labels: needs/ok-to-test

#1732 Add RegEx for new infra dependency
  pkg/apis/core/v1alpha1/helper/errors.go
  pkg/apis/core/v1alpha1/helper/errors_test.go
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/apis/core/v1beta1/helper/errors_test.go
Labels: needs/ok-to-test

#1702 [GEP-8] SNI Passthrough proxy for kube-apiservers
  docs/proposals/08-shoot-apiserver-via-sni.md
Labels: area/control-plane, area/cost, area/networking, area/scalability, component/gardener, exp/expert, kind/enhancement, needs/ok-to-test, platform/all, size/xl, topology/seed, topology/shoot

#1734 Use internal DNS for dependency-watchdog external probe.
  charts/seed-bootstrap/charts/dependency-watchdog/templates/probe-configmap.yaml
  pkg/operation/botanist/secrets.go
  pkg/operation/common/types.go
  pkg/operation/seed/seed.go
Labels: needs/ok-to-test

#1738 Allow 1.17 Kubernetes clients to be instantiated
  pkg/client/kubernetes/client.go
Labels: needs/ok-to-test

#1739 Make validation func public
  pkg/apis/garden/validation/validation_shoot.go
  pkg/apis/garden/validation/validation_utils.go
Labels: needs/ok-to-test

#1741 Let extensions API use v1beta1 version of core API
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/garden.md
  hack/api-reference/settings.md
  pkg/api/extensions/accessor.go
  pkg/api/extensions/accessor_test.go
  pkg/apis/core/v1alpha1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/extensions/v1alpha1/types.go
  pkg/apis/extensions/v1alpha1/types_defaults.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_control.go
  pkg/gardenlet/controller/backupbucket/backup_bucket_actuator.go
  pkg/gardenlet/controller/backupentry/backup_entry_actuator.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/infrastructure.go
  pkg/operation/botanist/network.go
  pkg/operation/botanist/worker.go
  pkg/operation/common/utils.go
  pkg/utils/kubernetes/health/health.go
  pkg/utils/kubernetes/health/health_test.go
Labels: needs/ok-to-test

#1710 [GEP-9] Test framework
  docs/proposals/09-test-framework.md
Labels: needs/ok-to-test

#1745 Revert change to gardener test
  .test-defs/PlantTest.yaml
Labels: needs/ok-to-test

#1742 Disable node anti affinity for single replica
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/scheduler/deployment.yaml
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  charts/seed-bootstrap/charts/fluentd-es/templates/fluentd-es-statefulset.yaml
Labels: needs/ok-to-test

#1740 Let gardenlet delete the bootstrap token itself
  cmd/gardenlet/app/bootstrap.go
  cmd/gardenlet/app/gardenlet.go
  pkg/controllermanager/controller/certificatesigningrequest/csr_autoapprove_control.go
  pkg/gardenlet/bootstrap/bootstrap.go
Labels: needs/ok-to-test

#1748 Store resources in etcd in `core.gardener.cloud/v1beta1` version
  cmd/gardener-apiserver/app/gardener_apiserver.go
  pkg/apis/core/install/install.go
Labels: needs/ok-to-test

#1752 Minor nit in integration test utils
  docs/testing/integration_tests.md
  test/integration/framework/utils.go
Labels: needs/ok-to-test

#1750 Enable scale down also for kube-apiserver via HVPA
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver-hvpa.yaml
Labels: needs/ok-to-test

#1754 Temporarily add experimental Kyma addon
  charts/shoot-addons-kyma/Chart.yaml
  charts/shoot-addons-kyma/charts/kyma/Chart.yaml
  charts/shoot-addons-kyma/charts/kyma/charts/utils-templates
  charts/shoot-addons-kyma/charts/kyma/files/certificate.sh
  charts/shoot-addons-kyma/charts/kyma/files/dns.sh
  charts/shoot-addons-kyma/charts/kyma/files/installation.sh
  charts/shoot-addons-kyma/charts/kyma/files/tiller.sh
  charts/shoot-addons-kyma/charts/kyma/files/wait-for-certificate.sh
  charts/shoot-addons-kyma/charts/kyma/files/wait-for-installation.sh
  charts/shoot-addons-kyma/charts/kyma/files/wait-for-tiller.sh
  charts/shoot-addons-kyma/charts/kyma/templates/clusterrolebinding.yaml
  charts/shoot-addons-kyma/charts/kyma/templates/configmap.yaml
  charts/shoot-addons-kyma/charts/kyma/templates/job-certificate.yaml
  charts/shoot-addons-kyma/charts/kyma/templates/job-installation.yaml
  charts/shoot-addons-kyma/charts/kyma/templates/job-tiller.yaml
  charts/shoot-addons-kyma/charts/kyma/templates/namespace.yaml
  charts/shoot-addons-kyma/charts/kyma/templates/serviceaccount.yaml
  charts/shoot-addons-kyma/charts/kyma/values.yaml
  charts/shoot-addons-kyma/requirements.yaml
  charts/shoot-addons-kyma/values.yaml
  pkg/apis/garden/validation/validation_shoot.go
  pkg/operation/botanist/addons.go
  pkg/operation/common/types.go
  pkg/registry/garden/shoot/strategy.go
Labels: needs/ok-to-test

#1755 Improve dependency of kubelet and updatecacert services
  charts/seed-operatingsystemconfig/original/templates/ssl/_update-ca-certs.service
Labels: needs/ok-to-test

#1756 Improve DNS validation
  pkg/apis/garden/validation/validation_shoot.go
  pkg/apis/garden/validation/validation_shoot_test.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: needs/ok-to-test

#1757 Fix allow adding zones
  pkg/apis/core/v1alpha1/conversions.go
  pkg/apis/core/v1beta1/conversions.go
  pkg/apis/garden/v1beta1/conversions.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: needs/ok-to-test

#1758 [release-v0.33] Improve dependency of kubelet and updatecacert services
  charts/seed-operatingsystemconfig/original/templates/ssl/_update-ca-certs.service
Labels: needs/ok-to-test

#1736 Add install section to downloader osc
  charts/seed-operatingsystemconfig/downloader/templates/osc.yaml
Labels: needs/ok-to-test

#1761 Keep old machine image in shoot validator admission plugin
  pkg/apis/garden/helper/helpers.go
  pkg/apis/garden/helper/helpers_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: needs/ok-to-test

#1759 Shoot Care Controller - adapt extension condition status
  pkg/operation/botanist/health_check.go
Labels: needs/ok-to-test

#1760 Change API version priority
  charts/gardener/controlplane/charts/application/templates/apiservice-v1alpha1-core-gardener-cloud.yaml
  charts/gardener/controlplane/charts/application/templates/apiservice-v1beta1-core-gardener-cloud.yaml
  charts/gardener/controlplane/charts/application/templates/apiservice-v1beta1-garden-sapcloud-io.yaml
  hack/dev-setup-register-gardener
Labels: needs/ok-to-test

#1764 Enable embed-certs for minikube
  docs/development/local_setup.md
Labels: area/dev-productivity, area/documentation, component/gardener, kind/enhancement, needs/ok-to-test, topology/garden

#1766 sap-tv link broken
  README.md
Labels: needs/ok-to-test

#1767 Update Proposals list
  docs/README.md
Labels: needs/ok-to-test

#1753 Add extension healthiness to `ControllerInstallation` and `Seed`
  charts/gardener/gardenlet/charts/runtime/templates/configmap-componentconfig.yaml
  example/20-componentconfig-gardenlet.yaml
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/garden.md
  hack/api-reference/settings.md
  pkg/apis/core/types_controllerinstallation.go
  pkg/apis/core/v1alpha1/types_controllerinstallation.go
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/core/v1beta1/types_controllerinstallation.go
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_care_control.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_control.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_types.go
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/seed/seed.go
  pkg/gardenlet/controller/seed/seed_extension_control.go
  pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener-resource-manager/pkg/health/health.go
  vendor/modules.txt
Labels: needs/ok-to-test

#1770 Move logic to separate packages
  docs/testing/integration_tests.md
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/garden.md
  hack/api-reference/settings.md
  pkg/apis/core/v1alpha1/constants/types_constants.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/helper/errors.go
  pkg/apis/core/v1alpha1/helper/helper.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/garden/helper/helpers.go
  pkg/apis/garden/v1beta1/defaults.go
  pkg/apis/garden/v1beta1/helper/helpers.go
  pkg/apis/garden/validation/validation_shoot.go
  pkg/client/core/openapi/zz_generated.openapi.go
  pkg/client/kubernetes/client.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_control.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/plant/plant.go
  pkg/controllermanager/controller/project/project_control_reconcile.go
  pkg/controllermanager/controller/shoot/shoot_hibernation_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation.go
  pkg/gardenlet/controller/shoot/shoot.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/logger/logger.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/garbage_collection.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/secrets.go
  pkg/operation/garden/garden.go
  pkg/operation/seed/seed.go
  pkg/utils/error.go
  pkg/utils/errors/errors.go
  pkg/utils/flow/flow.go
  pkg/utils/imagevector/imagevector.go
  pkg/utils/miscellaneous.go
  pkg/utils/version/version.go
  plugin/pkg/shoot/oidc/applier.go
  plugin/pkg/shoot/quotavalidator/admission.go
  test/integration/framework/plant_operations.go
  test/integration/framework/scheduler_operations.go
  test/integration/framework/utils.go
  test/integration/seeds/logging/seed_log_test.go
  test/integration/shoots/creation/create_test.go
Labels: needs/ok-to-test

#1769 Serve control plane endpoints with trusted certs
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/elasticsearch-vpa.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-ingress.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/values.yaml
  charts/seed-bootstrap/templates/aggregate-prometheus/ingress.yaml
  charts/seed-bootstrap/templates/grafana/ingress.yaml
  charts/seed-bootstrap/values.yaml
  charts/seed-monitoring/charts/alertmanager/templates/ingress.yaml
  charts/seed-monitoring/charts/alertmanager/values.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/ingress.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus-vpa.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-ingress.yaml
  charts/seed-monitoring/charts/grafana/values.yaml
  docs/README.md
  docs/usage/trusted-tls-for-control-planes.md
  pkg/operation/botanist/logging.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/secrets.go
  pkg/operation/common/types.go
  pkg/operation/common/utils.go
  pkg/operation/operation.go
  pkg/operation/operation_suite_test.go
  pkg/operation/operation_test.go
  pkg/operation/seed/seed.go
  pkg/operation/seed/seed_test.go
  pkg/operation/shoot/shoot.go
  pkg/operation/types.go
Labels: needs/ok-to-test

#1773 Fix the build
  pkg/operation/botanist/addons.go
  pkg/operation/seed/seed_test.go
  test/integration/framework/garden_operation.go
Labels: needs/ok-to-test
