Repository gardener/gardener, pull requests merged in 2019-07, with the labels that each got.

#1158 Fix minor markdown issue
  README.md
  charts/seed-bootstrap/templates/extensions/crd-controlplane.yaml
Labels: needs/ok-to-test

#1160 Added a 1s sleep while polling the etcd sidecar during startup.
  charts/seed-controlplane/charts/etcd/templates/configmap-etcd-bootstrap.yaml
Labels: needs/ok-to-test

#1162 support inject volume provider value during install controller
  pkg/controllermanager/controller/controllerinstallation/controllerinstallation_control.go
  pkg/operation/common/utils.go
  pkg/operation/seed/seed.go
Labels: component/gardener, needs/ok-to-test, platform/ali, size/s, topology/soil

#1163 support inject volume provider value during install controller
  pkg/controllermanager/controller/controllerinstallation/controllerinstallation_control.go
  pkg/operation/common/utils.go
  pkg/operation/seed/seed.go
Labels: needs/ok-to-test

#1164 Add support to specify seed in create-shoot tests
  .test-defs/cmd/create-shoot/main.go
Labels: needs/ok-to-test

#1159 Adding vpa exporter vpa to prevent OOMKills for vpa-exporter.
  charts/seed-bootstrap/charts/vpa/templates/vpa-exporter-vpa.yaml
  charts/seed-bootstrap/charts/vpa/templates/vpa-exporter.yaml
  charts/seed-monitoring/charts/core/charts/kube-state-metrics-seed/templates/kube-state-metrics.yaml
  charts/seed-monitoring/charts/core/charts/kube-state-metrics-seed/values.yaml
  charts/seed-monitoring/charts/core/charts/kube-state-metrics-shoot/templates/kube-state-metrics.yaml
  charts/seed-monitoring/charts/core/charts/kube-state-metrics-shoot/values.yaml
  pkg/operation/botanist/controlplane.go
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, size/s, topology/seed

#1169 Increase default timeout for seed monitoring
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
Labels: needs/ok-to-test

#1172 Replace poll with retry methods with proper errors
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/infrastructure.go
  pkg/operation/botanist/worker.go
  test/integration/framework/scheduler_operations.go
Labels: needs/ok-to-test

#1173 Remove VPA Feature Gate
  charts/seed-bootstrap/requirements.yaml
  charts/seed-bootstrap/templates/prometheus/prometheus-vpa.yaml
  charts/seed-bootstrap/templates/prometheus/statefulset.yaml
  charts/seed-bootstrap/values.yaml
  charts/seed-controlplane/charts/etcd/templates/etcd-vpa.yaml
  charts/seed-controlplane/charts/etcd/values.yaml
  charts/seed-controlplane/charts/gardener-resource-manager/templates/vpa.yaml
  charts/seed-controlplane/charts/gardener-resource-manager/values.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver-vpa.yaml
  charts/seed-controlplane/charts/kube-apiserver/values.yaml
  charts/seed-controlplane/charts/kube-controller-manager/templates/kube-controller-manager-vpa.yaml
  charts/seed-controlplane/charts/kube-controller-manager/values.yaml
  charts/seed-controlplane/charts/kube-scheduler/templates/kube-scheduler-vpa.yaml
  charts/seed-controlplane/charts/kube-scheduler/values.yaml
  charts/seed-monitoring/charts/core/charts/kube-state-metrics-seed/templates/kube-state-metrics.yaml
  charts/seed-monitoring/charts/core/charts/kube-state-metrics-seed/values.yaml
  charts/seed-monitoring/charts/core/charts/kube-state-metrics-shoot/templates/kube-state-metrics.yaml
  charts/seed-monitoring/charts/core/charts/kube-state-metrics-shoot/values.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus-vpa.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/seed-monitoring/charts/core/values.yaml
  charts/seed-monitoring/values.yaml
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/controllermanager/features/features.go
  pkg/features/features.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/common/types.go
  pkg/operation/common/utils.go
  pkg/operation/hybridbotanist/controlplane.go
  pkg/operation/hybridbotanist/resource_manager.go
  pkg/operation/seed/seed.go
Labels: needs/ok-to-test

#1175 Implement Extension accessor
  pkg/api/extensions/accessor.go
  pkg/api/extensions/accessor_test.go
  pkg/api/extensions/extensions_suite_test.go
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/extensions/install/install.go
  pkg/apis/extensions/v1alpha1/register.go
  pkg/apis/extensions/v1alpha1/types.go
  pkg/apis/extensions/v1alpha1/types_backupbucket.go
  pkg/apis/extensions/v1alpha1/types_backupentry.go
  pkg/apis/extensions/v1alpha1/types_controlplane.go
  pkg/apis/extensions/v1alpha1/types_defaults.go
  pkg/apis/extensions/v1alpha1/types_extension.go
  pkg/apis/extensions/v1alpha1/types_infrastructure.go
  pkg/apis/extensions/v1alpha1/types_network.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/apis/extensions/v1alpha1/types_worker.go
  pkg/controllermanager/controller/controllerinstallation/controllerinstallation_control.go
Labels: needs/ok-to-test

#1176 Add k8s conformance test coverage for k8s release v1.15*
  README.md
Labels: needs/ok-to-test

#1178 Adapt container requests based on VPA recommendations
  charts/seed-controlplane/charts/gardener-resource-manager/values.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver.yaml
  charts/seed-controlplane/charts/kube-scheduler/values.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
Labels: needs/ok-to-test

#1180 PR-Template: add developer target group
  .github/pull_request_template.md
Labels: needs/ok-to-test

#1184 Update example resources
  Gopkg.lock
  Gopkg.toml
  example/30-cloudprofile-alicloud.yaml
  example/30-cloudprofile-aws.yaml
  example/30-cloudprofile-azure.yaml
  example/30-cloudprofile-gcp.yaml
  example/30-cloudprofile-openstack.yaml
  example/30-cloudprofile-packet.yaml
  hack/templates/resources/30-cloudprofile.yaml.tpl
Labels: needs/ok-to-test

#1183 Remove cleanup code from old grafana deployment
  pkg/operation/botanist/controlplane.go
  pkg/operation/common/utils.go
Labels: reviewed/ok-to-test

#1188 Implement Extension accessor
  pkg/api/extensions/accessor.go
  pkg/api/extensions/accessor_test.go
  pkg/api/extensions/extensions_suite_test.go
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/extensions/install/install.go
  pkg/apis/extensions/v1alpha1/register.go
  pkg/apis/extensions/v1alpha1/types.go
  pkg/apis/extensions/v1alpha1/types_backupbucket.go
  pkg/apis/extensions/v1alpha1/types_backupentry.go
  pkg/apis/extensions/v1alpha1/types_controlplane.go
  pkg/apis/extensions/v1alpha1/types_defaults.go
  pkg/apis/extensions/v1alpha1/types_extension.go
  pkg/apis/extensions/v1alpha1/types_infrastructure.go
  pkg/apis/extensions/v1alpha1/types_network.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/apis/extensions/v1alpha1/types_worker.go
Labels: reviewed/ok-to-test

#1186 Better naming for 'make start-api' and 'make start'
  Makefile
  docs/development/local_setup.md
  hack/start-apiserver
  hack/start-controller-manager
Labels: needs/ok-to-test

#1187 remove shoot migration coding
  pkg/controllermanager/controller/shoot/shoot.go
Labels: needs/ok-to-test

#1197 Add gardener.cloud "dashboard" API group
  charts/gardener/charts/application/templates/rbac-user.yaml
Labels: needs/ok-to-test

#1196 Less bash in the Dockerfile (date format)
  Dockerfile
Labels: needs/ok-to-test

#1199 Enable encryption for default storage class of shoot cluster on Alicloud
  pkg/operation/cloudbotanist/alicloudbotanist/addons.go
Labels: needs/ok-to-test

#1200 Need to check storageclass name in alicloud when deleting
  pkg/operation/cloudbotanist/alicloudbotanist/addons.go
Labels: needs/ok-to-test, reviewed/ok-to-test

#1201 Enable encryption flag in storageclass on Alicloud
  pkg/operation/cloudbotanist/alicloudbotanist/addons.go
Labels: needs/ok-to-test

#1195 Fix resource creation while namespace in deletion issue
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
Labels: needs/ok-to-test

#1204 [hotfix] Add purpose-based deletion grace period for backup infrastructure
  charts/gardener/charts/runtime/templates/configmap-controller-manager.yaml
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
  pkg/controllermanager/controller/backupinfrastructure/backup_infrastructure_control.go
  pkg/operation/botanist/controlplane.go
  pkg/registry/garden/backupinfrastructure/strategy.go
  pkg/registry/garden/shoot/strategy.go
Labels: needs/ok-to-test

#1210 [hotfix]Fix the template for backupInfrastructure deletionGracePeriodHoursByPurpose in gardener chart
  charts/gardener/charts/runtime/templates/configmap-controller-manager.yaml
Labels: needs/ok-to-test

#1211 Fix make check
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
Labels: needs/ok-to-test

#1208 Implement audit policy validation
  pkg/operation/hybridbotanist/controlplane.go
  pkg/operation/hybridbotanist/controlplane_test.go
  pkg/operation/hybridbotanist/hybridbotanist_suite_test.go
Labels: needs/ok-to-test

#1220 Improve kind node name check for hack/dev-setup
  docs/development/local_setup.md
  hack/common
Labels: needs/ok-to-test

#1221 Continue cleanup delete if object is finalized
  pkg/utils/kubernetes/client/client.go
  pkg/utils/kubernetes/client/client_test.go
Labels: needs/ok-to-test

#1230 Fix accessor last operation typed nil pointer
  pkg/apis/extensions/v1alpha1/types_defaults.go
Labels: needs/ok-to-test

#1222 Added vpa for all controlplane components and set it to Auto.
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/elasticsearch-vpa.yaml
  charts/seed-controlplane/charts/aws-lb-readvertiser/templates/aws-lb-readvertiser.yaml
  charts/seed-controlplane/charts/dependency-watchdog/templates/deployment.yaml
  charts/seed-controlplane/charts/gardener-resource-manager/templates/vpa.yaml
  charts/seed-controlplane/charts/kube-controller-manager/templates/kube-controller-manager-vpa.yaml
  charts/seed-controlplane/charts/kube-scheduler/templates/kube-scheduler-vpa.yaml
  charts/seed-monitoring/charts/alertmanager/templates/alertmanager.yaml
Labels: needs/ok-to-test

#1192 Allow multiple AZs in OpenStack w/o dedicated subnets
  pkg/apis/garden/validation/validation.go
Labels: needs/ok-to-test

#1227 remove runtimeVersion (>= 1.14.x) specification for alicloud
  charts/images.yaml
Labels: needs/ok-to-test

#1231 Enhance Gardener Helm chart with anti-affinity and PDB
  charts/gardener/charts/runtime/templates/apiserver/_helpers.tpl
  charts/gardener/charts/runtime/templates/apiserver/configmap-audit-policy.yaml
  charts/gardener/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/charts/runtime/templates/apiserver/poddisruptionbudget.yaml
  charts/gardener/charts/runtime/templates/apiserver/secret-audit-webhook-config.yaml
  charts/gardener/charts/runtime/templates/apiserver/secret-cert.yaml
  charts/gardener/charts/runtime/templates/apiserver/secret-kubeconfig.yaml
  charts/gardener/charts/runtime/templates/apiserver/service.yaml
  charts/gardener/charts/runtime/templates/apiserver/serviceaccount.yaml
  charts/gardener/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  charts/gardener/charts/runtime/templates/controller-manager/configmap-imagevector-overwrite.yaml
  charts/gardener/charts/runtime/templates/controller-manager/deployment.yaml
  charts/gardener/charts/runtime/templates/controller-manager/poddisruptionbudget.yaml
  charts/gardener/charts/runtime/templates/controller-manager/secret-cert.yaml
  charts/gardener/charts/runtime/templates/controller-manager/secret-kubeconfig.yaml
  charts/gardener/charts/runtime/templates/controller-manager/service.yaml
  charts/gardener/charts/runtime/templates/controller-manager/serviceaccount.yaml
  charts/gardener/charts/runtime/templates/scheduler/configmap-componentconfig.yaml
  charts/gardener/charts/runtime/templates/scheduler/deployment.yaml
  charts/gardener/charts/runtime/templates/scheduler/poddisruptionbudget.yaml
  charts/gardener/charts/runtime/templates/scheduler/secret-kubeconfig.yaml
  charts/gardener/charts/runtime/templates/scheduler/service.yaml
  charts/gardener/charts/runtime/templates/scheduler/serviceaccount.yaml
Labels: component/gardener, kind/enhancement, needs/ok-to-test, platform/all, size/m, status/accepted, topology/garden

#1233 remove storage class upgrade logic
  pkg/operation/cloudbotanist/alicloudbotanist/addons.go
  test/integration/gardener/reconcile/gardener_reconcile_test.go
Labels: needs/ok-to-test

#1236 Adjust tests to use go modules
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/PlantTest.yaml
  .test-defs/RBACTest.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/SchedulerTest.yaml
  .test-defs/SeedLoggingTest.yaml
  .test-defs/SeedNetworkPoliciesTest.yaml
  .test-defs/ShootAppTest.yaml
Labels: needs/ok-to-test

#1235 Increase bcrypt cost
  pkg/utils/secrets/basic_auth.go
Labels: needs/ok-to-test

#1234 Increse requests and limits for the VPN-shoot componenet
  charts/shoot-core/charts/vpn-shoot/templates/deployment.yaml
Labels: needs/ok-to-test

#1212 Adds API server usage grafana dashboard
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-api-server.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-control-plane-status-dashboard.json
Labels: needs/ok-to-test

#1203 Add shoot kubernetes version update test
  pkg/apis/garden/v1beta1/helper/helpers.go
  pkg/apis/garden/v1beta1/helper/helpers_test.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  test/integration/framework/shoot_operations.go
  test/integration/shoots/update/shoot_update_test.go
  test/integration/shoots/update/shootupdate_suite_test.go
Labels: needs/ok-to-test

#1239 Always deploy gardener-resource-manager
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
Labels: needs/ok-to-test

#1238 Remove insecure TLS cipher suites
  charts/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
Labels: needs/ok-to-test

#1243 Allow to filter by target version for image vector
  pkg/utils/imagevector/imagevector.go
  pkg/utils/imagevector/imagevector_suite_test.go
  pkg/utils/imagevector/imagevector_test.go
  pkg/utils/imagevector/types.go
Labels: needs/ok-to-test

#1245 Update alicloud min worker nodes to 2
  example/90-shoot-alicloud.yaml
Labels: needs/ok-to-test

#1249 Make rbac test namespace cutomizable
  .test-defs/RBACTest.yaml
Labels: needs/ok-to-test

#1242 Unregister shoot as seed when it was annotated and gets deleted
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
Labels: needs/ok-to-test

#1165 Add reconcile annotation for extensions
  charts/seed-operatingsystemconfig/downloader/templates/osc.yaml
  charts/seed-operatingsystemconfig/original/templates/osc.yaml
  docs/extensions/conventions.md
  pkg/api/extensions/accessor.go
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/extensions/v1alpha1/types.go
  pkg/apis/extensions/v1alpha1/types_defaults.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/infrastructure.go
  pkg/operation/botanist/worker.go
  pkg/operation/hybridbotanist/cloud_config.go
  pkg/utils/flow/flow.go
  pkg/utils/kubernetes/health/health.go
  pkg/utils/kubernetes/health/health_test.go
Labels: component/gardener, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, size/s, topology/seed

#1255 Revert "Remove insecure TLS cipher suites"
  charts/utils-tls-cipher-suites/templates/_tls_cipher_suites.tpl
Labels: kind/bug, needs/ok-to-test, platform/aws, priority/blocker, size/xs, topology/seed, topology/shoot

#1258 Removed optional annotation from internal types
  pkg/apis/garden/types.go
Labels: needs/ok-to-test

#1256 Added loadbalancer classes support for openstack controlplane extension
  .gitignore
  go.mod
  go.sum
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/migration/openstack.go
  pkg/openapi/openapi_generated.go
  vendor/github.com/gardener/gardener-extensions/controllers/provider-openstack/pkg/apis/openstack/types_controlplane.go
  vendor/github.com/gardener/gardener-extensions/controllers/provider-openstack/pkg/apis/openstack/v1alpha1/types_controlplane.go
  vendor/github.com/gardener/gardener-extensions/controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener-extensions/controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extensions/controllers/provider-openstack/pkg/apis/openstack/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: needs/ok-to-test

#1260 Improve when to delete kube-apiserver HPA during hibernation
  pkg/operation/botanist/controlplane.go
  pkg/operation/hybridbotanist/controlplane.go
Labels: needs/ok-to-test

#1262 Explicitly set cluster autoscaler configuration
  charts/seed-controlplane/charts/cluster-autoscaler/templates/deployment.yaml
  charts/seed-controlplane/charts/cluster-autoscaler/values.yaml
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#1261 Support for worker pool OSC customization
  charts/seed-operatingsystemconfig/original/templates/osc.yaml
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/hybridbotanist/cloud_config.go
Labels: needs/ok-to-test

#1263 Adjusting gardener scheduler test definitions for the test machinery
  .test-defs/SchedulerTest.yaml
  .test-defs/cmd/scheduler/main.go
Labels: needs/ok-to-test

#1257 Add first version of gardener integration tests
  .ci/get_latest_release_component_descriptor
  .ci/testruns/default/Chart.yaml
  .ci/testruns/default/templates/testrun-default.yaml
  .ci/testruns/default/values.yaml
  .ci/tm-test
Labels: needs/ok-to-test

#1177 Allow to opt-out of automatic machine image upgrades
  .test-defs/ShootMaintenanceTest.yaml
  .test-defs/cmd/helper.go
  .test-defs/cmd/shoot-maintenance/main.go
  .test-defs/cmd/shoot-maintenance/maintenance_tests.go
  example/30-cloudprofile-alicloud.yaml
  example/30-cloudprofile-aws.yaml
  example/30-cloudprofile-azure.yaml
  example/30-cloudprofile-gcp.yaml
  example/30-cloudprofile-openstack.yaml
  example/30-cloudprofile-packet.yaml
  example/90-shoot-alicloud.yaml
  example/90-shoot-aws.yaml
  example/90-shoot-azure.yaml
  example/90-shoot-gcp.yaml
  example/90-shoot-openstack.yaml
  example/90-shoot-packet.yaml
  hack/templates/resources/30-cloudprofile.yaml.tpl
  hack/templates/resources/90-shoot.yaml.tpl
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/apis/garden/helper/helpers.go
  pkg/apis/garden/helper/helpers_test.go
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/conversion_test.go
  pkg/apis/garden/v1beta1/conversions.go
  pkg/apis/garden/v1beta1/defaults.go
  pkg/apis/garden/v1beta1/helper/helpers.go
  pkg/apis/garden/v1beta1/helper/helpers_test.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/validation/validation.go
  pkg/apis/garden/validation/validation_test.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_test.go
  pkg/openapi/openapi_generated.go
  pkg/operation/hybridbotanist/cloud_config.go
  pkg/operation/shoot/shoot.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  test/integration/framework/scheduler_operations.go
  test/integration/framework/shoot_maintenance_operations.go
  test/integration/framework/shoot_operations.go
  test/integration/framework/types.go
  test/integration/shoots/maintenance/maintenance_suite_test.go
  test/integration/shoots/maintenance/maintenance_test.go
Labels: kind/enhancement, needs/ok-to-test, platform/all, size/m, topology/garden

#1267 Add additional information regarding e2e test coverage
  README.md
Labels: needs/ok-to-test

#1189 Improve kubernetes pods dashboard
  charts/seed-monitoring/charts/grafana/dashboards/operators/kubernetes-pods-dashboard.json
Labels: needs/ok-to-test

#1268 Fix plant test example path
  .test-defs/PlantTest.yaml
Labels: needs/ok-to-test

#1269 Fetch scheduler configuration from host cluster
  .test-defs/cmd/scheduler/main.go
  test/integration/framework/scheduler_operations.go
  test/integration/scheduler/scheduler_test.go
Labels: needs/ok-to-test

#1271 Fix integration test
  .ci/get_latest_release_component_descriptor
  .ci/testruns/default/templates/testrun-default.yaml
Labels: needs/ok-to-test

#1272 Add gardener scheduler integration test to tm testsuite
  .ci/testruns/default/templates/testrun-default.yaml
  .ci/tm-test
Labels: needs/ok-to-test
