Repository gardener/gardener, pull requests merged in 2019-09, with the labels that each got.

#1383 Add state dump to create and delete shoot
  .test-defs/cmd/create-shoot/main.go
  .test-defs/cmd/delete-shoot/main.go
  test/integration/framework/garden_operation.go
  test/integration/gardener/rbac/gardener_rbac_test.go
  test/integration/gardener/reconcile/gardener_reconcile_test.go
  test/integration/plants/plant_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/seeds/logging/seed_log_test.go
  test/integration/shoots/applications/shoot_app_test.go
  test/integration/shoots/ts/shoot_app_test.go
  test/integration/shoots/update/shoot_update_test.go
  test/integration/shoots/worker/worker_test.go
Labels: needs/ok-to-test

#1389 Fix the issues with backup extensions
  pkg/apis/core/validation/backupentry.go
Labels: needs/ok-to-test, reviewed/ok-to-test

#1388 Remove backup infrastructure mitigation from tests
  .test-defs/cmd/create-shoot/main.go
  .test-defs/cmd/helper.go
Labels: needs/ok-to-test

#1392 Propagate reconcile annotation across backup extension resource
  pkg/controllermanager/controller/backupbucket/backup_bucket_actuator.go
  pkg/controllermanager/controller/backupentry/backup_entry_actuator.go
  pkg/controllermanager/controller/seed/seed_control.go
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#1393 Fix backup bucket reconciliation
  charts/gardener/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  charts/gardener/values.yaml
  cmd/utils/miscellaneous.go
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/controllermanager/controller/backupbucket/backup_bucket_actuator.go
  pkg/controllermanager/controller/backupbucket/backup_bucket_reconciler.go
  pkg/controllermanager/controller/backupentry/backup_entry_actuator.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_control.go
  pkg/controllermanager/controller/controllerregistration/seed_control.go
  pkg/controllermanager/controller/seed/seed_control.go
  pkg/controllermanager/controller/utils/finalizers.go
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#1391 Rewrite secrets in parallel for etcd encryption
  pkg/operation/botanist/etcdencryption.go
  pkg/utils/flow/flow_test.go
  pkg/utils/flow/taskfn.go
Labels: area/performance, component/gardener, kind/enhancement, needs/ok-to-test, topology/shoot

#1395 Add CI build status badge
  README.md
Labels: needs/ok-to-test

#1396 Remove unused consts
  pkg/client/kubernetes/types.go
  pkg/utils/kubernetes/health/health.go
Labels: needs/ok-to-test

#1397 Add backupProvider label on seednamespace even if backup is not configured in seed
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#1398 Update examples with the appropriate spec
  example/50-deprecated-seed-alicloud.yaml
  example/50-deprecated-seed-aws.yaml
  example/50-deprecated-seed-azure.yaml
  example/50-deprecated-seed-gcp.yaml
  example/50-deprecated-seed-openstack.yaml
  example/50-deprecated-seed-packet.yaml
  hack/templates/resources/50-deprecated-seed.yaml.tpl
Labels: needs/ok-to-test

#1381 Fix false positive Etcd alert
  charts/seed-monitoring/charts/core/charts/prometheus/rules-tests/kube-etcd3.rules.test.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-etcd3.rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
Labels: needs/ok-to-test

#1399 Add pod count to grafana for seeds
  charts/seed-bootstrap/dashboards/alerts-dashboard.json
  charts/seed-bootstrap/dashboards/cluster-overview.json
  charts/seed-bootstrap/dashboards/seed-resource-usage.json
Labels: needs/ok-to-test

#1400 Ignore err if the shoot cannot be added
  .test-defs/cmd/delete-shoot/main.go
Labels: needs/ok-to-test

#1406 Upgrade monitoring images
  charts/images.yaml
  charts/seed-monitoring/charts/core/charts/kube-state-metrics-seed/templates/kube-state-metrics.yaml
  charts/seed-monitoring/charts/core/charts/kube-state-metrics-shoot/templates/kube-state-metrics.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/seed-monitoring/charts/grafana/dashboards/operators/kubernetes-statefulsets-dashboard.json
Labels: needs/ok-to-test

#1408 Adjust ManagedResource additionalPrinterColumns
  .dockerignore
  charts/seed-bootstrap/templates/extensions/crd-managedresources.yaml
Labels: needs/ok-to-test

#1401 Enable balance-similar-node-groups flag in cluster-autoscaler
  charts/seed-controlplane/charts/cluster-autoscaler/templates/deployment.yaml
Labels: needs/ok-to-test

#1409 Improve Grafana graph usability
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-api-server-details.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-control-plane-status-dashboard.json
Labels: needs/ok-to-test

#1410 Upgrade prometheus image to 2.12.0
  charts/images.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
Labels: needs/ok-to-test

#1412 Enhance dump logic during shoot failures
  test/integration/framework/garden_operation.go
Labels: needs/ok-to-test

#1422 Unique global monitoring secret name
  pkg/operation/garden/garden.go
  pkg/operation/seed/seed.go
Labels: reviewed/ok-to-test

#1416 Update g/gardener-resource-manager to 0.5.0
  charts/images.yaml
  charts/seed-controlplane/charts/gardener-resource-manager/templates/deployment.yaml
  charts/seed-controlplane/charts/gardener-resource-manager/values.yaml
Labels: needs/ok-to-test

#1417 Alertmanager only for users
  charts/seed-monitoring/charts/alertmanager/templates/allow-alertmanager-network-policy.yaml
  pkg/operation/botanist/monitoring.go
  pkg/operation/common/types.go
Labels: needs/ok-to-test

#1414 Change default volume-plugin dir for kubelet
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.flags
Labels: needs/ok-to-test

#1425 Update to golang 1.13
  Dockerfile
  go.mod
  go.sum
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/tables10.0.0.go
  vendor/golang.org/x/net/idna/tables11.0.0.go
  vendor/golang.org/x/net/idna/tables9.0.0.go
  vendor/modules.txt
Labels: needs/ok-to-test

#1429 Prevent nil pointer exception- no monitoring basic auth secret available
  pkg/controllermanager/controller/backupinfrastructure/backup_infrastructure_control.go
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/network.go
  pkg/operation/botanist/waiter.go
  pkg/operation/hybridbotanist/controlplane.go
  pkg/operation/seed/seed.go
Labels: reviewed/ok-to-test

#1426 Add alert for failed etcd data restoration
  charts/seed-monitoring/charts/core/charts/prometheus/rules-tests/kube-etcd3.rules.test.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-etcd3.rules.yaml
Labels: needs/ok-to-test

#1427 Cleanup the old backup infra resources
  pkg/controllermanager/controller/backupinfrastructure/backup_infrastructure_control.go
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/waiter.go
  pkg/operation/hybridbotanist/controlplane.go
Labels: needs/ok-to-test

#1432 Add more recording rules for aggregate prometheus
  charts/seed-bootstrap/prometheus-rules/recording-rules.rules.yaml
  charts/seed-bootstrap/templates/aggregate-prometheus/config.yaml
Labels: reviewed/ok-to-test

#1436 Prevent panics due to potential invalid type conversion
  pkg/controllermanager/controller/shoot/shoot_hibernation_control.go
Labels: needs/ok-to-test

#1437 Fix Extension deletion for ControllerInstallation
  pkg/controllermanager/controller/controllerinstallation/controllerinstallation_control.go
Labels: needs/ok-to-test

#1440 Add VPA for gardener components
  charts/gardener/charts/runtime/templates/apiserver/vpa.yaml
  charts/gardener/charts/runtime/templates/controller-manager/vpa.yaml
  charts/gardener/charts/runtime/templates/scheduler/vpa.yaml
  charts/gardener/values.yaml
Labels: needs/ok-to-test

#1439 Address some golangci-lint findings
  pkg/apis/garden/v1beta1/helper/helpers_test.go
  pkg/controllermanager/controller/backupbucket/backup_bucket_controller.go
  pkg/controllermanager/controller/backupbucket/backup_bucket_reconciler.go
  pkg/controllermanager/controller/backupentry/backup_entry.go
  pkg/controllermanager/controller/backupentry/backup_entry_reconciler.go
  pkg/operation/cloudbotanist/packetbotanist/infrastructure.go
  pkg/operation/cloudbotanist/packetbotanist/types.go
  pkg/scheduler/controller/backupbucket/scheduler_reconciler.go
  pkg/scheduler/controller/shoot/scheduler.go
Labels: needs/ok-to-test

#1435 Adapt gardener-scheduler to work with `core.gardener.cloud/v1alpha1` resources
  cmd/gardener-scheduler/app/gardener_scheduler.go
  pkg/apis/core/v1alpha1/helper/helper.go
  pkg/apis/core/v1alpha1/helper/helpers_test.go
  pkg/scheduler/apis/config/install/install.go
  pkg/scheduler/controller/backupbucket/scheduler_reconciler.go
  pkg/scheduler/controller/shoot/scheduler.go
  pkg/scheduler/controller/shoot/scheduler_control.go
  pkg/scheduler/controller/shoot/scheduler_suite_test.go
  pkg/scheduler/controller/shoot/scheduler_test.go
  pkg/scheduler/utils/networks.go
  pkg/utils/kubernetes/shoot.go
  test/integration/framework/scheduler_operations.go
Labels: needs/ok-to-test

#1445 [ci:component:github.com/gardener/terraformer:0.13.0->0.14.0]
  charts/images.yaml
Labels: needs/ok-to-test

#1444 Change prometheus retention to 30d
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
Labels: needs/ok-to-test

#1443 Support for Kubernetes v1.16
  charts/images.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver.yaml
  charts/shoot-core/components/charts/coredns/templates/coredns-deployment.yaml
  charts/shoot-core/components/charts/coredns/templates/coredns-rbac.yaml
  charts/shoot-core/components/charts/coredns/values.yaml
  docs/usage/supported_k8s_versions.md
  example/30-deprecated-cloudprofile-alicloud.yaml
  example/30-deprecated-cloudprofile-aws.yaml
  example/30-deprecated-cloudprofile-azure.yaml
  example/30-deprecated-cloudprofile-gcp.yaml
  example/30-deprecated-cloudprofile-openstack.yaml
  example/30-deprecated-cloudprofile-packet.yaml
  example/90-deprecated-shoot-alicloud.yaml
  example/90-deprecated-shoot-aws.yaml
  example/90-deprecated-shoot-azure.yaml
  example/90-deprecated-shoot-gcp.yaml
  example/90-deprecated-shoot-openstack.yaml
  example/90-deprecated-shoot-packet.yaml
  hack/templates/resources/30-deprecated-cloudprofile.yaml.tpl
  hack/templates/resources/90-deprecated-shoot.yaml.tpl
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/zz_generated.defaults.go
  pkg/apis/garden/v1beta1/defaults.go
  pkg/apis/garden/v1beta1/defaults_test.go
  pkg/apis/garden/v1beta1/zz_generated.defaults.go
  pkg/client/kubernetes/client.go
  pkg/openapi/openapi_generated.go
  plugin/pkg/shoot/oidc/clusteropenidconnectpreset/admission.go
  plugin/pkg/shoot/oidc/openidconnectpreset/admission.go
Labels: needs/ok-to-test

#1448 Don't set failBelowRevision for etcd-events
  pkg/operation/hybridbotanist/controlplane.go
Labels: needs/ok-to-test

#1449 Fix backupinfra cleanup
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/operation/hybridbotanist/controlplane.go
Labels: needs/ok-to-test

#1457 [ci:component:github.com/gardener/terraformer:0.14.0->0.15.0]
  charts/images.yaml
Labels: needs/ok-to-test

#1431 Add OS user gardener to the VMs
  charts/seed-operatingsystemconfig/downloader/templates/osc.yaml
  charts/seed-operatingsystemconfig/downloader/templates/scripts/_gardener-user.sh
Labels: needs/ok-to-test

#1459 Use token authentication for kubernetes dashboard test
  test/integration/framework/garden_operation.go
  test/integration/framework/utils.go
  test/integration/shoots/applications/shoot_app_test.go
Labels: needs/ok-to-test

#1458 Aggregate prometheus tsdb metrics
  charts/seed-bootstrap/templates/aggregate-prometheus/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
Labels: needs/ok-to-test

#1460 Update to golang 1.13.1
  Dockerfile
  go.mod
  go.sum
  vendor/github.com/dsnet/compress/bzip2/internal/sais/sais_gen.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  vendor/modules.txt
Labels: needs/ok-to-test

#1464 Fix config
  charts/seed-bootstrap/templates/aggregate-prometheus/config.yaml
Labels: needs/ok-to-test

#1465 trouble shooting guide: dealing with dnsentries "already busy for owner"
  docs/usage/trouble_shooting_guide.md
Labels: needs/ok-to-test

#1468 Enhance retry logic for shootapp test
  test/integration/framework/garden_operation.go
Labels: needs/ok-to-test

#1471 Reduce cpu requests of elasticsearch
  charts/seed-bootstrap/charts/elastic-kibana-curator/values.yaml
Labels: needs/ok-to-test

#1469 Set TerminationGracePeriodSeconds to 300 for clean-up
  pkg/operation/botanist/cleanup.go
Labels: needs/ok-to-test

#1463 Finalizers are written by gardener-controller-manager not gardener-apiserver
  pkg/controllermanager/controller/cloudprofile/cloudprofile_control.go
  pkg/controllermanager/controller/project/project_control.go
  pkg/controllermanager/controller/quota/quota_control.go
  pkg/controllermanager/controller/secretbinding/secretbinding_control.go
  pkg/controllermanager/controller/seed/seed_control.go
  pkg/controllermanager/controller/shoot/shoot_control.go
  pkg/registry/garden/cloudprofile/strategy.go
  pkg/registry/garden/project/strategy.go
  pkg/registry/garden/quota/strategy.go
  pkg/registry/garden/secretbinding/strategy.go
  pkg/registry/garden/seed/strategy.go
  pkg/registry/garden/shoot/strategy.go
Labels: needs/ok-to-test

#1466 Add monitoring configuration from provider specific components
  charts/seed-monitoring/charts/core/charts/prometheus/rules-tests/cloud-controller-manager.rules.test.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules-tests/machine-controller-manager.rules.test.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/cloud-controller-manager.rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/machine-controller-manager.rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/seed-monitoring/charts/grafana/dashboards/operators/cluster-overview-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/machine-controller-manager-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-control-plane-status-dashboard.json
  charts/seed-monitoring/charts/grafana/templates/grafana-dashboards-configmap.yaml
  charts/seed-monitoring/charts/grafana/values.yaml
  pkg/apis/core/v1alpha1/constants/types_constants.go
  pkg/operation/botanist/monitoring.go
Labels: needs/ok-to-test
