Repository gardener/gardener, pull requests merged in 2019-06, with the labels that each got.

#1057 Drop minikube requirements for local setup
  docs/development/local_setup.md
  example/30-cloudprofile-aws.yaml
  example/30-cloudprofile-azure.yaml
  example/30-cloudprofile-gcp.yaml
  example/30-cloudprofile-openstack.yaml
  hack/templates/resources/30-cloudprofile.yaml.tpl
Labels: needs/ok-to-test

#1058 Add force delete annotation on backupinfra resource
  pkg/apis/garden/validation/validation.go
  pkg/apis/garden/validation/validation_test.go
  pkg/controllermanager/controller/backupinfrastructure/backup_infrastructure_control.go
  pkg/operation/common/types.go
  pkg/registry/garden/backupinfrastructure/strategy.go
Labels: needs/ok-to-test

#1059 Fix issue that didn't respect whether reconciliation is permitted
  pkg/controllermanager/controller/shoot/shoot_control.go
Labels: needs/ok-to-test

#1045 Enhance, refactor and use retry handling
  pkg/client/kubernetes/pods.go
  pkg/client/kubernetes/types.go
  pkg/controllermanager/controller/backupinfrastructure/backup_infrastructure_control.go
  pkg/controllermanager/controller/project/project_control_reconcile.go
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/mock/gardener/kubernetes/mocks.go
  pkg/mock/gardener/utils/context/doc.go
  pkg/mock/gardener/utils/context/mocks.go
  pkg/mock/gardener/utils/doc.go
  pkg/mock/gardener/utils/funcs.go
  pkg/mock/gardener/utils/mocks.go
  pkg/mock/gardener/utils/retry/doc.go
  pkg/mock/gardener/utils/retry/funcs.go
  pkg/mock/gardener/utils/retry/mocks.go
  pkg/mock/go/context/mocks.go
  pkg/operation/botanist/cleaner.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/dns.go
  pkg/operation/botanist/waiter.go
  pkg/operation/hybridbotanist/cloud_config.go
  pkg/operation/operation.go
  pkg/operation/terraformer/terraformer.go
  pkg/operation/terraformer/waiter.go
  pkg/utils/context/context.go
  pkg/utils/context/types.go
  pkg/utils/flow/taskfn.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
  pkg/utils/retry.go
  pkg/utils/retry/alias.go
  pkg/utils/retry/retry.go
  pkg/utils/retry/retry_test.go
  pkg/utils/retry/types.go
  pkg/utils/retry_test.go
  test/integration/framework/plant_operations.go
  test/integration/framework/shoot_app.go
  test/integration/framework/shoot_operations.go
Labels: needs/ok-to-test

#1048 gardener.unprivileged PSP default seccomp profile
  charts/shoot-core/charts/podsecuritypolicies/templates/_defaults.tpl
  charts/shoot-core/charts/podsecuritypolicies/templates/unprivileged-psp.yaml
  charts/shoot-core/charts/podsecuritypolicies/values.yaml
Labels: area/security, component/gardener, kind/enhancement, platform/all, reviewed/ok-to-test, size/xs, topology/shoot

#1062 Fix potential nil pointer accessing LastOperation
  pkg/operation/hybridbotanist/cloud_config.go
Labels: needs/ok-to-test

#1060 Add BackupInfrastructure deletion annotation to test shoots
  .test-defs/cmd/create-shoot/helper.go
  .test-defs/cmd/create-shoot/main.go
Labels: needs/ok-to-test

#1049 Added fine grained scale down options for CA
  charts/seed-controlplane/charts/cluster-autoscaler/templates/deployment.yaml
  example/90-shoot-alicloud.yaml
  example/90-shoot-aws.yaml
  example/90-shoot-azure.yaml
  example/90-shoot-gcp.yaml
  example/90-shoot-openstack.yaml
  example/90-shoot-packet.yaml
  hack/templates/resources/90-shoot.yaml.tpl
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#1004 Extend Project with Viewers
  charts/garden-project/charts/project-rbac/templates/clusterrole-project-viewer.yaml
  charts/garden-project/charts/project-rbac/templates/clusterrolebinding-project-viewers.yaml
  charts/garden-project/charts/project-rbac/templates/rolebinding-project-viewers.yaml
  charts/garden-project/charts/project-rbac/values.yaml
  charts/gardener/charts/application/templates/rbac-user.yaml
  example/05-project-dev.yaml
  hack/templates/resources/05-project-dev.yaml.tpl
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/validation/validation.go
  pkg/apis/garden/validation/validation_test.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/controllermanager/controller/project/project_control_reconcile.go
  pkg/openapi/openapi_generated.go
  pkg/operation/common/types.go
Labels: needs/ok-to-test

#1043 Added script for etcd migration.
  hack/migrate-etcd
Labels: needs/ok-to-test

#1061 Added KUBELET_EXTRA_ARGS to kubelet service
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.service
Labels: needs/ok-to-test, reviewed/ok-to-test

#1063 Fix create-shoot test list of backupinfrastructure
  .test-defs/cmd/create-shoot/helper.go
  .test-defs/cmd/create-shoot/main.go
Labels: needs/ok-to-test

#1064 Allow to change the CPU manager policy of the kubelet
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet-config-file
  charts/seed-operatingsystemconfig/original/values.yaml
  example/90-shoot-alicloud.yaml
  example/90-shoot-aws.yaml
  example/90-shoot-azure.yaml
  example/90-shoot-gcp.yaml
  example/90-shoot-openstack.yaml
  example/90-shoot-packet.yaml
  hack/templates/resources/90-shoot.yaml.tpl
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/hybridbotanist/cloud_config.go
Labels: needs/ok-to-test

#1037 Project controller is reconciling on gcm update
  pkg/controllermanager/controller/project/project_control.go
Labels: component/gardener, kind/enhancement, needs/ok-to-test, platform/all, reviewed/lgtm, size/s, topology/garden

#1067 Fix kube-proxy init container
  charts/shoot-core/charts/kube-proxy/templates/kube-proxy-daemonset.yaml
Labels: area/networking, component/gardener, needs/ok-to-test, platform/all, topology/shoot

#916 Packet botanist
  charts/images.yaml
  charts/seed-controlplane/charts/csi-packet/Chart.yaml
  charts/seed-controlplane/charts/csi-packet/charts/utils-templates
  charts/seed-controlplane/charts/csi-packet/templates/controller.yaml
  charts/seed-controlplane/charts/csi-packet/values.yaml
  charts/seed-controlplane/charts/packet-cloud-controller-manager/Chart.yaml
  charts/seed-controlplane/charts/packet-cloud-controller-manager/charts/utils-templates
  charts/seed-controlplane/charts/packet-cloud-controller-manager/templates/packet-ccm-deployment.yaml
  charts/seed-controlplane/charts/packet-cloud-controller-manager/values.yaml
  charts/shoot-core/charts/csi-packet/Chart.yaml
  charts/shoot-core/charts/csi-packet/charts/utils-templates
  charts/shoot-core/charts/csi-packet/templates/credential-secret.yaml
  charts/shoot-core/charts/csi-packet/templates/node.yaml
  charts/shoot-core/charts/csi-packet/templates/setup.yaml
  charts/shoot-core/charts/csi-packet/values.yaml
  charts/shoot-core/charts/vpn-shoot/templates/deployment.yaml
  charts/shoot-core/charts/vpn-shoot/values.yaml
  charts/shoot-core/values.yaml
  docs/development/new-cloud-provider-botanist.md
  docs/usage/supported_k8s_versions.md
  example/30-cloudprofile-packet.yaml
  example/50-seed-packet.yaml
  example/90-shoot-packet.yaml
  hack/templates/resources/30-cloudprofile.yaml.tpl
  hack/templates/resources/50-seed.yaml.tpl
  hack/templates/resources/90-shoot.yaml.tpl
  pkg/migration/infrastructure.go
  pkg/migration/packet.go
  pkg/operation/cloudbotanist/cloudbotanist.go
  pkg/operation/cloudbotanist/packetbotanist/addons.go
  pkg/operation/cloudbotanist/packetbotanist/cloud_config.go
  pkg/operation/cloudbotanist/packetbotanist/controlplane.go
  pkg/operation/cloudbotanist/packetbotanist/infrastructure.go
  pkg/operation/cloudbotanist/packetbotanist/packetbotanist.go
  pkg/operation/cloudbotanist/packetbotanist/types.go
  pkg/operation/common/types.go
  pkg/operation/shoot/shoot.go
Labels: area/open-source, exp/expert, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, size/l, status/author-action

#1038 Cleanup orphan etcd main PVC due to recent migration
  charts/seed-controlplane/charts/etcd/templates/configmap-etcd-bootstrap.yaml
  charts/seed-controlplane/charts/etcd/templates/etcd-statefulset.yaml
  charts/seed-controlplane/charts/etcd/values.yaml
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/cleanup.go
  pkg/operation/cloudbotanist/alicloudbotanist/controlplane.go
  pkg/operation/cloudbotanist/awsbotanist/controlplane.go
  pkg/operation/cloudbotanist/azurebotanist/controlplane.go
  pkg/operation/cloudbotanist/gcpbotanist/controlplane.go
  pkg/operation/cloudbotanist/openstackbotanist/controlplane.go
  pkg/operation/hybridbotanist/controlplane.go
Labels: needs/ok-to-test

#1068 Fix Shoot & Seed reconciliation
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/seed/seed.go
  pkg/controllermanager/controller/seed/seed_control.go
  pkg/controllermanager/controller/shoot/seed_control.go
  pkg/controllermanager/controller/shoot/shoot.go
  pkg/controllermanager/controller/shoot/shoot_control.go
  pkg/controllermanager/controller/shoot/shoot_control_types.go
  pkg/controllermanager/controller/shoot/shoot_utils.go
  pkg/openapi/openapi_generated.go
  pkg/utils/kubernetes/health/health.go
  pkg/utils/kubernetes/health/health_test.go
  pkg/utils/reconcilescheduler/reason.go
  pkg/utils/reconcilescheduler/reason_test.go
  pkg/utils/reconcilescheduler/reconcilescheduler_suite_test.go
  pkg/utils/reconcilescheduler/state.go
  pkg/utils/reconcilescheduler/state_test.go
Labels: needs/ok-to-test

#1069 etcd-main emits extensive (histogram) metrics.
  charts/seed-controlplane/charts/etcd/templates/configmap-etcd-bootstrap.yaml
  charts/seed-controlplane/charts/etcd/values.yaml
  charts/seed-monitoring/charts/prometheus/values.yaml
  pkg/operation/hybridbotanist/controlplane.go
Labels: needs/ok-to-test

#1071 Wait for deletion of Extension resources
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
Labels: component/gardener, kind/bug, needs/ok-to-test, platform/all, priority/normal, size/xs, topology/seed, topology/shoot

#1072 Fix care control to requeue unscheduled Shoots
  pkg/controllermanager/controller/shoot/shoot_care_control.go
Labels: component/gardener, kind/bug, needs/ok-to-test, platform/all, priority/normal, size/xs, topology/garden

#1077 read /etc/hostname when overriding hostname
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.service
  docs/proposals/01-extensibility.md
Labels: needs/ok-to-test

#1078 Increased the limits for seed kube-apiserver.
  pkg/operation/hybridbotanist/controlplane.go
Labels: needs/ok-to-test

#1080 Fix when to wait for infrastructures
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
Labels: needs/ok-to-test

#961 Enable kube-proxy cleanup
  pkg/apis/garden/validation/validation.go
  pkg/apis/garden/validation/validation_test.go
  pkg/operation/shoot/shoot_test.go
Labels: area/networking, needs/ok-to-test, platform/all, priority/normal, size/s, status/under-investigation

#1082 Default Nodes CIDR only when there is one worker group
  pkg/apis/garden/v1beta1/defaults.go
  pkg/apis/garden/v1beta1/defaults_test.go
  pkg/apis/garden/v1beta1/v1beta1_suite_test.go
Labels: component/gardener, kind/api-change, kind/bug, needs/ok-to-test, platform/all

#1081 Make metadata service IP part of the seed configuration
  charts/global-network-policies/templates/allow-to-blocked-cidrs.yaml
  charts/global-network-policies/templates/allow-to-public-networks.yaml
  charts/global-network-policies/templates/allow-to-seed-apiserver.yaml
  charts/global-network-policies/values.yaml
  charts/seed-controlplane/charts/kube-controller-manager/templates/kube-controller-manager.yaml
  charts/seed-controlplane/charts/network-policies/templates/allow-to-shoot-networks.yaml
  charts/seed-controlplane/charts/network-policies/values.yaml
  example/50-seed-alicloud.yaml
  example/50-seed-aws.yaml
  example/50-seed-azure.yaml
  example/50-seed-gcp.yaml
  example/50-seed-openstack.yaml
  example/50-seed-packet.yaml
  hack/templates/resources/50-seed.yaml.tpl
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/helper/helpers.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/botanist.go
  pkg/operation/cloudbotanist/alicloudbotanist/controlplane.go
  pkg/operation/cloudbotanist/awsbotanist/controlplane.go
  pkg/operation/cloudbotanist/azurebotanist/controlplane.go
  pkg/operation/cloudbotanist/gcpbotanist/controlplane.go
  pkg/operation/cloudbotanist/openstackbotanist/controlplane.go
  pkg/operation/cloudbotanist/packetbotanist/controlplane.go
  pkg/operation/cloudbotanist/types.go
  pkg/operation/hybridbotanist/controlplane.go
  test/integration/framework/networkpolicies/agnostic.go
  test/integration/seeds/networkpolicies/aws/networkpolicy_aws_test.go
  test/integration/seeds/networkpolicies/azure/networkpolicy_azure_test.go
  test/integration/seeds/networkpolicies/gcp/networkpolicy_gcp_test.go
  test/integration/seeds/networkpolicies/openstack/networkpolicy_openstack_test.go
Labels: needs/ok-to-test

#1084 Fix tm test for shoot creation
  .test-defs/cmd/create-shoot/main.go
  .test-defs/cmd/helper.go
Labels: needs/ok-to-test

#1083 Hotfix: allow delete of shoot when it is not scheduled yet
  pkg/controllermanager/controller/shoot/shoot_control.go
Labels: needs/ok-to-test

#1088 [ci:component:github.com/gardener/etcd-backup-restore:0.6.3->0.6.4]
  charts/images.yaml
Labels: needs/ok-to-test

#1085 Add all option for installing extensions
  hack/dev-setup-extensions
Labels: needs/ok-to-test

#1086 Always deploy the user monitoring stack
  pkg/apis/garden/v1beta1/helper/helpers.go
  pkg/operation/botanist/botanist_suite_test.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/secrets.go
  pkg/operation/common/types.go
  pkg/operation/operation.go
  pkg/operation/shoot/types.go
  test/integration/seeds/networkpolicies/aws/networkpolicy_aws_test.go
  test/integration/seeds/networkpolicies/azure/networkpolicy_azure_test.go
  test/integration/seeds/networkpolicies/gcp/networkpolicy_gcp_test.go
  test/integration/seeds/networkpolicies/openstack/networkpolicy_openstack_test.go
Labels: needs/ok-to-test

#1087 Expose etcd-backup-restore metrics to prometheus
  charts/seed-controlplane/charts/etcd/templates/allow-from-apiserver-network-policy.yaml
  charts/seed-controlplane/charts/etcd/templates/etcd-client-service.yaml
  charts/seed-controlplane/charts/etcd/values.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
Labels: needs/ok-to-test

#1090 Network policies are created last
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
Labels: area/control-plane, area/networking, area/security, component/gardener, reviewed/ok-to-test, topology/seed

#1092 Add vpa-exporter to prometheus network policy
  charts/seed-monitoring/charts/core/charts/prometheus/templates/allow-prometheus-network-policy.yaml
Labels: needs/ok-to-test

#851 Preparation for еxposing Kibana
  Gopkg.lock
  Gopkg.toml
  charts/images.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/temp.txt
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/curator-es/curator-configmap.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/_init-containers.tpl
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/configmap.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/searchguard-configmap.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/service.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/statefulset.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-configmap.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-deployment.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-ingress-auth-secret.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-ingress.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-logging-network-policy.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-objects-registration-config.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/values.yaml
  charts/seed-bootstrap/charts/fluentd-es/templates/fluent-bit-configmap.yaml
  charts/seed-bootstrap/charts/fluentd-es/templates/fluentd-es-configmap.yaml
  charts/seed-bootstrap/values.yaml
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/secrets.go
  pkg/operation/common/types.go
  pkg/operation/seed/seed.go
  pkg/utils/encoding.go
  pkg/utils/secrets/basic_auth.go
  pkg/utils/secrets/certificates.go
  test/integration/framework/shoot_app.go
  test/integration/framework/utils.go
  test/integration/shoots/applications/shoot_app_test.go
  vendor/golang.org/x/crypto/bcrypt/base64.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/golang.org/x/crypto/blowfish/block.go
  vendor/golang.org/x/crypto/blowfish/cipher.go
  vendor/golang.org/x/crypto/blowfish/const.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/transport.go
Labels: area/logging, area/security, exp/expert, kind/enhancement, needs/changes, needs/ok-to-test, needs/review, needs/second-opinion, platform/all, priority/normal, size/xl, status/author-action, status/in-progress, status/under-investigation, topology/seed

#1091 Use alpine image with iptables pre-installed for prometheus and kube-apiserver
  charts/images.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  pkg/operation/botanist/controlplane.go
  pkg/operation/common/types.go
  pkg/operation/hybridbotanist/controlplane.go
Labels: needs/ok-to-test

#1093 Remove unused temp file
  charts/seed-bootstrap/charts/elastic-kibana-curator/temp.txt
Labels: needs/ok-to-test

#1079 Add backup extension resources
  pkg/apis/extensions/v1alpha1/register.go
  pkg/apis/extensions/v1alpha1/types_backupbucket.go
  pkg/apis/extensions/v1alpha1/types_backupentry.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/backupbucket.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/backupentry.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/extensions_client.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_backupbucket.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_backupentry.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_extensions_client.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/generated_expansion.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/backupbucket.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/backupentry.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/interface.go
  pkg/client/extensions/informers/externalversions/generic.go
  pkg/client/extensions/listers/extensions/v1alpha1/backupbucket.go
  pkg/client/extensions/listers/extensions/v1alpha1/backupentry.go
  pkg/client/extensions/listers/extensions/v1alpha1/expansion_generated.go
Labels: needs/ok-to-test

#1097 Deploy `deny-all` network policy last.
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/operation/hybridbotanist/controlplane.go
Labels: needs/ok-to-test

#1098 [ci:component:github.com/gardener/terraformer:0.12.0->0.13.0]
  charts/images.yaml
Labels: needs/ok-to-test

#1099 Improve dashboards
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/seed-monitoring/charts/grafana/dashboards/operators/kubernetes-control-plane-status-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/shoot-nodes-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-control-plane-status-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-overview-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/shoot-nodes-dashboard.json
  charts/seed-monitoring/charts/grafana/templates/grafana-dashboards-configmap.yaml
Labels: needs/ok-to-test

#1101 NetworkPolicy e2e tests fixes
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-logging-network-policy.yaml
  charts/seed-controlplane/charts/deprecated-network-policies/templates/deprecated-kibana-logging-network-policy.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/allow-kube-apiserver-policy.yaml
  test/integration/framework/networkpolicies/alicloud.go
  test/integration/framework/networkpolicies/aws.go
  test/integration/framework/networkpolicies/azure.go
  test/integration/framework/networkpolicies/gcp.go
  test/integration/framework/networkpolicies/netpol-gen/generators/networkpolicies.go
  test/integration/framework/networkpolicies/openstack.go
  test/integration/framework/networkpolicies/shared_resources.go
  test/integration/framework/networkpolicies/types.go
  test/integration/framework/shoot_app.go
  test/integration/framework/types.go
  test/integration/seeds/networkpolicies/alicloud/networkpolicy_alicloud_test.go
  test/integration/seeds/networkpolicies/aws/networkpolicy_aws_test.go
  test/integration/seeds/networkpolicies/azure/networkpolicy_azure_test.go
  test/integration/seeds/networkpolicies/gcp/networkpolicy_gcp_test.go
  test/integration/seeds/networkpolicies/openstack/networkpolicy_openstack_test.go
Labels: area/networking, area/security, component/gardener, kind/regression, needs/ok-to-test, platform/all, size/xl, topology/seed

#1102 Add support for different machine image and version in tm tests
  .test-defs/cmd/create-shoot/main.go
  .test-defs/cmd/helper.go
Labels: needs/ok-to-test

#1105 Run seed policy tests in serial with 1 node
  .test-defs/SeedNetworkPoliciesTest.yaml
Labels: area/testing, needs/ok-to-test

#1104 Increase NetworkPolicy tests timeout
  test/integration/framework/networkpolicies/netpol-gen/generators/networkpolicies.go
  test/integration/seeds/networkpolicies/alicloud/networkpolicy_alicloud_test.go
  test/integration/seeds/networkpolicies/aws/networkpolicy_aws_test.go
  test/integration/seeds/networkpolicies/azure/networkpolicy_azure_test.go
  test/integration/seeds/networkpolicies/gcp/networkpolicy_gcp_test.go
  test/integration/seeds/networkpolicies/openstack/networkpolicy_openstack_test.go
Labels: area/networking, area/security, area/testing, component/gardener, needs/ok-to-test, size/s, topology/seed

#1095 Delete Extension Types with ControllerInstallation
  docs/extensions/cluster.md
  docs/extensions/extension.md
  docs/extensions/overview.md
  pkg/controllermanager/controller/controllerinstallation/controllerinstallation_control.go
Labels: component/gardener, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, size/s, topology/seed

#1103 Legacy policies are only added for `Reconcile` clusters.
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
Labels: needs/ok-to-test

#1110 Remove flaky seed-logging test from default tests
  .test-defs/SeedLoggingTest.yaml
  .test-defs/SeedNetworkPoliciesTest.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test

#1108 Fix elastic metrics-exporter
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/statefulset.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/values.yaml
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#1116 Fix regression of new controller runtime in shoot creation of tests
  .test-defs/cmd/helper.go
Labels: needs/ok-to-test

#1124 Added support for multi service dependancy watchdog.
  charts/images.yaml
  charts/seed-controlplane/charts/dependency-watchdog/templates/configmap.yaml
  charts/seed-controlplane/charts/dependency-watchdog/templates/deployment.yaml
  charts/seed-controlplane/charts/dependency-watchdog/templates/rbac.yaml
  charts/seed-controlplane/charts/dependency-watchdog/values.yaml
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#1121 Make backup extension resource cluster scoped
  pkg/apis/extensions/v1alpha1/types_backupbucket.go
  pkg/apis/extensions/v1alpha1/types_backupentry.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/backupbucket.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/backupentry.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/extensions_client.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_backupbucket.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_backupentry.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_extensions_client.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/backupbucket.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/backupentry.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/interface.go
  pkg/client/extensions/listers/extensions/v1alpha1/backupbucket.go
  pkg/client/extensions/listers/extensions/v1alpha1/backupentry.go
  pkg/client/extensions/listers/extensions/v1alpha1/expansion_generated.go
Labels: needs/ok-to-test

#1122 Add backup extension resources
  pkg/apis/extensions/v1alpha1/register.go
  pkg/apis/extensions/v1alpha1/types_backupbucket.go
  pkg/apis/extensions/v1alpha1/types_backupentry.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/backupbucket.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/backupentry.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/extensions_client.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_backupbucket.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_backupentry.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_extensions_client.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/generated_expansion.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/backupbucket.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/backupentry.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/interface.go
  pkg/client/extensions/informers/externalversions/generic.go
  pkg/client/extensions/listers/extensions/v1alpha1/backupbucket.go
  pkg/client/extensions/listers/extensions/v1alpha1/backupentry.go
  pkg/client/extensions/listers/extensions/v1alpha1/expansion_generated.go
Labels: reviewed/ok-to-test

#1113 Propagate usage of controller-runtime client
  example/30-cloudprofile-alicloud.yaml
  example/30-cloudprofile-aws.yaml
  example/30-cloudprofile-azure.yaml
  example/30-cloudprofile-gcp.yaml
  example/30-cloudprofile-openstack.yaml
  example/30-cloudprofile-packet.yaml
  example/90-shoot-alicloud.yaml
  example/90-shoot-aws.yaml
  example/90-shoot-azure.yaml
  example/90-shoot-gcp.yaml
  example/90-shoot-openstack.yaml
  example/90-shoot-packet.yaml
  hack/templates/resources/30-cloudprofile.yaml.tpl
  hack/templates/resources/90-shoot.yaml.tpl
  pkg/apis/garden/v1beta1/defaults_test.go
  pkg/client/kubernetes/types.go
  pkg/controllermanager/controller/backupinfrastructure/backup_infrastructure_control.go
  pkg/controllermanager/controller/project/project_control_delete.go
  pkg/controllermanager/controller/project/project_control_reconcile.go
  pkg/controllermanager/controller/secretbinding/secretbinding_control.go
  pkg/controllermanager/controller/seed/seed_control.go
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/controllermanager/server/handlers/metrics.go
  pkg/controllermanager/server/handlers/webhooks/validate_namespace_deletion.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/garbage_collection.go
  pkg/operation/cloudbotanist/packetbotanist/infrastructure.go
  pkg/operation/common/utils.go
  pkg/operation/seed/seed.go
  pkg/operation/shoot/shoot.go
  pkg/operation/terraformer/terraform_test.go
  test/integration/framework/utils.go
Labels: needs/ok-to-test

#1094 Reconcile shoots only during maintenance time
  Gopkg.lock
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/apis/core/v1alpha1/helper/errors.go
  pkg/apis/garden/v1beta1/types.go
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
  pkg/controllermanager/controller/backupinfrastructure/backup_infrastructure.go
  pkg/controllermanager/controller/cloudprofile/cloudprofile.go
  pkg/controllermanager/controller/controllerinstallation/controllerinstallation.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration.go
  pkg/controllermanager/controller/plant/plant.go
  pkg/controllermanager/controller/project/project.go
  pkg/controllermanager/controller/quota/quota.go
  pkg/controllermanager/controller/secretbinding/secretbinding.go
  pkg/controllermanager/controller/seed/seed.go
  pkg/controllermanager/controller/shoot/shoot.go
  pkg/controllermanager/controller/shoot/shoot_care_control.go
  pkg/controllermanager/controller/shoot/shoot_control.go
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/controllermanager/controller/shoot/shoot_quota_control.go
  pkg/controllermanager/controller/shoot/shoot_utils.go
  pkg/controllermanager/controller/utils/pointers.go
  pkg/controllermanager/controller/utils/pointers_test.go
  pkg/controllermanager/controller/utils/worker.go
  pkg/logger/logger.go
  pkg/logger/logger_test.go
  pkg/operation/common/utils.go
  pkg/operation/common/utils_test.go
  pkg/operation/hybridbotanist/cloud_config.go
  pkg/scheduler/controller/scheduler.go
  pkg/utils/errors/errors.go
  pkg/utils/errors/errors_test.go
  pkg/utils/timewindow.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
Labels: needs/ok-to-test

#1120 Fix calico kube-controllers PSP
  charts/shoot-core/charts/calico/templates/calico.yaml
  charts/shoot-core/charts/calico/templates/psp/calico-kube-controllers-clusterrole.yaml
  charts/shoot-core/charts/calico/templates/psp/calico-kube-controllers-clusterrolebinding.yaml
  charts/shoot-core/charts/calico/templates/psp/calico-kube-controllers-psp.yaml
Labels: needs/ok-to-test

#1129 Add system-component label to calico-kube-controllers deployment
  charts/shoot-core/charts/calico/templates/calico.yaml
Labels: needs/ok-to-test

#1125 Enhance `lastError` with timestamp
  charts/seed-bootstrap/templates/extensions/crd-controlplane.yaml
  charts/seed-bootstrap/templates/extensions/crd-extension.yaml
  charts/seed-bootstrap/templates/extensions/crd-operatingsystemconfig.yaml
  pkg/apis/core/types_common.go
  pkg/apis/core/v1alpha1/helper/errors.go
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/controllermanager/controller/backupinfrastructure/backup_infrastructure_control.go
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/controllermanager/controller/shoot/shoot_utils.go
  pkg/openapi/openapi_generated.go
Labels: needs/ok-to-test

#1130 Enhance chart utils with rendering functionality
  pkg/utils/chart/chart.go
Labels: needs/ok-to-test

#1133 Improve gardener create shoot test
  test/integration/framework/shoot_operations.go
  test/integration/framework/utils.go
Labels: needs/ok-to-test

#1127 Support for Kubernetes v1.15
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver.yaml
  charts/seed-controlplane/charts/kube-controller-manager/templates/kube-controller-manager.yaml
  charts/seed-controlplane/charts/kube-scheduler/templates/kube-scheduler.yaml
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet-config-file
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.flags
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.service
  charts/shoot-core/charts/coredns/values.yaml
  charts/shoot-core/charts/kube-proxy/templates/kube-proxy-daemonset.yaml
  docs/usage/supported_k8s_versions.md
  example/30-cloudprofile-alicloud.yaml
  example/30-cloudprofile-aws.yaml
  example/30-cloudprofile-azure.yaml
  example/30-cloudprofile-gcp.yaml
  example/30-cloudprofile-openstack.yaml
  example/30-cloudprofile-packet.yaml
  example/90-shoot-alicloud.yaml
  example/90-shoot-aws.yaml
  example/90-shoot-azure.yaml
  example/90-shoot-gcp.yaml
  example/90-shoot-openstack.yaml
  example/90-shoot-packet.yaml
  hack/templates/resources/30-cloudprofile.yaml.tpl
  hack/templates/resources/90-shoot.yaml.tpl
  pkg/client/kubernetes/client.go
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
Labels: needs/ok-to-test

#1136 Fix cleanup nil pointer
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
Labels: needs/ok-to-test

#1141 Add godoc badge
  README.md
Labels: needs/ok-to-test

#1139 Add integration test for gardener rbac
  .test-defs/RBACTest.yaml
  test/integration/framework/utils.go
  test/integration/gardener/rbac/gardener_rbac_suite_test.go
  test/integration/gardener/rbac/gardener_rbac_test.go
Labels: needs/ok-to-test

#1145 Moving imagevector related method to its package
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/factory_test.go
  pkg/utils/imagevector/imagevector.go
Labels: needs/ok-to-test

#1144 Remove network policy migration
  charts/seed-controlplane/charts/deprecated-network-policies/Chart.yaml
  charts/seed-controlplane/charts/deprecated-network-policies/charts/utils-templates
  charts/seed-controlplane/charts/deprecated-network-policies/templates/deprecated-apiserver-network-policy.yaml
  charts/seed-controlplane/charts/deprecated-network-policies/templates/deprecated-kibana-logging-network-policy.yaml
  charts/seed-controlplane/charts/deprecated-network-policies/templates/deprecated-network-policy-app.yaml
  charts/seed-controlplane/charts/deprecated-network-policies/templates/deprecated-network-policy-role.yaml
  charts/seed-controlplane/charts/deprecated-network-policies/values.yaml
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/hybridbotanist/controlplane.go
Labels: area/control-plane, area/networking, area/security, component/gardener, kind/cleanup, needs/ok-to-test, size/l, topology/seed

#1134 Cleanup the code for etcd old pvc deletion
  pkg/operation/botanist/cleanup.go
  pkg/operation/botanist/waiter.go
Labels: needs/ok-to-test

#1148 Add calico-kube-controller deployment to shoot care health check
  pkg/operation/botanist/botanist_suite_test.go
  pkg/operation/common/types.go
  test/integration/framework/networkpolicies/netpol-gen/generators/networkpolicies.go
  test/integration/seeds/networkpolicies/alicloud/networkpolicy_alicloud_test.go
  test/integration/seeds/networkpolicies/aws/networkpolicy_aws_test.go
  test/integration/seeds/networkpolicies/azure/networkpolicy_azure_test.go
  test/integration/seeds/networkpolicies/gcp/networkpolicy_gcp_test.go
  test/integration/seeds/networkpolicies/openstack/networkpolicy_openstack_test.go
Labels: needs/ok-to-test

#1147 improve rbac test with retry handling
  test/integration/gardener/rbac/gardener_rbac_test.go
Labels: area/testing, needs/ok-to-test, size/s

#1149 Adapt Network extension API
  pkg/apis/extensions/v1alpha1/types_network.go
Labels: needs/ok-to-test

#1152 Remove docs/usage/shoots.md
  docs/README.md
  docs/usage/shoots.md
Labels: needs/ok-to-test

#1131 Add apiserver audit to monitoring
  charts/seed-monitoring/charts/core/charts/prometheus/rules-tests/kube-apiserver.rules.test.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-apiserver.rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/seed-monitoring/charts/grafana/dashboards/operators/kubernetes-cluster-health-dashboard.json
Labels: needs/ok-to-test

#1153 Improve the audit related alert rule description
  charts/seed-monitoring/charts/core/charts/prometheus/rules-tests/kube-apiserver.rules.test.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-apiserver.rules.yaml
Labels: needs/ok-to-test

#1140 Clean up deprecated kubernetes methods
  pkg/apis/core/v1alpha1/helper/helpers_test.go
  pkg/apis/garden/helper/helpers.go
  pkg/apis/garden/v1beta1/helper/helpers_test.go
  pkg/client/kubernetes/client.go
  pkg/client/kubernetes/configmaps.go
  pkg/client/kubernetes/cronjobs.go
  pkg/client/kubernetes/daemonsets.go
  pkg/client/kubernetes/deployments.go
  pkg/client/kubernetes/horizontalpodautoscaler.go
  pkg/client/kubernetes/ingresses.go
  pkg/client/kubernetes/jobs.go
  pkg/client/kubernetes/namespaces.go
  pkg/client/kubernetes/networkpolicies.go
  pkg/client/kubernetes/nodes.go
  pkg/client/kubernetes/pods.go
  pkg/client/kubernetes/rbac.go
  pkg/client/kubernetes/replicasets.go
  pkg/client/kubernetes/secrets.go
  pkg/client/kubernetes/serviceaccounts.go
  pkg/client/kubernetes/services.go
  pkg/client/kubernetes/statefulsets.go
  pkg/client/kubernetes/types.go
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
  pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
  pkg/mock/gardener/kubernetes/mocks.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/waiter.go
  pkg/operation/garden/garden.go
  pkg/operation/hybridbotanist/addons.go
  pkg/operation/hybridbotanist/cloud_config.go
  pkg/operation/hybridbotanist/controlplane.go
  pkg/operation/operation.go
  pkg/operation/shoot/shoot_test.go
  pkg/utils/secrets/certificates.go
  pkg/utils/secrets/generate.go
  test/integration/framework/networkpolicies/netpol-gen/generators/networkpolicies.go
  test/integration/framework/networkpolicies/rule_builder_test.go
  test/integration/framework/networkpolicies/types.go
  test/integration/framework/networkpolicies/types_test.go
  test/integration/seeds/networkpolicies/alicloud/networkpolicy_alicloud_test.go
  test/integration/seeds/networkpolicies/aws/networkpolicy_aws_test.go
  test/integration/seeds/networkpolicies/azure/networkpolicy_azure_test.go
  test/integration/seeds/networkpolicies/gcp/networkpolicy_gcp_test.go
  test/integration/seeds/networkpolicies/openstack/networkpolicy_openstack_test.go
Labels: needs/ok-to-test
