Repository gardener/gardener, pull requests merged in 2019-10, with the labels that each got.

#1477 Fix small grammatical errors in readme
  README.md
Labels: needs/ok-to-test

#1475 Enable detailed metrics for HVPA
  charts/seed-bootstrap/charts/hvpa/templates/controller-deployment.yaml
Labels: needs/ok-to-test

#1479 [ci:component:github.com/gardener/autoscaler:0.5.0->0.6.0]
  charts/images.yaml
Labels: needs/ok-to-test

#1481 Remove deprecated seed-terraformer chart
  charts/seed-terraformer/Chart.yaml
  charts/seed-terraformer/charts/alicloud-backup/Chart.yaml
  charts/seed-terraformer/charts/alicloud-backup/charts/terraformer-common
  charts/seed-terraformer/charts/alicloud-backup/templates/_main.tf
  charts/seed-terraformer/charts/alicloud-backup/templates/_terraform.tfvars
  charts/seed-terraformer/charts/alicloud-backup/templates/_variables.tf
  charts/seed-terraformer/charts/alicloud-backup/templates/config.yaml
  charts/seed-terraformer/charts/alicloud-backup/values.yaml
  charts/seed-terraformer/charts/aws-backup/Chart.yaml
  charts/seed-terraformer/charts/aws-backup/charts/terraformer-common
  charts/seed-terraformer/charts/aws-backup/templates/_main.tf
  charts/seed-terraformer/charts/aws-backup/templates/_terraform.tfvars
  charts/seed-terraformer/charts/aws-backup/templates/_variables.tf
  charts/seed-terraformer/charts/aws-backup/templates/config.yaml
  charts/seed-terraformer/charts/aws-backup/values.yaml
  charts/seed-terraformer/charts/aws-kube2iam/Chart.yaml
  charts/seed-terraformer/charts/aws-kube2iam/charts/terraformer-common
  charts/seed-terraformer/charts/aws-kube2iam/templates/_main.tf
  charts/seed-terraformer/charts/aws-kube2iam/templates/_terraform.tfvars
  charts/seed-terraformer/charts/aws-kube2iam/templates/_variables.tf
  charts/seed-terraformer/charts/aws-kube2iam/templates/config.yaml
  charts/seed-terraformer/charts/aws-kube2iam/values.yaml
  charts/seed-terraformer/charts/azure-backup/Chart.yaml
  charts/seed-terraformer/charts/azure-backup/charts/terraformer-common
  charts/seed-terraformer/charts/azure-backup/templates/_main.tf
  charts/seed-terraformer/charts/azure-backup/templates/_terraform.tfvars
  charts/seed-terraformer/charts/azure-backup/templates/_variables.tf
  charts/seed-terraformer/charts/azure-backup/templates/config.yaml
  charts/seed-terraformer/charts/azure-backup/values.yaml
  charts/seed-terraformer/charts/gcp-backup/Chart.yaml
  charts/seed-terraformer/charts/gcp-backup/charts/terraformer-common
  charts/seed-terraformer/charts/gcp-backup/templates/_main.tf
  charts/seed-terraformer/charts/gcp-backup/templates/_terraform.tfvars
  charts/seed-terraformer/charts/gcp-backup/templates/_variables.tf
  charts/seed-terraformer/charts/gcp-backup/templates/config.yaml
  charts/seed-terraformer/charts/gcp-backup/values.yaml
  charts/seed-terraformer/charts/openstack-backup/Chart.yaml
  charts/seed-terraformer/charts/openstack-backup/charts/terraformer-common
  charts/seed-terraformer/charts/openstack-backup/templates/_main.tf
  charts/seed-terraformer/charts/openstack-backup/templates/_terraform.tfvars
  charts/seed-terraformer/charts/openstack-backup/templates/_variables.tf
  charts/seed-terraformer/charts/openstack-backup/templates/config.yaml
  charts/seed-terraformer/charts/openstack-backup/values.yaml
  charts/seed-terraformer/charts/terraformer-common/Chart.yaml
  charts/seed-terraformer/charts/terraformer-common/charts/utils-templates
  charts/seed-terraformer/charts/terraformer-common/templates/config.yaml
  pkg/operation/common/types.go
  pkg/operation/operation.go
Labels: needs/ok-to-test

#1480 Add support for terraform state v4
  pkg/operation/common/types.go
  pkg/operation/terraformer/state.go
  pkg/operation/terraformer/terraform_test.go
Labels: needs/ok-to-test

#1478 Fix monitoring regression
  charts/seed-bootstrap/templates/aggregate-prometheus/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/apiserver-connectivity-check.rules.yaml
Labels: needs/ok-to-test

#1486 Use metrics-server 0.3.1 for 1.10.x clusters
  charts/images.yaml
Labels: reviewed/ok-to-test

#1485 Use metrics-server 0.3.1 for 1.10.x clusters
  charts/images.yaml
Labels: needs/ok-to-test

#1484 Extend testgrid coverage by adding kubernetes version 1.16
  README.md
Labels: needs/ok-to-test

#1487 Revert "Add OS user gardener to the VMs"
  charts/seed-operatingsystemconfig/downloader/templates/osc.yaml
  charts/seed-operatingsystemconfig/downloader/templates/scripts/_gardener-user.sh
Labels: needs/ok-to-test

#1489 Fix deletion of ControlPlane secrets
  pkg/utils/secrets/secrets.go
Labels: kind/bug, needs/ok-to-test

#1488 Fix deletion of unsuccessfully hibernated Shoot
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
Labels: needs/ok-to-test

#1490 Add backup extension resource documentation
  docs/extensions/backupbucket.md
  docs/extensions/backupentry.md
Labels: needs/ok-to-test

#1493 Prevent resource exhaustion when determin container id
  cmd/gardener-controller-manager/app/gardener_controller_manager.go
Labels: needs/ok-to-test

#1500 prevent nil pointer in shoot control delete
  pkg/controllermanager/controller/shoot/shoot_control_delete.go
Labels: needs/ok-to-test

#1499 respecting global machine image for v1beta1
  pkg/apis/garden/v1beta1/defaults.go
  pkg/apis/garden/v1beta1/defaults_test.go
Labels: needs/ok-to-test

#1497 Update generate monitoring doc script to return 0 if there are no changes
  .ci/generate_monitoring_docs
Labels: needs/ok-to-test

#1501 Fix deletion for stale Extensions
  pkg/operation/botanist/extension.go
Labels: needs/ok-to-test

#1502 Fix monitoring regression
  charts/seed-bootstrap/templates/aggregate-prometheus/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/apiserver-connectivity-check.rules.yaml
Labels: needs/ok-to-test

#1508 Fix Shoot resource finalization for Kubernetes < v1.14
  pkg/utils/kubernetes/client/client.go
  pkg/utils/kubernetes/client/client_test.go
Labels: needs/ok-to-test

#1504 Allow project members to manage terminal resources
  charts/gardener/charts/application/templates/rbac-user.yaml
Labels: needs/ok-to-test

#1503 Add alerts for etcd DB size limits
  charts/seed-monitoring/charts/core/charts/prometheus/rules-tests/kube-etcd3.rules.test.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-etcd3.rules.yaml
Labels: needs/ok-to-test

#1506 fix openstack conversion for volumes
  pkg/apis/garden/v1beta1/conversions.go
  pkg/apis/roundtrip_shoot_migration_test.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/oidc/applier_test.go
Labels: kind/bug, needs/ok-to-test

#1509 Fix setting the gardener finalizer in gcm and improve logs on error
  pkg/controllermanager/controller/cloudprofile/cloudprofile_control.go
  pkg/controllermanager/controller/project/project_control.go
  pkg/controllermanager/controller/quota/quota_control.go
  pkg/controllermanager/controller/secretbinding/secretbinding_control.go
  pkg/controllermanager/controller/seed/seed_control.go
  pkg/controllermanager/controller/shoot/shoot_control.go
Labels: needs/ok-to-test

#1512 Upgrade VPA to 0.6.3
  charts/images.yaml
  charts/seed-bootstrap/charts/vpa/templates/vpa-rbac.yaml
Labels: needs/ok-to-test

#1513 Add gardener user for SSH
  charts/seed-operatingsystemconfig/original/templates/gardener-user/_gardener-user-script
  charts/seed-operatingsystemconfig/original/templates/gardener-user/_gardener-user.service
  charts/seed-operatingsystemconfig/original/templates/osc.yaml
  pkg/apis/core/v1alpha1/constants/types_constants.go
Labels: needs/ok-to-test

#1505 Adapt v1beta1 api to support Azure zones and ServiceEndpoints
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/garden.md
  hack/api-reference/settings.md
  pkg/apis/core/v1alpha1/conversions.go
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/conversions.go
  pkg/apis/garden/v1beta1/helper/helpers.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/validation/validation.go
  pkg/apis/garden/validation/validation_test.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/apis/roundtrip_cloudprofile_migration_test.go
  pkg/apis/roundtrip_shoot_migration_test.go
  pkg/openapi/openapi_generated.go
  vendor/modules.txt
Labels: needs/ok-to-test, platform/az

#1518 Stabilize client initialization in tests and fix shootapp redis statefulset
  test/integration/framework/garden_operation.go
  test/integration/shoots/applications/shoot_app_test.go
Labels: needs/ok-to-test

#1519 Prevent `gardener` finalizer from being removed for existing shoots
  cmd/gardener-apiserver/app/gardener_apiserver.go
  pkg/apiserver/admission/initializer/initializer.go
  pkg/apiserver/admission/initializer/types.go
  pkg/client/kubernetes/client.go
  pkg/client/kubernetes/types.go
  pkg/mock/gardener/client/kubernetes/doc.go
  pkg/mock/gardener/client/kubernetes/mocks.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: needs/ok-to-test

#1521 Update to golang 1.13.3
  Dockerfile
Labels: needs/ok-to-test

#1522 Fix redis slave persistence for alicloud tests
  test/integration/shoots/applications/shoot_app_test.go
Labels: needs/ok-to-test

#1528 Downgrade helm to v2.14.3
  .ci/check
Labels: needs/ok-to-test

#1516 Add monitoring to shoot spec
  example/90-deprecated-shoot-alicloud.yaml
  example/90-deprecated-shoot-aws.yaml
  example/90-deprecated-shoot-azure.yaml
  example/90-deprecated-shoot-gcp.yaml
  example/90-deprecated-shoot-openstack.yaml
  example/90-deprecated-shoot-packet.yaml
  example/90-shoot.yaml
  hack/templates/resources/90-deprecated-shoot.yaml.tpl
  pkg/apis/core/v1alpha1/conversions.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/validation/validation.go
  pkg/apis/garden/validation/validation_test.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/operation.go
Labels: needs/ok-to-test

#1524 Enhance gardener user
  charts/seed-operatingsystemconfig/original/templates/gardener-user/_gardener-user-script
  charts/seed-operatingsystemconfig/original/values.yaml
  pkg/apis/core/v1alpha1/constants/types_constants.go
  pkg/operation/botanist/operatingsystemconfig.go
Labels: needs/ok-to-test

#1529 Add spec.seedName fieldSelector for v1alpha1 Shoot
  pkg/apis/core/v1alpha1/conversions.go
  pkg/apis/core/v1alpha1/register.go
  pkg/apis/garden/field_constants.go
  pkg/apis/garden/v1beta1/conversions.go
  pkg/registry/garden/shoot/storage/storage.go
  pkg/registry/garden/shoot/strategy.go
  pkg/registry/garden/shoot/strategy_test.go
Labels: needs/ok-to-test

#1492 Adding HVPA metrices to prometheus config
  charts/seed-bootstrap/charts/hvpa/templates/controller-deployment.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/allow-prometheus-network-policy.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  pkg/operation/botanist/monitoring.go
Labels: needs/ok-to-test

#1491 Etcd-druid integration proposal.
  docs/proposals/06-etcd-druid.md
  docs/proposals/druid_integration.png
Labels: needs/ok-to-test

#1532 Fix local dev setup
  hack/dev-setup-register-gardener
Labels: needs/ok-to-test

#1537 Delete old HPA/VPA resources of HVPA feature gate is enabled
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver-hpa.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver-vpa.yaml
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#1535 add VPA for cluster-autoscaler in seed control-plane
  charts/seed-controlplane/charts/cluster-autoscaler/templates/vpa.yaml
Labels: needs/ok-to-test

#1520 Forbid "stealing" default domains from other projects
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: needs/ok-to-test

#1539 Project Viewer and Member are now aggregated
  charts/gardener/charts/application/templates/rbac-user.yaml
Labels: area/security, component/gardener, needs/ok-to-test

#1527 Remove volume type conversion for OpenStack cloud profiles
  pkg/apis/core/v1alpha1/conversions.go
  pkg/apis/core/v1alpha1/types_cloudprofile.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/conversions.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/roundtrip_cloudprofile_migration_test.go
  pkg/openapi/openapi_generated.go
  plugin/pkg/shoot/quotavalidator/admission.go
  plugin/pkg/shoot/quotavalidator/admission_test.go
Labels: needs/ok-to-test

#1523 Enable extensions to contribute conditions to shoot health status conditions
  docs/README.md
  docs/extensions/backupbucket.md
  docs/extensions/backupentry.md
  docs/extensions/shoot-health-status-conditions.md
  pkg/api/extensions/accessor.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/extensions/v1alpha1/types.go
  pkg/apis/extensions/v1alpha1/types_defaults.go
  pkg/apis/garden/v1beta1/types.go
  pkg/operation/botanist/health_check.go
  pkg/utils/kubernetes/health/health.go
Labels: needs/ok-to-test

#1544 [ci:component:github.com/gardener/gardener-resource-manager:0.6.0->0.7.0]
  charts/images.yaml
Labels: reviewed/ok-to-test

#1545 Fix github.com/gardener/external-dns-management version
  go.mod
  vendor/modules.txt
Labels: needs/ok-to-test

#1549 Clean up workers network patch on Shoot update
  pkg/registry/garden/shoot/strategy.go
  pkg/registry/garden/shoot/strategy_test.go
Labels: needs/ok-to-test

#1550 Update vpa command line parameters
  charts/seed-bootstrap/charts/vpa/templates/recommender-deployment.yaml
  charts/seed-bootstrap/charts/vpa/templates/updater-deployment.yaml
  charts/seed-bootstrap/charts/vpa/templates/vpa-rbac.yaml
  charts/seed-bootstrap/values.yaml
  charts/seed-controlplane/charts/kube-controller-manager/templates/kube-controller-manager.yaml
  charts/seed-controlplane/charts/kube-controller-manager/values.yaml
  charts/seed-controlplane/charts/kube-scheduler/values.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#1541 Enable CoreDNS Customization
  charts/shoot-core/components/charts/coredns/templates/coredns-configmap.yaml
  charts/shoot-core/components/charts/coredns/templates/coredns-custom-configmap.yaml
  charts/shoot-core/components/charts/coredns/templates/coredns-deployment.yaml
  charts/shoot-core/components/charts/coredns/values.yaml
  docs/usage/custom-dns.md
Labels: needs/ok-to-test

#1547 Fix CRD finalization
  pkg/operation/botanist/cleanup.go
  pkg/utils/kubernetes/client/client.go
Labels: needs/ok-to-test

#1557 Increase terraformer memory limit
  pkg/operation/terraformer/config.go
  pkg/operation/terraformer/terraform_test.go
  pkg/operation/terraformer/terraformer.go
Labels: needs/ok-to-test

#1559 [release-0.30] Increase terraformer resource limits
  pkg/operation/terraformer/config.go
  pkg/operation/terraformer/terraform_test.go
  pkg/operation/terraformer/terraformer.go
Labels: needs/ok-to-test

#1553 Aggregate shoot node information
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-state-metrics.rules.yaml
Labels: needs/ok-to-test

#1525 Integrate node-problem-detector
  charts/images.yaml
  charts/shoot-core/components/charts/node-problem-detector/Chart.yaml
  charts/shoot-core/components/charts/node-problem-detector/README.md
  charts/shoot-core/components/charts/node-problem-detector/charts/util-templates
  charts/shoot-core/components/charts/node-problem-detector/templates/_helpers.tpl
  charts/shoot-core/components/charts/node-problem-detector/templates/clusterrole.yaml
  charts/shoot-core/components/charts/node-problem-detector/templates/clusterrolebinding.yaml
  charts/shoot-core/components/charts/node-problem-detector/templates/custom-config-configmap.yaml
  charts/shoot-core/components/charts/node-problem-detector/templates/daemonset.yaml
  charts/shoot-core/components/charts/node-problem-detector/templates/psp-clusterrole.yaml
  charts/shoot-core/components/charts/node-problem-detector/templates/psp-clusterrolebinding.yaml
  charts/shoot-core/components/charts/node-problem-detector/templates/psp.yaml
  charts/shoot-core/components/charts/node-problem-detector/templates/serviceaccount.yaml
  charts/shoot-core/components/charts/node-problem-detector/values.yaml
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/botanist_suite_test.go
  pkg/operation/common/types.go
Labels: needs/ok-to-test

#1552 Emit events on deletion of referenced gardener resources
  pkg/apis/core/v1alpha1/constants/types_constants.go
  pkg/controllermanager/controller/backupbucket/backup_bucket_reconciler.go
  pkg/controllermanager/controller/cloudprofile/cloudprofile.go
  pkg/controllermanager/controller/cloudprofile/cloudprofile_control.go
  pkg/controllermanager/controller/controllerregistration/seed_control.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/quota/quota_control.go
  pkg/controllermanager/controller/secretbinding/secretbinding_control.go
  pkg/controllermanager/controller/seed/seed_control.go
Labels: needs/ok-to-test

#1561 Only check for NPD if Gardener version at least 0.31
  pkg/operation/botanist/botanist_suite_test.go
  pkg/operation/botanist/health_check.go
Labels: needs/ok-to-test

#1551 Use cluster autoscaler friendly scheduling algorithm
  charts/seed-controlplane/charts/kube-scheduler/templates/componentconfig.yaml
  charts/seed-controlplane/charts/kube-scheduler/values.yaml
  pkg/operation/botanist/controlplane.go
Labels: area/control-plane, component/gardener, kind/enhancement, needs/ok-to-test, topology/seed, topology/shoot

#1563 Allow custom configuration for nginx-ingress addon
  charts/shoot-addons/charts/nginx-ingress/templates/controller-configmap.yaml
  charts/shoot-addons/charts/nginx-ingress/values.yaml
  example/90-deprecated-shoot-alicloud.yaml
  example/90-deprecated-shoot-aws.yaml
  example/90-deprecated-shoot-azure.yaml
  example/90-deprecated-shoot-gcp.yaml
  example/90-deprecated-shoot-openstack.yaml
  example/90-deprecated-shoot-packet.yaml
  example/90-shoot.yaml
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/garden.md
  hack/api-reference/settings.md
  hack/templates/resources/90-deprecated-shoot.yaml.tpl
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/garden/types.go
  pkg/apis/garden/v1beta1/types.go
  pkg/apis/garden/v1beta1/zz_generated.conversion.go
  pkg/apis/garden/v1beta1/zz_generated.deepcopy.go
  pkg/apis/garden/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/addons.go
Labels: needs/ok-to-test

#1569 Copy secret after reading from informer cache
  pkg/controllermanager/controller/secretbinding/secretbinding_control.go
Labels: needs/ok-to-test
