Repository gardener/gardener, pull requests merged in 2020-04, with the labels that each got.

#2121 Prevent shoot-flow when writing UID to status
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: needs/ok-to-test

#2122 [ci:component:github.com/gardener/etcd-druid:v0.1.10->v0.1.11]
  charts/images.yaml
  go.mod
  go.sum
  pkg/apis/extensions/v1alpha1/types_containerruntime.go
  pkg/operation/botanist/health_check_test.go
  pkg/operation/botanist/waiter.go
  pkg/utils/kubernetes/health/health.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: needs/ok-to-test

#2124 [ci:component:github.com/gardener/etcd-druid:v0.1.11->v0.1.12]
  charts/images.yaml
  charts/seed-bootstrap/charts/etcd-druid/templates/etcd-crd.yaml
  charts/seed-controlplane/charts/etcd/templates/etcd.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: needs/ok-to-test

#2111 Support for Kubernetes v1.18
  README.md
  charts/seed-bootstrap/charts/kube-state-metrics/templates/clusterrole.yaml
  charts/seed-bootstrap/templates/clusterrole-kube-state-metrics.yaml
  charts/seed-controlplane/charts/kube-scheduler/templates/_helpers.tpl
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/shoot-core/components/charts/node-problem-detector/templates/psp-clusterrole.yaml
  docs/usage/supported_k8s_versions.md
Labels: needs/ok-to-test

#2125 Bump version of nodeless garden cluster to v1.17.3
  docs/usage/supported_k8s_versions.md
  hack/local-garden/run-kube-apiserver
  hack/local-garden/run-kube-controller-manager
Labels: needs/ok-to-test

#2126 update kyma addon to kyma 1.11.0
  charts/shoot-addons-kyma/charts/kyma/values.yaml
Labels: reviewed/ok-to-test

#2127 Add missing RBAC for GSAC for containerruntimes
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/rbac.yaml
Labels: needs/ok-to-test

#2130 Confirm deletion for ContainerRuntime resources
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/containerruntime.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/infrastructure.go
  pkg/operation/botanist/network.go
  pkg/operation/botanist/worker.go
Labels: needs/ok-to-test

#2132 Fix validating webhook configuration for GSAC
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/validatingwebhookconfiguration.yaml
  example/seed-admission-controller/10-validatingwebhookconfiguration.yaml
Labels: needs/ok-to-test

#2134 Fix etcd .status.lastError wrapping
  charts/seed-bootstrap/prometheus-rules/recording-rules.rules.yaml
  charts/shoot-core/components/charts/node-problem-detector/templates/daemonset.yaml
  charts/shoot-core/components/charts/node-problem-detector/values.yaml
  pkg/operation/botanist/waiter.go
Labels: needs/ok-to-test

#2140 Add tests for FileContent func
  pkg/apis/core/validation/shoot.go
  pkg/chartrenderer/chartrenderer_suite_test.go
  pkg/chartrenderer/default_test.go
  pkg/chartrenderer/testdata/alpine/Chart.yaml
  pkg/chartrenderer/testdata/alpine/README.md
  pkg/chartrenderer/testdata/alpine/templates/alpine-pod.yaml
  pkg/chartrenderer/testdata/alpine/values.yaml
  pkg/gardenlet/controller/backupbucket/backup_bucket_actuator.go
Labels: needs/ok-to-test

#2135 Do not try to sync extension resources if cluster object cannot be found
  pkg/gardenlet/controller/federatedseed/shootstate/common_sync.go
  pkg/gardenlet/controller/federatedseed/shootstate/shootstate_sync_control.go
Labels: needs/ok-to-test

#2128 Change ContainerRuntime deployment
  charts/seed-bootstrap/templates/extensions/crd-containerruntime.yaml
  charts/seed-operatingsystemconfig/original/templates/containerd/_containerd-initializer.service
  charts/seed-operatingsystemconfig/original/templates/containerd/_containerd-require-initializer.yaml
  charts/seed-operatingsystemconfig/original/templates/containerd/_node-cri.labels
  charts/seed-operatingsystemconfig/original/templates/node/_node-cri.labels
  charts/seed-operatingsystemconfig/original/values.yaml
  docs/extensions/containerruntime.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/extensions/v1alpha1/types_containerruntime.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/operation/botanist/containerruntime.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/worker.go
Labels: needs/ok-to-test

#2148 Remove unused mock
  .golangci.yaml
  extensions/README.md
  hack/api-reference/extensions.md
  pkg/apis/core/validation/shoot_test.go
  pkg/mock/gardener/client/core/listers/core/v1alpha1/doc.go
  pkg/mock/gardener/client/core/listers/core/v1alpha1/mocks.go
Labels: needs/ok-to-test

#2150 Component descriptor script works for hyperkube
  hack/.ci/component_descriptor
Labels: needs/ok-to-test

#2152 check-generate.sh calls make rules
  Makefile
  hack/check-generate.sh
Labels: needs/ok-to-test

#2153 Add missing files from gardener/gardener-extensions@v1.6.1
  extensions/pkg/controller/csimigration/README.md
  extensions/pkg/controller/csimigration/controller.go
  extensions/pkg/controller/csimigration/csimigration_suite_test.go
  extensions/pkg/controller/csimigration/predicate.go
  extensions/pkg/controller/csimigration/predicate_test.go
  extensions/pkg/controller/csimigration/reconciler.go
  extensions/pkg/controller/csimigration/reconciler_test.go
  extensions/pkg/controller/csimigration/utils.go
  extensions/pkg/controller/csimigration/utils_test.go
  extensions/pkg/controller/healthcheck/reconciler.go
  extensions/pkg/controller/operatingsystemconfig/oscommon/README.md
  extensions/pkg/controller/utils.go
  extensions/pkg/controller/utils_test.go
  extensions/pkg/controller/worker/actuator.go
  extensions/pkg/controller/worker/controller.go
  extensions/pkg/controller/worker/genericactuator/actuator.go
  extensions/pkg/controller/worker/genericactuator/actuator_migrate.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  extensions/pkg/controller/worker/genericactuator/machine_controller_manager.go
  extensions/pkg/controller/worker/machines.go
  extensions/pkg/controller/worker/mapper.go
  extensions/pkg/controller/worker/mapper_test.go
  extensions/pkg/controller/worker/predicate.go
  extensions/pkg/controller/worker/predicate_test.go
  extensions/pkg/controller/worker/reconciler.go
  extensions/pkg/controller/worker/reconciler_test.go
  extensions/pkg/controller/worker/state_actuator.go
  extensions/pkg/controller/worker/state_reconciler.go
  extensions/pkg/handler/mapper.go
  extensions/pkg/predicate/predicate.go
  extensions/pkg/predicate/predicate_test.go
  extensions/pkg/version/version.go
  go.mod
  go.sum
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/compiler/reader.go
  vendor/github.com/googleapis/gnostic/extensions/COMPILE-EXTENSION.sh
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
  vendor/github.com/googleapis/gnostic/extensions/extension.proto
  vendor/modules.txt
Labels: needs/ok-to-test

#2154 Add ErrorCode Mapping for InUseSubnetCannotBeDeleted
  pkg/apis/core/v1beta1/helper/errors.go
Labels: reviewed/ok-to-test

#2142 adding CRI integration test for containerd
  test/framework/k8s_utils.go
  test/integration/shoots/operations/containerruntime.go
Labels: needs/ok-to-test, reviewed/ok-to-test

#2159 Make admission plugins configurable in gardener-apiserver chart
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/values.yaml
Labels: needs/ok-to-test

#2155 Make machine image optional
  hack/api-reference/core.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/helper/helper.go
  pkg/apis/core/v1alpha1/helper/helpers_test.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helpers_test.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_test.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/worker.go
  test/integration/framework/shoot_maintenance_operations.go
  test/integration/shoots/maintenance/maintenance_test.go
  test/integration/shoots/operations/worker.go
  test/system/shoot_creation/create_test.go
Labels: kind/bug, needs/ok-to-test

#2105 GEP 5 - introduce version classification, validation and admission
  go.mod
  go.sum
  hack/api-reference/core.md
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_cloudprofile.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/registry/core/cloudprofile/strategy.go
  plugin/pkg/plant/admission_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/telemetry/event/event.go
  vendor/golang.org/x/tools/internal/telemetry/event/export.go
  vendor/golang.org/x/tools/internal/telemetry/event/key.go
  vendor/golang.org/x/tools/internal/telemetry/event/label.go
  vendor/golang.org/x/tools/internal/telemetry/event/log.go
  vendor/golang.org/x/tools/internal/telemetry/event/metric.go
  vendor/golang.org/x/tools/internal/telemetry/event/tag.go
  vendor/golang.org/x/tools/internal/telemetry/event/trace.go
  vendor/modules.txt
Labels: needs/ok-to-test

#2161 Modify controllers to accept multiple OS types
  extensions/pkg/controller/operatingsystemconfig/oscommon/add.go
  extensions/pkg/controller/operatingsystemconfig/oscommon/app/app.go
  extensions/pkg/controller/operatingsystemconfig/oscommon/cmd/options.go
Labels: needs/ok-to-test

#2164 Fix prometheus-config-reloader failing to start
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus-vpa.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
Labels: area/monitoring, area/scalability, component/gardener, kind/bug, needs/ok-to-test

#2160 Added integration test for scale-to-zero feature of cluster autoscaler
  test/framework/resources/templates/reserve-capacity.yaml.tpl
  test/integration/shoots/operations/clusterautoscaler.go
Labels: needs/ok-to-test

#2166 Set Node Labels via Worker instead of kubelet-flags
  charts/seed-operatingsystemconfig/original/templates/containerd/_node-cri.labels
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.flags
  charts/seed-operatingsystemconfig/original/values.yaml
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/worker.go
Labels: needs/ok-to-test

#2165 refactor hack scripts for common usage in extensions
  hack/get-build-ld-flags.sh
  hack/local-development/common/helpers
  hack/local-development/common/local-imagevector-overwrite
  hack/local-development/common/tools.go
  hack/local-development/dev-setup-register-gardener
  hack/local-development/start-apiserver
  hack/local-development/start-controller-manager
  hack/local-development/start-gardenlet
  hack/local-development/start-scheduler
  hack/local-development/start-seed-admission-controller
Labels: needs/ok-to-test

#2172 fix make-dev-setup
  hack/local-development/dev-setup
  hack/local-development/dev-setup-register-gardener
Labels: needs/ok-to-test

#2174 Revert "Optimize apiserver HVPA minAllowed config."
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver-hvpa.yaml
Labels: area/control-plane, area/control-plane-auto-scaling, component/hvpa, reviewed/ok-to-test

#2176 Shoot controller waits until required extension ready
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/waiter.go
Labels: needs/ok-to-test

#2171 Add elastic-search-service-account
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/elasticsearch-logging-role-binding.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/elasticsearch-logging-role.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/elasticsearch-logging-service-account.yaml
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/statefulset.yaml
  pkg/operation/common/utils.go
Labels: needs/ok-to-test

#2177 Refactor create shoot test to make it reuseable
  test/framework/gardener_utils.go
  test/framework/shoot_utils.go
  test/framework/shootcreationframework.go
  test/framework/shootframework.go
  test/framework/worker_utils.go
  test/system/shoot_creation/create_test.go
Labels: needs/ok-to-test

#2162 Add providerConfig to Seed object
  docs/extensions/controllerregistration.md
  example/50-seed.yaml
  hack/api-reference/core.md
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_control.go
  pkg/openapi/openapi_generated.go
Labels: needs/ok-to-test

#2178 Enhance generic control plane mutator webhook
  extensions/pkg/webhook/controlplane/genericmutator/mutator.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator_test.go
  extensions/pkg/webhook/controlplane/genericmutator/noopensurer.go
  pkg/mock/gardener/extensions/webhook/controlplane/genericmutator/mocks.go
Labels: needs/ok-to-test

#2182 [ci:component:github.com/gardener/etcd-druid:v0.1.12->v0.1.13]
  charts/images.yaml
Labels: needs/ok-to-test

#2185 update etcd-druid to v0.1.13
  charts/images.yaml
Labels: needs/ok-to-test

#2187 [ci:component:github.com/gardener/etcd-druid:v0.1.13->v0.1.14]
  charts/images.yaml
Labels: needs/ok-to-test

#2190 [ci:component:github.com/gardener/etcd-druid:v0.1.14->v0.1.15]
  charts/images.yaml
Labels: needs/ok-to-test

#2191 [release-v1.2] Upgrade github.com/gardener/etcd-druid
  charts/images.yaml
Labels: needs/ok-to-test

#2183 Remove read-only from kinaba index
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/curator-es/curator-configmap.yaml
Labels: needs/ok-to-test

#2189 Add alert if backup sidecar metrics are not scrapped
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-etcd3.rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
Labels: needs/ok-to-test

#2194 Test/additional guestbook dump
  extensions/test/integration/operation/shoot_operation.go
  test/framework/applications/guestbooktest.go
  test/framework/dump.go
  test/framework/k8s_utils.go
  test/framework/shoot_utils.go
  test/integration/framework/common.go
  test/integration/framework/dump.go
  test/integration/framework/errors.go
  test/integration/framework/garden_operation.go
  test/integration/framework/helm_utils.go
  test/integration/framework/plant_operations.go
  test/integration/framework/scheduler_operations.go
  test/integration/framework/shoot_maintenance_operations.go
  test/integration/framework/shoot_operations.go
  test/integration/framework/types.go
  test/integration/framework/utils.go
  test/integration/framework/worker_operations.go
  test/integration/shoots/care/shoot_care.go
  test/integration/shoots/gingko_utils.go
  test/integration/shoots/operations/containerruntime.go
Labels: needs/ok-to-test

#2192 Test/systemctl segfault
  pkg/client/kubernetes/pods.go
  test/framework/applications/guestbooktest.go
  test/framework/k8s_utils.go
  test/framework/pod_executor.go
  test/framework/resources/templates/simple-load-deployment.yaml.tpl
  test/framework/resources/templates/templates.go
  test/framework/rootpod_executor.go
  test/framework/utils.go
  test/integration/framework/garden_operation.go
  test/integration/shoots/applications/networking.go
  test/integration/shoots/logging/seed_log.go
  test/integration/shoots/operatingsystem/os.go
  test/integration/shoots/operations/clusterautoscaler.go
  test/integration/shoots/operations/containerruntime.go
  test/suites/shoot/run_suite_test.go
Labels: needs/ok-to-test

#2198 Increase limits for metrics-server
  charts/shoot-core/components/charts/metrics-server/templates/deployment.yaml
Labels: needs/ok-to-test

#2199 Reduce Prometheus terminationGracePeriodSeconds to 60s.
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
Labels: needs/ok-to-test

#2195 care controller - Health check condition message
  extensions/pkg/controller/healthcheck/healtcheck_actuator.go
  pkg/operation/botanist/health_check.go
Labels: needs/ok-to-test

#2204 Edited rbac roles to include get,list,watch etcd resources by vpa actors
  charts/seed-bootstrap/charts/vpa/templates/vpa-rbac.yaml
Labels: needs/ok-to-test

#2201 Skip the containerd test for non-ubuntu worker pool
  example/05-project-dev.yaml
  test/framework/test_description.go
  test/framework/utils.go
  test/framework/utils_test.go
  test/integration/shoots/operations/containerruntime.go
Labels: kind/bug, needs/ok-to-test

#2200 respect http proxy settings in test framework utils
  test/framework/http_utils.go
Labels: needs/ok-to-test

#2106 [GEP-5] do not allow deletion of used Kubernetes and OS versions
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/global/resourcereferencemanager/admission_test.go
Labels: needs/ok-to-test

#2209 Revert "Add alert if backup sidecar metrics are not scarraped"
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-etcd3.rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
Labels: kind/bug, needs/ok-to-test

#2205 Ignore endpoints not reconciled by kcm during hibernation
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/waiter.go
Labels: needs/ok-to-test

#2214 Fix kubelet monitor script
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet-monitor.service
  charts/shoot-cloud-config/templates/scripts/_cloud-config-script.sh
Labels: needs/ok-to-test

#2213 Remove pod affinity from fluentd
  charts/seed-bootstrap/charts/fluentd-es/templates/fluentd-es-statefulset.yaml
Labels: needs/ok-to-test

#2212 Add error codes to conditions
  docs/extensions/shoot-health-status-conditions.md
  go.mod
  go.sum
  hack/api-reference/core.md
  pkg/apis/core/types_utils.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/helper/condition_builder.go
  pkg/apis/core/v1alpha1/helper/condition_builder_test.go
  pkg/apis/core/v1alpha1/helper/helper.go
  pkg/apis/core/v1alpha1/helper/helper_test.go
  pkg/apis/core/v1alpha1/types_utils.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/condition_builder.go
  pkg/apis/core/v1beta1/helper/condition_builder_test.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helpers_test.go
  pkg/apis/core/v1beta1/types_utils.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/health_check.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/golang.org/x/tools/internal/telemetry/event/event.go
  vendor/golang.org/x/tools/internal/telemetry/event/key.go
  vendor/golang.org/x/tools/internal/telemetry/event/log.go
  vendor/golang.org/x/tools/internal/telemetry/event/tag.go
  vendor/modules.txt
Labels: needs/ok-to-test

#2108 [GEP-5] Changes to the Shoot Maintenance Controller
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helpers_test.go
  pkg/controllermanager/controller/shoot/shoot_hibernation_control.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_test.go
  test/framework/worker_utils.go
  test/integration/framework/common.go
  test/integration/framework/shoot_maintenance_operations.go
  test/system/shoot_update/update_test.go
Labels: needs/ok-to-test

#2221 Update Kubernetes dashboard + metrics-scraper versions
  charts/images.yaml
Labels: needs/ok-to-test

#2223 Fix bug in CheckCSIConditions function
  extensions/pkg/controller/csimigration/utils.go
  extensions/pkg/controller/csimigration/utils_test.go
Labels: kind/bug, needs/ok-to-test

#2224 Add ContainerRuntime to extension healthcheck
  extensions/test/integration/healthcheck/healthcheck_operation.go
Labels: needs/ok-to-test

#2202 Adjust dashboards for grafana in garden ns
  charts/seed-bootstrap/dashboards/cluster-overview.json
  charts/seed-bootstrap/dashboards/extensions-dashboard.json
  charts/seed-bootstrap/dashboards/seed-resource-usage.json
Labels: needs/ok-to-test

#2215 Gardenlet detects outdated HealthCheck conditions
  charts/gardener/gardenlet/charts/runtime/templates/configmap-componentconfig.yaml
  charts/gardener/gardenlet/values.yaml
  example/20-componentconfig-gardenlet.yaml
  extensions/pkg/controller/healthcheck/healtcheck_actuator.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/health_check_test.go
Labels: needs/ok-to-test

#2229 Remove shoot tasks only if executed
  pkg/controllerutils/miscellaneous.go
  pkg/controllerutils/miscellaneous_test.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: kind/bug, needs/ok-to-test

#2219 Make extension handler ready for common usage
  extensions/pkg/predicate/predicate.go
  extensions/pkg/webhook/cmd/factory.go
  extensions/pkg/webhook/cmd/options.go
  extensions/pkg/webhook/controlplane/controlplane.go
  extensions/pkg/webhook/factory.go
  extensions/pkg/webhook/handler.go
  extensions/pkg/webhook/handler_shootclient.go
  extensions/pkg/webhook/handler_test.go
  extensions/pkg/webhook/mutator.go
  extensions/pkg/webhook/network/network.go
  extensions/pkg/webhook/shoot/shoot.go
  extensions/pkg/webhook/validator.go
  extensions/pkg/webhook/webhook.go
  pkg/api/core/accessor.go
  pkg/api/core/accessor_suite_test.go
  pkg/api/core/accessor_test.go
  pkg/apis/core/types.go
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/types_seed.go
  pkg/apis/core/types_shoot.go
Labels: needs/ok-to-test

#2167 Extend the infrastructure actuator interfece with Migrate and Restore
  extensions/pkg/controller/infrastructure/actuator.go
  extensions/pkg/controller/infrastructure/reconciler.go
  extensions/pkg/controller/reconciler.go
  extensions/pkg/controller/utils.go
  extensions/pkg/controller/utils_test.go
  extensions/pkg/terraformer/config.go
  extensions/pkg/terraformer/state.go
  extensions/pkg/terraformer/terraform_test.go
  extensions/pkg/terraformer/terraformer.go
  extensions/pkg/terraformer/types.go
  go.mod
  go.sum
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/mock/gardener/extensions/terraformer/mocks.go
Labels: needs/ok-to-test, reviewed/lgtm

#2222 Refactor interaction with extension CRs
  pkg/api/extensions/accessor.go
  pkg/apis/core/v1beta1/types_common.go
  pkg/apis/extensions/v1alpha1/types.go
  pkg/gardenlet/controller/backupbucket/backup_bucket_actuator.go
  pkg/gardenlet/controller/backupentry/backup_entry_actuator.go
  pkg/operation/botanist/containerruntime.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/infrastructure.go
  pkg/operation/botanist/network.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/worker.go
  pkg/operation/common/extensions.go
  pkg/utils/kubernetes/health/health.go
  pkg/utils/kubernetes/health/health_suite_test.go
  pkg/utils/kubernetes/health/health_test.go
Labels: kind/cleanup, needs/ok-to-test

#2235 Updated to Alpine 3.11.6
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm

#2230 Add backup restore policy documentation
  docs/README.md
  docs/concepts/backup-restore.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm

#2231 Fix the CRI label on the Shoot Node
  go.sum
  pkg/operation/botanist/worker.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/modules.txt
Labels: needs/ok-to-test

#2210 Create dedicated secrets of cloud-config for each worker group
  charts/shoot-cloud-config-rbac/Chart.yaml
  charts/shoot-cloud-config-rbac/charts/utils-templates
  charts/shoot-cloud-config-rbac/templates/clusterrolebinding-bootstrapper.yaml
  charts/shoot-cloud-config-rbac/templates/role-downloader.yaml
  charts/shoot-cloud-config-rbac/templates/rolebinding-downloader.yaml
  charts/shoot-cloud-config-rbac/values.yaml
  charts/shoot-cloud-config/templates/secret-cloud-config-data.yaml
  charts/shoot-cloud-config/values.yaml
  pkg/chartrenderer/default.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_control.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/operatingsystemconfig.go
Labels: kind/enhancement, needs/ok-to-test

#2239 Add ContainerRuntime resources to the care controller
  pkg/operation/botanist/health_check.go
Labels: needs/ok-to-test

#2237 Extend error code mapping
  pkg/apis/core/types_common.go
  pkg/apis/core/v1alpha1/helper/errors.go
  pkg/apis/core/v1alpha1/helper/errors_test.go
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/apis/core/v1beta1/helper/errors_test.go
  pkg/apis/core/v1beta1/types_common.go
Labels: needs/ok-to-test

#2243 Add PingCAP in adopters
  ADOPTERS.md
Labels: needs/ok-to-test

#2245 Update go version to 1.14 in go.mod
  go.mod
  vendor/modules.txt
Labels: needs/ok-to-test

#2246 Use GO111MODULE=off to prevent changes in go.mod
  Makefile
Labels: needs/ok-to-test

#2233 Confine shoot spec update rollout to maintenance
  docs/README.md
  docs/extensions/shoot-maintenance.md
  docs/usage/shoot_maintenance.md
  docs/usage/shoot_operations.md
  example/90-shoot.yaml
  hack/api-reference/core.md
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/openapi/openapi_generated.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: needs/ok-to-test

#2244 Eliminate useless extensionsv1alpha1.Last{Operation,Error} interfaces
  extensions/pkg/controller/healthcheck/reconciler.go
  extensions/pkg/controller/utils.go
  extensions/pkg/controller/worker/reconciler.go
  extensions/pkg/predicate/predicate.go
  hack/api-reference/extensions.md
  pkg/api/extensions/accessor.go
  pkg/api/extensions/accessor_test.go
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/core/v1beta1/types_common.go
  pkg/apis/extensions/v1alpha1/types.go
  pkg/apis/extensions/v1alpha1/types_defaults.go
  pkg/operation/common/extensions.go
  pkg/utils/kubernetes/health/health.go
  test/framework/dump.go
  test/integration/framework/dump.go
Labels: needs/ok-to-test

#2250 Nit: update gardener/etcd-druid version in go.mod
  go.mod
  go.sum
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/modules.txt
Labels: needs/ok-to-test

#2240 Wait for extension resources to be deleted
  pkg/operation/common/extensions.go
Labels: kind/bug, needs/ok-to-test

#2248 Respect error codes from extensions instead of recomputing them
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/apis/core/v1beta1/helper/errors_test.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/operation/botanist/cleanup.go
  pkg/operation/common/extensions.go
  pkg/utils/kubernetes/health/health.go
Labels: kind/enhancement, needs/ok-to-test

#2256 Fix panic during extension deletion
  pkg/operation/common/extensions.go
Labels: kind/bug, needs/ok-to-test

#2259 ShootState controller syncs ContainerRuntimes
  pkg/gardenlet/controller/federatedseed/shootstate/shootstate_sync_control.go
Labels: needs/ok-to-test

#2260 [ci:component:github.com/gardener/etcd-backup-restore:0.8.0->v0.9.0]
  charts/images.yaml
Labels: needs/ok-to-test

#2170 [GEP-11] API Server Proxy for Inverting Seed-to-Shoot Connectivity
  docs/README.md
  docs/proposals/11-apiserver-network-proxy.md
Labels: needs/ok-to-test

#2263 [ci:component:github.com/gardener/etcd-druid:v0.1.15->v0.2.0]
  charts/images.yaml
Labels: needs/ok-to-test

#2262 Remove etcd and etcd-backup-restore images
  charts/images.yaml
  charts/seed-controlplane/charts/etcd/templates/etcd.yaml
  charts/seed-controlplane/charts/etcd/values.yaml
  pkg/operation/botanist/controlplane.go
  pkg/operation/common/types.go
Labels: needs/ok-to-test

#2264 Add k8s v1.18 conformance tests to matrix
  README.md
Labels: needs/ok-to-test

#2268 fixed a typo
  README.md
Labels: needs/ok-to-test, reviewed/lgtm

#2236 Fix the default dns assignment issue of `metadata.generateName`
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, needs/ok-to-test

#2242 Health checker computes error codes where applicable
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/health_check_test.go
Labels: kind/enhancement, needs/ok-to-test

#2258 Skip infrastructure reconciliation for hibernated shoots
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/operation/botanist/infrastructure.go
Labels: needs/ok-to-test

#2247 Extend controller actuators for migrate and restore operations
  extensions/pkg/controller/backupentry/actuator.go
  extensions/pkg/controller/backupentry/genericactuator/actuator.go
  extensions/pkg/controller/backupentry/reconciler.go
  extensions/pkg/controller/controlplane/actuator.go
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/controller/controlplane/reconciler.go
  extensions/pkg/controller/operatingsystemconfig/actuator.go
  extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_migrate.go
  extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_restore.go
  extensions/pkg/controller/operatingsystemconfig/reconciler.go
Labels: kind/enhancement, needs/ok-to-test

#2267 remove blackbox exporter sidecar from API Server deployment
  charts/seed-controlplane/charts/kube-apiserver/templates/blackbox-exporter-config.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver-hvpa.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver.yaml
  charts/seed-controlplane/charts/kube-apiserver/values.yaml
  pkg/operation/botanist/controlplane.go
Labels: area/monitoring, kind/cleanup, needs/ok-to-test
