Repository gardener/gardener, pull requests merged in 2020-12, with the labels that each got.

#3249 Faster gardenlet rollout after spec change or config change
  pkg/gardenlet/controller/shoot/seed_registration_control.go
  pkg/gardenlet/controller/shoot/shoot.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3239 Refactor gardener-seed-admission-controller deployment into component
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-configmap.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/deployment.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/poddisruptionbudget.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/rbac.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/secret.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/service.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/serviceaccount.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/validatingwebhookconfiguration.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/vpa.yaml
  charts/seed-bootstrap/values.yaml
  pkg/operation/botanist/controlplane/etcd/bootstrap.go
  pkg/operation/botanist/controlplane/etcd/bootstrap_test.go
  pkg/operation/botanist/seedsystemcomponents/seedadmission/logging.go
  pkg/operation/botanist/seedsystemcomponents/seedadmission/logging_test.go
  pkg/operation/botanist/seedsystemcomponents/seedadmission/seedadmission.go
  pkg/operation/botanist/seedsystemcomponents/seedadmission/seedadmission_suite_test.go
  pkg/operation/botanist/seedsystemcomponents/seedadmission/seedadmission_test.go
  pkg/operation/seed/seed.go
Labels: area/dev-productivity, area/quality, area/robustness, exp/intermediate, kind/technical-debt, kind/test, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, size/xl, topology/seed

#3256 Delete deprecated kibana secret
  pkg/operation/botanist/secrets.go
Labels: area/logging, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3250 Update istio to 1.18.0
  charts/images.yaml
  charts/istio/istio-crds/templates/crd-all.gen.yaml
  charts/istio/istio-ingress/templates/deployment.yaml
  charts/istio/istio-ingress/templates/envoy-filter.yaml
  charts/istio/istio-ingress/templates/service.yaml
  charts/istio/istio-istiod/templates/clusterrole.yaml
  charts/istio/istio-istiod/templates/configmap-envoy.yaml
  charts/istio/istio-istiod/templates/deployment.yaml
  charts/istio/istio-istiod/templates/service.yaml
  pkg/operation/seed/istio/crds.go
  pkg/operation/seed/istio/crds_test.go
  pkg/operation/seed/istio/ingress_gateway_test.go
  pkg/operation/seed/istio/istiod_test.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xl

#3251 Re-evaluate shoot health status right after reconciliation
  pkg/gardenlet/controller/shoot/shoot.go
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/gardenlet/controller/shoot/shoot_control.go
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3188 Extend fluent-bit dashboard with custom metrics
  charts/images.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-service.yaml
  charts/seed-bootstrap/charts/fluent-bit/values.yaml
  charts/seed-bootstrap/dashboards/fluent-bit-dashboard.json
  charts/seed-bootstrap/templates/aggregate-prometheus/config.yaml
  charts/seed-bootstrap/values.yaml
Labels: area/logging, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, size/xl

#3255 Improve infrastructure reconciliation
  pkg/operation/botanist/extensions/infrastructure/infrastructure.go
  pkg/operation/botanist/extensions/infrastructure/infrastructure_test.go
  pkg/operation/botanist/infrastructure.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: area/robustness, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3257 Refactor shoot namespaces deployment into component
  charts/shoot-core/namespaces/Chart.yaml
  charts/shoot-core/namespaces/templates/kube-system.yaml
  charts/shoot-core/namespaces/values.yaml
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_migrate.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/controlplane/clusterautoscaler/bootstrap_test.go
  pkg/operation/botanist/controlplane/etcd/bootstrap_test.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/namespaces.go
  pkg/operation/botanist/namespaces_test.go
  pkg/operation/botanist/seedsystemcomponents/seedadmission/seedadmission_test.go
  pkg/operation/botanist/systemcomponents/metricsserver/metrics_server_test.go
  pkg/operation/botanist/systemcomponents/namespaces/namespaces.go
  pkg/operation/botanist/systemcomponents/namespaces/namespaces_suite_test.go
  pkg/operation/botanist/systemcomponents/namespaces/namespaces_test.go
  pkg/operation/common/managedresources.go
  pkg/operation/common/managedresources_test.go
  pkg/operation/common/types.go
  pkg/operation/shoot/types.go
Labels: area/dev-productivity, area/quality, area/robustness, exp/intermediate, kind/technical-debt, kind/test, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, size/xl, topology/seed

#3253 Add integration test testing the Loki multitenant ID usage
  test/framework/resources/templates/logger-app.yaml.tpl
  test/framework/shoot_utils.go
  test/integration/shoots/logging/loki_tenant.go
  test/integration/shoots/logging/seed_logging_stack.go
  test/integration/shoots/logging/utils.go
Labels: area/logging, kind/test, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3258 Sanitize webhook response
  pkg/admissioncontroller/server/handlers/webhooks/utils.go
  pkg/admissioncontroller/server/handlers/webhooks/utils_test.go
  pkg/admissioncontroller/server/handlers/webhooks/validate_kubeconfig_secrets.go
  pkg/admissioncontroller/server/handlers/webhooks/validate_namespace_deletion.go
  pkg/admissioncontroller/server/handlers/webhooks/validate_resource_size.go
  pkg/logger/logger.go
  pkg/logger/logger_test.go
Labels: area/ops-productivity, area/security, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3254 [GEP-7] Adds check for seed provider type when changing the seed name of shoot
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: area/control-plane-migration, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3262 Fix error during seed bootstrapping for fresh seeds
  pkg/operation/seed/seed.go
Labels: kind/bug, needs/ok-to-test, priority/critical, reviewed/lgtm, size/xs

#3263 Clean up unnecessary get call during seed bootstrap
  pkg/operation/seed/seed.go
Labels: kind/cleanup, needs/ok-to-test, needs/review, size/xs

#3265 Use vpa-admission-controller runtime namespace only in seed
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-admission-controller.yaml
Labels: area/auto-scaling, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3091 Set DB sync to full mode
  charts/seed-bootstrap/charts/fluent-bit/templates/_fluent-bit-config.tpl
  charts/seed-bootstrap/charts/loki/templates/loki-configmap.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/do-not-merge, reviewed/lgtm, size/xs

#3270 Add severity unifying filter for the user logs
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-configmap.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3264 Clean up the usage of deprecated role label under charts/seed-bootstrap
  charts/seed-bootstrap/charts/dependency-watchdog/templates/endpoint-deployment.yaml
  charts/seed-bootstrap/charts/dependency-watchdog/templates/probe-deployment.yaml
  charts/seed-bootstrap/charts/kube-state-metrics/templates/deployment.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-admission-controller.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-recommender.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-updater.yaml
  charts/seed-bootstrap/charts/vpa/values.yaml
  charts/seed-bootstrap/templates/alertmanager/alertmanager.yaml
  charts/seed-bootstrap/templates/grafana/grafana-deployment.yaml
  charts/seed-bootstrap/templates/grafana/grafana-service.yaml
  charts/seed-bootstrap/templates/vpa-exporter/deployment-exporter.yaml
  charts/seed-bootstrap/values.yaml
  pkg/operation/botanist/controlplane.go
  pkg/operation/common/utils.go
  pkg/operation/common/utils_test.go
  pkg/operation/seed/seed.go
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/m

#3276 [component:github.com/gardener/autoscaler:v0.10.0->v0.10.1]
  charts/images.yaml
Labels: area/auto-scaling, kind/regression, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3269 Do not show the custom metrics with increase equals to zero
  charts/seed-bootstrap/dashboards/fluent-bit-dashboard.json
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, size/xs

#3268 Disable grm target cache for shoots
  charts/images.yaml
  charts/seed-controlplane/charts/gardener-resource-manager/templates/deployment.yaml
Labels: area/cost, area/robustness, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3282 Use system-node-critical for apiserver-proxy Daemonset
  charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-daemonset.yaml
Labels: area/networking, area/scalability, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3287 [release-1.13] Cherry-pick Use system-node-critical for apiserver-proxy Daemonset
  charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-daemonset.yaml
Labels: area/networking, area/scalability, kind/bug, needs/ok-to-test, needs/review, priority/normal, size/xs

#3285 Promote 2 nonserial beta tests to default
  test/framework/k8s_utils.go
  test/integration/shoots/applications/metrics.go
  test/integration/shoots/applications/networking.go
  test/integration/shoots/operations/worker.go
Labels: area/testing, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#3291 Enhance permissions for Gardener admin
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3289 Wait for apiserver Service to be deleted on hibernation
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/controlplane/kube_apiserver_service.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#3273 Collect relevant cadvisor metrics for all pods
  pkg/operation/botanist/controlplane/etcd/monitoring.go
  pkg/operation/botanist/controlplane/etcd/monitoring_test.go
  pkg/operation/seed/seed.go
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3227 Add "remote" option for local dev setup
  Makefile
  docs/development/local_setup.md
  hack/local-development/common/helpers
  hack/local-development/dev-setup
  hack/local-development/dev-setup-register-gardener
  hack/local-development/remote-garden/cleanup
  hack/local-development/remote-garden/generate-certs
  hack/local-development/remote-garden/open-gardener-tunnels
  hack/local-development/remote-garden/run-gardener-etcd
  hack/local-development/start-apiserver
Labels: area/dev-productivity, area/testing, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xl

#3293 Add metrics to the admission controller
  cmd/gardener-admission-controller/app/gardener_admission_controller.go
  go.mod
  pkg/admissioncontroller/server/handlers/webhooks/validate_kubeconfig_secrets.go
  pkg/admissioncontroller/server/handlers/webhooks/validate_namespace_deletion.go
  pkg/admissioncontroller/server/handlers/webhooks/validate_resource_size.go
  pkg/admissioncontroller/server/metrics/metrics.go
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/modules.txt
Labels: area/monitoring, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, size/s

#3294 Change PodAntiAffinity to PreferredDuringSchedulingIgnoredDuringExecution for seed-admission-controller
  pkg/operation/botanist/seedsystemcomponents/seedadmission/seedadmission.go
  pkg/operation/botanist/seedsystemcomponents/seedadmission/seedadmission_test.go
Labels: area/robustness, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3277 Reduce Garden cluster connections for Gardenlet
  pkg/client/kubernetes/clientmap/internal/generic_clientmap.go
  pkg/client/kubernetes/clientmap/internal/shoot_clientmap.go
  pkg/client/kubernetes/clientmap/internal/shoot_clientmap_test.go
  pkg/client/kubernetes/clientmap/types.go
  pkg/gardenlet/controller/factory.go
Labels: area/scalability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3283 Add alerts for the custom metrics
  charts/seed-bootstrap/aggregate-prometheus-rules-tests/fluent-bit.rules.test.yaml
  charts/seed-bootstrap/aggregate-prometheus-rules/fluent-bit.rules.yaml
  charts/seed-bootstrap/dashboards/fluent-bit-dashboard.json
Labels: area/logging, kind/enhancement, merge/squash, needs/changes, needs/ok-to-test, priority/normal, size/m

#3300 Promote several serial beta tests to default
  test/integration/shoots/care/shoot_care.go
  test/integration/shoots/operatingsystem/os.go
  test/integration/shoots/operations/clusterautoscaler.go
  test/integration/shoots/operations/containerruntime.go
  test/integration/shoots/operations/operations.go
  test/integration/shoots/operations/worker.go
  test/suites/shoot/run_suite_test.go
Labels: area/testing, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#3286 Only consider effective shoot for health checks
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/logging.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3299 Do not leave kubeconfigs after test execution
  test/integration/shoots/operations/operations.go
Labels: area/testing, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#3298 Correct order of admission plugins
  cmd/gardener-apiserver/app/gardener_apiserver.go
  pkg/apiserver/apiserver_suite_test.go
  pkg/apiserver/plugins.go
  pkg/apiserver/plugins_test.go
Labels: area/usability, kind/api-change, kind/bug, merge/squash, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3297 Upgrade Prometheus to v2.23.0
  charts/images.yaml
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, needs/review, priority/normal, size/xs

#3303 update api-reference documentation to 1.19
  hack/api-reference/core-config.json
  hack/api-reference/core.md
  hack/api-reference/extensions-config.json
  hack/api-reference/extensions.md
  hack/api-reference/settings-config.json
  hack/api-reference/settings.md
Labels: area/documentation, kind/bug, needs/ok-to-test, needs/review, priority/normal, size/m

#3284 Add API Server metrics about dropped requests
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-api-server-details.json
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/l

#3306 [release-v1.14] Correct order of admission plugins
  cmd/gardener-apiserver/app/gardener_apiserver.go
  pkg/apiserver/apiserver_suite_test.go
  pkg/apiserver/plugins.go
  pkg/apiserver/plugins_test.go
Labels: area/usability, kind/api-change, kind/bug, merge/squash, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3307 Add gen-crd-api-reference link in generated documentation
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/settings.md
  hack/api-reference/template/pkg.tpl
Labels: area/documentation, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3301 Check if shoot is no longer managed by this gardenlet before reconcilation
  pkg/controllerutils/seedfilter.go
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/gardenlet/controller/shoot/shoot_control.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3309 Upgrade blackbox exporter
  charts/images.yaml
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3308 WorkerDelegate: factor out optional interface WorkerCredentialsDelegate
  extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/genericactuator/interface.go
Labels: area/quality, kind/cleanup, needs/changes, needs/ok-to-test, priority/normal, size/s

#3310 Add node exporter metrics
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-details-dashboard.json
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3305 Fix Time_Format of some parsers
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-configmap.yaml
  pkg/operation/botanist/controlplane/etcd/logging.go
  pkg/operation/botanist/controlplane/etcd/logging_test.go
  pkg/operation/botanist/seedsystemcomponents/seedadmission/logging.go
  pkg/operation/botanist/seedsystemcomponents/seedadmission/logging_test.go
Labels: area/logging, kind/bug, needs/ok-to-test, priority/normal, size/xs

#3295 Remove preStop hook for >= 1.16 clusters
  charts/seed-controlplane/charts/kube-apiserver/templates/deployment.yaml
Labels: area/usability, kind/bug, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3314 Fetch guestbook tests redis chart from bitnami
  test/framework/resources/repository/repositories.yaml
Labels: area/testing, kind/cleanup, needs/ok-to-test, priority/critical, reviewed/lgtm, size/xs

#3312 Improve seed VPA handling
  charts/seed-bootstrap/templates/aggregate-prometheus/vpa.yaml
  docs/usage/seed_settings.md
  pkg/operation/seed/seed.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3320 Ensure stable order of extension webhooks when registering
  extensions/pkg/webhook/cmd/cmd_suite_test.go
  extensions/pkg/webhook/cmd/factory.go
  extensions/pkg/webhook/cmd/factory_test.go
  extensions/pkg/webhook/cmd/options_test.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3323 Renew bootstrap token only once a day
  pkg/utils/kubernetes/bootstrap_token.go
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3316 Enhance scheduler documentation
  docs/concepts/scheduler.md
Labels: area/documentation, kind/enhancement, needs/changes, needs/ok-to-test, needs/review, priority/normal, size/s

#3319 Extend error code mapping
  pkg/apis/core/v1beta1/helper/errors.go
Labels: area/ops-productivity, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3315 Use nginx-ingress 0.41 version for Kubernetes 1.20 shoots
  charts/images.yaml
  charts/shoot-addons/charts/nginx-ingress/README.md
  charts/shoot-addons/charts/nginx-ingress/templates/clusterrole.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-daemonset.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-deployment.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/role.yaml
  charts/shoot-addons/charts/nginx-ingress/values.yaml
Labels: area/security, area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3326 Write updated kubeconfig to testmachinery output
  test/framework/common.go
  test/integration/shoots/operations/operations.go
Labels: area/testing, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3327 Clean up unused variable roots in graph flow
  pkg/utils/flow/graph.go
Labels: area/robustness, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3322 Adapt the ShootUID annotation to the new API group
  extensions/pkg/controller/backupentry/mapper.go
  pkg/apis/core/v1alpha1/constants/types_constants.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/namespaces.go
  pkg/operation/botanist/namespaces_test.go
Labels: kind/api-change, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#3328 Demote rotate-kubeconfig test to beta again (breaks other tests)
  test/integration/shoots/operations/operations.go
Labels: area/testing, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3330 Add minAllowed to VPA recommender and admission controller
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/vpa-admission-controller.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/vpa-updater.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3331 Fix ./hack/generate-controller-registration.sh
  hack/install-requirements.sh
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs

#3333 Reduce the initialDelaySeconds to 80 seconds for the Loki readinessProbe
  charts/seed-bootstrap/charts/loki/values.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3336 Make HVPA CRD deployment work for special semver versions
  charts/seed-bootstrap/charts/hvpa/templates/hvpa-crd.yaml
Labels: area/usability, kind/bug, needs/ok-to-test, needs/review, priority/normal, size/xs

#3337 Prefix global nginx-ingress resources to prevent naming conflicts
  charts/seed-bootstrap/charts/nginx-ingress/templates/clusterrole.yaml
  charts/seed-bootstrap/charts/nginx-ingress/templates/clusterrolebinding.yaml
Labels: area/usability, kind/bug, needs/ok-to-test, needs/review, priority/normal, size/xs

#3342 Adjust minimum resource limits for ingress Controller
  charts/istio/istio-ingress/templates/deployment.yaml
  charts/seed-bootstrap/charts/nginx-ingress/templates/vpa.yaml
Labels: area/auto-scaling, area/control-plane, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3338 Extend error code mapping
  pkg/apis/core/v1beta1/helper/errors.go
Labels: area/ops-productivity, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3345 Apply ingress controller limits to the right file
  charts/istio/istio-ingress/templates/deployment.yaml
  charts/seed-bootstrap/charts/nginx-ingress/templates/controller-deployment.yaml
Labels: needs/ok-to-test, needs/review, priority/normal, size/xs

#3344 Allow setting Seed spec.settings.loadBalancerServices.annotations via "shoot.gardener.cloud/use-as-seed"
  docs/usage/shooted_seed.md
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/gardenlet/controller/shoot/seed_registration_control.go
Labels: area/usability, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3343 Update README.md with versions that are no longer actively tested
  README.md
Labels: area/documentation, needs/ok-to-test, reviewed/lgtm, size/xs

#3346 Increase CPU resources for seed nginx default backend
  charts/seed-bootstrap/charts/nginx-ingress/templates/default-backend-deployment.yaml
Labels: area/scalability, kind/enhancement, needs/ok-to-test, needs/review, priority/normal, size/xs
