Repository gardener/gardener, pull requests merged in 2020-05, with the labels that each got.

#2271 Remove default delete options when deleting extensions
  pkg/operation/botanist/operatingsystemconfig_test.go
  pkg/operation/common/extensions.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: needs/ok-to-test

#2275 Nit: fix broken link
  docs/development/local_setup.md
  example/90-shoot.yaml
Labels: needs/ok-to-test

#2265 Fix ShootNotFailed extension predicate
  extensions/pkg/predicate/predicate.go
  extensions/pkg/predicate/predicate_test.go
  pkg/mock/controller-runtime/cache/doc.go
  pkg/mock/controller-runtime/cache/mocks.go
Labels: kind/bug, needs/ok-to-test

#2269 Use cached client for generic health check reconciler
  extensions/pkg/controller/healthcheck/reconciler.go
Labels: needs/ok-to-test

#2217 Improve Cluster synchronization to seed
  pkg/gardenlet/controller/seed/seed_control.go
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/garden/garden.go
  pkg/operation/garden/types.go
  pkg/operation/operation.go
  pkg/operation/seed/seed.go
  pkg/operation/seed/types.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
  pkg/operation/types.go
Labels: kind/bug, needs/ok-to-test

#2249 Fix health check library predicates
  extensions/pkg/controller/healthcheck/actuator.go
  extensions/pkg/controller/healthcheck/controller.go
  extensions/pkg/controller/healthcheck/healtcheck_actuator.go
  extensions/pkg/controller/healthcheck/reconciler.go
Labels: kind/bug, needs/ok-to-test

#2280 Fix apierrors.IsAlreadyExists check in CreateState
  extensions/pkg/terraformer/state.go
  extensions/pkg/terraformer/terraform_test.go
Labels: kind/bug, needs/ok-to-test

#2281 Adapt workaround for broken ShootNotFailed predicate
  pkg/gardenlet/controller/shoot/shoot_control.go
Labels: needs/ok-to-test

#2266 Configurable Gardenlet Stale health check verification
  example/20-componentconfig-gardenlet.yaml
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/health_check_test.go
Labels: needs/ok-to-test, needs/rebase

#2282 Validate intersection of Pod and Service networks
  pkg/utils/validation/cidr/disjoint.go
  pkg/utils/validation/cidr/disjoint_test.go
Labels: needs/ok-to-test

#2284 Fix Shoot status transitioning to Failed too early
  pkg/gardenlet/controller/shoot/shoot_control.go
Labels: needs/ok-to-test

#2288 Nit: fix broken links
  docs/concepts/apiserver.md
  docs/development/local_setup.md
  docs/development/monitoring-stack.md
  docs/development/new-cloud-provider.md
  docs/development/process.md
  docs/extensions/cluster.md
  docs/extensions/conventions.md
  docs/extensions/healthcheck-library.md
  docs/extensions/logging-and-monitoring.md
  docs/extensions/network.md
  docs/extensions/overview.md
  docs/extensions/worker.md
  docs/monitoring/alerting.md
  extensions/README.md
  extensions/pkg/controller/operatingsystemconfig/oscommon/README.md
Labels: needs/ok-to-test

#2286 Increase limits for CoreDNS + blackbox-exporter
  charts/shoot-core/components/charts/coredns/values.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/config.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
Labels: kind/bug, needs/ok-to-test

#2297 [ci:component:github.com/gardener/autoscaler:0.7.0->0.8.0]
  charts/images.yaml
Labels: needs/ok-to-test

#2296 Security Policy created
  SECURITY.md
Labels: needs/ok-to-test

#2291 CoreDNS Dashboard for users
  charts/seed-monitoring/charts/grafana/dashboards/owners/coredns-dashboard.json
Labels: area/monitoring, kind/enhancement, needs/ok-to-test

#2299 Do not pardon False ConditionStatus for recently created Shoots
  pkg/operation/botanist/constraints_check.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/health_check_test.go
Labels: kind/bug, needs/ok-to-test

#2300 Change port of GSAC from 9443 to 443
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/deployment.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/service.yaml
Labels: needs/ok-to-test

#2301 [ci:component:github.com/gardener/autoscaler:0.8.0->0.9.0]
  charts/images.yaml
Labels: needs/ok-to-test

#2276 Add restore and migrate to Network and ContainerRuntime Actuator
  extensions/pkg/controller/containerruntime/actuator.go
  extensions/pkg/controller/containerruntime/controller.go
  extensions/pkg/controller/containerruntime/reconciler.go
  extensions/pkg/controller/controlplane/reconciler.go
  extensions/pkg/controller/network/actuator.go
  extensions/pkg/controller/network/reconciler.go
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm

#2277 expand extension actuator interface with migrate and restore
  extensions/pkg/controller/extension/actuator.go
  extensions/pkg/controller/extension/reconciler.go
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, status/author-action

#2303 [release-v1.3] Fix scale down issue with machineDeployments
  charts/images.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm

#2279 Do not reconcile extensions of failed shoot clusters
  extensions/pkg/controller/backupbucket/reconciler.go
  extensions/pkg/controller/backupentry/reconciler.go
  extensions/pkg/controller/cluster.go
  extensions/pkg/controller/containerruntime/reconciler.go
  extensions/pkg/controller/controlplane/reconciler.go
  extensions/pkg/controller/csimigration/reconciler.go
  extensions/pkg/controller/extension/reconciler.go
  extensions/pkg/controller/infrastructure/reconciler.go
  extensions/pkg/controller/network/reconciler.go
  extensions/pkg/controller/operatingsystemconfig/reconciler.go
  extensions/pkg/controller/shoot.go
  extensions/pkg/controller/shoot_test.go
  extensions/pkg/controller/worker/reconciler.go
  extensions/pkg/controller/worker/state_reconciler.go
  extensions/pkg/predicate/predicate.go
Labels: kind/bug, needs/ok-to-test, needs/rebase, reviewed/lgtm

#2261 "Required" condition for ControllerInstallation to prevent early deletion
  charts/gardener/gardenlet/charts/runtime/templates/configmap-componentconfig.yaml
  example/20-componentconfig-gardenlet.yaml
  pkg/apis/core/types_controllerinstallation.go
  pkg/apis/core/v1alpha1/types_controllerinstallation.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_controllerinstallation.go
  pkg/controllermanager/controller/controllerregistration/controllerinstallation_control.go
  pkg/controllermanager/controller/controllerregistration/controllerinstallation_control_test.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_seed_control.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_seed_control_test.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_control.go
  pkg/gardenlet/controller/federatedseed/extensions/artifact.go
  pkg/gardenlet/controller/federatedseed/extensions/controllerinstallation_control.go
  pkg/gardenlet/controller/federatedseed/extensions/extensions.go
  pkg/gardenlet/controller/federatedseed/extensions/shootretriever.go
  pkg/gardenlet/controller/federatedseed/extensions/shootstate_control.go
  pkg/gardenlet/controller/federatedseed/seed_control.go
  pkg/gardenlet/controller/federatedseed/shootstate/shootstate_sync_control.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/clientset.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/doc.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/dns_client.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/dnsentry.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/dnsowner.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/dnsprovider.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/doc.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/generated_expansion.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/informers/externalversions/dns/interface.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/informers/externalversions/dns/v1alpha1/dnsentry.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/informers/externalversions/dns/v1alpha1/dnsowner.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/informers/externalversions/dns/v1alpha1/dnsprovider.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/informers/externalversions/dns/v1alpha1/interface.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/informers/externalversions/factory.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/informers/externalversions/generic.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/listers/dns/v1alpha1/dnsentry.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/listers/dns/v1alpha1/dnsowner.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/listers/dns/v1alpha1/dnsprovider.go
  vendor/github.com/gardener/external-dns-management/pkg/client/dns/listers/dns/v1alpha1/expansion_generated.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test

#2283 Add global cleanuphandler and possible after test options to the testsuite testcases
  test/framework/cleanup.go
  test/framework/commonframework.go
  test/framework/shoot_utils.go
  test/framework/test_description.go
  test/framework/test_options.go
  test/integration/shoots/applications/networking.go
  test/integration/shoots/care/shoot_care.go
  test/integration/shoots/logging/seed_log.go
  test/integration/shoots/operations/clusterautoscaler.go
Labels: kind/test, needs/ok-to-test

#2290 Fix duplicate Extension CRD reconcile in extension library
  charts/seed-operatingsystemconfig/downloader/templates/osc.yaml
  charts/seed-operatingsystemconfig/downloader/values.yaml
  charts/seed-operatingsystemconfig/original/templates/osc.yaml
  charts/seed-operatingsystemconfig/original/values.yaml
  extensions/pkg/controller/backupbucket/controller.go
  extensions/pkg/controller/backupentry/controller.go
  extensions/pkg/controller/containerruntime/controller.go
  extensions/pkg/controller/controlplane/controller.go
  extensions/pkg/controller/extension/reconciler.go
  extensions/pkg/controller/infrastructure/controller.go
  extensions/pkg/controller/network/controller.go
  extensions/pkg/controller/worker/controller.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/controllermanager/controller/shoot/shoot_hibernation_control.go
  pkg/gardenlet/controller/backupbucket/backup_bucket_actuator.go
  pkg/gardenlet/controller/backupentry/backup_entry_actuator.go
  pkg/operation/botanist/containerruntime.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/infrastructure.go
  pkg/operation/botanist/network.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/operatingsystemconfig_test.go
  pkg/operation/botanist/worker.go
  pkg/operation/common/utils.go
  pkg/operation/common/utils_test.go
Labels: kind/bug, needs/ok-to-test

#2311 Enhance error codes
  pkg/apis/core/v1beta1/helper/errors.go
Labels: needs/ok-to-test

#2308 Allow status label to be unhealthy for recently created Shoots
  pkg/gardenlet/controller/shoot/shoot_utils.go
  pkg/gardenlet/controller/shoot/shoot_utils_test.go
Labels: kind/bug, needs/ok-to-test

#2312 Fix potential panic in federated seed controller
  pkg/gardenlet/controller/federatedseed/extensions/extensions.go
Labels: kind/bug, needs/ok-to-test

#2307 Fix health check library predicate & LastTransitionTime
  extensions/pkg/controller/healthcheck/controller.go
  extensions/pkg/controller/healthcheck/reconciler.go
Labels: kind/bug, needs/ok-to-test

#2313 Fix kubelet bootstrapping race condition
  charts/shoot-cloud-config/templates/scripts/_cloud-config-script.sh
Labels: kind/bug, needs/ok-to-test

#2314 [release-v1.4] Maintain cherry-picks
  charts/shoot-cloud-config/templates/scripts/_cloud-config-script.sh
  extensions/pkg/controller/healthcheck/controller.go
  extensions/pkg/controller/healthcheck/reconciler.go
  pkg/gardenlet/controller/shoot/shoot_utils.go
  pkg/gardenlet/controller/shoot/shoot_utils_test.go
Labels: needs/ok-to-test

#2270 Improve webhook hibernation validation
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/constants/constants.go
  pkg/operation/botanist/constraints_check.go
  pkg/operation/botanist/constraints_check_test.go
  pkg/operation/botanist/matchers/matcher.go
  pkg/operation/botanist/matchers/rule_matcher.go
  pkg/operation/botanist/resource_manager.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, needs/ok-to-test

#2316 Enhance configuration problem error code matcher
  pkg/apis/core/v1beta1/helper/errors.go
Labels: kind/enhancement, needs/ok-to-test

#2278 More control for extension controller deployment
  docs/extensions/controllerregistration.md
  example/25-controllerregistration.yaml
  example/90-shoot.yaml
  hack/api-reference/core.md
  pkg/apis/core/types_controllerregistration.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_controllerregistration.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/zz_generated.defaults.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_controllerregistration.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/zz_generated.defaults.go
  pkg/apis/core/validation/controllerregistration.go
  pkg/apis/core/validation/controllerregistration_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_seed_control.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_seed_control_test.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_control.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/extension.go
  pkg/operation/common/utils.go
  pkg/operation/common/utils_test.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/shoot_test.go
  plugin/pkg/controllerregistration/resources/admission.go
  plugin/pkg/controllerregistration/resources/admission_test.go
  plugin/pkg/global/extensionvalidation/admission.go
  plugin/pkg/global/extensionvalidation/admission_test.go
Labels: kind/enhancement, needs/ok-to-test

#2310 Add PDB and anti-affinity for kube-apiserver
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/deployment.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/configmap-admission-config.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/configmap-audit-policy.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/deployment.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/hpa.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/hvpa.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/networkpolicy-allow-kube-apiserver-policy.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/networkpolicy-allow-to-shoot-apiserver-policy.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/poddisruptionbudget.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/secret-oidc-ca.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/secret-service-account-signing-key.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/vpa.yaml
  pkg/operation/common/types.go
Labels: kind/enhancement, needs/ok-to-test

#2109 [GEP-5] update integration tests
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  test/framework/gardener_utils.go
  test/framework/shootcreationframework.go
  test/integration/framework/shoot_maintenance_operations.go
  test/integration/framework/types.go
  test/integration/gardener/scheduler/scheduler_test.go
  test/integration/shoots/maintenance/maintenance.go
  test/integration/shoots/maintenance/maintenance_operations.go
  test/integration/shoots/maintenance/maintenance_suite_test.go
  test/integration/shoots/maintenance/maintenance_test.go
  test/integration/shoots/maintenance/run_maintenance_test.go
  test/system/shoot_creation/create_test.go
Labels: kind/test, needs/ok-to-test

#2238 Allow switching kube-proxy mode for k8s cluster > 1.16
  charts/shoot-core/components/charts/kube-proxy/templates/kube-proxy-cleanup-script.yaml
  charts/shoot-core/components/charts/kube-proxy/templates/kube-proxy-daemonset.yaml
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: kind/enhancement, needs/ok-to-test

#2323 Fix kube-apiserver anti-affinity rule
  charts/seed-controlplane/charts/kube-apiserver/templates/deployment.yaml
Labels: needs/ok-to-test

#2322 Fix nil pointer exception in federated seed shutdown
  pkg/gardenlet/controller/federatedseed/extensions/artifact.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion

#2289 Extension health checks support Progressing status
  docs/extensions/healthcheck-library.md
  extensions/pkg/controller/healthcheck/actuator.go
  extensions/pkg/controller/healthcheck/general/daemonset.go
  extensions/pkg/controller/healthcheck/general/deployment.go
  extensions/pkg/controller/healthcheck/general/helpers.go
  extensions/pkg/controller/healthcheck/general/managed_resource.go
  extensions/pkg/controller/healthcheck/general/statefulsets.go
  extensions/pkg/controller/healthcheck/healtcheck_actuator.go
  extensions/pkg/controller/healthcheck/reconciler.go
  extensions/pkg/controller/healthcheck/worker/helpers.go
  extensions/pkg/controller/healthcheck/worker/helpers_test.go
  extensions/pkg/controller/healthcheck/worker/nodes.go
  extensions/pkg/controller/healthcheck/worker/sufficient_nodes.go
  extensions/pkg/controller/healthcheck/worker/worker_suite_test.go
  extensions/test/integration/healthcheck/healthcheck_operation.go
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/health_check_test.go
Labels: kind/enhancement, needs/ok-to-test, needs/review

#2326 upgrade kyma addon to kyma 1.12.0
  charts/shoot-addons-kyma/charts/kyma/values.yaml
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#2324 Fix retry cycle time for shoots
  charts/gardener/gardenlet/values.yaml
  example/20-componentconfig-gardenlet.yaml
  pkg/controllermanager/controller/shoot/shoot_hibernation_types.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/common/types.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: area/robustness, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#2329 Fix panic in GCM seed-lifecycle-control
  pkg/controllermanager/controller/seed/seed_lifecycle_control.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm

#2330 Gardenlet - fix Seed enqueue when Bootstrap status changed
  pkg/gardenlet/controller/federatedseed/seed_control.go
Labels: kind/bug, needs/ok-to-test, needs/review, topology/seed

#2331 Reduce the amount federated seed workers
  example/20-componentconfig-gardenlet.yaml
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/controller/federatedseed/extensions/extensions.go
Labels: area/performance, needs/ok-to-test, reviewed/lgtm, topology/seed

#2334 [ci:component:github.com/gardener/etcd-druid:v0.2.0->v0.3.0]
  charts/images.yaml
Labels: component/etcd-druid, needs/ok-to-test, reviewed/lgtm

#2317 safe-to-evict annotation only added for etcd-main
  pkg/operation/botanist/controlplane.go
Labels: area/auto-scaling, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#2338 Additional guestbook test wait step and increased timeout
  test/framework/applications/guestbooktest.go
  test/integration/framework/garden_operation.go
  test/integration/shoots/operations/operations.go
Labels: area/testing, needs/ok-to-test, reviewed/lgtm

#2337 Remove staleExtensionHealthCheckThreshold from gardenlet default values.yaml
  charts/gardener/gardenlet/values.yaml
Labels: area/quality, kind/enhancement, needs/ok-to-test, priority/normal

#2341 Add developer documentation about API changes
  docs/README.md
  docs/development/changing-the-api.md
  docs/development/process.md
Labels: area/dev-productivity, area/documentation, area/open-source, kind/enhancement, needs/ok-to-test, priority/normal

#2344 Removed the old test framework
  .test-defs/SchedulerTest.yaml
  .test-defs/ShootMaintenanceTest.yaml
  extensions/test/e2e/framework/networkpolicies/agnostic.go
  extensions/test/e2e/framework/networkpolicies/generators/networkpolicies.go
  test/framework/commonframework.go
  test/framework/gardener_utils.go
  test/framework/gardenerframework.go
  test/framework/k8s_utils.go
  test/framework/shootframework.go
  test/integration/framework/common.go
  test/integration/framework/dump.go
  test/integration/framework/errors.go
  test/integration/framework/framework_test.go
  test/integration/framework/garden_operation.go
  test/integration/framework/helm_utils.go
  test/integration/framework/plant_operations.go
  test/integration/framework/scheduler_operations.go
  test/integration/framework/shoot_operations.go
  test/integration/framework/types.go
  test/integration/framework/utils.go
  test/integration/framework/worker_operations.go
  test/integration/gardener/scheduler/scheduler_test.go
  test/integration/shoots/maintenance/maintenance.go
Labels: area/testing, kind/cleanup, needs/ok-to-test, needs/second-opinion, priority/normal

#2342 Extend error code mapping
  pkg/apis/core/v1beta1/helper/errors.go
Labels: area/operations, area/ops-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2347 Add x-frame-options in Kibana
  charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-configmap.yaml
Labels: area/logging, area/security, kind/enhancement, needs/ok-to-test, needs/second-opinion, priority/normal, reviewed/lgtm

#2345 Fix HVPA CRD deletion after GASC introduction
  pkg/operation/common/utils.go
Labels: area/open-source, area/usability, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2333 Set shoot to `Failed` if non-retryable error codes are detected
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/apis/core/v1beta1/helper/errors_test.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: area/quality, area/robustness, area/scalability, exp/intermediate, kind/enhancement, needs/ok-to-test, needs/review, priority/normal, topology/garden

#2349 Add fake Golang package to allow vendoring .github/ISSUE_TEMPLATE directory, move categorization to the top
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/doc.go
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
Labels: area/dev-productivity, area/open-source, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#1980 Isolate dns entry
  charts/seed-dns/entry/templates/dnsentry.yaml
  charts/seed-dns/entry/values.yaml
  charts/seed-dns/provider/templates/dnsprovider.yaml
  charts/seed-dns/provider/values.yaml
  docs/deployment/aks.md
  docs/proposals/01-extensibility.md
  pkg/client/kubernetes/chartapplier_test.go
  pkg/client/kubernetes/test/fake_discovery.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/addons_test.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/component/deploy_test.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/dns.go
  pkg/operation/botanist/dns/dns_suite_test.go
  pkg/operation/botanist/dns/dnsentry.go
  pkg/operation/botanist/dns/dnsentry_test.go
  pkg/operation/botanist/dns/dnsprovider.go
  pkg/operation/botanist/dns/dnsprovider_test.go
  pkg/operation/botanist/dns_test.go
  pkg/operation/botanist/waiter.go
  pkg/operation/operation.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
  pkg/operation/types.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, size/xl, topology/seed

#2309 Add /healthz endpoint for Gardenlet
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/secret-cert.yaml
  charts/gardener/gardenlet/charts/runtime/templates/configmap-componentconfig.yaml
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  charts/gardener/gardenlet/charts/runtime/templates/secret-cert.yaml
  charts/gardener/gardenlet/values.yaml
  cmd/gardener-controller-manager/app/gardener_controller_manager.go
  cmd/gardener-scheduler/app/gardener_scheduler.go
  cmd/gardenlet/app/gardenlet.go
  docs/concepts/gardenlet.md
  example/20-componentconfig-gardenlet.yaml
  hack/local-development/dev-setup
  pkg/controllermanager/server/handlers/webhooks/validate_kubeconfig_secrets.go
  pkg/controllermanager/server/handlers/webhooks/validate_namespace_deletion.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/v1alpha1_suite_test.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/validation/validation.go
  pkg/gardenlet/apis/config/validation/validation_test.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/lease/lease.go
  pkg/gardenlet/controller/lease/lease_suite_test.go
  pkg/gardenlet/controller/lease/lease_test.go
  pkg/gardenlet/controller/seed/seed.go
  pkg/gardenlet/controller/seed/seed_lease_control.go
  pkg/gardenlet/controller/seed/seed_lease_control_test.go
  pkg/gardenlet/controller/shoot/seed_registration_control.go
  pkg/healthz/default.go
  pkg/healthz/default_test.go
  pkg/healthz/healthz.go
  pkg/healthz/healthz_suite_test.go
  pkg/healthz/healthz_test.go
  pkg/healthz/periodic.go
  pkg/healthz/periodic_test.go
  pkg/server/builder.go
  pkg/server/builder_test.go
  pkg/server/handlers/healthz.go
  pkg/server/server.go
  pkg/server/server_suite_test.go
Labels: area/quality, area/robustness, kind/enhancement, needs/ok-to-test, needs/review, platform/all, priority/normal, size/l, topology/seed

#2340 Add seedSelector for shoot scheduling decisions
  docs/concepts/scheduler.md
  example/30-cloudprofile.yaml
  example/90-shoot.yaml
  hack/api-reference/core.md
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_cloudprofile.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/scheduler/controller/shoot/scheduler_control.go
  pkg/scheduler/controller/shoot/scheduler_test.go
Labels: area/usability, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal

#2346 Forbid SecurityContextDeny admission plugin for shoots
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: area/quality, area/robustness, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2348 Exit worker reconciliation if error is observed
  extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  extensions/pkg/controller/worker/genericactuator/actuator_migrate.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
Labels: area/quality, area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2351 Prevent errors to be logged multiple times
  extensions/pkg/controller/backupbucket/reconciler.go
  extensions/pkg/controller/backupentry/reconciler.go
  extensions/pkg/controller/containerruntime/reconciler.go
  extensions/pkg/controller/controlplane/reconciler.go
  extensions/pkg/controller/extension/reconciler.go
  extensions/pkg/controller/infrastructure/reconciler.go
  extensions/pkg/controller/network/reconciler.go
  extensions/pkg/controller/operatingsystemconfig/reconciler.go
  extensions/pkg/controller/worker/reconciler.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2352 Fix bug deleting stale extension roles for other projects
  charts/garden-project/charts/project-rbac/templates/clusterrole-project-extensions.yaml
  charts/garden-project/charts/project-rbac/templates/rolebinding-project-extensions.yaml
  pkg/controllermanager/controller/project/project_control_reconcile.go
  pkg/controllermanager/controller/project/project_control_reconcile_test.go
Labels: area/usability, kind/bug, needs/ok-to-test, priority/critical, reviewed/lgtm

#2012 Introduce flow for preparing Shoot's Control Plane for migration
  docs/usage/control_plane_migration.md
  pkg/api/extensions/utils.go
  pkg/apis/core/types_common.go
  pkg/apis/core/v1alpha1/constants/types_constants.go
  pkg/apis/core/v1alpha1/helper/helper.go
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/types_common.go
  pkg/client/kubernetes/pods.go
  pkg/controllerutils/seedfilter.go
  pkg/gardenlet/controller/federatedseed/extensions/shootstate_control.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_prepare_migration.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/infrastructure.go
  pkg/operation/botanist/migration.go
  pkg/operation/botanist/migration_test.go
  pkg/operation/botanist/network.go
  pkg/operation/botanist/resource_manager.go
  pkg/operation/botanist/waiter.go
  pkg/operation/botanist/worker.go
  pkg/operation/operation.go
  pkg/registry/core/shoot/strategy.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: area/control-plane-migration, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, size/xl, topology/garden, topology/seed

#2336 Exit shoot flow when observing extension error
  pkg/operation/botanist/waiter.go
  pkg/operation/common/extensions.go
  pkg/utils/kubernetes/health/health.go
  pkg/utils/kubernetes/health/health_test.go
  test/framework/dump.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2357 Container Runtime CRD deployment
  pkg/operation/botanist/containerruntime.go
Labels: kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2362 Adapt install-requirements.sh instructions for Mac users
  hack/install-requirements.sh
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2367 Allow Shoot to be created when Seed .spec.backup=nil
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/critical, reviewed/lgtm

#2315 Add settings for seeds and deprecate hard-coded taints
  charts/gardener/gardenlet/charts/runtime/templates/configmap-componentconfig.yaml
  charts/gardener/gardenlet/values.yaml
  docs/usage/seed_settings.md
  example/20-componentconfig-gardenlet.yaml
  example/50-seed.yaml
  hack/api-reference/core.md
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/zz_generated.defaults.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/zz_generated.defaults.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_seed_control_test.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_control.go
  pkg/gardenlet/controller/seed/seed_control.go
  pkg/gardenlet/controller/shoot/seed_registration_control.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/secrets.go
  pkg/operation/garden/garden.go
  pkg/operation/operation.go
  pkg/operation/seed/seed.go
  pkg/operation/seed/types.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/shoot_test.go
  pkg/registry/core/seed/seed_suite_test.go
  pkg/registry/core/seed/strategy.go
  pkg/registry/core/seed/strategy_test.go
  pkg/scheduler/controller/shoot/scheduler_control.go
  pkg/scheduler/controller/shoot/scheduler_test.go
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/global/resourcereferencemanager/admission_test.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: area/usability, kind/api-change, needs/ok-to-test, needs/review, platform/all, priority/normal, size/xl, topology/garden

#2369 Nit: update gardener/etcd-druid version in go.mod
  go.mod
  go.sum
  pkg/scheduler/controller/shoot/scheduler.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/github.com/huandu/xstrings/convert.go
  vendor/modules.txt
Labels: needs/ok-to-test, priority/normal

#2361 Gardenlet self-generates TLS server certificates if necessary
  charts/gardener/gardenlet/charts/runtime/templates/configmap-componentconfig.yaml
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  charts/gardener/gardenlet/charts/runtime/templates/secret-cert.yaml
  charts/gardener/gardenlet/values.yaml
  cmd/gardenlet/app/gardenlet.go
  example/20-componentconfig-gardenlet.yaml
  hack/local-development/dev-setup
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/validation/validation.go
  pkg/gardenlet/apis/config/validation/validation_test.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/utils/secrets/certificates.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2364 Prevent Shoot to be reconciled twice on creation
  pkg/gardenlet/controller/shoot/shoot_control.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2365 Delete excess capacity resources when disabled
  pkg/operation/common/utils.go
  pkg/operation/seed/seed.go
Labels: area/operations, area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2320 Мutate shoot control plane pods annotation so to be excluded from log processing.
  charts/seed-bootstrap/charts/fluentd-es/templates/fluent-bit-configmap.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/mutatingwebhookconfiguration.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/rbac.yaml
  cmd/gardener-seed-admission-controller/app/gardener_seed_admission_controller.go
  pkg/seedadmission/extension_crds.go
  pkg/seedadmission/pods.go
  pkg/seedadmission/pods_test.go
  pkg/seedadmission/utils.go
  pkg/seedadmission/utils_test.go
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m, topology/seed

#2373 Fix nil pointer exception when health check fails
  extensions/pkg/controller/healthcheck/reconciler.go
Labels: area/monitoring, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2350 Persist and migrate secrets required by extension controllers
  charts/seed-bootstrap/templates/extensions/crd-extension.yaml
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/update-codegen.sh
  hack/update-protobuf.sh
  pkg/api/extensions/accessor.go
  pkg/api/extensions/accessor_test.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/types_shootstate.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/helper/shootstate_list.go
  pkg/apis/core/v1alpha1/helper/shootstate_list_test.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/types_shootstate.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/validation/shootstate.go
  pkg/apis/core/validation/shootstate_test.go
  pkg/apis/core/validation/utils.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/extensions/v1alpha1/types.go
  pkg/apis/extensions/v1alpha1/types_defaults.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/controller/federatedseed/extensions/artifact.go
  pkg/gardenlet/controller/federatedseed/extensions/shootstate_control.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/migration.go
  pkg/operation/common/extensions.go
  pkg/utils/object.go
Labels: area/control-plane-migration, kind/task, needs/ok-to-test, needs/review, needs/second-opinion, priority/normal, reviewed/lgtm

#2273 Add managed istio feature gates for Seed clusters.
  charts/images.yaml
  charts/istio/README.md
  charts/istio/istio-crds/Chart.yaml
  charts/istio/istio-crds/README.md
  charts/istio/istio-crds/templates/crd-all.gen.yaml
  charts/istio/istio-crds/values.yaml
  charts/istio/istio-ingress/Chart.yaml
  charts/istio/istio-ingress/charts/utils-templates
  charts/istio/istio-ingress/templates/autoscale.yaml
  charts/istio/istio-ingress/templates/deployment.yaml
  charts/istio/istio-ingress/templates/namespace.yaml
  charts/istio/istio-ingress/templates/role.yaml
  charts/istio/istio-ingress/templates/rolebindings.yaml
  charts/istio/istio-ingress/templates/service.yaml
  charts/istio/istio-ingress/templates/serviceaccount.yaml
  charts/istio/istio-ingress/values.yaml
  charts/istio/istio-istiod/Chart.yaml
  charts/istio/istio-istiod/NOTES.txt
  charts/istio/istio-istiod/charts/utils-templates
  charts/istio/istio-istiod/templates/autoscale.yaml
  charts/istio/istio-istiod/templates/clusterrole.yaml
  charts/istio/istio-istiod/templates/clusterrolebinding.yaml
  charts/istio/istio-istiod/templates/configmap-envoy.yaml
  charts/istio/istio-istiod/templates/configmap.yaml
  charts/istio/istio-istiod/templates/deployment.yaml
  charts/istio/istio-istiod/templates/destinationrule.yaml
  charts/istio/istio-istiod/templates/namespace.yaml
  charts/istio/istio-istiod/templates/peerauthentication.yaml
  charts/istio/istio-istiod/templates/role.yaml
  charts/istio/istio-istiod/templates/rolebinding.yaml
  charts/istio/istio-istiod/templates/service.yaml
  charts/istio/istio-istiod/templates/serviceaccount.yaml
  charts/istio/istio-istiod/templates/sidecar.yaml
  charts/istio/istio-istiod/templates/validatingwebhookconfiguration.yaml
  charts/istio/istio-istiod/values.yaml
  docs/README.md
  docs/deployment/feature_gates.md
  docs/usage/istio.md
  docs/usage/supported_k8s_versions.md
  example/20-componentconfig-gardenlet.yaml
  pkg/features/features.go
  pkg/gardenlet/features/features.go
  pkg/operation/common/types.go
  pkg/operation/seed/istio/crds.go
  pkg/operation/seed/istio/crds_test.go
  pkg/operation/seed/istio/ingress_gateway.go
  pkg/operation/seed/istio/ingress_gateway_test.go
  pkg/operation/seed/istio/istio_suite_test.go
  pkg/operation/seed/istio/istiod.go
  pkg/operation/seed/istio/istiod_test.go
  pkg/operation/seed/istio/type.go
  pkg/operation/seed/seed.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xl

#2375 Fix bug where visible seeds are registered as 'invisible'
  pkg/gardenlet/controller/shoot/seed_registration_control.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2376 Fix backupentry and backupbucket reconcile
  extensions/pkg/controller/backupbucket/reconciler.go
  extensions/pkg/controller/backupentry/reconciler.go
  extensions/pkg/controller/healthcheck/reconciler.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2381 Metal-Pod was renamed to metal-stack
  extensions/README.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#2372 update extensions matrix documentation
  docs/extensions/overview.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2383 Correctly evalute seed settings when registering shooted seed
  pkg/gardenlet/controller/shoot/seed_registration_control.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal

#2377 Add missing worker predicates for state sync controller
  extensions/pkg/controller/worker/controller.go
Labels: area/control-plane-migration, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2382 Scheduler filters protected seeds when shoot not in garden namespace
  pkg/scheduler/controller/shoot/scheduler_control.go
  pkg/scheduler/controller/shoot/scheduler_test.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2378 Add utility function for cleaning up leaked worker `ClusterRole`s
  extensions/pkg/controller/backupentry/reconciler.go
  extensions/pkg/controller/worker/genericactuator/actuator.go
  extensions/pkg/controller/worker/genericactuator/actuator_test.go
Labels: area/quality, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#2389 Nit: Specify sideEffects for validate-kubeconfig-secrets webhook
  charts/gardener/controlplane/charts/application/templates/validatingwebhook-controller-manager.yaml
Labels: area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2386 Changed rate of 1m to 2m on all grafana dashboards
  charts/seed-monitoring/charts/grafana/dashboards/operators/etcd-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/kubernetes-pods-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/vpn-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-pool-dashboard.json
Labels: area/monitoring, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#2395 Fix PSP for kube-proxy
  charts/shoot-core/components/charts/kube-proxy/templates/psp/kube-proxy-psp.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2394 Condition for unsuccessful HealthCheck includes the detail message
  extensions/pkg/controller/healthcheck/reconciler.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2391 Improve local-garden setup for Mac users
  Makefile
  hack/local-development/dev-setup-register-gardener
  hack/local-development/local-garden/README.md
  hack/local-development/local-garden/apply-rbac-garden-ns
  hack/local-development/local-garden/cleanup
  hack/local-development/local-garden/run-gardener-etcd
  hack/local-development/local-garden/run-kube-apiserver
  hack/local-development/local-garden/run-kube-controller-manager
  hack/local-development/local-garden/run-kube-etcd
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2379 Improve update event predicates for ControllerInstallationRequired controller
  pkg/gardenlet/controller/federatedseed/extensions/artifact.go
  pkg/gardenlet/controller/federatedseed/extensions/extensions.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s, topology/seed

#2399 Improve error message
  extensions/pkg/controller/worker/genericactuator/actuator_migrate.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2397 Be more conservative with errors of 3rd party components
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/gardenlet/controller/backupbucket/backup_bucket_actuator.go
  pkg/gardenlet/controller/backupentry/backup_entry_actuator.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/cleanup.go
  pkg/operation/botanist/containerruntime.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/dns/dnsentry.go
  pkg/operation/botanist/dns/dnsprovider.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/infrastructure.go
  pkg/operation/botanist/network.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/waiter.go
  pkg/operation/botanist/worker.go
  pkg/operation/common/extensions.go
  pkg/utils/kubernetes/health/health.go
  pkg/utils/kubernetes/health/health_test.go
  pkg/utils/retry/retry.go
  pkg/utils/retry/retry_test.go
  test/framework/dump.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2398 Flag incomplete DNS config errors with 'configuration problem' error code
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/gardenlet/controller/shoot/shoot_control_prepare_migration.go
  pkg/operation/operation.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2401 Nit: Fix the newObj, oldObj order
  pkg/gardenlet/controller/federatedseed/extensions/extensions.go
Labels: area/quality, needs/ok-to-test, priority/normal, reviewed/lgtm

#2392 VPA 0.8.0
  charts/images.yaml
  charts/seed-bootstrap/charts/vpa/templates/updater-deployment.yaml
  charts/seed-bootstrap/charts/vpa/templates/vpa-crd.yaml
  charts/seed-bootstrap/charts/vpa/templates/vpa-rbac.yaml
Labels: area/auto-scaling, area/scalability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2363 Support gcm webhooks in nodeless setup
  hack/local-development/common/helpers
  hack/local-development/dev-setup-register-gardener
Labels: area/dev-productivity, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2396 Add flag 'allowPrivilegedContainers' to the Shoot creation framework
  .test-defs/CreateShoot.yaml
  test/framework/shoot_utils.go
  test/framework/shootcreationframework.go
Labels: area/testing, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2403 Enhance error code mapping
  pkg/apis/core/v1beta1/helper/errors.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, platform/alicloud, platform/azure, priority/normal, reviewed/lgtm
