Repository gardener/gardener, pull requests merged in 2020-03, with the labels that each got.

#1992 Assign initial `requests` for kube-apiserver based on minNodes
  pkg/operation/botanist/controlplane.go
  pkg/operation/shoot/shoot.go
Labels: needs/ok-to-test

#1986 Add validation for worker machine image
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: needs/ok-to-test

#1970 GEP 10 - Update
  docs/proposals/10-shoot-additional-container-runtimes.md
Labels: needs/ok-to-test

#1959 Support multiple DNS providers
  charts/seed-dns/provider/templates/dnsprovider.yaml
  charts/seed-dns/provider/values.yaml
  example/90-shoot.yaml
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/settings.md
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helpers_test.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/client/core/openapi/zz_generated.openapi.go
  pkg/client/kubernetes/apply.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/constraints_check.go
  pkg/operation/botanist/dns.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/shoot_test.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: needs/ok-to-test

#1995 Fix wait for ingress dns
  pkg/operation/botanist/addons.go
Labels: needs/ok-to-test

#1996 Use controller-runtime's CreateOrUpdate function
  pkg/gardenlet/controller/backupbucket/backup_bucket_actuator.go
  pkg/gardenlet/controller/backupentry/backup_entry_actuator.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_control.go
  pkg/gardenlet/controller/seed/seed_control.go
  pkg/gardenlet/controller/shoot/seed_registration_control.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/infrastructure.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/network.go
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/worker.go
  pkg/operation/garden/garden.go
  pkg/operation/operation.go
  pkg/operation/seed/seed.go
  pkg/utils/kubernetes/bootstrap_token.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
Labels: needs/ok-to-test

#1998 Remove functionless DNS providers
  pkg/apis/core/v1alpha1/conversions.go
  pkg/apis/core/v1alpha1/conversions_test.go
  pkg/apis/core/v1beta1/conversions.go
  pkg/apis/core/v1beta1/conversions_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  pkg/utils/miscellaneous.go
  pkg/utils/miscellaneous_test.go
Labels: needs/ok-to-test

#1999 Do not duplicate `role` to `roles` in versioned `Project` objects
  docs/extensions/project-roles.md
  example/05-project-dev.yaml
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/settings.md
  pkg/apis/core/v1alpha1/conversions.go
  pkg/apis/core/v1alpha1/conversions_test.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/types_project.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/conversions.go
  pkg/apis/core/v1beta1/conversions_test.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/types_project.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/project.go
  pkg/client/core/openapi/zz_generated.openapi.go
  pkg/controllermanager/controller/project/project_control_reconcile.go
  pkg/openapi/openapi_generated.go
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/global/resourcereferencemanager/admission_test.go
Labels: needs/ok-to-test, priority/critical

#1994 external domain points to api server LB instead of internal domain
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/dns.go
Labels: needs/ok-to-test

#1988 Fix merge apply functions for Service
  pkg/client/kubernetes/apply.go
  pkg/client/kubernetes/apply_test.go
Labels: kind/bug, kind/cleanup, needs/ok-to-test

#1991 TokenRequest and TokenRequestProjection enabled by default
  charts/seed-controlplane/charts/kube-apiserver/templates/_helpers.tpl
  charts/seed-controlplane/charts/kube-apiserver/values.yaml
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/settings.md
  hack/generate-code
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/client/core/openapi/zz_generated.openapi.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/controlplane.go
Labels: area/security, kind/enhancement, needs/ok-to-test, platform/all, size/m, topology/shoot

#2004 Update build badge
  README.md
Labels: needs/ok-to-test

#2003 Make kubelet flag --image-pull-progress-deadline configurable
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.flags
  charts/seed-operatingsystemconfig/original/values.yaml
  example/90-shoot.yaml
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/settings.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/operatingsystemconfig.go
Labels: needs/ok-to-test

#2006 Only check default domain during shoot creation
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: needs/ok-to-test

#2002 Adding integration test for gardenlet care controller
  test/framework/shootframework.go
  test/integration/framework/utils.go
  test/integration/shoots/care/shoot_care.go
  test/suites/shoot/run_suite_test.go
Labels: needs/ok-to-test

#2010 Calculate default domain during seed assignment
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: needs/ok-to-test, priority/critical

#2007 Fix clusterautoscaler defaults in API docs
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/settings.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/types_shoot.go
Labels: needs/ok-to-test

#2000 Test creation and deletion of hibernated shoot
  .test-defs/CreateShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/WakeUpShoot.yaml
  docs/testing/integration_tests.md
  test/framework/gardener_utils.go
  test/framework/shootframework.go
  test/system/shoot_creation/create_test.go
  test/system/shoot_hibernation/hibernation_suite_test.go
  test/system/shoot_hibernation/hibernation_test.go
  test/system/shoot_hibernation_wakeup/hibernation_suite_test.go
  test/system/shoot_hibernation_wakeup/hibernation_test.go
  test/system/shoot_update/update_suite_test.go
  test/system/shoot_update/update_test.go
Labels: needs/ok-to-test

#2009 Revert "Fix manifest sorting in chart renderer"
  pkg/chartrenderer/default.go
Labels: kind/bug, needs/ok-to-test

#2011 [release-v1.1] Revert "Fix manifest sorting in chart renderer"
  pkg/chartrenderer/default.go
Labels: kind/bug

#2013 Re-add ChartApplierForConfig function
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/v1alpha1/conversions.go
  pkg/apis/core/v1alpha1/conversions_test.go
  pkg/apis/core/v1beta1/conversions.go
  pkg/apis/core/v1beta1/conversions_test.go
  pkg/client/kubernetes/chartapplier.go
  test/suites/shoot/run_suite_test.go
Labels: needs/ok-to-test

#2015 Update etcd-druid to go mod friendly version
  go.mod
  go.sum
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: needs/ok-to-test

#1972 Add shootstate creation step in reconciliation flow
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/settings.md
  pkg/apis/core/types_shootstate.go
  pkg/apis/core/v1alpha1/helper/helper.go
  pkg/apis/core/v1alpha1/helper/shootstate_list.go
  pkg/apis/core/v1alpha1/helper/shootstate_list_test.go
  pkg/apis/core/v1alpha1/types_shootstate.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shootstate_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/gardenlet/controller/federatedseed/shootstate/common_sync.go
  pkg/gardenlet/controller/federatedseed/shootstate/shootstate_sync_control.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/openapi/openapi_generated.go
  pkg/operation/operation.go
  pkg/operation/operation_test.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/shoot_test.go
  pkg/operation/types.go
Labels: needs/ok-to-test

#2020 add NodeCidrMaskSize to shoot example
  example/90-shoot.yaml
Labels: needs/ok-to-test

#2018 [ci:component:github.com/gardener/autoscaler:0.6.0->0.7.0]
  charts/images.yaml
Labels: needs/ok-to-test

#2021 Fix an issue that occurs if the shoot does not get a seed assigned
  test/framework/gardener_utils.go
  test/framework/shoot_utils.go
  test/framework/shootframework.go
  test/system/shoot_creation/create_test.go
Labels: needs/ok-to-test

#2023 Add test-infra-maintainers as CODEOWNERS
  CODEOWNERS
Labels: needs/ok-to-test

#2024 Fix a small typo: `apiserverResources` to `apiServerResources`
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#2025 Fix a small typo: `apiserverResources` to `apiServerResources`
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#2022 [hotfix] Prevent CA from downscaling node running etcd pod
  charts/seed-controlplane/charts/etcd/templates/etcd-statefulset.yaml
Labels: needs/ok-to-test

#2030 Upgrade HVPA version to 0.2.2
  charts/images.yaml
Labels: needs/ok-to-test

#2029 [ci:component:github.com/gardener/hvpa-controller:v0.2.1->v0.2.2]
  charts/images.yaml
Labels: needs/ok-to-test

#2028 Prevent kyma addon to pick to wrong kyma version
  charts/shoot-addons-kyma/values.yaml
Labels: kind/bug, needs/ok-to-test

#2031 [release-v1.1] Prevent kyma addon to pick to wrong kyma version
  charts/shoot-addons-kyma/values.yaml
Labels: kind/bug, needs/ok-to-test

#1971 GEP 10 - ContainerD Enablement
  charts/seed-bootstrap/templates/extensions/crd-operatingsystemconfig.yaml
  charts/seed-operatingsystemconfig/original/templates/containerd/_containerd-monitor.service
  charts/seed-operatingsystemconfig/original/templates/containerd/_containerd.service
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.flags
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.service
  charts/seed-operatingsystemconfig/original/templates/logrotate/_containerd-logrotate-config
  charts/seed-operatingsystemconfig/original/templates/logrotate/_containerd-logrotate.service
  charts/seed-operatingsystemconfig/original/templates/logrotate/_containerd-logrotate.timer
  charts/seed-operatingsystemconfig/original/templates/logrotate/containerd.conf
  charts/seed-operatingsystemconfig/original/templates/osc.yaml
  charts/seed-operatingsystemconfig/original/templates/scripts/_health-monitor.sh
  charts/seed-operatingsystemconfig/original/templates/scripts/_init-containerd.sh
  charts/seed-operatingsystemconfig/original/values.yaml
  docs/extensions/operatingsystemconfig.md
  example/90-shoot.yaml
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/settings.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/constants/types_constants.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/operatingsystemconfig.go
Labels: needs/ok-to-test

#2026 [release-v1.1] Revise migration steps for primary DNS provider
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/garden/garden.go
  pkg/operation/garden/garden_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  pkg/utils/miscellaneous_test.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: needs/ok-to-test

#2027 Add integration test for clusterautoscaler
  charts/seed-bootstrap/charts/hvpa/Chart.yaml
  charts/shoot-addons-kyma/charts/kyma/Chart.yaml
  test/framework/k8s_utils.go
  test/framework/resources/templates/reserve-capacity.yaml.tpl
  test/integration/shoots/operations/clusterautoscaler.go
Labels: needs/ok-to-test

#2034 Ensure backwards compatibility for DNS section
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: needs/ok-to-test

#2037 fix nil pointer if nil Apply or Delete options
  pkg/client/kubernetes/chartapplier.go
  pkg/client/kubernetes/chartapplier_test.go
Labels: needs/ok-to-test

#2042 [ci:component:github.com/gardener/hvpa-controller:v0.2.2->v0.2.4]
  charts/images.yaml
Labels: needs/ok-to-test

#2040 Clean up labelling of well-known ManagedResources
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/resource_manager.go
Labels: needs/ok-to-test

#2043 Upgrade github.com/gardener/hvpa-controller to v0.2.4
  charts/images.yaml
Labels: needs/ok-to-test

#2045 Update validation to allow worker.min to be 0
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: needs/ok-to-test

#1993 Only deploy required extensions
  docs/extensions/controllerregistration.md
  go.sum
  pkg/apis/core/field_constants.go
  pkg/apis/core/v1alpha1/helper/helper.go
  pkg/apis/core/v1alpha1/helper/helpers_test.go
  pkg/apis/core/v1beta1/conversions.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helpers_test.go
  pkg/controllermanager/controller/controllerregistration/backupbucket_control.go
  pkg/controllermanager/controller/controllerregistration/backupbucket_control_test.go
  pkg/controllermanager/controller/controllerregistration/backupentry_control.go
  pkg/controllermanager/controller/controllerregistration/backupentry_control_test.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_control.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_control_test.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_seed_control.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_seed_control_test.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_suite_test.go
  pkg/controllermanager/controller/controllerregistration/seed_control.go
  pkg/controllermanager/controller/controllerregistration/seed_control_test.go
  pkg/controllermanager/controller/controllerregistration/shoot_control.go
  pkg/controllermanager/controller/controllerregistration/shoot_control_test.go
  pkg/controllermanager/controller/factory.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_control.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/botanist.go
  pkg/operation/shoot/shoot.go
  pkg/registry/core/backupbucket/backupbucket_suite_test.go
  pkg/registry/core/backupbucket/storage/storage.go
  pkg/registry/core/backupbucket/strategy.go
  pkg/registry/core/backupbucket/strategy_test.go
  pkg/registry/core/backupentry/backupentry_suite_test.go
  pkg/registry/core/backupentry/storage/storage.go
  pkg/registry/core/backupentry/strategy.go
  pkg/registry/core/backupentry/strategy_test.go
  pkg/utils/kubernetes/controllerinstallation.go
Labels: area/cost, needs/ok-to-test

#2036 Allow injecting image vector overwrite into etcd-druid
  charts/gardener/gardenlet/charts/runtime/templates/configmap-imagevector-overwrite-components.yaml
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  charts/gardener/gardenlet/values.yaml
  charts/images.yaml
  charts/seed-bootstrap/charts/etcd-druid/templates/configmap-imagevector-overwrite.yaml
  charts/seed-bootstrap/charts/etcd-druid/templates/controller-deployment.yaml
  charts/seed-bootstrap/values.yaml
  docs/deployment/image_vector.md
  pkg/controllermanager/controller/controllerregistration/controllerregistration_seed_control_test.go
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/seed/seed.go
  pkg/gardenlet/controller/seed/seed_control.go
  pkg/gardenlet/controller/shoot/seed_registration_control.go
  pkg/operation/seed/seed.go
  pkg/utils/imagevector/imagevector_components.go
  pkg/utils/imagevector/imagevector_components_test.go
  pkg/utils/imagevector/imagevector_test.go
  pkg/utils/imagevector/types.go
Labels: needs/ok-to-test

#2032 Allow project members to update Role and RoleBindings
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/project/project.go
  pkg/controllermanager/controller/project/project_control.go
  pkg/controllermanager/controller/project/project_control_test.go
Labels: needs/ok-to-test

#2050 Allow worker.min to be zero while deploying cluster-autoscaler
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#2046 Added new metric to monitor CPU throttling
  charts/seed-bootstrap/prometheus-rules/recording-rules.rules.yaml
  charts/seed-bootstrap/values.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
Labels: needs/ok-to-test

#2056 Optimize apiserver HVPA minAllowed config.
  charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver-hvpa.yaml
Labels: needs/ok-to-test

#2049 ExtensionValidation admission plugin
  .ci/test
  cmd/gardener-apiserver/app/gardener_apiserver.go
  pkg/apis/core/v1alpha1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  plugin/pkg/global/extensionvalidation/admission.go
  plugin/pkg/global/extensionvalidation/admission_test.go
  plugin/pkg/global/extensionvalidation/extensionvalidation_suite_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: needs/ok-to-test

#2055 Enhancement.dns providers
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/garden/garden.go
  pkg/operation/garden/garden_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  pkg/utils/miscellaneous_test.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: needs/ok-to-test

#2057 [ci:component:github.com/gardener/etcd-druid:v0.1.3->v0.1.4]
  charts/images.yaml
Labels: needs/ok-to-test

#2061 Fix project controller test
  pkg/controllermanager/controller/project/project_control_test.go
Labels: needs/ok-to-test

#2062 Fix etcd-druid RBAC
  charts/seed-bootstrap/charts/etcd-druid/templates/druid-clusterrole.yaml
Labels: kind/bug, needs/ok-to-test

#2060 Added HPA metrics to kube-state-metrics in garden ns.
  charts/seed-bootstrap/charts/kube-state-metrics/templates/clusterrole.yaml
  charts/seed-bootstrap/charts/kube-state-metrics/templates/deployment.yaml
  charts/seed-bootstrap/values.yaml
Labels: needs/ok-to-test

#2065 [ci:component:github.com/gardener/etcd-druid:v0.1.4->v0.1.5]
  charts/images.yaml
  charts/seed-bootstrap/charts/etcd-druid/templates/controller-deployment.yaml
Labels: needs/ok-to-test

#2059 fix containerd config generation & mtu service
  charts/seed-operatingsystemconfig/original/templates/containerd/_containerd.service
  charts/seed-operatingsystemconfig/original/templates/containerd/containerd-initializer.service
  charts/seed-operatingsystemconfig/original/templates/containerd/containerd-require-initializer.yaml
  charts/seed-operatingsystemconfig/original/templates/osc.yaml
Labels: needs/ok-to-test

#2044 add network policies
  charts/shoot-core/components/charts/metrics-server/templates/deployment.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-from-to-nginx.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-to-api-server.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-to-kubelet.yaml
Labels: needs/ok-to-test

#2051 Add Component interfaces and associated methods
  pkg/operation/botanist/component/component_suite_test.go
  pkg/operation/botanist/component/deploy.go
  pkg/operation/botanist/component/deploy_test.go
  pkg/operation/botanist/component/fake/doc.go
  pkg/operation/botanist/component/fake/mocks.go
  pkg/operation/botanist/component/interfaces.go
Labels: needs/ok-to-test

#2068 Upgrading hvpa-controller to 0.2.5
  charts/images.yaml
Labels: needs/ok-to-test

#2067 Ensure worker pools are compatible with system components
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: needs/ok-to-test

#2069 [ci:component:github.com/gardener/hvpa-controller:v0.2.4->v0.2.5]
  charts/images.yaml
Labels: needs/ok-to-test

#2072 Accept new labels for project namespaces
  example/00-namespace-garden-dev.yaml
  pkg/controllermanager/controller/project/project_control_reconcile.go
  pkg/controllermanager/controller/project/project_utils.go
Labels: needs/ok-to-test

#2071 Validate project namespace is not in use
  pkg/controllermanager/controller/project/project_control.go
  pkg/controllermanager/controller/project/project_control_test.go
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/global/resourcereferencemanager/admission_test.go
Labels: needs/ok-to-test

#2075 Use K8s 1.15 for nodeless local Gardener
  docs/usage/supported_k8s_versions.md
  hack/local-garden/run-kube-apiserver
  hack/local-garden/run-kube-controller-manager
  plugin/pkg/global/resourcereferencemanager/admission_test.go
Labels: needs/ok-to-test

#2073 Add alpha scaling annotation to circumvent node criteria
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/controlplane_test.go
  pkg/operation/common/types.go
Labels: needs/ok-to-test

#2079 [ci:component:github.com/gardener/etcd-druid:v0.1.5->v0.1.6]
  charts/images.yaml
Labels: needs/ok-to-test

#2078 Add hibernation column to shoot table converter
  pkg/registry/core/shoot/storage/tableconvertor.go
Labels: needs/ok-to-test

#2082 [ci:component:github.com/gardener/etcd-druid:v0.1.6->v0.1.8]
  charts/images.yaml
Labels: needs/ok-to-test

#2083 Add TLS config for prometheus etcdbr scrape config
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
Labels: needs/ok-to-test

#2087 Allow v1.18 clients to be created
  pkg/client/kubernetes/client.go
Labels: needs/ok-to-test

#2086 Increase node-exporter timeout
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
Labels: needs/ok-to-test

#2088 Allow minikube node name to be "m01"
  docs/development/local_setup.md
  hack/common
Labels: needs/ok-to-test

#2089 :bug: Fix the restoration failure alert for etcd
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-etcd3.rules.yaml
Labels: needs/ok-to-test

#2080 Aggregate metrics for containers at scaling and limiting threshold.
  charts/seed-bootstrap/prometheus-rules/recording-rules.rules.yaml
Labels: needs/ok-to-test

#2035 GEP 10 - Container runtime extensions
  charts/seed-bootstrap/templates/extensions/crd-containerruntime.yaml
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.flags
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.service
  charts/seed-operatingsystemconfig/original/templates/node/_node-cri.labels
  charts/seed-operatingsystemconfig/original/templates/osc.yaml
  charts/seed-operatingsystemconfig/original/templates/scripts/_init-containerd.sh
  charts/seed-operatingsystemconfig/original/values.yaml
  docs/README.md
  docs/extensions/containerruntime.md
  example/90-shoot.yaml
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/settings.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/extensions/v1alpha1/register.go
  pkg/apis/extensions/v1alpha1/types_containerruntime.go
  pkg/apis/extensions/v1alpha1/types_defaults.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/containerruntime.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/extensions_client.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_containerruntime.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/fake/fake_extensions_client.go
  pkg/client/extensions/clientset/versioned/typed/extensions/v1alpha1/generated_expansion.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/containerruntime.go
  pkg/client/extensions/informers/externalversions/extensions/v1alpha1/interface.go
  pkg/client/extensions/informers/externalversions/generic.go
  pkg/client/extensions/listers/extensions/v1alpha1/containerruntime.go
  pkg/client/extensions/listers/extensions/v1alpha1/expansion_generated.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/containerruntime.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/shoot/shoot.go
  plugin/pkg/global/extensionvalidation/admission.go
  plugin/pkg/global/extensionvalidation/admission_test.go
Labels: needs/ok-to-test

#2091 [ci:component:github.com/gardener/etcd-druid:v0.1.8->v0.1.9]
  charts/images.yaml
Labels: reviewed/ok-to-test

#2093 ControllerInstallation care controller caters with non-existing MR objects
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_care_control.go
  plugin/pkg/global/extensionvalidation/admission_test.go
Labels: needs/ok-to-test

#2090 Add error code for cluster cleanup
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/apis/core/v1beta1/helper/errors_test.go
  pkg/apis/core/v1beta1/types_common.go
  pkg/gardenlet/controller/backupbucket/backup_bucket_actuator.go
  pkg/gardenlet/controller/backupentry/backup_entry_actuator.go
  pkg/operation/botanist/cleanup.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/dns.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/infrastructure.go
  pkg/operation/botanist/network.go
  pkg/operation/botanist/worker.go
  pkg/utils/errors/errors.go
  pkg/utils/retry/retry.go
Labels: needs/ok-to-test

#2096 Fix the build error
  Dockerfile
  pkg/operation/botanist/containerruntime.go
Labels: needs/ok-to-test

#2103 Fix provider ControllerRuntime handling
  pkg/operation/botanist/containerruntime.go
Labels: needs/ok-to-test

#2102 Add etcd name to the prefix
  charts/seed-controlplane/charts/etcd/templates/etcd.yaml
Labels: needs/ok-to-test

#2100 Delete DNS entries when shoot is hibernated
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/dns.go
Labels: needs/ok-to-test

#2098 Restart control plane controllers during maintenance
  charts/seed-controlplane/charts/kube-controller-manager/templates/kube-controller-manager-svc.yaml
  charts/seed-controlplane/charts/kube-controller-manager/templates/kube-controller-manager.yaml
  charts/seed-controlplane/charts/kube-controller-manager/values.yaml
  docs/extensions/shoot-maintenance.md
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/controller/shoot/shoot.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/common/types.go
Labels: needs/ok-to-test

#2110 Care controller: adjusting test framework label
  test/integration/shoots/care/shoot_care.go
Labels: needs/ok-to-test

#2104 Enforce use of fixed size int types in the API
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/settings.md
  pkg/api/extensions/accessor.go
  pkg/api/extensions/accessor_test.go
  pkg/apis/core/types_common.go
  pkg/apis/core/types_quota.go
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/core/v1alpha1/types_quota.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/types_common.go
  pkg/apis/core/v1beta1/types_quota.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/extensions/v1alpha1/types.go
  pkg/apis/extensions/v1alpha1/types_worker.go
  pkg/controllermanager/controller/shoot/shoot_quota_control.go
  pkg/gardenlet/controller/backupbucket/backup_bucket_reconciler.go
  pkg/gardenlet/controller/backupentry/backup_entry_reconciler.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/worker.go
  pkg/utils/flow/flow.go
  plugin/pkg/shoot/quotavalidator/admission.go
  plugin/pkg/shoot/quotavalidator/admission_test.go
Labels: needs/ok-to-test

#2101 GEP 10 - Container runtime extensions - addded cr config validation
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: needs/ok-to-test

#2092 Annotate etcd with operation and check generation + error
  charts/images.yaml
  charts/seed-bootstrap/charts/etcd-druid/templates/controller-deployment.yaml
  charts/seed-bootstrap/charts/etcd-druid/templates/etcd-crd.yaml
  charts/seed-controlplane/charts/etcd/templates/allow-from-apiserver-network-policy.yaml
  charts/seed-controlplane/charts/etcd/templates/etcd-hvpa.yaml
  charts/seed-controlplane/charts/etcd/templates/etcd.yaml
  charts/seed-controlplane/charts/etcd/values.yaml
  go.mod
  go.sum
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/waiter.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, priority/critical

#2116 Add CP restart setting for versioned API
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  charts/gardener/controlplane/values.yaml
  hack/api-reference/core.md
  hack/api-reference/extensions.md
  hack/api-reference/settings.md
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
Labels: needs/ok-to-test

#2119 Adapt etcd-druid limits + deployment of Etcd resources
  charts/seed-bootstrap/charts/etcd-druid/templates/controller-deployment.yaml
  pkg/operation/botanist/controlplane.go
Labels: needs/ok-to-test

#2118 Write UID to shoot status after operation creation
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/operation/shoot/shoot.go
Labels: needs/ok-to-test
