Repository gardener/gardener, pull requests merged in 2020-11, with the labels that each got.

#3077 Scale up KCM during shoot deletion only if it already exist.
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3054 Dedicated files in botanist pkg for control plane components
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/mock/gardener/operation/botanist/controlplane/clusterautoscaler/doc.go
  pkg/mock/gardener/operation/botanist/controlplane/clusterautoscaler/mocks.go
  pkg/mock/gardener/operation/botanist/controlplane/kubecontrollermanager/doc.go
  pkg/mock/gardener/operation/botanist/controlplane/kubecontrollermanager/mocks.go
  pkg/mock/gardener/operation/botanist/controlplane/kubescheduler/doc.go
  pkg/mock/gardener/operation/botanist/controlplane/kubescheduler/mocks.go
  pkg/operation/botanist/clusterautoscaler.go
  pkg/operation/botanist/clusterautoscaler_test.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/kubecontrollermanager.go
  pkg/operation/botanist/kubecontrollermanager_test.go
  pkg/operation/botanist/kubescheduler.go
  pkg/operation/botanist/kubescheduler_test.go
Labels: area/dev-productivity, area/quality, kind/cleanup, kind/test, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xl

#3068 Remove pod panels from node-details dashboard
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-details-dashboard.json
Labels: area/monitoring, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/l

#3084 Enhance error code mapping
  pkg/apis/core/v1beta1/helper/errors.go
Labels: area/ops-productivity, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3070 Update VPA pod autoscaler from 0.8.0 to 0.9.0
  charts/images.yaml
Labels: area/auto-scaling, area/control-plane, kind/enhancement, needs/ok-to-test, priority/normal, size/xs

#3087 Use controller-runtime informer for Shoot reference controller
  pkg/controllermanager/controller/shoot/shoot.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/critical, size/xs

#3085 Skip certain tasks in shoot deletion flow if namespace is terminating
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_migrate.go
  pkg/utils/flow/taskfn.go
Labels: area/ops-productivity, area/usability, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3089 Collect metric `coredns_build_info`
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
Labels: area/monitoring, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3083 Add data transfer to Istio Mesh Dashboard
  charts/seed-bootstrap/dashboards/istio/istio-mesh-dashboard.json
Labels: area/monitoring, kind/cleanup, needs/ok-to-test, priority/normal, size/m

#3088 Exclude garden namespace from ValidatingWebhookConfig
  charts/gardener/controlplane/charts/application/templates/namespace-garden.yaml
  charts/gardener/controlplane/charts/application/templates/validatingwebhook-admission-controller.yaml
  docs/deployment/setup_gardener.md
  docs/usage/configuration.md
Labels: area/delivery, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3092 Add KEEPALIVE to apiserver-proxy
  charts/shoot-core/components/charts/apiserver-proxy/templates/proxy-configmap.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3093 [release-1.12] Cherry-pick - Add KEEP_ALIVE to apiserver-proxy
  charts/shoot-core/components/charts/apiserver-proxy/templates/proxy-configmap.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3095 Revert "Parallelize check-generate step in CI"
  .ci/check-generate
  Makefile
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, priority/normal, size/xs

#3096 Do not hard-code shoot priority class name
  charts/seed-bootstrap/templates/priorityclass-shoot-controlplane.yaml
  charts/seed-bootstrap/values.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/deployment.yaml
  charts/seed-controlplane/charts/kube-apiserver/values.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/seed/seed.go
Labels: area/dev-productivity, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3097 Clean up setting fake Shoot status in the Cluster
  pkg/operation/common/extensions.go
Labels: kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3105 [release-1.12] Cherry-pick Set KEEPALIVE on istio-ingress-gateway listeners
  charts/istio/istio-ingress/templates/envoy-filter.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3104 Set KEEPALIVE on istio-ingressgateway listeners
  charts/istio/istio-ingress/templates/envoy-filter.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3102 Trivial fix for the "default-admin.conf" path used for local-garden
  Makefile
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3100 Change rolling strategy for vpn deployment
  charts/shoot-core/components/charts/vpn-shoot/templates/deployment.yaml
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3107 Increase kube-controller-manager VPA minAllowed
  pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager_test.go
Labels: area/auto-scaling, area/control-plane, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3072 Add ResourceQuota for projects
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  charts/gardener/controlplane/values.yaml
  cmd/gardener-controller-manager/app/gardener_controller_manager.go
  docs/concepts/apiserver_admission_plugins.md
  docs/concepts/controller-manager.md
  example/20-componentconfig-gardener-controller-manager.yaml
  hack/api-reference/settings.md
  pkg/apis/settings/types_cluster_openidconnect_preset.go
  pkg/apis/settings/v1alpha1/generated.proto
  pkg/apis/settings/v1alpha1/types_cluster_openidconnect_preset.go
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/conversions.go
  pkg/controllermanager/apis/config/v1alpha1/conversions_test.go
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/defaults_test.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/validation/validation.go
  pkg/controllermanager/apis/config/validation/validation_suite_test.go
  pkg/controllermanager/apis/config/validation/validation_test.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
  pkg/controllermanager/controller/project/project.go
  pkg/controllermanager/controller/project/project_control.go
  pkg/controllermanager/controller/project/project_control_reconcile.go
  pkg/controllermanager/controller/project/project_control_reconcile_test.go
  pkg/openapi/openapi_generated.go
  pkg/utils/test/matchers/matchers.go
Labels: area/robustness, area/security, kind/api-change, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, size/xl

#3111 Nit: Cleanup deprecated predicate.Or
  extensions/pkg/predicate/predicate.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#3116 Allow updates to Shoots if spec is unchanged
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/global/resourcereferencemanager/admission_test.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/critical, reviewed/lgtm, size/s

#3114 Gardenlet does not use self-generated TLS cert during self-deployment
  pkg/gardenlet/controller/shoot/seed_registration_control.go
  pkg/utils/secrets/certificates.go
Labels: area/scalability, area/security, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3115 Ignore missing audit configmaps when deploying KAPI in shoot deletion
  pkg/operation/botanist/controlplane.go
Labels: area/open-source, area/usability, kind/task, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3098 Keep the Loki updates from the HVPA
  charts/seed-bootstrap/charts/loki/values.yaml
  pkg/operation/botanist/logging.go
  pkg/operation/common/utils.go
  pkg/operation/common/utils_test.go
  pkg/operation/seed/seed.go
Labels: area/logging, kind/bug, needs/changes, needs/ok-to-test, priority/normal, size/m

#3117 Disable audit policy configmap reference protection by default
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  charts/gardener/controlplane/values.yaml
  docs/concepts/controller-manager.md
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
  pkg/controllermanager/controller/shoot/shoot.go
  pkg/controllermanager/controller/shoot/shoot_reference_control.go
  pkg/controllermanager/controller/shoot/shoot_reference_control_test.go
Labels: area/open-source, area/usability, kind/task, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#2975 [GEP-7] Add ability to migrate shoot in the integration tests
  .test-defs/MigrateShoot.yaml
  test/framework/gardener_utils.go
  test/framework/k8s_utils.go
  test/framework/shoot_utils.go
  test/framework/shootframework.go
  test/framework/shootmigrationtest.go
  test/framework/utils.go
  test/system/shoot_cp_migration/migrate_suite_test.go
  test/system/shoot_cp_migration/migrate_test.go
Labels: area/control-plane-migration, area/testing, kind/test, needs/changes, needs/ok-to-test, priority/normal, size/xl

#3125 Fix IGW ports when SNI is being disabled
  pkg/operation/botanist/controlplane/kube_apiserver_sni.go
  pkg/operation/botanist/controlplane/kube_apiserver_sni_test.go
  pkg/operation/seed/seed.go
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3126 [release-1.12] Chery-pick Fix IGW ports when SNI is being disabled
  pkg/operation/botanist/controlplane/kube_apiserver_sni.go
  pkg/operation/botanist/controlplane/kube_apiserver_sni_test.go
  pkg/operation/seed/seed.go
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3124 Fix missing user logs issue
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-configmap.yaml
  pkg/operation/seed/seed.go
Labels: area/logging, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3113 Force ca-certs activation on the nodes.
  charts/seed-operatingsystemconfig/original/templates/ssl/_update-ca-certs.service
Labels: kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3135 Distribute gardenlet rollout due to shooted seed registration
  charts/gardener/gardenlet/charts/runtime/templates/configmap-componentconfig.yaml
  charts/gardener/gardenlet/values.yaml
  example/20-componentconfig-gardenlet.yaml
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/shoot/seed_registration_control.go
Labels: area/robustness, area/scalability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3134 Configuration option for feature gates for shooted seeds
  docs/usage/shooted_seed.md
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/gardenlet/controller/shoot/seed_registration_control.go
Labels: area/usability, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3132 Allow project members to read ResourceQuota
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
Labels: area/usability, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, size/xs

#3133 Properly de-bootstrap seed cluster on deletion (only for components)
  extensions/pkg/controller/healthcheck/general/helpers.go
  extensions/pkg/controller/healthcheck/general/helpers_test.go
  extensions/pkg/controller/healthcheck/general/managed_resource.go
  pkg/gardenlet/controller/seed/seed_control.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/component/interfaces.go
  pkg/operation/botanist/controlplane/clusterautoscaler/bootstrap.go
  pkg/operation/botanist/controlplane/clusterautoscaler/bootstrap_test.go
  pkg/operation/common/managedresources.go
  pkg/operation/common/managedresources_test.go
  pkg/operation/seed/seed.go
  pkg/utils/kubernetes/health/health.go
  pkg/utils/kubernetes/health/health_test.go
  pkg/utils/managedresources/managedresources.go
  pkg/utils/managedresources/managedresources_test.go
Labels: area/usability, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xl

#3145 Fix seed bootstrap
  pkg/operation/botanist/controlplane/kube_apiserver_sni.go
  pkg/operation/botanist/controlplane/kube_apiserver_sni_test.go
Labels: area/robustness, kind/bug, needs/ok-to-test, priority/blocker, size/s

#2969 [GEP-7] Adds checks whether the target seed supports DNS before migration
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: area/control-plane-migration, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, size/m

#3143 Add APIServerSNI configuration in Gardenlet
  charts/gardener/gardenlet/charts/runtime/templates/configmap-componentconfig.yaml
  charts/gardener/gardenlet/values.yaml
  charts/seed-controlplane/charts/kube-apiserver-sni/templates/kube-apiserver-envoyfilter.yaml
  charts/seed-controlplane/charts/kube-apiserver-sni/templates/kube-apiserver-gateway.yaml
  charts/seed-controlplane/charts/kube-apiserver-sni/values.yaml
  example/20-componentconfig-gardenlet.yaml
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/apis/config/validation/validation.go
  pkg/gardenlet/apis/config/validation/validation_test.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/seed/seed_control.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/controlplane/kube_apiserver_sni.go
  pkg/operation/botanist/controlplane/kube_apiserver_sni_test.go
  pkg/operation/common/types.go
  pkg/operation/seed/seed.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/l

#3146 Fix Dynamic Host Regex
  charts/seed-bootstrap/charts/fluent-bit/templates/_fluent-bit-config.tpl
Labels: area/logging, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3147 add event on BackupBucket if referred secret is missing
  pkg/gardenlet/controller/backupbucket/backup_bucket_reconciler.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3149 Remove ShootState sync controller events
  pkg/gardenlet/controller/federatedseed/extensions/shootstate_control.go
Labels: area/scalability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3151 Istio's ingressgateway's maxUnavailable is set to 0
  charts/istio/istio-ingress/templates/deployment.yaml
Labels: area/control-plane, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3144 Reset shoot rate limiting on deletion
  pkg/gardenlet/controller/shoot/shoot.go
  pkg/gardenlet/controller/shoot/shoot_control.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3154 Add minAllowed resource limits for hvpa controller
  charts/seed-bootstrap/charts/hvpa/templates/controller-deployment.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#3075 Ensure seeds capacity for shoots is not exceeded
  charts/gardener/gardenlet/charts/runtime/templates/configmap-componentconfig.yaml
  charts/gardener/gardenlet/values.yaml
  example/20-componentconfig-gardenlet.yaml
  hack/api-reference/core.md
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1alpha1/conversions.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/validation/validation.go
  pkg/gardenlet/apis/config/validation/validation_test.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/seed/seed_control.go
  pkg/gardenlet/controller/shoot/seed_registration_control.go
  pkg/openapi/openapi_generated.go
  pkg/scheduler/controller/shoot/scheduler_control.go
  pkg/scheduler/controller/shoot/scheduler_control_test.go
Labels: area/robustness, kind/api-change, kind/enhancement, kind/test, needs/changes, needs/ok-to-test, needs/second-opinion, priority/normal, size/xl

#3156 Update correct image on release
  hack/.ci/set_dependency_version
Labels: area/logging, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3153 Add cilium example to shoot.yaml
  example/90-shoot.yaml
Labels: area/usability, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, reviewed/ok-to-test, size/xs

#3136 Projects can be excluded from the stale checks
  docs/concepts/controller-manager.md
  pkg/controllermanager/controller/project/project.go
  pkg/controllermanager/controller/project/project_stale_control.go
  pkg/controllermanager/controller/project/project_stale_control_test.go
  pkg/operation/common/types.go
Labels: area/ops-productivity, area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3158 Update docu for seeds capacity for shoots
  docs/concepts/scheduler.md
  docs/usage/shooted_seed.md
  pkg/gardenlet/controller/seed/seed_control.go
Labels: area/documentation, area/robustness, kind/enhancement, priority/normal, reviewed/lgtm, reviewed/ok-to-test, size/xs

#3157 Add documentation for support of CP migration by extensions
  docs/README.md
  docs/extensions/migration.md
Labels: area/control-plane-migration, area/documentation, kind/enhancement, needs/changes, priority/normal, reviewed/ok-to-test, size/s

#3162 Fix coredns network policies.
  charts/shoot-core/components/charts/coredns/templates/coredns-networkpolicy.yaml
  charts/shoot-core/components/charts/coredns/values.yaml
Labels: kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3163 [release-1.12] Cherry-pick Fix coredns network policies.
  charts/shoot-core/components/charts/coredns/templates/coredns-networkpolicy.yaml
  charts/shoot-core/components/charts/coredns/values.yaml
Labels: kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3175 Update to golang@1.15.5
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#3167 Prevent successfully deleted shoots from getting stuck
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
Labels: area/ops-productivity, area/usability, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3176 Do not wait KCM if it is already gone
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
Labels: kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3168 Do not redeploy external DNS record for shoot deletion
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
Labels: area/ops-productivity, area/usability, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3164 Support containerd sandbox image overwrite
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.flags
  charts/seed-operatingsystemconfig/original/templates/scripts/_init-containerd.sh
Labels: area/os, kind/enhancement, needs/ok-to-test, priority/blocker, size/xs

#3106 Do not set Shoot status to Failed too early when operation cannot be initialized
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/gardenlet/controller/shoot/shoot_control_migrate.go
Labels: area/quality, kind/bug, needs/changes, needs/ok-to-test, priority/normal, size/s

#3182 Support containerd sandbox image overwrite
  charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet.flags
  charts/seed-operatingsystemconfig/original/templates/scripts/_init-containerd.sh
Labels: area/os, kind/enhancement, needs/ok-to-test, priority/blocker, reviewed/lgtm, size/xs

#3173 Introduce MaintenancePreconditionsSatisfied shoot constraint
  docs/usage/shoot_status.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/controllermanager/controller/seed/seed_lifecycle_control.go
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/operation/botanist/constraints_check.go
Labels: area/usability, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3165 Upgrade to fluent-bit 1.6.4 and set liveness and readiness probe to the fluent-bit DaemonSet
  charts/images.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/_fluent-bit-config.tpl
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3180 Small improvements for the managed resource registry utility
  pkg/utils/managedresources/registry.go
  pkg/utils/managedresources/registry_test.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3178 Prevent orphaned machine resources on worker deletion
  extensions/pkg/controller/worker/genericactuator/actuator.go
  extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  extensions/pkg/controller/worker/genericactuator/actuator_test.go
  extensions/pkg/controller/worker/genericactuator/interface.go
Labels: area/ops-productivity, area/quality, area/robustness, kind/bug, needs/changes, needs/ok-to-test, priority/normal, size/m

#3142 DNSEntry TTL is now configurable in gardenlet config
  charts/gardener/gardenlet/charts/runtime/templates/configmap-componentconfig.yaml
  charts/gardener/gardenlet/values.yaml
  example/20-componentconfig-gardenlet.yaml
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/validation/validation.go
  pkg/gardenlet/apis/config/validation/validation_test.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/addons_test.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/controlplane_test.go
  pkg/operation/botanist/dns.go
  pkg/operation/botanist/dns_test.go
  pkg/operation/botanist/extensions/dns/dnsentry.go
  pkg/operation/botanist/extensions/dns/dnsentry_test.go
Labels: area/networking, area/usability, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, size/m

#3137 Merge duplicate project members
  pkg/apis/core/validation/project.go
  pkg/apis/core/validation/project_test.go
  pkg/registry/core/project/project_suite_test.go
  pkg/registry/core/project/strategy.go
  pkg/registry/core/project/strategy_test.go
Labels: area/usability, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/l

#3166 Add PriorityClass for fluent-bit
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-priorityclass.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3094 Clean up more deprecated labels and annotations
  charts/gardener/controlplane/charts/utils-common/templates/_secret_openvpn-diffie-hellman.yaml
  pkg/apis/core/v1alpha1/constants/types_constants.go
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/constants/utils.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/types_common.go
  pkg/controllermanager/controller/project/project_control_delete.go
  pkg/controllermanager/controller/project/project_control_reconcile.go
  pkg/controllermanager/controller/project/project_utils.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/metadata.go
  pkg/operation/common/types.go
  plugin/pkg/shoot/validator/admission.go
Labels: kind/api-change, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3183 Health check only considers metrics-server MR for gardener >= 1.13
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/health_check_test.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
Labels: area/ops-productivity, kind/api-change, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3139 Allow configuring kcm's pod eviction timeout for shoots
  example/90-shoot.yaml
  hack/api-reference/core.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager_test.go
Labels: area/robustness, area/usability, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xl

#3179 Keep project namespaces after deletion if they existed already
  example/00-namespace-garden-dev.yaml
  example/00-namespace-garden.yaml
  pkg/controllermanager/controller/project/project_control_reconcile.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3141 Allow configuring kube-apiserver's max inflight requests for shoots
  charts/seed-controlplane/charts/kube-apiserver/templates/deployment.yaml
  charts/seed-controlplane/charts/kube-apiserver/values.yaml
  example/90-shoot.yaml
  hack/api-reference/core.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/controlplane.go
Labels: area/scalability, area/usability, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xl

#3174 Metrics server to use http healthchecks
  charts/images.yaml
  pkg/operation/botanist/systemcomponents/metricsserver/metrics_server.go
  pkg/operation/botanist/systemcomponents/metricsserver/metrics_server_test.go
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3181 Add page on relation between Gardener and Cluster API
  README.md
  docs/README.md
  docs/concepts/cluster-api.md
Labels: area/documentation, needs/changes, size/xs

#3189 Allow gcr copy of golang to be specified
  Dockerfile
  hack/.ci/prepare_release
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#3190 Fix missing metrics-server RBAC roles
  pkg/operation/botanist/systemcomponents/metricsserver/metrics_server.go
  pkg/operation/botanist/systemcomponents/metricsserver/metrics_server_test.go
Labels: area/usability, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3192 Fix test namespace dump accidentally reusing a potentially expired context
  test/framework/shootframework.go
Labels: area/testing, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3184 Fix node local dns issue for control plane pods
  charts/global-network-policies/templates/allow-to-dns.yaml
  charts/global-network-policies/values.yaml
  pkg/operation/botanist/controlplane.go
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3194 Editable dashboards by default
  charts/seed-monitoring/charts/grafana/dashboards/operators/cluster-overview-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/etcd-backup-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/etcd-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/kubernetes-daemonsets-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/kubernetes-statefulsets-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/vpn-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-control-plane-status-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-details-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-pool-dashboard.json
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3082 Add apiserver-proxy webhook to all SNI enabled clusters
  charts/images.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/deployment.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/hvpa.yaml
  charts/seed-controlplane/charts/kube-apiserver/values.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-pod-mutatingwebhook.yaml
  charts/shoot-core/components/charts/apiserver-proxy/values.yaml
  charts/shoot-core/components/values.yaml
  docs/README.md
  docs/usage/apiserver-sni-injection.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/federatedseed/networkpolicy/controller.go
  pkg/gardenlet/controller/federatedseed/networkpolicy/helper/helper.go
  pkg/gardenlet/controller/federatedseed/networkpolicy/helper/helper_test.go
  pkg/gardenlet/controller/federatedseed/networkpolicy/hostnameresolver/resolver.go
  pkg/gardenlet/controller/federatedseed/networkpolicy/hostnameresolver/resolver_test.go
  pkg/gardenlet/controller/federatedseed/networkpolicy/namespace_control.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/dns.go
  pkg/operation/botanist/dns_test.go
  pkg/operation/common/types.go
Labels: area/networking, kind/api-change, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, size/xl

#3099 Refactor etcd-druid deployment
  charts/seed-bootstrap/charts/etcd-druid/Chart.yaml
  charts/seed-bootstrap/charts/etcd-druid/charts/utils-templates
  charts/seed-bootstrap/charts/etcd-druid/templates/configmap-imagevector-overwrite.yaml
  charts/seed-bootstrap/charts/etcd-druid/templates/controller-deployment.yaml
  charts/seed-bootstrap/charts/etcd-druid/templates/druid-clusterrole.yaml
  charts/seed-bootstrap/charts/etcd-druid/templates/druid-rolebinding.yaml
  charts/seed-bootstrap/charts/etcd-druid/templates/service-account.yaml
  charts/seed-bootstrap/charts/etcd-druid/templates/vpa.yaml
  charts/seed-bootstrap/charts/etcd-druid/values.yaml
  charts/seed-bootstrap/values.yaml
  pkg/operation/botanist/controlplane/clusterautoscaler/bootstrap.go
  pkg/operation/botanist/controlplane/clusterautoscaler/bootstrap_test.go
  pkg/operation/botanist/controlplane/etcd/bootstrap.go
  pkg/operation/botanist/controlplane/etcd/bootstrap_test.go
  pkg/operation/seed/seed.go
Labels: area/dev-productivity, area/quality, area/robustness, exp/intermediate, kind/technical-debt, kind/test, needs/changes, needs/ok-to-test, platform/all, priority/normal, size/xl, topology/seed

#3196 Reconcile Infrastructure for hibernated clusters
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
Labels: area/robustness, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3195 Log checkAPIServerAvailability errors
  pkg/controllermanager/controller/plant/plant_health.go
  pkg/operation/botanist/health_check.go
  pkg/utils/kubernetes/health/health.go
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3197 Fix namespace not resetting on deletion failures and beautify dump output
  test/framework/dump.go
  test/framework/shootframework.go
Labels: area/testing, kind/bug, kind/enhancement, needs/ok-to-test, priority/normal, size/xs

#3198 Fix statefulset name retrieval for etcd
  pkg/operation/botanist/controlplane/etcd/etcd.go
  pkg/operation/botanist/controlplane/etcd/etcd_test.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3201 Fix flaky test in managed resource registry utility
  pkg/utils/managedresources/registry_test.go
Labels: area/testing, kind/flake, needs/ok-to-test, priority/normal, size/xs

#3202 Upgrade NPD to v0.8.5
  charts/images.yaml
  charts/shoot-core/components/charts/node-problem-detector/README.md
  charts/shoot-core/components/charts/node-problem-detector/values.yaml
Labels: area/open-source, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3204 Allow injecting arbitrary EnvVars into terraformer pods
  extensions/pkg/terraformer/config.go
  extensions/pkg/terraformer/terraformer.go
  extensions/pkg/terraformer/types.go
  pkg/mock/gardener/extensions/terraformer/mocks.go
Labels: area/quality, area/security, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3203 Fix allow to apiserver network policy
  pkg/gardenlet/controller/federatedseed/networkpolicy/controller.go
  pkg/gardenlet/controller/federatedseed/networkpolicy/hostnameresolver/resolver.go
  pkg/gardenlet/controller/federatedseed/networkpolicy/hostnameresolver/resolver_test.go
Labels: area/control-plane, kind/regression, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3207 Expose further configuration options for gardener-apiserver
  charts/gardener/controlplane/charts/application/templates/validatingwebhook-admission-controller.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/_helpers.tpl
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/values.yaml
  cmd/gardener-apiserver/app/gardener_apiserver.go
Labels: area/scalability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3200 Special handling for central cadvisor scrape config relabel config
  charts/seed-bootstrap/templates/prometheus/config.yaml
  charts/seed-bootstrap/values.yaml
  pkg/operation/botanist/component/types.go
  pkg/operation/botanist/controlplane/etcd/monitoring.go
  pkg/operation/botanist/controlplane/etcd/monitoring_test.go
  pkg/operation/seed/seed.go
Labels: area/monitoring, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3209 Fix shoot constraints to not contain duplicates
  pkg/operation/botanist/constraints_check.go
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3211 Set dnsPolicy to Deault for Shoot system components
  charts/shoot-core/components/charts/network-policies/templates/allow-to-dns.yaml
  charts/shoot-core/components/charts/node-problem-detector/templates/daemonset.yaml
  charts/shoot-core/components/charts/vpn-shoot/templates/deployment.yaml
  pkg/operation/botanist/addons/networkpolicy/shoot_network_policy_suite_test.go
  pkg/operation/botanist/systemcomponents/metricsserver/metrics_server.go
  pkg/operation/botanist/systemcomponents/metricsserver/metrics_server_test.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#2996 Integration test for the logging stack
  test/framework/common.go
  test/framework/resources/templates/logger-app.yaml.tpl
  test/framework/shoot_utils.go
  test/framework/shootframework.go
  test/integration/shoots/logging/logging.go
  test/integration/shoots/logging/seed_log.go
  test/integration/shoots/logging/utils.go
Labels: area/logging, kind/test, needs/changes, needs/ok-to-test, priority/normal, size/l

#3212 ConfigMap checksum in annotation for etcd-druid deployment
  pkg/operation/botanist/controlplane/etcd/bootstrap.go
  pkg/operation/botanist/controlplane/etcd/bootstrap_test.go
Labels: area/usability, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3213 Upgrade Prometheus to v2.22.2
  charts/images.yaml
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3215 Cleanup HealthChecker from migration logics
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/health_check_test.go
Labels: kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3199 Add Pod scheduler name webhook in seed-admission-controller
  cmd/gardener-seed-admission-controller/app/app_suite_test.go
  cmd/gardener-seed-admission-controller/app/gardener_seed_admission_controller.go
  cmd/gardener-seed-admission-controller/app/testdata/admission.json
  cmd/gardener-seed-admission-controller/app/testdata/ca.crt
  cmd/gardener-seed-admission-controller/app/testdata/dummy-kubeconfig.yaml
  cmd/gardener-seed-admission-controller/app/testdata/tls.crt
  cmd/gardener-seed-admission-controller/app/testdata/tls.key
  go.mod
  go.sum
  pkg/operation/seed/scheduler/types.go
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/testcerts/certs.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/testcerts/doc.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/testcerts/gencerts.sh
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/testing/authentication_info_resolver.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/testing/service_resolver.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/testing/testcase.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/testing/webhook_server.go
  vendor/modules.txt
Labels: area/control-plane, area/cost, area/scalability, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, size/l

#3217 Clean up more migration logic
  extensions/pkg/controller/csimigration/reconciler_test.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/seed/seed.go
  pkg/operation/types.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  pkg/utils/kubernetes/patch.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
  test/framework/dump.go
Labels: kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3017 [GEP-13] Automated Seed Management
  docs/README.md
  docs/proposals/13-automated-seed-management.md
Labels: area/documentation, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, size/l

#3206 Refactor seed bootstrapping to DeployWaiter components
  pkg/operation/botanist/component/interfaces.go
  pkg/operation/botanist/controlplane/clusterautoscaler/bootstrap.go
  pkg/operation/botanist/controlplane/clusterautoscaler/bootstrap_test.go
  pkg/operation/botanist/controlplane/etcd/bootstrap.go
  pkg/operation/botanist/controlplane/etcd/bootstrap_test.go
  pkg/operation/seed/seed.go
Labels: area/dev-productivity, area/quality, kind/cleanup, needs/changes, needs/ok-to-test, priority/normal, size/xl

#3221 Pin sigs.k8s.io/structured-merge-diff/v3 back to upstream
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v3/value/reflectcache.go
Labels: kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3220 Switch to "gardener.cloud/role" label key for system components
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/deployment-dashboard.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/deployment-metrics-scraper.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-daemonset.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-deployment.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/default-backend-deployment.yaml
  charts/shoot-core/components/charts/coredns/templates/coredns-deployment.yaml
  charts/shoot-core/components/charts/konnectivity-agent/templates/daemonset.yaml
  charts/shoot-core/components/charts/kube-proxy/templates/kube-proxy-daemonset.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-from-seed.yaml
  charts/shoot-core/components/charts/node-problem-detector/templates/daemonset.yaml
  charts/shoot-core/components/charts/nodelocal-dns/templates/daemonset.yaml
  charts/shoot-core/components/charts/vpn-shoot/templates/deployment.yaml
  docs/extensions/shoot-health-status-conditions.md
  hack/local-development/local-garden/apply-rbac-garden-ns
  pkg/gardenlet/controller/federatedseed/networkpolicy/controller.go
  pkg/gardenlet/controller/seed/seed.go
  pkg/gardenlet/controller/shoot/seed_registration_control.go
  pkg/operation/botanist/cleanup.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/systemcomponents/metricsserver/metrics_server.go
  pkg/operation/botanist/systemcomponents/metricsserver/metrics_server_test.go
  pkg/operation/garden/garden.go
Labels: kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3216 Remove GardenerID and GardenerName checks from CheckSeed method
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/utils/kubernetes/health/health.go
  pkg/utils/kubernetes/health/health_test.go
Labels: area/control-plane-migration, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, size/s

#3219 Parse the time zones from logs and set the tail plugin to read from head
  charts/seed-bootstrap/charts/fluent-bit/templates/_fluent-bit-config.tpl
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-configmap.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-role.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3223 Cleanup terraformer library
  extensions/pkg/controller/infrastructure/reconciler.go
  extensions/pkg/controller/worker/reconciler.go
  extensions/pkg/terraformer/config.go
  extensions/pkg/terraformer/errors.go
  extensions/pkg/terraformer/state.go
  extensions/pkg/terraformer/terraform_test.go
  extensions/pkg/terraformer/terraformer.go
  extensions/pkg/terraformer/types.go
  extensions/pkg/terraformer/waiter.go
  pkg/mock/gardener/extensions/terraformer/mocks.go
Labels: area/logging, area/quality, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xl

#3228 Add minAllowed VPA ResourcePolicy for Cluster Autoscaler
  pkg/operation/botanist/controlplane/clusterautoscaler/cluster_autoscaler.go
  pkg/operation/botanist/controlplane/clusterautoscaler/cluster_autoscaler_test.go
Labels: area/robustness, area/scalability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3226 Force gardenlet restart if SNI is enabled in the Seed cluster
  pkg/gardenlet/controller/shoot/seed_registration_control.go
  pkg/gardenlet/controller/shoot/seed_registration_control_test.go
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3229 Clean up migration code for uam role assignment
  docs/usage/projects.md
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/project/project.go
Labels: kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3231 Prepare for label key switch in the health check selector
  charts/seed-bootstrap/charts/loki/values.yaml
  charts/seed-controlplane/charts/gardener-resource-manager/templates/deployment.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/deployment.yaml
  charts/seed-monitoring/charts/alertmanager/templates/alertmanager.yaml
  charts/seed-monitoring/charts/core/charts/kube-state-metrics-shoot/templates/deployment.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-deployment.yaml
  pkg/operation/botanist/controlplane/clusterautoscaler/cluster_autoscaler.go
  pkg/operation/botanist/controlplane/clusterautoscaler/cluster_autoscaler_test.go
  pkg/operation/botanist/controlplane/etcd/etcd.go
  pkg/operation/botanist/controlplane/etcd/etcd_test.go
  pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager_test.go
  pkg/operation/botanist/controlplane/kubescheduler/kube_scheduler.go
  pkg/operation/botanist/controlplane/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/health_check.go
  plugin/pkg/shoot/validator/admission.go
Labels: kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3230 Update pull_request_template.md
  .github/pull_request_template.md
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3235 Do not use FQDN for KUBERNETES_SERVICE_HOST injection
  pkg/operation/botanist/controlplane.go
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3233 Add another special case to set_dependency_version script
  hack/.ci/set_dependency_version
Labels: kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3236 [release-v1.13] Cherry-pick: Do not use FQDN for KUBERNETES_SERVICE_HOST injection
  pkg/operation/botanist/controlplane.go
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3224 Update cloud credentials even for unwanted machine deployments.
  extensions/pkg/controller/worker/genericactuator/actuator.go
  extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/genericactuator/actuator_test.go
  extensions/pkg/controller/worker/genericactuator/interface.go
Labels: area/robustness, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#3241 Remove deprecated label key in networkpolicy test expectations
  extensions/test/e2e/framework/networkpolicies/agnostic.go
Labels: kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3232 Add documentation about shoot networking
  docs/README.md
  docs/usage/shoot_networking.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#3222 Refactor ControlPlane extension deployment into component
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/containerruntime.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/extensions/containerruntime/containerruntime.go
  pkg/operation/botanist/extensions/containerruntime/containerruntime_test.go
  pkg/operation/botanist/extensions/controlplane/controlplane.go
  pkg/operation/botanist/extensions/controlplane/controlplane_suite_test.go
  pkg/operation/botanist/extensions/controlplane/controlplane_test.go
  pkg/operation/botanist/extensions/infrastructure/infrastructure.go
  pkg/operation/botanist/extensions/infrastructure/infrastructure_test.go
  pkg/operation/botanist/infrastructure.go
  pkg/operation/common/extensions.go
  pkg/operation/shoot/types.go
Labels: area/dev-productivity, area/quality, area/robustness, exp/intermediate, kind/technical-debt, kind/test, needs/changes, needs/ok-to-test, platform/all, priority/normal, size/xl, topology/seed

#3248 Garbage collect OutOf* Pods
  pkg/operation/botanist/garbage_collection.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3247 Fix y axis title of 'System services Memory usage'
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-details-dashboard.json
Labels: needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#3245 Fix flaky tests in hostname resolver
  pkg/gardenlet/controller/federatedseed/networkpolicy/hostnameresolver/resolver.go
  pkg/gardenlet/controller/federatedseed/networkpolicy/hostnameresolver/resolver_test.go
Labels: area/testing, kind/flake, needs/ok-to-test, priority/normal, reviewed/lgtm, reviewed/ok-to-test, size/s

#3242 Do not reconcile shoots multiple times during their maintenance time windows
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/shoot.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/gardenlet/controller/shoot/shoot.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/operation/common/utils.go
  pkg/utils/timewindow.go
  pkg/utils/timewindow_test.go
Labels: area/scalability, kind/api-change, kind/enhancement, needs/ok-to-test, priority/critical, reviewed/lgtm, size/m
