Repository gardener/gardener, pull requests merged in 2020-08, with the labels that each got.

#2646 some nits after migration to loki
  extensions/test/e2e/framework/networkpolicies/agnostic.go
  test/framework/common.go
Labels: area/quality, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#2643 Secret generation waits for kube-apiserver LB if shoot DNS disabled
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2647 Add liveness probe for gardener-apiserver
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/values.yaml
Labels: area/high-availability, area/robustness, kind/task, needs/ok-to-test, priority/normal, reviewed/lgtm

#2651 Only pull metrics-server image if not present
  charts/shoot-core/components/charts/metrics-server/templates/deployment.yaml
Labels: area/networking, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#2641 Use `host.docker.internal` in local-garden
  cmd/registry-migrator/job-example.yaml
  example/seed-admission-controller/10-validatingwebhookconfiguration.yaml
  hack/local-development/dev-setup-register-gardener
  hack/local-development/local-garden/certificates/certs/ca.crt
  hack/local-development/local-garden/certificates/certs/default-admin.crt
  hack/local-development/local-garden/certificates/certs/default-controller-manager.crt
  hack/local-development/local-garden/certificates/certs/front-proxy-client.crt
  hack/local-development/local-garden/certificates/certs/kube-apiserver-etcd-client.crt
  hack/local-development/local-garden/certificates/certs/kube-apiserver.crt
  hack/local-development/local-garden/certificates/certs/kube-etcd-healthcheck-client.crt
  hack/local-development/local-garden/certificates/certs/kube-etcd-peer.crt
  hack/local-development/local-garden/certificates/certs/kube-etcd.crt
  hack/local-development/local-garden/certificates/certs/sa.pub
  hack/local-development/local-garden/certificates/keys/ca.key
  hack/local-development/local-garden/certificates/keys/default-admin.key
  hack/local-development/local-garden/certificates/keys/default-controller-manager.key
  hack/local-development/local-garden/certificates/keys/front-proxy-client.key
  hack/local-development/local-garden/certificates/keys/kube-apiserver-etcd-client.key
  hack/local-development/local-garden/certificates/keys/kube-apiserver.key
  hack/local-development/local-garden/certificates/keys/kube-etcd-healthcheck-client.key
  hack/local-development/local-garden/certificates/keys/kube-etcd-peer.key
  hack/local-development/local-garden/certificates/keys/kube-etcd.key
  hack/local-development/local-garden/certificates/keys/sa.key
  hack/local-development/local-garden/garden-certificate-generator.go
  hack/local-development/local-garden/kubeconfigs/default-admin.conf
  hack/local-development/local-garden/kubeconfigs/default-controller-manager.conf
  hack/local-development/local-garden/run-kube-apiserver
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2652 Optimize resource usage for fluent-bit and loki
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
  charts/seed-bootstrap/charts/loki/templates/vpa.yaml
  charts/seed-bootstrap/charts/loki/values.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2576 [GEP-7] Add DNSOwner to Shoot operations to support migration scenario
  charts/seed-dns/owner/Chart.yaml
  charts/seed-dns/owner/templates/dnsowner.yaml
  charts/seed-dns/owner/values.yaml
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_migrate.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/addons_test.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/controlplane_test.go
  pkg/operation/botanist/dns.go
  pkg/operation/botanist/dns_test.go
  pkg/operation/botanist/extensions/dns/dnsowner.go
  pkg/operation/botanist/extensions/dns/dnsowner_test.go
  pkg/operation/shoot/types.go
Labels: area/control-plane-migration, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2656 [release-v1.7] Fix WaitCleanup for Network
  pkg/operation/botanist/extensions/network/network.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2658 Fix cluster hibernation issue on worker controller
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
Labels: area/dev-productivity, kind/regression, needs/ok-to-test, priority/critical, reviewed/lgtm

#2636 Rearranging control plane migration task order to ensure that all objects are deleted
  pkg/gardenlet/controller/shoot/shoot_control_migrate.go
Labels: area/control-plane-migration, kind/enhancement, needs/ok-to-test, needs/review, priority/normal, status/author-action

#2660 Change default webhook server port to 10250
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-admission-controller.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/service-admission-controller.yaml
  charts/seed-bootstrap/charts/vpa/values.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/deployment.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/service.yaml
  charts/seed-bootstrap/values.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2659 Skip BackupEntry deletion if referred secret not found
  extensions/pkg/controller/backupentry/reconciler.go
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2661 Fix enqueuing namespaces for netpol controller
  pkg/gardenlet/controller/federatedseed/networkpolicy/endpoints.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, priority/blocker, reviewed/lgtm

#2169 introduce scheduling method Selector
  docs/concepts/scheduler.md
  go.mod
  go.sum
  hack/api-reference/core.md
  hack/update-protobuf.sh
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_cloudprofile.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  pkg/scheduler/controller/shoot/distance.go
  pkg/scheduler/controller/shoot/distance_test.go
  pkg/scheduler/controller/shoot/scheduler_control.go
  pkg/scheduler/controller/shoot/scheduler_test.go
  vendor/github.com/texttheater/golang-levenshtein/LICENSE
  vendor/github.com/texttheater/golang-levenshtein/levenshtein/levenshtein.go
  vendor/modules.txt
Labels: area/usability, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, topology/garden

#2662 Update PR template
  .github/pull_request_template.md
Labels: area/open-source, kind/task, needs/ok-to-test, priority/normal, reviewed/lgtm

#2664 Fix VPA webhook port configuration
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-admission-controller.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-exporter.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/service-admission-controller.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/service-exporter.yaml
  charts/seed-bootstrap/charts/vpa/values.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/networkpolicy-allow-kube-apiserver-policy.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2666 Treat machines w/o status as pending
  extensions/pkg/controller/healthcheck/worker/helpers.go
  extensions/pkg/controller/healthcheck/worker/helpers_test.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2663 Add utility function to refresh shoot webhook netpols
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
Labels: area/networking, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2665 Allow extensions to overwrite service port for webhook registration
  extensions/pkg/webhook/cmd/options.go
  extensions/pkg/webhook/registration.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2667 Increase leader election settings for shoot's GRM
  charts/images.yaml
  charts/seed-controlplane/charts/gardener-resource-manager/templates/deployment.yaml
  charts/seed-controlplane/charts/gardener-resource-manager/values.yaml
  pkg/operation/botanist/controlplane.go
Labels: area/cost, area/networking, area/robustness, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2668 Make watch cache sizes configurable
  charts/seed-controlplane/charts/kube-apiserver/templates/_helpers.tpl
  charts/seed-controlplane/charts/kube-apiserver/templates/deployment.yaml
  charts/seed-controlplane/charts/kube-apiserver/values.yaml
  example/90-shoot.yaml
  hack/api-reference/core.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/controlplane.go
Labels: area/cost, area/networking, area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2672 Set revisionHistoryLimit=0 for Deployments when missing
  charts/seed-bootstrap/charts/etcd-druid/templates/controller-deployment.yaml
  charts/seed-bootstrap/charts/hvpa/templates/controller-deployment.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-admission-controller.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-exporter.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-recommender.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-updater.yaml
Labels: area/ops-productivity, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#2669 Clean-up DNS provider migration
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: area/robustness, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#2674 Nit: Update to golang@1.14.7
  Dockerfile
Labels: kind/task, needs/ok-to-test, priority/normal, reviewed/lgtm

#2137 [GEP-10] Add validation for CRIs and CRs
  example/30-cloudprofile.yaml
  hack/api-reference/core.md
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/helper/helper.go
  pkg/apis/core/v1alpha1/helper/helper_test.go
  pkg/apis/core/v1alpha1/types_cloudprofile.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/validation/controllerregistration.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control_test.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/global/resourcereferencemanager/admission_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  test/integration/shoots/maintenance/maintenance.go
Labels: area/robustness, area/usability, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, topology/garden

#2671 Add toleration for fluent-bit to run on masters
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2676 Fix seed bootstrap for new seeds
  pkg/operation/common/utils.go
Labels: area/robustness, kind/bug, needs/ok-to-test, priority/critical, reviewed/lgtm

#2678 Fix dependencies in shoot flow
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: area/robustness, kind/bug, needs/ok-to-test, priority/critical, reviewed/lgtm

#2679 Creates new objects every time artifact.newFunc is called
  pkg/gardenlet/controller/federatedseed/extensions/artifact.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, priority/blocker, reviewed/lgtm

#2680 [Release-v1.8] Prepare hotfix
  Dockerfile
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
  pkg/gardenlet/controller/federatedseed/extensions/artifact.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/common/utils.go
Labels: area/robustness, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2681 Ensure cluster identity in deletion flow
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/operation/botanist/controlplane.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/critical, reviewed/lgtm

#2682 Update k8s.io/kube-openapi to forked version for bugfix for embedded pointer structs
  go.mod
  go.sum
  pkg/openapi/openapi_generated.go
  vendor/k8s.io/kube-openapi/pkg/generators/openapi.go
  vendor/modules.txt
Labels: area/quality, kind/bug, needs/ok-to-test, priority/critical, reviewed/lgtm

#2693 Update conformance test matrix
  README.md
Labels: area/quality, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#2700 Don't execute shoot health checks simultaneously
  pkg/gardenlet/controller/backupentry/backup_entry_controller.go
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/utils/random.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2699 Always allow project owner to be added to member list when creating a new project
  plugin/pkg/global/customverbauthorizer/admission.go
  plugin/pkg/global/customverbauthorizer/admission_test.go
Labels: area/quality, exp/intermediate, kind/bug, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, size/s, topology/garden

#2702 Extend error code mapping
  pkg/apis/core/v1beta1/helper/errors.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, size/xs, topology/garden

#2701 Remove experimental Kyma addon
  charts/shoot-addons-kyma/Chart.yaml
  charts/shoot-addons-kyma/charts/kyma/Chart.yaml
  charts/shoot-addons-kyma/charts/kyma/charts/utils-templates
  charts/shoot-addons-kyma/charts/kyma/files/installation.sh
  charts/shoot-addons-kyma/charts/kyma/files/requirements.sh
  charts/shoot-addons-kyma/charts/kyma/files/tiller.sh
  charts/shoot-addons-kyma/charts/kyma/files/wait-for-tiller.sh
  charts/shoot-addons-kyma/charts/kyma/templates/clusterrolebinding.yaml
  charts/shoot-addons-kyma/charts/kyma/templates/job-installation.yaml
  charts/shoot-addons-kyma/charts/kyma/templates/job-tiller.yaml
  charts/shoot-addons-kyma/charts/kyma/templates/namespace.yaml
  charts/shoot-addons-kyma/charts/kyma/templates/serviceaccount.yaml
  charts/shoot-addons-kyma/charts/kyma/values.yaml
  charts/shoot-addons-kyma/requirements.yaml
  charts/shoot-addons-kyma/values.yaml
  pkg/apis/core/validation/shoot.go
  pkg/operation/botanist/addons.go
  pkg/operation/common/types.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: area/open-source, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#2695 Improve condition when VPA for shooted seeds is disabled
  pkg/gardenlet/controller/shoot/seed_registration_control.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: area/quality, kind/bug, needs/ok-to-test, platform/all, priority/critical, reviewed/lgtm, size/xs, topology/garden, topology/seed

#2698 Add VPA control plane health check
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-admission-controller.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-exporter.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-recommender.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-updater.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/constants/utils.go
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/health_check_test.go
  pkg/operation/common/utils.go
  pkg/operation/seed/seed.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2704 Improve error message when zones for region without zones are configured
  plugin/pkg/shoot/validator/admission.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2708 Fix concurrent map writes
  pkg/operation/botanist/addons.go
Labels: area/robustness, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2711 Add etcds/finalizers to etcd-druid RBAC role
  charts/seed-bootstrap/charts/etcd-druid/templates/druid-clusterrole.yaml
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2713 Consider deprecated VPA labels for health checks
  pkg/operation/botanist/health_check.go
  pkg/operation/botanist/health_check_test.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2715 Fix VPA deletion in both seed and shoot
  charts/images.yaml
  charts/seed-bootstrap/charts/vpa/charts/application/templates/crd-verticalpodautoscalercheckpoints.yaml
  charts/seed-bootstrap/charts/vpa/charts/application/templates/crd-verticalpodautoscalers.yaml
  docs/usage/shoot_autoscaling.md
  pkg/operation/common/utils.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2716 Nit: allow "make verify" to pass also with helm3
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-admission-controller.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-exporter.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-recommender.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-updater.yaml
Labels: needs/ok-to-test, priority/normal, reviewed/lgtm

#2694 [GEP-7] Don't add entries with empty data in ShootState
  pkg/operation/shootsecrets/secrets_manager.go
  pkg/operation/shootsecrets/secrets_manager_test.go
  pkg/utils/infodata/infodata.go
  pkg/utils/infodata/infodata_test.go
  pkg/utils/infodata/types.go
  pkg/utils/secrets/control_plane.go
Labels: area/control-plane-migration, kind/enhancement, needs/ok-to-test, needs/review, priority/normal

#2717 Change fluent-bit version to v.0.23.0
  charts/images.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-role.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2718 Revert labels for seed VPA deployment
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-admission-controller.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-exporter.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-recommender.yaml
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-updater.yaml
  pkg/operation/botanist/health_check.go
  pkg/operation/seed/seed.go
Labels: area/control-plane, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#2720 Dedicated network policy for kube-apiserver-to-vpa communication
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/networkpolicy.yaml
  charts/seed-controlplane/charts/kube-apiserver/templates/networkpolicy-allow-kube-apiserver-policy.yaml
  charts/seed-controlplane/charts/kube-apiserver/values.yaml
  pkg/operation/botanist/controlplane.go
  pkg/operation/common/utils.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2612 Ignore ctrlreg in deletion when computing required ctrlinsts
  pkg/controllermanager/controller/controllerregistration/controllerregistration_seed_control.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration_seed_control_test.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2725 Make the fluent-bit metrics port accessible via port-forward
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2723 Increase resource requests for fluent-bit
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, needs/review, priority/normal

#2727 Updating hvpa-controller version:v0.3.0->v0.3.1
  charts/images.yaml
Labels: area/auto-scaling, kind/impediment, needs/ok-to-test, priority/normal, reviewed/lgtm

#2728 Add readiness probe for gardener-apiserver
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/values.yaml
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go
  vendor/modules.txt
Labels: area/quality, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2601 Updated monitoring and logging extension docs
  docs/README.md
  docs/extensions/logging-and-monitoring.md
Labels: area/logging, area/monitoring, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2733 Change fluent-bit image
  charts/images.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-configmap.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2649 Add Event Controller
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  charts/gardener/controlplane/values.yaml
  docs/concepts/controller-manager.md
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/types_common.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/defaults_test.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
  pkg/controllermanager/controller/event/event.go
  pkg/controllermanager/controller/event/event_control.go
  pkg/controllermanager/controller/event/event_control_test.go
  pkg/controllermanager/controller/event/event_suite_test.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/shoot/shoot_hibernation_control.go
  pkg/controllermanager/controller/shoot/shoot_hibernation_control_test.go
  pkg/controllermanager/controller/shoot/shoot_hibernation_types.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/gardenlet/controller/shoot/controllerinstallation_control.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/scheduler/controller/shoot/scheduler_control.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2740 Increase concurrent syncs for KCM controllers
  charts/seed-controlplane/charts/kube-controller-manager/templates/kube-controller-manager.yaml
Labels: area/scalability, exp/beginner, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, topology/seed

#2746 Prevent optimistic lock errors during 'MaintainShootAnnotations' step
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2735 Remove gardener-seed-admission mutatingwebhookconfiguration
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-configmap.yaml
  charts/seed-bootstrap/templates/gardener-seed-admission-controller/mutatingwebhookconfiguration.yaml
  cmd/gardener-seed-admission-controller/app/gardener_seed_admission_controller.go
  pkg/operation/seed/seed.go
  pkg/seedadmission/pods.go
  pkg/seedadmission/pods_test.go
Labels: area/logging, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#2748 Update konnectivity-tunnel to v0.0.12
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2749 Remove terminationGracePeriodSeconds from gardener manifests
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/scheduler/deployment.yaml
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
Labels: area/high-availability, area/ops-productivity, area/robustness, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2753 Fix unknown flags for kube-controller-manager
  charts/seed-controlplane/charts/kube-controller-manager/templates/kube-controller-manager.yaml
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2756 Auto-restart scheduler in shoot maintenance
  charts/seed-controlplane/charts/kube-scheduler/templates/kube-scheduler.yaml
  charts/seed-controlplane/charts/kube-scheduler/values.yaml
  pkg/operation/botanist/controlplane.go
Labels: area/ops-productivity, area/robustness, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2750 Deploy logging stack earlier in the reconciliation flow
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2757 Remove shoot controller tasks immediately after they are completed
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: area/networking, area/robustness, kind/enhancement, needs/ok-to-test, needs/review, priority/normal

#2737 Add new fluent-bit filters/parsers
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-configmap.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2752 Fix wrong API groups
  pkg/client/kubernetes/types.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/monitoring.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/critical, reviewed/lgtm

#2760 Nit: Use logrus.FieldLogger instead of logrus.Entry
  pkg/operation/botanist/controlplane/kube_apiserver_service.go
  pkg/operation/botanist/controlplane/kube_apiserver_service_test.go
  pkg/operation/botanist/extensions/dns/dnsentry.go
  pkg/operation/botanist/extensions/dns/dnsentry_test.go
  pkg/operation/botanist/extensions/dns/dnsprovider.go
  pkg/operation/botanist/extensions/dns/dnsprovider_test.go
  pkg/operation/botanist/extensions/infrastructure/infrastructure.go
  pkg/operation/botanist/extensions/infrastructure/infrastructure_test.go
  pkg/operation/botanist/extensions/network/network.go
  pkg/operation/botanist/extensions/network/network_test.go
  pkg/operation/common/extensions.go
  pkg/operation/common/extensions_test.go
Labels: area/dev-productivity, needs/ok-to-test, priority/normal, reviewed/lgtm

#2764 Forward user information to GAPI in local setup
  hack/local-development/local-garden/run-kube-apiserver
Labels: area/dev-productivity, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2763 Always allow project admins to manage non-human users
  plugin/pkg/global/customverbauthorizer/admission.go
  plugin/pkg/global/customverbauthorizer/admission_test.go
Labels: area/user-management, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2759 Report failed machines for hibernated clusters
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/helper/helper.go
  extensions/pkg/controller/worker/helper/helper_test.go
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#2765 Add doc about Shoot status
  docs/README.md
  docs/usage/shoot_status.md
  extensions/pkg/controller/healthcheck/healtcheck_actuator.go
  pkg/apis/core/types_common.go
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/core/v1beta1/types_common.go
Labels: area/documentation, kind/task, needs/ok-to-test, priority/normal, reviewed/lgtm

#2761 Deny shoots referencing absent DNS provider secrets
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/global/resourcereferencemanager/admission_test.go
Labels: area/robustness, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, reviewed/ok-to-test

#2768 Try to output YAML diff in matcher
  test/gomega/deep_derivative.go
  test/gomega/matchers.go
Labels: area/dev-productivity, area/testing, kind/enhancement, needs/ok-to-test, needs/review, priority/normal

#2772 Cleanup leader election clients/recorders
  cmd/gardener-controller-manager/app/gardener_controller_manager.go
  cmd/gardener-scheduler/app/gardener_scheduler.go
  cmd/gardenlet/app/gardenlet.go
Labels: area/quality, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#2773 minAllowed for vpa-recommender
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/vpa-recommender.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2777 Make AfterSuite hooks ordered
  test/framework/cleanup.go
Labels: area/testing, kind/task, needs/ok-to-test, priority/normal, reviewed/lgtm

#2769 Add new dashboard for fluent-bit
  charts/seed-bootstrap/dashboards/fluent-bit-dashboard.json
  charts/seed-bootstrap/dashboards/systemd-logs.json
  charts/seed-bootstrap/values.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, reviewed/ok-to-test

#2776 Refactor alerts
  charts/seed-bootstrap/aggregate-prometheus-rules-tests/fluent-bit.rules.test.yaml
  charts/seed-bootstrap/aggregate-prometheus-rules-tests/loki.rules.test.yaml
  charts/seed-bootstrap/aggregate-prometheus-rules/fluent-bit.rules.yaml
  charts/seed-bootstrap/aggregate-prometheus-rules/loki.rules.yaml
  charts/seed-bootstrap/templates/alertmanager/_config.tpl
  charts/seed-bootstrap/templates/alertmanager/alertmanager.yaml
  charts/seed-monitoring/charts/alertmanager/templates/_config.tpl
  charts/seed-monitoring/charts/alertmanager/templates/alertmanager.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/optional-rules/cluster-autoscaler.rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules-tests/kube-apiserver.rules.test.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules-tests/kube-kubelet.rules.test.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules-tests/kube-state-metrics.rules.test.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-apiserver.rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-etcd3.rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-kubelet.rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-state-metrics.rules.yaml
Labels: area/monitoring, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#2732 Prevent deletion of seed cluster which is still in use
  cmd/gardener-apiserver/app/gardener_apiserver.go
  docs/concepts/apiserver_admission_plugins.md
  plugin/pkg/seed/validator/admission.go
  plugin/pkg/seed/validator/admission_test.go
  plugin/pkg/seed/validator/validator_suite_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  plugin/pkg/utils/miscellaneous.go
  plugin/pkg/utils/miscellaneous_test.go
Labels: area/robustness, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2775 use ext4 filesystem with project quota support
  charts/shoot-cloud-config/templates/scripts/_cloud-config-script.sh
Labels: area/os, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2731 Refactor kube-scheduler deployment
  charts/seed-controlplane/charts/kube-scheduler/Chart.yaml
  charts/seed-controlplane/charts/kube-scheduler/charts/utils-templates
  charts/seed-controlplane/charts/kube-scheduler/templates/_helpers.tpl
  charts/seed-controlplane/charts/kube-scheduler/templates/componentconfig.yaml
  charts/seed-controlplane/charts/kube-scheduler/templates/kube-scheduler-vpa.yaml
  charts/seed-controlplane/charts/kube-scheduler/templates/kube-scheduler.yaml
  charts/seed-controlplane/charts/kube-scheduler/values.yaml
  extensions/pkg/webhook/controlplane/kubeletconfigcodec.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/controlplane/kubescheduler/kube_scheduler.go
  pkg/operation/botanist/controlplane/kubescheduler/kube_scheduler_suite_test.go
  pkg/operation/botanist/controlplane/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/wanted_secrets.go
  pkg/operation/common/types.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
  pkg/operation/shootsecrets/secrets_manager_test.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
  pkg/utils/secrets/control_plane.go
Labels: area/control-plane, area/dev-productivity, area/quality, area/robustness, area/testing, exp/intermediate, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, topology/seed

#2788 Fix for missing DNSOwner CRD when shootDNS is disabled
  charts/seed-bootstrap/templates/extensions/crd-dnsowner.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, priority/normal

#2542 Gardenlet certificate rotation
  cmd/gardenlet/app/bootstrap.go
  cmd/gardenlet/app/gardenlet.go
  docs/concepts/gardenlet.md
  pkg/client/kubernetes/client.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/bootstrap/bootstrap.go
  pkg/gardenlet/bootstrap/bootstrap_test.go
  pkg/gardenlet/bootstrap/certificate/certificate.go
  pkg/gardenlet/bootstrap/certificate/certificate_rotation.go
  pkg/gardenlet/bootstrap/certificate/certificate_rotation_test.go
  pkg/gardenlet/bootstrap/certificate/certificate_suite_test.go
  pkg/gardenlet/bootstrap/certificate/certificate_util.go
  pkg/gardenlet/bootstrap/util/bootstrap_util_suite_test.go
  pkg/gardenlet/bootstrap/util/util.go
  pkg/gardenlet/bootstrap/util/util_test.go
  pkg/gardenlet/controller/shoot/seed_registration_control.go
Labels: area/security, area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2780 Upgrade Loki version
  charts/images.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#2793 Allow administrator to list namespaces and manage RBACs and admission webhooks
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
Labels: area/ops-productivity, area/user-management, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm
