Repository gardener/gardener, pull requests merged in 2022-09, with the labels that each got.

#6604 GitHub Workflows security hardening
  .github/workflows/release-milestone.yaml
Labels: kind/enhancement, area/security, size/XS, ok-to-test, cla: yes, lgtm, approved

#6608 Adjust metrics-server memory resource requests when VPA is enabled
  pkg/operation/botanist/component/metricsserver/metrics_server.go
  pkg/operation/botanist/component/metricsserver/metrics_server_test.go
Labels: kind/enhancement, size/S, area/scalability, cla: yes, lgtm, approved

#6603 Fix bug in resourcemanager that ignore annotation does handle all possible truthy values
  docs/concepts/resource-manager.md
  pkg/resourcemanager/controller/health/add.go
  pkg/resourcemanager/predicate/ignore.go
  pkg/resourcemanager/predicate/ignore_test.go
Labels: kind/bug, area/quality, size/S, cla: yes, lgtm, approved

#6605 Reduce the size of the grafana dashboards configmap
  charts/seed-bootstrap/templates/grafana/_helpers.tpl
  charts/seed-monitoring/charts/grafana/templates/_helpers.tpl
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#6606 Nit: Clean up unused search textbox in the `Kubernetes Control Plane Status` dashboard
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-control-plane-status-dashboard.json
Labels: area/monitoring, kind/cleanup, size/S, cla: yes, lgtm, approved

#6609 Adapt blackbox exporter resource requests to VPA recommendations
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6610 Make sure the `default-scheduler` is present even when bin-packing is enabled
  pkg/operation/botanist/component/kubescheduler/kube_scheduler.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
Labels: kind/bug, size/XS, area/quality, cla: yes, lgtm, approved

#6549 Exempt `kube-system` namespace in `PodSecurity` admission config
  docs/usage/pod-security.md
  go.mod
  go.sum
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/registry/core/shoot/strategy_test.go
  pkg/utils/kubernetes/admissionplugins.go
  pkg/utils/kubernetes/admissionplugins_test.go
  test/e2e/shoot/create_and_delete_unprivileged.go
  vendor/k8s.io/pod-security-admission/LICENSE
  vendor/k8s.io/pod-security-admission/admission/api/doc.go
  vendor/k8s.io/pod-security-admission/admission/api/helpers.go
  vendor/k8s.io/pod-security-admission/admission/api/register.go
  vendor/k8s.io/pod-security-admission/admission/api/types.go
  vendor/k8s.io/pod-security-admission/admission/api/v1beta1/defaults.go
  vendor/k8s.io/pod-security-admission/admission/api/v1beta1/doc.go
  vendor/k8s.io/pod-security-admission/admission/api/v1beta1/register.go
  vendor/k8s.io/pod-security-admission/admission/api/v1beta1/types.go
  vendor/k8s.io/pod-security-admission/admission/api/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/pod-security-admission/admission/api/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/pod-security-admission/admission/api/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/pod-security-admission/admission/api/zz_generated.deepcopy.go
  vendor/k8s.io/pod-security-admission/api/attributes.go
  vendor/k8s.io/pod-security-admission/api/constants.go
  vendor/k8s.io/pod-security-admission/api/doc.go
  vendor/k8s.io/pod-security-admission/api/helpers.go
  vendor/modules.txt
Labels: kind/enhancement, area/open-source, cla: yes, lgtm, approved, size/XXL

#6616 Update `calico` manifests to `v3.24.1`
  example/gardener-local/calico/calico.yaml
  example/gardener-local/calico/kustomization.yaml
Labels: kind/enhancement, area/dev-productivity, area/testing, cla: yes, lgtm, approved, size/XXL

#6570 Deny setting `.spec.kubernetes.allowPrivilegedContainers` field for Shoot clusters `>=v1.25`
  docs/api-reference/core.md
  docs/usage/pod-security.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/openapi/openapi_generated.go
Labels: kind/enhancement, area/security, size/L, cla: yes, lgtm, approved

#6624 Update profiling docs
  docs/monitoring/profiling.md
Labels: kind/enhancement, size/XS, area/control-plane, cla: yes, lgtm, approved

#6622 Adds more info when comparing secrets for cpm integration tests
  test/framework/shootmigrationtest.go
Labels: size/S, area/testing, area/control-plane-migration, kind/flake, cla: yes, lgtm, approved

#6587 Adds `Progressing` status to `BackupBucketsReady` seed condition
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  charts/gardener/controlplane/values.yaml
  docs/concepts/controller-manager.md
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/defaults_test.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
  pkg/controllermanager/controller/bastion/add_test.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/seed/seed.go
  pkg/controllermanager/controller/seed/seed_backup_bucket_check_control.go
  pkg/controllermanager/controller/seed/seed_backup_bucket_check_control_test.go
  pkg/controllermanager/controller/seed/seed_backup_bucket_reconcile_test.go
  pkg/controllermanager/controller/seed/seed_extension_check_control.go
  pkg/controllermanager/controller/seed/seed_lifecycle_reconcile.go
  pkg/controllermanager/controller/seed/seed_reconcile.go
  pkg/utils/test/client.go
  test/integration/controllermanager/seed/backupbucketscheck/backupbucketscheck_suite_test.go
  test/integration/controllermanager/seed/backupbucketscheck/backupbucketscheck_test.go
Labels: kind/enhancement, area/ops-productivity, cla: yes, lgtm, approved, size/XXL

#6627 Remove release milestone github action
  .github/workflows/release-milestone.yaml
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#6628 Fix the network metrics for clusters with containerd
  charts/seed-bootstrap/templates/prometheus/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/grafana/dashboards/operators/kubernetes-pods-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-details-dashboard.json
Labels: kind/bug, size/L, area/monitoring, cla: yes, lgtm, approved

#6621 Switch `SecretBinding` controller to `controller-runtime`
  docs/concepts/controller-manager.md
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/secretbinding/add.go
  pkg/controllermanager/controller/secretbinding/reconciler.go
  pkg/controllermanager/controller/secretbinding/reconciler_test.go
  pkg/controllermanager/controller/secretbinding/secretbinding.go
  test/integration/controllermanager/secretbinding/secretbinding_suite_test.go
  test/integration/controllermanager/secretbinding/secretbinding_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, area/scalability, cla: yes, lgtm, approved

#6631 Fix shoot events dump
  Makefile
Labels: kind/bug, size/XS, area/testing, cla: yes, lgtm, approved

#6632 Fix failing beta test for ARM shoot
  test/framework/resources/templates/vpntunnel-copy.yaml.tpl
  test/framework/resources/templates/vpntunnel.yaml.tpl
  test/testmachinery/shoots/logging/utils.go
  test/testmachinery/shoots/vpntunnel/vpntunnel.go
Labels: kind/bug, size/S, area/testing, cla: yes, lgtm, approved

#6601 Added metrics needed for multi-node etcd and backup-restore.
  pkg/operation/botanist/component/etcd/monitoring.go
  pkg/operation/botanist/component/etcd/monitoring_test.go
Labels: kind/enhancement, size/M, area/monitoring, cla: yes, lgtm, approved

#6635 Wait for system components to be deployed before checking tunnel connection
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: kind/bug, area/ops-productivity, size/M, cla: yes, lgtm, approved

#6640 [ci:component:github.com/gardener/vpa-exporter:0.1.5->0.3.0]
  charts/images.yaml
  pkg/operation/botanist/component/vpa/exporter.go
  pkg/operation/botanist/component/vpa/vpa_test.go
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6579 [GEP-20] Zone pinning for shoots on multi-zonal seeds 📌
  cmd/gardener-resource-manager/app/app.go
  docs/concepts/resource-manager.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/namespaces.go
  pkg/operation/botanist/namespaces_test.go
  pkg/operation/seed/components.go
  pkg/resourcemanager/webhook/podzoneaffinity/add.go
  pkg/resourcemanager/webhook/podzoneaffinity/handler.go
  pkg/resourcemanager/webhook/podzoneaffinity/handler_test.go
  pkg/resourcemanager/webhook/podzoneaffinity/podzoneaffinity_suite_test.go
  test/integration/resourcemanager/podschedulername/podschedulername_test.go
  test/integration/resourcemanager/podzoneaffinity/podzoneaffinity_suite_test.go
  test/integration/resourcemanager/podzoneaffinity/podzoneaffinity_test.go
  test/integration/resourcemanager/seccompprofile/seccompprofile_test.go
  test/integration/resourcemanager/tokeninvalidator/tokeninvalidator_test.go
Labels: kind/enhancement, area/high-availability, area/control-plane, cla: yes, lgtm, approved, size/XXL

#6647 Deflake `Quota` and `CloudProfile` integration test
  test/integration/controllermanager/cloudprofile/cloudprofile_suite_test.go
  test/integration/controllermanager/cloudprofile/cloudprofile_test.go
  test/integration/controllermanager/quota/quota_suite_test.go
  test/integration/controllermanager/quota/quota_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#6644 Deflake `Shoot` credentials rotation e2e test
  pkg/provider-local/webhook/node/add.go
  test/e2e/shoot/internal/rotation/observability.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#6625 Adds validation of k8s admission plugins
  docs/development/new-kubernetes-version.md
  hack/compare-k8s-admission-plugins.sh
  pkg/apis/core/validation/shoot.go
  pkg/utils/validation/admissionplugins/admissionplugins.go
  pkg/utils/validation/admissionplugins/admissionplugins_suite_test.go
  pkg/utils/validation/admissionplugins/admissionplugins_test.go
Labels: kind/enhancement, area/ops-productivity, area/usability, size/L, cla: yes, lgtm, approved

#6641 Drop gardenlet dependency towards openvpn binary
  Dockerfile
  cmd/gardenlet/main.go
  pkg/utils/secrets/vpn_tlsauth.go
  skaffold.yaml
Labels: area/security, size/M, kind/cleanup, cla: yes, lgtm, approved

#6650 Update to golang 1.19.1
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#6651 Deflake pod-zone-affinity integration test
  test/integration/resourcemanager/podzoneaffinity/podzoneaffinity_suite_test.go
  test/integration/resourcemanager/podzoneaffinity/podzoneaffinity_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#6629 Switch `ControllerRegistration` controller to `controller-runtime`
  docs/concepts/controller-manager.md
  pkg/api/indexer/core.go
  pkg/api/indexer/core_test.go
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/controllerregistration/add.go
  pkg/controllermanager/controller/controllerregistration/backupbucket_control.go
  pkg/controllermanager/controller/controllerregistration/backupbucket_control_test.go
  pkg/controllermanager/controller/controllerregistration/backupentry_control.go
  pkg/controllermanager/controller/controllerregistration/backupentry_control_test.go
  pkg/controllermanager/controller/controllerregistration/controllerdeployment_control.go
  pkg/controllermanager/controller/controllerregistration/controllerinstallation_control.go
  pkg/controllermanager/controller/controllerregistration/controllerinstallation_control_test.go
  pkg/controllermanager/controller/controllerregistration/controllerregistration.go
  pkg/controllermanager/controller/controllerregistration/controllerregistrationfinalizer/add.go
  pkg/controllermanager/controller/controllerregistration/controllerregistrationfinalizer/controllerregistrationfinalizer_suite_test.go
  pkg/controllermanager/controller/controllerregistration/controllerregistrationfinalizer/reconciler.go
  pkg/controllermanager/controller/controllerregistration/controllerregistrationfinalizer/reconciler_test.go
  pkg/controllermanager/controller/controllerregistration/seed/add.go
  pkg/controllermanager/controller/controllerregistration/seed/add_test.go
  pkg/controllermanager/controller/controllerregistration/seed/reconciler.go
  pkg/controllermanager/controller/controllerregistration/seed/reconciler_test.go
  pkg/controllermanager/controller/controllerregistration/seed/seed_suite_test.go
  pkg/controllermanager/controller/controllerregistration/seedfinalizer/add.go
  pkg/controllermanager/controller/controllerregistration/seedfinalizer/reconciler.go
  pkg/controllermanager/controller/controllerregistration/seedfinalizer/reconciler_test.go
  pkg/controllermanager/controller/controllerregistration/seedfinalizer/seedfinalizer_suite_test.go
  pkg/controllermanager/controller/controllerregistration/shoot_control.go
  pkg/controllermanager/controller/controllerregistration/shoot_control_test.go
  pkg/controllermanager/controller/factory.go
  test/integration/controllermanager/controllerregistration/controllerregistration_suite_test.go
  test/integration/controllermanager/controllerregistration/controllerregistration_test.go
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#6637 Remediate already allocated nodePort conflict in provider-local
  pkg/provider-local/controller/service/reconciler.go
Labels: kind/bug, area/dev-productivity, size/M, cla: yes, lgtm, approved

#6619 Deflakes `SeedExtensionsCheck` controller integration test
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_suite_test.go
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#6643 Deflake kubeconfig rotation assertions in `ManagedSeed` e2e test
  test/e2e/managedseed/create_rotate_delete.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#6615 Switch `CertificateSigningRequest` controller to controller-runtime
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  charts/gardener/controlplane/values.yaml
  cmd/gardener-controller-manager/app/app.go
  cmd/gardenlet/app/gardenlet.go
  docs/concepts/controller-manager.md
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/admissioncontroller/webhooks/admission/seedrestriction/admission.go
  pkg/admissioncontroller/webhooks/admission/seedrestriction/admission_test.go
  pkg/admissioncontroller/webhooks/auth/seed/authorizer_test.go
  pkg/admissioncontroller/webhooks/auth/seed/graph/eventhandler_certificatesigningrequest.go
  pkg/admissioncontroller/webhooks/auth/seed/graph/graph.go
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/defaults_test.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/certificatesigningrequest/add.go
  pkg/controllermanager/controller/certificatesigningrequest/certificatesigningrequest.go
  pkg/controllermanager/controller/certificatesigningrequest/certificatesigningrequest_suite_test.go
  pkg/controllermanager/controller/certificatesigningrequest/csr_autoapprove_control.go
  pkg/controllermanager/controller/certificatesigningrequest/reconciler.go
  pkg/controllermanager/controller/certificatesigningrequest/reconciler_test.go
  pkg/controllermanager/controller/factory.go
  pkg/gardenlet/bootstrap/bootstrap.go
  pkg/gardenlet/bootstrap/bootstrap_test.go
  pkg/gardenlet/bootstrap/certificate/certificate.go
  pkg/gardenlet/bootstrap/certificate/certificate_rotation_test.go
  pkg/operation/botanist/matchers/matcher.go
  pkg/operation/care/constraints_test.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
  test/integration/controllermanager/certificatesigningrequest/certificatesigningrequest_suite_test.go
  test/integration/controllermanager/certificatesigningrequest/certificatesigningrequest_test.go
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#6620 Switch `Shoot` controller to `controller-runtime`
  cmd/gardener-controller-manager/app/app.go
  docs/concepts/controller-manager.md
  docs/usage/shoot_status.md
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/shoot/add.go
  pkg/controllermanager/controller/shoot/conditions/add.go
  pkg/controllermanager/controller/shoot/conditions/add_test.go
  pkg/controllermanager/controller/shoot/conditions/conditions_suite_test.go
  pkg/controllermanager/controller/shoot/conditions/reconciler.go
  pkg/controllermanager/controller/shoot/hibernation/add.go
  pkg/controllermanager/controller/shoot/hibernation/add_test.go
  pkg/controllermanager/controller/shoot/hibernation/hibernation_suite_test.go
  pkg/controllermanager/controller/shoot/hibernation/reconciler.go
  pkg/controllermanager/controller/shoot/hibernation/reconciler_test.go
  pkg/controllermanager/controller/shoot/maintenance/add.go
  pkg/controllermanager/controller/shoot/maintenance/add_test.go
  pkg/controllermanager/controller/shoot/maintenance/maintenance_suite_test.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler_test.go
  pkg/controllermanager/controller/shoot/quota/add.go
  pkg/controllermanager/controller/shoot/quota/add_test.go
  pkg/controllermanager/controller/shoot/quota/quota_suite_test.go
  pkg/controllermanager/controller/shoot/quota/reconciler.go
  pkg/controllermanager/controller/shoot/reference/add.go
  pkg/controllermanager/controller/shoot/reference/add_test.go
  pkg/controllermanager/controller/shoot/reference/reconciler.go
  pkg/controllermanager/controller/shoot/reference/reconciler_test.go
  pkg/controllermanager/controller/shoot/reference/reference_suite_test.go
  pkg/controllermanager/controller/shoot/retry/add.go
  pkg/controllermanager/controller/shoot/retry/add_test.go
  pkg/controllermanager/controller/shoot/retry/reconciler.go
  pkg/controllermanager/controller/shoot/retry/retry_suite_test.go
  pkg/controllermanager/controller/shoot/shoot.go
  pkg/controllermanager/controller/shoot/shoot_conditions_control_test.go
  pkg/controllermanager/controller/shoot/shoot_status_label_control.go
  pkg/controllermanager/controller/shoot/statuslabel/add.go
  pkg/controllermanager/controller/shoot/statuslabel/add_test.go
  pkg/controllermanager/controller/shoot/statuslabel/reconciler.go
  pkg/controllermanager/controller/shoot/statuslabel/statuslabel_suite_test.go
  pkg/utils/test/matchers/conditions.go
  test/integration/controllermanager/seed/backupbucketscheck/backupbucketscheck_test.go
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go
  test/integration/controllermanager/shoot/conditions/conditions_suite_test.go
  test/integration/controllermanager/shoot/conditions/conditions_test.go
  test/integration/controllermanager/shoot/hibernation/hibernation_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
  test/integration/controllermanager/shoot/quota/quota_suite_test.go
  test/integration/controllermanager/shoot/quota/quota_test.go
  test/integration/controllermanager/shoot/reference/reference_suite_test.go
  test/integration/controllermanager/shoot/reference/reference_test.go
  test/integration/controllermanager/shoot/retry/retry_suite_test.go
  test/integration/controllermanager/shoot/retry/retry_test.go
  test/integration/controllermanager/shoot/statuslabel/statuslabel_suite_test.go
  test/integration/controllermanager/shoot/statuslabel/statuslabel_test.go
  test/integration/gardenlet/controllerinstallation/care/care_test.go
  test/integration/resourcemanager/health/health_test.go
  test/integration/resourcemanager/managedresource/resource_test.go
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#6658 controller-manager: Prevent nil pointer dereference when `.controllers.certificateSigningRequest` is not specified
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/defaults_test.go
Labels: kind/bug, size/XS, area/quality, cla: yes, lgtm, approved

#6660 Switch back to the upstream node-problem-detector image
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/open-source, cla: yes, lgtm, approved

#6634 Release responsible schedule for v1.57 until v1.63
  docs/development/process.md
Labels: kind/enhancement, area/delivery, size/S, cla: yes, lgtm, approved

#6530 [GEP-20] Introduce shoot spec field for HA control planes, add validations
  docs/README.md
  docs/api-reference/core.md
  docs/usage/shoot_high_availability.md
  example/90-shoot.yaml
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_common.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_common.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile_test.go
  pkg/gardenlet/controller/shoot/shoot_suite_test.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/botanist_test.go
  pkg/operation/botanist/component/etcd/bootstrap.go
  pkg/operation/botanist/component/etcd/bootstrap_test.go
  pkg/operation/botanist/component/etcd/crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  pkg/operation/botanist/component/etcd/crds/templates/crd-druid.gardener.cloud_etcds.yaml
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/etcd/monitoring_test.go
  pkg/operation/botanist/component/etcd/waiter_test.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operation/botanist/namespaces.go
  pkg/operation/botanist/namespaces_test.go
  pkg/operation/shoot/shoot_test.go
  pkg/scheduler/controller/shoot/reconciler.go
  pkg/scheduler/controller/shoot/reconciler_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  test/integration/scheduler/shoot/scheduler_test.go
  test/integration/seedadmissioncontroller/extensioncrds/extensioncrds_test.go
Labels: kind/enhancement, kind/api-change, area/high-availability, cla: yes, lgtm, approved, tide/merge-method-squash, size/XXL

#6649 Handle `v1alpha1` config for `PodSecurity` admission plugin
  docs/usage/pod-security.md
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/utils/test/matchers/matchers.go
  vendor/k8s.io/pod-security-admission/admission/api/v1alpha1/defaults.go
  vendor/k8s.io/pod-security-admission/admission/api/v1alpha1/doc.go
  vendor/k8s.io/pod-security-admission/admission/api/v1alpha1/register.go
  vendor/k8s.io/pod-security-admission/admission/api/v1alpha1/types.go
  vendor/k8s.io/pod-security-admission/admission/api/v1alpha1/zz_generated.conversion.go
  vendor/k8s.io/pod-security-admission/admission/api/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/pod-security-admission/admission/api/v1alpha1/zz_generated.defaults.go
  vendor/modules.txt
Labels: kind/bug, size/XL, area/control-plane, cla: yes, lgtm, approved

#6645 Switch main `Project` controller to `controller-runtime`
  Makefile
  docs/concepts/controller-manager.md
  docs/extensions/project-roles.md
  docs/usage/projects.md
  go.mod
  go.sum
  hack/test-e2e-local.env
  hack/test-e2e-local.sh
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/controllerdeployment/reconciler.go
  pkg/controllermanager/controller/project/add.go
  pkg/controllermanager/controller/project/project.go
  pkg/controllermanager/controller/project/project/add.go
  pkg/controllermanager/controller/project/project/add_test.go
  pkg/controllermanager/controller/project/project/project_suite_test.go
  pkg/controllermanager/controller/project/project/reconciler.go
  pkg/controllermanager/controller/project/project/reconciler_test.go
  pkg/controllermanager/controller/project/project_control.go
  pkg/controllermanager/controller/project/project_control_delete.go
  pkg/controllermanager/controller/project/project_control_reconcile.go
  pkg/controllermanager/controller/project/project_control_test.go
  pkg/controllermanager/controller/project/project_utils.go
  pkg/controllermanager/controller/project/rolebinding_control.go
  pkg/controllermanager/controller/project/rolebinding_control_test.go
  test/e2e/project/project_roles.go
  test/framework/commonframework.go
  test/framework/gardenerframework.go
  test/framework/shootframework.go
  test/integration/controllermanager/project/project/project_suite_test.go
  test/integration/controllermanager/project/project/project_test.go
  test/utils/namespacefinalizer/namespacefinalizer.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/addr/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/defaulter_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#6653 Keep traffic from istio ingress gateway to the target pods in the same zone if possible.
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_sni.go
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_sni_test.go
  pkg/operation/botanist/component/test/istiocomponent.go
  pkg/operation/botanist/component/vpnauthzserver/external_authz_server.go
  pkg/operation/botanist/component/vpnauthzserver/external_authz_server_test.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server_test.go
Labels: kind/enhancement, area/cost, size/M, area/networking, area/high-availability, cla: yes, lgtm, approved

#6664 Fixes `make gardener-down` failing at deletion of `garden` `Project`
  Makefile
  hack/ci-e2e-kind-migration.sh
  hack/ci-e2e-kind.sh
Labels: kind/bug, area/dev-productivity, size/S, cla: yes, lgtm, approved

#6662 Add go vulnerability check
  Makefile
  hack/tools.mk
Labels: kind/enhancement, area/security, size/XS, area/open-source, cla: yes, lgtm, approved

#6638 Support for Kubernetes v1.25
  README.md
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/poddisruptionbudget.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/poddisruptionbudget.yaml
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/poddisruptionbudget.yaml
  charts/gardener/controlplane/charts/runtime/templates/scheduler/poddisruptionbudget.yaml
  charts/gardener/gardenlet/charts/runtime/templates/poddisruptionbudget.yaml
  charts/gardener/provider-local/extension/templates/_helpers.tpl
  charts/gardener/provider-local/extension/templates/poddisruptionbudget.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/pdb.yaml
  charts/utils-templates/templates/_versions.tpl
  docs/usage/supported_k8s_versions.md
  example/provider-local/garden/base/cloudprofile.yaml
  example/provider-local/garden/base/controller-registration.yaml
  example/provider-local/garden/base/kustomization.yaml
  example/provider-local/garden/base/patch-controller-deployment.yaml
  example/provider-local/shoot.yaml
  pkg/client/kubernetes/client.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/component/coredns/coredns.go
  pkg/operation/botanist/component/coredns/coredns_test.go
  pkg/operation/botanist/component/gardenerkubescheduler/gardener_kube_scheduler.go
  pkg/operation/botanist/component/gardenerkubescheduler/gardener_kube_scheduler_test.go
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/poddisruptionbudget.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/poddisruptionbudget.yaml
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/kubeapiserver/horizontalpodautoscaler.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/poddisruptionbudget.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller_test.go
  pkg/operation/botanist/component/vpnauthzserver/external_authz_server.go
  pkg/operation/botanist/component/vpnauthzserver/external_authz_server_test.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operation/seed/components.go
  pkg/operation/seed/seed.go
  pkg/provider-local/imagevector/images.yaml
  pkg/utils/validation/features/featuregates.go
  test/e2e/common.go
  test/e2e/managedseed/create_rotate_delete.go
  test/e2e/shoot/create_and_delete_unprivileged.go
Labels: kind/enhancement, area/open-source, area/usability, cla: yes, lgtm, approved, size/XXL

#6670 Upgrade prometheus-config-reloader
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6652 Configurable log level/format for gardener admission controller
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/configmap-componentconfig.yaml
  charts/gardener/controlplane/values.yaml
  cmd/gardener-admission-controller/app/gardener_admission_controller.go
  cmd/gardener-admission-controller/main.go
  example/20-componentconfig-gardener-admission-controller.yaml
  pkg/admissioncontroller/apis/config/types.go
  pkg/admissioncontroller/apis/config/v1alpha1/defaults.go
  pkg/admissioncontroller/apis/config/v1alpha1/defaults_test.go
  pkg/admissioncontroller/apis/config/v1alpha1/types.go
  pkg/admissioncontroller/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/admissioncontroller/apis/config/validation/admissioncontrollerconfiguration.go
  pkg/admissioncontroller/apis/config/validation/admissioncontrollerconfiguration_test.go
Labels: kind/enhancement, size/M, area/control-plane, cla: yes, lgtm, approved

#6669 Use `Fail` policy for shoot webhook in `provider-local`
  extensions/pkg/webhook/shoot/shoot.go
  pkg/provider-local/webhook/shoot/add.go
Labels: area/dev-productivity, size/S, kind/flake, cla: yes, lgtm, approved

#6672 Bump `nginx-ingress-controller-seed` to `v1.3.1` for `1.22+` seeds
  charts/images.yaml
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
Labels: kind/enhancement, area/open-source, size/M, cla: yes, lgtm, approved

#6676 Use /usr/bin/env bash in Makefile
  Makefile
Labels: kind/enhancement, size/XS, ok-to-test, cla: yes, lgtm, approved

#6673 Deflake Shoot Maintenance controller integration test
  charts/images.yaml
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/controllermanager/apis/config/validation/validation.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
  test/integration/controllermanager/shoot/maintenance/utils_test.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#6585 Add liveness probe for VPA components
  pkg/operation/botanist/component/vpa/admissioncontroller.go
  pkg/operation/botanist/component/vpa/general.go
  pkg/operation/botanist/component/vpa/recommender.go
  pkg/operation/botanist/component/vpa/updater.go
  pkg/operation/botanist/component/vpa/vpa_test.go
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#6674 [GEP-20] Add Topology Spread Constraints for Kube-Apiserver
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
Labels: kind/enhancement, size/L, area/high-availability, area/control-plane, cla: yes, lgtm, approved

#6667 Switch remaining `Project` controller to `controller-runtime`
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/project/activity/activity_suite_test.go
  pkg/controllermanager/controller/project/activity/add.go
  pkg/controllermanager/controller/project/activity/add_test.go
  pkg/controllermanager/controller/project/activity/reconciler.go
  pkg/controllermanager/controller/project/activity/reconciler_test.go
  pkg/controllermanager/controller/project/add.go
  pkg/controllermanager/controller/project/project.go
  pkg/controllermanager/controller/project/project_activity_control.go
  pkg/controllermanager/controller/project/project_activity_control_test.go
  pkg/controllermanager/controller/project/project_stale_control_test.go
  pkg/controllermanager/controller/project/stale/add.go
  pkg/controllermanager/controller/project/stale/add_test.go
  pkg/controllermanager/controller/project/stale/reconciler.go
  pkg/controllermanager/controller/project/stale/reconciler_test.go
  pkg/controllermanager/controller/project/stale/stale_suite_test.go
  test/integration/controllermanager/project/activity/activity_suite_test.go
  test/integration/controllermanager/project/activity/activity_test.go
  test/integration/controllermanager/project/stale/stale_suite_test.go
  test/integration/controllermanager/project/stale/stale_test.go
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#6675 Add a panel "Response Size Rate" to the API Server dashboard
  charts/seed-monitoring/charts/grafana/dashboards/owners/apiserver-overview.json
Labels: kind/enhancement, size/L, area/monitoring, cla: yes, lgtm, approved

#6681 Remove kris94 from OWNER_ALIASES
  OWNERS_ALIASES
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#6682 Configure the number of parallel E2E tests
  Makefile
  hack/ci-e2e-kind.sh
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#6683 [GEP-20] Fix getting namespace in Zone-Affinity webhook
  pkg/resourcemanager/webhook/podtopologyspreadconstraints/handler.go
  pkg/resourcemanager/webhook/podzoneaffinity/handler.go
  pkg/resourcemanager/webhook/podzoneaffinity/handler_test.go
  pkg/resourcemanager/webhook/projectedtokenmount/handler.go
  pkg/resourcemanager/webhook/seccompprofile/handler.go
  pkg/resourcemanager/webhook/tokeninvalidator/handler.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
Labels: kind/bug, size/M, area/high-availability, area/control-plane, cla: yes, lgtm, approved

#6684 [GEP-20] Use relaxed Topology Spread Constraint for non-HA shoots
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
Labels: kind/enhancement, size/L, area/control-plane, cla: yes, lgtm, approved

#6687 Deflakes ExtensionsCheck and BackupBucketsCheck controllers integration tests
  test/integration/controllermanager/seed/backupbucketscheck/backupbucketscheck_suite_test.go
  test/integration/controllermanager/seed/backupbucketscheck/backupbucketscheck_test.go
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_suite_test.go
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#6680 gardener-apiserver: Enforce the CloudProfile's `.spec.seedSelector` when validating the scheduling constraints of a Shoot
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, area/quality, size/L, cla: yes, lgtm, approved

#6694 gardener-admission-controller: Fix the CertificateSigningRequest version in the webhook
  charts/gardener/controlplane/charts/application/templates/validatingwebhook-admission-controller.yaml
  hack/local-development/dev-setup-register-gardener
Labels: kind/bug, size/XS, area/quality, kind/regression, cla: yes, lgtm, approved

#6685 [GEP-20] Add Topology Spread Constraints for `gardener-resource-manager`
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/resource_manager.go
  pkg/utils/checksums.go
Labels: kind/enhancement, size/L, area/high-availability, area/control-plane, cla: yes, lgtm, approved

#6701 Update architecture diagram
  docs/concepts/images/gardener-architecture-detailed.png
  docs/concepts/images/gardener-architecture-detailed.pptx
Labels: size/XS, area/documentation, kind/cleanup, cla: yes, lgtm, approved

#6714 Improve the logging in the control plane migration integration test
  test/framework/shootmigrationtest.go
Labels: kind/bug, size/XS, area/testing, cla: yes, lgtm, approved

#6715 Deflake `TokenInvalidator` integration test suite
  pkg/resourcemanager/controller/tokeninvalidator/add.go
  test/integration/resourcemanager/tokeninvalidator/tokeninvalidator_suite_test.go
  test/integration/resourcemanager/tokeninvalidator/tokeninvalidator_test.go
Labels: kind/enhancement, area/dev-productivity, size/M, area/testing, cla: yes, lgtm, approved

#6720 Revert "[ci:component:github.com/gardener/apiserver-proxy:v0.6.0->v0.7.0]"
  charts/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#6717 Deflake `Shoot` quota controller integration test suite
  test/integration/controllermanager/shoot/quota/quota_suite_test.go
  test/integration/controllermanager/shoot/quota/quota_test.go
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#6721 Revert "[ci:component:github.com/gardener/vpn2:0.10.0->0.11.1]"
  charts/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#6533 [GEP-20] Allow adding HA alpha annotation where none existed
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/operation/botanist/component/etcd/etcd.go
Labels: kind/enhancement, area/backup, size/L, area/high-availability, area/control-plane, cla: yes, lgtm, approved

#6699 Streamline `gardener-controller-manager` controllers after refactorings
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/bastion/add.go
  pkg/controllermanager/controller/bastion/add_test.go
  pkg/controllermanager/controller/bastion/bastion_suite_test.go
  pkg/controllermanager/controller/certificatesigningrequest/add.go
  pkg/controllermanager/controller/certificatesigningrequest/certificatesigningrequest_suite_test.go
  pkg/controllermanager/controller/cloudprofile/cloudprofile_suite_test.go
  pkg/controllermanager/controller/controllerdeployment/add.go
  pkg/controllermanager/controller/controllerdeployment/controllerdeployment_suite_test.go
  pkg/controllermanager/controller/controllerregistration/controllerregistrationfinalizer/controllerregistrationfinalizer_suite_test.go
  pkg/controllermanager/controller/controllerregistration/seed/add.go
  pkg/controllermanager/controller/controllerregistration/seed/add_test.go
  pkg/controllermanager/controller/controllerregistration/seed/seed_suite_test.go
  pkg/controllermanager/controller/controllerregistration/seedfinalizer/seedfinalizer_suite_test.go
  pkg/controllermanager/controller/event/add.go
  pkg/controllermanager/controller/event/event_suite_test.go
  pkg/controllermanager/controller/event/reconciler.go
  pkg/controllermanager/controller/exposureclass/exposureclass_suite_test.go
  pkg/controllermanager/controller/exposureclass/reconciler.go
  pkg/controllermanager/controller/managedseedset/managedseedset_suite_test.go
  pkg/controllermanager/controller/project/activity/activity_suite_test.go
  pkg/controllermanager/controller/project/activity/reconciler.go
  pkg/controllermanager/controller/project/project/add.go
  pkg/controllermanager/controller/project/project/add_test.go
  pkg/controllermanager/controller/project/project/project_suite_test.go
  pkg/controllermanager/controller/project/project/reconciler.go
  pkg/controllermanager/controller/project/stale/reconciler.go
  pkg/controllermanager/controller/project/stale/stale_suite_test.go
  pkg/controllermanager/controller/quota/quota_suite_test.go
  pkg/controllermanager/controller/quota/reconciler.go
  pkg/controllermanager/controller/secretbinding/secretbinding_suite_test.go
  pkg/controllermanager/controller/seed/backupbucketscheck/backupbucketscheck_suite_test.go
  pkg/controllermanager/controller/seed/backupbucketscheck/reconciler.go
  pkg/controllermanager/controller/seed/extensionscheck/extensionscheck_suite_test.go
  pkg/controllermanager/controller/seed/lifecycle/add.go
  pkg/controllermanager/controller/seed/lifecycle/add_test.go
  pkg/controllermanager/controller/seed/lifecycle/lifecycle_suite_test.go
  pkg/controllermanager/controller/seed/secrets/add.go
  pkg/controllermanager/controller/seed/secrets/add_test.go
  pkg/controllermanager/controller/seed/secrets/seed_suite_test.go
  pkg/controllermanager/controller/seed/utils/utils_suite_test.go
  pkg/controllermanager/controller/shoot/conditions/add.go
  pkg/controllermanager/controller/shoot/conditions/add_test.go
  pkg/controllermanager/controller/shoot/conditions/conditions_suite_test.go
  pkg/controllermanager/controller/shoot/hibernation/hibernation_suite_test.go
  pkg/controllermanager/controller/shoot/hibernation/reconciler.go
  pkg/controllermanager/controller/shoot/maintenance/maintenance_suite_test.go
  pkg/controllermanager/controller/shoot/quota/add.go
  pkg/controllermanager/controller/shoot/quota/add_test.go
  pkg/controllermanager/controller/shoot/quota/quota_suite_test.go
  pkg/controllermanager/controller/shoot/reference/reference_suite_test.go
  pkg/controllermanager/controller/shoot/retry/retry_suite_test.go
  pkg/controllermanager/controller/shoot/statuslabel/statuslabel_suite_test.go
  pkg/controllerutils/predicate/predicate.go
  pkg/controllerutils/predicate/predicate_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#6722 Set ldflags in skaffold builds
  Makefile
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#6690 Streamline `gardener-scheduler` entrypoint and controllers
  charts/gardener/controlplane/charts/runtime/templates/scheduler/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/scheduler/service.yaml
  cmd/gardener-scheduler/app/app.go
  cmd/gardener-scheduler/app/gardener_scheduler.go
  cmd/gardener-scheduler/app/options.go
  cmd/gardener-scheduler/main.go
  pkg/controllermanager/apis/config/encoding/encoding.go
  pkg/controllermanager/apis/config/encoding/encoding_suite_test.go
  pkg/controllermanager/apis/config/encoding/encoding_test.go
  pkg/controllerutils/predicate/predicate.go
  pkg/controllerutils/predicate/predicate_test.go
  pkg/scheduler/apis/config/encoding/encoding.go
  pkg/scheduler/apis/config/encoding/encoding_suite_test.go
  pkg/scheduler/apis/config/encoding/encoding_test.go
  pkg/scheduler/apis/config/install/install.go
  pkg/scheduler/apis/config/loader/loader.go
  pkg/scheduler/apis/config/v1alpha1/types.go
  pkg/scheduler/controller/add.go
  pkg/scheduler/controller/common/common_suite_test.go
  pkg/scheduler/controller/common/seed.go
  pkg/scheduler/controller/common/seed_test.go
  pkg/scheduler/controller/shoot/add.go
  pkg/scheduler/controller/shoot/add_test.go
  pkg/scheduler/controller/shoot/reconciler.go
  pkg/scheduler/controller/shoot/reconciler_test.go
  pkg/scheduler/controller/shoot/scheduler.go
  test/integration/scheduler/shoot/scheduler_test.go
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#6708 Streamline `gardener-seed-admission-controller` entrypoint
  cmd/gardener-seed-admission-controller/app/app.go
  cmd/gardener-seed-admission-controller/app/gardener_seed_admission_controller.go
  cmd/gardener-seed-admission-controller/app/options.go
  cmd/gardener-seed-admission-controller/main.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller_test.go
  pkg/seedadmissioncontroller/webhooks/add.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#6724 Deflake `Pod Zone Affinity` integration test
  test/integration/resourcemanager/podzoneaffinity/podzoneaffinity_suite_test.go
  test/integration/resourcemanager/podzoneaffinity/podzoneaffinity_test.go
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#6735 Configure static asset dependencies for `ko`
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#6706 Streamline `gardener-admission-controller` entrypoint
  charts/gardener/controlplane/charts/application/templates/validatingwebhook-admission-controller.yaml
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/configmap-componentconfig.yaml
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/secret-cert.yaml
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/service.yaml
  charts/gardener/controlplane/values.yaml
  cmd/gardener-admission-controller/app/app.go
  cmd/gardener-admission-controller/app/gardener_admission_controller.go
  cmd/gardener-admission-controller/app/options.go
  cmd/gardener-admission-controller/main.go
  example/20-componentconfig-gardener-admission-controller.yaml
  example/gardener-local/controlplane/values.yaml
  pkg/admissioncontroller/apis/config/types.go
  pkg/admissioncontroller/apis/config/v1alpha1/defaults.go
  pkg/admissioncontroller/apis/config/v1alpha1/defaults_test.go
  pkg/admissioncontroller/apis/config/v1alpha1/types.go
  pkg/admissioncontroller/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/admissioncontroller/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/admissioncontroller/apis/config/zz_generated.deepcopy.go
  pkg/admissioncontroller/webhooks/add.go
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#6677 Use gardenlet-specific error code for shoot flow
  extensions/pkg/controller/healthcheck/actuator.go
  extensions/pkg/controller/healthcheck/general/managed_resource.go
  extensions/pkg/controller/healthcheck/healthcheck_actuator.go
  extensions/pkg/controller/healthcheck/worker/nodes.go
  extensions/pkg/terraformer/terraformer.go
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/extensions/customresources.go
  pkg/operation/botanist/secrets.go
  pkg/operation/care/checker.go
  pkg/operation/care/health_check_test.go
  pkg/utils/managedresources/managedresources.go
Labels: kind/enhancement, area/ops-productivity, area/quality, size/L, cla: yes, lgtm, approved

#6737 Upgrade `sigs.k8s.io/controller-tools` to `v0.10.0`
  example/resource-manager/10-crd-resources.gardener.cloud_managedresources.yaml
  example/seed-crds/10-crd-autoscaling.k8s.io_hvpas.yaml
  example/seed-crds/10-crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  example/seed-crds/10-crd-druid.gardener.cloud_etcds.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_backupbuckets.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_backupentries.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_bastions.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_clusters.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_containerruntimes.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_controlplanes.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_dnsrecords.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_extensions.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_infrastructures.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_networks.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_workers.yaml
  example/seed-crds/10-crd-resources.gardener.cloud_managedresources.yaml
  go.mod
  go.sum
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_backupbuckets.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_backupentries.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_bastions.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_clusters.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_containerruntimes.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_controlplanes.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_dnsrecords.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_extensions.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_infrastructures.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_networks.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_workers.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-resources.gardener.cloud_managedresources.yaml
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/flatten.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/known_types.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/topology.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/spec.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/help/pretty/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/options.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/loader.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/collect.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/reg.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/zip.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/version/version.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: kind/enhancement, area/open-source, size/L, cla: yes, lgtm, approved

#6734 Promote `Shoot{C,S}ARotation` feature gates to GA
  docs/deployment/feature_gates.md
  pkg/api/core/shoot/warnings.go
  pkg/api/core/shoot/warnings_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/features/features.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: kind/enhancement, area/security, area/open-source, size/L, cla: yes, lgtm, approved

#6743 Fix formatting in priority classes docs
  docs/development/priority-classes.md
Labels: kind/bug, area/documentation, size/S, cla: yes, lgtm, approved

#6744 adopt refactoring from gardener/cc-utils
  hack/.ci/set_dependency_version
Labels: area/delivery, kind/cleanup, size/S, cla: yes, lgtm, approved

#6740 Project admins can no longer modify serviceaccounts
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
Labels: size/XS, kind/cleanup, area/user-management, cla: yes, lgtm, approved

#6753 Change path of containerd registry configurations in provider-local
  pkg/provider-local/webhook/controlplane/ensurer.go
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#6757 Keep custom `etcd` annotations
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
Labels: kind/enhancement, area/ops-productivity, size/M, area/control-plane, cla: yes, lgtm, approved

#6748 Scrape logs from pods in the shoot kube-system which have the resources.gardener.cloud/managed-by:gardener label:value
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/config_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/templates/promtail-config.tpl.yaml
Labels: kind/enhancement, area/logging, size/S, cla: yes, lgtm, approved

#6751 Deflake ExtensionsCheck test and BackupBucketsCheck test
  pkg/controllermanager/controller/seed/utils/utils.go
  test/integration/controllermanager/seed/backupbucketscheck/backupbucketscheck_test.go
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved
