Repository gardener/gardener, pull requests merged in 2022-12, with the labels that each got.

#7089 Split graph "Number of Nodes in Worker Group(s)" by workerpool to align with other charts
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-pool-dashboard.json
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#7119 Fix flaky shoot conditions integration test
  test/integration/controllermanager/shoot/conditions/conditions_suite_test.go
  test/integration/controllermanager/shoot/conditions/conditions_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#7126 Set force-deletion annotation on source BackupEntry
  pkg/operation/botanist/backupentry.go
  pkg/operation/botanist/backupentry_test.go
  pkg/operation/botanist/component/backupentry/backupentry.go
  pkg/operation/botanist/component/backupentry/backupentry_test.go
  pkg/operation/botanist/component/backupentry/mock/mocks.go
Labels: kind/bug, size/M, area/control-plane-migration, cla: yes, lgtm, approved

#7129 Adapt cluster-proportional autoscaling of coredns to new high-availability handling.
  pkg/operation/botanist/component/coredns/coredns.go
  pkg/operation/botanist/component/coredns/coredns_test.go
Labels: size/M, kind/regression, area/networking, area/high-availability, cla: yes, lgtm, approved

#7123 Fix prometheus alerts for multi-node etcd
  pkg/operation/botanist/component/etcd/monitoring.go
  pkg/operation/botanist/component/etcd/monitoring_test.go
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_important_multinode_with_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_important_singlenode_with_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_normal_multinode_with_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_normal_singlenode_with_backup.yaml
Labels: kind/enhancement, size/M, area/monitoring, cla: yes, lgtm, approved

#7109 Improve fetching token from kubeconfig in the `Shoot vpn tunnel` test
  test/testmachinery/shoots/vpntunnel/vpntunnel.go
Labels: kind/enhancement, size/S, area/testing, cla: yes, lgtm, approved

#7101 Use Ginkgo timeout in Prow
  hack/test-integration.sh
  hack/test.sh
Labels: kind/enhancement, area/dev-productivity, size/S, area/testing, cla: yes, lgtm, approved

#7088 Fix `kubelet` when `protectKernelDefaults=true`
  go.mod
  go.sum
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  vendor/k8s.io/component-helpers/LICENSE
  vendor/k8s.io/component-helpers/node/util/sysctl/sysctl.go
  vendor/modules.txt
Labels: kind/bug, area/security, size/L, cla: yes, lgtm, approved

#7133 Update CoreDNS to v1.10.0.
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#7134 Do not validate `Shoot` DNS domain uniqueness on adding `DeletionConfirmation` annotation
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, size/M, cla: yes, lgtm, approved

#7112 Fix calculation of overlapping CIDR ranges.
  pkg/operation/botanist/component/networkpolicies/peers.go
  pkg/operation/botanist/component/networkpolicies/peers_test.go
  pkg/operation/botanist/networkpolicies_test.go
Labels: kind/bug, area/networking, size/S, cla: yes, lgtm, approved

#7113 Deflake `BackupEntry` controller integration test and Minor controller improvements
  pkg/gardenlet/controller/backupentry/backupentry/reconciler.go
  test/integration/gardenlet/backupentry/backupentry/backupentry_suite_test.go
  test/integration/gardenlet/backupentry/backupentry/backupentry_test.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#7125 Fix flaky `Extensions Webhook Certificates` integration tests
  test/integration/extensions/webhook/certificates/certificates_test.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#7138 Remove dnsprovider from supported extension kinds
  pkg/apis/core/validation/controllerregistration.go
Labels: size/XS, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#7044 Deflake `Seed` controller integration test
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  test/integration/gardenlet/seed/seed/seed_suite_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#7082 [gardenlet] Switch `Shoot` main controller to controller-runtime
  cmd/gardenlet/app/app.go
  docs/concepts/controller-manager.md
  docs/concepts/gardenlet.md
  docs/concepts/operator.md
  docs/usage/shoot_maintenance.md
  pkg/controllerutils/predicate/predicate.go
  pkg/controllerutils/predicate/predicate_test.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/backupentry/backupentry/add.go
  pkg/gardenlet/controller/backupentry/backupentry/add_test.go
  pkg/gardenlet/controller/backupentry/backupentry/reconciler.go
  pkg/gardenlet/controller/backupentry/backupentry/reconciler_test.go
  pkg/gardenlet/controller/backupentry/migration/add.go
  pkg/gardenlet/controller/backupentry/migration/reconciler.go
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/seed/seed/add.go
  pkg/gardenlet/controller/shoot/add.go
  pkg/gardenlet/controller/shoot/migration/reconciler.go
  pkg/gardenlet/controller/shoot/shoot.go
  pkg/gardenlet/controller/shoot/shoot/add.go
  pkg/gardenlet/controller/shoot/shoot/add_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile_test.go
  pkg/gardenlet/controller/shoot/shoot/shoot_suite_test.go
  pkg/gardenlet/controller/shoot/shoot/tracker.go
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/scheduler/controller/shoot/add.go
  pkg/utils/gardener/backupentry.go
  pkg/utils/gardener/backupentry_test.go
  pkg/utils/gardener/migration.go
  pkg/utils/gardener/migration_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#7132 Make HOSTNAME env to lowercase for promtail service
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/config.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/config_test.go
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#7140 gep-19 observability stack - adding fluent-bit operator in logging
  docs/README.md
  docs/proposals/19-migrating-observability-stack-to-operators.md
Labels: kind/enhancement, size/L, area/monitoring, area/logging, cla: yes, lgtm, approved

#7146 Regenerate local development certificate for ETCD/GAPI
  example/gardener-local/controlplane/values.yaml
  example/gardener-local/etcd/tls/ca.crt
  example/gardener-local/etcd/tls/ca.key
  example/gardener-local/etcd/tls/server.crt
  example/gardener-local/etcd/tls/server.key
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#7067 [operator] Manage Virtual Garden ETCD
  Makefile
  charts/gardener/operator/templates/customresouredefintion.yaml
  charts/gardener/operator/templates/role.yaml
  docs/api-reference/operator.md
  docs/concepts/etcd.md
  docs/concepts/operator.md
  docs/development/priority-classes.md
  example/gardener-local/kind/cluster/templates/_extra_mounts.tpl
  example/gardener-local/kind/cluster/templates/cluster.yaml
  example/gardener-local/kind/cluster/values.yaml
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_suite_test.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/etcd/monitoring.go
  pkg/operation/botanist/component/etcd/monitoring_test.go
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_important_multinode_with_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_important_multinode_without_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_important_singlenode_with_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_important_singlenode_without_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_normal_multinode_with_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_normal_multinode_without_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_normal_singlenode_with_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_normal_singlenode_without_backup.yaml
  pkg/operation/botanist/component/etcd/waiter.go
  pkg/operation/botanist/component/etcd/waiter_test.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
  pkg/operator/client/scheme.go
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/garden/reconciler_delete.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  pkg/utils/timewindow/schedule.go
  pkg/utils/timewindow/schedule_test.go
  test/e2e/operator/garden/create_delete.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden_suite_test.go
  test/integration/operator/garden/garden_test.go
Labels: kind/enhancement, area/dev-productivity, area/delivery, cla: yes, lgtm, approved, size/XXL

#7094 Enable K8s API server log verbosity and acceess logs level configuration
  docs/api-reference/core.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/kubeapiserver.go
Labels: kind/api-change, area/control-plane, cla: yes, lgtm, approved, size/XXL

#7160 Allow providing separate ETCD TLS secrets for Gardener `controlplane` chart
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/values.yaml
Labels: kind/enhancement, area/ops-productivity, size/M, cla: yes, lgtm, approved

#7164 Deflake `ShootState Extensions` controller integration tests
  test/integration/gardenlet/shootstate/extensions/extensions_suite_test.go
  test/integration/gardenlet/shootstate/extensions/extensions_test.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#7166 HA config webhook extends node selector requirements instead of node selector terms
  pkg/resourcemanager/webhook/highavailabilityconfig/handler.go
  pkg/utils/kubernetes/highavailability.go
  pkg/utils/kubernetes/highavailability_test.go
  test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_test.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#7163 Update github.com/gardener/etcd-druid
  example/seed-crds/10-crd-druid.gardener.cloud_etcds.yaml
  go.mod
  go.sum
  pkg/operation/botanist/component/etcd/crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  pkg/operation/botanist/component/etcd/crds/templates/crd-druid.gardener.cloud_etcds.yaml
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/k8s_version.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/miscellaneous.go
  vendor/modules.txt
Labels: kind/enhancement, size/XL, cla: yes, lgtm, approved

#7168 Fix error message for missing hostnames in local setup
  hack/test-e2e-local.sh
Labels: kind/bug, size/S, area/testing, cla: yes, lgtm, approved

#7172 Do not destroy etcd-druid/HVPA on seed deletion when seed is garden at the same time
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#7173 Update to Go 1.19.4
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#7161 `ManagedResource` controller only considers `ConfigMap`s/`Secret`s as garbage-collectable resources
  pkg/resourcemanager/controller/managedresource/reconciler.go
  test/integration/resourcemanager/managedresource/resource_suite_test.go
  test/integration/resourcemanager/managedresource/resource_test.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#7165 Parameterize `hack/kind-up.sh`
  hack/kind-up.sh
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7175 Deflake `Seed` controller integration test
  test/integration/gardenlet/seed/seed/seed_suite_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/gardenlet/seed/seed/testdata/crd-verticalpodautoscalers.yaml
Labels: size/XL, area/testing, kind/flake, cla: yes, lgtm, approved

#7162 `CreateForShoot` and `NewForShoot` now accept additional `origin` parameter
  docs/extensions/conventions.md
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go
  pkg/operation/botanist/component/clusteridentity/clusteridentity.go
  pkg/operation/botanist/component/coredns/coredns.go
  pkg/operation/botanist/component/gardeneraccess/access.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubecontrollermanager/shoot_resources.go
  pkg/operation/botanist/component/kubeproxy/kube_proxy.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler.go
  pkg/operation/botanist/component/logging/eventlogger/event_logger.go
  pkg/operation/botanist/component/logging/kuberbacproxy/kube_rbac_proxy.go
  pkg/operation/botanist/component/metricsserver/metrics_server.go
  pkg/operation/botanist/component/namespaces/namespaces.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
  pkg/operation/botanist/component/nodeproblemdetector/node_problem_detector.go
  pkg/operation/botanist/component/resourceconfig.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/shootsystem/shootsystem.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/utils/managedresources/managedresources.go
  pkg/utils/managedresources/managedresources_test.go
Labels: kind/bug, area/quality, size/M, cla: yes, lgtm, approved

#7174 Update Kubernetes v1.25 conformance test coverage
  README.md
Labels: kind/enhancement, area/open-source, size/S, cla: yes, lgtm, approved

#7179 Fix `MCM` replica count during shoot hibernation
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
Labels: kind/enhancement, area/robustness, size/S, area/control-plane, cla: yes, lgtm, approved

#7181 [release-v1.61] Automated cherry pick of #7179: Fix `MCM` replica count during shoot hibernation
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
Labels: kind/enhancement, area/robustness, size/S, area/control-plane, cla: yes, lgtm, approved

#7195 Always validate `Seed` selection for multi zonal `Shoot`s
  plugin/pkg/shoot/validator/admission.go
Labels: kind/bug, size/XS, area/high-availability, cla: yes, lgtm, approved

#6678 [gardener-local] Support real infrastructure and registering provider-extensions
  Makefile
  docs/README.md
  docs/deployment/content/getting_started_locally_with_extensions.png
  docs/deployment/getting_started_locally_with_extensions.md
  example/gardener-local/gardenlet/secret-bootstrap-token-extensions.yaml
  example/gardener-local/gardenlet/values-provider-extensions.yaml
  example/gardener-local/kind/cluster/templates/_extra_port_mappings.tpl
  example/gardener-local/kind/cluster/templates/_kubeadm_config_patches.tpl
  example/gardener-local/kind/cluster/values.yaml
  example/gardener-local/kind/extensions/.gitignore
  example/gardener-local/kind/extensions/values.yaml
  example/provider-extensions/garden/.gitignore
  example/provider-extensions/garden/cloudprofiles/.gitignore
  example/provider-extensions/garden/controllerregistrations/.gitignore
  example/provider-extensions/garden/controlplane/.gitignore
  example/provider-extensions/garden/controlplane/values.yaml.tmpl
  example/provider-extensions/garden/project/credentials/.gitignore
  example/provider-extensions/garden/project/credentials/infrastructure-secrets.yaml.tmpl
  example/provider-extensions/garden/project/credentials/secretbindings.yaml.tmpl
  example/provider-extensions/garden/project/kustomization.yaml
  example/provider-extensions/garden/project/project.yaml
  example/provider-extensions/gardenlet/.gitignore
  example/provider-extensions/gardenlet/values.yaml.tmpl
  example/provider-extensions/kyverno-policies/gardener-image-pull-policy.yaml
  example/provider-extensions/kyverno-policies/kustomization.yaml
  example/provider-extensions/kyverno-policies/sync-gardener-secrets.yaml
  example/provider-extensions/kyverno/kustomization.yaml
  example/provider-extensions/kyverno/kyverno-configmap.yaml
  example/provider-extensions/kyverno/kyverno-deployment.yaml
  example/provider-extensions/kyverno/kyverno-poddisruptionbudget.yaml
  example/provider-extensions/registry-seed/.gitignore
  example/provider-extensions/registry-seed/deploy-registry.sh
  example/provider-extensions/registry-seed/load-balancer/base/kustomization.yaml
  example/provider-extensions/registry-seed/load-balancer/base/load-balancer.yaml
  example/provider-extensions/registry-seed/load-balancer/base/namespace.yaml
  example/provider-extensions/registry-seed/registry/registry.yaml
  example/provider-extensions/seed/.gitignore
  example/provider-extensions/seed/configure-seed.sh
  example/provider-extensions/seed/create-seed.sh
  example/provider-extensions/ssh-reverse-tunnel/create-client-keys.sh
  example/provider-extensions/ssh-reverse-tunnel/create-host-keys.sh
  example/provider-extensions/ssh-reverse-tunnel/load-balancer/kustomization.yaml
  example/provider-extensions/ssh-reverse-tunnel/load-balancer/load-balancer.yaml
  example/provider-extensions/ssh-reverse-tunnel/load-balancer/namespace.yaml
  example/provider-extensions/ssh-reverse-tunnel/ssh/client-keys/.gitignore
  example/provider-extensions/ssh-reverse-tunnel/ssh/files/entrypoint.sh
  example/provider-extensions/ssh-reverse-tunnel/ssh/files/ssh_config
  example/provider-extensions/ssh-reverse-tunnel/ssh/kustomization.yaml
  example/provider-extensions/ssh-reverse-tunnel/ssh/namespace.yaml
  example/provider-extensions/ssh-reverse-tunnel/ssh/ssh_deployment.yaml
  example/provider-extensions/ssh-reverse-tunnel/sshd/files/entrypoint.sh
  example/provider-extensions/ssh-reverse-tunnel/sshd/files/sshd_config
  example/provider-extensions/ssh-reverse-tunnel/sshd/host-keys/.gitignore
  example/provider-extensions/ssh-reverse-tunnel/sshd/kustomization.yaml
  example/provider-extensions/ssh-reverse-tunnel/sshd/sshd_deployment.yaml
  hack/gardener-extensions-down.sh
  hack/gardener-extensions-up.sh
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#7035 Keep track of the last maintenance operation in the shoot status
  docs/api-reference/core.md
  docs/usage/shoot_maintenance.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/controllermanager/controller/shoot/maintenance/add.go
  pkg/controllermanager/controller/shoot/maintenance/add_test.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler_test.go
  pkg/openapi/openapi_generated.go
  test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
Labels: kind/enhancement, area/ops-productivity, cla: yes, lgtm, approved, size/XXL

#7189 Refactor handling of shoot controller special cases
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/controllermanager/controller/shoot/hibernation/reconciler.go
  pkg/controllermanager/controller/shoot/maintenance/add.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/gardenlet/controller/shoot/shoot/add.go
  pkg/gardenlet/controller/shoot/shoot/add_test.go
  pkg/gardenlet/controller/shoot/shoot/helper/doc.go
  pkg/gardenlet/controller/shoot/shoot/helper/helper.go
  pkg/gardenlet/controller/shoot/shoot/helper/helper_suite_test.go
  pkg/gardenlet/controller/shoot/shoot/helper/helper_test.go
  pkg/gardenlet/controller/shoot/shoot/helper/infos.go
  pkg/gardenlet/controller/shoot/shoot/helper/infos_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile_test.go
  pkg/gardenlet/controller/shoot/shoot/tracker.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  skaffold.yaml
Labels: area/dev-productivity, area/quality, kind/technical-debt, cla: yes, lgtm, approved, size/XXL

#7152 Add document for checklist when adding new components
  docs/README.md
  docs/development/component-checklist.md
Labels: kind/enhancement, area/dev-productivity, area/documentation, size/L, cla: yes, lgtm, approved

#7201 Allow all authenticated users to create tokenreviews and selfsubjectaccessreviews
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
Labels: kind/enhancement, area/dev-productivity, area/ops-productivity, size/M, area/user-management, cla: yes, lgtm, approved

#7194 Fix replicas on hibernation for vpn-seed-server
  pkg/operation/botanist/component/vpnseedserver/mock/mocks.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/botanist/vpnseedserver.go
  pkg/operation/botanist/vpnseedserver_test.go
  test/e2e/gardener/shoot/create_and_delete_hibernated.go
  test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#7122 Add E2E Gardener upgrade test
  Makefile
  docs/deployment/getting_started_locally.md
  docs/development/testing.md
  hack/ci-e2e-kind-upgrade.sh
  hack/download_gardener_source_code.sh
  hack/test-e2e-local.sh
  skaffold.yaml
  test/e2e/gardener/e2e_suite_test.go
  test/e2e/gardener/shoot/upgrade_non-ha_to_node.go
  test/e2e/gardener/shoot/upgrade_non-ha_to_zone.go
  test/e2e/gardener/upgrade/upgrade.go
  test/utils/shoots/update/update.go
Labels: kind/enhancement, size/L, kind/test, area/robustness, area/high-availability, area/testing, cla: yes, lgtm, approved

#7209 Update gardener/autoscaler for K8S v1.25
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/auto-scaling, cla: yes, lgtm, approved

#7214 Consider only the 5xx responses as errors
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-control-plane-status-dashboard.json
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#7216 Fix the bin-packing scheduling profile for K8s 1.25 Shoot clusters
  pkg/operation/botanist/component/kubescheduler/kube_scheduler.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.20-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.20.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.22-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.22.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.23-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.23.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.25-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.25.yaml
Labels: kind/bug, size/L, area/control-plane, cla: yes, lgtm, approved

#7218 [release-v1.60] Automated cherry pick of #7216: Fix the bin-packing scheduling profile for K8s 1.25 Shoot clusters
  pkg/operation/botanist/component/kubescheduler/kube_scheduler.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.17.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.18-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.18.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.19-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.19.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.22-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.22.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.23-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.23.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.25-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.25.yaml
Labels: kind/bug, size/L, area/control-plane, cla: yes, lgtm, approved

#7219 [release-v1.59] Automated cherry pick of #7216: Fix the bin-packing scheduling profile for K8s 1.25 Shoot clusters
  pkg/operation/botanist/component/kubescheduler/kube_scheduler.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.17.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.18-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.18.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.19-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.19.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.22-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.22.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.23-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.23.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.25-bin-packing.yaml
  pkg/operation/botanist/component/kubescheduler/testdata/component-config-1.25.yaml
Labels: kind/bug, size/L, area/control-plane, cla: yes, lgtm, approved

#7108 [gardenlet] Switch `ManagedSeed` controller to `controller-runtime`
  charts/gardener/gardenlet/templates/configmap-componentconfig.yaml
  charts/gardener/gardenlet/templates/configmap-imagevector-overwrite-components.yaml
  charts/gardener/gardenlet/templates/configmap-imagevector-overwrite.yaml
  charts/gardener/gardenlet/templates/deployment.yaml
  charts/gardener/gardenlet/templates/poddisruptionbudget.yaml
  charts/gardener/gardenlet/templates/role-garden-gardenlet.yaml
  charts/gardener/gardenlet/templates/rolebinding-garden-gardenlet.yaml
  charts/gardener/gardenlet/templates/secret-kubeconfig-garden.yaml
  charts/gardener/gardenlet/templates/secret-kubeconfig-seed.yaml
  charts/gardener/gardenlet/templates/service.yaml
  charts/gardener/gardenlet/templates/serviceaccount.yaml
  charts/gardener/gardenlet/templates/vpa.yaml
  pkg/apis/seedmanagement/validation/managedseed.go
  pkg/apis/seedmanagement/validation/managedseed_test.go
  pkg/controllerutils/eventhandler.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/managedseed/actuator.go
  pkg/gardenlet/controller/managedseed/actuator_test.go
  pkg/gardenlet/controller/managedseed/add.go
  pkg/gardenlet/controller/managedseed/add_test.go
  pkg/gardenlet/controller/managedseed/managedseed.go
  pkg/gardenlet/controller/managedseed/managedseed_controller.go
  pkg/gardenlet/controller/managedseed/managedseed_controller_test.go
  pkg/gardenlet/controller/managedseed/managedseed_predicates.go
  pkg/gardenlet/controller/managedseed/managedseed_suite_test.go
  pkg/gardenlet/controller/managedseed/reconciler.go
  pkg/gardenlet/controller/managedseed/reconciler_test.go
  pkg/gardenlet/controller/managedseed/valueshelper.go
  pkg/gardenlet/controller/managedseed/valueshelper_test.go
  pkg/utils/kubernetes/eventhandler.go
  pkg/utils/kubernetes/eventhandler_test.go
  pkg/utils/kubernetes/mock/doc.go
  pkg/utils/kubernetes/mock/mocks.go
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
  test/integration/gardenlet/managedseed/managedseed_suite_test.go
  test/integration/gardenlet/managedseed/managedseed_test.go
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#7185 Update node-local-dns to v1.22.15
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#7186 Update envoy-proxy to v1.24.1
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#7223 Upgrade blackbox exporter
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#7050 [GEP-21] IPv6 Single-Stack Support in Local Gardener
  docs/README.md
  docs/proposals/21-ipv6-singlestack-local.md
Labels: kind/enhancement, size/L, area/networking, cla: yes, lgtm, approved

#7220 Update configmap-reloader version
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#7227 [GEP-21] Regenerate TOC
  docs/proposals/21-ipv6-singlestack-local.md
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#7202 Configure shoot worker pool labels via `--node-labels`
  docs/extensions/worker.md
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/components.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/cliflags.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/cliflags_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/operation/botanist/component/extensions/worker/worker.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/worker.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/enhancement, size/L, area/robustness, cla: yes, lgtm, approved

#7228 Deflake Shootstate secret controller
  test/integration/gardenlet/backupbucket/backupbucket_suite_test.go
  test/integration/gardenlet/shootstate/secret/secret_suite_test.go
  test/integration/gardenlet/shootstate/secret/secret_test.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#7207 Adapt version constraint matchers and use `*semver.Version` where possible
  pkg/gardenlet/controller/seed/seed/nginxingress.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/etcd/monitoring.go
  pkg/operation/botanist/component/etcd/monitoring_test.go
  pkg/operation/botanist/component/etcd/waiter_test.go
  pkg/operation/botanist/component/kubeapiserver/horizontalpodautoscaler.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/poddisruptionbudget.go
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/shared/resourcemanager.go
  pkg/operation/botanist/component/vpnauthzserver/external_authz_server.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/resource_manager.go
  pkg/operation/operation.go
  pkg/operator/controller/garden/add.go
  pkg/resourcemanager/controller/add.go
  pkg/resourcemanager/controller/garbagecollector/reconciler.go
  pkg/resourcemanager/controller/garbagecollector/reconciler_test.go
  pkg/resourcemanager/webhook/add.go
  pkg/resourcemanager/webhook/highavailabilityconfig/handler.go
  pkg/utils/version/version.go
  pkg/utils/version/version_test.go
  test/integration/resourcemanager/garbagecollector/garbagecollector_suite_test.go
  test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_suite_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#7234 Bump up kube-rbac-proxy to v0.14.0
  charts/images.yaml
Labels: size/XS, kind/task, area/logging, cla: yes, lgtm, approved

#7239 Drop unused controller utility functions
  docs/development/logging.md
  pkg/controllerutils/eventhandler.go
  pkg/controllerutils/seedfilter.go
  pkg/controllerutils/seedfilter_test.go
  pkg/controllerutils/worker.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#7240 Clean up the deletion of the stale `kube-addon-manager-vpa` VPA
  pkg/operation/botanist/component/vpnshoot/vpnshoot_test.go
  pkg/operation/botanist/resource_manager.go
  pkg/operation/botanist/resource_manager_test.go
Labels: area/ops-productivity, kind/cleanup, size/S, cla: yes, lgtm, approved

#7250 Adds `--shutdown-send-retry-after=true` for `kube-apiserver` `v1.24`
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
Labels: kind/bug, area/disaster-recovery, size/S, area/control-plane, cla: yes, lgtm, approved

#7184 Add CVE re-scoring configuration to VPA images
  charts/images.yaml
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#7245 Adapt multi availability zone handling of istio to local mac requirements.
  Makefile
  example/gardener-local/kind/cluster/templates/_extra_port_mappings.tpl
  hack/ci-e2e-kind-upgrade.sh
  hack/kind-up.sh
  test/e2e/gardener/shoot/upgrade_non-ha_to_zone.go
  test/e2e/gardener/upgrade/upgrade.go
Labels: kind/bug, size/M, area/networking, cla: yes, lgtm, approved

#7249 Add CVE re-scoring configuration to HVPA image
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/auto-scaling, cla: yes, lgtm, approved

#7238 [operator] Manage Virtual Garden `kube-apiserver` Exposure
  charts/gardener/operator/templates/customresouredefintion.yaml
  charts/gardener/operator/templates/role.yaml
  docs/api-reference/operator.md
  docs/concepts/operator.md
  example/gardener-local/kind/cluster/templates/_extra_port_mappings.tpl
  example/gardener-local/kind/cluster/templates/cluster.yaml
  example/gardener-local/kind/cluster/values.yaml
  example/gardener-local/kind/operator/values.yaml
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  hack/local-development/start-operator
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/service/add.go
  pkg/controller/service/reconciler.go
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_service.go
  pkg/operator/controller/add.go
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/garden/reconciler_delete.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  pkg/provider-local/controller/service/add.go
  pkg/provider-local/controller/service/reconciler.go
  skaffold-operator.yaml
  skaffold.yaml
  test/e2e/operator/garden/create_delete.go
  test/integration/operator/garden/garden_test.go
Labels: kind/enhancement, area/dev-productivity, area/delivery, size/XL, cla: yes, lgtm, approved

#7167 Remove legacy VPN solution
  charts/images.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  cmd/gardenlet/app/app.go
  docs/deployment/feature_gates.md
  docs/development/local_setup.md
  docs/extensions/provider-local.md
  docs/usage/reversed-vpn-tunnel.md
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/gardenlet/values.yaml
  extensions/pkg/webhook/controlplane/genericmutator/mutator.go
  hack/.ci/set_dependency_version
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/features/features.go
  pkg/gardenlet/controller/managedseed/valueshelper_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operation/botanist/component/kubeapiserver/configmaps.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/hvpa.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/logging.go
  pkg/operation/botanist/component/kubeapiserver/logging_test.go
  pkg/operation/botanist/component/kubeapiserver/networkpolicies.go
  pkg/operation/botanist/component/kubeapiserver/secrets.go
  pkg/operation/botanist/component/vpnshoot/mock/mocks.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot_test.go
  pkg/operation/botanist/coredns_test.go
  pkg/operation/botanist/dns_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operation/botanist/kubeapiserverexposure_test.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/monitoring_test.go
  pkg/operation/botanist/networkpolicies.go
  pkg/operation/botanist/networkpolicies_test.go
  pkg/operation/botanist/nodeproblemdetector_test.go
  pkg/operation/botanist/vpnseedserver.go
  pkg/operation/botanist/vpnseedserver_test.go
  pkg/operation/botanist/vpnshoot.go
  pkg/operation/botanist/vpnshoot_test.go
  pkg/operation/botanist/waiter.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
  pkg/provider-local/controller/infrastructure/actuator.go
  pkg/utils/images/images.go
Labels: kind/cleanup, area/networking, cla: yes, lgtm, approved, size/XXL

#7243 Enable secrets manager to adopt existing secrets
  docs/development/secrets_management.md
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
  pkg/utils/secrets/manager/manager.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#7180 Add dashboards for `controller-runtime` metrics
  charts/gardener/gardenlet/templates/deployment.yaml
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  charts/seed-bootstrap/charts/monitoring/templates/config.yaml
  charts/seed-bootstrap/dashboards/alerts-dashboard.json
  charts/seed-bootstrap/dashboards/client-go.json
  charts/seed-bootstrap/dashboards/controller-details.json
  charts/seed-bootstrap/dashboards/controllers.json
  charts/seed-bootstrap/dashboards/extensions-dashboard.json
  charts/seed-bootstrap/dashboards/resource-manager.json
  charts/seed-bootstrap/dashboards/seed-resource-usage.json
  charts/seed-bootstrap/dashboards/webhook-details.json
  charts/seed-bootstrap/dashboards/webhooks.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/client-go.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/controller-details.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/controllers.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/resource-manager.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/webhook-details.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/webhooks.json
  docs/monitoring/README.md
  example/provider-local/garden/base/controller-registration.yaml
Labels: kind/enhancement, area/monitoring, cla: yes, lgtm, approved, size/XXL

#7251 Improve `ManagedSeed` e2e tests to reduce flakiness
  test/e2e/gardener/managedseed/create_rotate_delete.go
Labels: area/dev-productivity, kind/test, size/S, cla: yes, lgtm, approved

#7204 Add `SystemComponentsConfig` Webhook
  charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
  charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml
  charts/gardener/resource-manager/values.yaml
  docs/concepts/resource-manager.md
  docs/development/component-checklist.md
  docs/extensions/conventions.md
  example/resource-manager/10-componentconfig.yaml
  example/resource-manager/10-mutatingwebhookconfiguration.yaml
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/resources/v1alpha1/types.go
  pkg/gardenlet/controller/networkpolicy/reconciler.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/resource_manager.go
  pkg/operation/care/constraints.go
  pkg/operation/care/webhook_remediation.go
  pkg/resourcemanager/apis/config/types.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults.go
  pkg/resourcemanager/apis/config/v1alpha1/types.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/resourcemanager/apis/config/zz_generated.deepcopy.go
  pkg/resourcemanager/webhook/add.go
  pkg/resourcemanager/webhook/systemcomponentsconfig/add.go
  pkg/resourcemanager/webhook/systemcomponentsconfig/handler.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  pkg/utils/kubernetes/daemonset.go
  pkg/utils/kubernetes/daemonset_test.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
  pkg/utils/sets/ordered.go
  pkg/utils/sets/set.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/resourcemanager/systemcomponentsconfig/systemcomponentsconfig_suite_test.go
  test/integration/resourcemanager/systemcomponentsconfig/systemcomponentsconfig_test.go
Labels: kind/enhancement, area/robustness, area/high-availability, cla: yes, lgtm, approved, size/XXL

#7247 Make `kind-up` volume paths absolute
  example/gardener-local/kind/cluster/templates/_extra_mounts.tpl
  example/gardener-local/kind/cluster/values.yaml
  hack/kind-up.sh
Labels: area/dev-productivity, size/XS, kind/cleanup, cla: yes, lgtm, approved

#7271 Fix the typo in the hostnames that prevents running `make test-e2e-local-simple`
  docs/deployment/getting_started_locally.md
Labels: kind/bug, area/dev-productivity, size/XS, kind/regression, cla: yes, lgtm, approved
