Repository gardener/gardener, pull requests merged in 2022-04, with the labels that each got.

#5717 Fix flaky test and Cleanup usages of time.Sleep
  extensions/pkg/controller/common/checkerwatchdog.go
  extensions/pkg/controller/common/checkerwatchdog_test.go
  pkg/client/kubernetes/clientmap/internal/generic_clientmap.go
  pkg/client/kubernetes/clientmap/internal/generic_clientmap_test.go
  pkg/operation/botanist/component/dependencywatchdog/bootstrap_test.go
  pkg/operation/botanist/component/nodeproblemdetector/node_problem_detector_test.go
Labels: needs/ok-to-test, size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#5718 Fix several issues related to recent changes in `master` branch
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/controllermanager/controller/factory.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
  pkg/operation/garden/garden.go
  pkg/operation/garden/garden_test.go
  pkg/operation/seed/seed.go
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
  pkg/utils/secrets/manager/manager.go
  pkg/utils/secrets/manager/manager_test.go
Labels: kind/bug, area/security, needs/ok-to-test, size/L, cla: yes, lgtm, approved

#5722 Allow projected volumes in the vpn-shoot PSP
  pkg/operation/botanist/component/vpnshoot/vpnshoot.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot_test.go
Labels: kind/bug, size/XS, needs/ok-to-test, area/quality, cla: yes, lgtm, approved

#5724 Fix observability Ingress Secrets
  pkg/utils/encoding.go
  pkg/utils/encoding_test.go
  pkg/utils/secrets/basic_auth_test.go
Labels: kind/bug, size/XS, needs/ok-to-test, status/accepted, area/monitoring, cla: yes, lgtm, approved

#5721 Restart cluster autoscaler during maintenance
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler_test.go
Labels: kind/enhancement, needs/ok-to-test, size/S, area/control-plane, cla: yes, lgtm, approved

#5649 Make creation of static token kubeconfig for shoot clusters configurable
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
  docs/api-reference/core.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/secrets.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
Labels: kind/enhancement, area/security, needs/changes, kind/api-change, needs/review, needs/rebase, needs/ok-to-test, needs/second-opinion, cla: yes, lgtm, approved, size/XXL

#5719 Fixes token invalidation in cloud-config-downloader
  pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/downloader_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/templates/scripts/download-cloud-config.tpl.sh
Labels: kind/bug, area/robustness, size/S, cla: yes, lgtm, approved

#5720 Automate CRD generation
  extensions/test/integration/backupbucket/backupbucket_suite_test.go
  hack/generate-seed-crds.sh
  pkg/operation/botanist/component/extensions/crds/crds.go
  pkg/operation/botanist/component/extensions/crds/templates/crd-backupbucket.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-backupentry.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-bastion.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-cluster.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-containerruntime.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-controlplane.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extension.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_backupbuckets.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_backupentries.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_bastions.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_clusters.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_containerruntimes.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_controlplanes.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_dnsrecords.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_extensions.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_infrastructures.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_networks.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_workers.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-infrastructure.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-managedresources.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-network.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-operatingsystemconfig.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-resources.gardener.cloud_managedresources.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-worker.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/doc.go
Labels: area/dev-productivity, kind/technical-debt, cla: yes, lgtm, approved, size/XXL

#5726 Promote `ShootMaxTokenExpirationOverwrite` feature gate to beta
  docs/deployment/feature_gates.md
  pkg/features/features.go
Labels: kind/enhancement, area/ops-productivity, size/XS, area/open-source, cla: yes, lgtm, approved

#5727 Adds support for v1beta1 CronJobs in resource manager
  charts/utils-templates/templates/_versions.tpl
  pkg/resourcemanager/controller/managedresource/merger.go
  pkg/resourcemanager/controller/managedresource/merger_test.go
Labels: kind/bug, kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#5732 Remove labels from issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/flaking-test.md
  .github/ISSUE_TEMPLATE/support.md
Labels: size/XS, kind/cleanup, cla: yes, lgtm, approved

#5734 Added title to the frontmatter of certain topics
  docs/extensions/backupbucket.md
  docs/extensions/backupentry.md
  docs/extensions/containerruntime.md
  docs/extensions/controllerregistration.md
  docs/extensions/controlplane-exposure.md
  docs/extensions/controlplane-webhooks.md
  docs/extensions/controlplane.md
  docs/extensions/dns.md
  docs/extensions/dnsrecord.md
  docs/proposals/08-shoot-apiserver-via-sni.md
  docs/usage/apiserver-sni-injection.md
  docs/usage/csi_components.md
  docs/usage/custom-dns.md
  docs/usage/dns-autoscaling.md
  docs/usage/exposureclasses.md
  docs/usage/node-local-dns.md
  docs/usage/openidconnect-presets.md
  docs/usage/reversed-vpn-tunnel.md
Labels: kind/enhancement, reviewed/ok-to-test, needs/ok-to-test, area/documentation, size/M, cla: yes, lgtm, approved

#5738 update api-server-proxy
  charts/images.yaml
Labels: kind/enhancement, size/XS, needs/ok-to-test, cla: yes, lgtm, approved

#5739 Add workaround for switching from kube-proxy mode IPVS to IPTables.
  pkg/operation/botanist/component/kubeproxy/kube_proxy_test.go
  pkg/operation/botanist/component/kubeproxy/resources/cleanup.sh
Labels: kind/bug, needs/ok-to-test, area/networking, size/S, cla: yes, lgtm, approved

#5743 Add qps and burst for the vpa-recommender for Shoots and Seeds
  charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-recommender.yaml
Labels: kind/enhancement, size/XS, needs/ok-to-test, area/auto-scaling, cla: yes, lgtm, approved

#5742 Scrape Resource Manager Instances
  pkg/operation/botanist/component/resourcemanager/mock/mocks.go
  pkg/operation/botanist/component/resourcemanager/monitoring.go
  pkg/operation/botanist/component/resourcemanager/monitoring_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/monitoring_test.go
Labels: kind/enhancement, needs/ok-to-test, size/L, cla: yes, lgtm, approved

#5746 Cleanup more legacy secrets from `ShootState`
  pkg/operation/botanist/secrets.go
Labels: area/security, needs/ok-to-test, kind/cleanup, size/S, area/scalability, cla: yes, lgtm, approved

#5744 Improve control plane migration integration tests
  test/framework/gardener_utils.go
  test/framework/shootmigrationtest.go
  test/testmachinery/system/shoot_cp_migration/migrate_test.go
Labels: kind/enhancement, needs/ok-to-test, size/M, kind/test, area/testing, area/control-plane-migration, cla: yes, lgtm, approved

#5716 Upgrade VPA binaries and dependency to 0.10.0
  charts/images.yaml
  charts/seed-bootstrap-crds/charts/hvpa/templates/hvpa.yaml
  charts/seed-bootstrap/charts/vpa/charts/application/templates/vpa-webhook-config.yaml
  example/seed-crds/10-crd-autoscaling.k8s.io_hvpas.yaml
  go.mod
  go.sum
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/zz_generated.deepcopy.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/types.go
  vendor/modules.txt
Labels: kind/enhancement, needs/ok-to-test, size/L, area/auto-scaling, cla: yes, lgtm, approved

#5751 Increase Loki memory limit to 3Gi
  charts/seed-bootstrap/charts/loki/values.yaml
Labels: kind/enhancement, size/XS, needs/ok-to-test, area/logging, cla: yes, lgtm, approved

#5735 renew garden cluster kubeconfig in gardenlet on CA rotation
  cmd/gardenlet/app/gardenlet.go
  pkg/gardenlet/bootstrap/util/util.go
  pkg/gardenlet/bootstrap/util/util_test.go
Labels: kind/enhancement, area/security, needs/ok-to-test, size/L, cla: yes, lgtm, approved

#5760 Add shoot-oidc-service extension to list
  extensions/README.md
Labels: kind/enhancement, size/XS, needs/ok-to-test, area/documentation, cla: yes, lgtm, approved

#5754 Eliminate usages of generated client sets in `kubernetes.Interface.Kubernetes()`
  pkg/operation/common/utils.go
  test/testmachinery/shoots/operations/worker.go
Labels: kind/enhancement, area/cost, needs/ok-to-test, area/quality, size/M, area/networking, cla: yes, lgtm, approved

#5759 Revert "Split VPA count in dashboard by API version"
  charts/seed-bootstrap/dashboards/vpa-recommender.json
Labels: kind/bug, needs/ok-to-test, area/monitoring, area/auto-scaling, cla: yes, lgtm, approved, size/XXL

#5761 Prevent writing newlines to nodename file
  pkg/operation/botanist/component/extensions/operatingsystemconfig/executor/executor_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/executor/templates/scripts/execute-cloud-config.tpl.sh
Labels: kind/bug, size/XS, needs/ok-to-test, area/usability, cla: yes, lgtm, approved

#5762 Use base-sha for presubmit job of apidiff
  hack/check-apidiff.sh
Labels: kind/bug, area/dev-productivity, needs/ok-to-test, size/S, cla: yes, lgtm, approved

#5766 [GEP-18] Fix basic auth secret migration for secrets without CSV data
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
Labels: kind/bug, area/security, needs/ok-to-test, size/M, cla: yes, lgtm, approved

#5768 Only download full cloud config if checksum annotation changed
  pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/downloader.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/downloader_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/templates/scripts/download-cloud-config.tpl.sh
  pkg/operation/botanist/component/extensions/operatingsystemconfig/executor/executor.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/executor/executor_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/executor/templates/scripts/execute-cloud-config.tpl.sh
Labels: kind/enhancement, area/cost, needs/ok-to-test, size/L, area/networking, cla: yes, lgtm, approved

#5773 Fix the PDB for the Gardener API server to allow roll outs
  charts/gardener/controlplane/charts/runtime/templates/apiserver/poddisruptionbudget.yaml
Labels: kind/bug, area/ops-productivity, size/XS, needs/ok-to-test, area/control-plane, cla: yes, lgtm, approved

#5774 Switch from `kindnetd` to `calico` in local setup
  Makefile
  charts/gardener/provider-local/extension/doc.go
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/templates/rbac.yaml
  charts/gardener/provider-local/extension/values.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-extension-provider-local/app/options.go
  docs/extensions/provider-local.md
  example/gardener-local/calico/kustomization.yaml
  example/gardener-local/kind/cluster-local.yaml
  example/gardener-local/kind/cluster-skaffold.yaml
  example/provider-local/base/controller-registration.yaml
  example/provider-local/base/kustomization.yaml
  example/provider-local/base/patch-controller-registration.yaml
  example/provider-local/base/patch-controller-registrations.yaml
  example/provider-local/shoot.yaml
  pkg/provider-local/controller/healthcheck/add.go
  pkg/provider-local/controller/infrastructure/actuator.go
  pkg/provider-local/controller/network/actuator.go
  pkg/provider-local/controller/network/add.go
  pkg/provider-local/local/types.go
  pkg/provider-local/webhook/machinepod/mutator.go
  test/e2e/shoot/common.go
  test/e2e/shoot/create_rotate-ca_delete.go
Labels: kind/enhancement, area/dev-productivity, area/security, size/XL, needs/ok-to-test, cla: yes, lgtm, approved

#5783 Stop using `Fatalf` logs in test framework
  test/framework/shoot_utils.go
  test/framework/shootcreationframework.go
Labels: kind/bug, needs/ok-to-test, size/S, area/testing, cla: yes, lgtm, approved

#5780 Use networking api for ingress
  pkg/operation/common/utils.go
Labels: size/XS, needs/ok-to-test, area/monitoring, kind/regression, cla: yes, lgtm, approved

#5786 Disable calico backend for shoots in local e2e tests
  example/provider-local/shoot.yaml
  test/e2e/shoot/common.go
Labels: size/XS, needs/ok-to-test, area/testing, kind/flake, cla: yes, lgtm, approved

#5752 Promote CachedRuntimeClients feature gate to GA
  cmd/gardener-controller-manager/app/gardener_controller_manager.go
  cmd/gardenlet/app/gardenlet.go
  docs/deployment/feature_gates.md
  docs/development/kubernetes-clients.md
  docs/proposals/13-automated-seed-management.md
  example/20-componentconfig-gardener-controller-manager.yaml
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/controlplane/values.yaml
  example/gardener-local/gardenlet/values.yaml
  pkg/client/kubernetes/client.go
  pkg/controllermanager/controller/managedseedset/managedseedset_replicagetter.go
  pkg/controllermanager/controller/managedseedset/managedseedset_replicagetter_test.go
  pkg/features/features.go
  pkg/gardenlet/controller/managedseed/managedseed_valueshelper_test.go
  test/framework/gardener_utils.go
  test/framework/gardenerframework.go
  test/framework/k8s_utils.go
  test/framework/shootframework.go
Labels: kind/enhancement, needs/ok-to-test, size/M, area/scalability, cla: yes, lgtm, approved

#5784 Generate junit reports in prow
  Makefile
  go.mod
  go.sum
  hack/test-e2e-local.sh
  hack/test-integration.sh
  hack/test.sh
  hack/tools.mk
  hack/tools/report-collector/main.go
  test/integration/controllermanager/shootmaintenance/maintenance_suite_test.go
  test/integration/controllermanager/shootretry/shootretry_suite_test.go
  test/integration/gardenlet/shootsecret/shootsecret_suite_test.go
  test/integration/resourcemanager/managedresource/reconciler_suite_test.go
  test/integration/resourcemanager/rootcapublisher/publisher_suite_test.go
  test/integration/resourcemanager/tokeninvalidator/tokeninvalidator_suite_test.go
  test/integration/resourcemanager/tokenrequestor/tokenrequestor_suite_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/seedadmissioncontroller/seedadmission_suite_test.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/README.md
  vendor/github.com/onsi/ginkgo/v2/config/deprecated.go
  vendor/github.com/onsi/ginkgo/v2/core_dsl.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/generators/bootstrap_command.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/generators/generate_command.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/generators/generators_common.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/profiles_and_reports.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/run.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/test_suite.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/unfocus/unfocus_command.go
  vendor/github.com/onsi/ginkgo/v2/internal/ordering.go
  vendor/github.com/onsi/ginkgo/v2/internal/output_interceptor.go
  vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  vendor/github.com/onsi/ginkgo/v2/reporters/junit_report.go
  vendor/github.com/onsi/ginkgo/v2/reporting_dsl.go
  vendor/github.com/onsi/ginkgo/v2/types/config.go
  vendor/github.com/onsi/ginkgo/v2/types/errors.go
  vendor/github.com/onsi/ginkgo/v2/types/flags.go
  vendor/github.com/onsi/ginkgo/v2/types/report_entry.go
  vendor/github.com/onsi/ginkgo/v2/types/types.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/modules.txt
Labels: kind/enhancement, area/dev-productivity, needs/ok-to-test, size/L, cla: yes, lgtm, approved

#5791 Revert 'Allow changing container runtime on existing workers'
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: kind/bug, needs/ok-to-test, size/M, area/control-plane, cla: yes, lgtm, approved

#5794 bump prometheus/client_golang
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
Labels: kind/enhancement, size/L, ok-to-test, cla: yes, lgtm, approved

#5781 Make `ConcurrentSyncs` field in `ControllerConfiguration` of GCM Controllers optional and Default them
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/defaults_test.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/validation/validation.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
  pkg/controllermanager/controller/event/event.go
  pkg/controllermanager/controller/factory.go
  test/integration/controllermanager/shootmaintenance/maintenance_control_test.go
Labels: kind/bug, size/XL, needs/ok-to-test, area/control-plane, merge/squash, cla: yes, lgtm, approved

#5793 Promote DenyInvalidExtensionResources feature gate to GA
  cmd/gardener-seed-admission-controller/app/gardener_seed_admission_controller.go
  docs/deployment/feature_gates.md
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/gardenlet/values.yaml
  hack/local-development/start-seed-admission-controller
  pkg/features/features.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller_test.go
  pkg/seedadmissioncontroller/webhooks/admission/extensionresources/admission.go
  pkg/seedadmissioncontroller/webhooks/admission/extensionresources/admission_test.go
  test/integration/seedadmissioncontroller/seedadmission_suite_test.go
Labels: kind/enhancement, size/M, cla: yes, lgtm, approved

#5785 [GEP-18] Auto-rotate seed cluster CA certificate every `30d`
  docs/development/secrets_management.md
  pkg/operation/botanist/component/metricsserver/metrics_server.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/logging.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/secrets.go
  pkg/operation/seed/seed.go
  pkg/utils/secrets/manager/fake/fake_manager.go
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
  pkg/utils/secrets/manager/manager.go
  pkg/utils/secrets/manager/manager_test.go
Labels: kind/enhancement, area/security, needs/ok-to-test, size/L, cla: yes, lgtm, approved

#5740 Promote `RotateSSHKeypairOnMaintenance` feature gate to beta
  docs/deployment/feature_gates.md
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/features/features.go
  test/integration/controllermanager/shootmaintenance/utils_test.go
Labels: kind/enhancement, needs/ok-to-test, area/quality, size/S, cla: yes, lgtm, approved

#5514 Add support for ETCD backups in the local-provider extension
  Makefile
  charts/gardener/provider-local/extension/doc.go
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/templates/rbac.yaml
  charts/gardener/provider-local/extension/values.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-extension-provider-local/app/options.go
  docs/extensions/provider-local.md
  example/gardener-local/gardenlet/values.yaml
  example/gardener-local/kind/cluster-local.yaml
  example/gardener-local/kind/cluster-skaffold.yaml
  example/provider-local/base/controller-registration.yaml
  example/provider-local/overlays/local/seed.yaml
  hack/local-development/start-extension-provider-local
  pkg/provider-local/controller/backupbucket/actuator.go
  pkg/provider-local/controller/backupbucket/add.go
  pkg/provider-local/controller/backupentry/actuator.go
  pkg/provider-local/controller/backupentry/add.go
  pkg/provider-local/controller/backupoptions/options.go
Labels: kind/enhancement, needs/changes, needs/review, needs/ok-to-test, needs/second-opinion, area/backup, size/L, cla: yes, lgtm, approved

#5805 [GEP-18] Sign VPA server cert with current CA
  pkg/operation/botanist/component/vpa/vpa.go
Labels: kind/enhancement, area/security, size/XS, cla: yes, lgtm, approved

#5799 Do not consider shoots with deletion timestamp when `ShootMaxTokenExpiration{Overwrite,Validation}` is enabled
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#5811 Fix disabling of seed VPA
  pkg/operation/botanist/component/vpa/vpa.go
  pkg/operation/botanist/component/vpa/vpa_test.go
  pkg/operation/botanist/vpa.go
  pkg/operation/seed/components.go
  pkg/operation/seed/seed.go
Labels: kind/bug, size/M, area/auto-scaling, cla: yes, lgtm, approved

#5815 Update to golang@1.17.9
  .test-defs/CreateManagedSeed.yaml
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteManagedSeed.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
  Dockerfile.local
Labels: kind/enhancement, size/M, cla: yes, lgtm, approved

#5806 [GEP-18] Adapt `gardener-seed-admission-controller` component to new secrets manager
  pkg/operation/botanist/component/gardenerkubescheduler/gardener_kube_scheduler_bootstrap.go
  pkg/operation/botanist/component/gardenerkubescheduler/gardener_kube_scheduler_bootstrap_test.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller_suite_test.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller_test.go
  pkg/operation/seed/components.go
  pkg/operation/seed/seed.go
  test/framework/resources/templates/block-loki-validatingwebhookconfiguration.yaml.tpl
  test/testmachinery/shoots/logging/loki_tenant.go
Labels: kind/enhancement, area/security, size/L, cla: yes, lgtm, approved

#5798 Auto-maintain `valid-until-time` label for `ControlPlaneSecretConfig`s
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#5816 Update v1.23 conformance test coverage
  README.md
Labels: kind/test, size/S, area/certification, cla: yes, lgtm, approved

#5818 adds gardener images to component descriptor
  .ci/resources.yaml
  hack/.ci/component_descriptor
Labels: kind/bug, area/delivery, size/M, cla: yes, lgtm, approved

#5819 read component version from env variable
  .ci/resources.yaml
  hack/.ci/component_descriptor
Labels: kind/bug, reviewed/ok-to-test, area/delivery, size/S, cla: yes, lgtm, approved

#5828 Fix different memory limits when VPA enabled
  charts/shoot-addons/charts/kubernetes-dashboard/templates/deployment-dashboard.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-deployment.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
Labels: kind/bug, size/S, area/auto-scaling, cla: yes, lgtm, approved

#5834 Pin calico manifests to v3.22.2
  example/gardener-local/calico/calico.yaml
  example/gardener-local/calico/kustomization.yaml
Labels: kind/bug, area/dev-productivity, area/testing, cla: yes, lgtm, approved, size/XXL

#5803 [GEP-18] Adapt extensions library to new secrets manager
  charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/serviceaccount.yaml
  charts/gardener/provider-local/internal/machine-controller-manager/seed/values.yaml
  charts/gardener/provider-local/internal/machine-controller-manager/shoot/templates/clusterrolebinding-machine-controller-manager.yaml
  charts/gardener/provider-local/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  charts/gardener/provider-local/internal/machine-controller-manager/shoot/values.yaml
  cmd/gardener-extension-provider-local/app/app.go
  docs/README.md
  docs/development/secrets_management.md
  docs/extensions/ca-rotation.md
  docs/extensions/conventions.md
  docs/proposals/18-shoot-CA-rotation.md
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  extensions/pkg/controller/controlplane/genericactuator/mock/mocks.go
  extensions/pkg/controller/controlplane/genericactuator/noopvaluesprovider.go
  extensions/pkg/controller/status.go
  extensions/pkg/controller/utils.go
  extensions/pkg/controller/utils_test.go
  extensions/pkg/controller/worker/genericactuator/actuator.go
  extensions/pkg/controller/worker/genericactuator/machine_controller_manager.go
  extensions/pkg/terraformer/config.go
  extensions/pkg/terraformer/terraformer.go
  extensions/pkg/terraformer/types.go
  extensions/pkg/util/secret/manager/manager.go
  extensions/pkg/util/secret/manager/manager_suite_test.go
  extensions/pkg/util/secret/manager/manager_test.go
  extensions/pkg/util/shoot.go
  extensions/pkg/util/shoot_test.go
  pkg/provider-local/controller/controlplane/add.go
  pkg/provider-local/controller/controlplane/valuesprovider.go
  pkg/provider-local/controller/worker/actuator.go
  pkg/provider-local/controller/worker/add.go
  pkg/utils/secrets/manager/interface.go
  pkg/utils/secrets/mock/mocks.go
  pkg/utils/secrets/secrets.go
  test/e2e/shoot/create_rotate-ca_delete.go
  test/framework/shootcreationframework.go
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL

#5831 Add missing network policy
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#5835 Only copy existing kube-apiserver requests but not limits
  pkg/operation/botanist/kubeapiserver.go
Labels: kind/bug, size/XS, area/auto-scaling, cla: yes, lgtm, approved

#5823 Update release responsible schedule
  docs/development/process.md
Labels: kind/enhancement, area/delivery, size/M, cla: yes, lgtm, approved

#5840 Fixes nil pointer exceptions that happen during seed deletion
  pkg/operation/botanist/component/gardenerkubescheduler/gardener_kube_scheduler_bootstrap.go
  pkg/operation/seed/seed.go
Labels: kind/bug, area/robustness, size/S, cla: yes, lgtm, approved

#5845 Use `client-ca` for signing vpn-seed certificates
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot.go
Labels: kind/bug, area/quality, size/M, kind/regression, cla: yes, lgtm, approved

#5848 Properly select CA secrets by labels
  pkg/apis/core/v1alpha1/helper/shootstate_list.go
  pkg/apis/core/v1alpha1/helper/shootstate_list_test.go
  pkg/registry/core/shoot/storage/admin_kubeconfig.go
  pkg/registry/core/shoot/storage/admin_kubeconfig_test.go
Labels: area/security, size/L, kind/regression, cla: yes, lgtm, approved

#5837 Update OWA GEP to better reflect current state
  docs/proposals/12-oidc-webhook-authenticator.md
  docs/proposals/assets/registration.dot
  docs/proposals/assets/registration.svg
Labels: area/documentation, size/L, kind/cleanup, cla: yes, lgtm, approved

#5851 Admin kubeconfigs sign with client CA and verify with cluster CA
  pkg/registry/core/shoot/storage/admin_kubeconfig.go
  pkg/registry/core/shoot/storage/admin_kubeconfig_test.go
Labels: kind/bug, area/security, size/L, kind/regression, cla: yes, lgtm, approved

#5852 fix for issue #5832
  example/provider-local/base/cloudprofile.yaml
  example/provider-local/shoot.yaml
  test/e2e/shoot/common.go
Labels: kind/bug, area/dev-productivity, size/XS, area/testing, cla: yes, lgtm, approved

#5782 Use Custom Validator of c-r for webhook
  cmd/gardener-seed-admission-controller/app/gardener_seed_admission_controller.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller_test.go
  pkg/seedadmissioncontroller/webhooks/admission/extensionresources/admission.go
  pkg/seedadmissioncontroller/webhooks/admission/extensionresources/admission_test.go
  test/integration/seedadmissioncontroller/seedadmission_suite_test.go
Labels: kind/enhancement, needs/ok-to-test, area/open-source, cla: yes, lgtm, approved, size/XXL

#5853 Cleanup monitoring secrets when purpose is switched to testing
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/monitoring_test.go
  pkg/operation/botanist/secrets.go
Labels: kind/bug, size/M, area/monitoring, cla: yes, lgtm, approved

#5856 Initialize secret management only if shoot namespace is not terminating
  pkg/gardenlet/controller/shoot/shoot_control_migrate.go
Labels: kind/bug, size/XS, area/control-plane-migration, cla: yes, lgtm, approved

#5807 [GEP-18] Instrument CA secret generation according to specification
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/seed-monitoring/charts/core/values.yaml
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  extensions/pkg/util/secret/manager/manager_test.go
  pkg/operation/botanist/component/metricsserver/metrics_server.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/secrets.go
  pkg/operation/seed/seed.go
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
  pkg/utils/secrets/manager/manager.go
  test/e2e/shoot/create_rotate-ca_delete.go
Labels: kind/enhancement, area/security, size/L, cla: yes, lgtm, approved

#5859 Nit: Improve log formatting
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_care_control.go
Labels: size/XS, kind/cleanup, cla: yes, lgtm, approved

#5820 Streamline defaulted value of ETCDConfig
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/operation/botanist/component/etcd/bootstrap.go
Labels: size/M, kind/technical-debt, area/control-plane, cla: yes, lgtm, approved

#5862 [ci:component:github.com/gardener/etcd-druid:v0.8.2->v0.8.3]
  charts/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#5864 Add projected service account tokens also for init containers.
  pkg/resourcemanager/webhook/projectedtokenmount/handler.go
  pkg/resourcemanager/webhook/projectedtokenmount/handler_test.go
Labels: kind/enhancement, area/robustness, size/S, cla: yes, lgtm, approved

#5866 Drop `operation.*CheckSum` functions
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/vpnseedserver.go
  pkg/operation/botanist/vpnseedserver_test.go
  pkg/operation/botanist/vpnshoot.go
  pkg/operation/operation.go
  pkg/operation/types.go
Labels: kind/bug, area/security, size/L, cla: yes, lgtm, approved

#5868 Set kubeconfig rotation details in shootstatus to nil when `enableStaticTokenKubeconfig` is set to false
  pkg/gardenlet/controller/shoot/shoot_control.go
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#5849 Add documentation for shoot access
  docs/README.md
  docs/usage/shoot_access.md
  example/90-shoot.yaml
  example/shoot-kubeconfig/README.md
  example/shoot-kubeconfig/kubeconfig-request.json
Labels: kind/enhancement, area/documentation, size/L, cla: yes, lgtm, approved

#5861 Ensure new shoots get a dedicated client CA
  pkg/operation/botanist/secrets.go
Labels: kind/bug, area/security, size/XS, cla: yes, lgtm, approved

#5857 Promote `WorkerPoolKubernetesVersion` to beta
  docs/deployment/feature_gates.md
  pkg/features/features.go
Labels: kind/enhancement, size/XS, area/open-source, cla: yes, lgtm, approved

#5863 Check if `issued-at-time` label is present before parsing
  pkg/operation/seed/seed.go
Labels: kind/bug, area/security, size/XS, cla: yes, lgtm, approved

#5871 Added personas and fixed titles
  .docforge/manifest.yaml
  docs/extensions/backupbucket.md
  docs/extensions/backupentry.md
  docs/extensions/containerruntime.md
  docs/extensions/controllerregistration.md
  docs/extensions/controlplane-exposure.md
  docs/extensions/controlplane-webhooks.md
  docs/extensions/controlplane.md
  docs/extensions/dns.md
  docs/extensions/dnsrecord.md
  docs/proposals/08-shoot-apiserver-via-sni.md
  docs/usage/apiserver-sni-injection.md
  docs/usage/csi_components.md
  docs/usage/custom-dns.md
  docs/usage/dns-autoscaling.md
  docs/usage/exposureclasses.md
  docs/usage/node-local-dns.md
  docs/usage/openidconnect-presets.md
  docs/usage/reversed-vpn-tunnel.md
Labels: kind/enhancement, area/documentation, size/L, cla: yes, lgtm, approved

#5873 Add debug logs to watchdog test
  extensions/pkg/controller/common/checkerwatchdog.go
  extensions/pkg/controller/common/checkerwatchdog_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved, tide/merge-method-merge

#5874 Fix GRM not scaled up after a failed hibernation attempt
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/kubecontrollermanager.go
  pkg/operation/botanist/resource_manager.go
  pkg/operation/botanist/resource_manager_test.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#5875 Nit: make report-collector optional
  hack/test.sh
Labels: kind/bug, size/S, cla: yes, lgtm, approved

#5876 Make sure secret manager's clean up is executed at the end of the flow
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: kind/bug, size/S, area/control-plane, cla: yes, lgtm, approved

#5814 Remove Worker's RollingUpdate condition and replace last tryUpdateStatus usage with patch
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/genericactuator/actuator_test.go
  extensions/pkg/controller/worker/genericactuator/update.go
  extensions/pkg/controller/worker/genericactuator/update_test.go
  pkg/apis/extensions/v1alpha1/types_worker.go
Labels: area/quality, size/L, kind/cleanup, cla: yes, lgtm, approved
