Repository gardener/gardener, pull requests merged in 2022-06, with the labels that each got.

#6038 Introduce `rotate-credentials-{start,complete}` operation annotations
  docs/usage/shoot_credentials_rotation.md
  docs/usage/shoot_operations.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL

#6060 [GEP-18] Make shoot webhook reconciliation generic
  cmd/gardener-extension-provider-local/app/app.go
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  extensions/pkg/webhook/certificates/add.go
  extensions/pkg/webhook/certificates/reconciler.go
  extensions/pkg/webhook/cmd/options.go
  extensions/pkg/webhook/shoot/networkpolicy.go
  extensions/pkg/webhook/shoot/networkpolicy_test.go
  extensions/pkg/webhook/shoot/shoot_suite_test.go
  extensions/pkg/webhook/shoot/webhook.go
  extensions/pkg/webhook/shoot/webhook_test.go
  test/integration/extensions/webhook/certificates/certificates_test.go
Labels: kind/enhancement, area/security, size/XL, area/usability, cla: yes, lgtm, approved

#6056 Added a prerequisite
  docs/deployment/getting_started_locally.md
  docs/development/getting_started_locally.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#6026 [ci:component:github.com/gardener/etcd-druid:v0.8.5->v0.9.0]
  charts/images.yaml
  example/seed-crds/10-crd-druid.gardener.cloud_etcds.yaml
  go.mod
  go.sum
  pkg/operation/botanist/component/etcd/bootstrap.go
  pkg/operation/botanist/component/etcd/bootstrap_test.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/names.go
  vendor/modules.txt
Labels: kind/enhancement, area/control-plane, cla: yes, lgtm, approved, size/XXL

#6054 Handle scaling of MCM as part of generic Worker actuator reconciliation
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/controller/csimigration/reconciler.go
  extensions/pkg/controller/healthcheck/reconciler.go
  extensions/pkg/controller/shoot.go
  extensions/pkg/controller/shoot_test.go
  extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/genericactuator/machine_controller_manager.go
Labels: kind/enhancement, size/L, area/robustness, area/control-plane, cla: yes, lgtm, approved

#6065 Higher timeout for `kube-apiserver` deployment task during ETCD encryption key rotation
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: kind/enhancement, area/security, area/ops-productivity, size/S, cla: yes, lgtm, approved

#6066 Apply resources in sorted order in managedresource controller
  pkg/resourcemanager/controller/managedresource/reconciler.go
  pkg/resourcemanager/controller/managedresource/sort.go
  pkg/resourcemanager/controller/managedresource/sort_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#6055 Combine systemd log streams per shoot node
  docs/usage/images/explore-button-usage.png
  docs/usage/images/shoot-node-logging-architecture.png
  docs/usage/logging.md
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/config_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/templates/promtail-config.tpl.yaml
Labels: kind/enhancement, size/L, area/logging, cla: yes, lgtm, approved

#6074 Removed overrides from manifest file
  .docforge/manifest.yaml
  docs/concepts/apiserver.md
  docs/concepts/apiserver_admission_plugins.md
  docs/concepts/cluster-api.md
  docs/deployment/gardenlet_api_access.md
  docs/development/changing-the-api.md
  docs/extensions/backupbucket.md
  docs/extensions/backupentry.md
  docs/extensions/ca-rotation.md
  docs/extensions/containerruntime.md
  docs/extensions/controllerregistration.md
  docs/extensions/controlplane-exposure.md
  docs/extensions/controlplane-webhooks.md
  docs/extensions/controlplane.md
  docs/extensions/dns.md
  docs/extensions/dnsrecord.md
  docs/proposals/04-new-core-gardener-cloud-apis.md
  docs/proposals/08-shoot-apiserver-via-sni.md
  docs/usage/apiserver-sni-injection.md
  docs/usage/csi_components.md
  docs/usage/custom-dns.md
  docs/usage/dns-autoscaling.md
  docs/usage/exposureclasses.md
  docs/usage/node-local-dns.md
  docs/usage/openidconnect-presets.md
  docs/usage/reversed-vpn-tunnel.md
  docs/usage/shooted_seed.md
Labels: kind/enhancement, area/documentation, size/L, cla: yes, lgtm, approved

#6061 Export gardener-local kubeconfig once in Makefile
  Makefile
  hack/tools.mk
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#6064 Perform snapshot of ETCD after secrets got encrypted with new key
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/secrets_test.go
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#6071 Update coredns to 1.9.3.
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#6072 [GEP-18] Credentials rotation e2e test
  docs/development/testing.md
  hack/test-e2e-local.sh
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/secrets.go
  test/e2e/e2e_suite_test.go
  test/e2e/shoot/common.go
  test/e2e/shoot/create_rotate-ca_delete.go
  test/e2e/shoot/create_rotate_delete.go
  test/e2e/shoot/internal/rotation/certificate_authorities.go
  test/e2e/shoot/internal/rotation/etcd_encryption_key.go
  test/e2e/shoot/internal/rotation/kubeconfig.go
  test/e2e/shoot/internal/rotation/observability.go
  test/e2e/shoot/internal/rotation/service_account_key.go
  test/e2e/shoot/internal/rotation/ssh_keypair.go
  test/e2e/shoot/internal/rotation/utils.go
  test/e2e/shoot/internal/rotation/verifier.go
  test/framework/gardener_utils.go
  test/framework/gardenerframework.go
  test/framework/k8s_utils.go
  test/framework/shootcreationframework.go
  test/framework/shootframework.go
  test/testmachinery/system/complete_reconcile/gardener_reconcile_test.go
Labels: area/security, kind/test, area/testing, cla: yes, lgtm, approved, size/XXL

#6077 Extend `serviceaccountmanager` docu to cover kubectl 1.24
  docs/usage/project_namespace_access.md
Labels: kind/enhancement, area/documentation, size/S, cla: yes, lgtm, approved

#6075 Drop `constants` package and unused `helper` functions for `core.gardener.cloud/v1alpha1`
  pkg/apis/core/v1alpha1/constants/types_constants.go
  pkg/apis/core/v1alpha1/helper/condition_builder_test.go
  pkg/apis/core/v1alpha1/helper/helper.go
  pkg/apis/core/v1alpha1/helper/helper_test.go
  pkg/apis/core/v1alpha1/helper/shootstate_list.go
  pkg/apis/core/v1alpha1/helper/shootstate_list_test.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/controllermanager/controller/exposureclass/exposureclass_control.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/operation/botanist/component/istio/ingress_gateway.go
  pkg/operation/botanist/component/istio/ingress_gateway_test.go
  pkg/operation/seed/seed.go
  pkg/utils/gardener/exposureclass.go
Labels: area/dev-productivity, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#6076 [provider-local] Add support for `PersistentVolumeClaim`s in local shoot clusters
  charts/gardener/provider-local/internal/shoot-storageclasses/Chart.yaml
  charts/gardener/provider-local/internal/shoot-storageclasses/templates/storageclasses.yaml
  charts/gardener/provider-local/internal/shoot-system-components/Chart.yaml
  charts/gardener/provider-local/internal/shoot-system-components/charts/local-path-provisioner/Chart.yaml
  charts/gardener/provider-local/internal/shoot-system-components/charts/local-path-provisioner/templates/clusterrole.yaml
  charts/gardener/provider-local/internal/shoot-system-components/charts/local-path-provisioner/templates/clusterrolebinding.yaml
  charts/gardener/provider-local/internal/shoot-system-components/charts/local-path-provisioner/templates/configmap.yaml
  charts/gardener/provider-local/internal/shoot-system-components/charts/local-path-provisioner/templates/deployment.yaml
  charts/gardener/provider-local/internal/shoot-system-components/charts/local-path-provisioner/templates/serviceaccount.yaml
  charts/gardener/provider-local/internal/shoot-system-components/charts/local-path-provisioner/values.yaml
  charts/gardener/provider-local/internal/shoot-system-components/requirements.yaml
  docs/extensions/provider-local.md
  pkg/provider-local/controller/controlplane/add.go
  pkg/provider-local/controller/controlplane/valuesprovider.go
  pkg/provider-local/controller/worker/machine_controller_manager.go
  pkg/provider-local/imagevector/images.go
  pkg/provider-local/imagevector/images.yaml
Labels: kind/bug, area/security, size/L, cla: yes, lgtm, approved

#6079 Do not persist `rotate-{ca,serviceaccount-key}-{start,complete}` annotation if `Shoot{C,S}ARotation` feature gates disabled
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: kind/bug, area/security, size/M, cla: yes, lgtm, approved

#6078 Do not rely on `kube-controller-manager` removing `Secret`s from `ServiceAccount` spec
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/secrets_test.go
Labels: kind/bug, area/security, size/S, cla: yes, lgtm, approved

#5976 Add MaxAllowed for VPA objects
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/operation/botanist/component/kubeproxy/kube_proxy_test.go
  pkg/operation/botanist/component/kubeproxy/resources.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#6087 Fix a nil pointer exception on webhook registration
  extensions/pkg/webhook/cmd/options.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#6082 Use strategic merge for patching `ShootState.Spec.Gardener`
  pkg/gardenlet/controller/shootsecret/reconciler.go
  pkg/operation/operation.go
  pkg/operation/operation_test.go
Labels: kind/enhancement, size/S, area/scalability, cla: yes, lgtm, approved

#6089 Dump container logs of e2e tests
  hack/test-e2e-local.sh
Labels: kind/enhancement, area/dev-productivity, size/S, area/testing, cla: yes, lgtm, approved

#6093 Add serviceaccountmanager permissions to administratos
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
Labels: kind/enhancement, size/XS, area/usability, cla: yes, lgtm, approved

#6094 Augment the list of known gardener extensions
  extensions/README.md
Labels: kind/enhancement, area/open-source, size/S, cla: yes, lgtm, approved

#6069 fix renew-kubeconfig annotation
  pkg/admissioncontroller/webhooks/admission/seedrestriction/admission.go
  pkg/admissioncontroller/webhooks/admission/seedrestriction/admission_test.go
  pkg/admissioncontroller/webhooks/auth/seed/graph/eventhandler_managedseed.go
  pkg/admissioncontroller/webhooks/auth/seed/graph/graph_test.go
  pkg/gardenlet/controller/managedseed/managedseed_actuator.go
  pkg/gardenlet/controller/managedseed/managedseed_actuator_test.go
Labels: kind/enhancement, size/M, area/robustness, cla: yes, lgtm, approved

#6086 fix webhook certificate reconciler in case no SeedWebhookConfig is there
  extensions/pkg/webhook/certificates/reconciler.go
  test/integration/extensions/webhook/certificates/certificates_test.go
Labels: kind/bug, size/XL, cla: yes, lgtm, approved

#6096 Use optimistic locking for populating requested token
  pkg/client/kubernetes/clientmap/internal/generic_clientmap.go
  pkg/resourcemanager/controller/tokenrequestor/reconciler.go
Labels: kind/bug, size/XS, area/robustness, cla: yes, lgtm, approved

#5741 Introduce HA shoot control planes in alpha state
  charts/seed-monitoring/charts/core/charts/prometheus/templates/allow-prometheus-network-policy.yaml
  docs/concepts/scheduler.md
  docs/deployment/feature_gates.md
  example/20-componentconfig-gardener-scheduler.yaml
  example/20-componentconfig-gardenlet.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/features/features.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_migrate.go
  pkg/gardenlet/features/features.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_suite_test.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/etcd/monitoring_test.go
  pkg/operation/botanist/component/etcd/waiter_test.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/networkpolicies.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operation/botanist/secrets.go
  pkg/scheduler/controller/shoot/reconciler.go
  pkg/scheduler/controller/shoot/reconciler_test.go
  pkg/scheduler/controller/shoot/scheduler_suite_test.go
  pkg/scheduler/features/features.go
  test/integration/scheduler/scheduler_suite_test.go
  test/integration/seedadmissioncontroller/testdata/etcd.yaml
Labels: kind/enhancement, area/high-availability, area/control-plane, cla: yes, lgtm, approved, size/XXL

#6100 Remove limits carry-over for loki
  pkg/operation/botanist/logging.go
  pkg/operation/seed/seed.go
Labels: kind/bug, size/XS, area/auto-scaling, cla: yes, lgtm, approved

#6057 Add node local dns option to shoot spec and roll nodes in case it is switched.
  docs/api-reference/core.md
  docs/usage/node-local-dns.md
  example/90-shoot.yaml
  extensions/pkg/controller/worker/machines.go
  extensions/pkg/controller/worker/machines_test.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/extensions/worker/worker.go
  pkg/operation/botanist/component/extensions/worker/worker_test.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns_test.go
  pkg/operation/botanist/nodelocaldns.go
  pkg/operation/botanist/worker.go
  pkg/operation/shoot/shoot.go
Labels: kind/enhancement, area/usability, area/networking, cla: yes, lgtm, approved, size/XXL

#6098 [GEP-18] Advanced checks for credentials e2e test (1)
  extensions/pkg/webhook/controlplane/genericmutator/mutator_test.go
  hack/test-e2e-local.sh
  test/e2e/shoot/create_and_delete.go
  test/e2e/shoot/create_rotate_delete.go
  test/e2e/shoot/internal/access.go
  test/e2e/shoot/internal/rotation/certificate_authorities.go
  test/e2e/shoot/internal/rotation/kubeconfig.go
  test/e2e/shoot/internal/rotation/secret_encryption.go
  test/e2e/shoot/internal/rotation/shoot_access.go
  test/e2e/shoot/internal/rotation/verifier.go
Labels: kind/enhancement, area/security, size/XL, area/testing, cla: yes, lgtm, approved

#6105 [HA] Don't schedule single-zonal shoots on multi-zonal seeds
  pkg/scheduler/controller/shoot/reconciler.go
  pkg/scheduler/controller/shoot/reconciler_test.go
Labels: kind/enhancement, size/M, area/high-availability, cla: yes, lgtm, approved

#6108 Increase VPA Recommender log level to v=3
  pkg/operation/botanist/component/vpa/recommender.go
  pkg/operation/botanist/component/vpa/vpa_test.go
Labels: kind/enhancement, size/XS, area/auto-scaling, cla: yes, lgtm, approved

#6107 Keep node local dns components during the roll out of new nodes.
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/component/nodelocaldns/mock/doc.go
  pkg/operation/botanist/component/nodelocaldns/mock/mocks.go
  pkg/operation/botanist/nodelocaldns.go
  pkg/operation/botanist/nodelocaldns_test.go
Labels: kind/enhancement, size/L, area/networking, cla: yes, lgtm, approved

#6109 Do not use global variables in GRM component
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
Labels: size/M, kind/regression, area/control-plane, cla: yes, lgtm, approved

#6115 Bump `nginx-ingress-controller` image
  charts/images.yaml
Labels: kind/enhancement, area/security, size/XS, ok-to-test, cla: yes, lgtm, approved

#6119 Upgrade grafana to 7.5.16
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#6116 Cleanup utility functions
  extensions/pkg/webhook/certificates/certificates.go
  pkg/gardenlet/controller/shoot/seed_registration_control_test.go
  pkg/operation/botanist/resource_manager.go
  pkg/operation/seed/components.go
  pkg/utils/miscellaneous.go
  pkg/utils/secrets/manager/generate_test.go
Labels: area/dev-productivity, kind/cleanup, cla: yes, lgtm, approved

#6125 Use optimistic locking for reconciling shoot access secret
  pkg/controllerutils/patch.go
  pkg/controllerutils/patch_test.go
  pkg/resourcemanager/controller/secret/reconciler_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/test/test.go
Labels: kind/bug, size/L, area/robustness, cla: yes, lgtm, approved

#6123 Remove alpine based envoy image
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/open-source, cla: yes, lgtm, approved

#6110 [GEP-18] Add client warnings for `Shoot`s when credentials rotation is due
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/values.yaml
  pkg/api/core/shoot/shoot_suite_test.go
  pkg/api/core/shoot/warnings.go
  pkg/api/core/shoot/warnings_test.go
  pkg/apiserver/apiserver.go
  pkg/registry/core/rest/storage_core.go
  pkg/registry/core/shoot/storage/storage.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: kind/enhancement, area/security, size/XL, component/gardener, cla: yes, lgtm, approved

#6137 [provider-local] Bump `machine-controller-manager{-provider-local}` versions
  charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/clusterrole.yaml
  go.mod
  go.sum
  pkg/provider-local/imagevector/images.go
  pkg/provider-local/imagevector/images.yaml
  vendor/github.com/cespare/xxhash/v2/.travis.yml
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/alicoud_machineclass_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/machine_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/machineclass_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/zz_generated.deepcopy.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/text_parse.go
  vendor/github.com/prometheus/procfs/Makefile
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/README.md
  vendor/github.com/prometheus/procfs/cmdline.go
  vendor/github.com/prometheus/procfs/doc.go
  vendor/github.com/prometheus/procfs/fixtures.ttar
  vendor/github.com/prometheus/procfs/mdstat.go
  vendor/github.com/prometheus/procfs/net_ip_socket.go
  vendor/github.com/prometheus/procfs/netstat.go
  vendor/github.com/prometheus/procfs/proc_cgroup.go
  vendor/github.com/prometheus/procfs/proc_stat.go
  vendor/github.com/prometheus/procfs/zoneinfo.go
  vendor/modules.txt
Labels: kind/enhancement, area/open-source, cla: yes, lgtm, approved, size/XXL

#6090 Introduce option to remediate problematic shoot webhooks
  charts/gardener/gardenlet/charts/runtime/templates/_helpers.tpl
  charts/gardener/gardenlet/values.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-pod-mutatingwebhook.yaml
  docs/usage/shoot_status.md
  example/20-componentconfig-gardenlet.yaml
  extensions/pkg/webhook/registration.go
  extensions/pkg/webhook/registration_test.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/gardenlet/controller/shoot/shoot_care_control_types.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/vpa/general.go
  pkg/operation/botanist/component/vpa/vpa_test.go
  pkg/operation/botanist/matchers/matcher.go
  pkg/operation/care/constraints.go
  pkg/operation/care/webhook_remediation.go
  pkg/operation/care/webhook_remediation_test.go
Labels: kind/enhancement, size/XL, area/ops-productivity, cla: yes, lgtm, approved

#6132 Improve the CPU and memory usage calculation on the Node Details dashboard
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-details-dashboard.json
Labels: kind/enhancement, size/M, area/monitoring, component/gardener, cla: yes, lgtm, approved

#6140 Write the blackbox exporter scrape probe logs also to stdout
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6139 Do not deny updates for old shoots with invalid domains
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
Labels: kind/bug, area/security, area/ops-productivity, size/M, cla: yes, lgtm, approved

#6142 Promote feature gate `DisableDNSProviderManagement` to Beta
  docs/deployment/feature_gates.md
  pkg/features/features.go
  pkg/operation/botanist/dnsresources_test.go
Labels: kind/enhancement, area/open-source, size/S, cla: yes, lgtm, approved

#6144 Add dependency for node local dns
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#6147 fix: Alert dashboard panels
  charts/seed-bootstrap/dashboards/alerts-dashboard.json
Labels: kind/enhancement, size/XS, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#6135 Refactor `reserve-excess-capacity` Helm chart into Golang component
  charts/seed-bootstrap/templates/reserve-excess-capacity/deployment.yaml
  charts/seed-bootstrap/templates/reserve-excess-capacity/priorityclass.yaml
  charts/seed-bootstrap/values.yaml
  pkg/operation/botanist/component/seedsystem/seedsystem.go
  pkg/operation/botanist/component/seedsystem/seedsystem_suite_test.go
  pkg/operation/botanist/component/seedsystem/seedsystem_test.go
  pkg/operation/care/seed_health.go
  pkg/operation/care/seed_health_test.go
  pkg/operation/seed/components.go
  pkg/operation/seed/seed.go
Labels: kind/enhancement, area/dev-productivity, size/XL, area/quality, kind/test, area/robustness, kind/technical-debt, component/gardener, cla: yes, lgtm, approved

#6134 Refactor `shoot-info` Helm chart into Golang component
  charts/shoot-core/components/charts/shoot-info/templates/configmap.yaml
  charts/shoot-core/components/charts/shoot-info/values.yaml
  charts/shoot-core/components/values.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/component/shootsystem/shootsystem.go
  pkg/operation/botanist/component/shootsystem/shootsystem_test.go
  pkg/operation/botanist/shootsystem.go
  pkg/operation/seed/seed.go
Labels: kind/enhancement, area/dev-productivity, area/quality, size/L, kind/test, area/robustness, kind/technical-debt, component/gardener, cla: yes, lgtm, approved

#6124 Make "cloud-config execution max delay seconds" configurable per `Shoot`
  example/provider-local/shoot.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/executor/executor.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/executor/executor_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/executor/templates/scripts/execute-cloud-config.tpl.sh
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/operatingsystemconfig_test.go
  pkg/operation/botanist/worker.go
  pkg/operation/botanist/worker_test.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
  test/e2e/shoot/common.go
Labels: kind/enhancement, area/dev-productivity, size/L, area/robustness, component/gardener, cla: yes, lgtm, approved

#6148 Forbid certain rotation operations when `Shoot` is hibernated
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: kind/bug, area/security, size/L, cla: yes, lgtm, approved

#6155 Make scripts in hack compatible with NixOS
  hack/check-apidiff.sh
  hack/check-charts.sh
  hack/check-generate.sh
  hack/check.sh
  hack/clean.sh
  hack/compare-k8s-controllers.sh
  hack/compare-k8s-feature-gates.sh
  hack/format.sh
  hack/generate-controller-registration.sh
  hack/generate-imagename-constants.sh
  hack/generate-parallel.sh
  hack/generate.sh
  hack/get-build-ld-flags.sh
  hack/install-requirements.sh
  hack/install.sh
  hack/local-development/common/helpers
  hack/local-development/common/local-imagevector-overwrite
  hack/local-development/dev-setup
  hack/local-development/dev-setup-register-gardener
  hack/local-development/start-admission-controller
  hack/local-development/start-apiserver
  hack/local-development/start-controller-manager
  hack/local-development/start-extension-provider-local
  hack/local-development/start-gardenlet
  hack/local-development/start-resource-manager
  hack/local-development/start-scheduler
  hack/local-development/start-seed-admission-controller
  hack/tools/install-promtool.sh
  hack/update-codegen.sh
  hack/update-protobuf.sh
  hack/usage/delete
  hack/usage/shoot-operation
Labels: kind/enhancement, area/dev-productivity, size/M, ok-to-test, cla: yes, lgtm, approved

#6133 Refactor `hvpa` Helm chart into component
  charts/seed-bootstrap-crds/Chart.yaml
  charts/seed-bootstrap-crds/charts/hvpa/Chart.yaml
  charts/seed-bootstrap-crds/charts/hvpa/values.yaml
  charts/seed-bootstrap-crds/values.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/_helpers.tpl
  charts/seed-bootstrap/charts/hvpa/Chart.yaml
  charts/seed-bootstrap/charts/hvpa/charts/utils-templates
  charts/seed-bootstrap/charts/hvpa/templates/controller-deployment.yaml
  charts/seed-bootstrap/charts/hvpa/templates/hvpa-rbac.yaml
  charts/seed-bootstrap/charts/hvpa/values.yaml
  charts/seed-bootstrap/requirements.yaml
  charts/seed-bootstrap/templates/prometheus/config.yaml
  charts/seed-bootstrap/values.yaml
  pkg/operation/botanist/component/hvpa/crd.go
  pkg/operation/botanist/component/hvpa/crd_test.go
  pkg/operation/botanist/component/hvpa/hvpa.go
  pkg/operation/botanist/component/hvpa/hvpa_suite_test.go
  pkg/operation/botanist/component/hvpa/hvpa_test.go
  pkg/operation/botanist/component/hvpa/logging.go
  pkg/operation/botanist/component/hvpa/logging_test.go
  pkg/operation/botanist/component/hvpa/monitoring.go
  pkg/operation/botanist/component/hvpa/monitoring_test.go
  pkg/operation/botanist/component/hvpa/templates/crd.tpl.yaml
  pkg/operation/care/seed_health.go
  pkg/operation/care/seed_health_test.go
  pkg/operation/common/utils.go
  pkg/operation/seed/components.go
  pkg/operation/seed/seed.go
Labels: kind/enhancement, area/dev-productivity, area/quality, kind/test, area/robustness, kind/technical-debt, component/gardener, cla: yes, lgtm, approved, size/XXL

#6113 Allow passing custom REST configuration settings to extension shoot clients
  extensions/pkg/controller/csimigration/reconciler.go
  extensions/pkg/controller/csimigration/reconciler_test.go
  extensions/pkg/controller/healthcheck/config/types.go
  extensions/pkg/controller/healthcheck/controller.go
  extensions/pkg/controller/healthcheck/healthcheck_actuator.go
  extensions/pkg/util/shoot_clients.go
  extensions/pkg/webhook/handler_shootclient.go
  pkg/provider-local/controller/healthcheck/add.go
Labels: kind/enhancement, area/performance, size/M, cla: yes, lgtm, approved

#6138 Update node local dns to v1.22.5
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#6164 `start-gardenlet` respects `IMAGEVECTOR_OVERWRITE` env var
  hack/local-development/start-gardenlet
Labels: kind/enhancement, size/XS, area/usability, cla: yes, lgtm, approved

#6167 Add missing `// +optional` and `omitempty` tags
  docs/api-reference/core.md
  pkg/admissioncontroller/webhooks/admission/resourcesize/admission_test.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/openapi/openapi_generated.go
Labels: kind/bug, area/open-source, size/S, cla: yes, lgtm, approved

#6159 Change some of the Gardener components' base images to distroless
  Dockerfile
  Dockerfile.local
  charts/gardener/controlplane/charts/application/templates/service-apiserver.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/service.yaml
Labels: kind/enhancement, area/security, area/open-source, size/M, cla: yes, lgtm, approved

#6149 [GEP-18] Add a new constraint in `.status.constraints` for `Shoot`s whose CAs are expiring in less than `1y`
  docs/usage/shoot_status.md
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/gardenlet/controller/shoot/shoot_care_control_test.go
  pkg/gardenlet/controller/shoot/shoot_care_control_types.go
  pkg/operation/care/constraints.go
  pkg/operation/care/constraints_test.go
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL

#6171 Upgrade node-exporter to v1.3.1
  charts/images.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6172 seed care: Check for the hvpa ManagedResource only when the HVPA feature gate is enabled
  pkg/operation/care/care_suite_test.go
  pkg/operation/care/seed_health.go
  pkg/operation/care/seed_health_test.go
Labels: kind/bug, size/S, area/control-plane, cla: yes, lgtm, approved

#6170 Secure port of gapi-server can now be configured through the helm chart
  charts/gardener/controlplane/charts/application/templates/service-apiserver.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/service.yaml
  charts/gardener/controlplane/values.yaml
Labels: kind/enhancement, area/usability, size/S, cla: yes, lgtm, approved

#6173 gardener-kube-scheduler: Support K8s 1.24 Seeds
  pkg/operation/botanist/component/gardenerkubescheduler/gardener_kube_scheduler_bootstrap.go
  pkg/operation/botanist/component/gardenerkubescheduler/gardener_kube_scheduler_bootstrap_test.go
  pkg/utils/version/version.go
Labels: kind/enhancement, size/S, area/scalability, cla: yes, lgtm, approved

#6176 `gardener-scheduler` provides meaningful error message when no seeds with matching providers found
  pkg/scheduler/controller/shoot/reconciler.go
Labels: kind/enhancement, area/ops-productivity, size/XS, cla: yes, lgtm, approved

#6174 Exclude optional addons from compliance scans
  charts/images.yaml
Labels: kind/enhancement, size/M, area/compliance, cla: yes, lgtm, approved

#6175 Skip projected token mount for gardenlet pods
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
Labels: kind/bug, area/robustness, size/S, cla: yes, lgtm, approved

#6177 Upgrade machine-controller-manager-provider-local
  pkg/provider-local/imagevector/images.yaml
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#6166 Enhance shoot update test and promote `WorkerPoolKubernetesVersion` to GA
  .test-defs/ShootKubernetesUpdateTest.yaml
  Makefile
  cmd/gardener-apiserver/app/gardener_apiserver.go
  docs/deployment/feature_gates.md
  docs/deployment/getting_started_locally.md
  docs/development/getting_started_locally.md
  docs/development/testing.md
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/features/features.go
  test/e2e/shoot/create_update_delete.go
  test/e2e/shoot/internal/rotation/secret_encryption.go
  test/e2e/shoot/internal/rotation/shoot_access.go
  test/testmachinery/system/shoot_update/update_test.go
  test/utils/shoots/access/adminkubeconfig.go
  test/utils/shoots/access/csr.go
  test/utils/shoots/access/serviceaccount.go
  test/utils/shoots/access/statictokenkubeconfig.go
  test/utils/shoots/update/update.go
Labels: kind/enhancement, area/open-source, size/L, kind/test, cla: yes, lgtm, approved

#6187 [GRM] Allow grm to read its service account token
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#6183 Activate the `diskstats` collector for the node_exporter
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6181 Adapt allow-to-dns networkpolicy to also work with node local dns in cilium case
  charts/shoot-core/components/charts/network-policies/templates/allow-to-dns.yaml
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/addons/networkpolicy/shoot_network_policy.go
  pkg/operation/botanist/addons/networkpolicy/shoot_network_policy_suite_test.go
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved

#6189 Increase timeouts in `create_update_delete` e2e test
  test/e2e/shoot/create_update_delete.go
Labels: size/XS, area/testing, kind/flake, cla: yes, lgtm, approved

#6184 Change the default audit.log path
  charts/gardener/controlplane/values.yaml
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#6190 Fixed broken links - 06-2022
  docs/concepts/gardenlet.md
  docs/deployment/gardenlet_api_access.md
  docs/development/kubernetes-clients.md
  docs/proposals/10-shoot-additional-container-runtimes.md
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#6163 Upgrade github.com/gardener/autoscaler
  charts/images.yaml
Labels: kind/enhancement, size/S, area/auto-scaling, cla: yes, lgtm, approved

#6193 Clean up GA-ed feature gates
  docs/deployment/feature_gates.md
  docs/extensions/dnsrecord.md
  pkg/apiserver/features/features.go
  pkg/controllermanager/features/features.go
  pkg/features/features.go
  pkg/gardenlet/features/features.go
Labels: size/M, kind/cleanup, cla: yes, lgtm, approved

#6201 Switch back the istiod PriorityClass name to `istiod`
  pkg/operation/botanist/component/istio/istiod.go
  pkg/operation/botanist/component/istio/istiod_test.go
Labels: size/XS, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#6099 Add CA rotation support for multi-node etcd clusters
  cmd/gardener-extension-provider-local/app/app.go
  example/20-componentconfig-gardener-scheduler.yaml
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/controlplane/values.yaml
  example/gardener-local/gardenlet/values.yaml
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/etcd/mock/mocks.go
  pkg/operation/botanist/component/etcd/monitoring_test.go
  pkg/operation/botanist/component/etcd/waiter_test.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
  pkg/operation/seed/seed.go
  pkg/operation/seed/types.go
  pkg/provider-local/webhook/controlplane/add.go
  pkg/provider-local/webhook/controlplane/ensurer.go
  test/e2e/shoot/create_rotate_delete.go
Labels: kind/enhancement, area/security, size/XL, area/high-availability, cla: yes, lgtm, approved

#6186 Introduce well-known and fine-granular `PriorityClasses` managed by gardenlet
  charts/seed-bootstrap/templates/priorityclass-shoot-controlplane.yaml
  charts/seed-bootstrap/values.yaml
  docs/README.md
  docs/development/priority-classes.md
  docs/extensions/conventions.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/component/seedsystem/seedsystem.go
  pkg/operation/botanist/component/seedsystem/seedsystem_test.go
  pkg/operation/botanist/component/shootsystem/shootsystem.go
  pkg/operation/botanist/component/shootsystem/shootsystem_test.go
  pkg/operation/common/utils.go
  pkg/operation/seed/seed.go
Labels: kind/enhancement, size/L, area/robustness, cla: yes, lgtm, approved

#6209 Properly define `cluster-autoscaler` image in `images.yaml`
  charts/images.yaml
Labels: kind/bug, size/XS, area/usability, cla: yes, lgtm, approved

#6202 Properly `Unwrap` errors from flow when construction `lastErrors`
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/utils/errors/errors.go
Labels: kind/enhancement, area/ops-productivity, size/XS, component/gardener, cla: yes, lgtm, approved

#6207 Only reset conditions when resource set changes
  pkg/resourcemanager/controller/managedresource/reconciler.go
Labels: kind/enhancement, area/ops-productivity, size/XS, cla: yes, lgtm, approved

#6218 [release-v1.47] Automated cherry pick of #6207: Only reset conditions when resource set changes
  pkg/resourcemanager/controller/managedresource/reconciler.go
Labels: kind/bug, size/XS, cla: yes, lgtm, approved

#6156 Enhance image vector APIs to support multi arch images
  docs/deployment/image_vector.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/utils/imagevector/imagevector.go
  pkg/utils/imagevector/imagevector_test.go
  pkg/utils/imagevector/types.go
Labels: kind/enhancement, area/delivery, size/L, cla: yes, lgtm, approved

#6178 Enhance `CloudProfile` and `Worker` API to support multi arch machines and machine images
  docs/api-reference/core.md
  docs/api-reference/extensions.md
  example/30-cloudprofile.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_workers.yaml
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_cloudprofile.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/zz_generated.defaults.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/extensions/v1alpha1/types_worker.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/extensions/validation/worker.go
  pkg/apis/extensions/validation/worker_test.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_workers.yaml
Labels: kind/enhancement, area/delivery, cla: yes, lgtm, approved, size/XXL

#6238 Use multi arch pause image
  charts/images.yaml
Labels: kind/enhancement, area/delivery, size/XS, cla: yes, lgtm, approved

#6233 Enhance `Shoot` API to support multi arch machines
  docs/api-reference/core.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/seedmanagement/validation/managedseedset_test.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/extensions/worker/worker.go
  pkg/operation/botanist/component/extensions/worker/worker_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, area/delivery, cla: yes, lgtm, approved, size/XXL

#6226 Drop duplicative `hvpa-controller` logging filter
  charts/seed-bootstrap/charts/fluent-bit/templates/_helpers.tpl
Labels: area/dev-productivity, kind/cleanup, cla: yes, lgtm, approved

#6234 Use existing API in `CentralLoggingConfig` for exposing logs to users
  pkg/operation/botanist/component/clusterautoscaler/logging.go
  pkg/operation/botanist/component/clusterautoscaler/logging_test.go
  pkg/operation/botanist/component/coredns/logging_test.go
  pkg/operation/botanist/component/dependencywatchdog/logging_test.go
  pkg/operation/botanist/component/etcd/logging_test.go
  pkg/operation/botanist/component/hvpa/logging_test.go
  pkg/operation/botanist/component/kubeapiserver/logging.go
  pkg/operation/botanist/component/kubeapiserver/logging_test.go
  pkg/operation/botanist/component/kubecontrollermanager/logging.go
  pkg/operation/botanist/component/kubecontrollermanager/logging_test.go
  pkg/operation/botanist/component/kubeproxy/logging_test.go
  pkg/operation/botanist/component/kubescheduler/logging.go
  pkg/operation/botanist/component/kubescheduler/logging_test.go
  pkg/operation/botanist/component/metricsserver/logging_test.go
  pkg/operation/botanist/component/nodeproblemdetector/logging_test.go
  pkg/operation/botanist/component/seedadmissioncontroller/logging_test.go
  pkg/operation/botanist/component/types.go
  pkg/operation/botanist/component/vpa/logging.go
  pkg/operation/botanist/component/vpa/logging_test.go
  pkg/operation/botanist/component/vpnseedserver/logging_test.go
  pkg/operation/botanist/component/vpnshoot/logging_test.go
  pkg/operation/seed/seed.go
Labels: area/dev-productivity, size/M, kind/cleanup, cla: yes, lgtm, approved

#6237 Update the conformance spreadsheet URL and the highest certified version
  README.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#6240 Promote the `SecretBindingProviderValidation` feature gate to beta
  docs/deployment/feature_gates.md
  docs/deployment/secret_binding_provider_controller.md
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/defaults_test.go
  pkg/features/features.go
  test/integration/scheduler/scheduler_suite_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/enhancement, size/M, component/gardener, cla: yes, lgtm, approved

#6205 Use `metadata.labels["node"]` when restoring `Machine` resources
  extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  extensions/pkg/controller/worker/genericactuator/actuator_test.go
  extensions/pkg/controller/worker/state_actuator.go
Labels: kind/enhancement, size/M, area/control-plane-migration, cla: yes, lgtm, approved

#6241 Drop GA-ed or deprecated feature gates
  docs/api-reference/core.md
  docs/deployment/feature_gates.md
  docs/proposals/17-shoot-control-plane-migration-bad-case.md
  docs/usage/shoot_credentials_rotation.md
  example/gardener-local/controlplane/values.yaml
  extensions/README.md
  hack/local-development/start-apiserver
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apiserver/features/features.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/controllermanager/features/features.go
  pkg/features/features.go
  pkg/openapi/openapi_generated.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: area/open-source, size/L, kind/cleanup, cla: yes, lgtm, approved

#6224 Upgrade kube-state-metrics to 2.5.0
  charts/gardener/provider-local/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  charts/images.yaml
  charts/seed-bootstrap/charts/kube-state-metrics/templates/deployment.yaml
  charts/seed-bootstrap/prometheus-rules/recording-rules.rules.yaml
  charts/seed-bootstrap/values.yaml
  charts/seed-monitoring/charts/core/charts/kube-state-metrics-shoot/templates/deployment.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-state-metrics.rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/seed-monitoring/charts/grafana/dashboards/operators/kubernetes-daemonsets-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/kubernetes-pods-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/vpa-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/vpn-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/controlplane-logs-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-control-plane-status-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-details-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-pool-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/shoot-vpa-dashboard.json
Labels: kind/enhancement, size/L, area/monitoring, cla: yes, lgtm, approved

#6244 Add containerd parser
  charts/seed-bootstrap/charts/fluent-bit/templates/_fluent-bit-config.tpl
  charts/seed-bootstrap/charts/fluent-bit/templates/_helpers.tpl
Labels: kind/enhancement, area/logging, size/S, cla: yes, lgtm, approved

#6243 Update VPA to 0.11.0
  charts/images.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/enhancement, size/S, area/auto-scaling, cla: yes, lgtm, approved

#6231 Move shoot-specific `hvpa` monitoring config into component package
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/component/hvpa/hvpa.go
  pkg/operation/botanist/component/hvpa/mock/doc.go
  pkg/operation/botanist/component/hvpa/mock/mocks.go
  pkg/operation/botanist/component/hvpa/monitoring.go
  pkg/operation/botanist/component/hvpa/monitoring_test.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/monitoring_test.go
  pkg/operation/seed/components.go
  pkg/operation/shoot/types.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved
