Repository gardener/gardener, pull requests merged in 2022-05, with the labels that each got.

#5881 [release-v1.43] Make sure secret manager's clean up is executed at the end of the flow
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: kind/bug, size/S, cla: yes, lgtm, approved

#5882 Deflake watchdog test
  extensions/pkg/controller/common/checkerwatchdog.go
  extensions/pkg/controller/common/checkerwatchdog_test.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#5887 Update vpn2 images to v0.7.0.
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#5889 Add shoot-networking-filter extension to list
  extensions/README.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#5877 Promote `ShootMaxTokenExpirationValidation` feature gate to beta
  docs/deployment/feature_gates.md
  pkg/features/features.go
Labels: kind/enhancement, area/ops-productivity, size/XS, area/open-source, cla: yes, lgtm, approved

#5888 Always add default issuer to accepted issuers, add documentation
  docs/README.md
  docs/usage/shoot_serviceaccounts.md
  example/90-shoot.yaml
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
Labels: kind/bug, area/security, size/L, cla: yes, lgtm, approved

#5898 Revert "Apply resources in sorted order in managedresource controller (#5822)
  pkg/resourcemanager/controller/managedresource/reconciler.go
  pkg/resourcemanager/controller/managedresource/sort.go
  pkg/resourcemanager/controller/managedresource/sort_test.go
Labels: kind/bug, size/L, area/control-plane, cla: yes, lgtm, approved

#5906 Fix handling of automatic pull requests for container image updates of vpn2 repo.
  hack/.ci/set_dependency_version
Labels: kind/enhancement, reviewed/ok-to-test, size/XS, area/networking, cla: yes, lgtm, approved

#5907 Fix contorlplane migration integration test
  test/framework/gardener_utils.go
  test/framework/gardenerframework.go
  test/framework/k8s_utils.go
  test/framework/shootframework.go
  test/testmachinery/system/shoot_cp_migration/migrate_test.go
Labels: kind/bug, size/M, area/testing, area/control-plane-migration, cla: yes, lgtm, approved

#5905 Add egress-filter-refresher to special names in set_dependency_version
  hack/.ci/set_dependency_version
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#5918 Update apiserver-proxy to v0.4.0 and adapt dependency script so that automatic pull requests should do the right thing.
  charts/images.yaml
  hack/.ci/set_dependency_version
Labels: kind/bug, size/XS, area/networking, cla: yes, lgtm, approved

#5919 Remove gardenlet memory limit.
  charts/gardener/gardenlet/values.yaml
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
Labels: kind/bug, area/robustness, size/S, area/auto-scaling, cla: yes, lgtm, approved

#5897 [GEP-18] Cleanup `ca-client` migration and `ShootState` cleanup coding
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_migrate.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/secrets.go
  pkg/registry/core/shoot/storage/admin_kubeconfig.go
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
Labels: area/security, size/L, kind/cleanup, cla: yes, lgtm, approved

#5804 Update k8s.io/helm
  go.mod
  go.sum
  pkg/client/kubernetes/testdata/render-test/Chart.yaml
  vendor/k8s.io/helm/internal/third_party/dep/fs/fs.go
  vendor/k8s.io/helm/internal/third_party/dep/fs/rename.go
  vendor/k8s.io/helm/internal/third_party/dep/fs/rename_windows.go
  vendor/k8s.io/helm/pkg/chartutil/capabilities.go
  vendor/k8s.io/helm/pkg/chartutil/capabilities_versions_generated.go
  vendor/k8s.io/helm/pkg/chartutil/create.go
  vendor/k8s.io/helm/pkg/chartutil/doc.go
  vendor/k8s.io/helm/pkg/chartutil/load.go
  vendor/k8s.io/helm/pkg/chartutil/requirements.go
  vendor/k8s.io/helm/pkg/chartutil/values.go
  vendor/k8s.io/helm/pkg/downloader/chart_downloader.go
  vendor/k8s.io/helm/pkg/downloader/manager.go
  vendor/k8s.io/helm/pkg/engine/engine.go
  vendor/k8s.io/helm/pkg/getter/getter.go
  vendor/k8s.io/helm/pkg/getter/httpgetter.go
  vendor/k8s.io/helm/pkg/getter/plugingetter.go
  vendor/k8s.io/helm/pkg/helm/environment/environment.go
  vendor/k8s.io/helm/pkg/proto/hapi/chart/chart.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/chart/config.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/chart/metadata.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/chart/template.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/release/hook.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/release/info.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/release/release.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/release/status.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/release/test_run.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/release/test_suite.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/version/version.pb.go
  vendor/k8s.io/helm/pkg/provenance/sign.go
  vendor/k8s.io/helm/pkg/repo/chartrepo.go
  vendor/k8s.io/helm/pkg/repo/index.go
  vendor/k8s.io/helm/pkg/repo/repo.go
  vendor/k8s.io/helm/pkg/resolver/resolver.go
  vendor/k8s.io/helm/pkg/sympath/walk.go
  vendor/k8s.io/helm/pkg/tlsutil/cfg.go
  vendor/k8s.io/helm/pkg/version/version.go
  vendor/modules.txt
Labels: kind/enhancement, ok-to-test, cla: yes, lgtm, approved, size/XXL

#5625 Deprecate `DetermineError` functions
  extensions/pkg/controller/healthcheck/general/managed_resource.go
  extensions/pkg/controller/healthcheck/healthcheck_actuator.go
  extensions/pkg/controller/healthcheck/worker/nodes.go
  extensions/pkg/controller/infrastructure/reconciler.go
  extensions/pkg/controller/status.go
  extensions/pkg/controller/status_test.go
  extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  extensions/pkg/controller/worker/genericactuator/actuator_migrate.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/terraformer/terraformer.go
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/apis/core/v1beta1/helper/errors_test.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/extensions/customresources.go
  pkg/extensions/customresources_test.go
  pkg/operation/botanist/cleanup.go
  pkg/operation/botanist/component/extensions/dns/dns.go
  pkg/operation/care/checker.go
  pkg/utils/kubernetes/health/extensions.go
  pkg/utils/managedresources/managedresources.go
Labels: kind/enhancement, needs/review, area/ops-productivity, needs/ok-to-test, needs/second-opinion, area/quality, size/L, kind/technical-debt, merge/squash, cla: yes, lgtm, approved

#5933 Update coredns to v1.9.1
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#5922 Update envoy proxy to v1.21.2
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#5915 Use `--kubeconfig` flag for VPA recommender and updater
  pkg/operation/botanist/component/vpa/admissioncontroller.go
  pkg/operation/botanist/component/vpa/recommender.go
  pkg/operation/botanist/component/vpa/updater.go
  pkg/operation/botanist/component/vpa/vpa.go
  pkg/operation/botanist/component/vpa/vpa_test.go
Labels: area/open-source, size/L, kind/cleanup, cla: yes, lgtm, approved

#5904 Add `ResourcesProgressing` condition to `ManagedResources`
  cmd/gardener-resource-manager/app/app.go
  docs/concepts/resource-manager.md
  example/resource-manager/10-crd-resources.gardener.cloud_managedresources.yaml
  example/seed-crds/10-crd-resources.gardener.cloud_managedresources.yaml
  pkg/apis/resources/v1alpha1/helper/helper.go
  pkg/apis/resources/v1alpha1/helper/helper_suite_test.go
  pkg/apis/resources/v1alpha1/helper/helper_test.go
  pkg/apis/resources/v1alpha1/types.go
  pkg/operation/botanist/component/extensions/crds/templates/crd-resources.gardener.cloud_managedresources.yaml
  pkg/resourcemanager/cmd/target.go
  pkg/resourcemanager/controller/garbagecollector/add.go
  pkg/resourcemanager/controller/garbagecollector/reconciler.go
  pkg/resourcemanager/controller/health/add.go
  pkg/resourcemanager/controller/health/health_checker.go
  pkg/resourcemanager/controller/health/health_checker_test.go
  pkg/resourcemanager/controller/health/health_reconciler.go
  pkg/resourcemanager/controller/health/progressing_reconciler.go
  pkg/resourcemanager/controller/managedresource/add.go
  pkg/resourcemanager/controller/managedresource/merger.go
  pkg/resourcemanager/controller/managedresource/merger_test.go
  pkg/resourcemanager/controller/managedresource/reconciler.go
  pkg/resourcemanager/controller/rootcapublisher/reconciler.go
  pkg/resourcemanager/controller/rootcapublisher/reconciler_test.go
  pkg/resourcemanager/controller/secret/add.go
  pkg/resourcemanager/controller/secret/reconciler.go
  pkg/resourcemanager/controller/secret/reconciler_test.go
  pkg/resourcemanager/predicate/ignore.go
  pkg/utils/kubernetes/health/daemonset.go
  pkg/utils/kubernetes/health/daemonset_test.go
  pkg/utils/kubernetes/health/deployment.go
  pkg/utils/kubernetes/health/deployment_test.go
  pkg/utils/kubernetes/health/replicaset_test.go
  pkg/utils/kubernetes/health/replicationcontroller_test.go
  pkg/utils/kubernetes/health/statefulset.go
  pkg/utils/kubernetes/health/statefulset_test.go
  test/integration/resourcemanager/health/health_suite_test.go
  test/integration/resourcemanager/health/health_test.go
  test/integration/resourcemanager/managedresource/reconciler_suite_test.go
  test/integration/resourcemanager/managedresource/reconciler_test.go
Labels: kind/enhancement, area/robustness, cla: yes, lgtm, approved, size/XXL

#5935 Update to node-local-dns v1.22.2
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#5923 Remove etcd-pod resource limits for old clusters (already have limits)
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
Labels: kind/bug, size/S, area/control-plane, cla: yes, lgtm, approved

#5934 Add Grafana dashboards for `gardener-resource-manager`
  charts/seed-bootstrap/charts/monitoring/templates/config.yaml
  charts/seed-bootstrap/dashboards/resource-manager.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/resource-manager.json
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
Labels: kind/enhancement, area/monitoring, cla: yes, lgtm, approved, size/XXL

#5870 Prevent updates of existing nodes when CRI name in `ShootSpec` gets changed
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/operatingsystemconfig_test.go
Labels: kind/enhancement, size/L, area/os, cla: yes, lgtm, approved

#5926 Enable rotation trigger for shoot observability credentials
  docs/api-reference/core.md
  docs/usage/shoot_operations.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/secrets.go
  pkg/registry/core/shoot/strategy.go
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL

#5936 Update container images for `nginx-ingress-controller` and `kubernetes-dashboard`
  charts/images.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/deployment-dashboard.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/deployment-metrics-scraper.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-deployment.yaml
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
Labels: kind/enhancement, area/open-source, size/M, cla: yes, lgtm, approved

#5941 component:github.com/gardener/etcd-druid:Upgrade v0.8.3->v0.8.4
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/control-plane, cla: yes, lgtm, approved

#5942 Update alpine images to version 3.15.4
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#5947 Adjust the path to the shoot CA certificate in the blackbox exporter
  charts/seed-monitoring/charts/core/charts/prometheus/templates/blackbox-exporter-config.yaml
Labels: size/XS, kind/regression, cla: yes, lgtm, approved

#5950 Enable trusted endpoints in test framework
  test/framework/k8s_utils.go
Labels: kind/bug, size/XS, area/testing, cla: yes, lgtm, approved

#5955 Manage autoscaler versions per k8s version
  charts/images.yaml
Labels: size/S, cla: yes, lgtm, approved

#5924 [provider-local] Make `Ingress`es resolvable/reachable
  charts/gardener/provider-local/extension/templates/coredns/configmap.yaml
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/templates/rbac.yaml
  charts/gardener/provider-local/extension/values.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-extension-provider-local/app/options.go
  docs/extensions/provider-local.md
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/gardenlet/values.yaml
  example/gardener-local/kind/cluster-local.yaml
  example/gardener-local/kind/cluster-skaffold.yaml
  example/provider-local/base/controller-registration.yaml
  example/provider-local/overlays/local/seed.yaml
  hack/test-e2e-local.sh
  pkg/provider-local/controller/infrastructure/actuator.go
  pkg/provider-local/controller/ingress/add.go
  pkg/provider-local/controller/ingress/options.go
  pkg/provider-local/controller/ingress/reconciler.go
  pkg/provider-local/controller/service/add.go
  pkg/provider-local/controller/service/reconciler.go
  test/framework/gardener_utils.go
  test/framework/shootcreationframework.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#5938 Add E2E test for `AdminKubeconfigRequest` feature
  docs/deployment/getting_started_locally.md
  hack/test-e2e-local.sh
  test/e2e/shoot/create_and_delete.go
Labels: kind/enhancement, size/M, area/testing, cla: yes, lgtm, approved

#5944 [GEP-18] Use old CA for signing the `kube-apiserver`'s client certificate for `kubelet`
  docs/development/secrets_management.md
  pkg/operation/botanist/component/kubeapiserver/secrets.go
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#5274 Add seed care reconciler for health checks of seed system components
  charts/gardener/gardenlet/charts/runtime/templates/_helpers.tpl
  charts/gardener/gardenlet/values.yaml
  example/20-componentconfig-gardenlet.yaml
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_seed.go
  pkg/controllermanager/controller/managedseedset/managedseedset_replica.go
  pkg/controllermanager/controller/managedseedset/managedseedset_replica_test.go
  pkg/controllermanager/controller/shoot/shoot_conditions_control.go
  pkg/controllermanager/controller/shoot/shoot_conditions_control_test.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/gardenlet/controller/seed/seed.go
  pkg/gardenlet/controller/seed/seed_care_control.go
  pkg/gardenlet/controller/seed/seed_care_control_test.go
  pkg/gardenlet/controller/seed/seed_care_control_types.go
  pkg/operation/botanist/component/clusterautoscaler/bootstrap.go
  pkg/operation/botanist/component/clusteridentity/clusteridentity.go
  pkg/operation/botanist/component/dependencywatchdog/bootstrap.go
  pkg/operation/botanist/component/networkpolicies/bootstrap.go
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/vpa/vpa.go
  pkg/operation/care/seed_health.go
  pkg/operation/common/types.go
  pkg/operation/seed/seed.go
  pkg/registry/core/seed/storage/tableconvertor.go
  pkg/scheduler/controller/common/seed.go
  pkg/utils/kubernetes/health/seed.go
  pkg/utils/kubernetes/health/seed_test.go
Labels: kind/enhancement, needs/changes, kind/api-change, needs/review, needs/rebase, needs/ok-to-test, needs/second-opinion, area/monitoring, area/robustness, cla: yes, lgtm, approved, size/XXL

#5960 component:github.com/gardener/etcd-druid:Upgrade v0.8.4->v0.8.5
  charts/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#5967 Drop `hack/usage/retry-shoot-operation`
  hack/usage/retry-shoot-operation
Labels: area/dev-productivity, kind/cleanup, size/S, cla: yes, lgtm, approved

#5959 Change the Loki fsGroupChangePolicy from Always to OnRootMismatch
  charts/seed-bootstrap/charts/loki/templates/statefulset.yaml
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#5966 (Re-)bootstrap GRM when its token expired
  pkg/operation/botanist/resource_manager.go
  pkg/operation/botanist/resource_manager_test.go
Labels: kind/enhancement, area/robustness, size/S, cla: yes, lgtm, approved

#5940 Ensure same order of CAs for `adminkubeconfig` subresource and `ca-cluster` secret
  pkg/registry/core/shoot/storage/admin_kubeconfig.go
  pkg/registry/core/shoot/storage/admin_kubeconfig_test.go
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#5937 [provider-local] Make `dependency-watchdog-probe` usable
  charts/gardener/provider-local/extension/templates/coredns/networkpolicy.yaml
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/values.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-extension-provider-local/app/options.go
  docs/extensions/provider-local.md
  example/gardener-local/gardenlet/values.yaml
  example/provider-local/base/controller-registration.yaml
  example/provider-local/overlays/local/seed.yaml
  pkg/operation/botanist/component/dependencywatchdog/bootstrap.go
  pkg/operation/botanist/component/dependencywatchdog/bootstrap_test.go
  pkg/provider-local/controller/node/add.go
  pkg/provider-local/controller/node/options.go
  pkg/provider-local/controller/node/reconciler.go
  pkg/provider-local/webhook/dnsconfig/add.go
  pkg/provider-local/webhook/dnsconfig/mutator.go
  pkg/provider-local/webhook/machinepod/mutator.go
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#5945 [GEP-18] Prevent automatic shoot CA rotation caused by approaching expiration time or config change
  extensions/pkg/util/secret/manager/manager.go
  pkg/controllermanager/controller/factory.go
  pkg/operation/botanist/botanist.go
  pkg/operation/seed/seed.go
  pkg/utils/secrets/manager/cleanup_test.go
  pkg/utils/secrets/manager/generate_test.go
  pkg/utils/secrets/manager/manager.go
  pkg/utils/secrets/manager/manager_test.go
Labels: kind/enhancement, area/security, size/L, cla: yes, lgtm, approved

#5965 Reverse checks for invalidating clients
  pkg/client/kubernetes/clientmap/internal/generic_clientmap.go
  pkg/client/kubernetes/clientmap/internal/generic_clientmap_test.go
Labels: kind/enhancement, area/robustness, size/S, cla: yes, lgtm, approved

#5969 Make component-cli parameters configurable again
  hack/.ci/component_descriptor
Labels: size/M, kind/regression, cla: yes, lgtm, approved

#5970 Update `OWNERS`
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/XS, kind/cleanup, cla: yes, lgtm, approved

#5939 [GEP-18] Add documentation for the shoot cluster CA certificate rotation
  docs/README.md
  docs/usage/secrets_rotation.md
  docs/usage/shoot_access.md
  docs/usage/shoot_credentials_rotation.md
  docs/usage/shoot_operations.md
Labels: kind/enhancement, area/security, area/documentation, size/L, cla: yes, lgtm, approved

#5953 Deflake managedresource controller integration test
  pkg/resourcemanager/controller/managedresource/add.go
  pkg/resourcemanager/controller/managedresource/reconciler.go
  test/integration/resourcemanager/health/health_suite_test.go
  test/integration/resourcemanager/managedresource/reconciler_test.go
  test/integration/resourcemanager/managedresource/resource_suite_test.go
  test/integration/resourcemanager/managedresource/resource_test.go
Labels: area/dev-productivity, kind/cleanup, area/testing, kind/flake, cla: yes, lgtm, approved, size/XXL

#5975 Recreate DWD deployment if needed
  pkg/operation/botanist/component/dependencywatchdog/bootstrap.go
  pkg/operation/botanist/component/dependencywatchdog/bootstrap_test.go
Labels: size/XS, kind/regression, area/control-plane, cla: yes, lgtm, approved

#5982 Fixed broken links - 05.2022
  docs/development/secrets_management.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#5984 Upgrade Prometheus
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#5989 Fixed monitoring of node local dns.
  pkg/operation/botanist/component/nodelocaldns/monitoring.go
  pkg/operation/botanist/component/nodelocaldns/monitoring_test.go
Labels: kind/bug, area/monitoring, area/networking, size/S, cla: yes, lgtm, approved

#5980 Deprecate the `ServiceAccount` signing key secret field
  docs/api-reference/core.md
  docs/usage/shoot_serviceaccounts.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/openapi/openapi_generated.go
Labels: kind/enhancement, area/security, component/gardener, size/S, cla: yes, lgtm, approved

#5985 Deprecate `RotateSSHKeypairOnMaintenance` feature gate
  docs/deployment/feature_gates.md
  docs/usage/shoot_credentials_rotation.md
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/features/features.go
Labels: kind/enhancement, area/security, size/XS, cla: yes, lgtm, approved

#5988 add annotation to renew gardenlet kubeconfig secret to ManagedSeed
  docs/usage/managed_seed.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/managedseed/managedseed_actuator.go
  pkg/gardenlet/controller/managedseed/managedseed_actuator_test.go
  pkg/registry/seedmanagement/managedseed/strategy.go
Labels: kind/enhancement, area/usability, size/M, component/gardener, cla: yes, lgtm, approved

#5991 Improve WebhookConstraintMatchers for namespaces
  pkg/operation/botanist/matchers/matcher.go
  pkg/operation/care/constraints_test.go
Labels: kind/enhancement, area/ops-productivity, size/M, component/gardener, cla: yes, lgtm, approved

#5974 Validate shoot default dns even if shoot's seed spec is not specified
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dns/admission_test.go
  test/integration/controllermanager/shootmaintenance/maintenance_control_test.go
  test/integration/controllermanager/shootmaintenance/utils_test.go
  test/integration/controllermanager/shootretry/shootretry_control_test.go
Labels: kind/bug, area/security, area/ops-productivity, size/L, cla: yes, lgtm, approved

#6000 Add dashboard for node-local-dns operational errors.
  charts/seed-monitoring/charts/grafana/dashboards/dns/node-local-dns-dashboard.json
  pkg/operation/botanist/component/nodelocaldns/monitoring.go
  pkg/operation/botanist/component/nodelocaldns/monitoring_test.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns_test.go
Labels: kind/enhancement, size/L, area/monitoring, area/networking, cla: yes, lgtm, approved

#6003 [GEP-18] Use new secrets manager for extension CA and server secret generation, auto-rotate those every 30d
  cmd/gardener-extension-provider-local/app/app.go
  docs/development/secrets_management.md
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  extensions/pkg/webhook/certificates.go
  extensions/pkg/webhook/certificates/add.go
  extensions/pkg/webhook/certificates/certificates.go
  extensions/pkg/webhook/certificates/certificates_suite_test.go
  extensions/pkg/webhook/certificates/certificates_test.go
  extensions/pkg/webhook/certificates/reconciler.go
  extensions/pkg/webhook/certificates/reloader.go
  extensions/pkg/webhook/certificates_test.go
  extensions/pkg/webhook/cmd/options.go
  extensions/pkg/webhook/controlplane/controlplane.go
  extensions/pkg/webhook/registration.go
  extensions/pkg/webhook/registration_test.go
  extensions/pkg/webhook/webhook.go
  pkg/operation/seed/seed.go
  pkg/provider-local/controller/controlplane/add.go
  pkg/provider-local/webhook/dnsconfig/add.go
  pkg/provider-local/webhook/node/add.go
  pkg/utils/secrets/certificates.go
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
  test/integration/extensions/webhook/certificates/certificates_suite_test.go
  test/integration/extensions/webhook/certificates/certificates_test.go
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL

#6001 Fix pod security policy of node-local-dns by adding missing port.
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns_test.go
Labels: kind/bug, area/networking, size/S, cla: yes, lgtm, approved

#6002 managedseed_actuator: Clean up ineffective `updateCondition` call
  pkg/gardenlet/controller/managedseed/managedseed_actuator.go
  pkg/gardenlet/controller/managedseed/managedseed_actuator_test.go
Labels: kind/enhancement, size/XS, area/quality, cla: yes, lgtm, approved

#6006 Switch default backend to `k8s.gcr.io/defaultbackend-amd64:1.5`
  charts/images.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/default-backend-deployment.yaml
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
Labels: kind/enhancement, area/open-source, size/S, cla: yes, lgtm, approved

#6010 Allow projected volumes for node-local-dns
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns_test.go
Labels: kind/bug, size/XS, area/quality, cla: yes, lgtm, approved

#6011 Properly maintain `valid-until-time` label on `Secret`s managed by secrets manager
  extensions/pkg/util/secret/manager/manager_test.go
  pkg/utils/secrets/manager/fake/fake_manager.go
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
  pkg/utils/secrets/manager/manager.go
  pkg/utils/secrets/manager/manager_test.go
Labels: kind/bug, area/security, size/L, cla: yes, lgtm, approved

#6015 Update the doc for Registering Extension Controllers
  docs/extensions/controllerregistration.md
Labels: size/XS, area/documentation, kind/cleanup, cla: yes, lgtm, approved

#6007 Deprecate `ManagedIstio` and `APIServerSNI` feature gates and `ShootDNS` seed setting
  docs/api-reference/core.md
  docs/deployment/feature_gates.md
  docs/usage/istio.md
  example/50-seed.yaml
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/features/features.go
  pkg/openapi/openapi_generated.go
Labels: kind/enhancement, area/security, size/S, cla: yes, lgtm, approved

#6019 Ensure that shoot node network and seed service network do not overlap.
  pkg/utils/validation/cidr/disjoint.go
  pkg/utils/validation/cidr/disjoint_test.go
Labels: kind/bug, size/M, area/robustness, area/networking, cla: yes, lgtm, approved

#6004 Re-enable CRI migration for existing worker pools
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/operatingsystemconfig.go
Labels: kind/enhancement, size/L, area/os, cla: yes, lgtm, approved

#6022 Require `gnostic` in `v0.5.5`
  go.mod
  vendor/modules.txt
Labels: kind/enhancement, size/XS, area/open-source, cla: yes, lgtm, approved

#6031 Keep all the memory metrics in the seed prometheus
  charts/seed-bootstrap/values.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6024 fix fluentbit network policy
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-network-policy.yaml
  charts/seed-bootstrap/charts/fluent-bit/values.yaml
  docs/deployment/configuring_logging.md
  example/20-componentconfig-gardenlet.yaml
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/networkpolicy/helper/helper.go
  pkg/gardenlet/controller/networkpolicy/helper/helper_test.go
  pkg/operation/seed/seed.go
Labels: kind/bug, size/L, area/logging, ok-to-test, cla: yes, lgtm, approved

#6029 Fix `invalid memory address` error
  pkg/gardenlet/controller/shoot/shoot_control.go
Labels: kind/bug, size/XS, cla: yes, lgtm, approved

#6030 Drop usages of `k8s.io/apimachinery/pkg/util/clock`
  cmd/gardenlet/app/gardenlet.go
  extensions/pkg/controller/common/checkerwatchdog.go
  extensions/pkg/controller/common/checkerwatchdog_test.go
  extensions/pkg/controller/common/checkerwatchdogfactory.go
  extensions/pkg/controller/common/checkerwatchdogfactory_test.go
  extensions/pkg/controller/common/watchdogmanager.go
  extensions/pkg/controller/common/watchdogmanager_test.go
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  extensions/pkg/util/secret/manager/manager.go
  extensions/pkg/util/secret/manager/manager_test.go
  extensions/pkg/webhook/certificates/add.go
  extensions/pkg/webhook/certificates/reconciler.go
  extensions/pkg/webhook/cmd/options.go
  pkg/client/kubernetes/clientmap/internal/garden_clientmap.go
  pkg/client/kubernetes/clientmap/internal/generic_clientmap.go
  pkg/client/kubernetes/clientmap/internal/generic_clientmap_test.go
  pkg/client/kubernetes/clientmap/internal/plant_clientmap.go
  pkg/client/kubernetes/clientmap/internal/seed_clientmap.go
  pkg/client/kubernetes/clientmap/internal/shoot_clientmap.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/project/project.go
  pkg/controllermanager/controller/project/project_activity_control.go
  pkg/controllermanager/controller/project/project_activity_control_test.go
  pkg/controllermanager/controller/shoot/shoot.go
  pkg/controllermanager/controller/shoot/shoot_hibernation_control.go
  pkg/controllermanager/controller/shoot/shoot_hibernation_control_test.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/healthz/periodic.go
  pkg/healthz/periodic_test.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/seed/seed.go
  pkg/registry/core/shoot/storage/admin_kubeconfig_test.go
  pkg/resourcemanager/controller/garbagecollector/add.go
  pkg/resourcemanager/controller/garbagecollector/reconciler.go
  pkg/resourcemanager/controller/garbagecollector/reconciler_test.go
  pkg/resourcemanager/controller/tokenrequestor/add.go
  pkg/resourcemanager/controller/tokenrequestor/reconciler.go
  pkg/resourcemanager/controller/tokenrequestor/reconciler_test.go
  pkg/utils/flow/progress_reporter_delaying.go
  pkg/utils/flow/progress_reporter_delaying_test.go
  pkg/utils/secrets/alias.go
  pkg/utils/secrets/manager/cleanup_test.go
  pkg/utils/secrets/manager/generate_test.go
  pkg/utils/secrets/manager/manager.go
  pkg/utils/secrets/manager/manager_test.go
  pkg/utils/secrets/secrets_suite_test.go
  test/integration/controllermanager/shoothibernation/shoothibernation_suite_test.go
  test/integration/extensions/webhook/certificates/certificates_test.go
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/modules.txt
Labels: kind/enhancement, size/XL, area/open-source, cla: yes, lgtm, approved

#6035 Allow updates to the `extensions.BackupEntry.Spec.Region` field
  pkg/apis/extensions/validation/backupentry.go
  pkg/apis/extensions/validation/backupentry_test.go
Labels: kind/enhancement, size/S, area/control-plane-migration, cla: yes, lgtm, approved

#5995 Set `SeedSystemComponentsHealthy` and `Bootstrapped` seed conditions to `Progressing` on seed reconciliations.
  charts/gardener/gardenlet/values.yaml
  example/20-componentconfig-gardenlet.yaml
  pkg/gardenlet/controller/seed/seed_care_control.go
  pkg/gardenlet/controller/seed/seed_care_control_test.go
  pkg/gardenlet/controller/seed/seed_care_control_types.go
  pkg/gardenlet/controller/seed/seed_control.go
  pkg/operation/care/seed_health.go
  pkg/operation/care/seed_health_test.go
  pkg/utils/kubernetes/health/seed.go
Labels: kind/enhancement, area/ops-productivity, size/L, area/robustness, cla: yes, lgtm, approved

#6023 Support for Kubernetes v1.24
  README.md
  docs/extensions/controlplane-webhooks.md
  docs/usage/supported_k8s_versions.md
  example/gardener-local/kind/cluster-local.yaml
  example/gardener-local/kind/cluster-skaffold.yaml
  example/provider-local/base/cloudprofile.yaml
  example/provider-local/shoot.yaml
  hack/local-development/common/helpers
  hack/local-development/start-gardenlet
  hack/tools.mk
  pkg/client/kubernetes/client.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/resource_manager.go
  pkg/operation/seed/components.go
  pkg/operation/seed/seed.go
  pkg/registry/core/backupbucket/storage/tableconvertor.go
  pkg/registry/core/backupentry/storage/tableconvertor.go
  pkg/registry/core/cloudprofile/storage/tableconvertor.go
  pkg/registry/core/controllerdeployment/storage/tableconvertor.go
  pkg/registry/core/controllerinstallation/storage/tableconvertor.go
  pkg/registry/core/controllerregistration/storage/tableconvertor.go
  pkg/registry/core/exposureclass/storage/tableconvertor.go
  pkg/registry/core/plant/storage/tableconvertor.go
  pkg/registry/core/project/storage/tableconvertor.go
  pkg/registry/core/quota/storage/tableconvertor.go
  pkg/registry/core/secretbinding/storage/tableconvertor.go
  pkg/registry/core/seed/storage/tableconvertor.go
  pkg/registry/core/shoot/storage/tableconvertor.go
  pkg/registry/core/shootstate/storage/tableconvertor.go
  pkg/registry/operations/bastion/storage/tableconvertor.go
  pkg/registry/seedmanagement/managedseed/storage/tableconvertor.go
  pkg/registry/seedmanagement/managedseedset/storage/tableconvertor.go
  pkg/registry/settings/clusteropenidconnectpreset/storage/tableconvertor.go
  pkg/registry/settings/openidconnectpreset/storage/tableconvertor.go
  pkg/utils/kubernetes/unstructured/object.go
  pkg/utils/validation/features/featuregates.go
  pkg/utils/version/version.go
  test/e2e/shoot/common.go
Labels: kind/enhancement, size/XL, area/open-source, area/usability, cla: yes, lgtm, approved

#6043 Explicitly delete metrics-server on Shoot deletion
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
Labels: kind/enhancement, size/XS, area/control-plane, cla: yes, lgtm, approved

#6046 Use local garden kubeconfig explicitly in local setup targets
  Makefile
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#6047 Handle cluster-autoscaler Deployment in generic controlplane mutator
  extensions/pkg/webhook/controlplane/genericmutator/mock/mocks.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator_test.go
  extensions/pkg/webhook/controlplane/genericmutator/noopensurer.go
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#6037 Jitter for the shootretry controller
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  charts/gardener/controlplane/values.yaml
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/defaults_test.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
  pkg/controllermanager/controller/shoot/shoot_retry_control.go
Labels: kind/enhancement, size/M, area/control-plane, cla: yes, lgtm, approved

#6048 Promote `ShootMaxTokenExpiration{Validation,Overwrite}` feature gates to GA
  docs/deployment/feature_gates.md
  pkg/features/features.go
  pkg/registry/core/shoot/strategy_test.go
Labels: kind/enhancement, area/ops-productivity, area/open-source, size/M, cla: yes, lgtm, approved

#6040 Replace `utils.IsTrue` with `pointer.BoolDeref`
  cmd/gardener-admission-controller/app/gardener_admission_controller.go
  pkg/apis/seedmanagement/validation/managedseed.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/gardenlet/controller/managedseed/managedseed_actuator.go
  pkg/operation/botanist/component/etcd/waiter.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/namespaces.go
  pkg/operation/shoot/shoot.go
  pkg/utils/kubernetes/health/etcd.go
  pkg/utils/miscellaneous.go
  pkg/utils/miscellaneous_test.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/validator/admission.go
Labels: area/dev-productivity, size/M, kind/cleanup, cla: yes, lgtm, approved

#6050 Mount proper ca-bundle to vpn-seed on ca rotation
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/secrets.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#6028 Consider `ResourcesProgressing` condition of `ManagedResources` during seed health checks
  pkg/operation/care/checker.go
  pkg/operation/care/health_check_test.go
  pkg/operation/care/seed_health.go
  pkg/operation/care/seed_health_test.go
Labels: kind/enhancement, area/ops-productivity, size/L, area/robustness, cla: yes, lgtm, approved

#6021 Support ETCD encryption key secret rotation for shoot clusters
  docs/api-reference/core.md
  docs/usage/shoot_credentials_rotation.md
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler_test.go
  pkg/operation/botanist/component/dependencywatchdog/access_test.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/etcd/waiter_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/operation/botanist/component/gardeneraccess/access_test.go
  pkg/operation/botanist/component/gardenerkubescheduler/gardener_kube_scheduler_bootstrap_test.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/mock/mocks.go
  pkg/operation/botanist/component/kubeapiserver/secrets.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/component/metricsserver/metrics_server_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller_test.go
  pkg/operation/botanist/component/vpa/vpa_test.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server_test.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot_test.go
  pkg/operation/botanist/etcd_test.go
  pkg/operation/botanist/infrastructure_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operation/botanist/kubeproxy_test.go
  pkg/operation/botanist/monitoring_test.go
  pkg/operation/botanist/operatingsystemconfig_test.go
  pkg/operation/botanist/resource_manager_test.go
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/secrets_test.go
  pkg/operation/botanist/worker_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  pkg/utils/secrets/manager/fake/fake_manager.go
  pkg/utils/secrets/manager/fake/fake_manager_test.go
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL

#6020 Update/remove memory limits. Disable limit autoscaling.
  charts/istio/istio-istiod/templates/deployment.yaml
  charts/seed-bootstrap/charts/hvpa/templates/controller-deployment.yaml
  charts/seed-bootstrap/charts/loki/templates/hvpa.yaml
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/component/vpnauthzserver/external_authz_server.go
  pkg/operation/botanist/component/vpnauthzserver/external_authz_server_test.go
Labels: kind/enhancement, area/robustness, size/S, area/auto-scaling, cla: yes, lgtm, approved

#6049 Drop legacy client certificate for Prometheus
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/seed-monitoring/charts/core/values.yaml
  pkg/operation/botanist/monitoring.go
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#6051 Fix `blackbox-exporter` checks in local setup
  charts/gardener/provider-local/extension/templates/coredns/configmap.yaml
  charts/gardener/provider-local/extension/templates/coredns/deployment.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  docs/extensions/provider-local.md
  example/provider-local/base/controller-registration.yaml
  pkg/provider-local/webhook/dnsconfig/add.go
  pkg/provider-local/webhook/dnsconfig/mutator.go
Labels: kind/enhancement, area/dev-productivity, area/monitoring, size/S, cla: yes, lgtm, approved
