Repository gardener/gardener, pull requests merged in 2022-10, with the labels that each got.

#6738 Cleanup old priority class and related migration code
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/factory.go
  pkg/operation/botanist/component/seedsystem/seedsystem.go
  pkg/operation/botanist/component/seedsystem/seedsystem_test.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server_test.go
Labels: kind/cleanup, size/S, area/control-plane, cla: yes, lgtm, approved

#6764 Upgrade logging components to v0.44.0
  charts/images.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#6739 Update VPA to 0.12.0
  charts/images.yaml
  go.mod
  go.sum
  pkg/operation/botanist/component/vpa/admissioncontroller.go
  pkg/operation/botanist/component/vpa/vpa.go
  pkg/operation/seed/components.go
  pkg/operation/seed/seed.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#6767 Clean up no longer needed `ginkgo.Skip` statement from the cluster-autoscaler integration tests
  test/testmachinery/shoots/operations/clusterautoscaler.go
Labels: kind/enhancement, size/XS, area/testing, cla: yes, lgtm, approved

#6768 Prevent `gardenlet` from watching `Project`s
  cmd/gardener-controller-manager/app/app.go
  cmd/gardenlet/app/app.go
  pkg/api/indexer/add.go
  pkg/api/indexer/add_test.go
Labels: kind/bug, size/L, area/robustness, cla: yes, lgtm, approved

#6730 Remote local setup
  docs/deployment/content/remote-local-setup.yaml
  docs/deployment/getting_started_locally.md
  docs/development/content/remote-local-setup.yaml
  docs/development/getting_started_locally.md
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#6754 Fix injecting custom containerd config imports
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/initializer_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/templates/scripts/init.tpl.sh
Labels: kind/bug, size/S, area/os, cla: yes, lgtm, approved

#6626 Makes extensions health checks use a `Lease` resource
  charts/gardener/gardenlet/charts/runtime/templates/clusterrole-gardenlet.yaml
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/templates/rbac.yaml
  charts/gardener/provider-local/extension/values.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-extension-provider-local/app/options.go
  docs/README.md
  docs/extensions/heartbeat.md
  example/provider-local/garden/base/controller-registration.yaml
  extensions/pkg/controller/healthcheck/reconciler.go
  extensions/pkg/controller/heartbeat/cmd/options.go
  extensions/pkg/controller/heartbeat/controller.go
  extensions/pkg/controller/heartbeat/reconciler.go
  extensions/pkg/webhook/certificates/reconciler.go
  extensions/pkg/webhook/certificates/reloader.go
  hack/local-development/start-extension-provider-local
  pkg/controllerutils/source.go
  pkg/controllerutils/source_test.go
  pkg/extensions/constants.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_control.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/operation/care/checker.go
  pkg/operation/care/health.go
  pkg/operation/care/health_check_test.go
  pkg/utils/gardener/controllerinstallation.go
  pkg/utils/gardener/controllerinstallation_test.go
  test/integration/extensions/controller/heartbeat/heartbeat_suite_test.go
  test/integration/extensions/controller/heartbeat/heartbeat_test.go
Labels: kind/enhancement, size/XL, area/quality, ok-to-test, cla: yes, lgtm, approved

#6770 Enhance resource-manager health controller
  pkg/resourcemanager/controller/health/add.go
  pkg/resourcemanager/controller/health/add_test.go
  pkg/resourcemanager/controller/health/health_checker.go
  pkg/resourcemanager/controller/health/health_checker_test.go
  pkg/resourcemanager/controller/health/health_reconciler.go
  pkg/utils/kubernetes/health/service.go
  pkg/utils/kubernetes/health/service_test.go
Labels: kind/enhancement, size/XL, area/ops-productivity, area/scalability, ok-to-test, cla: yes, lgtm, approved

#6779 Update machines crd
  extensions/pkg/controller/worker/templates/alicloudmachineclasses.tpl.yaml
  extensions/pkg/controller/worker/templates/awsmachineclasses.tpl.yaml
  extensions/pkg/controller/worker/templates/azuremachineclasses.tpl.yaml
  extensions/pkg/controller/worker/templates/gcpmachineclasses.tpl.yaml
  extensions/pkg/controller/worker/templates/machineclasses.tpl.yaml
  extensions/pkg/controller/worker/templates/machinedeployments.tpl.yaml
  extensions/pkg/controller/worker/templates/machines.tpl.yaml
  extensions/pkg/controller/worker/templates/machinesets.tpl.yaml
  extensions/pkg/controller/worker/templates/openstackmachineclasses.tpl.yaml
  extensions/pkg/controller/worker/templates/packetmachineclasses.tpl.yaml
Labels: kind/enhancement, area/usability, size/M, ok-to-test, cla: yes, lgtm, approved

#6780 Support running "make generate" in the (dev) "remote-local-setup"
  docs/development/content/remote-local-setup.yaml
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#6729 Extend ConditionBuilder interface with a WithClock(...) function
  extensions/pkg/controller/healthcheck/reconciler.go
  pkg/apis/.import-restrictions
  pkg/apis/core/v1beta1/helper/condition_builder.go
  pkg/apis/core/v1beta1/helper/condition_builder_test.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/controllermanager/controller/seed/backupbucketscheck/reconciler.go
  pkg/controllermanager/controller/seed/extensionscheck/reconciler.go
  pkg/controllermanager/controller/seed/lifecycle/reconciler.go
  pkg/controllermanager/controller/seed/utils/utils.go
  pkg/controllermanager/controller/seed/utils/utils_test.go
  pkg/gardenlet/controller/seed/lease_control.go
  pkg/gardenlet/controller/seed/lease_control_test.go
  pkg/gardenlet/controller/seed/seed.go
  pkg/operation/care/constraints.go
  pkg/operation/care/health_check_test.go
  test/integration/controllermanager/seed/backupbucketscheck/backupbucketscheck_suite_test.go
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_suite_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, ok-to-test, cla: yes, lgtm, approved

#6776 Fix flaky `ManagedSeed` e2e test
  test/e2e/managedseed/create_rotate_delete.go
Labels: area/dev-productivity, size/M, kind/flake, cla: yes, lgtm, approved

#6778 Fix nodes CIDR in local `Seed` specification
  cmd/gardener-extension-provider-local/app/options.go
  example/gardener-local/gardenlet/values.yaml
  example/provider-local/seed-kind/local/seed.yaml
  pkg/provider-local/webhook/networkpolicy/add.go
  pkg/provider-local/webhook/networkpolicy/mutator.go
Labels: kind/bug, area/dev-productivity, size/L, cla: yes, lgtm, approved

#6733 [gardenlet] Switch `ControllerInstallation` controller to `controller-runtime`
  cmd/gardenlet/app/app.go
  docs/concepts/gardenlet.md
  extensions/pkg/webhook/shoot/webhook.go
  pkg/controllermanager/controller/seed/extensionscheck/add.go
  pkg/controllermanager/controller/seed/extensionscheck/add_test.go
  pkg/controllerutils/predicate/predicate.go
  pkg/controllerutils/predicate/predicate_test.go
  pkg/controllerutils/seedfilter.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/controllerinstallation/add.go
  pkg/gardenlet/controller/controllerinstallation/care/add.go
  pkg/gardenlet/controller/controllerinstallation/care/add_test.go
  pkg/gardenlet/controller/controllerinstallation/care/care_suite_test.go
  pkg/gardenlet/controller/controllerinstallation/care/reconciler.go
  pkg/gardenlet/controller/controllerinstallation/care/reconciler_test.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/add.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/add_test.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/gardenlet/controller/controllerinstallation/utils/constants.go
  pkg/gardenlet/controller/factory.go
  pkg/registry/core/controllerinstallation/storage/storage.go
  pkg/registry/core/controllerinstallation/strategy.go
  pkg/registry/core/controllerinstallation/strategy_test.go
  pkg/utils/managedresources/managedresources.go
  test/integration/gardenlet/controllerinstallation/care/care_suite_test.go
  test/integration/gardenlet/controllerinstallation/care/care_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/testdata/chart/Chart.yaml
  test/integration/gardenlet/controllerinstallation/controllerinstallation/testdata/chart/templates/config.yaml
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#6741 Added kubelet config parameter 'seccompDefault'
  docs/api-reference/core.md
  docs/usage/default_seccomp_profile.md
  example/90-shoot.yaml
  example/provider-local/shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
Labels: kind/enhancement, area/security, ok-to-test, cla: yes, lgtm, approved, size/XXL

#6765 Add networkpolicies for istio-ingress
  pkg/operation/botanist/component/istio/ingress_gateway.go
  pkg/operation/botanist/component/istio/istiod.go
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/vpnauthzserver/external_authz_server.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/seed/components.go
Labels: kind/enhancement, size/XL, area/networking, cla: yes, lgtm, approved

#6783 Deflake `Pod Scheduler Name Webhook Handler` test
  test/integration/seedadmissioncontroller/podschedulername/podschedulername_suite_test.go
  test/integration/seedadmissioncontroller/podschedulername/podschedulername_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#6727 Cleanup `ShootBinding` admission plugin
  docs/concepts/apiserver_admission_plugins.md
  pkg/apiserver/plugins.go
  plugin/pkg/shoot/binding/admission.go
  plugin/pkg/shoot/binding/admission_test.go
  plugin/pkg/shoot/binding/binding_suite_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  plugin/pkg/shoot/validator/validator_suite_test.go
  test/integration/controllermanager/bastion/bastion_suite_test.go
  test/integration/controllermanager/cloudprofile/cloudprofile_suite_test.go
  test/integration/controllermanager/controllerregistration/controllerregistration_suite_test.go
  test/integration/controllermanager/exposureclass/exposureclass_suite_test.go
  test/integration/controllermanager/quota/quota_suite_test.go
  test/integration/controllermanager/secretbinding/secretbinding_suite_test.go
Labels: area/quality, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#6771 Replace vpa-exporter with kube-state-metrics
  charts/images.yaml
  charts/seed-bootstrap/dashboards/vpa-dashboard.json
  charts/seed-bootstrap/prometheus-rules/recording-rules.rules.yaml
  charts/seed-bootstrap/templates/aggregate-prometheus/config.yaml
  charts/seed-bootstrap/values.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/allow-prometheus-network-policy.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/grafana/dashboards/operators/vpa-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/shoot-vpa-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/vpa-dashboard.json
  docs/development/priority-classes.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/component/etcd/monitoring.go
  pkg/operation/botanist/component/etcd/monitoring_test.go
  pkg/operation/botanist/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/operation/botanist/component/kubestatemetrics/monitoring.go
  pkg/operation/botanist/component/kubestatemetrics/monitoring_test.go
  pkg/operation/botanist/component/kubestatemetrics/resources.go
  pkg/operation/botanist/component/kubestatemetrics/testdata/monitoring_alertingrules.yaml
  pkg/operation/botanist/component/vpa/exporter.go
  pkg/operation/botanist/component/vpa/logging.go
  pkg/operation/botanist/component/vpa/logging_test.go
  pkg/operation/botanist/component/vpa/mock/mocks.go
  pkg/operation/botanist/component/vpa/monitoring.go
  pkg/operation/botanist/component/vpa/monitoring_test.go
  pkg/operation/botanist/component/vpa/vpa.go
  pkg/operation/botanist/component/vpa/vpa_test.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/monitoring_test.go
  pkg/operation/botanist/vpa.go
  pkg/operation/botanist/vpa_test.go
  pkg/operation/seed/components.go
  pkg/operation/seed/seed.go
  pkg/utils/images/images.go
Labels: kind/enhancement, area/monitoring, cla: yes, lgtm, approved, size/XXL

#6785 Wait for webhook server to start in `Extension CRDs Webhook` test
  test/integration/seedadmissioncontroller/extensioncrds/extensioncrds_suite_test.go
Labels: size/XS, area/testing, kind/flake, cla: yes, lgtm, approved

#6782 Added checks for non-gardener managed seed clusters to ensure correct seed configurations.
  cmd/gardenlet/app/bootstrappers/seed_config.go
  cmd/gardenlet/app/bootstrappers/seed_config_test.go
Labels: area/quality, size/L, kind/technical-debt, area/networking, cla: yes, lgtm, approved

#6725 Keep track of the last maintenance operation in the shoot status
  docs/api-reference/core.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/controllermanager/controller/shoot/add.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
Labels: kind/enhancement, area/ops-productivity, cla: yes, lgtm, approved, size/XXL

#6781 Speed up local image builds by defining Skaffold dependencies
  Makefile
  cmd/utils/config.go
  cmd/utils/miscellaneous.go
  hack/check-skaffold-deps.sh
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#6750 [GEP-20] Add HA option to `gardenlet`
  charts/gardener/gardenlet/charts/runtime/templates/_helpers.tpl
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  charts/gardener/gardenlet/values.yaml
  docs/api-reference/seedmanagement.md
  docs/deployment/deploy_gardenlet_manually.md
  docs/usage/managed_seed.md
  example/55-managedseed-gardenlet.yaml
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/utils.go
  pkg/apis/core/validation/utils_test.go
  pkg/apis/seedmanagement/types_managedseed.go
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseed.go
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseed_test.go
  pkg/apis/seedmanagement/v1alpha1/generated.pb.go
  pkg/apis/seedmanagement/v1alpha1/generated.proto
  pkg/apis/seedmanagement/v1alpha1/types_managedseed.go
  pkg/apis/seedmanagement/v1alpha1/zz_generated.conversion.go
  pkg/apis/seedmanagement/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/seedmanagement/validation/managedseed.go
  pkg/apis/seedmanagement/validation/managedseed_test.go
  pkg/apis/seedmanagement/zz_generated.deepcopy.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/gardenlet/controller/managedseed/managedseed_valueshelper.go
  pkg/gardenlet/controller/managedseed/managedseed_valueshelper_test.go
  pkg/openapi/openapi_generated.go
Labels: kind/enhancement, size/XL, area/high-availability, cla: yes, lgtm, approved

#6789 Update to go 1.19.2
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#6793 Remove preStop hook from gardener-apiserver
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/values.yaml
Labels: kind/bug, size/XS, area/quality, cla: yes, lgtm, approved

#6794 Remove step to install openvpn in local setup guide
  docs/development/local_setup.md
Labels: area/documentation, kind/cleanup, size/S, cla: yes, lgtm, approved

#6799 Revert "Drop Priority class gardener-shoot-controlplane"
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/component/seedsystem/seedsystem.go
  pkg/operation/botanist/component/seedsystem/seedsystem_test.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#6790 Update grafana image version
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6784 `kubelet` requests server certificate via `CertificateSigningRequest` API
  cmd/gardener-resource-manager/app/app.go
  docs/concepts/resource-manager.md
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/resource_manager.go
  pkg/resourcemanager/cmd/source.go
  pkg/resourcemanager/controller/csrapprover/add.go
  pkg/resourcemanager/controller/csrapprover/reconciler.go
  skaffold.yaml
  test/integration/resourcemanager/csrapprover/csrapprover_suite_test.go
  test/integration/resourcemanager/csrapprover/csrapprover_test.go
  test/integration/resourcemanager/csrapprover/testdata/crd-machines.yaml
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL

#6792 Clarify the role that is used to manage permissions of service accounts
  docs/usage/projects.md
Labels: size/XS, area/documentation, kind/cleanup, cla: yes, lgtm, approved

#6806 Increase timeout for wake-up step in "Create, Hibernate, Wake up and Delete Shoot" e2e test suite
  test/e2e/shoot/create_hibernate_wakeup_delete.go
Labels: area/dev-productivity, size/XS, kind/test, cla: yes, lgtm, approved

#6808 Do not put `gardenlet` under time pressure during start-up
  cmd/gardenlet/app/app.go
  pkg/healthz/default.go
  pkg/healthz/default_test.go
  pkg/healthz/periodic.go
  pkg/healthz/periodic_test.go
Labels: kind/enhancement, area/robustness, size/S, cla: yes, lgtm, approved

#6814 Fix flaky `ControllerInstallation` controller integration test suite
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go
Labels: area/dev-productivity, size/S, kind/flake, cla: yes, lgtm, approved

#6817 Configurable log level/format for gardener apiserver
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/values.yaml
  cmd/gardener-apiserver/app/gardener_apiserver.go
  pkg/apiserver/apiserver.go
Labels: kind/enhancement, size/S, area/control-plane, cla: yes, lgtm, approved

#6816 Fixed `gardener-e2e-kind-ha-single-zone` failing tests.
  Makefile
  hack/test-e2e-local.sh
  pkg/provider-local/webhook/controlplane/ensurer.go
Labels: size/M, kind/test, area/testing, cla: yes, lgtm, approved

#6820 Upgrade kube-rbac-proxy version
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#6824 Upgrade prometheus to v2.39.1
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6787 Add short names for machine resources
  extensions/pkg/controller/worker/templates/machineclasses.tpl.yaml
  extensions/pkg/controller/worker/templates/machinedeployments.tpl.yaml
  extensions/pkg/controller/worker/templates/machines.tpl.yaml
  extensions/pkg/controller/worker/templates/machinesets.tpl.yaml
Labels: kind/enhancement, size/XS, area/usability, cla: yes, lgtm, approved

#6813 Deflake GRM's kubelet CSR approver integration test suite
  test/integration/resourcemanager/csrapprover/csrapprover_suite_test.go
  test/integration/resourcemanager/csrapprover/csrapprover_test.go
Labels: area/dev-productivity, size/L, kind/flake, cla: yes, lgtm, approved

#6825 Add `kubernetes.io/arch` label in worker
  pkg/operation/botanist/component/extensions/worker/worker.go
  pkg/operation/botanist/component/extensions/worker/worker_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, size/L, area/control-plane, cla: yes, lgtm, approved

#6828 Update apiserver-proxy-pod-webhook image version
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/control-plane, cla: yes, lgtm, approved

#6830 Configurable log level/format for gardener-resource-manager
  charts/gardener/gardener-resource-manager/templates/deployment.yaml
  charts/gardener/gardener-resource-manager/values.yaml
  cmd/gardener-resource-manager/app/app.go
  cmd/gardener-resource-manager/app/options.go
  pkg/apiserver/apiserver.go
  pkg/operation/botanist/component/resourcemanager/monitoring_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/resource_manager.go
  pkg/operation/seed/components.go
  pkg/operation/seed/seed.go
Labels: kind/enhancement, size/L, area/control-plane, cla: yes, lgtm, approved

#6831 Configurable log level/format for gardener-seed-admission-controller
  cmd/gardener-seed-admission-controller/app/app.go
  cmd/gardener-seed-admission-controller/app/options.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller_test.go
  pkg/operation/seed/components.go
  pkg/operation/seed/seed.go
Labels: kind/enhancement, size/M, area/control-plane, cla: yes, lgtm, approved

#6829 Add `gardener.cloud/purpose: kube-system` label to all seeds
  pkg/operation/seed/seed.go
Labels: size/XS, kind/task, area/control-plane, cla: yes, lgtm, approved

#6835 Fix imageVectorOverwrite for HA e2e tests
  skaffold.yaml
Labels: kind/bug, area/dev-productivity, size/S, cla: yes, lgtm, approved

#6838 Set priority class for `kube-scheduler` and `cluster-autoscaler`
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler_test.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
Labels: kind/bug, size/S, area/control-plane, cla: yes, lgtm, approved

#6841 Fix `ControllerInstallation` integration test flakiness
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: area/dev-productivity, size/S, kind/flake, cla: yes, lgtm, approved

#6840 Remove `DNSProvider` from supported extension kinds
  pkg/apis/core/validation/controllerregistration.go
Labels: size/XS, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#6842 Fix flaky `ShootValidator` integration test
  test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_suite_test.go
  test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_test.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#6844 Exclude the attach subresource when considering high latency of the API Server
  charts/seed-monitoring/charts/grafana/dashboards/owners/apiserver-overview.json
  pkg/operation/botanist/component/kubeapiserver/monitoring.go
  pkg/operation/botanist/component/kubeapiserver/monitoring_test.go
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6834 Wait no running pods for kube-apiserver are present before scaling down etcd on hibernation
  pkg/operation/botanist/controlplane.go
Labels: kind/enhancement, size/M, area/robustness, cla: yes, lgtm, approved

#6843 Use jq `--compact-output` option in the binding update command
  docs/usage/control_plane_migration.md
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, size/M, area/control-plane-migration, cla: yes, lgtm, approved

#6700 Remove `PodSecurityPolicy` from requiredPlugins and add a user-facing warning to consider migration
  docs/api-reference/core.md
  docs/usage/pod-security.md
  example/seed-crds/10-crd-extensions.gardener.cloud_backupbuckets.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_backupentries.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_bastions.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_containerruntimes.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_controlplanes.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_dnsrecords.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_extensions.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_infrastructures.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_networks.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_workers.yaml
  pkg/api/core/shoot/warnings.go
  pkg/api/core/shoot/warnings_test.go
  pkg/apis/core/types_common.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_common.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/validation/utils.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_backupbuckets.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_backupentries.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_bastions.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_containerruntimes.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_controlplanes.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_dnsrecords.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_extensions.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_infrastructures.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_networks.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-extensions.gardener.cloud_workers.yaml
  pkg/operation/botanist/coredns.go
  pkg/operation/botanist/metricsserver.go
  pkg/operation/botanist/nodelocaldns.go
  pkg/operation/botanist/nodeproblemdetector.go
  pkg/operation/botanist/resource_manager.go
  pkg/operation/botanist/vpnshoot.go
  pkg/utils/validation/admissionplugins/admissionplugins.go
  test/e2e/shoot/create_update_delete.go
Labels: kind/enhancement, area/usability, size/L, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#6742 [controller-manager] Switch `ManagedSeedSet` controller to `controller-runtime`
  cmd/gardener-controller-manager/app/app.go
  docs/concepts/controller-manager.md
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/managedseedset/actuator.go
  pkg/controllermanager/controller/managedseedset/actuator_test.go
  pkg/controllermanager/controller/managedseedset/add.go
  pkg/controllermanager/controller/managedseedset/add_test.go
  pkg/controllermanager/controller/managedseedset/managedseedset.go
  pkg/controllermanager/controller/managedseedset/managedseedset_controller.go
  pkg/controllermanager/controller/managedseedset/managedseedset_controller_test.go
  pkg/controllermanager/controller/managedseedset/managedseedset_predicates.go
  pkg/controllermanager/controller/managedseedset/reconciler.go
  pkg/controllermanager/controller/managedseedset/reconciler_test.go
  pkg/controllermanager/controller/managedseedset/replica.go
  pkg/controllermanager/controller/managedseedset/replica_test.go
  pkg/controllermanager/controller/managedseedset/replicagetter.go
  pkg/controllermanager/controller/managedseedset/replicagetter_test.go
  test/integration/controllermanager/managedseedset/managedseedset_suite_test.go
  test/integration/controllermanager/managedseedset/managedseedset_test.go
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#6826 Add `Networkpolicy`s for `istio-system`
  pkg/gardenlet/controller/networkpolicy/endpoints.go
  pkg/gardenlet/controller/networkpolicy/namespace_control.go
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/deployment.yaml
  pkg/operation/botanist/component/istio/ingress_gateway.go
  pkg/operation/botanist/component/istio/istiod.go
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/istio/networkpolicies.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot.go
  pkg/operation/seed/components.go
Labels: kind/enhancement, area/networking, cla: yes, lgtm, approved, size/XXL

#6850 Remove scale subresource from etcd CRD
  pkg/operation/botanist/component/etcd/crds/templates/crd-druid.gardener.cloud_etcds.yaml
Labels: kind/bug, size/XS, area/auto-scaling, cla: yes, lgtm, approved

#6856 Document restrictions with regards to custom dns configuration and node local dns.
  docs/usage/custom-dns-config.md
  docs/usage/node-local-dns.md
Labels: kind/enhancement, area/documentation, area/networking, size/S, cla: yes, lgtm, approved

#6857 Allow all traffic to `istiod` webhook server port
  pkg/operation/botanist/component/istio/istiod.go
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/istio/networkpolicies.go
Labels: kind/bug, area/security, size/M, area/networking, cla: yes, lgtm, approved

#6861 Specify `NetworkPolicy` in kind sorter
  pkg/chartrenderer/sorter.go
Labels: kind/enhancement, size/XS, area/robustness, cla: yes, lgtm, approved

#6862 Revert "Keep track of the last maintenance operation in the shoot status (#6725)"
  docs/api-reference/core.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/controllermanager/controller/shoot/add.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
Labels: kind/bug, area/control-plane, cla: yes, lgtm, approved, size/XXL

#6866 gardenlet: Stop deleting Ingress resources for Seed via the extensions/v1beta1 API
  pkg/operation/botanist/logging.go
  pkg/operation/botanist/logging_test.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/common/utils.go
  test/testmachinery/shoots/logging/loki_tenant.go
  test/testmachinery/shoots/logging/seed_logging_stack.go
Labels: size/M, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#6702 support containerLogMax[Size|Files] kubelet configurations
  docs/api-reference/core.md
  docs/usage/logging.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/logrotate/logrotate.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/logrotate/logrotate_suite_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/logrotate/logrotate_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/docker/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/docker/logrotate/logrotate.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/docker/logrotate/logrotate_suite_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/docker/logrotate/logrotate_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/configcodec_test.go
  skaffold.yaml
Labels: kind/enhancement, cla: yes, lgtm, approved, size/XXL

#6732 [GEP-20] Update the existing recovery mechanisms in the proposal
  docs/proposals/20-ha-control-planes.md
Labels: kind/enhancement, size/S, area/high-availability, cla: yes, lgtm, approved

#6875 Configurable log level/format for gardener-extensions-controller package
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/values.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  example/provider-local/garden/base/controller-registration.yaml
  extensions/pkg/controller/cmd/options.go
  extensions/pkg/controller/cmd/options_test.go
Labels: kind/enhancement, size/L, area/logging, cla: yes, lgtm, approved

#6871 Fix monitoring alert for failed audit logs
  charts/seed-monitoring/charts/grafana/dashboards/operators/cluster-overview-dashboard.json
  pkg/operation/botanist/component/kubeapiserver/monitoring.go
  pkg/operation/botanist/component/kubeapiserver/monitoring_test.go
Labels: kind/bug, area/monitoring, size/S, area/audit-logging, cla: yes, lgtm, approved

#6874 [GEP-20] Adjust Control Plane Status Dashboard
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-control-plane-status-dashboard.json
Labels: kind/enhancement, area/monitoring, size/S, area/high-availability, cla: yes, lgtm, approved

#6884 Adapt static telegraf in the Loki pod
  charts/images.yaml
  charts/seed-bootstrap/charts/loki/templates/_helpers.tpl
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#6889 Improves error message when validating `workers[].maximum` field
  pkg/apis/core/validation/shoot.go
Labels: kind/enhancement, size/XS, area/quality, cla: yes, lgtm, approved

#6853 Wait for all shoot `ManagedResource`s to be deleted before deleting `kube-apiserver`
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_migrate.go
  pkg/operation/botanist/managedresources.go
  pkg/operation/botanist/managedresources_test.go
Labels: kind/enhancement, area/quality, size/L, area/robustness, cla: yes, lgtm, approved

#6899 Drop the `gardener-shoot-controlplane` PriorityClass
  docs/development/priority-classes.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/component/seedsystem/seedsystem.go
  pkg/operation/botanist/component/seedsystem/seedsystem_test.go
Labels: kind/cleanup, size/S, area/control-plane, cla: yes, lgtm, approved

#6901 [gardener-local] Run 2 replicas of admission-controller
  example/gardener-local/controlplane/values.yaml
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#6902 [provider-local] Use default Deployment strategy
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/values.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  example/provider-local/garden/base/controller-registration.yaml
Labels: kind/bug, area/dev-productivity, size/S, cla: yes, lgtm, approved

#6909 Prevent nil pointer in the guestbook test
  test/framework/applications/guestbooktest.go
Labels: kind/bug, size/XS, area/testing, cla: yes, lgtm, approved

#6908 Record failed maintenance operation in shoot event
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
Labels: kind/enhancement, area/ops-productivity, size/XS, cla: yes, lgtm, approved

#6894 Rename `validate-namespace-deletion` VWC to `gardener-admission-controller`
  Makefile
  charts/gardener/controlplane/charts/application/templates/validatingwebhook-admission-controller.yaml
Labels: size/XS, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#6918 Do not explicitly default containerLogMaxSize in shoot spec
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
Labels: kind/bug, size/L, area/logging, cla: yes, lgtm, approved

#6916 Update golangci to v1.50.1
  .golangci.yaml
  hack/tools.mk
  hack/tools/gomegacheck/go.mod
  hack/tools/gomegacheck/go.sum
  hack/tools/logcheck/go.mod
  hack/tools/logcheck/go.sum
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#6876 Cleanup unneeded complexity in `gardenlet` Helm chart
  charts/gardener/gardenlet/charts/runtime/Chart.yaml
  charts/gardener/gardenlet/charts/runtime/charts/utils-templates
  charts/gardener/gardenlet/charts/runtime/templates/_feature-gates.tpl
  charts/gardener/gardenlet/charts/runtime/templates/_helpers.tpl
  charts/gardener/gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml
  charts/gardener/gardenlet/charts/runtime/values.yaml
  charts/gardener/gardenlet/templates/_feature-gates.tpl
  charts/gardener/gardenlet/templates/_helpers.tpl
  charts/gardener/gardenlet/templates/clusterrole-apiserver-sni.yaml
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  charts/gardener/gardenlet/templates/clusterrole-managed-istio.yaml
  charts/gardener/gardenlet/templates/clusterrolebinding-apiserver-sni.yaml
  charts/gardener/gardenlet/templates/clusterrolebinding-gardenlet.yaml
  charts/gardener/gardenlet/templates/clusterrolebinding-managed-istio.yaml
  charts/gardener/gardenlet/templates/configmap-componentconfig.yaml
  charts/gardener/gardenlet/templates/configmap-imagevector-overwrite-components.yaml
  charts/gardener/gardenlet/templates/configmap-imagevector-overwrite.yaml
  charts/gardener/gardenlet/templates/deployment.yaml
  charts/gardener/gardenlet/templates/poddisruptionbudget.yaml
  charts/gardener/gardenlet/templates/priorityclass.yaml
  charts/gardener/gardenlet/templates/role-garden-gardenlet.yaml
  charts/gardener/gardenlet/templates/rolebinding-garden-gardenlet.yaml
  charts/gardener/gardenlet/templates/secret-kubeconfig-garden-bootstrap.yaml
  charts/gardener/gardenlet/templates/secret-kubeconfig-garden.yaml
  charts/gardener/gardenlet/templates/secret-kubeconfig-seed.yaml
  charts/gardener/gardenlet/templates/service.yaml
  charts/gardener/gardenlet/templates/serviceaccount.yaml
  charts/gardener/gardenlet/templates/vpa.yaml
  charts/gardener/gardenlet/values.yaml
  docs/deployment/deploy_gardenlet_manually.md
  example/gardener-local/gardenlet/values-kind-ha.yaml
  example/gardener-local/gardenlet/values-kind2.yaml
  example/gardener-local/gardenlet/values.yaml
  hack/local-development/start-gardenlet
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/gardenlet/controller/managedseed/managedseed_valueshelper.go
  pkg/gardenlet/controller/managedseed/managedseed_valueshelper_test.go
  skaffold.yaml
Labels: area/dev-productivity, kind/technical-debt, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#6920 Add PATCH as allowed VERB for Gardenlet leases in the Garden cluster
  pkg/admissioncontroller/webhook/auth/seed/authorizer.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer_test.go
Labels: kind/bug, size/XS, cla: yes, lgtm, approved

#6915 Move `HAControlPlanes` feature gate from gardenlet to gardener-apiserver
  docs/deployment/feature_gates.md
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/gardenlet/values.yaml
  hack/local-development/start-apiserver
  pkg/apiserver/features/features.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile_test.go
  pkg/gardenlet/features/features.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/botanist_test.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operation/botanist/namespaces.go
  pkg/operation/botanist/namespaces_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  skaffold.yaml
  test/integration/scheduler/shoot/scheduler_suite_test.go
Labels: kind/bug, size/L, area/high-availability, cla: yes, lgtm, approved

#6736 Add new Prometheus alert `ApiserverRequestsFailureRate` for API Server failure rate
  pkg/operation/botanist/component/kubeapiserver/monitoring.go
  pkg/operation/botanist/component/kubeapiserver/monitoring_test.go
  pkg/operation/botanist/component/kubeapiserver/testdata/monitoring_alertingrules.yaml
Labels: kind/enhancement, size/M, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#6914 Introduce `.spec.provider.zones` in `Seed`, deprecate `.spec.highAvailability` and drop `seed.gardener.cloud/multi-zonal` label
  Makefile
  docs/api-reference/core.md
  docs/concepts/scheduler.md
  example/50-seed.yaml
  example/gardener-local/gardenlet/values-kind-ha.yaml
  example/provider-local/seed-kind-ha/local-multi-zone/kustomization.yaml
  example/provider-local/seed-kind-ha/local-multi-zone/patch-seed.yaml
  example/provider-local/seed-kind-ha/local-single-zone/kustomization.yaml
  example/provider-local/seed-kind-ha/local-single-zone/patch-seed.yaml
  example/provider-local/seed-kind-ha/local/seed.yaml
  hack/ci-e2e-kind-ha.sh
  hack/ci-e2e-kind-migration.sh
  hack/ci-e2e-kind.sh
  hack/test-e2e-local.sh
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/seedmanagement/helper/helper.go
  pkg/apis/seedmanagement/helper/helper_test.go
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseed.go
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseed_test.go
  pkg/gardenlet/controller/managedseed/managedseed_valueshelper.go
  pkg/gardenlet/controller/managedseed/managedseed_valueshelper_test.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/namespaces.go
  pkg/operation/botanist/namespaces_test.go
  pkg/provider-local/webhook/controlplane/add.go
  pkg/provider-local/webhook/controlplane/ensurer.go
  pkg/scheduler/controller/shoot/reconciler.go
  pkg/scheduler/controller/shoot/reconciler_test.go
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
  plugin/pkg/seed/validator/admission.go
  plugin/pkg/seed/validator/admission_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  plugin/pkg/utils/miscellaneous.go
  plugin/pkg/utils/miscellaneous_test.go
  skaffold.yaml
  test/e2e/common.go
  test/framework/shootcreationframework.go
  test/integration/scheduler/shoot/scheduler_test.go
Labels: kind/enhancement, area/robustness, kind/technical-debt, kind/cleanup, area/high-availability, cla: yes, lgtm, approved, size/XXL

#6922 Disable kube-controller-manager profiling for shoots with k8s version >= 1.19
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go
Labels: kind/enhancement, area/security, size/XS, area/compliance, cla: yes, lgtm, approved

#6925 use dedicated lock for container logrotate service
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/logrotate/logrotate.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/logrotate/logrotate_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/docker/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/docker/logrotate/logrotate.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/docker/logrotate/logrotate_test.go
Labels: kind/bug, area/logging, size/S, area/os, cla: yes, lgtm, approved

#6900 Update `kindest/node` image to v1.24.7
  example/gardener-local/kind-ha/cluster-local.yaml
  example/gardener-local/kind-ha/cluster-skaffold.yaml
  example/gardener-local/kind/cluster-local.yaml
  example/gardener-local/kind/cluster-skaffold.yaml
  example/gardener-local/kind2/cluster-local.yaml
  example/gardener-local/kind2/cluster-skaffold.yaml
Labels: kind/cleanup, size/S, area/testing, cla: yes, lgtm, approved

#6919 Enable setting `protectKernelDefaults` for kubelet
  docs/api-reference/core.md
  example/90-shoot.yaml
  example/provider-local/shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
  pkg/utils/version/version.go
Labels: kind/enhancement, area/security, area/compliance, cla: yes, lgtm, approved, size/XXL

#6934 [GEP-20] Remove zone pinning
  charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
  charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml
  charts/gardener/resource-manager/values.yaml
  docs/concepts/resource-manager.md
  example/resource-manager/10-componentconfig.yaml
  example/resource-manager/10-mutatingwebhookconfiguration.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/namespaces.go
  pkg/operation/botanist/namespaces_test.go
  pkg/resourcemanager/apis/config/types.go
  pkg/resourcemanager/apis/config/v1alpha1/types.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/resourcemanager/apis/config/zz_generated.deepcopy.go
  pkg/resourcemanager/webhook/add.go
  pkg/resourcemanager/webhook/podzoneaffinity/add.go
  pkg/resourcemanager/webhook/podzoneaffinity/handler.go
  pkg/resourcemanager/webhook/podzoneaffinity/handler_test.go
  pkg/resourcemanager/webhook/podzoneaffinity/podzoneaffinity_suite_test.go
  skaffold.yaml
  test/integration/resourcemanager/podzoneaffinity/podzoneaffinity_suite_test.go
  test/integration/resourcemanager/podzoneaffinity/podzoneaffinity_test.go
Labels: kind/bug, area/high-availability, area/control-plane, cla: yes, lgtm, approved, size/XXL

#6938 [release-v1.58][GEP-20] Remove zone pinning
  cmd/gardener-resource-manager/app/app.go
  docs/concepts/resource-manager.md
  example/resource-manager/10-mutatingwebhookconfiguration.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/namespaces.go
  pkg/operation/botanist/namespaces_test.go
  pkg/operation/seed/components.go
  pkg/resourcemanager/webhook/podzoneaffinity/add.go
  pkg/resourcemanager/webhook/podzoneaffinity/handler.go
  pkg/resourcemanager/webhook/podzoneaffinity/handler_test.go
  pkg/resourcemanager/webhook/podzoneaffinity/podzoneaffinity_suite_test.go
  skaffold.yaml
  test/integration/resourcemanager/podzoneaffinity/podzoneaffinity_suite_test.go
  test/integration/resourcemanager/podzoneaffinity/podzoneaffinity_test.go
Labels: kind/bug, area/high-availability, area/control-plane, cla: yes, lgtm, approved, size/XXL

#6935 Add steps in local deployment and development how the kind network to be created
  docs/deployment/getting_started_locally.md
  docs/development/getting_started_locally.md
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved
