Repository gardener/gardener, pull requests merged in 2022-08, with the labels that each got.

#6257 Adapt seed system components priority classes
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-priorityclass.yaml
  charts/seed-bootstrap/charts/loki/templates/priorityclass.yaml
  charts/seed-bootstrap/charts/loki/templates/statefulset.yaml
  charts/seed-bootstrap/charts/loki/values.yaml
  charts/seed-bootstrap/charts/monitoring/templates/statefulset.yaml
  charts/seed-bootstrap/templates/aggregate-prometheus/statefulset.yaml
  charts/seed-bootstrap/templates/alertmanager/alertmanager.yaml
  charts/seed-bootstrap/templates/grafana/grafana-deployment.yaml
  charts/seed-bootstrap/templates/prometheus/statefulset.yaml
  charts/seed-monitoring/charts/alertmanager/templates/alertmanager.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-deployment.yaml
  hack/local-development/start-gardenlet
  pkg/gardenlet/controller/seed/seed_control.go
  pkg/gardenlet/controller/seed/seed_control_test.go
  pkg/operation/botanist/component/dependencywatchdog/bootstrap.go
  pkg/operation/botanist/component/dependencywatchdog/bootstrap_test.go
  pkg/operation/botanist/component/etcd/bootstrap.go
  pkg/operation/botanist/component/etcd/bootstrap_test.go
  pkg/operation/botanist/component/hvpa/hvpa.go
  pkg/operation/botanist/component/hvpa/hvpa_test.go
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/priorityclass-istioingressgateway.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/values.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/priorityclass-istiod.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/values.yaml
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/operation/botanist/component/kubestatemetrics/resources.go
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller_test.go
  pkg/operation/botanist/component/vpa/admissioncontroller.go
  pkg/operation/botanist/component/vpa/exporter.go
  pkg/operation/botanist/component/vpa/recommender.go
  pkg/operation/botanist/component/vpa/updater.go
  pkg/operation/botanist/component/vpa/vpa_test.go
  pkg/operation/botanist/component/vpnauthzserver/external_authz_server.go
  pkg/operation/botanist/component/vpnauthzserver/external_authz_server_test.go
Labels: kind/enhancement, size/L, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#6393 [GRM] Label managed resources
  docs/concepts/resource-manager.md
  pkg/apis/resources/v1alpha1/types.go
  pkg/resourcemanager/controller/managedresource/add.go
  pkg/resourcemanager/controller/managedresource/reconciler.go
  test/integration/resourcemanager/managedresource/resource_suite_test.go
  test/integration/resourcemanager/managedresource/resource_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, area/robustness, ok-to-test, cla: yes, lgtm, approved

#6407 Reload kube-apiserver variable on dashboard time change
  charts/seed-monitoring/charts/grafana/dashboards/owners/apiserver-request-duration-and-response-size.json
Labels: kind/bug, area/monitoring, component/dashboard, size/S, cla: yes, lgtm, approved

#6415 Use multi-arch node-problem-detector image
  charts/images.yaml
Labels: kind/enhancement, area/delivery, size/XS, ok-to-test, cla: yes, lgtm, approved

#6391 Switch Quota controller to controller-runtime
  docs/concepts/controller-manager.md
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/quota/add.go
  pkg/controllermanager/controller/quota/quota.go
  pkg/controllermanager/controller/quota/quota_suite_test.go
  pkg/controllermanager/controller/quota/reconciler.go
  pkg/controllermanager/controller/quota/reconciler_test.go
  test/integration/controllermanager/quota/quota_suite_test.go
  test/integration/controllermanager/quota/quota_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, area/scalability, ok-to-test, cla: yes, lgtm, approved

#6388 Enforce that Shoot nginx-ingress addon and Seed VPA are not enabled for ManagedSeeds
  docs/concepts/apiserver_admission_plugins.md
  docs/usage/managed_seed.md
  docs/usage/shoot_autoscaling.md
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
  plugin/pkg/shoot/managedseed/admission.go
  plugin/pkg/shoot/managedseed/admission_test.go
Labels: kind/enhancement, area/quality, size/L, ok-to-test, cla: yes, lgtm, approved

#6416 Improve validations on `shoots/binding` update
  docs/usage/control_plane_migration.md
  plugin/pkg/shoot/binding/admission.go
  plugin/pkg/shoot/binding/admission_test.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, area/ops-productivity, size/M, ok-to-test, cla: yes, lgtm, approved

#6432 Revert "Adapt `gardenlet` to use priority class `gardener-system-critical` (#6235)"
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  charts/gardener/gardenlet/charts/runtime/templates/priorityclass.yaml
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/seedsystem/seedsystem.go
  pkg/operation/botanist/component/seedsystem/seedsystem_test.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#6437 [release-v1.52] Revert "Adapt gardenlet to use priority class gardener-system-critical (#6235)"
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  charts/gardener/gardenlet/charts/runtime/templates/priorityclass.yaml
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/operation/botanist/component/seedsystem/seedsystem.go
  pkg/operation/botanist/component/seedsystem/seedsystem_test.go
Labels: kind/bug, size/S, area/control-plane, cla: yes, lgtm, approved

#6428 Upgrade gardener/autoscaler
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/auto-scaling, ok-to-test, cla: yes, lgtm, approved

#6412 Disables owner checks for clustered ETCD
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
Labels: kind/enhancement, size/S, area/high-availability, area/control-plane-migration, ok-to-test, cla: yes, lgtm, approved

#6434 Fix etcd readiness check
  pkg/operation/botanist/component/etcd/waiter.go
  pkg/operation/botanist/component/etcd/waiter_test.go
Labels: kind/bug, size/S, area/control-plane, cla: yes, lgtm, approved

#6443 Upgrade K8s dependencies to v0.24.3
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/modules.txt
Labels: kind/bug, area/quality, ok-to-test, cla: yes, lgtm, approved

#6429 Promote the `SecretBindingProviderValidation` feature gate to GA
  docs/api-reference/core.md
  docs/deployment/feature_gates.md
  docs/deployment/secret_binding_provider_controller.md
  pkg/apis/core/types_secretbinding.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_secretbinding.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_secretbinding.go
  pkg/apis/core/validation/secretbinding.go
  pkg/apis/core/validation/secretbinding_test.go
  pkg/features/features.go
  pkg/openapi/openapi_generated.go
  pkg/registry/core/secretbinding/strategy_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  plugin/pkg/shoot/validator/validator_suite_test.go
Labels: kind/enhancement, size/XL, cla: yes, lgtm, approved

#6446 Update `redis` test image to multi arch image
  test/framework/applications/guestbooktest.go
Labels: kind/enhancement, area/delivery, size/XS, cla: yes, lgtm, approved

#6448 [release-v1.51] Automated cherry pick of #6443: Upgrade K8s dependencies to v0.24.3
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/modules.txt
Labels: kind/bug, size/L, cla: yes, lgtm, approved

#6449 Update gardener/autoscaler for K8S v1.20, v1.21 and v1.22
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/auto-scaling, cla: yes, lgtm, approved

#6424 Collect filesystem metrics for the /run tmpfs mount point
  charts/seed-bootstrap/values.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/node-exporter.rules.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
Labels: kind/enhancement, size/XS, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#6445 Exclude the proxy subresource from the KubeApiServerLatency alert and dashboard
  charts/seed-monitoring/charts/grafana/dashboards/owners/apiserver-overview.json
  pkg/operation/botanist/component/kubeapiserver/monitoring.go
  pkg/operation/botanist/component/kubeapiserver/monitoring_test.go
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6423 Switch ExposureClass controller to controller-runtime
  docs/concepts/controller-manager.md
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/exposureclass/add.go
  pkg/controllermanager/controller/exposureclass/exposureclass.go
  pkg/controllermanager/controller/exposureclass/exposureclass_control_test.go
  pkg/controllermanager/controller/exposureclass/exposureclass_suite_test.go
  pkg/controllermanager/controller/exposureclass/reconciler.go
  pkg/controllermanager/controller/exposureclass/reconciler_test.go
  pkg/controllermanager/controller/factory.go
  test/integration/controllermanager/exposureclass/exposureclass_suite_test.go
  test/integration/controllermanager/exposureclass/exposureclass_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, area/scalability, cla: yes, lgtm, approved

#6433 Option to disable gardener shoot monitoring
  docs/monitoring/README.md
  example/20-componentconfig-gardenlet.yaml
  pkg/gardenlet/apis/config/helper/helpers.go
  pkg/gardenlet/apis/config/helper/helpers_test.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/kubestatemetrics.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/care/checker.go
  pkg/operation/care/health.go
  pkg/operation/care/health_check_test.go
  pkg/operation/operation.go
Labels: kind/enhancement, kind/api-change, size/L, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#6451 Do not run node-local-dns/node-cache in privileged mode
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns_test.go
Labels: kind/enhancement, area/security, size/S, cla: yes, lgtm, approved

#6452 Promote `SeedChange` and `CopyEtcdBackupsDuringControlPlaneMigration` feature gates to beta
  docs/deployment/feature_gates.md
  docs/usage/control_plane_migration.md
  example/20-componentconfig-gardenlet.yaml
  pkg/features/features.go
  plugin/pkg/shoot/binding/admission_test.go
Labels: kind/enhancement, size/S, area/control-plane-migration, cla: yes, lgtm, approved

#6456 Update node local dns to v1.22.8
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#6457 Execute workaround for kube-proxy issue only for K8s < 1.25 Shoots
  pkg/operation/botanist/component/kubeproxy/kube_proxy_test.go
  pkg/operation/botanist/component/kubeproxy/resources.go
  pkg/operation/botanist/component/kubeproxy/resources/cleanup.sh
Labels: kind/enhancement, area/open-source, size/M, cla: yes, lgtm, approved

#6461 Fix flaky scheduler integration test
  test/integration/controllermanager/bastion/bastion_suite_test.go
  test/integration/controllermanager/bastion/bastion_test.go
  test/integration/scheduler/shoot/scheduler_test.go
Labels: size/XS, area/testing, kind/flake, cla: yes, lgtm, approved

#6465 Fix control plane monitoring and logging PriorityClasses
  charts/gardener/gardenlet/values.yaml
  charts/seed-bootstrap/charts/loki/templates/statefulset.yaml
  charts/seed-bootstrap/charts/loki/values.yaml
  charts/seed-monitoring/charts/alertmanager/templates/alertmanager.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-deployment.yaml
  docs/deployment/configuring_logging.md
  docs/development/priority-classes.md
  example/20-componentconfig-gardenlet.yaml
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/operation/botanist/logging.go
  pkg/operation/care/health_check_test.go
  pkg/operation/common/types.go
  pkg/operation/common/utils.go
  pkg/operation/common/utils_test.go
  pkg/operation/seed/seed.go
  test/testmachinery/shoots/logging/seed_logging_stack.go
Labels: kind/bug, size/L, area/control-plane, cla: yes, lgtm, approved

#6468 Improve the K8s version checks in the nginx-ingress component to consider versions with suffixes
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
  pkg/operation/seed/nginxingress.go
Labels: kind/bug, area/quality, size/M, cla: yes, lgtm, approved

#6223 Install shoot event logger to scrape events from shoot and seed.
  charts/images.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/_fluent-bit-config.tpl
  charts/seed-bootstrap/charts/fluent-bit/templates/_helpers.tpl
  charts/seed-bootstrap/requirements.yaml
  docs/development/priority-classes.md
  docs/usage/logging.md
  example/20-componentconfig-gardenlet.yaml
  hack/.ci/set_dependency_version
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/apis/config/helper/helpers.go
  pkg/gardenlet/apis/config/helper/helpers_test.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/downloader.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/config.go
  pkg/operation/botanist/component/hvpa/hvpa_test.go
  pkg/operation/botanist/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/operation/botanist/component/logging/eventlogger/event_logger.go
  pkg/operation/botanist/component/logging/eventlogger/event_logger_suite_test.go
  pkg/operation/botanist/component/logging/eventlogger/event_logger_test.go
  pkg/operation/botanist/component/logging/eventlogger/logging.go
  pkg/operation/botanist/component/logging/eventlogger/logging_test.go
  pkg/operation/botanist/component/logging/kube_rbac_proxy_test.go
  pkg/operation/botanist/component/logging/kuberbacproxy/kube_rbac_proxy.go
  pkg/operation/botanist/component/logging/kuberbacproxy/kube_rbac_proxy_suite_test.go
  pkg/operation/botanist/component/logging/kuberbacproxy/kube_rbac_proxy_test.go
  pkg/operation/botanist/component/test/seralize.go
  pkg/operation/botanist/component/vpa/vpa_test.go
  pkg/operation/botanist/logging.go
  pkg/operation/botanist/logging_test.go
  pkg/operation/care/checker.go
  pkg/operation/care/health.go
  pkg/operation/care/health_check_test.go
  pkg/operation/seed/seed.go
  pkg/operation/shoot/types.go
  pkg/utils/images/images.go
Labels: kind/enhancement, area/logging, ok-to-test, cla: yes, lgtm, approved, size/XXL

#6467 Integrate etcd-druid v0.12
  charts/images.yaml
  pkg/operation/botanist/component/etcd/bootstrap.go
  pkg/operation/botanist/component/etcd/bootstrap_test.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  test/e2e/shoot/create_rotate_delete.go
  test/e2e/shoot/internal/rotation/certificate_authorities.go
Labels: kind/enhancement, area/backup, size/S, cla: yes, lgtm, approved

#6409 Don't deploy `PSP`s when `PodSecurityPolicy` plugin is disabled
  charts/shoot-addons/charts/kubernetes-dashboard/templates/deployment-dashboard.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/deployment-metrics-scraper.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/default-backend-deployment.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/psp/nginx-ingress-rolebinding-privileged.yaml
  charts/shoot-addons/values.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/psp/apiserver-proxy-clusterrole.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/psp/apiserver-proxy-psp.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/psp/apiserver-proxy-rolebinding.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/psp/node-exporter-clusterrole.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/psp/node-exporter-psp.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/psp/node-exporter-rolebinding.yaml
  charts/shoot-core/components/values.yaml
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/component/coredns/coredns.go
  pkg/operation/botanist/component/coredns/coredns_test.go
  pkg/operation/botanist/component/kubeproxy/kube_proxy.go
  pkg/operation/botanist/component/kubeproxy/kube_proxy_test.go
  pkg/operation/botanist/component/kubeproxy/resources.go
  pkg/operation/botanist/component/metricsserver/metrics_server.go
  pkg/operation/botanist/component/metricsserver/metrics_server_test.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns_test.go
  pkg/operation/botanist/component/nodeproblemdetector/node_problem_detector.go
  pkg/operation/botanist/component/nodeproblemdetector/node_problem_detector_test.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot_test.go
  pkg/operation/botanist/kubeproxy.go
  pkg/operation/botanist/nodelocaldns.go
  pkg/operation/botanist/nodeproblemdetector.go
  pkg/operation/botanist/vpnshoot.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
  pkg/utils/version/version.go
  test/framework/applications/guestbooktest.go
  test/framework/k8s_utils.go
  test/testmachinery/shoots/applications/networking.go
  test/testmachinery/shoots/logging/seed_logging_stack.go
Labels: kind/enhancement, area/open-source, component/gardener, ok-to-test, cla: yes, lgtm, approved, size/XXL

#6287 [GEP-20] HA Shoot Control Planes
  docs/README.md
  docs/proposals/20-ha-control-planes.md
  docs/proposals/assets/activepassive-option1.png
  docs/proposals/assets/activepassive-option2.png
  docs/proposals/assets/delete-request-targeting-follower.png
  docs/proposals/assets/delete-request-targeting-leader.png
  docs/proposals/assets/etcd-member-initial-sync-with-large-revision.png
  docs/proposals/assets/etcdcluster-steadystate-traffic.png
  docs/proposals/assets/etcdcustomresource.png
  docs/proposals/assets/get-request-targeting-follower.png
  docs/proposals/assets/get-request-targeting-leader.png
  docs/proposals/assets/multi-zone-node-groups.png
  docs/proposals/assets/multizone-multinode.png
  docs/proposals/assets/put-request-targeting-follower.png
  docs/proposals/assets/put-request-targeting-leader.png
  docs/proposals/assets/singlezone-multinode.png
  docs/proposals/assets/watch-request-del-targeting-follower.png
  docs/proposals/assets/watch-request-targeting-follower.png
Labels: kind/discussion, area/documentation, area/control-plane, ok-to-test, cla: yes, lgtm, approved, size/XXL

#6462 Switch ControllerDeployment controller to controller-runtime
  docs/concepts/controller-manager.md
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/controllerdeployment/add.go
  pkg/controllermanager/controller/controllerdeployment/controllerdeployment.go
  pkg/controllermanager/controller/controllerdeployment/controllerdeployment_control_test.go
  pkg/controllermanager/controller/controllerdeployment/reconciler.go
  pkg/controllermanager/controller/controllerdeployment/reconciler_test.go
  pkg/controllermanager/controller/factory.go
  test/integration/controllermanager/controllerdeployment/controllerdeployment_suite_test.go
  test/integration/controllermanager/controllerdeployment/controllerdeployment_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, area/scalability, cla: yes, lgtm, approved

#6476 Do not run kube-proxy/cleanup in privileged mode
  pkg/operation/botanist/component/kubeproxy/kube_proxy_test.go
  pkg/operation/botanist/component/kubeproxy/resources.go
Labels: kind/enhancement, area/security, size/XS, cla: yes, lgtm, approved

#6475 Persist additional disk storage metrics in Prometheus
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
Labels: kind/enhancement, size/XS, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#6477 Switch health check port of node local dns to a less often used port.
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns_test.go
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#6455 Add `gomegacheck` linter
  .golangci.yaml
  Makefile
  extensions/pkg/webhook/certificates/certificates_test.go
  hack/tools.mk
  hack/tools/gomegacheck/README.md
  hack/tools/gomegacheck/go.mod
  hack/tools/gomegacheck/go.sum
  hack/tools/gomegacheck/main.go
  hack/tools/gomegacheck/pkg/gomegacheck/gomegacheck.go
  hack/tools/gomegacheck/pkg/gomegacheck/gomegacheck_test.go
  hack/tools/gomegacheck/pkg/gomegacheck/testdata/src/README.md
  hack/tools/gomegacheck/pkg/gomegacheck/testdata/src/github.com/onsi/gomega/gomega_dsl.go
  hack/tools/gomegacheck/pkg/gomegacheck/testdata/src/github.com/onsi/gomega/internal
  hack/tools/gomegacheck/pkg/gomegacheck/testdata/src/github.com/onsi/gomega/types
  hack/tools/gomegacheck/pkg/gomegacheck/testdata/src/no-gomega/no_gomega_test.go
  hack/tools/gomegacheck/pkg/gomegacheck/testdata/src/use-gomega/use_gomega_test.go
  hack/tools/gomegacheck/plugin/golangci_lint.go
  pkg/controllermanager/controller/exposureclass/reconciler_test.go
  pkg/gardenlet/controller/extensions/shootstate_control_test.go
  pkg/gardenlet/controller/seed/seed_extension_control_test.go
  pkg/operation/botanist/component/coredns/coredns_test.go
  pkg/operation/botanist/component/dependencywatchdog/bootstrap_test.go
  pkg/operation/botanist/component/hvpa/hvpa_test.go
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/kubeproxy/kube_proxy_test.go
  pkg/operation/botanist/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/operation/botanist/component/namespaces/namespaces_test.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns_test.go
  pkg/operation/botanist/component/nodeproblemdetector/node_problem_detector_test.go
  pkg/operation/botanist/component/seedsystem/seedsystem_test.go
  pkg/operation/botanist/component/shootsystem/shootsystem_test.go
  pkg/operation/botanist/component/vpa/vpa_test.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot_test.go
  pkg/operation/botanist/secrets_test.go
  pkg/utils/kubernetes/client/client_test.go
  test/integration/resourcemanager/health/health_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, area/testing, cla: yes, lgtm, approved

#6482 Fix flaky integration test
  test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_suite_test.go
  test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_test.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#6488 Increase shoot creation timeout for ManagedSeed e2e test
  test/e2e/managedseed/create_delete.go
Labels: area/dev-productivity, size/XS, kind/flake, cla: yes, lgtm, approved

#6490 Upgrade prometheus version
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6492 Update gardenlet's base image to alpine:3.16.2
  Dockerfile
  Dockerfile.local
Labels: kind/enhancement, area/security, size/XS, cla: yes, lgtm, approved

#6491 Update go version to 1.18.5
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
  Dockerfile.local
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#6493 Fix the guestbook integration test for alicloud Shoots
  test/framework/applications/guestbooktest.go
Labels: kind/bug, kind/regression, size/S, area/testing, cla: yes, lgtm, approved

#6484 Install kubectl as local tool
  Makefile
  hack/tools.mk
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#6479 Cleanup of DNSProvider extension kind
  charts/gardener/gardenlet/charts/runtime/templates/clusterrole-gardenlet.yaml
  charts/gardener/provider-local/extension/doc.go
  charts/gardener/provider-local/extension/templates/rbac.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  docs/extensions/dnsrecord.md
  docs/extensions/provider-local.md
  docs/usage/trouble_shooting_guide.md
  example/provider-local/garden/base/controller-registration.yaml
  extensions/README.md
  go.mod
  go.sum
  pkg/apis/core/types_controllerregistration.go
  pkg/apis/core/validation/controllerregistration.go
  pkg/client/kubernetes/types.go
  pkg/controllermanager/controller/controllerregistration/seed_control_test.go
  pkg/gardenlet/controller/extensions/artifact.go
  pkg/gardenlet/controller/extensions/controllerinstallation_control.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/operation/botanist/component/extensions/crds/crds.go
  pkg/operation/botanist/component/extensions/crds/crds_test.go
  pkg/operation/botanist/component/extensions/crds/templates/crd-dnsentry.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-dnsowner.tpl.yaml
  pkg/operation/botanist/component/extensions/crds/templates/crd-dnsprovider.tpl.yaml
  pkg/operation/botanist/dns.go
  pkg/operation/botanist/dns_test.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/shoot_test.go
  plugin/pkg/global/extensionvalidation/admission.go
  plugin/pkg/global/extensionvalidation/admission_test.go
  test/integration/seedadmissioncontroller/extensioncrds/extensioncrds_test.go
  vendor/github.com/gardener/external-dns-management/LICENSE.md
  vendor/github.com/gardener/external-dns-management/NOTICE.md
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/register.go
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/dnsannotation.go
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/dnsentry.go
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/dnsowner.go
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/dnsprovider.go
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/doc.go
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/register.go
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/state.go
  vendor/github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: kind/technical-debt, cla: yes, lgtm, approved, size/XXL

#6480 Cleanup CloudProfile docker migration and Add Validation MachineImageVersion CRI
  example/provider-local/garden/base/cloudprofile.yaml
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/zz_generated.defaults.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/controllermanager/controller/cloudprofile/reconciler.go
  pkg/controllermanager/controller/cloudprofile/reconciler_test.go
Labels: size/L, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#6499 Upgrade blackbox exporter
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6500 Update cluster-proportional-autoscaler image
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#6497 Simplify deflaking gardener integration tests
  docs/development/testing.md
  hack/test-integration.env
  hack/test-integration.sh
  pkg/envtest/environment.go
Labels: kind/enhancement, size/L, area/testing, cla: yes, lgtm, approved

#6478 Integration test for cloudprovider extension webhook
  extensions/pkg/webhook/certificates/certificates.go
  test/integration/extensions/webhook/cloudprovider/cloudprovider_suite_test.go
  test/integration/extensions/webhook/cloudprovider/cloudprovider_test.go
  test/integration/extensions/webhook/cloudprovider/ensurer.go
Labels: kind/enhancement, area/dev-productivity, area/quality, size/L, area/robustness, area/testing, cla: yes, lgtm, approved

#6498 Deflake bastion controller integration test
  test/integration/controllermanager/bastion/bastion_suite_test.go
  test/integration/controllermanager/bastion/bastion_test.go
Labels: size/S, kind/flake, cla: yes, lgtm, approved

#6511 Delay the cleanup of the `loki` PriorityClass
  pkg/gardenlet/controller/seed/seed_control.go
  pkg/gardenlet/controller/seed/seed_control_test.go
Labels: kind/bug, size/XS, kind/regression, area/control-plane, cla: yes, lgtm, approved

#6503 Upgrade alertmanager version
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6508 Update gardener/autoscaler for K8S v1.24
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/auto-scaling, cla: yes, lgtm, approved

#6481 fix(dnsrecord): reconcile dnsrecords when changing their spec
  pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go
  pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go
Labels: kind/bug, size/L, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#6514 Upgrade `golangci-lint` to v1.48.0
  hack/tools.mk
  hack/tools/gomegacheck/go.mod
  hack/tools/gomegacheck/go.sum
  hack/tools/logcheck/go.mod
  hack/tools/logcheck/go.sum
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#6513 Create user RBAC on `make dev-setup`
  hack/local-development/dev-setup-configure-rbac
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#6521 Switch default backend to `eu.gcr.io/gardener-project/gardener/ingress-default-backend:0.11.0`
  charts/images.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/default-backend-deployment.yaml
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
Labels: kind/enhancement, area/open-source, size/S, cla: yes, lgtm, approved

#6515 Use PriorityClass for terraformer
  docs/development/priority-classes.md
  extensions/pkg/terraformer/terraformer.go
Labels: kind/enhancement, area/robustness, size/S, cla: yes, lgtm, approved

#6524 Upgrade prometheus to v2.38.0
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6525 Upgrade the version of fluent-bit image to 1.9.7
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#6526 Upgrade configmap-reloader
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6527 Deflake more integration tests
  docs/development/testing.md
  pkg/controllermanager/controller/controllerdeployment/add.go
  pkg/controllermanager/controller/controllerdeployment/reconciler.go
  pkg/controllermanager/controller/exposureclass/add.go
  pkg/controllermanager/controller/exposureclass/reconciler.go
  test/integration/controllermanager/cloudprofile/cloudprofile_suite_test.go
  test/integration/controllermanager/cloudprofile/cloudprofile_test.go
  test/integration/controllermanager/controllerdeployment/controllerdeployment_suite_test.go
  test/integration/controllermanager/controllerdeployment/controllerdeployment_test.go
  test/integration/controllermanager/exposureclass/exposureclass_suite_test.go
  test/integration/controllermanager/exposureclass/exposureclass_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
  test/integration/extensions/webhook/cloudprovider/cloudprovider_test.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#6534 Label shoots for globally enabled extensions
  plugin/pkg/global/extensionlabels/admission.go
  plugin/pkg/global/extensionlabels/admission_test.go
Labels: kind/bug, size/L, area/robustness, cla: yes, lgtm, approved

#6509 [GEP-20] Minor changes to GEP to include HA setup for additional shoot control plane components
  docs/proposals/20-ha-control-planes.md
Labels: kind/discussion, size/S, area/control-plane, cla: yes, lgtm, approved

#6535 Docforge version update
  hack/check-docforge.sh
  hack/tools.mk
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#6510 Migrate gardenlet priority-class
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  charts/gardener/gardenlet/charts/runtime/templates/priorityclass.yaml
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/deployment.yaml
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/seedsystem/seedsystem.go
  pkg/operation/botanist/component/seedsystem/seedsystem_test.go
Labels: kind/enhancement, size/M, area/control-plane, cla: yes, lgtm, approved

#6545 Provider local updates
  example/provider-local/garden/base/kustomization.yaml
  pkg/provider-local/imagevector/images.yaml
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#6547 Fix kubectl download for aarch64 machines
  hack/tools.mk
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#6531 Use `kube-state-metrics` v2.5.0 for seed version >=1.20
  pkg/operation/seed/components.go
  pkg/operation/seed/seed.go
Labels: kind/enhancement, size/XS, area/monitoring, area/control-plane, cla: yes, lgtm, approved

#6523 Improve the ApiServerUnreachableViaKubernetesService alert
  charts/seed-monitoring/charts/core/charts/prometheus/rules-tests/apiserver-connectivity-check.rules.test.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/rules/apiserver-connectivity-check.rules.yaml
  docs/monitoring/operator_alerts.md
  docs/monitoring/user_alerts.md
Labels: kind/enhancement, size/M, area/monitoring, cla: yes, lgtm, approved

#6546 update logging components from 0.42.0 to 0.43.0
  charts/images.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/_fluent-bit-config.tpl
  pkg/operation/botanist/component/logging/eventlogger/event_logger.go
  pkg/operation/botanist/component/logging/eventlogger/event_logger_test.go
Labels: kind/enhancement, area/logging, size/S, cla: yes, lgtm, approved

#6557 Gardener API server now uses dedicated folder for the audit logs
  charts/gardener/controlplane/values.yaml
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/options/audit.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/client-go/tools/clientcmd/auth_loaders.go
  vendor/modules.txt
Labels: kind/enhancement, size/L, kind/cleanup, area/audit-logging, cla: yes, lgtm, approved

#6553 Remove readiness/liveness probes and metrics requests from apiserver-proxy access log.
  charts/shoot-core/components/charts/apiserver-proxy/templates/_helpers.tpl
Labels: kind/enhancement, area/networking, size/S, cla: yes, lgtm, approved

#6558 Revert "Do not run kube-proxy/cleanup in privileged mode"
  pkg/operation/botanist/component/kubeproxy/kube_proxy_test.go
  pkg/operation/botanist/component/kubeproxy/resources.go
Labels: kind/bug, size/XS, area/networking, cla: yes, lgtm, approved

#6560 Deflake ExposureClass controller integration test
  test/integration/controllermanager/exposureclass/exposureclass_suite_test.go
  test/integration/controllermanager/exposureclass/exposureclass_test.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#6552 Evaluate etcd's `BackupReady` condition
  example/seed-crds/10-crd-druid.gardener.cloud_etcds.yaml
  go.mod
  go.sum
  pkg/utils/kubernetes/health/etcd.go
  pkg/utils/kubernetes/health/etcd_test.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/miscellaneous.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/names.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/statefulset.go
  vendor/modules.txt
Labels: kind/enhancement, size/L, area/control-plane, cla: yes, lgtm, approved, tide/merge-method-squash

#6556 Updated gardenlet image to use `scratch` based image
  Dockerfile
  Dockerfile.local
  cmd/gardenlet/main.go
Labels: kind/enhancement, area/security, area/open-source, size/M, cla: yes, lgtm, approved

#6431 Enforce PSP admission plugin disablement before upgrading the shoot cluster to `v1.25`
  docs/README.md
  docs/concepts/controller-manager.md
  docs/proposals/10-shoot-additional-container-runtimes.md
  docs/usage/pod-security.md
  pkg/api/core/shoot/warnings_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/operation/botanist/component/kubeapiserver/configmaps.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  pkg/utils/version/version.go
  test/integration/extensions/webhook/cloudprovider/ensurer.go
Labels: kind/enhancement, area/open-source, size/L, component/gardener, cla: yes, lgtm, approved

#6554 Build local gardener images with `ko`
  Dockerfile
  Dockerfile.local
  Makefile
  charts/charts.go
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/scheduler/deployment.yaml
  charts/gardener/gardener-resource-manager/templates/deployment.yaml
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/values.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-extension-provider-local/kodata/charts
  cmd/gardenlet/kodata/charts
  example/gardener-local/controlplane/values.yaml
  example/provider-local/garden/base/controller-registration.yaml
  hack/tools.mk
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller_test.go
  pkg/provider-local/controller/dnsrecord/actuator.go
  pkg/provider-local/controller/dnsrecord/add.go
  pkg/provider-local/controller/dnsrecord/options.go
  pkg/provider-local/local/types.go
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#6550 Switch Event controller to controller-runtime
  docs/concepts/controller-manager.md
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/event/add.go
  pkg/controllermanager/controller/event/event.go
  pkg/controllermanager/controller/event/event_control_test.go
  pkg/controllermanager/controller/event/event_suite_test.go
  pkg/controllermanager/controller/event/reconciler.go
  pkg/controllermanager/controller/event/reconciler_test.go
  pkg/controllermanager/controller/factory.go
  test/integration/controllermanager/event/event_suite_test.go
  test/integration/controllermanager/event/event_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, area/scalability, cla: yes, lgtm, approved

#6563 Improve the listing of cloud-config Secret by specifying a namespace
  pkg/operation/botanist/worker.go
  pkg/operation/botanist/worker_test.go
  pkg/operation/care/health_check_test.go
Labels: kind/enhancement, size/S, area/control-plane, cla: yes, lgtm, approved

#6572 Cleanup special owners handling for testmachinery
  .test-defs/OWNERS
  OWNERS_ALIASES
  test/testmachinery/OWNERS
Labels: kind/cleanup, cla: yes, lgtm, approved

#6571 Cap the Loki container requests to 50m of CPU and 300Mi of Memory for the test-machinery
  test/testmachinery/shoots/logging/seed_logging_stack.go
Labels: kind/test, area/logging, size/S, cla: yes, lgtm, approved

#6551 Adds `Progressing` status to `ExtensionsReady` seed condition
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  charts/gardener/controlplane/values.yaml
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/defaults_test.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/seed/seed.go
  pkg/controllermanager/controller/seed/seed_extension_check_control.go
  pkg/controllermanager/controller/seed/seed_extension_check_control_test.go
  pkg/gardenlet/controller/seed/seed.go
  pkg/gardenlet/controller/seed/seed_extension_control.go
  pkg/gardenlet/controller/seed/seed_extension_control_test.go
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_suite_test.go
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go
Labels: kind/enhancement, area/ops-productivity, cla: yes, lgtm, approved, size/XXL

#6555 Prevent confusing error messages about outdated cloud configs on nodes during rolling updates
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/worker.go
  pkg/operation/botanist/worker_test.go
  pkg/operation/care/checker.go
  pkg/operation/care/health_check_test.go
Labels: kind/bug, area/ops-productivity, size/L, cla: yes, lgtm, approved

#6574 Specify the kubelet flag runtime-cgroups when using containerd
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/cliflags.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/cliflags_test.go
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6578 Fix `hack/check-docforge.sh` to do not silently fail
  hack/check-docforge.sh
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#6575 Use `Eventually`/`Consistently` in all integration tests
  test/framework/resources/templates/pod-anti-affinity-deployment.yaml.tpl
  test/integration/controllermanager/shoot/maintenance/utils_test.go
  test/integration/controllermanager/shoot/retry/retry_test.go
  test/integration/extensions/controller/backupbucket/backupbucket_test.go
Labels: size/M, kind/technical-debt, area/testing, cla: yes, lgtm, approved

#6192 Add option to automatically rewrite some dns requests to reduce amount of requests being made due to dns search path and ndots=5.
  docs/README.md
  docs/api-reference/core.md
  docs/concepts/apiserver_admission_plugins.md
  docs/deployment/feature_gates.md
  docs/usage/dns-search-path-optimization.md
  example/20-admissionconfig.yaml
  example/20-componentconfig-gardenlet.yaml
  example/90-shoot.yaml
  example/gardener-local/gardenlet/values.yaml
  hack/update-codegen.sh
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/plugins.go
  pkg/features/features.go
  pkg/gardenlet/features/features.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/coredns/coredns.go
  pkg/operation/botanist/component/coredns/coredns_test.go
  pkg/operation/botanist/coredns.go
  plugin/pkg/shoot/dnsrewriting/admission.go
  plugin/pkg/shoot/dnsrewriting/admission_test.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/doc.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/install/install.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/register.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/types.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/v1alpha1/defaults.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/v1alpha1/doc.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/v1alpha1/register.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/v1alpha1/types.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/v1alpha1/zz_generated.conversion.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/v1alpha1/zz_generated.deepcopy.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/v1alpha1/zz_generated.defaults.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/validation/validation.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/validation/validation_suite_test.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/validation/validation_test.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/zz_generated.deepcopy.go
  plugin/pkg/shoot/dnsrewriting/config.go
  plugin/pkg/shoot/dnsrewriting/dnsrewriting_suite_test.go
Labels: kind/enhancement, area/networking, ok-to-test, cla: yes, lgtm, approved, size/XXL

#6580 Minor corrections to the README.md
  README.md
Labels: size/XS, kind/cleanup, cla: yes, lgtm, approved

#6581 Dump logs of shoot machine pods in e2e tests
  hack/ci-common.sh
  hack/ci-e2e-kind-migration.sh
  hack/ci-e2e-kind.sh
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/M, area/testing, cla: yes, lgtm, approved

#6577 Improve log values in webhook remediator
  docs/development/logging.md
  pkg/operation/care/webhook_remediation.go
Labels: kind/enhancement, area/ops-productivity, size/XS, cla: yes, lgtm, approved

#6584 Fix the monitoring configuration tracking the count of ETCD objects to use correct metric for k8s >= 1.21
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/etcd/monitoring.go
  pkg/operation/botanist/component/etcd/monitoring_test.go
  pkg/operation/botanist/component/etcd/waiter_test.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
Labels: kind/bug, size/M, area/monitoring, cla: yes, lgtm, approved

#6573 Skip problematic webhook check for Gardener-managed webhooks
  pkg/operation/care/constraints.go
  pkg/operation/care/webhook_remediation.go
  pkg/operation/care/webhook_remediation_test.go
  pkg/provider-local/webhook/node/add.go
Labels: kind/enhancement, area/dev-productivity, area/ops-productivity, size/M, cla: yes, lgtm, approved

#6586 Use priority class `gardener-system-critical`
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  charts/gardener/gardenlet/charts/runtime/templates/priorityclass.yaml
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/deployment.yaml
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
Labels: kind/enhancement, size/S, area/control-plane, cla: yes, lgtm, approved

#6576 Validate seed network configuration on gardenlet startup.
  cmd/gardenlet/app/gardenlet.go
  cmd/gardenlet/app/gardenlet_suite_test.go
  cmd/gardenlet/app/gardenlet_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, area/networking, cla: yes, lgtm, approved

#6366 Update envoy proxy to v1.23.1
  charts/images.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/_helpers.tpl
  charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-daemonset.yaml
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server_test.go
Labels: kind/enhancement, size/M, area/networking, ok-to-test, cla: yes, lgtm, approved

#6568 Extend `ManagedSeed` e2e test with gardenlet kubeconfig rotation scenarios
  charts/gardener/gardenlet/charts/runtime/templates/_helpers.tpl
  charts/gardener/gardenlet/values.yaml
  cmd/gardenlet/app/bootstrap.go
  docs/concepts/gardenlet.md
  example/20-componentconfig-gardenlet.yaml
  hack/test-e2e-local.sh
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/apis/config/validation/validation.go
  pkg/gardenlet/apis/config/validation/validation_test.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/bootstrap/bootstrap.go
  pkg/gardenlet/bootstrap/bootstrap_test.go
  pkg/gardenlet/bootstrap/certificate/certificate.go
  pkg/gardenlet/bootstrap/certificate/certificate_rotation.go
  pkg/gardenlet/bootstrap/certificate/certificate_rotation_test.go
  pkg/gardenlet/bootstrap/certificate/certificate_util.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  test/e2e/managedseed/create_delete.go
  test/e2e/managedseed/create_rotate_delete.go
Labels: area/dev-productivity, area/ops-productivity, kind/test, cla: yes, lgtm, approved, size/XXL

#6589 Export all events of kind and shoot clusters to `ARTIFACTS` directory in CI
  docs/deployment/getting_started_locally.md
  hack/ci-common.sh
  hack/ci-e2e-kind-migration.sh
  hack/ci-e2e-kind.sh
  hack/test-e2e-local.sh
  test/e2e/common.go
  test/e2e/managedseed/create_rotate_delete.go
  test/e2e/shoot/common.go
  test/e2e/shoot/create_and_delete_hibernated.go
  test/e2e/shoot/create_and_delete_unprivileged.go
  test/e2e/shoot/create_hibernate_wakeup_delete.go
  test/e2e/shoot/create_migrate_delete.go
  test/e2e/shoot/create_rotate_delete.go
  test/e2e/shoot/create_update_delete.go
Labels: kind/enhancement, area/dev-productivity, size/L, area/testing, cla: yes, lgtm, approved

#6593 Clean up the `SecretBindingProviderValidation` feature gate
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  docs/deployment/feature_gates.md
  docs/deployment/secret_binding_provider_controller.md
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/apiserver/features/features.go
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/defaults_test.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/validation/validation.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/secretbinding/secretbinding.go
  pkg/controllermanager/controller/secretbinding/secretbinding_provider_control.go
  pkg/features/features.go
  pkg/operation/seed/seed.go
Labels: size/L, kind/cleanup, cla: yes, lgtm, approved

#6594 Restore node labels for kube state metrics
  pkg/operation/botanist/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/operation/botanist/component/kubestatemetrics/resources.go
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6564 Add the container_oom_events_total metric
  charts/seed-bootstrap/charts/monitoring/values.yaml
  charts/seed-bootstrap/values.yaml
  charts/seed-monitoring/charts/grafana/dashboards/operators/kubernetes-pods-dashboard.json
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#6591 [gardener-local] Add pull-through cache registry
  Makefile
  charts/images.yaml
  charts/shoot-addons/charts/nginx-ingress/README.md
  docs/api-reference/core.md
  docs/deployment/getting_started_locally.md
  docs/deployment/image_vector.md
  docs/development/getting_started_locally.md
  example/90-shoot.yaml
  example/gardener-local/kind/cluster-local.yaml
  example/gardener-local/kind/cluster-skaffold.yaml
  example/gardener-local/kind2/cluster-local.yaml
  example/gardener-local/kind2/cluster-skaffold.yaml
  example/gardener-local/metrics-server/kustomization.yaml
  example/gardener-local/registry/base/kustomization.yaml
  example/gardener-local/registry/base/registry.yaml
  example/gardener-local/registry/docker/kustomization.yaml
  example/gardener-local/registry/gcr-eu/kustomization.yaml
  example/gardener-local/registry/gcr/kustomization.yaml
  example/gardener-local/registry/ghcr/kustomization.yaml
  example/gardener-local/registry/k8s/kustomization.yaml
  example/gardener-local/registry/kustomization.yaml
  example/gardener-local/registry/localhost/kustomization.yaml
  example/gardener-local/registry/namespace.yaml
  example/gardener-local/registry/quay/kustomization.yaml
  example/gardener-local/registry/registry.yaml
  example/provider-local/managedseeds/shoot-managedseed.yaml
  example/provider-local/shoot.yaml
  hack/local-development/local-garden/run-kube-apiserver
  hack/local-development/local-garden/run-kube-controller-manager
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/utils/unitserializer_test.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/component/metricsserver/metrics_server_test.go
  pkg/provider-local/webhook/controlplane/ensurer.go
  test/e2e/common.go
  test/framework/resources/templates/logger-app.yaml.tpl
  test/framework/resources/templates/pod-anti-affinity-deployment.yaml.tpl
  test/framework/resources/templates/vpntunnel.yaml.tpl
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#6595 Improve the Node/Worker Pool Overview dashboard
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-pool-dashboard.json
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#6599 Deprecate the `SeedKubeScheduler` feature gate
  docs/deployment/feature_gates.md
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/gardenlet/values.yaml
  pkg/features/features.go
Labels: size/L, kind/cleanup, area/auto-scaling, cla: yes, lgtm, approved

#6583 Fix to-dns network policy in garden namespace for node-local-dns if non-ip based policy engine is used.
  pkg/operation/botanist/component/networkpolicies/global.go
  pkg/operation/botanist/component/networkpolicies/global_test.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved
