Repository gardener/gardener, pull requests merged in 2022-07, with the labels that each got.

#6248 Revert "Allow passing custom REST configuration settings to extension shoot clients (#6113)"
  extensions/pkg/controller/csimigration/reconciler.go
  extensions/pkg/controller/csimigration/reconciler_test.go
  extensions/pkg/controller/healthcheck/config/types.go
  extensions/pkg/controller/healthcheck/controller.go
  extensions/pkg/controller/healthcheck/healthcheck_actuator.go
  extensions/pkg/util/shoot_clients.go
  extensions/pkg/webhook/handler_shootclient.go
  pkg/provider-local/controller/healthcheck/add.go
Labels: kind/bug, size/M, cla: yes, lgtm, approved

#6246 [docs] Fix the key name of the seed provider label added on shoot namespace
  docs/extensions/controlplane-webhooks.md
Labels: kind/bug, size/XS, area/documentation, cla: yes, lgtm, approved

#6239 Move aggregate `istio` monitoring config into component package
  charts/seed-bootstrap/templates/aggregate-prometheus/config.yaml
  charts/seed-bootstrap/values.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/operation/botanist/component/interfaces.go
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/service.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/values.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/service.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/values.yaml
  pkg/operation/botanist/component/istio/ingress_gateway.go
  pkg/operation/botanist/component/istio/istiod.go
  pkg/operation/botanist/component/istio/monitoring.go
  pkg/operation/botanist/component/istio/monitoring_test.go
  pkg/operation/botanist/component/kubeapiserver/networkpolicies.go
  pkg/operation/botanist/component/networkpolicies/global.go
  pkg/operation/botanist/component/types.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/care/seed_health.go
  pkg/operation/care/seed_health_test.go
  pkg/operation/common/types.go
  pkg/operation/seed/components.go
  pkg/operation/seed/seed.go
  pkg/utils/gardener/exposureclass.go
Labels: area/dev-productivity, size/XL, kind/cleanup, cla: yes, lgtm, approved

#6253 Switch controller-manager to logr (5)
  pkg/controllermanager/controller/factory.go
  pkg/controllermanager/controller/managedseedset/managedseedset.go
  pkg/controllermanager/controller/plant/plant_health.go
  pkg/controllermanager/controller/shoot/shoot.go
  pkg/controllermanager/controller/shoot/shoot_conditions_control.go
  pkg/controllermanager/controller/shoot/shoot_hibernation_control.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control_test.go
  pkg/controllermanager/controller/shoot/shoot_quota_control.go
  pkg/controllermanager/controller/shoot/shoot_reference_control.go
  pkg/controllermanager/controller/shoot/shoot_reference_control_test.go
  pkg/controllermanager/controller/shoot/shoot_retry_control.go
  pkg/controllermanager/controller/shoot/shoot_status_label_control.go
  pkg/gardenlet/controller/managedseed/managedseed.go
  pkg/utils/kubernetes/eventhandler.go
  pkg/utils/kubernetes/eventhandler_test.go
  test/integration/controllermanager/shoot/hibernation/hibernation_suite_test.go
  test/integration/controllermanager/shoot/hibernation/hibernation_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
  test/integration/controllermanager/shoot/maintenance/utils_test.go
  test/integration/controllermanager/shoot/retry/retry_suite_test.go
  test/integration/controllermanager/shoot/retry/retry_test.go
  test/integration/gardenlet/shoot/secret/secret_suite_test.go
  test/integration/gardenlet/shoot/secret/secret_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, area/logging, cla: yes, lgtm, approved

#6198 Validate `kubeReserved` and `systemReserved` resources against Node allocatable resources
  example/provider-local/garden/base/cloudprofile.yaml
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, area/quality, size/L, cla: yes, lgtm, approved

#6236 Adapt `provider-local` to use priority class `gardener-system-900`
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/templates/priorityclass.yaml
  charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/gardener/provider-local/internal/shoot-system-components/charts/local-path-provisioner/templates/deployment.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  example/provider-local/garden/base/controller-registration.yaml
Labels: kind/enhancement, size/S, area/control-plane, cla: yes, lgtm, approved

#6256 Clean up migration code in the generic Worker actuator
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
Labels: kind/cleanup, size/S, cla: yes, lgtm, approved

#6225 Move `vpa-exporter` monitoring config into component package
  charts/seed-bootstrap/templates/prometheus/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  pkg/operation/botanist/component/vpa/exporter.go
  pkg/operation/botanist/component/vpa/mock/doc.go
  pkg/operation/botanist/component/vpa/mock/mocks.go
  pkg/operation/botanist/component/vpa/monitoring.go
  pkg/operation/botanist/component/vpa/monitoring_test.go
  pkg/operation/botanist/component/vpa/vpa.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/monitoring_test.go
  pkg/operation/botanist/vpa.go
  pkg/operation/botanist/vpa_test.go
  pkg/operation/seed/seed.go
  pkg/operation/shoot/types.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#6255 Raise minimum Kubernetes cluster version to 1.20 for garden and seeds
  charts/seed-bootstrap/charts/loki/templates/kube-rbac-proxy-ingress.yaml
  charts/seed-bootstrap/templates/aggregate-prometheus/ingress.yaml
  charts/seed-bootstrap/templates/grafana/ingress.yaml
  charts/utils-templates/templates/_versions.tpl
  docs/usage/supported_k8s_versions.md
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/garden/garden.go
  pkg/operation/garden/garden_test.go
  pkg/operation/seed/seed.go
Labels: kind/enhancement, size/XL, area/open-source, cla: yes, lgtm, approved

#6227 Move shoot-specific `vpn-seed-server` monitoring config into component package
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/values.yaml
  pkg/operation/botanist/component/vpnseedserver/mock/mocks.go
  pkg/operation/botanist/component/vpnseedserver/monitoring.go
  pkg/operation/botanist/component/vpnseedserver/monitoring_test.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/monitoring_test.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#6261 Fix headers of hack scripts
  hack/compare-k8s-controllers.sh
  hack/local-development/common/helpers
  hack/usage/shoot-operation
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#6259 Switch `gardenlet` to `logr` (1)
  pkg/extensions/customresources.go
  pkg/gardenlet/controller/backupbucket/backup_bucket.go
  pkg/gardenlet/controller/backupbucket/backup_bucket_actuator.go
  pkg/gardenlet/controller/backupbucket/backup_bucket_controller.go
  pkg/gardenlet/controller/backupbucket/backup_bucket_reconciler.go
  pkg/gardenlet/controller/factory.go
  pkg/utils/flow/flow.go
Labels: kind/enhancement, area/dev-productivity, size/L, area/logging, cla: yes, lgtm, approved

#6264 Switch `gardenlet` to `logr` (3)
  cmd/gardenlet/app/bootstrap.go
  cmd/gardenlet/app/gardenlet.go
  pkg/gardenlet/bootstrap/bootstrap.go
  pkg/gardenlet/bootstrap/bootstrap_test.go
  pkg/gardenlet/bootstrap/certificate/certificate.go
  pkg/gardenlet/bootstrap/certificate/certificate_rotation.go
  pkg/gardenlet/bootstrap/certificate/certificate_rotation_test.go
  pkg/gardenlet/bootstrap/util/util.go
  pkg/gardenlet/bootstrap/util/util_test.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, area/logging, cla: yes, lgtm, approved

#6269 Allow ingress traffic to shoot kube-apiserver from pods within a cilium seed
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/networkpolicies.go
Labels: kind/bug, area/networking, size/S, cla: yes, lgtm, approved

#6245 Add testing strategy and developer guideline
  docs/development/testing.md
Labels: kind/enhancement, area/dev-productivity, size/L, area/testing, cla: yes, lgtm, approved

#6280 Allow to inject special cases
  hack/.ci/set_dependency_version
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#6288 Do not allow containers in privileged mode for the apiserver-proxy PodSecurityPolicy
  charts/shoot-core/components/charts/apiserver-proxy/templates/psp/apiserver-proxy-psp.yaml
Labels: kind/enhancement, area/security, size/XS, cla: yes, lgtm, approved

#6277 Do not exit early when a webhook has `failurePolicy=Ignore`
  pkg/operation/care/webhook_remediation.go
  pkg/operation/care/webhook_remediation_test.go
Labels: kind/bug, area/ops-productivity, size/M, cla: yes, lgtm, approved

#6285 Deploy istio-ingress in all namespace when ExposureClass is used
  pkg/operation/botanist/component/istio/ingress_gateway.go
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/istio/proxy_protocol.go
Labels: kind/bug, size/M, area/networking, cla: yes, lgtm, approved

#6279 add ShootNodeLocalDNSEnabledByDefault admission plugin
  docs/concepts/apiserver_admission_plugins.md
  pkg/apiserver/plugins.go
  plugin/pkg/shoot/nodelocaldns/admission.go
  plugin/pkg/shoot/nodelocaldns/admission_test.go
  plugin/pkg/shoot/nodelocaldns/nodelocaldns_suite_test.go
Labels: kind/enhancement, size/L, area/networking, cla: yes, lgtm, approved

#6284 Check workspace location in generator scripts
  hack/update-codegen.sh
  hack/update-protobuf.sh
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#6266 Switch `gardenlet` to `logr` (5)
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_care_control.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation_control.go
  pkg/gardenlet/controller/extensions/controllerinstallation_control.go
  pkg/gardenlet/controller/extensions/extensions.go
  pkg/gardenlet/controller/extensions/shootstate_control.go
  pkg/gardenlet/controller/extensions/shootstate_control_test.go
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/shootsecret/controller.go
  pkg/gardenlet/controller/shootsecret/reconciler.go
  test/integration/gardenlet/shoot/secret/secret_suite_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, area/logging, ok-to-test, cla: yes, lgtm, approved

#6278 Switch `gardenlet` to `logr` (7)
  .golangci.yaml
  pkg/controllermanager/controller/controllerregistration/seed_control.go
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/seed/lease_control.go
  pkg/gardenlet/controller/seed/lease_control_test.go
  pkg/gardenlet/controller/seed/seed.go
  pkg/gardenlet/controller/seed/seed_care_control.go
  pkg/gardenlet/controller/seed/seed_control.go
  pkg/gardenlet/controller/seed/seed_extension_control.go
  pkg/gardenlet/controller/seed/seed_extension_control_test.go
  pkg/gardenlet/controller/shoot/shoot_care_control.go
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/operation/botanist/component/extensions/dns/dnsentry.go
  pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go
  pkg/operation/botanist/waiter.go
  pkg/operation/garden/garden.go
  pkg/operation/seed/nginxingress.go
  pkg/operation/seed/seed.go
  pkg/operation/seed/seed_test.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, area/logging, cla: yes, lgtm, approved

#6293 [provider-local] Add support for `ManagedSeed`s including e2e tests
  .test-defs/CreateManagedSeed.yaml
  .test-defs/DeleteManagedSeed.yaml
  Makefile
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-extension-provider-local/app/options.go
  cmd/gardenlet/app/gardenlet.go
  docs/README.md
  docs/development/testing.md
  docs/extensions/provider-local.md
  docs/usage/custom-containerd-config.md
  docs/usage/custom-dns-config.md
  example/00-namespace-garden.yaml
  example/gardener-local/controlplane/values.yaml
  example/gardener-local/gardenlet/values.yaml
  example/gardener-local/kind/cluster-skaffold.yaml
  example/gardener-local/kind2/cluster-skaffold.yaml
  example/gardener-local/registry/kustomization.yaml
  example/gardener-local/registry/registry.yaml
  example/provider-local/garden/base/controller-registration.yaml
  example/provider-local/garden/base/project.yaml
  example/provider-local/garden/base/secretbinding.yaml
  example/provider-local/managedseeds/managedseed.yaml
  example/provider-local/managedseeds/shoot-managedseed.yaml
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/initializer_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/templates/scripts/init.tpl.sh
  pkg/operation/seed/seed.go
  pkg/provider-local/controller/infrastructure/actuator.go
  pkg/provider-local/imagevector/images.yaml
  pkg/provider-local/webhook/controlplane/ensurer.go
  pkg/provider-local/webhook/node/add.go
  skaffold.yaml
  test/e2e/common.go
  test/e2e/e2e_suite_test.go
  test/e2e/managedseed/create_delete.go
  test/e2e/shoot/common.go
  test/e2e/shoot/create_and_delete_hibernated.go
  test/e2e/shoot/create_and_delete_unprivileged.go
  test/e2e/shoot/create_hibernate_wakeup_delete.go
  test/e2e/shoot/create_migrate_delete.go
  test/e2e/shoot/create_rotate_delete.go
  test/e2e/shoot/create_update_delete.go
  test/framework/gardener_utils.go
  test/framework/managedseedframework.go
  test/framework/shootcreationframework.go
  test/testmachinery/system/managed_seed_creation/create_suite_test.go
  test/testmachinery/system/managed_seed_creation/create_test.go
  test/testmachinery/system/managed_seed_deletion/delete_suite_test.go
  test/testmachinery/system/managed_seed_deletion/delete_test.go
Labels: kind/enhancement, area/dev-productivity, area/testing, cla: yes, lgtm, approved, size/XXL

#6306 Deploy shoot VPA earlier in the flow
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
Labels: kind/bug, area/dev-productivity, area/usability, size/S, cla: yes, lgtm, approved

#6303 Differentiate the vpa metrics for the seed and control planes
  charts/seed-bootstrap/prometheus-rules/recording-rules.rules.yaml
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved

#6304 Update the supported values in the usage text of the `--leader-election-resource-lock` flag
  extensions/pkg/controller/cmd/options.go
  pkg/resourcemanager/cmd/manager.go
Labels: size/XS, area/documentation, kind/cleanup, cla: yes, lgtm, approved

#6290 Add pre/post reconciliation/deletion hooks for the Worker resource
  extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/genericactuator/interface.go
  pkg/provider-local/controller/worker/machines.go
Labels: kind/enhancement, area/usability, size/M, cla: yes, lgtm, approved

#6315 Cleaned up imports in vpn-seed-server
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
Labels: size/XS, kind/cleanup, area/networking, cla: yes, lgtm, approved

#6300 Update to golang 1.18.4
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
  Dockerfile.local
Labels: kind/enhancement, area/security, area/open-source, size/M, cla: yes, lgtm, approved

#6151 [GEP-19] Monitoring Stack - Migrating to the `prometheus-operator`
  docs/README.md
  docs/proposals/19-migrating-to-prometheus-operator.md
Labels: kind/discussion, size/XL, area/monitoring, cla: yes, lgtm, approved

#6249 Add missing unit tests for the predicates provided by the extensions library
  extensions/pkg/predicate/predicate_test.go
Labels: kind/enhancement, area/dev-productivity, area/quality, area/robustness, area/testing, cla: yes, lgtm, approved

#6314 Fix tools download for aarch64 (arm64) 🐧
  hack/tools.mk
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#6301 Deploy the metrics server to the kind cluster (local development setup)
  Makefile
  example/gardener-local/metrics-server/kustomization.yaml
  example/gardener-local/metrics-server/metrics-deployment_patch.json
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#6320 Update envoy proxy to v1.21.4
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#6321 Update gardenlet's base image to alpine:3.16.0
  Dockerfile
  Dockerfile.local
Labels: kind/enhancement, area/security, size/XS, cla: yes, lgtm, approved

#6329 Add dashboard for monitoring conntrack race failures.
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-details-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-pool-dashboard.json
Labels: kind/enhancement, size/L, area/monitoring, area/networking, cla: yes, lgtm, approved

#6235 Adapt `gardenlet` to use priority class `gardener-system-critical`
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
  charts/gardener/gardenlet/charts/runtime/templates/priorityclass.yaml
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/operation/botanist/component/seedsystem/seedsystem.go
  pkg/operation/botanist/component/seedsystem/seedsystem_test.go
Labels: kind/enhancement, size/S, area/control-plane, cla: yes, lgtm, approved

#6335 Fix a typo in the markdown link syntax
  docs/deployment/getting_started_locally.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#6323 Cleanup deprecated `install-requirements.sh`
  Makefile
  docs/development/local_setup.md
  hack/.ci/prepare_release
  hack/install-requirements.sh
Labels: size/M, kind/cleanup, cla: yes, lgtm, approved

#6334 Do not run loki/telegraf in privileged mode
  charts/seed-bootstrap/charts/loki/templates/statefulset.yaml
Labels: kind/enhancement, area/security, size/XS, cla: yes, lgtm, approved

#6336 Upgrade the blackbox-exporter image to v0.21.1
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6309 Add `skip-health-check` annotation for managed resources
  docs/concepts/resource-manager.md
  pkg/apis/resources/v1alpha1/types.go
  pkg/operation/botanist/component/seedsystem/seedsystem.go
  pkg/operation/botanist/component/seedsystem/seedsystem_test.go
  pkg/resourcemanager/controller/health/health_checker.go
  pkg/resourcemanager/controller/health/health_checker_test.go
  pkg/resourcemanager/controller/health/progressing_reconciler.go
  test/integration/resourcemanager/health/health_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#6338 Update metrics-server to v0.6.1
  charts/images.yaml
  pkg/operation/botanist/component/metricsserver/metrics_server.go
  pkg/operation/botanist/component/metricsserver/metrics_server_test.go
Labels: kind/enhancement, area/security, size/XS, cla: yes, lgtm, approved

#6283 Eliminate `causer` interface in favour of errors.Unwrap
  pkg/utils/errors/errors.go
  pkg/utils/errors/unwrap.go
  pkg/utils/flow/flow.go
  pkg/utils/retry/retry.go
Labels: area/dev-productivity, size/M, kind/technical-debt, kind/cleanup, cla: yes, lgtm, approved

#6339 Fix istio after update to v1.14.1.
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/operation/botanist/component/istio/istiod_test.go
Labels: kind/bug, area/networking, size/S, cla: yes, lgtm, approved

#6343 Fixed typos
  docs/usage/worker_pool_k8s_versions.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#6347 Modified sentence in Shoot Status page
  docs/usage/shoot_status.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#6351 Update v1.24 conformance test coverage
  README.md
Labels: kind/enhancement, size/S, area/compliance, cla: yes, lgtm, approved

#6344 Remove vpnachev from reviewers
  OWNERS_ALIASES
Labels: area/dev-productivity, size/XS, kind/technical-debt, cla: yes, lgtm, approved

#6327 Improve maintenance controller to filter image based on architecture
  pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
  pkg/controllermanager/controller/shoot/shoot_maintenance_control_test.go
  test/framework/worker_utils.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
  test/integration/controllermanager/shoot/maintenance/utils_test.go
Labels: kind/enhancement, area/delivery, size/L, cla: yes, lgtm, approved

#6276 Allow passing custom REST configuration settings to extension shoot clients
  extensions/pkg/apis/config/doc.go
  extensions/pkg/apis/config/types.go
  extensions/pkg/apis/config/v1alpha1/doc.go
  extensions/pkg/apis/config/v1alpha1/types.go
  extensions/pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  extensions/pkg/apis/config/zz_generated.deepcopy.go
  extensions/pkg/apis/doc.go
  extensions/pkg/controller/csimigration/reconciler.go
  extensions/pkg/controller/csimigration/reconciler_test.go
  extensions/pkg/controller/healthcheck/controller.go
  extensions/pkg/controller/healthcheck/healthcheck_actuator.go
  extensions/pkg/util/shoot_clients.go
  extensions/pkg/webhook/handler_shootclient.go
  hack/update-codegen.sh
  pkg/provider-local/controller/healthcheck/add.go
Labels: kind/enhancement, area/performance, size/L, cla: yes, lgtm, approved

#6357 Moved image file
  docs/usage/images/node-local-dns.png
  docs/usage/node-local-dns.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#6353 Consider compatibility matrix of metrics-server
  charts/images.yaml
  pkg/operation/botanist/component/metricsserver/metrics_server.go
  pkg/operation/botanist/component/metricsserver/metrics_server_test.go
Labels: kind/bug, area/quality, kind/regression, size/S, cla: yes, lgtm, approved

#6346 Remove privilege flag from vpn-seed-server
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server_test.go
Labels: size/M, kind/cleanup, area/networking, cla: yes, lgtm, approved

#6356 Bump `nginx-ingress-controller-seed` to `v1.3.0` for `1.22+` seeds
  charts/images.yaml
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
Labels: kind/enhancement, area/open-source, size/M, cla: yes, lgtm, approved

#6363 Fix Shoot Secret contoller that uses wrong client (gardenClient instead of seedClient)
  pkg/gardenlet/controller/shootsecret/reconciler.go
Labels: kind/bug, size/XS, area/quality, kind/regression, cla: yes, lgtm, approved

#6324 Improve default machine image selection for worker pool having machine of CPU architecture `arm64`
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, area/delivery, size/L, cla: yes, lgtm, approved

#6352 Restrict the amount of work being done in a privileged container in the reversed vpn client.
  pkg/operation/botanist/component/vpnshoot/vpnshoot.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot_test.go
Labels: size/L, kind/cleanup, area/networking, cla: yes, lgtm, approved

#6364 Drop custom `predicateutils.Or` function
  extensions/pkg/controller/dnsrecord/controller.go
  pkg/controllerutils/predicate/or.go
  pkg/controllerutils/predicate/or_test.go
Labels: area/dev-productivity, size/L, kind/cleanup, ok-to-test, cla: yes, lgtm, approved

#6368 Fixed broken links
  docs/concepts/controller-manager.md
  docs/deployment/deploy_gardenlet_manually.md
  docs/extensions/provider-local.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#6359 Minor update to the istio dashboards to incorporate upstream changes.
  charts/seed-bootstrap/dashboards/istio/istio-control-plane-dashboard.json
  charts/seed-bootstrap/dashboards/istio/istio-mesh-dashboard.json
Labels: kind/enhancement, size/L, area/monitoring, area/networking, cla: yes, lgtm, approved

#6360 Add documentation and integration test for `CloudProfile` controller
  docs/concepts/controller-manager.md
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/cloudprofile/add.go
  pkg/controllermanager/controller/cloudprofile/reconciler.go
  test/integration/controllermanager/cloudprofile/cloudprofile_suite_test.go
  test/integration/controllermanager/cloudprofile/cloudprofile_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, area/scalability, cla: yes, lgtm, approved

#6372 Fix cluster autoscaler permissions
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler_test.go
Labels: kind/bug, size/L, area/auto-scaling, cla: yes, lgtm, approved

#6380 Use debug log level in all tests
  docs/development/logging.md
  extensions/pkg/controller/status_test.go
  extensions/pkg/terraformer/state_test.go
  extensions/pkg/terraformer/terraform_test.go
  pkg/admissioncontroller/webhooks/admission/auditpolicy/admission_test.go
  pkg/admissioncontroller/webhooks/admission/internaldomainsecret/admission_test.go
  pkg/admissioncontroller/webhooks/admission/kubeconfigsecret/admission_test.go
  pkg/admissioncontroller/webhooks/admission/namespacedeletion/admission_test.go
  pkg/admissioncontroller/webhooks/admission/resourcesize/admission_test.go
  pkg/admissioncontroller/webhooks/admission/seedrestriction/admission_test.go
  pkg/admissioncontroller/webhooks/auth/seed/authorizer_test.go
  pkg/admissioncontroller/webhooks/auth/seed/graph/graph_test.go
  pkg/admissioncontroller/webhooks/auth/seed/handler_test.go
  pkg/resourcemanager/webhook/projectedtokenmount/handler_test.go
  pkg/resourcemanager/webhook/tokeninvalidator/handler_test.go
  pkg/seedadmissioncontroller/webhooks/admission/extensioncrds/admission_test.go
  test/framework/framework_test.go
  test/integration/controllermanager/shoot/hibernation/hibernation_suite_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go
  test/integration/controllermanager/shoot/retry/retry_suite_test.go
  test/integration/envtest/envtest_suite_test.go
  test/integration/extensions/controller/backupbucket/backupbucket_suite_test.go
  test/integration/extensions/webhook/certificates/certificates_suite_test.go
  test/integration/gardenlet/shoot/secret/secret_suite_test.go
  test/integration/resourcemanager/garbagecollector/garbagecollector_suite_test.go
  test/integration/resourcemanager/health/health_suite_test.go
  test/integration/resourcemanager/managedresource/resource_suite_test.go
  test/integration/resourcemanager/podschedulername/podschedulername_suite_test.go
  test/integration/resourcemanager/rootcapublisher/publisher_suite_test.go
  test/integration/resourcemanager/secret/secret_suite_test.go
  test/integration/resourcemanager/tokeninvalidator/tokeninvalidator_suite_test.go
  test/integration/resourcemanager/tokenrequestor/tokenrequestor_suite_test.go
  test/integration/scheduler/scheduler_suite_test.go
  test/integration/seedadmissioncontroller/seedadmission_suite_test.go
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#6384 [ci:component:github.com/gardener/etcd-druid:v0.10.0->v0.11.1]
  charts/images.yaml
  pkg/operation/botanist/component/etcd/bootstrap.go
  pkg/operation/botanist/component/etcd/bootstrap_test.go
Labels: kind/enhancement, size/S, area/control-plane, cla: yes, lgtm, approved

#6381 Remove warning in vpn-shoot by setting the correct file permissions on tls key.
  pkg/operation/botanist/component/vpnshoot/vpnshoot.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot_test.go
Labels: size/XS, kind/cleanup, area/networking, cla: yes, lgtm, approved

#6379 Drop support for the `shoot.gardener.cloud/use-as-seed` annotation
  docs/api-reference/core.md
  docs/usage/managed_seed.md
  docs/usage/shooted_seed.md
  docs/usage/trusted-tls-for-control-planes.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/controller/shoot/seed_registration_control.go
  pkg/gardenlet/controller/shoot/seed_registration_control_test.go
  pkg/gardenlet/controller/shoot/shoot.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operation/operation.go
  pkg/operation/types.go
Labels: kind/api-change, area/quality, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#6389 Allow Shoot deletion even when OS version or K8s version are expired
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, size/L, area/control-plane, cla: yes, lgtm, approved

#6394 Updated topics
  docs/extensions/backupbucket.md
  docs/extensions/backupentry.md
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#6395 Use HA shoot for e2e rotation test
  test/e2e/shoot/create_rotate_delete.go
  test/e2e/shoot/internal/rotation/certificate_authorities.go
Labels: kind/enhancement, size/XS, area/quality, component/gardener, cla: yes, lgtm, approved

#6341 Promote `DisableDNSProviderManagement` to GA
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/values.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-extension-provider-local/app/options.go
  docs/README.md
  docs/deployment/feature_gates.md
  docs/extensions/cluster.md
  docs/extensions/dns.md
  example/20-componentconfig-gardenlet.yaml
  example/provider-local/garden/base/controller-registration.yaml
  extensions/README.md
  pkg/features/features.go
  pkg/gardenlet/controller/managedseed/managedseed_actuator.go
  pkg/gardenlet/controller/managedseed/managedseed_actuator_test.go
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
  pkg/gardenlet/controller/shoot/shoot_control_migrate.go
  pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/addons_test.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/component/extensions/dns/dns.go
  pkg/operation/botanist/component/extensions/dns/dns_suite_test.go
  pkg/operation/botanist/component/extensions/dns/dns_test.go
  pkg/operation/botanist/component/extensions/dns/dnsentry.go
  pkg/operation/botanist/component/extensions/dns/dnsentry_test.go
  pkg/operation/botanist/component/extensions/dns/dnsowner.go
  pkg/operation/botanist/component/extensions/dns/dnsowner_test.go
  pkg/operation/botanist/component/extensions/dns/dnsprovider.go
  pkg/operation/botanist/component/extensions/dns/dnsprovider_test.go
  pkg/operation/botanist/dns.go
  pkg/operation/botanist/dns_test.go
  pkg/operation/botanist/dnsresources.go
  pkg/operation/botanist/dnsresources_test.go
  pkg/operation/seed/nginxingress.go
  pkg/operation/seed/seed.go
  pkg/operation/seed/types.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
  pkg/provider-local/controller/dnsprovider/add.go
  pkg/provider-local/controller/dnsprovider/reconciler.go
  test/framework/shootmigrationtest.go
Labels: area/open-source, kind/cleanup, component/gardener, cla: yes, lgtm, approved, size/XXL

#6390 metrics: etcd_object_counts->apiserver_storage_objects
  charts/seed-monitoring/charts/grafana/dashboards/owners/apiserver-overview.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-api-server-details.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-control-plane-status-dashboard.json
  pkg/operation/botanist/component/kubeapiserver/monitoring.go
  pkg/operation/botanist/component/kubeapiserver/monitoring_test.go
Labels: kind/enhancement, area/monitoring, size/S, ok-to-test, cla: yes, lgtm, approved

#6358 Switch `Bastion` controller to `controller-runtime` and introduce common indexers
  cmd/gardener-controller-manager/app/app.go
  docs/concepts/controller-manager.md
  extensions/pkg/controller/backupbucket/controller.go
  extensions/pkg/controller/backupbucket/mapper.go
  extensions/pkg/controller/backupentry/controller.go
  extensions/pkg/controller/backupentry/mapper.go
  extensions/pkg/controller/containerruntime/controller.go
  extensions/pkg/controller/controlplane/controller.go
  extensions/pkg/controller/dnsrecord/controller.go
  extensions/pkg/controller/extension/controller.go
  extensions/pkg/controller/healthcheck/controller.go
  extensions/pkg/controller/infrastructure/controller.go
  extensions/pkg/controller/network/controller.go
  extensions/pkg/controller/worker/controller.go
  extensions/pkg/controller/worker/mapper.go
  extensions/pkg/controller/worker/mapper_test.go
  pkg/api/indexer/core.go
  pkg/api/indexer/core_test.go
  pkg/api/indexer/indexer_suite_test.go
  pkg/api/indexer/operations.go
  pkg/api/indexer/operations_test.go
  pkg/api/indexer/seedmanagement.go
  pkg/api/indexer/seedmanagement_test.go
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/bastion/add.go
  pkg/controllermanager/controller/bastion/add_test.go
  pkg/controllermanager/controller/bastion/bastion.go
  pkg/controllermanager/controller/bastion/bastion_control.go
  pkg/controllermanager/controller/bastion/reconciler.go
  pkg/controllermanager/controller/bastion/reconciler_test.go
  pkg/controllermanager/controller/factory.go
  pkg/controllerutils/mapper/enqueue_mapped.go
  pkg/controllerutils/mapper/enqueue_mapped_test.go
  pkg/controllerutils/mapper/mapper.go
  pkg/controllerutils/mapper/mapper_test.go
  pkg/gardenlet/controller/factory.go
  pkg/registry/operations/bastion/strategy.go
  pkg/resourcemanager/controller/managedresource/add.go
  pkg/resourcemanager/controller/managedresource/mapper.go
  pkg/resourcemanager/controller/managedresource/mapper_test.go
  pkg/resourcemanager/controller/secret/add.go
  pkg/resourcemanager/controller/secret/mapper.go
  pkg/resourcemanager/controller/secret/mapper_test.go
  test/integration/controllermanager/bastion/bastion_suite_test.go
  test/integration/controllermanager/bastion/bastion_test.go
  third_party/apiserver/pkg/apis/audit/v1alpha1/doc.go
  third_party/apiserver/pkg/apis/audit/v1beta1/doc.go
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#6404 Revert "Use HA shoot for e2e rotation test"
  test/e2e/shoot/create_rotate_delete.go
  test/e2e/shoot/internal/rotation/certificate_authorities.go
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#6371 Use multi-arch image of `nginx`, `curl`, `alpine`, `busybox` and `k8s-example-web-app` for tests
  test/framework/k8s_utils.go
  test/framework/resources/templates/guestbook-app.yaml.tpl
  test/framework/resources/templates/network-nginx-daemonset.yaml.tpl
  test/framework/resources/templates/simple-load-deployment.yaml.tpl
  test/framework/resources/templates/vpntunnel-copy.yaml.tpl
  test/framework/resources/templates/vpntunnel.yaml.tpl
Labels: kind/enhancement, area/delivery, size/S, cla: yes, lgtm, approved

#6403 Add `Disabled` field for `AdmissionPlugin` in `ShootSpec`
  docs/api-reference/core.md
  example/90-shoot.yaml
  extensions/pkg/util/shoot.go
  extensions/pkg/util/shoot_test.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
Labels: kind/enhancement, area/usability, component/gardener, cla: yes, lgtm, approved, size/XXL

#6406 fix: overview of all nodes dashboard
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-pool-dashboard.json
Labels: kind/bug, size/XS, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#6405 Change automated reviewer assignment by prow
  OWNERS_ALIASES
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#6387 Fix time format from PR #6150
  charts/seed-bootstrap/charts/fluent-bit/templates/_helpers.tpl
  pkg/operation/botanist/component/vpnseedserver/logging.go
  pkg/operation/botanist/component/vpnseedserver/logging_test.go
Labels: kind/bug, area/logging, size/S, cla: yes, lgtm, approved

#6408 Prevent panic in gardenlet when shoot namespace doesn't have required project label
  pkg/gardenlet/controller/shoot/shoot_control.go
  pkg/operation/garden/garden.go
Labels: kind/bug, size/S, area/control-plane, cla: yes, lgtm, approved

#6413 Move `IsPSPDisabled` helper function to v1beta1/helper
  extensions/pkg/util/shoot.go
  extensions/pkg/util/shoot_test.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#6414 Updating CRD for DNSEntries to allow specifying routing policy
  pkg/operation/botanist/component/extensions/crds/templates/crd-dnsentry.tpl.yaml
Labels: kind/enhancement, size/M, area/control-plane, cla: yes, lgtm, approved

#6417 Revert "[ci:component:github.com/gardener/etcd-druid:v0.10.0->v0.11.1]"
  charts/images.yaml
  pkg/operation/botanist/component/etcd/bootstrap.go
  pkg/operation/botanist/component/etcd/bootstrap_test.go
Labels: kind/regression, size/S, area/control-plane, cla: yes, lgtm, approved
