Repository gardener/gardener, pull requests merged in 2022-11, with the labels that each got.

#6937 Allow setting `streamingConnectionIdleTimeout` for kubelet
  docs/api-reference/core.md
  example/90-shoot.yaml
  example/provider-local/shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
Labels: kind/enhancement, area/security, area/compliance, cla: yes, lgtm, approved, size/XXL

#6941 Update to go 1.19.3
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#6943 Improve rotation of `ServiceAccount` token signing key
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/secrets_test.go
Labels: kind/enhancement, area/security, size/M, area/robustness, cla: yes, lgtm, approved

#6947 [release-v1.56] Improve rotation of `ServiceAccount` token signing key
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/secrets_test.go
Labels: kind/enhancement, size/M, cla: yes, lgtm, approved

#6950 Update API Core version in docs to core.gardener.cloud/v1beta1
  docs/README.md
Labels: kind/enhancement, size/XS, area/usability, cla: yes, lgtm, approved

#6949 Updated Service Account Manager documentation
  docs/concepts/controller-manager.md
  docs/development/logging.md
  docs/extensions/heartbeat.md
  docs/usage/projects.md
  docs/usage/service-account-manager.md
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#6951 Revert "remove dnsprovider from supported extension kinds" temporarily
  pkg/apis/core/validation/controllerregistration.go
Labels: size/XS, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#6953 Explicitly default seccomp profile for gardenlet
  charts/gardener/gardenlet/templates/deployment.yaml
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
Labels: kind/bug, area/quality, area/robustness, size/S, cla: yes, lgtm, approved

#6954 Inject annotations for GRMs unique `ConfigMap`
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
Labels: kind/bug, area/usability, size/L, cla: yes, lgtm, approved

#6939 `provider-local` now implements deletion of backup buckets and entries
  Makefile
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  example/provider-local/garden/base/controller-registration.yaml
  pkg/provider-local/controller/backupbucket/actuator.go
  pkg/provider-local/controller/backupentry/actuator.go
  pkg/provider-local/controller/backupentry/add.go
Labels: kind/bug, area/dev-productivity, size/M, cla: yes, lgtm, approved

#6930 Remove GA-ed `Shoot{C,S}ARotation` feature gates
  docs/deployment/feature_gates.md
  docs/usage/shoot_credentials_rotation.md
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/controlplane/values.yaml
  example/gardener-local/gardenlet/values.yaml
  hack/local-development/start-apiserver
  pkg/apiserver/features/features.go
  pkg/features/features.go
  pkg/gardenlet/features/features.go
Labels: kind/enhancement, area/security, area/open-source, size/M, cla: yes, lgtm, approved

#6956 Cleanup scheduler.alpha.kubernetes.io/critical-pod annotations
  charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-deployment.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/default-backend-deployment.yaml
  charts/shoot-addons/charts/nginx-ingress/values.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
Labels: area/open-source, kind/cleanup, size/S, cla: yes, lgtm, approved

#6959 Remove GA-ed `DisableDNSProviderManagement` feature gate
  docs/deployment/feature_gates.md
  pkg/features/features.go
  pkg/gardenlet/features/features.go
Labels: kind/cleanup, size/S, cla: yes, lgtm, approved

#6958 Also respect "exotic" node address types when auto-approving kubelet server CSRs
  pkg/resourcemanager/controller/csrapprover/reconciler.go
  test/integration/resourcemanager/csrapprover/csrapprover_test.go
Labels: kind/bug, area/usability, size/M, kind/regression, cla: yes, lgtm, approved

#6960 Drop `.spec.highAvailability` from `Seed` API
  docs/api-reference/core.md
  example/gardener-local/gardenlet/values-kind-ha.yaml
  example/provider-local/seed-kind-ha/local/seed.yaml
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
Labels: area/usability, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#6964 `gardener-resource-manager`s `secret` controller watches the right cluster
  pkg/resourcemanager/controller/add.go
Labels: kind/bug, size/XS, area/usability, kind/regression, cla: yes, lgtm, approved

#6968 Enable heartbeat controller in the common app package
  extensions/pkg/controller/operatingsystemconfig/oscommon/app/app.go
  extensions/pkg/controller/operatingsystemconfig/oscommon/cmd/options.go
Labels: kind/enhancement, area/open-source, size/S, cla: yes, lgtm, approved

#6942 Add configuration to disable forwarding DNS queries for external domains by NodeLocalDNS.
  docs/api-reference/core.md
  docs/usage/custom-dns-config.md
  docs/usage/node-local-dns.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns_test.go
  pkg/operation/botanist/nodelocaldns.go
Labels: kind/enhancement, area/usability, area/networking, cla: yes, lgtm, approved, size/XXL

#6970 fix link to custom coredns configmap
  pkg/operation/botanist/component/coredns/coredns.go
  pkg/operation/botanist/component/coredns/coredns_test.go
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#6910 Add E2e HA tests
  Makefile
  example/gardener-local/gardenlet/values-kind-ha-multi-zone.yaml
  example/gardener-local/gardenlet/values-kind-ha-single-zone.yaml
  example/gardener-local/kind-ha-multi-zone/.gitignore
  example/gardener-local/kind-ha-multi-zone/cluster-local.yaml
  example/gardener-local/kind-ha-multi-zone/cluster-skaffold.yaml
  example/gardener-local/kind-ha-single-zone/.gitignore
  example/gardener-local/kind-ha-single-zone/cluster-local.yaml
  example/gardener-local/kind-ha-single-zone/cluster-skaffold.yaml
  example/provider-local/seed-kind-ha-multi-zone/base/.gitignore
  example/provider-local/seed-kind-ha-multi-zone/base/kustomization.yaml
  example/provider-local/seed-kind-ha-multi-zone/local/kustomization.yaml
  example/provider-local/seed-kind-ha-multi-zone/local/seed.yaml
  example/provider-local/seed-kind-ha-multi-zone/skaffold/kustomization.yaml
  example/provider-local/seed-kind-ha-single-zone/base/.gitignore
  example/provider-local/seed-kind-ha-single-zone/base/kustomization.yaml
  example/provider-local/seed-kind-ha-single-zone/local/kustomization.yaml
  example/provider-local/seed-kind-ha-single-zone/local/seed.yaml
  example/provider-local/seed-kind-ha-single-zone/skaffold/kustomization.yaml
  hack/ci-e2e-kind-ha-multi-zone.sh
  hack/ci-e2e-kind-ha-single-zone.sh
  hack/test-e2e-local.sh
  pkg/provider-local/webhook/controlplane/add.go
  pkg/provider-local/webhook/controlplane/ensurer.go
  skaffold.yaml
  test/e2e/shoot/upgrade_non-ha_to_node.go
  test/e2e/shoot/upgrade_non-ha_to_zone.go
  test/utils/shoots/update/highavailability/upgrade.go
  test/utils/shoots/update/update.go
Labels: size/XL, kind/test, area/high-availability, area/testing, cla: yes, lgtm, approved

#6971 Bump `networking-calico` extension version for local setup
  example/provider-local/garden/base/patch-controller-deployment.yaml
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#6974 Revert "[ci:component:github.com/gardener/etcd-druid:v0.13.3->v0.14.0]"
  charts/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#6696 Fix containerd-monitoring script to not kill containerd-shims
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/templates/scripts/health-monitor.tpl.sh
Labels: kind/bug, size/M, area/os, cla: yes, lgtm, approved, help wanted

#6837 [gardenlet] Switch `BackupBucket` controller to controller-runtime
  cmd/gardenlet/app/app.go
  docs/concepts/gardenlet.md
  pkg/api/indexer/core.go
  pkg/api/indexer/core_test.go
  pkg/apis/core/field_constants.go
  pkg/apis/core/v1beta1/conversions.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/controllerutils/eventhandler.go
  pkg/controllerutils/eventhandler_test.go
  pkg/controllerutils/miscellaneous.go
  pkg/controllerutils/miscellaneous_test.go
  pkg/controllerutils/predicate/predicate.go
  pkg/controllerutils/predicate/predicate_test.go
  pkg/controllerutils/seedfilter.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/backupbucket/add.go
  pkg/gardenlet/controller/backupbucket/add_test.go
  pkg/gardenlet/controller/backupbucket/backup_bucket.go
  pkg/gardenlet/controller/backupbucket/backup_bucket_actuator.go
  pkg/gardenlet/controller/backupbucket/backup_bucket_controller.go
  pkg/gardenlet/controller/backupbucket/backup_bucket_reconciler.go
  pkg/gardenlet/controller/backupbucket/backupbucket_suite_test.go
  pkg/gardenlet/controller/backupbucket/reconciler.go
  pkg/gardenlet/controller/backupentry/backup_entry.go
  pkg/gardenlet/controller/backupentry/backup_entry_controller.go
  pkg/gardenlet/controller/backupentry/backup_entry_migration_controller.go
  pkg/gardenlet/controller/backupentry/backup_entry_reconciler.go
  pkg/gardenlet/controller/factory.go
  pkg/registry/core/backupbucket/strategy.go
  pkg/registry/core/backupentry/storage/storage.go
  pkg/registry/core/backupentry/strategy.go
  pkg/registry/core/backupentry/strategy_test.go
  skaffold.yaml
  test/integration/gardenlet/backupbucket/backupbucket_suite_test.go
  test/integration/gardenlet/backupbucket/backupbucket_test.go
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#6979 Fix gardenlet metrics scraping by seed-prometheus
  charts/gardener/gardenlet/templates/deployment.yaml
Labels: kind/bug, size/XS, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#6984 [release-v1.58] Automated cherry pick of #6979: Fix gardenlet metrics scraping by seed-prometheus
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
Labels: kind/bug, size/XS, ok-to-test, cla: yes, lgtm, approved

#6985 [release-v1.57] Automated cherry pick of #6979: Fix gardenlet metrics scraping by seed-prometheus
  charts/gardener/gardenlet/charts/runtime/templates/deployment.yaml
Labels: kind/bug, size/XS, ok-to-test, cla: yes, lgtm, approved

#6986 Use prow-friendly label commands in `cherry-pick-pull.sh`
  hack/cherry-pick-pull.sh
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#6977 Fix test to use TokenRequest API for garden clusters >=1.24
  test/framework/k8s_utils.go
  test/testmachinery/gardener/security/rbac.go
Labels: kind/bug, size/M, area/testing, cla: yes, lgtm, approved

#6983 Update istio to 1.15.3
  charts/images.yaml
  go.mod
  go.sum
  pkg/operation/botanist/component/istio/charts/istio/istio-crds/templates/crd-all.gen.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/envoy-filter.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/values.yaml
  pkg/operation/botanist/component/istio/istiod.go
  pkg/operation/botanist/component/istio/istiod_test.go
  vendor/istio.io/api/analysis/v1alpha1/message.pb.go
  vendor/istio.io/api/meta/v1alpha1/status.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.gen.json
  vendor/istio.io/api/networking/v1alpha3/destination_rule.pb.go
  vendor/istio.io/api/networking/v1alpha3/destination_rule.proto
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.pb.go
  vendor/istio.io/api/networking/v1alpha3/envoy_filter.proto
  vendor/istio.io/api/networking/v1alpha3/gateway.gen.json
  vendor/istio.io/api/networking/v1alpha3/gateway.pb.go
  vendor/istio.io/api/networking/v1alpha3/gateway.proto
  vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/service_entry.proto
  vendor/istio.io/api/networking/v1alpha3/sidecar.gen.json
  vendor/istio.io/api/networking/v1alpha3/sidecar.pb.go
  vendor/istio.io/api/networking/v1alpha3/sidecar.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service.gen.json
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/networking/v1alpha3/virtual_service_deepcopy.gen.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service_json.gen.go
  vendor/istio.io/api/networking/v1alpha3/workload_entry.pb.go
  vendor/istio.io/api/networking/v1alpha3/workload_group.pb.go
  vendor/istio.io/api/networking/v1beta1/destination_rule.gen.json
  vendor/istio.io/api/networking/v1beta1/destination_rule.pb.go
  vendor/istio.io/api/networking/v1beta1/destination_rule.proto
  vendor/istio.io/api/networking/v1beta1/gateway.gen.json
  vendor/istio.io/api/networking/v1beta1/gateway.pb.go
  vendor/istio.io/api/networking/v1beta1/gateway.proto
  vendor/istio.io/api/networking/v1beta1/proxy_config.gen.json
  vendor/istio.io/api/networking/v1beta1/proxy_config.pb.go
  vendor/istio.io/api/networking/v1beta1/proxy_config.proto
  vendor/istio.io/api/networking/v1beta1/service_entry.pb.go
  vendor/istio.io/api/networking/v1beta1/service_entry.proto
  vendor/istio.io/api/networking/v1beta1/sidecar.gen.json
  vendor/istio.io/api/networking/v1beta1/sidecar.pb.go
  vendor/istio.io/api/networking/v1beta1/sidecar.proto
  vendor/istio.io/api/networking/v1beta1/virtual_service.gen.json
  vendor/istio.io/api/networking/v1beta1/virtual_service.pb.go
  vendor/istio.io/api/networking/v1beta1/virtual_service.proto
  vendor/istio.io/api/networking/v1beta1/virtual_service_deepcopy.gen.go
  vendor/istio.io/api/networking/v1beta1/virtual_service_json.gen.go
  vendor/istio.io/api/networking/v1beta1/workload_entry.pb.go
  vendor/istio.io/api/networking/v1beta1/workload_group.pb.go
  vendor/istio.io/api/type/v1beta1/selector.pb.go
  vendor/modules.txt
Labels: kind/enhancement, area/networking, cla: yes, lgtm, approved, size/XXL

#6980 Remove journald path from the fluent-bit and promtail configuration.
  charts/seed-bootstrap/charts/fluent-bit/templates/_fluent-bit-config.tpl
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/config.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/config_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/templates/promtail-config.tpl.yaml
Labels: kind/enhancement, size/M, area/logging, cla: yes, lgtm, approved

#7000 Fix nil pointer exception error in gardenlet
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#6993 Enhance test framework to handle upgrades to Kubernetes v1.25
  example/provider-local/garden/base/cloudprofile.yaml
  example/provider-local/shoot.yaml
  test/e2e/common.go
  test/e2e/managedseed/create_rotate_delete.go
  test/e2e/shoot/create_and_delete_unprivileged.go
  test/e2e/shoot/create_update_delete.go
  test/framework/shoot_utils.go
  test/utils/shoots/update/update.go
Labels: kind/enhancement, size/M, area/testing, cla: yes, lgtm, approved

#6944 Calculate the monthly average resource usage of the shoot control planes
  charts/seed-bootstrap/aggregate-prometheus-rules/metering.rules.stateful.yaml
  charts/seed-bootstrap/charts/monitoring/templates/config.yaml
  charts/seed-bootstrap/dashboards/gardener-resource-usage-by-container.json
  charts/seed-bootstrap/dashboards/gardener-resource-usage.json
  charts/seed-bootstrap/dashboards/shoot-control-plane-resource-usage-by-owner-container.json
  charts/seed-bootstrap/dashboards/shoot-control-plane-resource-usage-overview.json
  charts/seed-bootstrap/dashboards/shoot-control-plane-resource-usage.json
  charts/seed-bootstrap/prometheus-rules/metering.rules.stateful.sh
  charts/seed-bootstrap/prometheus-rules/metering.rules.stateful.yaml
  charts/seed-bootstrap/prometheus-rules/metering.rules.yaml
  charts/seed-bootstrap/templates/aggregate-prometheus/config.yaml
  charts/seed-bootstrap/templates/prometheus/config.yaml
  charts/seed-bootstrap/templates/prometheus/statefulset.yaml
  charts/seed-bootstrap/values.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/grafana/dashboards/owners/shoot-control-plane-resource-usage-by-owner-container.json
  pkg/operation/botanist/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/operation/botanist/component/kubestatemetrics/monitoring.go
  pkg/operation/botanist/component/kubestatemetrics/monitoring_test.go
  pkg/operation/botanist/component/kubestatemetrics/resources.go
Labels: kind/enhancement, area/monitoring, cla: yes, lgtm, approved, size/XXL

#7002 The blackbox-exporter need not tolerate the NoSchedule/NoExecute taints
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#6973 Removes owner checks from extension controller reconciliations
  extensions/pkg/controller/backupentry/reconciler.go
  extensions/pkg/controller/cluster.go
  extensions/pkg/controller/common/checkerwatchdog.go
  extensions/pkg/controller/common/checkerwatchdog_test.go
  extensions/pkg/controller/common/checkerwatchdogfactory.go
  extensions/pkg/controller/common/checkerwatchdogfactory_test.go
  extensions/pkg/controller/common/mock/doc.go
  extensions/pkg/controller/common/mock/mocks.go
  extensions/pkg/controller/common/ownerchecker.go
  extensions/pkg/controller/common/ownerchecker_test.go
  extensions/pkg/controller/common/ownercheckerfactory.go
  extensions/pkg/controller/common/ownercheckerfactory_test.go
  extensions/pkg/controller/common/watchdogmanager.go
  extensions/pkg/controller/common/watchdogmanager_test.go
  extensions/pkg/controller/containerruntime/reconciler.go
  extensions/pkg/controller/controlplane/reconciler.go
  extensions/pkg/controller/dnsrecord/reconciler.go
  extensions/pkg/controller/extension/reconciler.go
  extensions/pkg/controller/infrastructure/reconciler.go
  extensions/pkg/controller/network/reconciler.go
  extensions/pkg/controller/operatingsystemconfig/reconciler.go
  extensions/pkg/controller/worker/controller.go
  extensions/pkg/controller/worker/reconciler.go
  extensions/pkg/controller/worker/reconciler_test.go
  pkg/extensions/owner.go
  pkg/extensions/owner_test.go
Labels: kind/cleanup, area/control-plane-migration, cla: yes, lgtm, approved, size/XXL

#6976 Reduce duplication and maintenance effort for kind `Cluster` specification and `make` targets
  Makefile
  docs/deployment/content/remote-local-setup.yaml
  docs/deployment/getting_started_locally.md
  docs/development/content/remote-local-setup.yaml
  docs/development/getting_started_locally.md
  docs/development/testing.md
  example/gardener-local/kind-ha-multi-zone/cluster-local.yaml
  example/gardener-local/kind-ha-multi-zone/cluster-skaffold.yaml
  example/gardener-local/kind-ha-single-zone/cluster-local.yaml
  example/gardener-local/kind-ha-single-zone/cluster-skaffold.yaml
  example/gardener-local/kind/cluster-local.yaml
  example/gardener-local/kind/cluster-skaffold.yaml
  example/gardener-local/kind/cluster/Chart.yaml
  example/gardener-local/kind/cluster/templates/_containerd_config_patches.tpl
  example/gardener-local/kind/cluster/templates/_extra_mounts.tpl
  example/gardener-local/kind/cluster/templates/_extra_port_mappings.tpl
  example/gardener-local/kind/cluster/templates/_kubeadm_config_patches.tpl
  example/gardener-local/kind/cluster/templates/cluster.yaml
  example/gardener-local/kind/cluster/values.yaml
  example/gardener-local/kind/ha-multi-zone/.gitignore
  example/gardener-local/kind/ha-multi-zone/values.yaml
  example/gardener-local/kind/ha-single-zone/.gitignore
  example/gardener-local/kind/ha-single-zone/values.yaml
  example/gardener-local/kind/local/.gitignore
  example/gardener-local/kind/local/values.yaml
  example/gardener-local/kind/local2/.gitignore
  example/gardener-local/kind/local2/values.yaml
  example/gardener-local/kind2/cluster-local.yaml
  example/gardener-local/kind2/cluster-skaffold.yaml
  hack/ci-e2e-kind-migration.sh
  hack/ci-e2e-kind.sh
  hack/gardener-down.sh
  hack/kind-down.sh
  hack/kind-up.sh
Labels: area/dev-productivity, kind/technical-debt, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#6998 [GEP-20] Remove support for HA alpha annotation
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/etcd/monitoring_test.go
  pkg/operation/botanist/component/etcd/waiter_test.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  pkg/scheduler/controller/shoot/reconciler_test.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: size/XL, kind/cleanup, area/high-availability, cla: yes, lgtm, approved

#7001 Remove vpa for vpa-recommender on seeds. Avoids VPA self-scaling…
  pkg/operation/botanist/component/vpa/recommender.go
  pkg/operation/botanist/component/vpa/vpa_test.go
Labels: kind/bug, size/M, cla: yes, lgtm, approved

#6991 [gardenlet] Switch `NetworkPolicy` controller to `controller-runtime`
  docs/concepts/gardenlet.md
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/factory.go
  pkg/gardenlet/controller/networkpolicy/add.go
  pkg/gardenlet/controller/networkpolicy/add_test.go
  pkg/gardenlet/controller/networkpolicy/controller.go
  pkg/gardenlet/controller/networkpolicy/endpoints.go
  pkg/gardenlet/controller/networkpolicy/helper/helper.go
  pkg/gardenlet/controller/networkpolicy/helper/helper_test.go
  pkg/gardenlet/controller/networkpolicy/hostnameresolver/resolver.go
  pkg/gardenlet/controller/networkpolicy/hostnameresolver/resolver_test.go
  pkg/gardenlet/controller/networkpolicy/namespaces.go
  pkg/gardenlet/controller/networkpolicy/networkpolicy_suite_test.go
  pkg/gardenlet/controller/networkpolicy/reconciler.go
  test/integration/gardenlet/networkpolicy/networkpolicy_suite_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#6839 [gardenlet] Switch `Bastion` controller to `controller-runtime`
  cmd/gardenlet/app/app.go
  docs/concepts/gardenlet.md
  pkg/controllerutils/seedfilter.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/bastion/add.go
  pkg/gardenlet/controller/bastion/add_test.go
  pkg/gardenlet/controller/bastion/bastion.go
  pkg/gardenlet/controller/bastion/bastion_suite_test.go
  pkg/gardenlet/controller/bastion/reconciler.go
  pkg/gardenlet/controller/factory.go
  test/integration/gardenlet/bastion/bastion_suite_test.go
  test/integration/gardenlet/bastion/bastion_test.go
Labels: kind/enhancement, area/dev-productivity, area/scalability, cla: yes, lgtm, approved, size/XXL

#7012 Fix flaky `ShootState` Extensions Controller Integration Test Suite
  test/integration/gardenlet/shootstate/extensions/extensions_suite_test.go
  test/integration/gardenlet/shootstate/extensions/extensions_test.go
Labels: area/dev-productivity, size/S, kind/flake, cla: yes, lgtm, approved

#6992 Adapt high-availability configuration of shoot control plane components
  pkg/operation/botanist/clusterautoscaler.go
  pkg/operation/botanist/clusterautoscaler_test.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler_test.go
  pkg/operation/botanist/component/clusterautoscaler/monitoring_test.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/operation/botanist/component/kubecontrollermanager/monitoring_test.go
  pkg/operation/botanist/component/kubecontrollermanager/waiter.go
  pkg/operation/botanist/component/kubecontrollermanager/waiter_test.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/component/kubescheduler/monitoring_test.go
  pkg/operation/botanist/kubecontrollermanager.go
  pkg/operation/botanist/kubecontrollermanager_test.go
  pkg/operation/botanist/kubescheduler.go
  pkg/operation/botanist/kubescheduler_test.go
  pkg/operation/operation.go
  pkg/operation/seed/types.go
  pkg/utils/version/version.go
  pkg/utils/version/version_suite_test.go
  pkg/utils/version/version_test.go
  test/utils/shoots/update/highavailability/upgrade.go
Labels: kind/enhancement, size/XL, area/high-availability, cla: yes, lgtm, approved

#7008 Always wait for managed resources to be deleted during deletion flow
  pkg/gardenlet/controller/shoot/shoot_control_delete.go
Labels: kind/bug, size/XS, area/robustness, cla: yes, lgtm, approved

#6989 Adapt high-availability configuration of shoot system components
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/pdb.yaml
  pkg/operation/botanist/component/coredns/coredns.go
  pkg/operation/botanist/component/coredns/coredns_test.go
  pkg/operation/botanist/component/metricsserver/metrics_server.go
  pkg/operation/botanist/component/metricsserver/metrics_server_test.go
Labels: kind/enhancement, size/L, area/high-availability, cla: yes, lgtm, approved

#6982 Adapt high-availability configuration of seed system components
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/templates/rbac.yaml
  charts/gardener/provider-local/extension/values.yaml
  charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/poddisruptionbudget.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  example/provider-local/garden/base/controller-registration.yaml
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/component/dependencywatchdog/bootstrap.go
  pkg/operation/botanist/component/dependencywatchdog/bootstrap_test.go
  pkg/operation/botanist/component/etcd/bootstrap.go
  pkg/operation/botanist/component/etcd/bootstrap_test.go
  pkg/operation/botanist/component/hvpa/hvpa.go
  pkg/operation/botanist/component/hvpa/hvpa_test.go
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller.go
  pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller_test.go
  pkg/operation/botanist/component/seedsystem/seedsystem.go
  pkg/operation/botanist/component/seedsystem/seedsystem_test.go
  pkg/operation/botanist/component/vpa/admissioncontroller.go
  pkg/operation/botanist/component/vpa/general.go
  pkg/operation/botanist/component/vpa/recommender.go
  pkg/operation/botanist/component/vpa/updater.go
  pkg/operation/botanist/component/vpa/vpa.go
  pkg/operation/botanist/component/vpa/vpa_test.go
  pkg/operation/botanist/component/vpnauthzserver/external_authz_server.go
  pkg/operation/botanist/component/vpnauthzserver/external_authz_server_test.go
  pkg/operation/botanist/vpa.go
  pkg/operation/botanist/vpa_test.go
Labels: kind/enhancement, size/XL, area/high-availability, cla: yes, lgtm, approved

#7024 Remove seed zone admission checks
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
  plugin/pkg/seed/validator/admission.go
  plugin/pkg/seed/validator/admission_test.go
  plugin/pkg/utils/miscellaneous.go
  plugin/pkg/utils/miscellaneous_test.go
Labels: size/L, kind/technical-debt, area/high-availability, cla: yes, lgtm, approved

#7022 Minor improvements for the metering dashboards
  charts/seed-bootstrap/dashboards/gardener-resource-usage-by-container.json
  charts/seed-bootstrap/dashboards/shoot-control-plane-resource-usage-by-owner-container.json
  charts/seed-bootstrap/dashboards/shoot-control-plane-resource-usage-overview.json
Labels: kind/enhancement, size/L, area/monitoring, cla: yes, lgtm, approved

#7017 Clean up the stale `kube-addon-manager-vpa` VPA
  pkg/operation/botanist/resource_manager.go
  pkg/operation/botanist/resource_manager_test.go
Labels: area/ops-productivity, kind/cleanup, size/S, cla: yes, lgtm, approved

#7018 Modifies timeout of EtcdCopyBackupsTask
  pkg/operation/botanist/component/etcdcopybackupstask/etcdcopybackupstask.go
  pkg/operation/botanist/etcdcopybackupstask.go
  pkg/operation/botanist/etcdcopybackupstask_test.go
Labels: kind/bug, size/XS, area/control-plane-migration, cla: yes, lgtm, approved

#7025 Deflake `BackupBucket` controller integration tests
  test/integration/gardenlet/backupbucket/backupbucket_suite_test.go
  test/integration/gardenlet/backupbucket/backupbucket_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#7030 Recommend to debug integration tests in KIND_ENV=local mode
  docs/development/testing.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#6988 Removes setting owner checks on `Etcd` resources
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/mock/mocks.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
Labels: size/M, kind/cleanup, area/control-plane-migration, cla: yes, lgtm, approved

#7014 Fix flaky `ControllerInstallation` Required Controller Integration Test Suite
  test/integration/gardenlet/controllerinstallation/required/required_suite_test.go
  test/integration/gardenlet/controllerinstallation/required/required_test.go
Labels: area/dev-productivity, size/S, kind/flake, cla: yes, lgtm, approved

#7020 Fix flaky `Project` controller tests
  test/integration/controllermanager/project/activity/activity_test.go
  test/integration/controllermanager/project/project/project_test.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#7027 Remove status port 15021 from service `istio-ingressgateway`.
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/service.yaml
  pkg/operation/botanist/component/istio/istiod_test.go
Labels: kind/enhancement, area/networking, size/S, cla: yes, lgtm, approved

#7037 Update yq in tools to v4.30.4
  hack/tools.mk
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7042 Increase replicas of nginx ingress controller to 2
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
Labels: kind/bug, size/XS, area/robustness, cla: yes, lgtm, approved

#7045 Allow configuring replicas of `provider-local`
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/values.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  example/provider-local/garden/base/controller-registration.yaml
Labels: kind/bug, area/dev-productivity, kind/regression, size/S, cla: yes, lgtm, approved

#7043 Deflake `Project` controller integration tests
  test/integration/controllermanager/project/activity/activity_suite_test.go
  test/integration/controllermanager/project/activity/activity_test.go
  test/integration/controllermanager/project/project/project_test.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#7040 Fix section filtering of check-apidiff
  hack/check-apidiff.sh
Labels: kind/bug, size/XS, area/open-source, cla: yes, lgtm, approved

#7047 `kube-apiserver` verifies `kubelet`s' server certificates
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
Labels: kind/enhancement, area/security, size/L, cla: yes, lgtm, approved

#7046 Explicitly enable IPv4 forwarding
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go
Labels: size/XS, kind/technical-debt, area/os, cla: yes, lgtm, approved

#7036 Finally drop deprecated `garden.sapcloud.io/role` label
  docs/development/high-availability.md
  docs/development/seed_network_policies.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/utils/kubernetes/health/etcd.go
Labels: area/dev-productivity, size/M, kind/technical-debt, kind/cleanup, cla: yes, lgtm, approved

#7054 Upgrade node_exporter to v1.4.0
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#7055 Upgrade prometheus to v2.40.2
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#7056 Harmonize the remaining finalizer additions of controllers
  pkg/controllermanager/controller/controllerregistration/controllerregistrationfinalizer/add.go
  pkg/controllermanager/controller/controllerregistration/seedfinalizer/add.go
Labels: size/XS, area/quality, kind/technical-debt, cla: yes, lgtm, approved

#7059 Reduce the nginx-ingress-k8s-backend replicas to 1
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
Labels: size/XS, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#7049 Add docs about field removal
  docs/development/changing-the-api.md
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#7048 [operator] Manage `hvpa-controller` and `etcd-druid`
  charts/gardener/operator/templates/_helpers.tpl
  charts/gardener/operator/templates/role.yaml
  charts/gardener/operator/values.yaml
  docs/concepts/operator.md
  docs/deployment/feature_gates.md
  docs/development/priority-classes.md
  example/operator/10-componentconfig.yaml
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/component/deploy.go
  pkg/operation/botanist/component/deploy_test.go
  pkg/operation/botanist/component/etcd/bootstrap.go
  pkg/operation/botanist/component/etcd/bootstrap_test.go
  pkg/operation/botanist/component/hvpa/hvpa.go
  pkg/operation/botanist/component/hvpa/hvpa_test.go
  pkg/operation/botanist/component/shared/etcd_druid.go
  pkg/operation/botanist/component/shared/hvpa.go
  pkg/operation/botanist/kubeapiserverexposure.go
  pkg/operator/apis/.import-restrictions
  pkg/operator/apis/config/types.go
  pkg/operator/apis/config/v1alpha1/defaults.go
  pkg/operator/apis/config/v1alpha1/defaults_test.go
  pkg/operator/apis/config/v1alpha1/types.go
  pkg/operator/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/operator/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/apis/config/zz_generated.deepcopy.go
  pkg/operator/client/scheme.go
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/garden/reconciler.go
  pkg/operator/controller/garden/reconciler_delete.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  pkg/operator/features/features.go
  skaffold-operator.yaml
  test/e2e/operator/garden/create_delete.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden_test.go
Labels: kind/enhancement, area/dev-productivity, area/delivery, cla: yes, lgtm, approved, size/XXL

#7066 Fix fetching zones from the PV spec
  pkg/operation/botanist/namespaces.go
  pkg/operation/botanist/namespaces_test.go
Labels: kind/bug, size/M, area/high-availability, cla: yes, lgtm, approved

#7070 Fix TopologySpreadConstraints for existing clusters
  pkg/utils/kubernetes/highavailability.go
  pkg/utils/kubernetes/highavailability_test.go
  test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_test.go
Labels: kind/bug, kind/regression, size/S, area/high-availability, cla: yes, lgtm, approved

#7072 Remove misleading ExpectWithOffset in e2e test
  test/utils/shoots/update/highavailability/upgrade.go
  test/utils/shoots/update/update.go
Labels: area/dev-productivity, kind/test, size/S, cla: yes, lgtm, approved

#7081 Add missing e2e domain names to be added to /etc/hosts for local setup.
  docs/deployment/content/remote-local-setup.yaml
  docs/deployment/getting_started_locally.md
Labels: kind/enhancement, area/dev-productivity, size/XS, area/documentation, cla: yes, lgtm, approved

#7023 Add multinode etcd dashboard, adapt etcd dashboard and alerts
  charts/seed-monitoring/charts/grafana/dashboards/operators/etcd-backup-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/etcd-cluster-details-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/operators/etcd-dashboard.json
  pkg/operation/botanist/component/etcd/monitoring.go
  pkg/operation/botanist/component/etcd/monitoring_test.go
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_important_multinode_with_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_important_multinode_without_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_important_singlenode_with_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_important_singlenode_without_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_normal_multinode_with_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_normal_multinode_without_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_normal_singlenode_with_backup.yaml
  pkg/operation/botanist/component/etcd/testdata/monitoring_alertingrules_normal_singlenode_without_backup.yaml
Labels: kind/enhancement, area/backup, area/monitoring, area/high-availability, cla: yes, lgtm, approved, size/XXL

#7084 Update metrics-server
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/open-source, cla: yes, lgtm, approved

#7060 Refine high availability documentation
  docs/development/high-availability.md
Labels: kind/enhancement, area/documentation, size/S, area/high-availability, cla: yes, lgtm, approved

#7085 Enhance `PodSecurity` documentation
  docs/usage/pod-security.md
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_and_delete_unprivileged.go
Labels: kind/enhancement, area/documentation, size/S, cla: yes, lgtm, approved

#7083 Fix flaky `BackupBucket` Controller test
  test/integration/extensions/controller/backupbucket/actuator.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#7086 Do not validate `Shoot` DNS domain uniqueness for `DELETE` operations
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, area/ops-productivity, size/M, cla: yes, lgtm, approved

#7065 Improve validations for `BackupBucket`s and `BackupEntry`s
  pkg/gardenlet/controller/backupbucket/reconciler.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/global/resourcereferencemanager/admission_test.go
  plugin/pkg/shoot/managedseed/admission.go
  plugin/pkg/utils/miscellaneous.go
  plugin/pkg/utils/miscellaneous_test.go
  test/integration/gardenlet/backupbucket/backupbucket_suite_test.go
  test/integration/gardenlet/backupbucket/backupbucket_test.go
Labels: kind/bug, size/XL, area/usability, cla: yes, lgtm, approved

#7080 Deflake `Bastion` controller integration test
  pkg/controllermanager/controller/bastion/reconciler.go
  test/integration/controllermanager/bastion/bastion_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#7097 Fix a "many-to-many matching" error case in a recording rule
  charts/seed-bootstrap/prometheus-rules/metering.rules.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#7096 Let the metrics-server tolerate the NoSchedule/NoExecute taints
  pkg/operation/botanist/component/metricsserver/metrics_server.go
  pkg/operation/botanist/component/metricsserver/metrics_server_test.go
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#7102 Fix kubernetes dashboard integration test to fetch the token from the kubeconfig
  test/testmachinery/shoots/applications/shoot_app.go
Labels: kind/bug, size/S, area/testing, cla: yes, lgtm, approved

#7115 Fix logging integration test
  test/testmachinery/shoots/logging/seed_logging_stack.go
Labels: kind/bug, size/XS, area/testing, cla: yes, lgtm, approved

#7118 Improve the logging in the `WaitUntilPodIsRunning` func
  test/framework/k8s_utils.go
Labels: kind/bug, size/XS, area/testing, cla: yes, lgtm, approved
