Repository gardener/gardener, pull requests merged in 2023-06, with the labels that each got.

#8002 Deploy `Etcd` CRDs independent of Etcd bootstrap
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  pkg/component/etcd/bootstrap.go
  pkg/component/etcd/bootstrap_test.go
  pkg/component/etcd/crd.go
  pkg/component/etcd/crd_test.go
  pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks-copy.yaml
  pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcds-copy.yaml
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/garden/reconciler_delete.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden_suite_test.go
  test/integration/operator/garden/garden_test.go
Labels: kind/bug, size/L, area/control-plane, cla: yes, lgtm, approved

#7902 Remediate webhooks affecting lease resource in kube-system namespace with timeoutSeconds more than 4
  docs/usage/shoot_status.md
  pkg/operation/botanist/matchers/matcher.go
  pkg/operation/care/constraints.go
  pkg/operation/care/constraints_test.go
  pkg/operation/care/webhook_remediation.go
  pkg/operation/care/webhook_remediation_test.go
Labels: kind/enhancement, area/ops-productivity, size/L, cla: yes, lgtm, approved

#7995 Validate that only `Secret` and `ConfigMap` can be referenced in `.spec.resources` in `Shoot`s
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_shoot.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/validation/utils.go
  pkg/controllermanager/controller/shoot/reference/add.go
  pkg/controllermanager/controller/shoot/reference/add_test.go
  pkg/controllermanager/controller/shoot/reference/reconciler_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: kind/bug, size/XL, area/control-plane, cla: yes, lgtm, approved

#7998 Minor preparations for reusing some logic related to ETCD encryption
  pkg/component/kubeapiserver/kube_apiserver.go
  pkg/component/kubeapiserver/kube_apiserver_test.go
  pkg/component/kubeapiserver/secrets.go
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  pkg/utils/gardener/secretsrotation/etcd.go
  pkg/utils/gardener/secretsrotation/etcd_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#8016 Export resource YAMLs of `garden` for `pull-gardener-e2e-kind-operator` prow job
  hack/ci-e2e-kind-operator.sh
Labels: size/XS, kind/test, area/robustness, area/testing, cla: yes, lgtm, approved

#8017 Upgrade golangci-lint to v1.52.2
  .golangci.yaml
  cmd/gardener-controller-manager/app/options.go
  cmd/gardener-operator/app/options.go
  cmd/gardener-scheduler/app/options.go
  cmd/gardenlet/app/options.go
  extensions/pkg/controller/dnsrecord/reconciler.go
  extensions/pkg/controller/healthcheck/general/daemonset.go
  extensions/pkg/controller/healthcheck/general/deployment.go
  extensions/pkg/controller/healthcheck/general/managed_resource.go
  extensions/pkg/controller/healthcheck/general/statefulsets.go
  extensions/pkg/controller/healthcheck/worker/nodes.go
  extensions/pkg/webhook/cloudprovider/mutator_test.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator_test.go
  hack/check-charts.sh
  hack/check-imports.sh
  hack/tools.mk
  hack/tools/gomegacheck/go.mod
  hack/tools/gomegacheck/go.sum
  hack/tools/logcheck/go.mod
  hack/tools/logcheck/go.sum
  hack/tools/report-collector/main.go
  pkg/api/extensions/accessor.go
  pkg/apis/core/v1beta1/helper/condition_builder.go
  pkg/client/kubernetes/applier_test.go
  pkg/component/clusteridentity/clusteridentity.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/kubeapiserverexposure/kube_apiserver_sni_test.go
  pkg/component/resourcemanager/resource_manager.go
  pkg/component/vpnauthzserver/external_authz_server.go
  pkg/component/vpnseedserver/vpn_seed_server.go
  pkg/component/vpnseedserver/vpn_seed_server_test.go
  pkg/gardenlet/controller/shoot/care/reconciler_test.go
  pkg/operation/botanist/logging.go
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/waiter.go
  pkg/resourcemanager/controller/managedresource/merger_test.go
  pkg/resourcemanager/predicate/class_changed.go
  pkg/resourcemanager/predicate/condition_status.go
  plugin/pkg/global/resourcereferencemanager/admission.go
  test/framework/shootmigrationtest.go
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#8020 Fix broken links in documentation
  docs/development/component-checklist.md
  docs/development/new-kubernetes-version.md
  docs/development/testing.md
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#8024 Deflake `KubernetesServiceHost` integration test
  test/integration/resourcemanager/kubernetesservicehost/kubernetesservicehost_suite_test.go
  test/integration/resourcemanager/kubernetesservicehost/kubernetesservicehost_test.go
Labels: size/XS, area/testing, kind/flake, cla: yes, lgtm, approved

#8026 Drop usage of deprecated functions
  extensions/pkg/controller/status_test.go
  go.mod
  pkg/client/kubernetes/pods.go
  pkg/component/etcd/monitoring.go
  test/e2e/gardener/shoot/internal/rotation/ssh_keypair.go
  vendor/golang.org/x/text/cases/cases.go
  vendor/golang.org/x/text/cases/context.go
  vendor/golang.org/x/text/cases/fold.go
  vendor/golang.org/x/text/cases/icu.go
  vendor/golang.org/x/text/cases/info.go
  vendor/golang.org/x/text/cases/map.go
  vendor/golang.org/x/text/cases/tables10.0.0.go
  vendor/golang.org/x/text/cases/tables11.0.0.go
  vendor/golang.org/x/text/cases/tables12.0.0.go
  vendor/golang.org/x/text/cases/tables13.0.0.go
  vendor/golang.org/x/text/cases/tables9.0.0.go
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/match.go
  vendor/modules.txt
Labels: area/open-source, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#8029 Update kube-rbac-proxy image to v0.14.2
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#8025 Introduce `core.gardener.cloud/v1beta1.InternalSecret` API
  docs/api-reference/core.md
  docs/concepts/apiserver.md
  example/11-internal-secret.yaml
  pkg/api/indexer/gardener_core.go
  pkg/apis/core/field_constants.go
  pkg/apis/core/register.go
  pkg/apis/core/types_internalsecret.go
  pkg/apis/core/v1beta1/conversions.go
  pkg/apis/core/v1beta1/conversions_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/register.go
  pkg/apis/core/v1beta1/types_internalsecret.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/internalsecret.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/client/core/clientset/internalversion/typed/core/internalversion/core_client.go
  pkg/client/core/clientset/internalversion/typed/core/internalversion/fake/fake_core_client.go
  pkg/client/core/clientset/internalversion/typed/core/internalversion/fake/fake_internalsecret.go
  pkg/client/core/clientset/internalversion/typed/core/internalversion/generated_expansion.go
  pkg/client/core/clientset/internalversion/typed/core/internalversion/internalsecret.go
  pkg/client/core/clientset/versioned/typed/core/v1beta1/core_client.go
  pkg/client/core/clientset/versioned/typed/core/v1beta1/fake/fake_core_client.go
  pkg/client/core/clientset/versioned/typed/core/v1beta1/fake/fake_internalsecret.go
  pkg/client/core/clientset/versioned/typed/core/v1beta1/generated_expansion.go
  pkg/client/core/clientset/versioned/typed/core/v1beta1/internalsecret.go
  pkg/client/core/clientset/versioned/typed/core/v1beta1/mock/mocks.go
  pkg/client/core/informers/externalversions/core/v1beta1/interface.go
  pkg/client/core/informers/externalversions/core/v1beta1/internalsecret.go
  pkg/client/core/informers/externalversions/generic.go
  pkg/client/core/informers/internalversion/core/internalversion/interface.go
  pkg/client/core/informers/internalversion/core/internalversion/internalsecret.go
  pkg/client/core/informers/internalversion/generic.go
  pkg/client/core/listers/core/internalversion/expansion_generated.go
  pkg/client/core/listers/core/internalversion/internalsecret.go
  pkg/client/core/listers/core/v1beta1/expansion_generated.go
  pkg/client/core/listers/core/v1beta1/internalsecret.go
  pkg/openapi/openapi_generated.go
  pkg/registry/core/internalsecret/storage/storage.go
  pkg/registry/core/internalsecret/storage/tableconvertor.go
  pkg/registry/core/internalsecret/strategy.go
  pkg/registry/core/rest/storage_core.go
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, area/usability, cla: yes, lgtm, approved, size/XXL

#8031 Updates etcd-druid crds and dependency
  go.mod
  go.sum
  pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcds.yaml
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/types_etcd.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/lease.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/statefulset.go
  vendor/modules.txt
Labels: kind/enhancement, size/M, cla: yes, lgtm, approved

#8008 Maintain feature gates
  charts/seed-bootstrap/charts/monitoring/templates/networkpolicy.yaml
  charts/seed-bootstrap/charts/monitoring/values.yaml
  cmd/gardenlet/app/app.go
  docs/api-reference/core.md
  docs/deployment/feature_gates.md
  docs/usage/control_plane_migration.md
  docs/usage/network_policies.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apiserver/features/features.go
  pkg/component/kubeapiserverexposure/kube_apiserver_service.go
  pkg/component/kubeapiserverexposure/kube_apiserver_service_test.go
  pkg/component/resourcemanager/resource_manager.go
  pkg/component/resourcemanager/resource_manager_test.go
  pkg/component/shared/resourcemanager.go
  pkg/controller/networkpolicy/reconciler.go
  pkg/features/features.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/shoot/shoot/helper/helper_test.go
  pkg/gardenlet/features/features.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/kubeapiserverexposure.go
  pkg/operator/controller/garden/components.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: kind/enhancement, area/dev-productivity, area/open-source, size/L, cla: yes, lgtm, approved

#8028 Set references.InjectAnnotations to consider also image pull secrets
  pkg/resourcemanager/controller/garbagecollector/references/references.go
  pkg/resourcemanager/controller/garbagecollector/references/references_test.go
Labels: kind/bug, area/dev-productivity, area/usability, size/S, cla: yes, lgtm, approved

#8022 Cleanup TODO
  pkg/component/etcd/bootstrap.go
  pkg/component/etcd/bootstrap_test.go
  pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks-copy.yaml
  pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcds-copy.yaml
Labels: size/M, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#8037 Update to Go `1.20.5`
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#8035 Increase workers for `NetworkPolicy` controller
  pkg/component/resourcemanager/resource_manager.go
  pkg/component/resourcemanager/resource_manager_test.go
  pkg/component/shared/resourcemanager.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults_test.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/utils/kubernetes/managedseed.go
Labels: kind/enhancement, area/performance, size/M, cla: yes, lgtm, approved

#8040 Improve `test-e2e-local` script
  hack/test-e2e-local.sh
Labels: kind/enhancement, size/M, area/testing, cla: yes, lgtm, approved

#8034 Enhance Webhook remediator
  pkg/operation/botanist/matchers/matcher.go
  pkg/operation/care/constraints_test.go
  pkg/operation/care/webhook_remediation_test.go
Labels: kind/enhancement, area/usability, size/M, cla: yes, lgtm, approved

#8044 [release-v1.72] Increase workers for `NetworkPolicy` controller
  pkg/component/resourcemanager/resource_manager.go
  pkg/component/resourcemanager/resource_manager_test.go
  pkg/component/shared/resourcemanager.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults_test.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/utils/kubernetes/managedseed.go
Labels: kind/enhancement, area/performance, size/M, cla: yes, lgtm, approved

#8009 [`provider-local`] Drop `MachineClass` Helm chart
  charts/gardener/provider-local/internal/machineclass/Chart.yaml
  charts/gardener/provider-local/internal/machineclass/templates/machineclass.yaml
  charts/gardener/provider-local/internal/machineclass/values.yaml
  pkg/provider-local/controller/worker/actuator.go
  pkg/provider-local/controller/worker/machines.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#8042 Fix zone affinity merge
  pkg/resourcemanager/webhook/highavailabilityconfig/handler.go
  test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_test.go
Labels: kind/bug, size/L, area/high-availability, cla: yes, lgtm, approved

#8051 [release-v1.70] Fix zone affinity merge
  pkg/resourcemanager/webhook/highavailabilityconfig/handler.go
  test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_test.go
Labels: kind/bug, size/L, area/high-availability, cla: yes, lgtm, approved

#7994 Cleanup Shoot provider label from the secret if there are no secretbindings referring it
  pkg/controllermanager/controller/secretbinding/reconciler.go
  pkg/controllermanager/controller/secretbinding/reconciler_test.go
Labels: kind/bug, size/L, area/control-plane, cla: yes, lgtm, approved

#8048 Update kyverno to `v1.9.5`
  example/provider-extensions/kyverno/kustomization.yaml
  example/provider-extensions/seed/configure-seed.sh
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#8052 [release-v1.72] Prevent sending empty patches in `NetworkPolicy` controller
  pkg/resourcemanager/controller/networkpolicy/reconciler.go
Labels: kind/enhancement, area/performance, area/cost, size/M, cla: yes, lgtm, approved

#8011 Populate `gardenlet` feature gates to extensions when installing
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#8010 Prepare for removal of `cluster-autoscaler` scaling in generic `Worker` actuator
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operation/botanist/clusterautoscaler.go
  pkg/operation/botanist/clusterautoscaler_test.go
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#8015 `gardenlet`'s `Seed` controller deploys MCM-related `CustomResourceDefinition`s
  cmd/gardener-extension-provider-local/app/app.go
  extensions/pkg/controller/worker/machine_crds.go
  extensions/pkg/controller/worker/options.go
  pkg/component/extensions/crds/crds.go
  pkg/component/extensions/crds/crds_test.go
  pkg/component/machinecontrollermanager/crd.go
  pkg/component/machinecontrollermanager/crd_test.go
  pkg/component/machinecontrollermanager/templates/crd-alicloudmachineclasses.tpl.yaml
  pkg/component/machinecontrollermanager/templates/crd-awsmachineclasses.tpl.yaml
  pkg/component/machinecontrollermanager/templates/crd-azuremachineclasses.tpl.yaml
  pkg/component/machinecontrollermanager/templates/crd-gcpmachineclasses.tpl.yaml
  pkg/component/machinecontrollermanager/templates/crd-machineclasses.tpl.yaml
  pkg/component/machinecontrollermanager/templates/crd-machinedeployments.tpl.yaml
  pkg/component/machinecontrollermanager/templates/crd-machines.tpl.yaml
  pkg/component/machinecontrollermanager/templates/crd-machinesets.tpl.yaml
  pkg/component/machinecontrollermanager/templates/crd-openstackmachineclasses.tpl.yaml
  pkg/component/machinecontrollermanager/templates/crd-packetmachineclasses.tpl.yaml
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  skaffold.yaml
  test/integration/gardenlet/seed/seed/seed_suite_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/gardenlet/seed/seed/testdata/crd-verticalpodautoscalers.yaml
  test/integration/resourcemanager/crddeletionprotection/crddeletionprotection_test.go
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#8043 Prevent sending empty patches in `NetworkPolicy` controller
  cmd/gardenlet/app/app.go
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  pkg/component/clusterautoscaler/cluster_autoscaler_test.go
  pkg/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/component/kubescheduler/kube_scheduler_test.go
  pkg/component/resourcemanager/resource_manager_test.go
  pkg/controllerutils/patch.go
  pkg/controllerutils/patch_test.go
  pkg/resourcemanager/controller/networkpolicy/reconciler.go
  pkg/utils/gardener/shoot.go
Labels: kind/enhancement, area/performance, area/cost, size/L, cla: yes, lgtm, approved

#8055 [release-v1.70] Increase workers for `NetworkPolicy` controller
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/resource_manager.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults_test.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/utils/kubernetes/managedseed.go
Labels: kind/enhancement, area/performance, size/M, cla: yes, lgtm, approved

#8018 Adapt `gardenlet` to take over management of `machine-controller-manager` deployment
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  charts/images.yaml
  charts/seed-monitoring/charts/plutono/dashboards/owners/machine-controller-manager/mcm-dashboard.json
  charts/seed-monitoring/charts/plutono/templates/_helpers.tpl
  charts/seed-monitoring/charts/plutono/values.yaml
  docs/deployment/feature_gates.md
  docs/extensions/conventions.md
  docs/extensions/logging-and-monitoring.md
  docs/extensions/worker.md
  extensions/pkg/controller/cmd/options.go
  extensions/pkg/controller/worker/genericactuator/actuator.go
  extensions/pkg/controller/worker/genericactuator/actuator_migrate.go
  extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  extensions/pkg/controller/worker/genericactuator/machine_controller_manager.go
  extensions/pkg/webhook/controlplane/genericmutator/mock/mocks.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator_test.go
  extensions/pkg/webhook/controlplane/genericmutator/noopensurer.go
  extensions/pkg/webhook/utils.go
  pkg/component/machinecontrollermanager/machine_controller_manager.go
  pkg/component/machinecontrollermanager/provider.go
  pkg/component/machinecontrollermanager/provider_test.go
  pkg/features/features.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/features/features.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/machinecontrollermanager.go
  pkg/operation/botanist/machinecontrollermanager_test.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/shoot/types.go
  pkg/utils/images/images.go
  skaffold.yaml
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#8057 Add missing test suite for `pkg/component/extensions`
  pkg/component/extensions/extensions_suite_test.go
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#8003 Add feature gate `DisableScalingClassesForShoots` to assign Shoot `kube-apiserver` resource requests statically instead of using a ScalingClass
  docs/deployment/feature_gates.md
  pkg/features/features.go
  pkg/gardenlet/features/features.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: kind/enhancement, size/L, area/control-plane, area/auto-scaling, cla: yes, lgtm, approved

#8064 Deprecate `spec.secretRef` field in Seed API
  docs/api-reference/core.md
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/openapi/openapi_generated.go
Labels: kind/enhancement, size/S, area/control-plane, cla: yes, lgtm, approved

#8059 Don't kill terraform pod on context cancelation
  extensions/pkg/terraformer/terraformer.go
Labels: kind/bug, size/S, area/control-plane, cla: yes, lgtm, approved

#8072 Add CVE Responsibles for Monitoring images
  charts/images.yaml
Labels: size/M, area/monitoring, kind/task, cla: yes, lgtm, approved

#8056 Move machine/node-specific health checks into `gardenlet`'s shoot care controller
  extensions/pkg/controller/healthcheck/worker/helpers.go
  extensions/pkg/controller/healthcheck/worker/helpers_test.go
  extensions/pkg/controller/healthcheck/worker/nodes.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  pkg/operation/care/checker.go
  pkg/operation/care/checker_test.go
  pkg/operation/care/health.go
  pkg/operation/care/health_check_test.go
  pkg/utils/kubernetes/health/machinedeployment.go
  pkg/utils/kubernetes/health/machinedeployment_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#8069 Fix `fluent-bit` service
  pkg/component/logging/fluentoperator/custom_resources_test.go
  pkg/component/logging/fluentoperator/customresources/fluent_bit.go
  pkg/component/logging/fluentoperator/customresources/fluent_bit_test.go
  pkg/component/logging/fluentoperator/fluent_operator.go
  pkg/component/shared/fluent_operator_custom_resources.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
Labels: kind/bug, area/security, area/monitoring, size/S, cla: yes, lgtm, approved

#8012 📖 [GEP-22] Improved Usage of the `ShootState` API
  docs/README.md
  docs/proposals/22-improved-usage-of-shootstate-api.md
Labels: kind/enhancement, size/L, area/scalability, cla: yes, lgtm, approved

#8019 [`provider-local`] Adapt to new `MachineControllerManagerDeployment` feature gate
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/values.yaml
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-extension-provider-local/app/options.go
  docs/extensions/provider-local.md
  example/gardener-local/gardenlet/values.yaml
  example/provider-local/garden/base/controller-registration.yaml
  pkg/component/machinecontrollermanager/machine_controller_manager.go
  pkg/component/machinecontrollermanager/machine_controller_manager_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/operation/botanist/machinecontrollermanager.go
  pkg/operation/botanist/machinecontrollermanager_test.go
  pkg/provider-local/controller/healthcheck/add.go
  pkg/provider-local/controller/worker/actuator.go
  pkg/provider-local/controller/worker/add.go
  pkg/provider-local/webhook/controlplane/add.go
  pkg/provider-local/webhook/controlplane/ensurer.go
  pkg/provider-local/webhook/machinecontrollermanager/add.go
  pkg/provider-local/webhook/machinecontrollermanager/mutator.go
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#8039 Cleanup the seed secret when `.spec.secretRef` is unset in the seed template in the `ManagedSeed`
  .golangci.yaml
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_managedseed.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
  pkg/apis/seedmanagement/v1alpha1/constants/types_constants.go
  pkg/gardenlet/controller/managedseed/actuator.go
  pkg/gardenlet/controller/managedseed/add.go
  pkg/resourcemanager/controller/health/utils/controller.go
  pkg/resourcemanager/controller/managedresource/reconciler.go
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
  skaffold.yaml
  test/integration/gardenlet/managedseed/managedseed_test.go
Labels: kind/enhancement, size/L, cla: yes, lgtm, approved

#8076 Simplify `NetworkPolicy` configuration for webhook servers
  charts/gardener/provider-local/extension/templates/service.yaml
  docs/extensions/shoot-webhooks.md
  docs/usage/network_policies.md
  example/provider-local/garden/base/controller-registration.yaml
  extensions/pkg/webhook/shoot/networkpolicy.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/kubeapiserver/deployment.go
  pkg/component/kubeapiserver/kube_apiserver_test.go
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved

#8078 Add note about encrypting `internalsecrets.core.gardener.cloud` in etcd
  charts/gardener/controlplane/values.yaml
  docs/concepts/apiserver.md
Labels: kind/enhancement, area/security, size/XS, cla: yes, lgtm, approved

#8079 Deploy namespace during shoot deletion
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
Labels: kind/enhancement, size/S, area/high-availability, area/control-plane, cla: yes, lgtm, approved

#8060 Clean up TODO
  pkg/operator/controller/networkpolicyregistrar/add.go
  pkg/operator/controller/networkpolicyregistrar/add_test.go
Labels: size/L, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#8081 bump up plutono to v7.5.22
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, area/logging, cla: yes, lgtm, approved

#8086 Fix broken links in documentation
  docs/development/component-checklist.md
Labels: kind/enhancement, area/documentation, size/S, cla: yes, lgtm, approved

#8047 Adapt kind cluster's registry configuration to the new way of configuring registry mirrors in containerd
  example/gardener-local/kind/cluster/templates/_containerd_config_patches.tpl
  example/gardener-local/kind/cluster/templates/cluster.yaml
  hack/kind-up.sh
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#8067 Deprecate `node-local-dns` annotations
  pkg/api/core/shoot/warnings.go
  pkg/api/core/shoot/warnings_test.go
  pkg/apis/core/v1beta1/constants/types_constants.go
Labels: size/M, kind/cleanup, area/networking, cla: yes, lgtm, approved

#8085 Increased default reconciliation timeout to 3 minutes.
  pkg/controllerutils/miscellaneous.go
Labels: kind/enhancement, size/XS, area/robustness, cla: yes, lgtm, approved

#8093 Clarify contract when extension resources are migrated
  docs/extensions/migration.md
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
Labels: kind/enhancement, area/usability, size/M, cla: yes, lgtm, approved

#7951 Prepare for the removal of the `ownerChecks` field
  docs/api-reference/core.md
  docs/usage/seed_settings.md
  example/50-seed.yaml
  example/gardener-local/gardenlet/values.yaml
  example/provider-extensions/gardenlet/values.yaml.tmpl
  example/provider-local/managedseeds/managedseed.yaml
  example/provider-local/seed-kind-ha-multi-zone/local/seed.yaml
  example/provider-local/seed-kind-ha-single-zone/local/seed.yaml
  example/provider-local/seed-kind/local/seed.yaml
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
  pkg/gardenlet/apis/config/helper/helpers.go
  pkg/gardenlet/apis/config/helper/helpers_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/dnsrecord.go
  pkg/operation/botanist/dnsrecord_test.go
  pkg/operation/botanist/dnsresources.go
  pkg/operation/botanist/dnsresources_test.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
  pkg/registry/core/seed/strategy.go
  pkg/registry/core/seed/strategy_test.go
  test/e2e/gardener/managedseed/create_rotate_delete.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: size/XL, kind/cleanup, area/control-plane-migration, cla: yes, lgtm, approved, lifecycle/frozen

#8083 Drop GA-ed `HAControlPlanes` and `FullNetworkPoliciesInRuntimeCluster` feature gates
  cmd/gardenlet/app/app.go
  docs/deployment/feature_gates.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apiserver/features/features.go
  pkg/controller/networkpolicy/add_test.go
  pkg/controller/networkpolicy/reconciler.go
  pkg/features/features.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/features/features.go
  pkg/operator/features/features.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, area/dev-productivity, area/open-source, size/L, cla: yes, lgtm, approved

#8097 Update images.yaml - set logging responsibles
  charts/images.yaml
Labels: kind/enhancement, size/M, area/logging, cla: yes, lgtm, approved

#8095 Add missing test suite for `pkg/component/monitoring`
  pkg/component/monitoring/monitoring_suite_test.go
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#8084 🧹 Cleanup a few `TODO`s
  cmd/gardener-extension-provider-local/app/app.go
  pkg/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/monitoring.go
  pkg/operator/controller/garden/reconciler_delete.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  pkg/registry/core/backupbucket/strategy.go
  pkg/registry/operations/bastion/strategy.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#8098 Drop TODO
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: area/dev-productivity, size/M, kind/cleanup, cla: yes, lgtm, approved

#8082 [GEP-22] Change control plane migration flow to fetch relevant shoot state ad-hoc and push it to the `ShootState` resource
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  pkg/component/kubeapiserver/secrets.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operation/botanist/shootstate.go
  pkg/operation/botanist/shootstate_test.go
  pkg/operation/operation.go
  pkg/operation/operation_test.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
  pkg/operation/types.go
  pkg/utils/gardener/shootstate/shootstate.go
  pkg/utils/gardener/shootstate/shootstate_suite_test.go
  pkg/utils/gardener/shootstate/shootstate_test.go
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  skaffold.yaml
Labels: kind/enhancement, area/scalability, cla: yes, lgtm, approved, size/XXL

#8089 Removed broken link
  docs/extensions/logging-and-monitoring.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#8071 Do not recreate VPA for `kube-proxy` when Kubernetes patch version changes
  pkg/component/kubeproxy/kube_proxy.go
  pkg/component/kubeproxy/kube_proxy_test.go
  pkg/component/kubeproxy/resources.go
  pkg/operation/botanist/kubeproxy.go
  pkg/operation/botanist/kubeproxy_test.go
Labels: kind/enhancement, size/XL, area/scalability, cla: yes, lgtm, approved

#8102 [release-v1.71] Automated cherry pick of #8081: bump up plutono to v7.5.22
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, area/logging, cla: yes, lgtm, approved

#8101 [release-v1.72] Automated cherry pick of #8081: bump up plutono to v7.5.22
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, area/logging, cla: yes, lgtm, approved

#8088 Sync client CA to `InternalSecret` and use it in `shoots/adminkubeconfig` subresource
  charts/gardener/controlplane/charts/application/templates/validatingwebhook-admission-controller.yaml
  cmd/gardener-apiserver/app/gardener_apiserver.go
  cmd/gardenlet/app/app.go
  docs/concepts/apiserver.md
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler.go
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler_test.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer_test.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_shoot.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
  pkg/admissioncontroller/webhook/auth/seed/graph/vertices.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apiserver/apiserver.go
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/secrets_test.go
  pkg/registry/core/rest/storage_core.go
  pkg/registry/core/shoot/storage/admin_kubeconfig.go
  pkg/registry/core/shoot/storage/admin_kubeconfig_test.go
  pkg/registry/core/shoot/storage/storage.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
Labels: kind/enhancement, area/dev-productivity, area/usability, cla: yes, lgtm, approved, size/XXL

#8032 Make `tokenrequestor` controller reusable and add it to gardenlet
  charts/gardener/gardenlet/templates/_helpers.tpl
  charts/gardener/gardenlet/values.yaml
  cmd/gardenlet/app/app.go
  docs/concepts/gardenlet.md
  docs/concepts/resource-manager.md
  docs/deployment/gardenlet_api_access.md
  example/20-componentconfig-gardenlet.yaml
  example/resource-manager/30-secret-tokenrequestor.yaml
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler.go
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler_test.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer_test.go
  pkg/apis/resources/v1alpha1/types.go
  pkg/component/clusterautoscaler/cluster_autoscaler_test.go
  pkg/component/dependencywatchdog/access_test.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/gardeneraccess/access_test.go
  pkg/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/component/kubescheduler/kube_scheduler_test.go
  pkg/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/component/machinecontrollermanager/machine_controller_manager_test.go
  pkg/component/resourcemanager/resource_manager_test.go
  pkg/component/vpa/vpa_test.go
  pkg/controller/tokenrequestor/add.go
  pkg/controller/tokenrequestor/add_test.go
  pkg/controller/tokenrequestor/reconciler.go
  pkg/controller/tokenrequestor/reconciler_test.go
  pkg/controller/tokenrequestor/tokenrequestor_suite_test.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/resourcemanager/controller/add.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/e2e/gardener/e2e_suite_test.go
  test/e2e/gardener/project/common.go
  test/e2e/gardener/project/project_roles.go
  test/e2e/gardener/seed/common.go
  test/e2e/gardener/seed/garden_access.go
  test/integration/resourcemanager/tokenrequestor/tokenrequestor_suite_test.go
Labels: kind/enhancement, area/security, size/XL, area/usability, cla: yes, lgtm, approved

#8103 Fix flaky gardener operator tests caused by concurrent writes to garden object.
  pkg/operator/controller/garden/components.go
Labels: area/dev-productivity, size/XS, kind/flake, cla: yes, lgtm, approved

#8106 deploy Controlplane config chart on deletion
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#8111 Bump up vali version to v2.2.6
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#8115 Skip reading zone for non-existing PVs
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/operation/botanist/namespaces.go
  pkg/operation/botanist/namespaces_test.go
Labels: kind/enhancement, size/L, area/control-plane, cla: yes, lgtm, approved

#8070 Improve some map initializations
  extensions/pkg/controller/controlplane/utils.go
  pkg/admissioncontroller/seedidentity/identity.go
  pkg/admissioncontroller/webhook/auth/seed/attributes.go
  pkg/apis/core/v1beta1/conversions.go
  pkg/apis/core/validation/project.go
  pkg/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go
  pkg/controllermanager/controller/certificatesigningrequest/reconciler.go
  pkg/operation/operation.go
  pkg/resourcemanager/controller/managedresource/merger.go
  pkg/resourcemanager/controller/networkpolicy/reconciler.go
  pkg/utils/imagevector/imagevector.go
  pkg/utils/miscellaneous.go
  pkg/utils/secrets/basic_auth.go
  test/framework/shootmigrationtest.go
  test/utils/shoots/update/update.go
Labels: kind/enhancement, area/quality, size/M, cla: yes, lgtm, approved

#8112 [GEP-22] Perform regular state backups for `Shoot`s running on unmanaged `Seed`s
  charts/gardener/gardenlet/templates/_helpers.tpl
  charts/gardener/gardenlet/values.yaml
  docs/concepts/gardenlet.md
  example/20-componentconfig-gardenlet.yaml
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/gardenlet/controller/shoot/add.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/gardenlet/controller/shoot/state/add.go
  pkg/gardenlet/controller/shoot/state/add_test.go
  pkg/gardenlet/controller/shoot/state/reconciler.go
  pkg/gardenlet/controller/shoot/state/state_suite_test.go
  pkg/utils/gardener/shootstate/shootstate.go
  pkg/utils/gardener/shootstate/shootstate_test.go
  skaffold.yaml
  test/integration/gardenlet/shoot/state/state_suite_test.go
  test/integration/gardenlet/shoot/state/state_test.go
Labels: kind/enhancement, area/scalability, cla: yes, lgtm, approved, size/XXL

#8126 Allow deletion of shoot clusters with incorrect networking settings.
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, size/M, area/networking, cla: yes, lgtm, approved

#8132 Fix namespace selector
  charts/gardener/provider-local/extension/templates/service.yaml
  example/provider-local/garden/base/controller-registration.yaml
Labels: kind/bug, size/XS, cla: yes, lgtm, approved

#8096 Reuse `nginx-ingress` component for Shoot addon
  charts/images.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/extensions/worker/worker_test.go
  pkg/component/nginxingress/logging.go
  pkg/component/nginxingress/logging_test.go
  pkg/component/nginxingress/nginxingress.go
  pkg/component/nginxingress/nginxingress_test.go
  pkg/component/nginxingressshoot/nginxingress.go
  pkg/component/nginxingressshoot/nginxingress_suite_test.go
  pkg/component/nginxingressshoot/nginxingress_test.go
  pkg/gardenlet/controller/seed/seed/nginxingress.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/nginxingress.go
  skaffold.yaml
  test/integration/controllermanager/project/activity/activity_test.go
  test/integration/controllermanager/project/stale/stale_test.go
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#8135 Fix unit tests in `pkg/utils/gardener/shootstate`
  pkg/utils/gardener/shootstate/shootstate_test.go
Labels: area/dev-productivity, size/XS, kind/test, cla: yes, lgtm, approved

#8129 gardener-apiserver: Do not validate Shoot networks for a DELETE request
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, area/quality, size/M, cla: yes, lgtm, approved

#8137 [release-v1.73] gardener-apiserver: Do not validate Shoot networks for a DELETE request
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, area/quality, size/M, cla: yes, lgtm, approved

#8138 [release-v1.72] gardener-apiserver: Do not validate Shoot networks for a DELETE request
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, area/quality, size/M, cla: yes, lgtm, approved

#8113 Drop temporary cleanup code for old `fluent-bit`
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile_test.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#8133 Bump up fluent-operator to 2.3.0, fluent-bit to 2.1.4 and g/logging to 0.55.3
  charts/images.yaml
Labels: kind/enhancement, area/logging, size/S, cla: yes, lgtm, approved

#8114 Adapt Shoot maintenance controller to disable `EnableStaticTokenKubeconfig` when upgrading Shoot cluster to k8s version >= 1.27
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
Labels: kind/enhancement, area/open-source, size/M, cla: yes, lgtm, approved

#8014 Added service for metrics endpoint of `etcd-druid`
  pkg/component/etcd/bootstrap.go
  pkg/component/etcd/bootstrap_test.go
Labels: kind/enhancement, size/M, area/control-plane, cla: yes, lgtm, approved

#8141 Improvements for Workerless Shoot
  pkg/api/core/shoot/warnings.go
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  plugin/pkg/global/extensionlabels/admission.go
  plugin/pkg/global/extensionlabels/admission_test.go
Labels: kind/enhancement, area/usability, area/quality, size/L, cla: yes, lgtm, approved

#8125 Improve documentation about worker pool configuration with multiple zones
  docs/api-reference/core.md
  docs/usage/shoot_high_availability_best_practices.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/openapi/openapi_generated.go
Labels: kind/enhancement, area/documentation, area/usability, size/M, cla: yes, lgtm, approved

#8122 Allow deletion for `Shoot`s with invalid spec
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  test/e2e/gardener/shoot/create_and_delete_failed.go
Labels: area/ops-productivity, area/usability, size/M, kind/regression, cla: yes, lgtm, approved

#8145 Prevent concurrent updates on in-memory Garden object of operator during parallel task flow.
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/garden/reconciler_delete.go
  pkg/operator/controller/garden/reconciler_reconcile.go
Labels: kind/enhancement, area/robustness, size/S, cla: yes, lgtm, approved

#8149 Fix `plutono` dashboard
  charts/seed-bootstrap/dashboards/seed-deployments-replicas.json
  charts/seed-monitoring/charts/plutono/dashboards/owners/kubernetes-deployments-dashboard.json
  charts/seed-monitoring/charts/plutono/dashboards/owners/kubernetes-statefulsets-dashboard.json
Labels: kind/bug, area/monitoring, size/S, cla: yes, lgtm, approved

#8061 Refactor `vali` Helm chart into Golang component
  charts/seed-bootstrap/charts/vali/Chart.yaml
  charts/seed-bootstrap/charts/vali/charts/utils-templates
  charts/seed-bootstrap/charts/vali/templates/_helpers.tpl
  charts/seed-bootstrap/charts/vali/templates/hvpa.yaml
  charts/seed-bootstrap/charts/vali/templates/kube-rbac-proxy-ingress.yaml
  charts/seed-bootstrap/charts/vali/templates/logging-service.yaml
  charts/seed-bootstrap/charts/vali/templates/service.yaml
  charts/seed-bootstrap/charts/vali/templates/statefulset.yaml
  charts/seed-bootstrap/charts/vali/templates/telegraf-config.yaml
  charts/seed-bootstrap/charts/vali/templates/vali-configmap.yaml
  charts/seed-bootstrap/charts/vali/values.yaml
  charts/seed-bootstrap/requirements.yaml
  charts/seed-bootstrap/values.yaml
  pkg/component/logging/vali/logging.go
  pkg/component/logging/vali/templates/curator-config.yaml
  pkg/component/logging/vali/templates/telegraf-config.tpl
  pkg/component/logging/vali/templates/telegraf-start.sh.tpl
  pkg/component/logging/vali/templates/vali-config.yaml.tpl
  pkg/component/logging/vali/templates/vali-init.sh
  pkg/component/logging/vali/vali.go
  pkg/component/logging/vali/vali_test.go
  pkg/component/shared/vali.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/logging.go
  pkg/operation/botanist/logging_test.go
  pkg/operation/common/utils.go
  pkg/operation/common/utils_test.go
  pkg/operation/operation.go
  pkg/operation/shoot/types.go
  skaffold-operator.yaml
Labels: area/logging, kind/technical-debt, cla: yes, lgtm, approved, size/XXL

#8143 [GEP-22] Prevent losing `ShootState` data
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/gardenlet/controller/shoot/state/reconciler.go
  pkg/utils/gardener/shootstate/shootstate.go
  pkg/utils/gardener/shootstate/shootstate_test.go
  test/integration/gardenlet/shoot/state/state_test.go
Labels: kind/bug, size/L, area/scalability, cla: yes, lgtm, approved

#8144 [GEP-22] Delete stale `ShootState`s for `Shoot`s running on managed `Seed`s
  cmd/gardenlet/app/app.go
Labels: kind/enhancement, size/M, area/scalability, cla: yes, lgtm, approved

#8150 Update `calico` manifests to `v3.26.1`
  example/gardener-local/calico/base/kustomization.yaml
  example/provider-local/garden/base/kustomization.yaml
Labels: kind/enhancement, size/S, area/testing, cla: yes, lgtm, approved

#8146 Adapt `Worker` controller to persist state in `Migrate` phase
  extensions/pkg/controller/worker/genericactuator/actuator_migrate.go
  extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  extensions/pkg/controller/worker/state_reconciler.go
Labels: kind/enhancement, area/usability, size/M, cla: yes, lgtm, approved

#8152 Renew all garden access secrets on seed when triggered by annotation
  docs/README.md
  docs/concepts/gardenlet.md
  docs/extensions/garden-api-access.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  pkg/registry/core/seed/strategy.go
  pkg/registry/core/seed/strategy_test.go
  pkg/utils/gardener/tokenrequest/secrets.go
  pkg/utils/gardener/tokenrequest/secrets_test.go
  test/e2e/gardener/seed/garden_access.go
Labels: kind/enhancement, area/security, area/usability, size/L, cla: yes, lgtm, approved

#8151 Cleanup left-out things related to removed local setup
  Makefile
  example/gardener-local/controlplane/auth-webhook-kubeconfig-ipv4.yaml
  example/gardener-local/controlplane/auth-webhook-kubeconfig-ipv6.yaml
  example/gardener-local/controlplane/auth-webhook-kubeconfig-local-ipv4.yaml
  example/gardener-local/controlplane/auth-webhook-kubeconfig-skaffold-ipv6.yaml
  example/gardener-local/kind/cluster/templates/_extra_port_mappings.tpl
  example/gardener-local/kind/cluster/templates/_kubeadm_config_patches.tpl
  example/gardener-local/kind/cluster/values.yaml
  hack/kind-extensions-up.sh
  hack/kind-up.sh
Labels: area/dev-productivity, size/M, kind/cleanup, cla: yes, lgtm, approved

#8165 [release-v1.74] Revert "[GEP-22] Delete stale `ShootState`s for `Shoot`s running on managed `Seed`s (#8144)"
  cmd/gardenlet/app/app.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#8167 Use release branch of previous minor version as backup for upgrade tests
  hack/ci-e2e-kind-upgrade.sh
Labels: kind/bug, size/S, area/testing, cla: yes, lgtm, approved

#8161 Make containerd dependent on mirror configuration
  pkg/provider-local/webhook/controlplane/ensurer.go
Labels: area/dev-productivity, size/S, kind/flake, cla: yes, lgtm, approved

#8153 Adapt vpa-updater QPS limits such that it doesn't get throttled on large clusters
  pkg/component/vpa/updater.go
  pkg/component/vpa/vpa_test.go
Labels: kind/enhancement, size/XS, area/auto-scaling, cla: yes, lgtm, approved

#8156 [operator] Introduce `dns.domains` field
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/operator.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  pkg/operator/webhook/validation/handler_test.go
  test/e2e/operator/garden/common.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden_test.go
Labels: kind/api-change, area/usability, size/L, area/scalability, cla: yes, lgtm, approved

#8157 resource-manager: Ignore the `ToBeDeletedByClusterAutoscaler` taint in the system-components-config webhook
  pkg/resourcemanager/webhook/systemcomponentsconfig/handler.go
  test/integration/resourcemanager/systemcomponentsconfig/systemcomponentsconfig_test.go
Labels: kind/bug, area/ops-productivity, area/quality, size/M, cla: yes, lgtm, approved

#7954 update tunnel-probe-apiserver-proxy for HA mode
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
Labels: kind/bug, lifecycle/stale, area/monitoring, size/S, ok-to-test, cla: yes, lgtm, approved

#8160 Fix Exposure Class annotation handling
  pkg/gardenlet/controller/seed/seed/components.go
Labels: kind/bug, size/XS, area/high-availability, area/control-plane, cla: yes, lgtm, approved

#8162 Deploy `ControlPlane` extension after `kube-apiserver` in the reconciliation flow
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
Labels: size/M, kind/cleanup, cla: yes, lgtm, approved

#8099 Add pod security `enforce` label to gardener created namespaces
  charts/gardener/provider-local/extension/doc.go
  docs/extensions/conventions.md
  example/provider-local/garden/base/controller-registration.yaml
  hack/generate-controller-registration.sh
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/istio/istio_test.go
  pkg/component/istio/istiod.go
  pkg/controllermanager/controller/controllerregistration/seed/reconciler.go
  pkg/controllermanager/controller/controllerregistration/seed/reconciler_test.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/namespaces.go
  pkg/operation/botanist/namespaces_test.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden_test.go
Labels: kind/enhancement, area/security, size/L, cla: yes, lgtm, approved

#8166 Update VPA to v0.14.0
  charts/images.yaml
  go.mod
  go.sum
  pkg/component/vpa/templates/crd-verticalpodautoscalercheckpoints.tpl.yaml
  pkg/component/vpa/templates/crd-verticalpodautoscalers.tpl.yaml
  pkg/component/vpa/vpa_test.go
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/constants.go
  vendor/github.com/emicklei/go-restful/v3/request.go
  vendor/github.com/emicklei/go-restful/v3/response.go
  vendor/github.com/emicklei/go-restful/v3/route.go
  vendor/github.com/emicklei/go-restful/v3/route_builder.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
  vendor/modules.txt
Labels: kind/enhancement, area/auto-scaling, cla: yes, lgtm, approved, size/XXL

#8187 Update CA version for k8s v1.27
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/auto-scaling, cla: yes, lgtm, approved

#8159 Introduce constraints for CRDs with multiple stored versions and a conversion webhook
  docs/usage/shoot_status.md
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/gardenlet/controller/shoot/care/reconciler.go
  pkg/gardenlet/controller/shoot/care/reconciler_test.go
  pkg/operation/care/constraints.go
  pkg/operation/care/constraints_test.go
Labels: kind/enhancement, size/L, area/robustness, cla: yes, lgtm, approved

#8192 Switch the coredns image to be pulled from `registry.k8s.io`
  charts/images.yaml
Labels: kind/enhancement, area/cost, size/XS, area/open-source, cla: yes, lgtm, approved

#7945 [operator] Manage `nginx-ingress-{controller,k8s-backend}`
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/core.md
  docs/api-reference/operator.md
  docs/concepts/operator.md
  docs/development/priority-classes.md
  example/gardener-local/kind/cluster/templates/_extra_port_mappings.tpl
  example/gardener-local/kind/cluster/values.yaml
  example/gardener-local/kind/extensions/values.yaml
  example/gardener-local/kind/operator/values.yaml
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/component/shared/nginx_ingress.go
  pkg/gardenlet/controller/seed/seed/nginxingress.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/nginxingress.go
  pkg/operation/botanist/nginxingress_test.go
  pkg/operator/apis/config/types.go
  pkg/operator/controller/add.go
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/garden/reconciler_delete.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  pkg/utils/miscellaneous.go
  pkg/utils/miscellaneous_test.go
  test/e2e/operator/garden/common.go
  test/e2e/operator/garden/create_delete.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#8184 Forbid hibernating the `Shoot` during credential rotation and triggering rotation when the `Shoot` is waking up
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: kind/bug, area/ops-productivity, area/quality, size/L, cla: yes, lgtm, approved

#8110 Support AdmissionPlugin to reference other files
  charts/gardener/controlplane/charts/application/templates/validatingwebhook-admission-controller.yaml
  docs/concepts/admission-controller.md
  example/90-shoot.yaml
  pkg/admissioncontroller/webhook/add.go
  pkg/admissioncontroller/webhook/admission/admissionpluginsecret/add.go
  pkg/admissioncontroller/webhook/admission/admissionpluginsecret/admissionpluginsecret_suite_test.go
  pkg/admissioncontroller/webhook/admission/admissionpluginsecret/handler.go
  pkg/admissioncontroller/webhook/admission/admissionpluginsecret/handler_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/operator/controller/garden/components.go
  pkg/utils/gardener/secret_test.go
  pkg/utils/gardener/secrets.go
  pkg/utils/validation/admissionplugins/admissionplugins.go
  pkg/utils/validation/admissionplugins/admissionplugins_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  skaffold.yaml
Labels: kind/enhancement, size/XL, area/usability, cla: yes, lgtm, approved

#8193 Cleanup TODOs
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/Chart.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/charts/utils-templates
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/pdb.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/service.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/serviceaccount.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/vpa.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/values.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/Chart.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/charts/utils-templates
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/psp/node-exporter-clusterrole.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/psp/node-exporter-psp.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/psp/node-exporter-rolebinding.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/vpa.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/values.yaml
  charts/shoot-core/components/charts/monitoring/requirements.yaml
  charts/shoot-core/components/charts/monitoring/values.yaml
  charts/shoot-core/components/values.yaml
  pkg/operation/botanist/addons.go
Labels: area/quality, size/L, kind/cleanup, cla: yes, lgtm, approved

#8194 Cleanup more stuff related to local kind setup
  Makefile
  example/provider-local/garden/local/kustomization.yaml
  example/provider-local/garden/local/patch-controller-deployment.yaml
  example/provider-local/garden/local/secret-default-domain.yaml
  example/provider-local/garden/local/secret-internal-domain.yaml
  example/provider-local/seed-kind-ha-single-zone/local/kustomization.yaml
  example/provider-local/seed-kind-ha-single-zone/local/seed.yaml
  example/provider-local/seed-kind/local/kustomization.yaml
  example/provider-local/seed-kind/local/seed.yaml
  example/provider-local/seed-kind2-ha-single-zone/local/delete-secret-seed-local-ha-single-zone.yaml
  example/provider-local/seed-kind2-ha-single-zone/local/kustomization.yaml
  example/provider-local/seed-kind2-ha-single-zone/local/patch-seed.yaml
  example/provider-local/seed-kind2/local/delete-secret-seed-local.yaml
  example/provider-local/seed-kind2/local/kustomization.yaml
  example/provider-local/seed-kind2/local/patch-seed.yaml
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#8195 `shoots/adminkubeconfig`: drop fallback to `ShootState`
  pkg/registry/core/rest/storage_core.go
  pkg/registry/core/shoot/storage/admin_kubeconfig.go
  pkg/registry/core/shoot/storage/admin_kubeconfig_test.go
  pkg/registry/core/shoot/storage/storage.go
  skaffold.yaml
Labels: area/dev-productivity, size/XL, area/usability, kind/cleanup, cla: yes, lgtm, approved

#8197 Add label to fluent-bit to allow ingress and egress to shoot Vali
  pkg/component/logging/fluentoperator/custom_resources_test.go
  pkg/component/logging/fluentoperator/fluent_operator.go
Labels: kind/bug, area/logging, size/S, cla: yes, lgtm, approved
