Repository gardener/gardener, pull requests merged in 2023-07, with the labels that each got.

#8205 Use the same `nginx-ingress-controller` image for `Shoot`s and `Seed`s
  charts/images.yaml
  pkg/component/shared/nginx_ingress.go
  pkg/operation/botanist/nginxingress_test.go
  pkg/utils/images/images.go
Labels: kind/enhancement, area/open-source, size/M, area/control-plane, cla: yes, lgtm, approved

#8204 Inject extension garden access into `ControllerInstallations`
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/templates/networkpolicy.yaml
  cmd/gardener-extension-provider-local/app/app.go
  docs/concepts/gardenlet.md
  docs/extensions/garden-api-access.md
  example/provider-local/garden/base/controller-registration.yaml
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/client/kubernetes/client.go
  pkg/component/clusterautoscaler/cluster_autoscaler.go
  pkg/component/kubecontrollermanager/kube_controller_manager.go
  pkg/component/kubescheduler/kube_scheduler.go
  pkg/component/kubestatemetrics/kube_state_metrics.go
  pkg/component/kubestatemetrics/resources.go
  pkg/component/logging/eventlogger/event_logger.go
  pkg/component/logging/kuberbacproxy/kube_rbac_proxy.go
  pkg/component/logging/vali/vali.go
  pkg/component/logging/vali/vali_test.go
  pkg/component/machinecontrollermanager/machine_controller_manager.go
  pkg/component/resourcemanager/resource_manager.go
  pkg/gardenlet/controller/controllerinstallation/add.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/add.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/gardenlet/controller/managedseed/actuator.go
  pkg/gardenlet/features/features.go
  pkg/utils/gardener/garden.go
  pkg/utils/gardener/garden_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  pkg/utils/kubernetes/pod.go
  pkg/utils/kubernetes/pod_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: kind/enhancement, area/security, area/usability, cla: yes, lgtm, approved, size/XXL

#8210 Fix version copy/paste error in shoot versions documentation
  docs/usage/shoot_versions.md
Labels: kind/bug, size/XS, area/documentation, cla: yes, lgtm, approved

#8198 Default `kubernetes.version` if omitted
  docs/api-reference/core.md
  docs/concepts/apiserver_admission_plugins.md
  docs/development/new-kubernetes-version.md
  example/90-shoot.yaml
  example/provider-local/shoot-workerless.yaml
  example/provider-local/shoot.yaml
  extensions/pkg/controller/worker/machines.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/openapi/openapi_generated.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  plugin/pkg/bastion/validator/admission.go
  plugin/pkg/controllerregistration/resources/admission.go
  plugin/pkg/global/customverbauthorizer/admission.go
  plugin/pkg/global/deletionconfirmation/admission.go
  plugin/pkg/global/extensionlabels/admission.go
  plugin/pkg/global/extensionvalidation/admission.go
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/managedseed/shoot/admission.go
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/seed/validator/admission.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/exposureclass/admission.go
  plugin/pkg/shoot/managedseed/admission.go
  plugin/pkg/shoot/oidc/clusteropenidconnectpreset/admission.go
  plugin/pkg/shoot/oidc/openidconnectpreset/admission.go
  plugin/pkg/shoot/quotavalidator/admission.go
  plugin/pkg/shoot/tolerationrestriction/admission.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  test/integration/gardenlet/managedseed/managedseed_test.go
Labels: kind/enhancement, area/usability, cla: yes, lgtm, approved, size/XXL

#8199 Clean up DNS handling
  charts/gardener/controlplane/charts/utils-common/templates/_secret-default-domain.yaml
  docs/api-reference/core.md
  example/10-secret-default-domain.yaml
  example/10-secret-internal-domain.yaml
  example/90-shoot.yaml
  pkg/admissioncontroller/webhook/admission/internaldomainsecret/handler.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/dns.go
  pkg/operation/botanist/dns_test.go
  pkg/utils/gardener/dns.go
  pkg/utils/gardener/dns_test.go
  pkg/utils/gardener/garden.go
  pkg/utils/gardener/garden_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/shoot/dns/admission.go
Labels: area/open-source, size/L, kind/cleanup, cla: yes, lgtm, approved

#8202 Introduce persona-based docs
  .docforge/manifest.yaml
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/README.md
  docs/api-reference/core.md
  docs/api-reference/operator.md
  docs/concepts/apiserver.md
  docs/concepts/architecture.md
  docs/concepts/backup-restore.md
  docs/concepts/cluster-api.md
  docs/concepts/gardenlet.md
  docs/concepts/operator.md
  docs/concepts/scheduler.md
  docs/deployment/deploy_gardenlet.md
  docs/deployment/deploy_gardenlet_automatically.md
  docs/deployment/deploy_gardenlet_manually.md
  docs/deployment/getting_started_locally.md
  docs/deployment/setup_gardener.md
  docs/development/component-checklist.md
  docs/extensions/controllerregistration.md
  docs/extensions/controlplane.md
  docs/extensions/conventions.md
  docs/extensions/provider-local.md
  docs/extensions/shoot-webhooks.md
  docs/monitoring/alerting.md
  docs/monitoring/connectivity.md
  docs/operations/configuration.md
  docs/operations/control_plane_migration.md
  docs/operations/images/external-traffic-policy-cluster.png
  docs/operations/images/external-traffic-policy-local.png
  docs/operations/images/multi-zonal-istio.png
  docs/operations/istio.md
  docs/operations/managed_seed.md
  docs/operations/network_policies.md
  docs/operations/seed_bootstrapping.md
  docs/operations/seed_settings.md
  docs/operations/topology_aware_routing.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/operator/v1alpha1/types.go
  pkg/openapi/openapi_generated.go
Labels: size/L, kind/cleanup, cla: yes, lgtm, approved

#8209 Forbid adding well-known gardener finalizers on `Shoot` creation
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/controllermanager/controller/shoot/reference/reconciler.go
  pkg/controllermanager/controller/shoot/reference/reconciler_test.go
  pkg/gardenlet/controller/bastion/reconciler.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: kind/enhancement, size/L, area/robustness, cla: yes, lgtm, approved

#8196 Watch `core.gardener.cloud/v1beta1.BackupBucket` in the `BackupEntry` controller
  pkg/api/indexer/gardener_core.go
  pkg/controllerutils/predicate/predicate.go
  pkg/controllerutils/predicate/predicate_test.go
  pkg/gardenlet/controller/backupbucket/add.go
  pkg/gardenlet/controller/backupbucket/reconciler.go
  pkg/gardenlet/controller/backupentry/add.go
  pkg/gardenlet/controller/backupentry/add_test.go
  pkg/gardenlet/controller/backupentry/reconciler.go
  pkg/gardenlet/controller/bastion/add.go
  pkg/utils/kubernetes/health/extensions.go
  test/integration/gardenlet/backupbucket/backupbucket_suite_test.go
  test/integration/gardenlet/backupentry/backupentry_suite_test.go
  test/integration/gardenlet/backupentry/backupentry_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, area/scalability, cla: yes, lgtm, approved

#8212 Improve admissionplugin validation
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  pkg/utils/validation/admissionplugins/admissionplugins.go
  pkg/utils/validation/admissionplugins/admissionplugins_test.go
Labels: kind/enhancement, area/usability, area/quality, size/L, cla: yes, lgtm, approved

#8216 Move content of `kuberbacproxy` into `vali` component
  pkg/component/extensions/operatingsystemconfig/downloader/downloader.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config.go
  pkg/component/logging/kuberbacproxy/kube_rbac_proxy.go
  pkg/component/logging/kuberbacproxy/kube_rbac_proxy_test.go
  pkg/component/logging/vali/monitoring.go
  pkg/component/logging/vali/monitoring_test.go
  pkg/component/logging/vali/vali.go
  pkg/component/logging/vali/vali_test.go
  pkg/component/shared/vali.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/logging.go
  pkg/operation/botanist/logging_test.go
  pkg/operation/shoot/types.go
Labels: area/dev-productivity, size/XL, kind/cleanup, cla: yes, lgtm, approved

#8219 Use alpine `testing` image in remote local setup
  docs/deployment/content/remote-local-setup.yaml
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#8220 Update cve-categorisation for `valitail`
  charts/images.yaml
Labels: size/XS, kind/task, area/logging, cla: yes, lgtm, approved

#8221 Fixed broken links - 2023.07
  docs/concepts/resource-manager.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#8218 Install `protoc` in tools/bin dir
  Makefile
  hack/tools.mk
  hack/tools/install-protoc.sh
  hack/update-protobuf.sh
Labels: kind/enhancement, area/dev-productivity, size/M, area/robustness, cla: yes, lgtm, approved

#8224 Update to Go 1.20.6
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#8223 Allow to use the pre-previous version for upgrade tests
  hack/ci-e2e-kind-upgrade.sh
Labels: kind/bug, area/dev-productivity, size/S, cla: yes, lgtm, approved

#8222 Prepare next Dev Cycle v1.76.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8158 [operator] Add `Care` reconciler to `Garden` controller.
  charts/gardener/operator/templates/_helpers.tpl
  charts/gardener/operator/values.yaml
  cmd/gardener-operator/app/app.go
  docs/concepts/operator.md
  example/operator/10-componentconfig.yaml
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/operator/v1alpha1/types.go
  pkg/client/kubernetes/clientmap/builder/garden_builder.go
  pkg/client/kubernetes/clientmap/builder/garden_builder_test.go
  pkg/client/kubernetes/clientmap/internal/garden_clientmap.go
  pkg/client/kubernetes/clientmap/internal/garden_clientmap_test.go
  pkg/client/kubernetes/clientmap/keys/keys.go
  pkg/client/kubernetes/clientmap/keys/keys_test.go
  pkg/component/gardeneraccess/access.go
  pkg/component/kubecontrollermanager/kube_controller_manager.go
  pkg/component/kubecontrollermanager/shoot_resources.go
  pkg/gardenlet/controller/seed/care/add_test.go
  pkg/gardenlet/controller/seed/care/reconciler.go
  pkg/gardenlet/controller/shoot/care/add_test.go
  pkg/gardenlet/controller/shoot/care/reconciler.go
  pkg/operation/care/checker.go
  pkg/operation/care/garden_health.go
  pkg/operation/care/garden_health_test.go
  pkg/operation/care/health.go
  pkg/operation/care/health_check_test.go
  pkg/operation/care/seed_health_test.go
  pkg/operator/apis/config/types.go
  pkg/operator/apis/config/v1alpha1/defaults.go
  pkg/operator/apis/config/v1alpha1/defaults_test.go
  pkg/operator/apis/config/v1alpha1/types.go
  pkg/operator/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/operator/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/operator/apis/config/validation/validation.go
  pkg/operator/apis/config/validation/validation_test.go
  pkg/operator/apis/config/zz_generated.deepcopy.go
  pkg/operator/controller/add.go
  pkg/operator/controller/garden/add.go
  pkg/operator/controller/garden/care/add.go
  pkg/operator/controller/garden/care/add_test.go
  pkg/operator/controller/garden/care/care_suite_test.go
  pkg/operator/controller/garden/care/reconciler.go
  pkg/operator/controller/garden/care/reconciler_test.go
  pkg/operator/controller/garden/care/types.go
  pkg/operator/controller/garden/garden/add.go
  pkg/operator/controller/garden/garden/add_test.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/garden/garden/garden_suite_test.go
  pkg/operator/controller/garden/garden/reconciler.go
  pkg/operator/controller/garden/garden/reconciler_delete.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/operator/garden/care/care_suite_test.go
  test/integration/operator/garden/care/care_test.go
  test/integration/operator/garden/garden/garden_suite_test.go
  test/integration/operator/garden/garden/garden_test.go
Labels: kind/enhancement, area/dev-productivity, area/delivery, cla: yes, lgtm, approved, size/XXL

#8228 Updates `etcd-druid` crds and dependency
  example/seed-crds/10-crd-druid.gardener.cloud_etcds.yaml
  go.mod
  go.sum
  pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcds.yaml
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/types_etcd.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/store.go
  vendor/modules.txt
Labels: kind/enhancement, area/open-source, size/M, cla: yes, lgtm, approved

#8230 Fixed broken links
  docs/usage/shoot_credentials_rotation.md
  docs/usage/shoot_versions.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#8232 Deploy `OperatingSystemConfig` after `Extension` resources
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
Labels: kind/enhancement, size/S, area/control-plane, cla: yes, lgtm, approved

#8231 Add DNS value rewrite.
  pkg/component/coredns/coredns.go
  pkg/component/coredns/coredns_test.go
Labels: kind/bug, size/XS, area/networking, cla: yes, lgtm, approved

#8236 Improve local extension setup with regards to ssh tunnel stability
  example/provider-extensions/ssh-reverse-tunnel/base/ssh/ssh_deployment.yaml
  example/provider-extensions/ssh-reverse-tunnel/base/sshd/sshd_deployment.yaml
  example/provider-extensions/ssh-reverse-tunnel/seed-template/ssh/kustomization.yaml
  example/provider-extensions/ssh-reverse-tunnel/seed-template/sshd/kustomization.yaml
Labels: kind/enhancement, area/dev-productivity, area/robustness, area/networking, size/S, cla: yes, lgtm, approved

#8215 [operator] Introduce `gardenerapiserver` Golang component
  docs/development/priority-classes.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/operator/v1alpha1/constants.go
  pkg/component/apiserver/admission.go
  pkg/component/apiserver/admission_test.go
  pkg/component/apiserver/apiserver_suite_test.go
  pkg/component/apiserver/audit.go
  pkg/component/apiserver/audit_test.go
  pkg/component/apiserver/deployment.go
  pkg/component/apiserver/deployment_test.go
  pkg/component/apiserver/encryptionconfiguration.go
  pkg/component/apiserver/encryptionconfiguration_test.go
  pkg/component/apiserver/types.go
  pkg/component/gardenerapiserver/apiservice.go
  pkg/component/gardenerapiserver/configmaps.go
  pkg/component/gardenerapiserver/deployment.go
  pkg/component/gardenerapiserver/endpoints.go
  pkg/component/gardenerapiserver/gardener_apiserver.go
  pkg/component/gardenerapiserver/gardener_apiserver_suite_test.go
  pkg/component/gardenerapiserver/gardener_apiserver_test.go
  pkg/component/gardenerapiserver/hvpa.go
  pkg/component/gardenerapiserver/poddisruptionbudget.go
  pkg/component/gardenerapiserver/rbac.go
  pkg/component/gardenerapiserver/secrets.go
  pkg/component/gardenerapiserver/service.go
  pkg/component/gardenerapiserver/vpa.go
  pkg/component/kubeapiserver/configmaps.go
  pkg/component/kubeapiserver/deployment.go
  pkg/component/kubeapiserver/kube_apiserver.go
  pkg/component/kubeapiserver/kube_apiserver_test.go
  pkg/component/kubeapiserver/mock/mocks.go
  pkg/component/kubeapiserver/secrets.go
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/component/test/seralize.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operator/client/scheme.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/garden/garden/reconciler.go
  pkg/utils/kubernetes/tls_cipher_suites.go
  skaffold-operator.yaml
  skaffold.yaml
  test/e2e/operator/garden/create_delete.go
  test/e2e/operator/garden/create_rotate_delete.go
  test/e2e/operator/garden/internal/rotation/certificate_authorities.go
Labels: kind/enhancement, area/usability, cla: yes, lgtm, approved, size/XXL

#8233 Cleanup old `addons` `ManagedResource`
  cmd/gardenlet/app/app.go
  pkg/component/kubernetesdashboard/kubernetes_dashboard.go
  pkg/component/nginxingress/nginxingress.go
  pkg/operation/botanist/kubeapiserver_test.go
Labels: area/usability, area/quality, size/L, kind/cleanup, cla: yes, lgtm, approved

#8109 Drop `.spec.settings.ownerChecks` field from Seed API
  docs/api-reference/core.md
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/types_seed_test.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/registry/core/seed/strategy.go
  pkg/registry/core/seed/strategy_test.go
Labels: kind/api-change, kind/cleanup, area/control-plane-migration, cla: yes, lgtm, approved, size/XXL

#8239 Allow local gardener API server to call webhooks
  example/gardener-local/controlplane/values.yaml
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#8238 [operator] Introduce `lastOperation` in `Garden` status
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/operator.md
  docs/concepts/operator.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/operation/care/garden_health.go
  pkg/operation/care/garden_health_test.go
  pkg/operation/operation.go
  pkg/operator/controller/garden/care/add.go
  pkg/operator/controller/garden/care/add_test.go
  pkg/operator/controller/garden/care/reconciler.go
  pkg/operator/controller/garden/care/reconciler_test.go
  pkg/operator/controller/garden/care/types.go
  pkg/operator/controller/garden/garden/reconciler.go
  pkg/utils/flow/progress_reporter.go
  pkg/utils/flow/progress_reporter_test.go
  test/e2e/operator/garden/common.go
  test/integration/operator/garden/care/care_test.go
  test/integration/operator/garden/garden/garden_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#8248 Vendor `DWD@v1.1.1`
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/enhancement, area/open-source, size/L, cla: yes, lgtm, approved

#8227 Implement orphan file deletion in the cloud-config executor script
  docs/api-reference/extensions.md
  example/seed-crds/10-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  extensions/pkg/controller/operatingsystemconfig/actuator.go
  extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_reconcile.go
  extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_restore.go
  extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_util.go
  extensions/pkg/controller/operatingsystemconfig/reconciler.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  pkg/component/extensions/operatingsystemconfig/executor/executor.go
  pkg/component/extensions/operatingsystemconfig/executor/executor_test.go
  pkg/component/extensions/operatingsystemconfig/executor/templates/scripts/execute-cloud-config.tpl.sh
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/operatingsystemconfig_test.go
Labels: kind/enhancement, size/L, area/control-plane, area/os, cla: yes, lgtm, approved

#8246 Update and add e2e tests for HA prow jobs
  Makefile
  test/e2e/gardener/shoot/create_and_delete_unprivileged.go
  test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go
  test/e2e/gardener/shoot/create_rotate_delete.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/enhancement, kind/test, area/robustness, size/S, area/high-availability, area/testing, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#8237 Move `seed-bootstrap` chart and monitoring-related logic in `Seed` controller into `monitoring` component
  charts/seed-bootstrap/charts/monitoring/charts/utils-templates
  charts/seed-bootstrap/charts/utils-templates
  hack/test-prometheus.sh
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/logging/vali/vali.go
  pkg/component/monitoring/bootstrap.go
  pkg/component/monitoring/charts/bootstrap/Chart.yaml
  pkg/component/monitoring/charts/bootstrap/aggregate-prometheus-rules-tests/fluent-bit.rules.test.yaml
  pkg/component/monitoring/charts/bootstrap/aggregate-prometheus-rules-tests/vali.rules.test.yaml
  pkg/component/monitoring/charts/bootstrap/aggregate-prometheus-rules/fluent-bit.rules.yaml
  pkg/component/monitoring/charts/bootstrap/aggregate-prometheus-rules/metering.rules.stateful.yaml
  pkg/component/monitoring/charts/bootstrap/aggregate-prometheus-rules/vali.rules.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/Chart.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/seed-prometheus-rules/.gitkeep
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/clusterrolebinding.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/config.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/helpers.tpl
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/prometheus-vpa.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/rules.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/service.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/serviceaccount.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/statefulset.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/values.yaml
  pkg/component/monitoring/charts/bootstrap/prometheus-rules/metering.rules.stateful.sh
  pkg/component/monitoring/charts/bootstrap/prometheus-rules/metering.rules.stateful.yaml
  pkg/component/monitoring/charts/bootstrap/prometheus-rules/metering.rules.yaml
  pkg/component/monitoring/charts/bootstrap/prometheus-rules/recording-rules.rules.yaml
  pkg/component/monitoring/charts/bootstrap/templates/aggregate-prometheus/clusterrolebinding.yaml
  pkg/component/monitoring/charts/bootstrap/templates/aggregate-prometheus/config.yaml
  pkg/component/monitoring/charts/bootstrap/templates/aggregate-prometheus/helpers.tpl
  pkg/component/monitoring/charts/bootstrap/templates/aggregate-prometheus/hvpa.yaml
  pkg/component/monitoring/charts/bootstrap/templates/aggregate-prometheus/ingress.yaml
  pkg/component/monitoring/charts/bootstrap/templates/aggregate-prometheus/rules.yaml
  pkg/component/monitoring/charts/bootstrap/templates/aggregate-prometheus/service.yaml
  pkg/component/monitoring/charts/bootstrap/templates/aggregate-prometheus/serviceaccount.yaml
  pkg/component/monitoring/charts/bootstrap/templates/aggregate-prometheus/statefulset.yaml
  pkg/component/monitoring/charts/bootstrap/templates/aggregate-prometheus/vpa.yaml
  pkg/component/monitoring/charts/bootstrap/templates/alertmanager/alertmanager.yaml
  pkg/component/monitoring/charts/bootstrap/templates/alertmanager/config.tpl
  pkg/component/monitoring/charts/bootstrap/templates/alertmanager/config.yaml
  pkg/component/monitoring/charts/bootstrap/templates/clusterrole-prometheus.yaml
  pkg/component/monitoring/charts/bootstrap/templates/prometheus/clusterrolebinding.yaml
  pkg/component/monitoring/charts/bootstrap/templates/prometheus/config.yaml
  pkg/component/monitoring/charts/bootstrap/templates/prometheus/hvpa.yaml
  pkg/component/monitoring/charts/bootstrap/templates/prometheus/networkpolicy.yaml
  pkg/component/monitoring/charts/bootstrap/templates/prometheus/prometheus-vpa.yaml
  pkg/component/monitoring/charts/bootstrap/templates/prometheus/resource.tpl
  pkg/component/monitoring/charts/bootstrap/templates/prometheus/rules.yaml
  pkg/component/monitoring/charts/bootstrap/templates/prometheus/service.yaml
  pkg/component/monitoring/charts/bootstrap/templates/prometheus/serviceaccount.yaml
  pkg/component/monitoring/charts/bootstrap/templates/prometheus/statefulset.yaml
  pkg/component/monitoring/charts/bootstrap/values.yaml
  pkg/component/shared/fluent_operator.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/monitoring.go
Labels: area/dev-productivity, size/XL, kind/cleanup, cla: yes, lgtm, approved

#8214 Remove `service.beta.kubernetes.io/aws-load-balancer-type: nlb` from service `istio-ingress/istio-ingressgateway`.
  pkg/component/istio/charts/istio/istio-ingress/templates/service.yaml
  pkg/component/istio/istio_test.go
Labels: size/XS, kind/cleanup, area/networking, cla: yes, lgtm, approved

#8252 Fix vali ingress backend definition
  pkg/component/logging/vali/vali.go
  pkg/component/logging/vali/vali_test.go
Labels: kind/bug, size/XS, area/logging, cla: yes, lgtm, approved

#8253 [release-v1.74] Automated cherry pick of #8252: Fix vali ingress backend definition
  pkg/component/logging/vali/vali.go
  pkg/component/logging/vali/vali_test.go
Labels: kind/bug, size/XS, area/logging, cla: yes, lgtm, approved

#8254 [release-v1.75] Automated cherry pick of #8252: Fix vali ingress backend definition
  pkg/component/logging/vali/vali.go
  pkg/component/logging/vali/vali_test.go
Labels: kind/bug, size/XS, area/logging, cla: yes, lgtm, approved

#8258 Allow to enable disabled APIs in workerless shoots
  pkg/component/kubeapiserver/deployment.go
  pkg/component/kubeapiserver/kube_apiserver_test.go
Labels: kind/enhancement, area/usability, size/S, cla: yes, lgtm, approved

#7410 📖 [GEP-23] Autoscaling Shoot `kube-apiserver` via Independently Driven HPA and VPA
  docs/README.md
  docs/proposals/23-autoscaling-kube-apiserver-via-independent-hpa-and-vpa.md
  docs/proposals/assets/gep23-design-outline.png
Labels: kind/enhancement, size/L, area/auto-scaling, cla: yes, lgtm, approved

#8260 Fix the origin handling in the `pkg/utils/managedresources.NewForShoot` func
  pkg/utils/managedresources/managedresources.go
  pkg/utils/managedresources/managedresources_test.go
Labels: kind/bug, area/quality, size/M, cla: yes, lgtm, approved

#8235 [operator] Add component instantiation/deploy functions for `gardenerapiserver`
  charts/images.yaml
  pkg/component/gardenerapiserver/mock/doc.go
  pkg/component/gardenerapiserver/mock/mocks.go
  pkg/component/shared/apiserver.go
  pkg/component/shared/gardenerapiserver.go
  pkg/component/shared/gardenerapiserver_test.go
  pkg/component/shared/kubeapiserver.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  pkg/utils/gardener/secretsrotation/etcd.go
  pkg/utils/gardener/secretsrotation/etcd_test.go
  pkg/utils/images/images.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/usability, cla: yes, lgtm, approved, size/XXL

#8226 Release responsible schedule for v1.79 until v1.87
  docs/development/process.md
Labels: kind/enhancement, area/delivery, size/S, cla: yes, lgtm, approved

#8242 Enhance error code detection in worker controller
  extensions/pkg/controller/worker/genericactuator/actuator.go
  extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/genericactuator/machine_controller_manager.go
  pkg/operation/care/health.go
  pkg/provider-local/controller/worker/actuator.go
Labels: kind/enhancement, area/ops-productivity, size/M, cla: yes, lgtm, approved

#8261 Introduce `.spec.schedulerName` in `Shoot` API
  docs/api-reference/core.md
  docs/concepts/scheduler.md
  example/90-shoot.yaml
  example/provider-local/managedseeds/shoot-managedseed.yaml
  example/provider-local/shoot-workerless.yaml
  example/provider-local/shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/scheduler/controller/shoot/add.go
  pkg/scheduler/controller/shoot/add_test.go
  test/integration/scheduler/shoot/shoot_test.go
Labels: kind/enhancement, area/usability, cla: yes, lgtm, approved, size/XXL

#8244 [operator] Introduce `gardeneradmissioncontroller` Golang component
  docs/development/priority-classes.md
  pkg/component/gardeneradmissioncontroller/configmap.go
  pkg/component/gardeneradmissioncontroller/deployment.go
  pkg/component/gardeneradmissioncontroller/gardener_admission_controller.go
  pkg/component/gardeneradmissioncontroller/gardener_admission_controller_suite_test.go
  pkg/component/gardeneradmissioncontroller/gardener_admission_controller_test.go
  pkg/component/gardeneradmissioncontroller/poddisruptionbudget.go
  pkg/component/gardeneradmissioncontroller/rbac.go
  pkg/component/gardeneradmissioncontroller/secrets.go
  pkg/component/gardeneradmissioncontroller/service.go
  pkg/component/gardeneradmissioncontroller/vpa.go
  pkg/component/gardeneradmissioncontroller/webhooks.go
  pkg/component/gardenerapiserver/gardener_apiserver.go
  pkg/component/gardenerapiserver/gardener_apiserver_test.go
Labels: kind/enhancement, area/usability, cla: yes, lgtm, approved, size/XXL

#8265 [operator] Add Gardener Scheduler options to `Garden` API
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/operator.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/scheduler/apis/config/validation/validation.go
  pkg/scheduler/apis/config/validation/validation_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#8267 Prepare next Dev Cycle v1.77.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8266 Drop completed cleanup codes
  cmd/gardenlet/app/app.go
Labels: area/usability, area/quality, size/L, kind/cleanup, cla: yes, lgtm, approved

#8264 Handle extension `ServiceAccounts` in `Seed{Authorizer,Restriction}`
  cmd/gardener-extension-provider-local/app/app.go
  docs/deployment/gardenlet_api_access.md
  docs/extensions/garden-api-access.md
  pkg/admissioncontroller/seedidentity/identity.go
  pkg/admissioncontroller/seedidentity/identity_test.go
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler.go
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler_test.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer_test.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_certificatesigningrequest.go
  test/e2e/gardener/seed/garden_access.go
Labels: kind/enhancement, area/security, area/usability, cla: yes, lgtm, approved, size/XXL

#8206 Expose etcd snapshot compaction metrics from etcd-druid to control plane Prometheus instances
  pkg/component/etcd/monitoring.go
  pkg/component/etcd/monitoring_bootstrap.go
  pkg/component/etcd/monitoring_bootstrap_test.go
  pkg/component/etcd/monitoring_test.go
  pkg/component/monitoring/bootstrap.go
  pkg/component/plutono/dashboards/shoot/owners/etcd-compaction-job-dashboard.json
  pkg/component/plutono/plutono_test.go
Labels: size/XL, area/monitoring, kind/task, cla: yes, lgtm, approved

#8268 Drop no longer needed checksum annotations from GCM deployment
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/deployment.yaml
Labels: area/delivery, size/XS, kind/regression, cla: yes, lgtm, approved

#8278 Remove unneeded import from `hack/tools.go`
  hack/tools.go
  pkg/provider-local/webhook/controlplane/registry_mirror.go
Labels: size/XS, kind/cleanup, cla: yes, lgtm, approved

#8251 [operator] Add Gardener Admission Controller options to `Garden` API
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/operator.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/admissioncontroller/apis/config/validation/admissioncontrollerconfiguration.go
  pkg/apis/operator/v1alpha1/conversion/.import-restrictions
  pkg/apis/operator/v1alpha1/conversion/conversion.go
  pkg/apis/operator/v1alpha1/conversion/conversion_suite_test.go
  pkg/apis/operator/v1alpha1/conversion/conversion_test.go
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  skaffold-operator.yaml
Labels: kind/enhancement, size/XL, area/usability, cla: yes, lgtm, approved

#8272 Enforce `containerd` when `maintenance-controller` updates Kubernetes from `v1.22` to `v1.23`
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler_test.go
Labels: kind/enhancement, area/ops-productivity, size/M, cla: yes, lgtm, approved
