Repository gardener/gardener, pull requests merged in 2023-05, with the labels that each got.

#7854 Rename httpAccessLogs to httpAccessVerbosity in the shoot example
  example/90-shoot.yaml
  example/operator/20-garden.yaml
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#7832 Suppress the event-logger `nest` filter's warnings
  pkg/operation/botanist/component/logging/eventlogger/logging.go
  pkg/operation/botanist/component/logging/eventlogger/logging_test.go
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#7853 gardener-apiserver: Fix the kubelet version constraint validation to cover the Shoot K8s version update
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  test/integration/controllermanager/shoot/maintenance/utils_test.go
Labels: kind/bug, area/quality, size/L, cla: yes, lgtm, approved

#7850 Protect `Secret`s/`ConfigMap`s referenced in `.spec.resources` of `Shoot`s with finalizer
  pkg/controllermanager/controller/shoot/reference/reconciler.go
  test/integration/controllermanager/shoot/reference/reference_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#7848 refactor loki init container script turning it to a best effort init
  charts/seed-bootstrap/charts/loki/templates/_helpers.tpl
  charts/seed-bootstrap/charts/loki/templates/statefulset.yaml
Labels: kind/enhancement, area/logging, size/S, cla: yes, lgtm, approved

#7862 Update to Go 1.20.4
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#7856 Clarification on static token kubeconfig docs
  docs/usage/shoot_access.md
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#7860 Change `log` mount path of `node-problem-detector` from `/var/log` to `/var/log/journal`.
  pkg/operation/botanist/component/nodeproblemdetector/node_problem_detector.go
  pkg/operation/botanist/component/nodeproblemdetector/node_problem_detector_test.go
Labels: kind/enhancement, area/security, size/S, area/compliance, cla: yes, lgtm, approved

#7869 gardenlet: Deploy/destroy the owner DNSRecord when the Shoot namespace exists and is not terminating
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
Labels: kind/bug, size/XS, area/quality, kind/regression, cla: yes, lgtm, approved

#7867 Promote `HAControlPlanes` feature gate to beta
  docs/deployment/feature_gates.md
  example/gardener-local/controlplane/values.yaml
  hack/local-development/start-apiserver
  pkg/features/features.go
  skaffold.yaml
  test/integration/scheduler/shoot/shoot_suite_test.go
Labels: kind/enhancement, size/S, area/high-availability, cla: yes, lgtm, approved

#7875 set_dependency_version script: Add tune2fs as logging image as well
  hack/.ci/set_dependency_version
Labels: kind/enhancement, area/dev-productivity, size/XS, area/logging, cla: yes, lgtm, approved

#7879 [release-v1.68] Unpin previous release for upgrade tests
  Makefile
Labels: size/XS, kind/cleanup, area/testing, cla: yes, lgtm, approved

#7880 Move remaining `gardener-local` images from docker.io to registry mirror
  example/gardener-local/calico/base/kustomization.yaml
  example/gardener-local/registry/base/registry.yaml
Labels: kind/bug, area/dev-productivity, size/S, cla: yes, lgtm, approved

#7858 [Workerless Shoots] Prepare components to support workerless shoot
  docs/development/new-kubernetes-version.md
  pkg/api/core/shoot/warnings.go
  pkg/api/core/shoot/warnings_test.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/secrets.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/operation/botanist/component/kubecontrollermanager/monitoring_test.go
  pkg/operation/botanist/component/kubecontrollermanager/waiter_test.go
  pkg/operation/botanist/component/shared/kubeapiserver.go
  pkg/operation/botanist/component/shared/kubeapiserver_test.go
  pkg/operation/botanist/controlplane.go
  pkg/operation/botanist/infrastructure_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubecontrollermanager.go
  pkg/operation/botanist/operatingsystemconfig_test.go
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/secrets_test.go
  pkg/operation/botanist/worker_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/miscellaneous.go
  pkg/utils/miscellaneous_test.go
Labels: kind/enhancement, area/delivery, area/control-plane, cla: yes, lgtm, approved, size/XXL

#7864 No longer delete `Namespace`s on `Shoot` deletion
  docs/usage/shoot_cleanup.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/operation/botanist/cleanup.go
  pkg/utils/kubernetes/client/client.go
  pkg/utils/kubernetes/client/client_test.go
Labels: kind/bug, area/ops-productivity, size/L, cla: yes, lgtm, approved

#7885 Remove deprecated prometheus relabel config
  charts/seed-bootstrap/charts/monitoring/templates/config.yaml
Labels: size/XS, area/monitoring, kind/cleanup, cla: yes, lgtm, approved

#7877 Change trigger for static token secret rotation
  pkg/operation/botanist/secrets.go
  pkg/operator/controller/garden/reconciler.go
  pkg/utils/version/version.go
Labels: kind/enhancement, area/security, size/S, cla: yes, lgtm, approved

#7866 Promote `FullNetworkPoliciesInRuntimeCluster` feature gate to beta
  docs/deployment/feature_gates.md
  example/gardener-local/gardenlet/values.yaml
  pkg/features/features.go
  pkg/gardenlet/controller/networkpolicy/add_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_suite_test.go
Labels: kind/enhancement, size/L, area/networking, cla: yes, lgtm, approved

#7888 Extend the SeedPredicate of `controllerregistration` controller
  pkg/controllermanager/controller/controllerregistration/seed/add.go
  pkg/controllermanager/controller/controllerregistration/seed/add_test.go
Labels: kind/enhancement, area/quality, size/S, cla: yes, lgtm, approved

#7878 Enhance validation for `worker.maximum` configuration
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: kind/api-change, area/usability, size/L, area/high-availability, cla: yes, lgtm, approved

#7859 [operator] Enable `NetworkPolicy` protection in garden cluster
  charts/gardener/operator/templates/_helpers.tpl
  charts/gardener/operator/templates/clusterrole.yaml
  charts/gardener/operator/templates/customresouredefintion.yaml
  charts/gardener/operator/templates/deployment.yaml
  charts/gardener/operator/templates/networkpolicy.yaml
  charts/gardener/operator/values.yaml
  cmd/gardenlet/app/app.go
  docs/api-reference/operator.md
  docs/concepts/gardenlet.md
  docs/concepts/operator.md
  docs/deployment/feature_gates.md
  example/operator/10-componentconfig.yaml
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/networkpolicy/add.go
  pkg/controller/networkpolicy/add_test.go
  pkg/controller/networkpolicy/helper/helper.go
  pkg/controller/networkpolicy/helper/helper_suite_test.go
  pkg/controller/networkpolicy/helper/helper_test.go
  pkg/controller/networkpolicy/hostnameresolver/resolver.go
  pkg/controller/networkpolicy/hostnameresolver/resolver_test.go
  pkg/controller/networkpolicy/networkpolicy_suite_test.go
  pkg/controller/networkpolicy/peers.go
  pkg/controller/networkpolicy/reconciler.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/networkpolicy/add.go
  pkg/gardenlet/controller/networkpolicy/add_test.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/shared/resourcemanager.go
  pkg/operator/apis/config/types.go
  pkg/operator/apis/config/v1alpha1/types.go
  pkg/operator/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/operator/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/apis/config/zz_generated.deepcopy.go
  pkg/operator/controller/add.go
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/garden/reconciler_delete.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  pkg/operator/controller/networkpolicyregistrar/add.go
  pkg/operator/controller/networkpolicyregistrar/reconciler.go
  pkg/operator/features/features.go
  pkg/operator/webhook/validation/handler_test.go
  pkg/utils/gardener/seed.go
  pkg/utils/gardener/seed_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/e2e/operator/garden/common.go
  test/integration/gardenlet/networkpolicy/networkpolicy_suite_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden_test.go
Labels: kind/enhancement, area/security, area/networking, cla: yes, lgtm, approved, size/XXL

#7861 Add options to configure `{NotReady,Unreachable}TolerationSeconds`
  charts/gardener/gardenlet/templates/_helpers.tpl
  charts/gardener/gardenlet/templates/deployment.yaml
  charts/gardener/gardenlet/values.yaml
  charts/gardener/operator/templates/_helpers.tpl
  charts/gardener/operator/templates/deployment.yaml
  charts/gardener/operator/values.yaml
  charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml
  charts/gardener/resource-manager/charts/runtime/templates/deployment.yaml
  charts/gardener/resource-manager/values.yaml
  docs/concepts/resource-manager.md
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/gardenlet/values-kind-ha-multi-zone.yaml
  example/gardener-local/gardenlet/values-kind-ha-single-zone.yaml
  example/operator/10-componentconfig.yaml
  example/resource-manager/10-componentconfig.yaml
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/validation/validation.go
  pkg/gardenlet/apis/config/validation/validation_test.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/shared/resourcemanager.go
  pkg/operation/botanist/resource_manager.go
  pkg/operation/botanist/resource_manager_test.go
  pkg/operator/apis/config/types.go
  pkg/operator/apis/config/v1alpha1/types.go
  pkg/operator/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/operator/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/apis/config/validation/validation.go
  pkg/operator/apis/config/validation/validation_test.go
  pkg/operator/apis/config/zz_generated.deepcopy.go
  pkg/operator/controller/garden/components.go
  pkg/resourcemanager/apis/config/types.go
  pkg/resourcemanager/apis/config/v1alpha1/types.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/resourcemanager/apis/config/validation/validation.go
  pkg/resourcemanager/apis/config/validation/validation_test.go
  pkg/resourcemanager/apis/config/zz_generated.deepcopy.go
  pkg/resourcemanager/webhook/add.go
  pkg/resourcemanager/webhook/highavailabilityconfig/handler.go
  skaffold-operator.yaml
  test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_suite_test.go
  test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_test.go
Labels: kind/enhancement, size/XL, area/high-availability, cla: yes, lgtm, approved

#7897 Update gardener/autoscaler for K8S v1.21 , v1.22 , v1.23 , v1.24 , v1.25 , v1.26
  charts/images.yaml
Labels: kind/enhancement, size/S, area/auto-scaling, cla: yes, lgtm, approved

#7886 Remove `.spec.kubernetes.kubeAPIServer.enableBasicAuthentication` field from the Shoot API
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/core.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/types_shoot_test.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/types_shoot_test.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: kind/api-change, kind/cleanup, area/control-plane, cla: yes, lgtm, approved, size/XXL

#7904 Bump `nginx-ingress-controller-seed` to `v1.7.1` for `1.24.x+` seeds
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/open-source, area/control-plane, cla: yes, lgtm, approved

#7908 Fix nil pointer panic
  extensions/pkg/controller/healthcheck/healthcheck_actuator.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#7910 Fix Istio-Ingress `service` annotation issue
  pkg/operation/seed/seed.go
  pkg/operation/seed/seed_test.go
  pkg/utils/test/matchers/matchers.go
  pkg/utils/test/matchers/reference.go
  pkg/utils/test/matchers/reference_test.go
Labels: kind/bug, size/L, area/control-plane, cla: yes, lgtm, approved

#7912 Skip deleting stale `kube-proxy` resources on hibernation
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
Labels: kind/bug, area/ops-productivity, size/XS, area/robustness, cla: yes, lgtm, approved

#7903 Expand `ClusterRole` of `fluent-operator`
  pkg/operation/botanist/component/logging/fluentoperator/fluent_operator.go
  pkg/operation/botanist/component/logging/fluentoperator/fluent_operator_test.go
Labels: kind/bug, size/M, area/logging, cla: yes, lgtm, approved

#7894 Don't allow shoot to scale up to HA if it is hibernated
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: kind/enhancement, size/M, area/high-availability, area/control-plane, cla: yes, lgtm, approved

#7892 Upgrade prometheus to v2.43.1
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#7923 Improve the formatting of grafana.dashboards.data
  charts/seed-monitoring/charts/grafana/templates/_helpers.tpl
Labels: kind/enhancement, size/M, area/monitoring, cla: yes, lgtm, approved

#7927 Update cluster-proportional-autoscaler to v1.8.8
  charts/images.yaml
Labels: kind/enhancement, area/security, size/XS, cla: yes, lgtm, approved

#7930 Fix race in `gardener-operator` integration test suite
  pkg/operation/botanist/component/shared/resourcemanager.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  test/integration/operator/garden/garden_test.go
Labels: area/dev-productivity, size/M, kind/flake, cla: yes, lgtm, approved

#7932 Bump `nginx-ingress-controller` addon image to v1.3.0 for 1.22+ shoots
  charts/images.yaml
  pkg/operation/botanist/component/nginxingressshoot/nginxingress.go
  pkg/operation/botanist/component/nginxingressshoot/nginxingress_test.go
Labels: kind/enhancement, area/open-source, size/M, cla: yes, lgtm, approved

#7907 Extend `NetworkPolicy` controller to allow multiple custom pod label selectors
  charts/gardener/gardenlet/templates/service.yaml
  charts/gardener/provider-local/extension/templates/service.yaml
  charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/service.yaml
  charts/seed-bootstrap/charts/loki/templates/logging-service.yaml
  charts/seed-bootstrap/charts/loki/templates/service.yaml
  charts/seed-bootstrap/templates/alertmanager/alertmanager.yaml
  charts/seed-bootstrap/templates/prometheus/service.yaml
  charts/seed-monitoring/charts/alertmanager/templates/alertmanager.yaml
  docs/concepts/resource-manager.md
  docs/usage/network_policies.md
  example/provider-local/garden/base/controller-registration.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/resources/v1alpha1/types.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler_test.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/hvpa/hvpa_test.go
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/service.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/service.yaml
  pkg/operation/botanist/component/istio/istio_test.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_service_test.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/operation/botanist/component/logging/fluentoperator/customresources/fluent_bit.go
  pkg/operation/botanist/component/logging/fluentoperator/customresources/fluent_bit_test.go
  pkg/operation/botanist/component/machinecontrollermanager/machine_controller_manager_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/vpa/admissioncontroller.go
  pkg/operation/botanist/component/vpa/vpa_test.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server_test.go
  pkg/resourcemanager/controller/networkpolicy/add.go
  pkg/resourcemanager/controller/networkpolicy/add_test.go
  pkg/resourcemanager/controller/networkpolicy/reconciler.go
  pkg/utils/gardener/networkpolicy.go
  pkg/utils/gardener/networkpolicy_test.go
  test/integration/operator/garden/garden_test.go
  test/integration/resourcemanager/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, area/security, size/XL, area/networking, cla: yes, lgtm, approved

#7935 Nit: Annotate the garden resources with confirmation annotation during `make operator-down`
  Makefile
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7933 topology-aware routing: Adapt to the upstream annotation change in K8s 1.27
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/service.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/service.yaml
  docs/usage/topology_aware_routing.md
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_service.go
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_service_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/shared/resourcemanager.go
  pkg/operation/botanist/component/vpa/admissioncontroller.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/kubeapiserverexposure.go
  pkg/operator/controller/garden/components.go
  pkg/utils/gardener/topology_aware_routing.go
  pkg/utils/gardener/topology_aware_routing_test.go
Labels: kind/enhancement, size/L, area/networking, area/high-availability, cla: yes, lgtm, approved

#7906 Extension resource health check enhancement
  extensions/pkg/predicate/default.go
  extensions/pkg/predicate/default_test.go
  pkg/operation/botanist/component/extensions/backupentry/backupentry_test.go
  pkg/operation/botanist/component/extensions/containerruntime/containerruntime_test.go
  pkg/operation/botanist/component/extensions/controlplane/controlplane_test.go
  pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go
  pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go
  pkg/operation/botanist/component/extensions/infrastructure/infrastructure.go
  pkg/operation/botanist/component/extensions/infrastructure/infrastructure_test.go
  pkg/operation/botanist/component/extensions/network/network_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/operation/botanist/component/extensions/worker/worker_test.go
  pkg/utils/kubernetes/health/extensions.go
  pkg/utils/kubernetes/health/extensions_test.go
Labels: kind/enhancement, area/quality, size/L, area/robustness, cla: yes, lgtm, approved

#7936 Improve `make check-apidiff`
  hack/check-apidiff.sh
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#7937 Add sample to create expiring kubeconfig with controller runtime
  docs/usage/shoot_access.md
Labels: area/dev-productivity, area/documentation, kind/cleanup, size/S, ok-to-test, cla: yes, lgtm, approved

#7855 Improve validation for machine types, images, and volumes in the Shoot
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, size/XL, area/ops-productivity, area/usability, cla: yes, lgtm, approved

#7942 adjust default fluent-bit log level
  pkg/operation/botanist/component/logging/fluentoperator/customresources/cluster_fluent_bit_config.go
  pkg/operation/botanist/component/logging/fluentoperator/customresources/cluster_fluent_bit_config_test.go
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#7943 Move fluent-bit persistent folder from /opt/fluent-bit to /var/fluent…
  pkg/operation/botanist/component/logging/fluentoperator/customresources/cluster_inputs.go
  pkg/operation/botanist/component/logging/fluentoperator/customresources/cluster_inputs_test.go
  pkg/operation/botanist/component/logging/fluentoperator/customresources/fluent_bit.go
  pkg/operation/botanist/component/logging/fluentoperator/customresources/fluent_bit_test.go
Labels: kind/bug, area/logging, size/S, cla: yes, lgtm, approved

#7931 [operator] Manage Virtual Garden `kube-controller-manager` Deployment
  charts/gardener/operator/templates/customresouredefintion.yaml
  charts/gardener/operator/templates/role.yaml
  docs/api-reference/operator.md
  docs/concepts/operator.md
  docs/development/priority-classes.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  example/operator/doc.go
  hack/generate-crds.sh
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/zz_generated.defaults.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/operation/botanist/component/shared/kubecontrollermanager.go
  pkg/operation/botanist/kubecontrollermanager.go
  pkg/operation/botanist/kubecontrollermanager_test.go
  pkg/operation/botanist/resource_manager.go
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/garden/reconciler_delete.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  pkg/operator/webhook/defaulting/handler.go
  skaffold-operator.yaml
  test/e2e/gardener/managedseed/create_rotate_delete.go
  test/e2e/gardener/shoot/create_rotate_delete.go
  test/e2e/gardener/shoot/create_update_delete.go
  test/e2e/gardener/shoot/internal/node/node.go
  test/e2e/gardener/shoot/internal/rotation/shoot_access.go
  test/e2e/operator/garden/create_delete.go
  test/e2e/operator/garden/create_rotate_delete.go
  test/e2e/operator/garden/internal/rotation/virtual_garden_access.go
  test/framework/k8s_utils.go
  test/framework/shootframework.go
  test/framework/shootmigrationtest.go
  test/integration/operator/garden/garden_test.go
  test/testmachinery/shoots/vpntunnel/vpntunnel.go
  test/utils/access/adminkubeconfig.go
  test/utils/access/csr.go
  test/utils/access/serviceaccount.go
  test/utils/access/statictokenkubeconfig.go
  test/utils/shoots/update/update.go
Labels: kind/enhancement, area/dev-productivity, area/delivery, cla: yes, lgtm, approved, size/XXL

#7939 Document guidelines for `TODO` statements
  docs/development/process.md
Labels: kind/enhancement, area/dev-productivity, area/documentation, size/L, cla: yes, lgtm, approved

#7929 Extend `NetworkPolicy` controllers to allow covering custom/additional namespaces
  charts/gardener/gardenlet/templates/_helpers.tpl
  charts/gardener/gardenlet/values.yaml
  charts/gardener/operator/templates/_helpers.tpl
  charts/gardener/operator/values.yaml
  docs/concepts/gardenlet.md
  docs/usage/network_policies.md
  example/20-componentconfig-gardenlet.yaml
  example/operator/10-componentconfig.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/kubeapiserverexposure/kube_apiserver_service.go
  pkg/component/kubeapiserverexposure/kube_apiserver_service_test.go
  pkg/component/resourcemanager/resource_manager.go
  pkg/component/resourcemanager/resource_manager_test.go
  pkg/component/shared/resourcemanager.go
  pkg/controller/networkpolicy/add.go
  pkg/controller/networkpolicy/reconciler.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/validation/validation.go
  pkg/gardenlet/apis/config/validation/validation_test.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/gardenlet/controller/networkpolicy/add.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operator/apis/config/types.go
  pkg/operator/apis/config/v1alpha1/types.go
  pkg/operator/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/operator/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/apis/config/validation/validation.go
  pkg/operator/apis/config/validation/validation_test.go
  pkg/operator/apis/config/zz_generated.deepcopy.go
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/networkpolicyregistrar/reconciler.go
  test/integration/gardenlet/networkpolicy/networkpolicy_suite_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
  test/integration/operator/garden/garden_test.go
Labels: kind/enhancement, area/security, size/XL, area/networking, cla: yes, lgtm, approved

#7947 Fixed broken links - 2023.05 (Part 2 - rebased)
  docs/concepts/gardenlet.md
  docs/development/component-checklist.md
  docs/extensions/controlplane.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#7946 Reconcile dnsrecord when status is outdated
  pkg/component/extensions/dnsrecord/dnsrecord.go
  pkg/component/extensions/dnsrecord/dnsrecord_test.go
Labels: kind/bug, area/quality, size/M, area/robustness, cla: yes, lgtm, approved

#7865 Fix: Grafana dashboard of VPN
  charts/seed-monitoring/charts/plutono/dashboards/owners/worker/vpn-dashboard.json
Labels: kind/bug, area/monitoring, size/S, ok-to-test, cla: yes, lgtm, approved

#7913 Allow the kubelet configuration to define swap behaviour for k8s >= 1.22
  docs/api-reference/core.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
  pkg/openapi/openapi_generated.go
Labels: kind/enhancement, area/os, cla: yes, lgtm, approved, size/XXL

#7950 Fix `NetworkPolicy` for scraping machine-controller-manager
  charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/service.yaml
Labels: kind/bug, area/security, size/XS, area/networking, cla: yes, lgtm, approved

#7957 Fix Seed logging test
  test/framework/dump.go
  test/testmachinery/shoots/logging/seed_logging_stack.go
  test/testmachinery/shoots/logging/utils.go
Labels: kind/bug, size/M, area/logging, area/testing, cla: yes, lgtm, approved

#7962 Fixed vpn dashboard location after workerless shoot monitoring change
  charts/seed-monitoring/charts/plutono/dashboards/owners/worker/vpn-seed-server/envoy-proxy-dashboard.json
  charts/seed-monitoring/charts/plutono/dashboards/owners/worker/vpn-seed-server/vpn-seed-server-dashboard.json
Labels: kind/bug, size/XS, area/monitoring, area/networking, cla: yes, lgtm, approved

#7966 Reconcile infrastructure when status is outdated
  pkg/component/extensions/infrastructure/infrastructure.go
  pkg/component/extensions/infrastructure/infrastructure_test.go
Labels: kind/bug, area/quality, size/M, area/robustness, cla: yes, lgtm, approved

#7960 Drop Kubernetes version support timeline docs
  docs/usage/supported_k8s_versions.md
Labels: area/documentation, kind/cleanup, size/S, cla: yes, lgtm, approved

#7896 add new dashboard of seed deployment replicas
  charts/seed-bootstrap/dashboards/seed-deployments-replicas.json
Labels: kind/enhancement, area/ops-productivity, size/L, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#7928 Require provider extension for seed type
  docs/concepts/controller-manager.md
  pkg/controllermanager/controller/controllerregistration/seed/reconciler.go
  pkg/controllermanager/controller/controllerregistration/seed/reconciler_test.go
  pkg/controllermanager/controller/seed/extensionscheck/reconciler.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/botanist.go
  pkg/utils/gardener/seed.go
  pkg/utils/gardener/seed_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  test/integration/controllermanager/controllerregistration/controllerregistration_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
Labels: kind/enhancement, size/XL, area/control-plane, cla: yes, lgtm, approved

#7952 Update etcd-druid CRDs and dependency
  example/seed-crds/10-crd-druid.gardener.cloud_etcds.yaml
  go.mod
  go.sum
  pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcds.yaml
  skaffold-operator.yaml
  skaffold.yaml
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/types_common.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/types_etcd.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/types_etcdcopybackupstask.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/etcd-druid/api/validation/etcd.go
  vendor/github.com/gardener/etcd-druid/pkg/common/constants.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/image.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/k8sversion.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/miscellaneous.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/names.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/statefulset.go
  vendor/github.com/gardener/etcd-druid/pkg/utils/store.go
  vendor/modules.txt
Labels: kind/enhancement, cla: yes, lgtm, approved, size/XXL

#7909 Lock the Seed's `.spec.settings.ownerChecks.enabled` field to `false`
  docs/api-reference/core.md
  example/50-seed.yaml
  example/provider-extensions/gardenlet/values.yaml.tmpl
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
  pkg/controllerutils/predicate/predicate.go
  pkg/controllerutils/predicate/predicate_test.go
  pkg/gardenlet/apis/config/helper/helpers.go
  pkg/gardenlet/apis/config/helper/helpers_test.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/dnsresources_test.go
  pkg/utils/gardener/migration.go
  pkg/utils/gardener/migration_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: size/L, kind/cleanup, area/control-plane-migration, cla: yes, lgtm, approved

#7958 Drop migration code for `istio` `ManagedResource` split
  pkg/component/istio/charts/istio/istio-istiod/templates/autoscale.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/clusterrole.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/clusterrolebinding.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/configmap.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/deployment.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/destinationrule.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/namespace.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/peerauthentication.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/poddisruptionbudget.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/role.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/rolebinding.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/service.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/serviceaccount.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/sidecar.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/validatingwebhookconfiguration.yaml
  pkg/component/istio/charts/istio/istio-istiod/values.yaml
  pkg/component/istio/istio_test.go
  pkg/component/istio/istiod.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#7949 Clean up unused field from the `pkg/registry/core/seed.Strategy`
  pkg/registry/core/rest/storage_core.go
  pkg/registry/core/seed/storage/storage.go
  pkg/registry/core/seed/strategy.go
Labels: kind/cleanup, size/S, cla: yes, lgtm, approved

#7970 Set kindest/node image and Shoot K8s version to 1.27 for e2e tests
  Makefile
  example/gardener-local/kind/cluster/values.yaml
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_rotate_delete.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/enhancement, area/open-source, size/S, cla: yes, lgtm, approved

#7975 Reconcile `networkpolicy`s on `Update` events of `Garden`
  pkg/operator/controller/networkpolicyregistrar/add.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#7979 Fix the slow startup and termination of the vali-0 pod
  charts/seed-bootstrap/charts/vali/templates/_helpers.tpl
  charts/seed-bootstrap/charts/vali/templates/statefulset.yaml
  charts/seed-bootstrap/charts/vali/values.yaml
Labels: kind/enhancement, area/logging, size/S, cla: yes, lgtm, approved

#7984 Harmonize license headers
  NOTICE.md
  hack/cherry-pick-pull.sh
  pkg/admissioncontroller/webhook/auth/seed/attributes.go
  pkg/admissioncontroller/webhook/auth/seed/graph/doc.go
  pkg/component/logging/fluentoperator/custom_resources.go
  pkg/component/logging/fluentoperator/custom_resources_test.go
  pkg/component/logging/fluentoperator/customresources/cluster_filters.go
  pkg/component/logging/fluentoperator/customresources/cluster_fluent_bit_config.go
  pkg/component/logging/fluentoperator/customresources/cluster_inputs.go
  pkg/component/logging/fluentoperator/customresources/cluster_outputs.go
  pkg/component/logging/fluentoperator/customresources/cluster_parsers.go
  pkg/component/logging/fluentoperator/customresources/fluent_bit.go
  pkg/component/logging/fluentoperator/fluent_operator.go
  pkg/component/logging/fluentoperator/fluent_operator_test.go
  pkg/component/logging/vali/logging_test.go
  pkg/component/monitoring/logging.go
  pkg/component/monitoring/logging_test.go
  pkg/component/nginxingressshoot/logging.go
  pkg/component/nginxingressshoot/logging_test.go
  pkg/component/shared/fluent_operator.go
  pkg/component/shared/fluent_operator_custom_resources.go
  pkg/controllermanager/controller/certificatesigningrequest/reconciler.go
  pkg/envtest/port.go
  pkg/gardenlet/bootstrap/certificate/certificate_util.go
  test/framework/cleanup.go
Labels: kind/enhancement, size/M, area/compliance, cla: yes, lgtm, approved

#7983 Add the `networkpolicy` reconciler only if the `.spec.runtimeCluster.networking.{pods,services}` fields are set
  pkg/operator/controller/networkpolicyregistrar/add.go
  pkg/operator/controller/networkpolicyregistrar/add_test.go
  pkg/operator/controller/networkpolicyregistrar/garden_suite_test.go
Labels: kind/bug, size/L, area/control-plane, cla: yes, lgtm, approved

#7988 Upgraded ETCD druid from v0.17.0 to v0.18.1
  charts/images.yaml
  pkg/component/etcd/bootstrap.go
  pkg/component/etcd/bootstrap_test.go
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#7956 Unify build dates in Skaffold
  Makefile
  hack/get-build-ld-flags.sh
Labels: area/dev-productivity, size/XS, kind/cleanup, cla: yes, lgtm, approved

#7981 Improve accuracy of local control plane migration e2e tests
  extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  extensions/pkg/controller/worker/genericactuator/actuator_test.go
  extensions/pkg/controller/worker/genericactuator/machine_controller_manager.go
  pkg/provider-local/controller/worker/actuator.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#7968 Minor nits in the `provider-extensions` setup
  example/provider-extensions/seed/configure-seed.sh
  example/provider-extensions/seed/create-seed.sh
  pkg/operator/controller/garden/garden_suite_test.go
Labels: kind/bug, area/dev-productivity, size/XS, area/usability, cla: yes, lgtm, approved

#7978 Refactor `blackbox exporter` Helm chart into Golang component
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/_helpers.tpl
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/config.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/pdb.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/service.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/serviceaccount.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/vpa.yaml
  pkg/component/blackboxexporter/blackboxexporter.go
  pkg/component/blackboxexporter/blackboxexporter_suite_test.go
  pkg/component/blackboxexporter/blackboxexporter_test.go
  pkg/component/blackboxexporter/mock/doc.go
  pkg/component/blackboxexporter/mock/mocks.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/blackboxexporter.go
  pkg/operation/botanist/blackboxexporter_test.go
  pkg/operation/botanist/botanist.go
  pkg/operation/shoot/types.go
  skaffold.yaml
Labels: area/dev-productivity, area/quality, kind/test, area/robustness, kind/technical-debt, cla: yes, lgtm, approved, size/XXL

#7992 fix broken links in monitoring-stack documentation
  docs/development/monitoring-stack.md
Labels: kind/bug, size/XS, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#7973 Refactor `node-exporter` Helm chart into component
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/psp/node-exporter-clusterrole.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/psp/node-exporter-psp.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/psp/node-exporter-rolebinding.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/vpa.yaml
  charts/shoot-core/components/values.yaml
  pkg/component/monitoring/logging.go
  pkg/component/monitoring/logging_test.go
  pkg/component/nodeexporter/logging.go
  pkg/component/nodeexporter/logging_test.go
  pkg/component/nodeexporter/mock/doc.go
  pkg/component/nodeexporter/mock/mocks.go
  pkg/component/nodeexporter/nodeexporter.go
  pkg/component/nodeexporter/nodeexporter_test.go
  pkg/component/nodeexporter/nodexporter_suite_test.go
  pkg/component/vpnshoot/vpnshoot.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/nodeexporter.go
  pkg/operation/botanist/nodeexporter_test.go
  pkg/operation/shoot/types.go
  skaffold.yaml
Labels: area/dev-productivity, area/quality, kind/test, area/robustness, kind/technical-debt, cla: yes, lgtm, approved, size/XXL

#7980 Move `apiserver-proxy-pod-webhook` logic into `gardener-resource-manager`
  charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml
  charts/gardener/resource-manager/values.yaml
  charts/images.yaml
  docs/concepts/resource-manager.md
  example/resource-manager/10-componentconfig.yaml
  hack/.ci/set_dependency_version
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/resources/v1alpha1/types.go
  pkg/component/apiserverproxy/apiserver_proxy.go
  pkg/component/apiserverproxy/apiserver_proxy_test.go
  pkg/component/kubeapiserver/deployment.go
  pkg/component/kubeapiserver/hvpa.go
  pkg/component/kubeapiserver/kube_apiserver.go
  pkg/component/kubeapiserver/kube_apiserver_test.go
  pkg/component/kubeapiserver/logging.go
  pkg/component/kubeapiserver/logging_test.go
  pkg/component/kubeapiserver/secrets.go
  pkg/component/resourcemanager/resource_manager.go
  pkg/component/resourcemanager/resource_manager_test.go
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/component/shared/resourcemanager.go
  pkg/operation/botanist/apiserverproxy.go
  pkg/operation/botanist/dns.go
  pkg/operation/botanist/dns_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operation/botanist/resource_manager.go
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  pkg/resourcemanager/apis/config/types.go
  pkg/resourcemanager/apis/config/v1alpha1/types.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/resourcemanager/apis/config/zz_generated.deepcopy.go
  pkg/resourcemanager/webhook/add.go
  pkg/resourcemanager/webhook/kubernetesservicehost/add.go
  pkg/resourcemanager/webhook/kubernetesservicehost/handler.go
  pkg/utils/images/images.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/resourcemanager/kubernetesservicehost/kubernetesservicehost_suite_test.go
  test/integration/resourcemanager/kubernetesservicehost/kubernetesservicehost_test.go
Labels: area/dev-productivity, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#7996 Deflake integration tests
  pkg/component/kubeapiserver/kube_apiserver.go
  pkg/component/kubecontrollermanager/waiter.go
  test/integration/gardenlet/shoot/care/care_suite_test.go
  test/integration/gardenlet/shoot/care/care_test.go
  test/integration/operator/garden/garden_test.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#7852 Cleanup Makefile
  Makefile
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#7989 Partially Revert "Drop `identity` value from Helm chart values"
  pkg/admissioncontroller/webhook/auth/seed/authorizer.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer_test.go
Labels: kind/bug, size/S, area/control-plane, cla: yes, lgtm, approved

#7953 [operator] Expose `kube-apiserver` via `Istio`
  charts/gardener/operator/templates/clusterrole.yaml
  docs/concepts/operator.md
  docs/development/testing.md
  example/gardener-local/kind/cluster/templates/_extra_port_mappings.tpl
  pkg/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/component/istio/charts/istio/istio-ingress/values.yaml
  pkg/component/istio/ingress_gateway.go
  pkg/component/istio/istio_test.go
  pkg/component/istio/istiod.go
  pkg/component/kubeapiserverexposure/kube_apiserver_sni.go
  pkg/component/kubeapiserverexposure/kube_apiserver_sni_test.go
  pkg/component/kubeapiserverexposure/templates/envoyfilter.yaml
  pkg/component/shared/istio.go
  pkg/component/shared/istio_test.go
  pkg/controller/service/reconciler.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/operation/botanist/kubeapiserverexposure.go
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/garden/reconciler_delete.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  skaffold-operator.yaml
  test/integration/operator/garden/garden_test.go
Labels: kind/enhancement, size/XL, area/scalability, cla: yes, lgtm, approved

#8000 Cleanup `core/v1alpha1` API version from local-setup
  docs/development/local_setup.md
  hack/local-development/dev-setup-register-gardener
Labels: area/dev-productivity, kind/cleanup, size/S, cla: yes, lgtm, approved
