Repository gardener/gardener, pull requests merged in 2023-12, with the labels that each got.

#8866 Don't set `EveryNodeReady` condition for workerless shoots
  pkg/controllermanager/controller/seed/lifecycle/reconciler.go
  test/integration/controllermanager/seed/lifecycle/lifecycle_test.go
Labels: kind/bug, size/L, area/control-plane, cla: yes, lgtm, approved

#8891 Fix `gardener-node-agent` image tag defaulting
  pkg/operation/botanist/operatingsystemconfig.go
Labels: kind/bug, area/usability, size/S, cla: yes, lgtm, approved

#8873 Promote `ContainerdRegistryHostsDir` feature gate to beta
  docs/deployment/feature_gates.md
  pkg/features/features.go
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8893 [node-agent] Restrict cache for `Lease`s to `kube-system` namespace
  cmd/gardener-node-agent/app/app.go
Labels: kind/bug, size/XS, area/quality, cla: yes, lgtm, approved

#8890 Add container registry for `europe-docker.pkg.dev` to local-setup
  example/gardener-local/registry-prow/kustomization.yaml
  example/gardener-local/registry/europe-docker-pkg-dev/kustomization.yaml
  example/gardener-local/registry/kustomization.yaml
  hack/kind-up.sh
  pkg/provider-local/webhook/controlplane/ensurer.go
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#8792 Local-Setup: add node internal IP addresses to istio-ingressgateway LB service
  charts/gardener/operator/templates/clusterrole.yaml
  pkg/controller/service/reconciler.go
Labels: kind/enhancement, area/dev-productivity, size/S, ok-to-test, cla: yes, lgtm, approved

#8902 [node-agent] Make hostname lower case
  cmd/gardener-node-agent/app/app.go
Labels: kind/bug, size/XS, area/usability, cla: yes, lgtm, approved

#8901 [node-agent] Restrict `Lease` cache when `Node` has already been registered
  cmd/gardener-node-agent/app/app.go
  pkg/nodeagent/controller/lease/lease_suite_test.go
  pkg/nodeagent/controller/lease/reconciler.go
  pkg/nodeagent/controller/lease/reconciler_test.go
  pkg/nodeagent/controller/operatingsystemconfig/reconciler.go
  pkg/nodeagent/nodeagent_suite_test.go
  pkg/nodeagent/nodename.go
  pkg/nodeagent/nodename_test.go
  skaffold.yaml
Labels: kind/enhancement, size/L, area/scalability, cla: yes, lgtm, approved

#8883 🧹 Cleanup a few `TODO`s
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  cmd/gardenlet/app/app.go
  extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  extensions/pkg/controller/worker/genericactuator/actuator_migrate.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/genericactuator/machine_controller_manager.go
  pkg/apis/resources/v1alpha1/types.go
  pkg/component/machinecontrollermanager/crd.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/shoot/shoot/cleaner.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  pkg/resourcemanager/controller/add.go
  pkg/resourcemanager/controller/networkpolicy/add.go
  pkg/resourcemanager/controller/networkpolicy/add_test.go
  pkg/resourcemanager/controller/networkpolicy/reconciler.go
  test/integration/resourcemanager/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#8905 Explicitly disable `UseGardenerNodeAgent` feature gate in local extensions setup
  example/gardener-local/gardenlet/values-provider-extensions.yaml
  example/provider-extensions/seed/create-seed.sh
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#8906 Promote `WorkerlessShoots` to `GA`
  docs/deployment/feature_gates.md
  pkg/features/features.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: kind/enhancement, area/open-source, size/M, cla: yes, lgtm, approved

#8907 [node-agent] `dbus` interface should not block and wait for result channel forever
  pkg/nodeagent/dbus/dbus.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#8854 Fix: Forbid creation/update of expired k8s/machine image versions
  docs/usage/shoot_versions.md
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, area/ops-productivity, size/L, cla: yes, lgtm, approved

#8910 Upgrade to golang 1.20.12-bookworm and 1.21.5-bookworm
  hack/tools/image/variants.yaml
Labels: kind/enhancement, size/XS, area/testing, needs-ok-to-test, cla: yes, lgtm, approved

#8911 Add new recording rule for kube apiserver latency
  pkg/component/kubeapiserver/monitoring.go
  pkg/component/kubeapiserver/monitoring_test.go
Labels: kind/enhancement, size/XS, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#8849 Update documentation concerning dockerhub IPv6 support
  docs/usage/ipv6.md
Labels: kind/enhancement, size/XS, area/documentation, area/networking, cla: yes, lgtm, approved

#8919 [node-agent] Stop waiting for systemd command results after `10s`
  cmd/gardener-node-agent/app/app.go
  pkg/nodeagent/controller/node/add.go
  pkg/nodeagent/controller/operatingsystemconfig/add.go
  pkg/nodeagent/dbus/dbus.go
Labels: kind/enhancement, size/M, area/robustness, cla: yes, lgtm, approved

#8925 Fix Update PR generation for filter extension
  hack/.ci/set_dependency_version
Labels: kind/bug, area/dev-productivity, size/XS, area/networking, cla: yes, lgtm, approved

#8933 Update apiserver-proxy to v0.15.0 and remove flag `--setup-iptables`
  imagevector/images.yaml
  pkg/component/apiserverproxy/apiserver_proxy.go
  pkg/component/apiserverproxy/apiserver_proxy_test.go
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#8935 Add support for optional `REPO_ROOT` environment var in `vgopath` enabled hack scripts
  hack/check-imports.sh
  hack/generate-crds.sh
  hack/update-codegen.sh
  hack/update-protobuf.sh
  hack/vgopath-setup.sh
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#8947 [ci:component:github.com/gardener/vpn2:0.20.0->0.21.0]
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8842 Support end-user configuration for encrypted resources in the Shoot
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/README.md
  docs/api-reference/core.md
  docs/api-reference/operator.md
  docs/concepts/operator.md
  docs/usage/etcd_encryption_config.md
  docs/usage/shoot_credentials_rotation.md
  example/90-shoot.yaml
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/component/apiserver/encryptionconfiguration.go
  pkg/component/apiserver/encryptionconfiguration_test.go
  pkg/component/apiserver/types.go
  pkg/component/gardenerapiserver/gardener_apiserver_test.go
  pkg/component/kubeapiserver/kube_apiserver_test.go
  pkg/component/shared/apiserver.go
  pkg/component/shared/apiserver_test.go
  pkg/component/shared/gardenerapiserver.go
  pkg/component/shared/gardenerapiserver_test.go
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/openapi/api_violations.report
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  pkg/utils/gardener/garden.go
  pkg/utils/gardener/garden_test.go
  pkg/utils/gardener/secretsrotation/etcd.go
  pkg/utils/gardener/secretsrotation/etcd_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  pkg/utils/miscellaneous.go
  pkg/utils/miscellaneous_test.go
Labels: kind/enhancement, area/control-plane, cla: yes, lgtm, approved, size/XXL

#8943 Fix CPM for hibernated Shoots
  extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  extensions/pkg/controller/worker/genericactuator/actuator_restore_test.go
Labels: kind/regression, size/S, area/control-plane-migration, cla: yes, lgtm, approved

#8952 Add e2e test for cpm of hibernated shoot
  docs/deployment/content/remote-local-setup.yaml
  docs/deployment/getting_started_locally.md
  hack/test-e2e-local.sh
  test/e2e/gardener/shoot/create_migrate_delete.go
Labels: kind/test, size/S, area/control-plane-migration, cla: yes, lgtm, approved

#8832 [scheduler] Clean up technical debt in defaulting code
  pkg/scheduler/apis/config/v1alpha1/defaults.go
  pkg/scheduler/apis/config/v1alpha1/defaults_test.go
  pkg/scheduler/apis/config/v1alpha1/register.go
  pkg/scheduler/apis/config/v1alpha1/zz_generated.defaults.go
Labels: area/dev-productivity, size/L, kind/technical-debt, cla: yes, lgtm, approved

#8955 typo in provider-extensions sshd port
  example/provider-extensions/ssh-reverse-tunnel/base/sshd/sshd_deployment.yaml
Labels: area/dev-productivity, size/XS, kind/cleanup, cla: yes, lgtm, approved

#8958 [ci:component:github.com/gardener/vpn2:0.21.0->0.22.0]
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#8888 egress cidrs
  docs/api-reference/extensions.md
  example/seed-crds/10-crd-extensions.gardener.cloud_infrastructures.yaml
  pkg/apis/extensions/v1alpha1/types_infrastructure.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_infrastructures.yaml
  pkg/component/extensions/infrastructure/infrastructure.go
  pkg/component/extensions/infrastructure/infrastructure_test.go
  pkg/component/extensions/infrastructure/mock/mocks.go
Labels: kind/enhancement, size/M, area/control-plane, cla: yes, lgtm, approved

#8957 Prepare next Dev Cycle v1.87.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8868 Delete MCM before deleting the MCM resources in the Shoot force deletion flow
  pkg/gardenlet/controller/shoot/shoot/cleaner.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_force_delete.go
Labels: kind/bug, size/S, cla: yes, lgtm, approved

#8959 Don't health check logging MR if seed is garden
  pkg/gardenlet/controller/seed/care/health.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#8964 Prevent reading encrypted resources with `shoots/viewerkubeconfig` subresource
  docs/usage/shoot_access.md
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/component/shared/apiserver.go
  pkg/component/shared/apiserver_test.go
  pkg/component/shootsystem/shootsystem.go
  pkg/component/shootsystem/shootsystem_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/shootsystem.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/enhancement, area/security, size/L, cla: yes, lgtm, approved

#8965 Revert "Spread Istio Ingress Gateway pods across hosts if there are multiple nodes per zone."
  pkg/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/component/istio/charts/istio/istio-ingress/values.yaml
  pkg/component/istio/ingress_gateway.go
  pkg/component/shared/istio.go
  pkg/component/shared/istio_test.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operator/controller/garden/garden/components.go
Labels: size/L, kind/cleanup, area/networking, cla: yes, lgtm, approved

#8896 Drop `spec.secretRef` field in Seed API
  docs/api-reference/core.md
  example/50-seed.yaml
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/types_seed_test.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
Labels: kind/api-change, kind/cleanup, area/control-plane, cla: yes, lgtm, approved, size/XXL

#8931 Improved kube-state-metrics Configuration
  pkg/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/component/kubestatemetrics/resources.go
  pkg/component/shared/kube_state_metrics.go
Labels: kind/enhancement, size/L, area/monitoring, area/robustness, area/control-plane, cla: yes, lgtm, approved

#8977 Correct the state of the `WorkerlessShoots` feature gate. Update K8s v1.28 conformance test coverage
  README.md
  pkg/features/features.go
Labels: kind/cleanup, size/S, cla: yes, lgtm, approved

#8786 [node-agent] Refactor `{kubelet,containerd}-monitor` health check bash scripts to Golang
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/rbac.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/rbac_test.go
  pkg/nodeagent/controller/add.go
  pkg/nodeagent/controller/healthcheck/add.go
  pkg/nodeagent/controller/healthcheck/containerd.go
  pkg/nodeagent/controller/healthcheck/healthcheck.go
  pkg/nodeagent/controller/healthcheck/healthcheck_suite_test.go
  pkg/nodeagent/controller/healthcheck/kubelet.go
  pkg/nodeagent/controller/healthcheck/kubelet_test.go
  pkg/nodeagent/controller/healthcheck/reconciler.go
  pkg/nodeagent/dbus/dbus.go
  pkg/nodeagent/dbus/fake/fake_dbus.go
  skaffold.yaml
  test/integration/nodeagent/healthcheck/healthcheck_suite_test.go
  test/integration/nodeagent/healthcheck/healthcheck_test.go
Labels: kind/enhancement, area/dev-productivity, ok-to-test, cla: yes, lgtm, approved, size/XXL

#8972 Mitigate random connection issues to virtual garden in local gardener operator setup.
  pkg/controller/service/reconciler.go
Labels: area/dev-productivity, size/XS, kind/regression, area/networking, cla: yes, lgtm, approved

#8979 Promote `ContainerdRegistryHostsDir` feature gate to GA
  docs/deployment/feature_gates.md
  docs/usage/containerd-registry-configuration.md
  example/gardener-local/gardenlet/values.yaml
  extensions/pkg/webhook/controlplane/genericmutator/.import-restrictions
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/containerd_suite_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/initializer.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/initializer_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/templates/scripts/init.tpl.sh
  pkg/features/features.go
Labels: kind/enhancement, size/L, cla: yes, lgtm, approved

#8976 Support for Kubernetes v1.29
  README.md
  docs/usage/supported_k8s_versions.md
  example/gardener-local/kind/cluster/values.yaml
  example/provider-local/garden/base/cloudprofile.yaml
  hack/compare-k8s-admission-plugins.sh
  hack/compare-k8s-api-groups.sh
  hack/compute-k8s-controllers.sh
  hack/tools.mk
  pkg/component/shootsystem/shootsystem.go
  pkg/component/shootsystem/shootsystem_test.go
  pkg/utils/kubernetes/controllers.go
  pkg/utils/validation/apigroups/apigroups.go
  pkg/utils/validation/features/featuregates.go
  pkg/utils/validation/kubernetesversion/version.go
  pkg/utils/validation/kubernetesversion/version_test.go
  pkg/utils/version/version.go
Labels: kind/enhancement, area/open-source, size/L, cla: yes, lgtm, approved

#8992 Deflake nodeagent health check integration test
  test/integration/nodeagent/healthcheck/healthcheck_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#8988 Prevent false positive PrometheusCantScrape alerts for the etcd-druid job
  pkg/component/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/rules/prometheus.rules.yaml
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved

#8953 [ResourceManager] Clean up technical debt in defaulting code
  pkg/resourcemanager/apis/config/v1alpha1/defaults.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults_test.go
  pkg/resourcemanager/apis/config/v1alpha1/register.go
Labels: area/dev-productivity, size/L, kind/technical-debt, cla: yes, lgtm, approved

#8985 [Gardenlet] Clean up technical debt in defaulting code
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/register.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/operator/apis/config/v1alpha1/defaults.go
Labels: area/dev-productivity, kind/technical-debt, cla: yes, lgtm, approved, size/XXL
