Repository gardener/gardener, pull requests merged in 2023-01, with the labels that each got.

#7273 Fix `make start-gardenlet` for a new Seed
  hack/local-development/start-gardenlet
Labels: kind/bug, area/dev-productivity, size/XS, kind/regression, cla: yes, lgtm, approved

#7261 Make use of kubelet's node lease feature in shoot clusters
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
Labels: kind/enhancement, area/performance, size/XS, ok-to-test, cla: yes, lgtm, approved

#7260 Documentation Clean Up - Part 1 (Concepts)
  docs/README.md
  docs/concepts/admission-controller.md
  docs/concepts/apiserver.md
  docs/concepts/apiserver_admission_plugins.md
  docs/concepts/architecture.md
  docs/concepts/backup-restore.md
  docs/concepts/cluster-api.md
  docs/concepts/controller-manager.md
  docs/concepts/etcd.md
  docs/concepts/gardenlet.md
  docs/concepts/network_policies.md
  docs/concepts/operator.md
  docs/concepts/resource-manager.md
  docs/concepts/scheduler.md
  docs/proposals/01-extensibility.md
  docs/proposals/13-automated-seed-management.md
  docs/proposals/15-manage-bastions-and-ssh-key-pair-rotation.md
  docs/usage/shoot_status.md
Labels: kind/enhancement, size/XL, area/documentation, cla: yes, lgtm, approved

#7283 Add disableForwardToUpstreamDNS option to shoot example.
  example/90-shoot.yaml
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#7267 Refactor `kubernetes-dashboard` Helm chart into Golang component
  charts/seed-bootstrap/charts/fluent-bit/templates/_helpers.tpl
  charts/shoot-addons/charts/kubernetes-dashboard/templates/_helpers.tpl
  charts/shoot-addons/charts/kubernetes-dashboard/templates/configmap.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/deployment-dashboard.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/deployment-metrics-scraper.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/namespace.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/rbac.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/secret.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/service-dashboard.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/service-metrics-scraper.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/serviceaccount.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/vpa.yaml
  charts/shoot-addons/requirements.yaml
  charts/shoot-addons/values.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/component/kubernetesdashboard/kubernetes_dashboard.go
  pkg/operation/botanist/component/kubernetesdashboard/kubernetes_dashboard_suite_test.go
  pkg/operation/botanist/component/kubernetesdashboard/kubernetes_dashboard_test.go
  pkg/operation/botanist/component/kubernetesdashboard/logging.go
  pkg/operation/botanist/component/kubernetesdashboard/logging_test.go
  pkg/operation/botanist/component/kubernetesdashboard/mock/doc.go
  pkg/operation/botanist/component/kubernetesdashboard/mock/mocks.go
  pkg/operation/botanist/kubernetesdashboard.go
  pkg/operation/botanist/kubernetesdashboard_test.go
  pkg/operation/shoot/shoot.go
  pkg/operation/shoot/types.go
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, area/quality, area/robustness, cla: yes, lgtm, approved, size/XXL

#7282 Upgrade node-exporter to v1.5.0
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#7246 [GEP-21] `DNSRecord`: add support for `AAAA` record type
  docs/extensions/dnsrecord.md
  pkg/apis/extensions/v1alpha1/helper/helper.go
  pkg/apis/extensions/v1alpha1/helper/helper_test.go
  pkg/apis/extensions/v1alpha1/types_dnsrecord.go
  pkg/apis/extensions/validation/dnsrecord.go
  pkg/apis/extensions/validation/dnsrecord_test.go
  pkg/provider-local/controller/ingress/reconciler.go
Labels: kind/enhancement, size/M, area/networking, ok-to-test, cla: yes, lgtm, approved

#7265 Support machine image versions to specify constraint for supported kubelet versions
  docs/api-reference/core.md
  example/30-cloudprofile.yaml
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_cloudprofile.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler_test.go
  pkg/openapi/openapi_generated.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, kind/api-change, cla: yes, lgtm, approved, size/XXL

#7291 Fix wrong count of pods per node in grafana dashboard
  charts/seed-monitoring/charts/grafana/dashboards/owners/node-pool-dashboard.json
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved

#7287 Cleanup deprecated Condition builder functions
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/controllermanager/controller/seed/backupbucketscheck/reconciler_test.go
  pkg/controllermanager/controller/seed/extensionscheck/reconciler_test.go
  pkg/gardenlet/controller/controllerinstallation/care/add.go
  pkg/gardenlet/controller/controllerinstallation/care/reconciler.go
  pkg/gardenlet/controller/controllerinstallation/care/reconciler_test.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/add.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/gardenlet/controller/controllerinstallation/required/add.go
  pkg/gardenlet/controller/controllerinstallation/required/reconciler.go
  pkg/gardenlet/controller/managedseed/actuator.go
  pkg/gardenlet/controller/managedseed/actuator_test.go
  pkg/gardenlet/controller/managedseed/add.go
  pkg/gardenlet/controller/managedseed/reconciler.go
  pkg/gardenlet/controller/seed/care/add.go
  pkg/gardenlet/controller/seed/care/reconciler.go
  pkg/gardenlet/controller/seed/care/reconciler_test.go
  pkg/gardenlet/controller/seed/care/types.go
  pkg/gardenlet/controller/seed/seed/add.go
  pkg/gardenlet/controller/seed/seed/reconciler.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/shoot/care/add.go
  pkg/gardenlet/controller/shoot/care/reconciler.go
  pkg/gardenlet/controller/shoot/care/reconciler_test.go
  pkg/gardenlet/controller/shoot/care/types.go
  pkg/operation/care/checker.go
  pkg/operation/care/constraints.go
  pkg/operation/care/health.go
  pkg/operation/care/health_check_test.go
  pkg/operation/care/seed_health.go
  pkg/operation/care/seed_health_test.go
  pkg/resourcemanager/controller/health/health/add.go
  pkg/resourcemanager/controller/health/health/reconciler.go
  pkg/resourcemanager/controller/health/progressing/add.go
  pkg/resourcemanager/controller/health/progressing/reconciler.go
  pkg/resourcemanager/controller/managedresource/add.go
  pkg/resourcemanager/controller/managedresource/reconciler.go
  pkg/utils/kubernetes/health/healthz.go
  pkg/utils/test/matchers/conditions.go
  test/integration/controllermanager/seed/backupbucketscheck/backupbucketscheck_suite_test.go
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_suite_test.go
  test/integration/resourcemanager/managedresource/resource_suite_test.go
  test/integration/resourcemanager/managedresource/resource_test.go
Labels: area/dev-productivity, size/XL, kind/cleanup, cla: yes, lgtm, approved

#7293 Release responsible schedule for v1.64 until v1.78
  docs/development/process.md
Labels: kind/enhancement, area/delivery, size/S, cla: yes, lgtm, approved

#7258 Adapt `kubeapiserver` component for "nodeless" scenario
  pkg/operation/botanist/component/kubeapiserver/configmaps.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/networkpolicies.go
  pkg/operation/botanist/component/kubeapiserver/secrets.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
Labels: kind/enhancement, size/XL, area/usability, cla: yes, lgtm, approved

#7225 [operator] Allow highly available deployment of virtual garden cluster control plane
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/operator.md
  docs/concepts/operator.md
  example/gardener-local/kind/operator/values.yaml
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_service.go
  pkg/operation/botanist/etcd.go
  pkg/operator/controller/garden/components.go
  pkg/operator/controller/garden/reconciler_delete.go
  pkg/operator/controller/garden/reconciler_reconcile.go
  pkg/operator/webhook/validation/handler.go
  pkg/operator/webhook/validation/handler_test.go
  test/e2e/operator/garden/common.go
  test/e2e/operator/garden/create_delete.go
  test/e2e/operator/garden/create_rotate_delete.go
Labels: kind/enhancement, size/L, area/high-availability, cla: yes, lgtm, approved

#7269 Raise error when `ip` command not found instead of skipping if `OS` is Mac.
  hack/kind-up.sh
Labels: kind/bug, area/dev-productivity, size/XS, kind/test, area/testing, cla: yes, lgtm, approved

#7292 local-provider: recociling permissions for local backup directory
  pkg/provider-local/controller/backupbucket/actuator.go
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7188 Add configuration `SSHAccess` for workers settings
  docs/README.md
  docs/api-reference/core.md
  docs/extensions/bastion.md
  docs/usage/shoot_workers_settings.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/bastion.go
  pkg/operation/botanist/bastion_test.go
  pkg/operation/botanist/component/extensions/infrastructure/infrastructure_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/components.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/sshdensurer/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/sshdensurer/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/sshdensurer/sshd_suite_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/sshdensurer/templates/scripts/disable-sshd.tpl.sh
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/sshdensurer/templates/scripts/enable-sshd.tpl.sh
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/original.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/original_test.go
  pkg/operation/botanist/infrastructure.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/secrets_test.go
  pkg/operation/botanist/worker.go
  plugin/pkg/bastion/validator/admission.go
  plugin/pkg/bastion/validator/admission_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  skaffold.yaml
Labels: kind/enhancement, area/security, area/compliance, cla: yes, lgtm, approved, size/XXL

#7278 Fix bug where `kubelet-monitor` kills processes other than `kubelet`
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/templates/scripts/health-monitor.tpl.sh
Labels: kind/bug, size/XS, area/robustness, ok-to-test, cla: yes, lgtm, approved

#7277 Add documentation on open endpoints/ports
  docs/README.md
  docs/usage/control-plane-endpoints-and-ports.md
  docs/usage/images/api-server-proxy.png
  docs/usage/images/api-server-sni.png
  docs/usage/images/reversed-vpn.png
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved

#7296 [extensions] Use dedicated timeout for actual health checks
  extensions/pkg/controller/healthcheck/reconciler.go
Labels: kind/bug, area/robustness, size/S, cla: yes, lgtm, approved

#7226 Add `HPA`/`HVPA` handling to `HighAvailabilityConfig` webhook.
  charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
  docs/concepts/resource-manager.md
  docs/development/high-availability.md
  example/resource-manager/10-mutatingwebhookconfiguration.yaml
  pkg/operation/botanist/component/coredns/coredns.go
  pkg/operation/botanist/component/coredns/coredns_test.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/kubeapiserver/hvpa.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/resourcemanager/webhook/highavailabilityconfig/handler.go
  test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_test.go
Labels: kind/enhancement, area/high-availability, cla: yes, lgtm, approved, size/XXL

#7253 Add Gardener CAs to CA bundle on Debian based OS
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/rootcertificates/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/rootcertificates/templates/scripts/update-local-ca-certificates.tpl.sh
Labels: kind/bug, size/L, area/os, cla: yes, lgtm, approved

#7309 Update to Go 1.19.5
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#7310 Documentation Clean Up - Part 2 (Deployments)
  docs/deployment/authentication_gardener_control_plane.md
  docs/deployment/configuring_logging.md
  docs/deployment/deploy_gardenlet.md
  docs/deployment/deploy_gardenlet_automatically.md
  docs/deployment/deploy_gardenlet_manually.md
  docs/deployment/feature_gates.md
  docs/deployment/gardenlet_api_access.md
  docs/deployment/getting_started_locally.md
  docs/deployment/getting_started_locally_with_extensions.md
  docs/deployment/image_vector.md
  docs/deployment/secret_binding_provider_controller.md
  docs/deployment/setup_gardener.md
  docs/deployment/version_skew_policy.md
Labels: kind/enhancement, area/documentation, size/L, cla: yes, lgtm, approved

#7304 Drop `nodeSelector` and `tolerations` from Shoot System Components
  charts/shoot-addons/charts/nginx-ingress/values.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-daemonset.yaml
  charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
  charts/shoot-core/components/charts/monitoring/charts/node-exporter/templates/node-exporter.yaml
  pkg/operation/botanist/component/coredns/coredns.go
  pkg/operation/botanist/component/coredns/coredns_test.go
  pkg/operation/botanist/component/kubeproxy/kube_proxy_test.go
  pkg/operation/botanist/component/kubeproxy/resources.go
  pkg/operation/botanist/component/kubernetesdashboard/kubernetes_dashboard.go
  pkg/operation/botanist/component/kubernetesdashboard/kubernetes_dashboard_test.go
  pkg/operation/botanist/component/metricsserver/metrics_server.go
  pkg/operation/botanist/component/metricsserver/metrics_server_test.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns_test.go
  pkg/operation/botanist/component/nodeproblemdetector/node_problem_detector.go
  pkg/operation/botanist/component/nodeproblemdetector/node_problem_detector_test.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot_test.go
Labels: size/M, kind/cleanup, area/scalability, cla: yes, lgtm, approved

#7305 Update HVPA to 0.9.0
  charts/images.yaml
  pkg/operation/botanist/component/hvpa/hvpa.go
  pkg/operation/botanist/component/hvpa/hvpa_test.go
Labels: kind/enhancement, size/XS, area/auto-scaling, ok-to-test, cla: yes, lgtm, approved

#7300 Document Kubernetes Version Support Policy
  docs/usage/supported_k8s_versions.md
Labels: kind/enhancement, area/documentation, area/open-source, size/M, cla: yes, lgtm, approved

#7268 Add means to by-pass readiness checks
  docs/usage/shoot_high_availability.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/enhancement, size/L, area/high-availability, area/control-plane, cla: yes, lgtm, approved

#7289 Add CVE re-scoring configuration to Logging stack images
  charts/images.yaml
Labels: kind/enhancement, size/M, area/logging, cla: yes, lgtm, approved

#7315 Fix `ManagedSeed` bootstrapping for Kubernetes 1.24+ clusters
  example/provider-local/managedseeds/shoot-managedseed.yaml
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer.go
  pkg/gardenlet/bootstrap/bootstrap.go
  pkg/gardenlet/bootstrap/util/util.go
  pkg/gardenlet/bootstrap/util/util_test.go
  pkg/gardenlet/controller/managedseed/actuator.go
Labels: kind/bug, area/usability, size/L, cla: yes, lgtm, approved

#7313 Improve `ServiceAccount` Signing Key Rotation Procedure
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/core.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  pkg/api/core/shoot/warnings.go
  pkg/api/core/shoot/warnings_test.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_common.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_common.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/secrets_test.go
  pkg/operator/controller/garden/reconciler.go
  test/e2e/gardener/shoot/internal/rotation/certificate_authorities.go
  test/e2e/gardener/shoot/internal/rotation/etcd_encryption_key.go
  test/e2e/gardener/shoot/internal/rotation/service_account_key.go
  test/e2e/operator/garden/internal/rotation/certificate_authorities.go
Labels: kind/enhancement, area/security, area/usability, cla: yes, lgtm, approved, size/XXL

#7275 Support for Kubernetes v1.26
  README.md
  charts/seed-monitoring/charts/grafana/dashboards/owners/apiserver-overview.json
  docs/api-reference/core.md
  docs/development/new-kubernetes-version.md
  docs/usage/shoot_access.md
  docs/usage/shoot_credentials_rotation.md
  docs/usage/supported_k8s_versions.md
  example/90-shoot.yaml
  example/provider-local/garden/base/cloudprofile.yaml
  example/provider-local/shoot.yaml
  hack/local-development/start-apiserver
  pkg/api/core/shoot/warnings.go
  pkg/api/core/shoot/warnings_test.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/client/kubernetes/client.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/monitoring.go
  pkg/operation/botanist/component/kubeapiserver/monitoring_test.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/component/shootsystem/shootsystem.go
  pkg/operation/botanist/component/shootsystem/shootsystem_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/utils/validation/admissionplugins/admissionplugins.go
  pkg/utils/validation/features/featuregates.go
  pkg/utils/version/version.go
  pkg/utils/version/version_test.go
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_update_delete.go
  test/framework/k8s_utils.go
  test/framework/resources/templates/default-shoot.yaml
  test/framework/resources/templates/simple-load-deployment.yaml.tpl
  test/framework/shootframework.go
  test/testmachinery/shoots/applications/shoot_app.go
  test/testmachinery/shoots/operations/operations.go
  test/testmachinery/shoots/vpntunnel/vpntunnel.go
  test/utils/shoots/access/adminkubeconfig.go
Labels: kind/enhancement, area/open-source, area/usability, cla: yes, lgtm, approved, size/XXL

#7326 Fix bug preventing shoot deletion when never reconciled at least once
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
Labels: kind/bug, size/XS, area/usability, cla: yes, lgtm, approved

#7327 Increase verbosity for check whether pods are still running
  test/e2e/gardener/shoot/create_and_delete_hibernated.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#7281 Improve reconciliation of extension `BackupBucket` and `BackupEntry`
  pkg/gardenlet/controller/backupbucket/reconciler.go
  pkg/gardenlet/controller/backupbucket/reconciler_test.go
  pkg/gardenlet/controller/backupentry/backupentry/reconciler.go
  pkg/gardenlet/controller/backupentry/backupentry/reconciler_test.go
  pkg/gardenlet/controller/bastion/reconciler.go
  test/integration/gardenlet/backupentry/backupentry/backupentry_suite_test.go
Labels: kind/bug, size/XL, area/control-plane, cla: yes, lgtm, approved

#7348 [release-v1.60] Improve reconciliation of extension `BackupBucket`
  pkg/gardenlet/controller/backupbucket/reconciler.go
  pkg/gardenlet/controller/backupbucket/reconciler_test.go
Labels: kind/bug, size/L, cla: yes, lgtm, approved

#7346 [release-v1.62] Improve reconciliation of extension `BackupBucket` and `BackupEntry`
  pkg/gardenlet/controller/backupbucket/reconciler.go
  pkg/gardenlet/controller/backupbucket/reconciler_test.go
  pkg/gardenlet/controller/backupentry/backupentry/reconciler.go
  pkg/gardenlet/controller/backupentry/backupentry/reconciler_test.go
  pkg/gardenlet/controller/bastion/reconciler.go
  test/integration/gardenlet/backupentry/backupentry/backupentry_suite_test.go
Labels: kind/bug, size/XL, cla: yes, lgtm, approved

#7336 Use metadata-only GET when reading secrets in `botanist.DeleteOldServiceAccountSecrets`.
  pkg/operation/botanist/secrets.go
Labels: kind/enhancement, size/XS, area/scalability, cla: yes, lgtm, approved

#7332 Revert `shootDNS` field removal
  docs/api-reference/core.md
  docs/development/changing-the-api.md
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/core/v1alpha1/types_seed_test.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/types_seed_test.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: kind/bug, area/control-plane, cla: yes, lgtm, approved, size/XXL

#7345 Add `VERSION` file in skaffold dependencies of gardener component
  hack/check-skaffold-deps.sh
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/bug, area/dev-productivity, size/S, cla: yes, lgtm, approved

#7353 [GEP-21] Use `int64` for `maxNodeCount` validation error
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: kind/bug, size/M, area/networking, cla: yes, lgtm, approved

#7324 Improve match for `service`s of problematic webhook detector
  pkg/operation/botanist/matchers/matcher.go
  pkg/operation/care/constraints_test.go
  pkg/operation/care/webhook_remediation_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#7329 Streamline integration tests
  docs/development/testing.md
  test/integration/controllermanager/bastion/bastion_test.go
  test/integration/controllermanager/managedseedset/managedseedset_suite_test.go
  test/integration/controllermanager/project/activity/activity_suite_test.go
  test/integration/controllermanager/project/project/project_test.go
  test/integration/controllermanager/project/stale/stale_suite_test.go
  test/integration/controllermanager/quota/quota_test.go
  test/integration/controllermanager/seed/backupbucketscheck/backupbucketscheck_suite_test.go
  test/integration/controllermanager/seed/backupbucketscheck/backupbucketscheck_test.go
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_suite_test.go
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go
  test/integration/controllermanager/seed/lifecycle/lifecycle_suite_test.go
  test/integration/controllermanager/seed/lifecycle/lifecycle_test.go
  test/integration/controllermanager/seed/secrets/secrets_suite_test.go
  test/integration/controllermanager/shoot/conditions/conditions_suite_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
  test/integration/envtest/envtest_suite_test.go
  test/integration/extensions/controller/heartbeat/heartbeat_suite_test.go
  test/integration/extensions/controller/heartbeat/heartbeat_test.go
  test/integration/gardenlet/backupbucket/backupbucket_suite_test.go
  test/integration/gardenlet/backupentry/backupentry/backupentry_suite_test.go
  test/integration/gardenlet/backupentry/migration/migration_suite_test.go
  test/integration/gardenlet/bastion/bastion_test.go
  test/integration/gardenlet/controllerinstallation/required/required_suite_test.go
  test/integration/gardenlet/seed/lease/lease_test.go
  test/integration/gardenlet/shoot/migration/migration_suite_test.go
  test/integration/gardenlet/shootstate/extensions/extensions_test.go
  test/integration/gardenlet/shootstate/secret/secret_suite_test.go
  test/integration/resourcemanager/garbagecollector/garbagecollector_test.go
  test/integration/resourcemanager/managedresource/resource_suite_test.go
  test/integration/resourcemanager/managedresource/resource_test.go
  test/integration/resourcemanager/tokeninvalidator/tokeninvalidator_test.go
  test/integration/resourcemanager/tokenrequestor/tokenrequestor_test.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#7350 Check existing machine deployment for mcm replica count
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
Labels: kind/enhancement, size/XS, area/robustness, area/control-plane, cla: yes, lgtm, approved

#7359 Update gardener/autoscaler for K8S v1.20, v1.21 , v1.22 , v1.23 , v1.24
  charts/images.yaml
Labels: kind/enhancement, size/S, area/auto-scaling, cla: yes, lgtm, approved

#7325 Introduce `ObservabilityComponentsHealthy` Shoot condition for status of observability components
  charts/gardener/gardenlet/values.yaml
  docs/concepts/gardenlet.md
  docs/deployment/getting_started_locally.md
  docs/development/getting_started_locally.md
  example/20-componentconfig-gardenlet.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/controllermanager/controller/seed/lifecycle/reconciler.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/gardenlet/controller/shoot/care/reconciler.go
  pkg/gardenlet/controller/shoot/care/reconciler_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  pkg/operation/care/health.go
  pkg/registry/core/shoot/storage/tableconvertor.go
  test/framework/k8s_utils.go
  test/framework/k8s_utils_test.go
  test/integration/controllermanager/seed/lifecycle/lifecycle_test.go
  test/integration/gardenlet/shoot/care/care_test.go
Labels: kind/enhancement, area/ops-productivity, size/L, area/monitoring, cla: yes, lgtm, approved

#7361 Upgrade prometheus to v2.41.0
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#7360 Allow `ControlPlane` spec modifications for unscheduled shoots
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: kind/enhancement, area/usability, size/M, cla: yes, lgtm, approved

#7364 Website Cleanup - Part 3 (Development) - Rebased
  docs/development/changing-the-api.md
  docs/development/component-checklist.md
  docs/development/dependencies.md
  docs/development/getting_started_locally.md
  docs/development/high-availability.md
  docs/development/kubernetes-clients.md
  docs/development/local_setup.md
  docs/development/log_parsers.md
  docs/development/logging.md
  docs/development/monitoring-stack.md
  docs/development/new-cloud-provider.md
  docs/development/new-kubernetes-version.md
  docs/development/priority-classes.md
  docs/development/process.md
  docs/development/secrets_management.md
  docs/development/seed_network_policies.md
  docs/development/testing.md
  docs/development/testmachinery_tests.md
  docs/extensions/conventions.md
Labels: kind/enhancement, size/XL, area/documentation, cla: yes, lgtm, approved

#7362 Remove the CSV format from Basic Authentication secrets
  docs/development/secrets_management.md
  docs/usage/shoot_credentials_rotation.md
  extensions/pkg/util/secret/manager/manager_test.go
  pkg/operation/botanist/monitoring_test.go
  pkg/provider-local/controller/controlplane/valuesprovider.go
  pkg/utils/secrets/basic_auth.go
  pkg/utils/secrets/basic_auth_test.go
Labels: area/open-source, size/M, kind/cleanup, cla: yes, lgtm, approved

#7355 Improve problematic webhook detector
  pkg/operation/botanist/matchers/matcher.go
  pkg/operation/care/constraints_test.go
Labels: kind/enhancement, area/robustness, size/S, cla: yes, lgtm, approved

#7294 Refactor `nginx-ingress` addon Helm chart into Golang component
  charts/shoot-addons/charts/nginx-ingress/templates/NOTES.txt
  charts/shoot-addons/charts/nginx-ingress/templates/_helpers.tpl
  charts/shoot-addons/charts/nginx-ingress/templates/clusterrole.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/clusterrolebinding.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-configmap.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-deployment.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-metrics-service.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-service.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-stats-service.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/default-backend-deployment.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/default-backend-service.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/ingressclass.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/psp/nginx-ingress-rolebinding-privileged.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/role.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/rolebinding.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/serviceaccount.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/tcp-configmap.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/udp-configmap.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/vpa.yaml
  charts/shoot-addons/charts/nginx-ingress/values.yaml
  charts/shoot-addons/requirements.yaml
  charts/shoot-addons/values.yaml
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/component/nginxingressshoot/nginxingress.go
  pkg/operation/botanist/component/nginxingressshoot/nginxingress_suite_test.go
  pkg/operation/botanist/component/nginxingressshoot/nginxingress_test.go
  pkg/operation/botanist/nginxingress.go
  pkg/operation/botanist/nginxingress_test.go
  pkg/operation/shoot/types.go
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, area/quality, area/robustness, cla: yes, lgtm, approved, size/XXL

#7241 Mark `ShootSystemComponentsHealthy` condition unhealthy if `ManagedResource` is stuck in progressing for more than threshold time
  charts/gardener/gardenlet/templates/_helpers.tpl
  charts/gardener/gardenlet/values.yaml
  docs/concepts/gardenlet.md
  example/20-componentconfig-gardenlet.yaml
  pkg/apis/core/v1beta1/types_utils.go
  pkg/gardenlet/apis/config/helper/helpers.go
  pkg/gardenlet/apis/config/helper/helpers_test.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/validation/validation.go
  pkg/gardenlet/apis/config/validation/validation_test.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/operation/care/checker.go
  pkg/operation/care/health.go
  pkg/operation/care/health_check_test.go
  pkg/operation/care/seed_health.go
Labels: kind/enhancement, area/quality, size/L, area/control-plane, cla: yes, lgtm, approved

#7369 [garden-local] Only add loopback addresses for multi-zonal setup
  Makefile
  example/gardener-local/kind/cluster/templates/_extra_port_mappings.tpl
  example/gardener-local/kind/cluster/values.yaml
  example/gardener-local/kind/ha-multi-zone/values.yaml
  hack/kind-up.sh
Labels: kind/enhancement, size/M, area/high-availability, area/testing, cla: yes, lgtm, approved

#7372 Don't pass the loop init variable as pointer to go routines
  cmd/gardenlet/app/app.go
Labels: kind/bug, size/XS, area/quality, area/control-plane, cla: yes, lgtm, approved

#7374 Don't install yq every time
  Makefile
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7357 [core] Clean up technical debt in defaulting code (1)
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_cloudprofile.go
  pkg/apis/core/v1alpha1/defaults_cloudprofile_test.go
  pkg/apis/core/v1alpha1/defaults_controllerregistration.go
  pkg/apis/core/v1alpha1/defaults_controllerregistration_test.go
  pkg/apis/core/v1alpha1/defaults_project.go
  pkg/apis/core/v1alpha1/defaults_project_test.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/zz_generated.defaults.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_cloudprofile.go
  pkg/apis/core/v1beta1/defaults_cloudprofile_test.go
  pkg/apis/core/v1beta1/defaults_controllerregistration.go
  pkg/apis/core/v1beta1/defaults_controllerregistration_test.go
  pkg/apis/core/v1beta1/defaults_project.go
  pkg/apis/core/v1beta1/defaults_project_test.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/zz_generated.defaults.go
Labels: area/dev-productivity, kind/technical-debt, component/gardener, cla: yes, lgtm, approved, size/XXL

#7377 Fix nil pointer exception in case extension `lastOperation` is nil
  pkg/gardenlet/controller/backupbucket/reconciler.go
  pkg/gardenlet/controller/backupentry/backupentry/reconciler.go
  pkg/gardenlet/controller/bastion/reconciler.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#7382 [release-v1.62] Use istio tunnel port for prometheus endpoint check.
  pkg/operation/botanist/component/istio/ingress_gateway.go
  pkg/operation/botanist/component/istio/monitoring.go
  pkg/operation/botanist/component/istio/monitoring_test.go
Labels: kind/bug, size/S, cla: yes, lgtm, approved

#7384 [release-v1.61] Use istio tunnel port for prometheus endpoint check.
  pkg/operation/botanist/component/istio/ingress_gateway.go
  pkg/operation/botanist/component/istio/monitoring.go
  pkg/operation/botanist/component/istio/monitoring_test.go
Labels: kind/bug, size/S, cla: yes, lgtm, approved

#7365 Update docforge to v0.33.0
  hack/tools.mk
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7366 Adds a watchdog to forcefully shutdown v1.24 `kube-apiserver` that are stuck in shutdown
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/resources/watchdog.sh
  pkg/operation/botanist/component/kubeapiserver/watchdog.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
Labels: kind/bug, area/ops-productivity, size/L, area/control-plane, cla: yes, lgtm, approved

#7386 Improve `addons-nginx-ingress-controller` component refactoring
  pkg/gardenlet/controller/shoot/care/add_test.go
  pkg/operation/botanist/component/nginxingressshoot/nginxingress.go
  pkg/operation/botanist/component/nginxingressshoot/nginxingress_test.go
  pkg/operation/botanist/component/nodeproblemdetector/node_problem_detector.go
  pkg/operation/botanist/component/nodeproblemdetector/node_problem_detector_test.go
  pkg/operation/botanist/nginxingress.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#7381 [GEP-21] Document dev setup options for IPv6
  docs/deployment/getting_started_locally.md
  docs/development/getting_started_locally.md
  docs/development/local_setup.md
  docs/usage/ipv6.md
Labels: kind/enhancement, area/dev-productivity, size/M, area/networking, cla: yes, lgtm, approved

#7390 Fix `SecretRef` comment in `InfrastructureSpec`
  docs/api-reference/extensions.md
  example/seed-crds/10-crd-extensions.gardener.cloud_infrastructures.yaml
  pkg/apis/extensions/v1alpha1/types_infrastructure.go
  pkg/operation/botanist/component/extensions/crds/assets/crd-extensions.gardener.cloud_infrastructures.yaml
Labels: kind/enhancement, area/quality, size/S, cla: yes, lgtm, approved

#7367 Drop `rootcapublisher` controller in `gardener-resource-manager`
  charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml
  charts/gardener/resource-manager/charts/runtime/templates/deployment.yaml
  charts/gardener/resource-manager/charts/runtime/templates/secret-root-ca.yaml
  charts/gardener/resource-manager/values.yaml
  example/resource-manager/10-componentconfig.yaml
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/shared/resourcemanager.go
  pkg/operation/botanist/resource_manager.go
  pkg/resourcemanager/apis/config/types.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults_test.go
  pkg/resourcemanager/apis/config/v1alpha1/types.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/resourcemanager/apis/config/validation/validation.go
  pkg/resourcemanager/apis/config/validation/validation_test.go
  pkg/resourcemanager/apis/config/zz_generated.deepcopy.go
  pkg/resourcemanager/controller/add.go
  pkg/resourcemanager/controller/rootcapublisher/add.go
  pkg/resourcemanager/controller/rootcapublisher/add_test.go
  pkg/resourcemanager/controller/rootcapublisher/reconciler.go
  pkg/resourcemanager/controller/rootcapublisher/reconciler_test.go
  pkg/resourcemanager/controller/rootcapublisher/rootcapublisher_suite_test.go
  pkg/resourcemanager/webhook/projectedtokenmount/handler.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/resourcemanager/rootcapublisher/publisher_suite_test.go
  test/integration/resourcemanager/rootcapublisher/publisher_test.go
  test/integration/resourcemanager/rootcapublisher/testdata/ca.crt
Labels: area/security, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#7394 Website Cleanup Part 4 - Extensions
  docs/concepts/cluster-api.md
  docs/concepts/etcd.md
  docs/concepts/network_policies.md
  docs/concepts/operator.md
  docs/concepts/resource-manager.md
  docs/deployment/getting_started_locally_with_extensions.md
  docs/development/high-availability.md
  docs/development/kubernetes-clients.md
  docs/development/local_setup.md
  docs/development/priority-classes.md
  docs/development/testmachinery_tests.md
  docs/extensions/admission.md
  docs/extensions/backupbucket.md
  docs/extensions/backupentry.md
  docs/extensions/bastion.md
  docs/extensions/ca-rotation.md
  docs/extensions/cluster.md
  docs/extensions/containerruntime.md
  docs/extensions/controllerregistration.md
  docs/extensions/controlplane-exposure.md
  docs/extensions/controlplane-webhooks.md
  docs/extensions/controlplane.md
  docs/extensions/conventions.md
  docs/extensions/dnsrecord.md
  docs/extensions/extension.md
  docs/extensions/healthcheck-library.md
  docs/extensions/heartbeat.md
  docs/extensions/infrastructure.md
  docs/extensions/logging-and-monitoring.md
  docs/extensions/managedresources.md
  docs/extensions/migration.md
  docs/extensions/network.md
  docs/extensions/operatingsystemconfig.md
  docs/extensions/overview.md
  docs/extensions/project-roles.md
  docs/extensions/provider-local.md
  docs/extensions/reconcile-trigger.md
  docs/extensions/referenced-resources.md
  docs/extensions/shoot-health-status-conditions.md
  docs/extensions/shoot-maintenance.md
  docs/extensions/shoot-webhooks.md
  docs/extensions/worker.md
  docs/proposals/01-extensibility.md
  docs/proposals/04-new-core-gardener-cloud-apis.md
  docs/proposals/15-manage-bastions-and-ssh-key-pair-rotation.md
  docs/proposals/18-shoot-CA-rotation.md
  docs/proposals/20-ha-control-planes.md
  docs/proposals/README.md
Labels: kind/enhancement, size/XL, area/documentation, cla: yes, lgtm, approved

#7396 Improve docs: Running integration tests
  docs/development/testing.md
Labels: kind/enhancement, area/dev-productivity, size/XS, area/documentation, area/testing, ok-to-test, cla: yes, lgtm, approved

#7389 "Rename" `NetworkPolicy`: `allow-to-seed-apiserver` -> `allow-to-runtime-apiserver`
  charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  docs/development/seed_network_policies.md
  example/20-componentconfig-gardenlet.yaml
  extensions/pkg/terraformer/terraformer.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/networkpolicy/add.go
  pkg/gardenlet/controller/networkpolicy/add_test.go
  pkg/gardenlet/controller/networkpolicy/helper/helper.go
  pkg/gardenlet/controller/networkpolicy/helper/helper_test.go
  pkg/gardenlet/controller/networkpolicy/reconciler.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler_test.go
  pkg/operation/botanist/component/dependencywatchdog/bootstrap.go
  pkg/operation/botanist/component/dependencywatchdog/bootstrap_test.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/namespace.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/namespace.yaml
  pkg/operation/botanist/component/istio/istiod.go
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/operation/botanist/component/kubestatemetrics/resources.go
  pkg/operation/botanist/component/logging/eventlogger/event_logger.go
  pkg/operation/botanist/component/logging/eventlogger/event_logger_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_suite_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, area/security, area/networking, cla: yes, lgtm, approved, size/XXL

#7398 Set Shoot K8s version to 1.26 for e2e tests
  Makefile
  example/provider-local/shoot.yaml
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/cleanup, size/S, area/testing, cla: yes, lgtm, approved

#7392 Introduce new `NetworkPolicy` controller in `gardener-resource-manager`
  charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml
  charts/gardener/resource-manager/values.yaml
  docs/concepts/resource-manager.md
  example/resource-manager/10-componentconfig.yaml
  pkg/apis/resources/v1alpha1/types.go
  pkg/gardenlet/controller/bastion/add_test.go
  pkg/resourcemanager/apis/config/types.go
  pkg/resourcemanager/apis/config/v1alpha1/types.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/resourcemanager/apis/config/zz_generated.deepcopy.go
  pkg/resourcemanager/controller/add.go
  pkg/resourcemanager/controller/networkpolicy/add.go
  pkg/resourcemanager/controller/networkpolicy/add_test.go
  pkg/resourcemanager/controller/networkpolicy/networkpolicy_suite_test.go
  pkg/resourcemanager/controller/networkpolicy/reconciler.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/resourcemanager/networkpolicy/networkpolicy_suite_test.go
  test/integration/resourcemanager/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, area/security, area/networking, cla: yes, lgtm, approved, size/XXL

#7393 Deflake garden controller integration test
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_service.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden_suite_test.go
  test/integration/operator/garden/garden_test.go
  test/utils/operationannotation/operationannotation.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#7401 Move `shoot-core/network-policies` Helm chart into responsible components packages
  charts/shoot-core/components/charts/network-policies/templates/allow-from-seed.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-from-to-nginx.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-to-api-server.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-to-dns.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-to-kubelet.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-to-public-networks.yaml
  charts/shoot-core/components/charts/network-policies/values.yaml
  charts/shoot-core/components/values.yaml
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/addons/networkpolicy/shoot_network_policy.go
  pkg/operation/botanist/addons/networkpolicy/shoot_network_policy_suite_test.go
  pkg/operation/botanist/component/nginxingressshoot/nginxingress.go
  pkg/operation/botanist/component/nginxingressshoot/nginxingress_test.go
  pkg/operation/botanist/component/shootsystem/shootsystem.go
  pkg/operation/botanist/component/shootsystem/shootsystem_test.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot.go
  pkg/operation/botanist/component/vpnshoot/vpnshoot_test.go
  skaffold.yaml
Labels: area/dev-productivity, size/XL, kind/cleanup, cla: yes, lgtm, approved

#7391 Add CVE re-scoring configuration to the monitoring images
  charts/images.yaml
Labels: kind/enhancement, size/M, area/monitoring, cla: yes, lgtm, approved

#7388 [GEP-21] Prepare local setup for IPv6 development
  Makefile
  docs/deployment/getting_started_locally.md
  docs/development/getting_started_locally.md
  example/gardener-local/calico/base/kustomization.yaml
  example/gardener-local/calico/ipv4/kustomization.yaml
  example/gardener-local/calico/ipv6/cni_network_config.json
  example/gardener-local/calico/ipv6/kustomization.yaml
  example/gardener-local/calico/ipv6/patch-calico-node-daemonset.yaml
  example/gardener-local/kind/cluster/templates/_containerd_config_patches.tpl
  example/gardener-local/kind/cluster/templates/cluster.yaml
  example/gardener-local/kind/cluster/values-ipv6.yaml
  example/gardener-local/kind/cluster/values.yaml
  example/gardener-local/kind/local2/values.yaml
  example/gardener-local/registry/docker-ipv6/kustomization.yaml
  example/gardener-local/registry/kustomization.yaml
  hack/kind-up.sh
  pkg/provider-local/webhook/controlplane/ensurer.go
Labels: kind/enhancement, area/dev-productivity, size/L, ok-to-test, cla: yes, lgtm, approved
