Repository gardener/gardener, pull requests merged in 2023-11, with the labels that each got.

#8743 Prepare dev-cycle v1.84.0-dev
  VERSION
Labels: kind/enhancement, area/delivery, size/XS, cla: yes, lgtm, approved

#8736 Improve condition handling for `ManagedSeed`s
  hack/tools/image/README.md
  pkg/apis/core/v1beta1/helper/condition.go
  pkg/apis/core/v1beta1/helper/condition_test.go
  pkg/controllermanager/controller/seed/lifecycle/reconciler.go
  pkg/controllermanager/controller/shoot/conditions/reconciler.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  test/framework/k8s_utils.go
  test/integration/controllermanager/shoot/conditions/conditions_test.go
Labels: kind/bug, size/L, area/robustness, cla: yes, lgtm, approved

#8751 Switch prometheus-config-reloader image to be pulled from quay
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8701 [Authentication] Technical debt in defaulting code
  pkg/apis/authentication/v1alpha1/defaults_adminkubeconfigrequest.go
  pkg/apis/authentication/v1alpha1/defaults_adminkubeconfigrequest_test.go
  pkg/apis/authentication/v1alpha1/v1alpha1_suite_test.go
Labels: area/dev-productivity, size/M, kind/technical-debt, cla: yes, lgtm, approved

#8756 [node-agent] Adapt extension operating system config components according to changes in `OperatingSystemConfig` API
  docs/deployment/feature_gates.md
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/logrotate/logrotate.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/logrotate/logrotate_suite_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/logrotate/logrotate_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kernelconfig/kernelconfig_suite_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/kubelet_suite_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/rootcertificates_suite_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/sshd_suite_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/component_suite_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config_test.go
  pkg/gardenlet/features/features.go
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#8760 [node-agent] controlplane mutator webhook also searches for files in units.files of OSC
  extensions/pkg/webhook/controlplane/genericmutator/mutator.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator_test.go
Labels: kind/bug, area/dev-productivity, size/M, cla: yes, lgtm, approved

#8750 Cluster autoscaler metrics to be scraped by prometheus
  pkg/component/clusterautoscaler/monitoring.go
  pkg/component/clusterautoscaler/monitoring_test.go
Labels: kind/enhancement, area/ops-productivity, size/M, area/monitoring, cla: yes, lgtm, approved

#8761 Forbid changes to primary DNS provider
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: kind/api-change, area/robustness, size/S, cla: yes, lgtm, approved

#8765 Update Go versions of golang-test image
  hack/tools/image/variants.yaml
Labels: kind/enhancement, size/XS, area/testing, cla: yes, lgtm, approved

#8659 Introduce Configurable `DeltaSnapshotRetentionPeriod ` in GardenletConfiguration
  example/20-componentconfig-gardenlet.yaml
  pkg/component/etcd/etcd.go
  pkg/component/etcd/etcd_test.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/operation/botanist/etcd.go
Labels: kind/enhancement, lifecycle/stale, area/backup, size/M, cla: yes, lgtm, approved

#8745 Remove MR secret GRM finaliser
  pkg/resourcemanager/controller/secret/reconciler.go
  pkg/resourcemanager/controller/secret/reconciler_test.go
  test/integration/resourcemanager/secret/secret_test.go
Labels: area/quality, size/L, kind/cleanup, cla: yes, lgtm, approved

#8690 Run Control Plane components as `nonroot` user `65532`
  pkg/component/kubeapiserver/deployment.go
  pkg/component/kubeapiserver/kube_apiserver_test.go
  pkg/component/kubecontrollermanager/kube_controller_manager.go
  pkg/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/component/kubescheduler/kube_scheduler.go
  pkg/component/kubescheduler/kube_scheduler_test.go
Labels: kind/enhancement, area/security, area/quality, size/M, cla: yes, lgtm, approved

#8742 Deploy MCM with 0 replicas during cpm `restore` phase
  extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  pkg/operation/botanist/machinecontrollermanager.go
  pkg/operation/botanist/machinecontrollermanager_test.go
Labels: kind/bug, size/S, area/control-plane-migration, cla: yes, lgtm, approved

#8774 Allow MCM to delete VolumeAttachments
  pkg/component/machinecontrollermanager/machine_controller_manager.go
  pkg/component/machinecontrollermanager/machine_controller_manager_test.go
Labels: kind/bug, size/XS, cla: yes, lgtm, approved

#8771 Drop TODOs
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: size/L, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#8781 Use restmapper with `LazyDiscovery`
  extensions/pkg/util/shoot_clients.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#8787 Update Go versions of golang-test image
  hack/tools/image/variants.yaml
Labels: kind/enhancement, size/XS, area/testing, ok-to-test, cla: yes, lgtm, approved

#8791 Properly handle error in `ControllerInstallation` controller
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
Labels: kind/bug, size/XS, cla: yes, lgtm, approved

#8747 Drop `probe` and `endpoint` fields in `spec.settings.dependencyWatchdog`
  docs/api-reference/core.md
  example/50-seed.yaml
  example/provider-extensions/gardenlet/values.yaml.tmpl
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/types_seed_test.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/component/dependencywatchdog/bootstrap.go
  pkg/component/dependencywatchdog/bootstrap_test.go
  pkg/gardenlet/controller/seed/care/health_test.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/dependency_watchdog_test.go
  pkg/registry/core/seed/strategy.go
  pkg/registry/core/seed/strategy_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: kind/api-change, area/usability, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#8789 Fix `generate-crds.sh` script
  hack/generate-crds.sh
Labels: kind/bug, size/XS, cla: yes, lgtm, approved

#8788 Stop patching new secretRefs on MR reconciliaition
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  pkg/component/etcd/bootstrap_test.go
  pkg/component/logging/vali/vali_test.go
  pkg/component/resourcemanager/resource_manager_test.go
  pkg/utils/managedresources/builder/managedresources.go
  pkg/utils/managedresources/builder/resourcemanager_test.go
Labels: size/L, area/robustness, kind/cleanup, cla: yes, lgtm, approved

#8766 Add `hack/update-skaffold-deps.sh`
  hack/check-skaffold-deps-for-binary.sh
  hack/check-skaffold-deps.sh
  hack/update-skaffold-deps.sh
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#8799 Bump observaility components, plutono to 7.5.26, vali and valitail to 2.2.11, kube-rbac-proxy to 0.15.0
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, area/logging, cla: yes, lgtm, approved

#8770 Enhance component-checklist with 2 new rules for container images
  docs/development/component-checklist.md
Labels: kind/enhancement, size/M, cla: yes, lgtm, approved

#8798 Scrape kubelet volume metrics
  pkg/component/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#8721 Enables `node-exporter`'s `textfile` collector
  docs/development/monitoring-stack.md
  pkg/component/nodeexporter/nodeexporter.go
  pkg/component/nodeexporter/nodeexporter_test.go
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#8755 Prepare migration from GCR -> Artifact Registry
  hack/.ci/component_descriptor
Labels: area/delivery, kind/technical-debt, size/S, cla: yes, lgtm, approved

#8759 Fix `check-charts` script
  hack/check-charts.sh
Labels: kind/enhancement, size/XS, area/testing, cla: yes, lgtm, approved

#8803 Drop unwanted annotations from referenced resources
  pkg/operation/botanist/resources.go
  pkg/operation/botanist/resources_test.go
Labels: kind/bug, area/security, size/M, cla: yes, lgtm, approved

#8795 Fix unrecoverable issues with `etcd` during credentials rotation
  pkg/component/etcd/etcd.go
  pkg/component/etcd/etcd_test.go
  pkg/operation/botanist/etcd.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
Labels: kind/bug, size/M, area/robustness, cla: yes, lgtm, approved

#8801 Duplicate the `GetResourceByName` helper func to internal API helper pkg
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
Labels: kind/enhancement, size/M, cla: yes, lgtm, approved

#8763 Disable `kube-controller-manager` controllers based on disabled APIs
  docs/development/new-kubernetes-version.md
  hack/compute-k8s-controllers.sh
  pkg/component/kubecontrollermanager/kube_controller_manager.go
  pkg/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/component/kubecontrollermanager/mock/mocks.go
  pkg/operation/botanist/kubecontrollermanager.go
  pkg/operation/botanist/kubecontrollermanager_test.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  pkg/utils/kubernetes/controllers.go
  pkg/utils/validation/admissionplugins/admissionplugins.go
  pkg/utils/validation/admissionplugins/admissionplugins_test.go
  pkg/utils/validation/apigroups/apigroups.go
  pkg/utils/validation/apigroups/apigroups_test.go
  pkg/utils/validation/features/featuregates.go
  pkg/utils/validation/features/featuregates_test.go
  pkg/utils/version/version.go
  pkg/utils/version/version_test.go
Labels: kind/enhancement, area/control-plane, cla: yes, lgtm, approved, size/XXL

#8790 Configure `0640` permissions to mounted `key` files on Control plane components
  pkg/component/apiserver/deployment.go
  pkg/component/apiserver/deployment_test.go
  pkg/component/apiserver/encryptionconfiguration.go
  pkg/component/apiserver/encryptionconfiguration_test.go
  pkg/component/gardeneradmissioncontroller/deployment.go
  pkg/component/gardeneradmissioncontroller/gardener_admission_controller_test.go
  pkg/component/gardenerapiserver/deployment.go
  pkg/component/gardenerapiserver/gardener_apiserver_test.go
  pkg/component/gardenercontrollermanager/deployment.go
  pkg/component/gardenercontrollermanager/gardener_controller_manager_test.go
  pkg/component/gardenerscheduler/deployment.go
  pkg/component/gardenerscheduler/gardener_scheduler_test.go
  pkg/component/kubeapiserver/deployment.go
  pkg/component/kubeapiserver/kube_apiserver_test.go
  pkg/component/kubecontrollermanager/kube_controller_manager.go
  pkg/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/component/kubescheduler/kube_scheduler.go
  pkg/component/kubescheduler/kube_scheduler_test.go
Labels: kind/enhancement, area/security, size/L, area/compliance, cla: yes, lgtm, approved

#8812 Recreate managed resource secrets that have deletion timestamp
  cmd/gardenlet/app/app.go
  cmd/gardenlet/app/app_test.go
Labels: area/quality, size/L, kind/cleanup, cla: yes, lgtm, approved

#8746 Log a minor retriable error as info instead of an error
  pkg/extensions/customresources.go
Labels: kind/enhancement, size/XS, area/quality, cla: yes, lgtm, approved

#8818 Use annotation for old secret name instead of label
  cmd/gardenlet/app/app.go
  cmd/gardenlet/app/app_test.go
Labels: kind/bug, area/usability, kind/cleanup, size/S, cla: yes, lgtm, approved

#8814 [node-agent] Refactor `files` handling in `OperatingSystemConfig` API
  docs/api-reference/extensions.md
  example/seed-crds/10-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  extensions/pkg/controller/operatingsystemconfig/bash.go
  extensions/pkg/controller/operatingsystemconfig/bash_test.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator_test.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/extensions/validation/operatingsystemconfig.go
  pkg/apis/extensions/validation/operatingsystemconfig_test.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit.go
  pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/logrotate/logrotate.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/logrotate/logrotate_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config_test.go
  pkg/nodeagent/controller/operatingsystemconfig/changes.go
  pkg/provider-local/controller/operatingsystemconfig/actuator.go
  test/integration/nodeagent/operatingsystemconfig/operatingsystemconfig_test.go
Labels: kind/enhancement, size/XL, area/usability, cla: yes, lgtm, approved

#8820 Do not try recreating secrets in terminating namespaces
  cmd/gardenlet/app/app.go
Labels: kind/bug, area/usability, size/M, kind/cleanup, cla: yes, lgtm, approved

#8809 Prepare next Dev Cycle v1.85.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8768 Add unit tests
  extensions/pkg/controller/backupbucket/backupbucket_suite_test.go
  extensions/pkg/controller/backupbucket/mapper_test.go
  extensions/pkg/controller/backupentry/mapper_test.go
  pkg/admissioncontroller/seedidentity/identity_test.go
  pkg/admissioncontroller/webhook/admission/admissionpluginsecret/handler_test.go
  pkg/admissioncontroller/webhook/admission/namespacedeletion/handler_test.go
  pkg/api/extensions/accessor_test.go
  pkg/api/indexer/gardener_core_test.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/chartrenderer/default_test.go
  pkg/chartrenderer/testdata/alpine/templates/secret.yaml
  pkg/controller/networkpolicy/add_test.go
  pkg/controllermanager/apis/config/validation/validation.go
  pkg/controllerutils/associations_test.go
  pkg/extensions/cluster_test.go
Labels: kind/test, area/testing, cla: yes, lgtm, approved, size/XXL

#8823 Install gnu bash in local setup
  docs/development/local_setup.md
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#8819 Minor fixes in the CP migration TM tests
  test/framework/shootmigrationtest.go
  test/testmachinery/system/shoot_cp_migration/migrate_test.go
Labels: kind/bug, size/M, area/testing, area/control-plane-migration, cla: yes, lgtm, approved

#8825 Deprecated OS common package ignores files with image ref
  extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_util.go
Labels: kind/enhancement, size/XS, area/usability, cla: yes, lgtm, approved

#8574 [GEP-21] provider-local single-stack ipv6 implementation
  docs/usage/ipv6.md
  example/gardener-local/gardenlet/values-ipv6.yaml
  example/provider-local/shoot-ipv6.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/validation/seed.go
  pkg/apis/extensions/validation/network.go
  pkg/component/apiserverproxy/apiserver_proxy.go
  pkg/component/apiserverproxy/apiserver_proxy_test.go
  pkg/component/apiserverproxy/templates/envoy.yaml.tpl
  pkg/component/coredns/coredns.go
  pkg/component/coredns/coredns_test.go
  pkg/component/extensions/network/network.go
  pkg/component/extensions/network/network_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go
  pkg/component/istio/charts/istio/istio-ingress/templates/vpn-envoy-filter.yaml
  pkg/component/istio/test_charts/ingress_vpn_envoy_filter.yaml
  pkg/component/kubeapiserver/secrets.go
  pkg/component/kubeapiserverexposure/kube_apiserver_sni.go
  pkg/component/kubeapiserverexposure/kube_apiserver_sni_test.go
  pkg/component/kubeapiserverexposure/templates/envoyfilter.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/statefulset.yaml
  pkg/component/monitoring/charts/bootstrap/templates/aggregate-prometheus/statefulset.yaml
  pkg/component/monitoring/charts/bootstrap/templates/prometheus/statefulset.yaml
  pkg/component/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  pkg/component/nodeproblemdetector/node_problem_detector.go
  pkg/component/nodeproblemdetector/node_problem_detector_test.go
  pkg/component/shootsystem/shootsystem.go
  pkg/component/shootsystem/shootsystem_test.go
  pkg/component/vpnseedserver/vpn_seed_server.go
  pkg/component/vpnseedserver/vpn_seed_server_test.go
  pkg/component/vpnshoot/vpnshoot.go
  pkg/component/vpnshoot/vpnshoot_test.go
  pkg/controller/networkpolicy/helper/helper.go
  pkg/controller/networkpolicy/helper/helper_test.go
  pkg/controller/networkpolicy/peers.go
  pkg/controller/networkpolicy/reconciler.go
  pkg/gardenlet/controller/networkpolicy/add.go
  pkg/operation/botanist/apiserverproxy.go
  pkg/operation/botanist/network.go
  pkg/operation/botanist/vpnseedserver.go
  pkg/operation/botanist/vpnshoot.go
  pkg/operation/botanist/vpnshoot_test.go
  pkg/operator/controller/networkpolicyregistrar/reconciler.go
  pkg/utils/net/ip.go
  pkg/utils/net/ip_test.go
  pkg/utils/net/net_suite_test.go
  pkg/utils/validation/cidr/disjoint.go
  pkg/utils/validation/cidr/disjoint_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/gardenlet/networkpolicy/networkpolicy_suite_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, kind/api-change, area/networking, ok-to-test, cla: yes, lgtm, approved, size/XXL

#8808 Release responsible schedule for v1.88 until v1.93
  docs/development/process.md
Labels: kind/enhancement, area/delivery, size/S, cla: yes, lgtm, approved

#8827 Original `OperatingSystemConfig` components always specify `filePaths` in their units
  pkg/apis/extensions/v1alpha1/helper/helper.go
  pkg/apis/extensions/v1alpha1/helper/helper_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/logrotate/logrotate.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/logrotate/logrotate_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/templates/scripts/fetch-token.tpl.sh
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/templates/valitail-config.tpl.yaml
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#8826 [node-agent] Do not try fetching node name on start-up
  cmd/gardener-node-agent/app/app.go
  pkg/nodeagent/controller/add.go
  pkg/nodeagent/controller/operatingsystemconfig/reconciler.go
  pkg/nodeagent/dbus/dbus.go
  test/integration/nodeagent/operatingsystemconfig/operatingsystemconfig_test.go
Labels: kind/bug, area/usability, size/L, cla: yes, lgtm, approved

#8840 Fix `Seed` care controller checks when `vali` is disabled
  pkg/gardenlet/controller/seed/add.go
  pkg/gardenlet/controller/seed/care/health.go
  pkg/gardenlet/controller/seed/care/health_test.go
  pkg/gardenlet/controller/seed/care/reconciler.go
  pkg/gardenlet/controller/seed/care/reconciler_test.go
  pkg/gardenlet/controller/seed/care/types.go
  test/integration/gardenlet/seed/care/care_suite_test.go
  test/integration/gardenlet/seed/care/care_test.go
Labels: kind/bug, area/ops-productivity, size/L, cla: yes, lgtm, approved

#8835 Avoid unnecessary GRM rollouts
  pkg/component/resourcemanager/resource_manager_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
Labels: kind/enhancement, size/M, area/control-plane, cla: yes, lgtm, approved

#8836 [node-agent] Add logging configuration for `gardener-node-agent` unit
  hack/ci-common.sh
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/logging.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/logging_test.go
  pkg/gardenlet/controller/seed/seed/components.go
  skaffold.yaml
Labels: kind/enhancement, size/L, area/logging, cla: yes, lgtm, approved

#8696 [core] Clean up technical debt in defaulting code (2)
  pkg/apis/core/v1beta1/defaults_secretbinding.go
  pkg/apis/core/v1beta1/defaults_secretbinding_test.go
  pkg/apis/core/v1beta1/defaults_seed.go
  pkg/apis/core/v1beta1/defaults_seed_test.go
  pkg/apis/core/v1beta1/defaults_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot_test.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/register.go
  pkg/apis/core/v1beta1/zz_generated.defaults.go
  pkg/operator/webhook/defaulting/handler.go
Labels: area/dev-productivity, kind/technical-debt, cla: yes, lgtm, approved, size/XXL

#8838 [node-agent] Merge `filePaths` when merging units
  pkg/nodeagent/controller/operatingsystemconfig/changes.go
  test/integration/nodeagent/operatingsystemconfig/operatingsystemconfig_test.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#8834 [provider-local] Adapt to changes needed for `gardener-node-agent`
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-extension-provider-local/app/options.go
  extensions/pkg/webhook/controlplane/genericmutator/mock/mocks.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator_test.go
  extensions/pkg/webhook/controlplane/genericmutator/noopensurer.go
  pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
  pkg/provider-local/controller/operatingsystemconfig/actuator.go
  pkg/provider-local/webhook/controlplane/add.go
  pkg/provider-local/webhook/controlplane/ensurer.go
  pkg/provider-local/webhook/nodeagentosc/add.go
  pkg/provider-local/webhook/nodeagentosc/mutator.go
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/XL, area/usability, cla: yes, lgtm, approved

#8841 Update rule about image registries
  docs/development/component-checklist.md
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8839 [node-agent] Adapt `token` controller to fetch also other tokens (`valitail`)
  cmd/gardener-node-agent/app/app.go
  docs/concepts/node-agent.md
  example/node-agent/10-componentconfig.yaml
  pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/templates/scripts/fetch-token.tpl.sh
  pkg/nodeagent/apis/config/types.go
  pkg/nodeagent/apis/config/v1alpha1/types.go
  pkg/nodeagent/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/nodeagent/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/nodeagent/apis/config/validation/validation.go
  pkg/nodeagent/apis/config/validation/validation_test.go
  pkg/nodeagent/apis/config/zz_generated.deepcopy.go
  pkg/nodeagent/controller/token/add.go
  pkg/nodeagent/controller/token/reconciler.go
  skaffold.yaml
  test/integration/nodeagent/token/token_suite_test.go
  test/integration/nodeagent/token/token_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#8844 Verify no pod is running in controlplane for workerless shoots
  test/e2e/gardener/shoot/create_and_delete_hibernated.go
  test/framework/gardener_utils.go
Labels: kind/enhancement, size/S, area/testing, cla: yes, lgtm, approved

#8800 Remove obsolete vali tenant configurations
  pkg/component/logging/fluentoperator/customresources/cluster_outputs.go
  pkg/component/logging/fluentoperator/customresources/cluster_outputs_test.go
  pkg/component/logging/vali/templates/vali-config.yaml
  pkg/component/logging/vali/vali.go
  pkg/component/logging/vali/vali_test.go
  pkg/component/plutono/plutono.go
  pkg/component/plutono/plutono_test.go
  pkg/component/shared/vali.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/operation/botanist/logging.go
  pkg/operator/controller/garden/garden/components.go
  test/framework/shoot_utils.go
  test/testmachinery/shoots/logging/seed_logging_stack.go
  test/testmachinery/shoots/logging/shoot_logging.go
  test/testmachinery/shoots/logging/utils.go
Labels: kind/enhancement, size/XL, area/logging, cla: yes, lgtm, approved

#8758 Document the Shoot status error classification (user error or not)
  docs/usage/shoot_status.md
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#8845 Replaced absolute links with relative
  docs/concepts/controller-manager.md
  docs/concepts/resource-manager.md
  docs/deployment/deploy_gardenlet_manually.md
  docs/development/component-checklist.md
  docs/development/new-kubernetes-version.md
  docs/development/process.md
  docs/extensions/controlplane-exposure.md
  docs/extensions/controlplane-webhooks.md
  docs/extensions/force-deletion.md
  docs/extensions/healthcheck-library.md
  docs/extensions/migration.md
  docs/extensions/reconcile-trigger.md
  docs/extensions/shoot-health-status-conditions.md
  docs/extensions/worker.md
  docs/proposals/02-backupinfra.md
  docs/proposals/04-new-core-gardener-cloud-apis.md
  docs/proposals/06-etcd-druid.md
  docs/proposals/07-shoot-control-plane-migration.md
  docs/proposals/09-test-framework.md
  docs/proposals/11-apiserver-network-proxy.md
  docs/proposals/14-reversed-cluster-vpn.md
  docs/proposals/15-manage-bastions-and-ssh-key-pair-rotation.md
  docs/proposals/19-migrating-observability-stack-to-operators.md
  docs/proposals/20-ha-control-planes.md
  docs/proposals/22-improved-usage-of-shootstate-api.md
  docs/proposals/README.md
  docs/usage/exposureclasses.md
  docs/usage/shoot_auditpolicy.md
  docs/usage/shoot_credentials_rotation.md
  docs/usage/shoot_status.md
  docs/usage/tolerations.md
Labels: kind/enhancement, area/documentation, size/L, cla: yes, lgtm, approved

#8850 Federate non-namespaced metrics
  pkg/component/monitoring/charts/bootstrap/templates/aggregate-prometheus/config.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#8843 Set logger in e2e test
  test/e2e/gardener/shoot/common.go
Labels: kind/bug, size/S, area/testing, cla: yes, lgtm, approved

#8822 Updated clusterrole for CA
  pkg/component/clusterautoscaler/bootstrap.go
  pkg/component/clusterautoscaler/bootstrap_test.go
Labels: kind/enhancement, size/S, area/auto-scaling, cla: yes, lgtm, approved

#8757 add kubelet version and OS image version in node/worker pool overview dashboard
  pkg/component/plutono/dashboards/shoot/owners/worker/node-pool-dashboard.json
Labels: kind/enhancement, area/ops-productivity, size/L, cla: yes, lgtm, approved

#8856 Update alpine image to `3.18.4`
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8855 Still support extensions with vendor dir
  hack/check-generate.sh
  hack/check-skaffold-deps-for-binary.sh
Labels: kind/bug, size/M, cla: yes, lgtm, approved

#8862 Set a timeout for the `WaitUntilMachineResourcesDeleted` step in the Shoot force deletion flow
  pkg/gardenlet/controller/shoot/shoot/reconciler_force_delete.go
Labels: kind/bug, size/XS, cla: yes, lgtm, approved

#8816 Clean-up old unsupported ClusterRoleBinding for MCM before deploying new one
  pkg/component/machinecontrollermanager/bootstrap.go
  pkg/component/machinecontrollermanager/machine_controller_manager.go
  pkg/component/machinecontrollermanager/machine_controller_manager_test.go
Labels: kind/bug, size/M, area/robustness, cla: yes, lgtm, approved

#8817 Shoot care controller garbage-collects orphaned `Lease` objects related to no longer existing `Node`s
  pkg/gardenlet/controller/shoot/care/garbage_collection.go
  pkg/gardenlet/controller/shoot/care/garbage_collection_test.go
Labels: kind/enhancement, size/L, area/scalability, cla: yes, lgtm, approved

#8725 Enhancements for `extensions` webhook lib
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-operator/app/app.go
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  extensions/pkg/webhook/certificates/add.go
  extensions/pkg/webhook/certificates/reconciler.go
  extensions/pkg/webhook/certificates/reloader.go
  extensions/pkg/webhook/cmd/options.go
  extensions/pkg/webhook/handler.go
  extensions/pkg/webhook/handler_shootclient.go
  extensions/pkg/webhook/mutator.go
  extensions/pkg/webhook/registration.go
  extensions/pkg/webhook/registration_test.go
  extensions/pkg/webhook/shoot/webhook.go
  extensions/pkg/webhook/shoot/webhook_test.go
  extensions/pkg/webhook/validator.go
  extensions/pkg/webhook/webhook.go
  extensions/pkg/webhook/webhook_test.go
  pkg/utils/test/manager.go
  test/integration/extensions/webhook/certificates/certificates_test.go
  test/integration/extensions/webhook/cloudprovider/cloudprovider_suite_test.go
Labels: kind/enhancement, area/security, area/ops-productivity, area/open-source, cla: yes, lgtm, approved, size/XXL

#8872 update the etcd-druid dependency version in go.mod
  go.mod
  go.sum
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8852 Bump VPA to v1.0.0
  example/seed-crds/10-crd-autoscaling.k8s.io_verticalpodautoscalers.yaml
  go.mod
  go.sum
  imagevector/images.yaml
  pkg/component/vpa/admissioncontroller.go
  pkg/component/vpa/general.go
  pkg/component/vpa/recommender.go
  pkg/component/vpa/templates/crd-autoscaling.k8s.io_verticalpodautoscalers.yaml
  pkg/component/vpa/vpa_test.go
Labels: kind/enhancement, size/L, area/auto-scaling, cla: yes, lgtm, approved

#8833 Prepare for removal of `.spec.secretRef` field in the Seed
  docs/concepts/gardenlet.md
  example/gardener-local/gardenlet/values-kind-ha-multi-zone.yaml
  example/gardener-local/gardenlet/values-kind-ha-single-zone.yaml
  example/gardener-local/gardenlet/values-kind2-ha-single-zone.yaml
  example/gardener-local/gardenlet/values-kind2.yaml
  example/gardener-local/gardenlet/values.yaml
  example/provider-extensions/gardenlet/values.yaml.tmpl
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler.go
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler_test.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_managedseed.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_seed.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
  pkg/apis/seedmanagement/v1alpha1/constants/types_constants.go
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseed.go
  pkg/apis/seedmanagement/validation/managedseed_test.go
  pkg/gardenlet/controller/managedseed/actuator.go
  pkg/gardenlet/controller/managedseed/actuator_test.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/global/resourcereferencemanager/admission_test.go
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
  plugin/pkg/shoot/managedseed/admission.go
  plugin/pkg/shoot/managedseed/admission_test.go
  plugin/pkg/shoot/validator/admission_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/framework/gardener_utils.go
  test/framework/shootcreationframework.go
  test/integration/gardenlet/managedseed/managedseed_test.go
Labels: kind/api-change, size/XL, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#8853 Drop `docker` original `OperatingSystemConfig` component and a few left-over usages
  docs/api-reference/core.md
  docs/api-reference/extensions.md
  docs/usage/logging.md
  example/seed-crds/10-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  pkg/component/extensions/operatingsystemconfig/downloader/downloader.go
  pkg/component/extensions/operatingsystemconfig/executor/executor.go
  pkg/component/extensions/operatingsystemconfig/executor/executor_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/docker/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/docker/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/docker/docker_suite_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/docker/logging.go
  pkg/component/extensions/operatingsystemconfig/original/components/docker/logging_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/docker/logrotate/logrotate.go
  pkg/component/extensions/operatingsystemconfig/original/components/docker/logrotate/logrotate_suite_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/docker/logrotate/logrotate_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/docker/templates/scripts/health-monitor.tpl.sh
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/component.go
  pkg/component/extensions/operatingsystemconfig/original/original.go
  pkg/component/extensions/operatingsystemconfig/original/original_test.go
  pkg/component/logging/configs.go
  pkg/component/logging/fluentoperator/customresources/cluster_filters.go
  pkg/component/logging/fluentoperator/customresources/cluster_filters_test.go
  pkg/component/logging/fluentoperator/customresources/cluster_parsers.go
  pkg/component/logging/fluentoperator/customresources/cluster_parsers_test.go
  pkg/component/logging/fluentoperator/fluent_bit_test.go
  pkg/openapi/openapi_generated.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: area/dev-productivity, size/XL, kind/cleanup, cla: yes, lgtm, approved

#8875 Read `ImageNameGardenerNodeAgent` image only if `UseGardenerNodeAgent` feature gate is enabled
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
Labels: kind/bug, size/S, area/os, cla: yes, lgtm, approved

#8874 Prepare next Dev Cycle v1.86.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8878 Minor fixes
  docs/api-reference/settings.md
  pkg/apis/core/v1beta1/defaults_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot_test.go
  pkg/apis/settings/types_shared.go
  pkg/apis/settings/v1alpha1/generated.proto
  pkg/apis/settings/v1alpha1/types_shared.go
  pkg/openapi/openapi_generated.go
Labels: kind/enhancement, area/quality, size/M, cla: yes, lgtm, approved

#8767 [node-agent] Add `Lease` controller for reporting health/liveness (similar to the `Lease` the `kubelet` writes)
  docs/concepts/node-agent.md
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/rbac.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/rbac_test.go
  pkg/nodeagent/controller/add.go
  pkg/nodeagent/controller/lease/add.go
  pkg/nodeagent/controller/lease/reconciler.go
  pkg/operation/botanist/operatingsystemconfig_test.go
  skaffold.yaml
  test/integration/nodeagent/lease/lease_suite_test.go
  test/integration/nodeagent/lease/lease_test.go
Labels: kind/enhancement, area/ops-productivity, size/L, ok-to-test, cla: yes, lgtm, approved

#8880 Use registry-cache extension when running e2e tests in prow
  example/gardener-local/registry-prow/kustomization.yaml
  hack/kind-up.sh
Labels: kind/enhancement, area/cost, size/M, area/testing, cla: yes, lgtm, approved

#8884 Add `GOPROXY` build-arg to build targets in `Dockerfile`s
  Dockerfile
  hack/tools/image/Dockerfile
Labels: kind/enhancement, area/cost, size/XS, area/testing, cla: yes, lgtm, approved
