Repository gardener/gardener, pull requests merged in 2023-03, with the labels that each got.

#7577 Clean up the deletion logic for the `loki` PriorityClass
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile_test.go
Labels: size/M, kind/cleanup, cla: yes, lgtm, approved

#7576 Drop ingress `NetworkPolicy` rule from `seed-prometheus` for shoot components
  charts/seed-monitoring/charts/core/charts/prometheus/templates/allow-from-prometheus-network-policy.yaml
Labels: area/security, size/XS, kind/cleanup, area/networking, cla: yes, lgtm, approved

#7529 Prepare for removal of `.spec.dns.{ingressDomain,provider.domains,provider.zones}` fields in the Seed API
  docs/api-reference/core.md
  docs/deployment/deploy_gardenlet_manually.md
  docs/extensions/dnsrecord.md
  docs/usage/trusted-tls-for-control-planes.md
  example/50-seed.yaml
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
  pkg/apis/seedmanagement/validation/managedseed_test.go
  pkg/controllermanager/controller/managedseedset/replica.go
  pkg/controllermanager/controller/managedseedset/replica_test.go
  pkg/gardenlet/apis/config/validation/validation_test.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/gardenlet/controller/seed/seed/nginxingress.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/operatingsystemconfig_test.go
  pkg/operation/operation_test.go
  pkg/operation/seed/seed.go
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
  test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_suite_test.go
  test/integration/controllermanager/controllerregistration/controllerregistration_test.go
  test/integration/controllermanager/managedseedset/managedseedset_test.go
  test/integration/controllermanager/seed/backupbucketscheck/backupbucketscheck_test.go
  test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go
  test/integration/controllermanager/seed/lifecycle/lifecycle_test.go
  test/integration/controllermanager/seed/secrets/secrets_test.go
  test/integration/controllermanager/shoot/conditions/conditions_test.go
  test/integration/gardenlet/backupbucket/backupbucket_suite_test.go
  test/integration/gardenlet/backupentry/backupentry/backupentry_suite_test.go
  test/integration/gardenlet/backupentry/backupentry/backupentry_test.go
  test/integration/gardenlet/bastion/bastion_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
  test/integration/gardenlet/managedseed/managedseed_suite_test.go
  test/integration/gardenlet/managedseed/managedseed_test.go
  test/integration/gardenlet/seed/care/care_test.go
  test/integration/gardenlet/seed/lease/lease_suite_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/gardenlet/shoot/care/care_test.go
  test/integration/scheduler/shoot/shoot_test.go
Labels: area/dev-productivity, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#7579 Clean up the deletion of `fluent-bit` and `loki` PriorityClasses as part of the Seed logging deletion
  pkg/operation/common/utils.go
  pkg/operation/common/utils_test.go
Labels: kind/cleanup, size/S, cla: yes, lgtm, approved

#7584 Readd wrongly removed unit test
  plugin/pkg/managedseed/validator/admission_test.go
Labels: kind/bug, size/M, area/testing, cla: yes, lgtm, approved

#7558 Support audit, authentication, authorization webhook configurations for `kube-apiserver`
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/secrets.go
Labels: kind/enhancement, size/XL, area/usability, cla: yes, lgtm, approved

#7587 Enhance `vpn-seed-server` netpol label to consider exposure class
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server_test.go
Labels: size/XS, kind/regression, area/control-plane, cla: yes, lgtm, approved

#7578 Add shoot webhook to modify coreDNS config in provider-local setup
  example/90-shoot.yaml
  pkg/operation/botanist/component/vpnshoot/vpnshoot.go
  pkg/provider-local/webhook/shoot/add.go
  pkg/provider-local/webhook/shoot/coredns.go
  pkg/provider-local/webhook/shoot/mutator.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#7535 Add documentation for webhook remediation
  docs/usage/shoot_status.md
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#7546 managedseed controller: Do not sync the Seed kubeconfig secret when Shoot's static token kubeconfig is not enabled
  pkg/gardenlet/controller/managedseed/actuator.go
  pkg/gardenlet/controller/managedseed/actuator_test.go
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
  plugin/pkg/shoot/managedseed/admission.go
  plugin/pkg/shoot/managedseed/admission_test.go
  skaffold.yaml
Labels: kind/bug, size/L, cla: yes, lgtm, approved

#7570 Adapt `NetworkPolicy`s for components in `Istio`-related namespaces
  cmd/gardenlet/app/app.go
  pkg/gardenlet/controller/networkpolicy/add.go
  pkg/gardenlet/controller/networkpolicy/add_test.go
  pkg/gardenlet/controller/networkpolicy/reconciler.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/service.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/service.yaml
  pkg/operation/botanist/component/istio/istiod.go
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/istio/monitoring.go
  pkg/operation/botanist/component/istio/networkpolicies.go
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_service.go
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_service_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/istio_config.go
  pkg/operation/istio_config_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
  test/integration/operator/garden/garden_test.go
Labels: kind/enhancement, area/dev-productivity, area/security, size/XL, area/ops-productivity, area/networking, cla: yes, lgtm, approved

#7573 [operator] Extend `operatorv1alpha1.GardenStatus` with `{ServiceAccount,ETCDEncryption}KeyRotation` fields
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/core.md
  docs/api-reference/operator.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  extensions/pkg/controller/worker/machines_test.go
  pkg/api/core/shoot/warnings_test.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/helper/helper.go
  pkg/apis/operator/v1alpha1/helper/helper_test.go
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operation/botanist/secrets_test.go
  pkg/operator/controller/garden/reconciler.go
Labels: kind/enhancement, area/usability, cla: yes, lgtm, approved, size/XXL

#7596 Use locally downloaded `yq` for gardener-up recipe
  Makefile
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7589 Adapt `NetworkPolicy`s for components in extensions-related namespaces
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  charts/gardener/provider-local/extension/templates/deployment.yaml
  charts/gardener/provider-local/extension/templates/service.yaml
  charts/gardener/provider-local/registration/templates/controller-registration.yaml
  charts/seed-bootstrap/charts/monitoring/templates/networkpolicy.yaml
  charts/seed-bootstrap/charts/monitoring/templates/statefulset.yaml
  cmd/gardener-extension-provider-local/app/app.go
  docs/deployment/feature_gates.md
  example/gardener-local/gardenlet/values.yaml
  example/provider-local/garden/base/controller-registration.yaml
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  extensions/pkg/webhook/certificates/reconciler.go
  extensions/pkg/webhook/cmd/options.go
  extensions/pkg/webhook/shoot/networkpolicy.go
  extensions/pkg/webhook/shoot/networkpolicy_test.go
  extensions/pkg/webhook/shoot/webhook.go
  extensions/pkg/webhook/shoot/webhook_test.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/features/features.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/networkpolicy/add.go
  pkg/gardenlet/controller/networkpolicy/add_test.go
  pkg/gardenlet/controller/networkpolicy/networkpolicy_suite_test.go
  pkg/gardenlet/controller/networkpolicy/reconciler.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/features/features.go
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_service.go
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_service_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/shared/resourcemanager.go
  pkg/operation/botanist/kubeapiserverexposure.go
  pkg/operator/controller/garden/components.go
  pkg/provider-local/controller/controlplane/add.go
  test/integration/extensions/webhook/certificates/certificates_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_suite_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, area/dev-productivity, area/security, size/XL, area/ops-productivity, area/networking, cla: yes, lgtm, approved

#7601 Add Johannes to `OWNER_ALIASES`
  OWNERS_ALIASES
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7604 Revert "[`prometheus`] Drop egress rule to `istio-ingressgateway`"
  charts/seed-monitoring/charts/core/charts/prometheus/templates/allow-prometheus-network-policy.yaml
Labels: size/XS, area/monitoring, kind/regression, cla: yes, lgtm, approved

#7603 Allow `blackbox-exporter` to scrape `kube-apiserver` via `istio-ingressgateway`
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/service.yaml
  pkg/operation/botanist/component/istio/istio_test.go
Labels: area/monitoring, kind/regression, size/S, cla: yes, lgtm, approved

#7608 Fix(control-plane-migration): stuck for hibernated shoots at "Waiting until ManagedResources are deleted"
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
Labels: kind/bug, size/S, area/control-plane-migration, ok-to-test, cla: yes, lgtm, approved

#7616 Update to Go 1.20.2
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#7618 Fix a minor regression in the "remote local setup" scenario
  hack/local-development/start-extension-provider-local
Labels: area/dev-productivity, size/XS, kind/regression, cla: yes, lgtm, approved

#7609 Disable the static token kubeconfig in the shoot template used for TM integration tests
  test/framework/resources/templates/default-shoot.yaml
  test/framework/utils.go
Labels: kind/enhancement, size/S, area/testing, cla: yes, lgtm, approved

#7617 Disable the static token kubeconfig in the e2e (where it is possible)
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_rotate_delete.go
Labels: kind/enhancement, size/XS, area/testing, cla: yes, lgtm, approved

#7619 Fixed broken links - 2023.03
  docs/development/new-kubernetes-version.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#7605 Add a periodSeconds and a failureThreshold to the startup probe
  docs/development/content/remote-local-setup.yaml
Labels: kind/enhancement, size/XS, area/usability, cla: yes, lgtm, approved

#7620 Disable `SeedValidator` plugin in Shoot Scheduler integration test
  test/integration/scheduler/shoot/shoot_suite_test.go
Labels: size/XS, area/testing, kind/flake, cla: yes, lgtm, approved

#7598 Add new `machinecontrollermanager` Golang component
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go
  pkg/operation/botanist/component/machinecontrollermanager/bootstrap.go
  pkg/operation/botanist/component/machinecontrollermanager/bootstrap_test.go
  pkg/operation/botanist/component/machinecontrollermanager/logging.go
  pkg/operation/botanist/component/machinecontrollermanager/logging_test.go
  pkg/operation/botanist/component/machinecontrollermanager/machine_controller_manager.go
  pkg/operation/botanist/component/machinecontrollermanager/machine_controller_manager_suite_test.go
  pkg/operation/botanist/component/machinecontrollermanager/machine_controller_manager_test.go
  pkg/operation/botanist/component/machinecontrollermanager/mock/doc.go
  pkg/operation/botanist/component/machinecontrollermanager/mock/mocks.go
  pkg/operation/botanist/component/machinecontrollermanager/monitoring.go
  pkg/operation/botanist/component/machinecontrollermanager/monitoring_test.go
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#7599 Revendor `github.com/gardener/machine-controller-manager@v0.48.1`
  extensions/pkg/controller/worker/controller.go
  extensions/pkg/controller/worker/predicate.go
  extensions/pkg/controller/worker/predicate_test.go
  go.mod
  go.sum
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/machine_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/machineclass_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/machinedeployment_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/machineset_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  vendor/modules.txt
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#7615 Clean up Grafana Unification helper functions
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/care/checker.go
  pkg/operation/care/health_check_test.go
  pkg/operation/common/utils.go
  test/integration/gardenlet/shoot/care/care_test.go
Labels: size/L, area/monitoring, kind/cleanup, cla: yes, lgtm, approved

#7612 Upgrade `k8s.io/*` to `v0.26.2`, `sigs.k8s.io/controller-runtime` to `v0.14.5`
  charts/seed-bootstrap/dashboards/client-go.json
  go.mod
  go.sum
  vendor/k8s.io/api/resource/v1alpha1/generated.proto
  vendor/k8s.io/api/resource/v1alpha1/types.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/validatingadmissionpolicy/controller_reconcile.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/delete.go
  vendor/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/component-base/logs/api/v1/pflags.go
  vendor/k8s.io/component-base/metrics/legacyregistry/registry.go
  vendor/k8s.io/component-base/metrics/metric.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/lazyrestmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/register.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/types.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go
Labels: kind/enhancement, size/XL, area/open-source, ok-to-test, cla: yes, lgtm, approved

#7622 Reorder validation and Improve documentation to decrease confusion for users
  docs/usage/pod-security.md
  pkg/apis/core/validation/shoot.go
Labels: kind/enhancement, size/XS, area/usability, cla: yes, lgtm, approved

#7624 Provide value`gardener.seed.name` for controller registration helm charts.
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: kind/enhancement, size/XS, area/control-plane, cla: yes, lgtm, approved

#7602 Drop `.spec.dns.{ingressDomain,provider.domains,provider.zones}` fields in the Seed API
  docs/api-reference/core.md
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/core/v1alpha1/types_seed_test.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/types_seed_test.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
Labels: area/dev-productivity, kind/cleanup, ok-to-test, cla: yes, lgtm, approved, size/XXL

#7629 Drop no longer needed `shoot-core/network-policies` Helm chart
  charts/shoot-core/components/charts/network-policies/Chart.yaml
  charts/shoot-core/components/charts/network-policies/charts/utils-templates
  charts/shoot-core/components/charts/network-policies/templates/allow-from-seed.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-from-to-nginx.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-to-api-server.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-to-dns.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-to-kubelet.yaml
  charts/shoot-core/components/charts/network-policies/templates/allow-to-public-networks.yaml
  charts/shoot-core/components/requirements.yaml
  charts/shoot-core/components/values.yaml
  pkg/operation/botanist/addons.go
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#7634 Fix shut down kind cluster of operator e2e test
  hack/ci-e2e-kind-operator.sh
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7621 Wait for `CSINode` object before scheduling workload pods
  docs/usage/node-readiness.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/resourcemanager/controller/node/reconciler.go
  pkg/resourcemanager/controller/node/reconciler_test.go
  test/e2e/gardener/shoot/internal/node/node.go
  test/integration/resourcemanager/node/node_test.go
Labels: kind/enhancement, size/L, area/robustness, ok-to-test, cla: yes, lgtm, approved

#7556 Add HA best practices guide
  docs/README.md
  docs/usage/shoot_high_availability.md
  docs/usage/shoot_high_availability_best_practices.md
Labels: kind/enhancement, area/documentation, size/L, cla: yes, lgtm, approved

#7633 Update `skaffold` to `v2.2.0`
  hack/tools.mk
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#7600 Cleanup deprecated functions and interface in generic `Worker` actuator
  extensions/pkg/controller/worker/genericactuator/actuator.go
  extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/genericactuator/actuator_test.go
  extensions/pkg/controller/worker/genericactuator/interface.go
  pkg/provider-local/controller/worker/machines.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#7630 Enable `FullNetworkPoliciesInRuntimeCluster` feature gate locally
  example/gardener-local/gardenlet/values.yaml
  example/provider-local/garden/base/kustomization.yaml
  example/provider-local/garden/base/patch-controller-deployment.yaml
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#7641 Cleanup deprecated functions related to `ErrorCode` detection
  extensions/pkg/controller/healthcheck/worker/nodes.go
  extensions/pkg/terraformer/terraformer.go
  pkg/apis/core/v1beta1/helper/errors.go
  pkg/apis/core/v1beta1/helper/errors_test.go
  pkg/extensions/customresources.go
  pkg/gardenlet/controller/backupbucket/reconciler.go
  pkg/gardenlet/controller/backupentry/reconciler.go
  pkg/gardenlet/controller/bastion/reconciler.go
Labels: kind/enhancement, area/ops-productivity, area/quality, size/L, cla: yes, lgtm, approved

#7652 Fix `ManagedSeed` controller integration test
  test/integration/gardenlet/managedseed/managedseed_suite_test.go
  test/integration/gardenlet/managedseed/managedseed_test.go
Labels: kind/bug, size/M, area/testing, cla: yes, lgtm, approved

#7632 Enhance client cache support in Gardenlet
  cmd/gardenlet/app/app.go
  example/gardener-local/controlplane/values.yaml
  pkg/admissioncontroller/webhook/auth/seed/authorizer.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer_test.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_seed.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
  pkg/client/kubernetes/cache/aggregator.go
  pkg/client/kubernetes/cache/aggregator_test.go
  pkg/client/kubernetes/cache/single_object.go
  pkg/client/kubernetes/cache/single_object_test.go
  pkg/client/kubernetes/runtime_client.go
  pkg/utils/miscellaneous.go
  pkg/utils/miscellaneous_test.go
Labels: kind/enhancement, area/performance, area/cost, area/robustness, area/scalability, cla: yes, lgtm, approved, size/XXL

#7656 Move `dropEnableBasicAuthenticationField` and `setKubernetesDashboardAuthMode` functions to `Canonicalize`
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: kind/bug, area/usability, size/L, cla: yes, lgtm, approved

#7654 Add hint about the optional nature of the apidiff check
  hack/check-apidiff.sh
Labels: kind/enhancement, area/open-source, size/M, cla: yes, lgtm, approved

#7663 update node local dns to version 1.22.20
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#7639 Enhance API server monitoring
  charts/seed-monitoring/charts/grafana/dashboards/owners/apiserver-overview.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-api-server-details.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-control-plane-status-dashboard.json
  pkg/operation/botanist/component/kubeapiserver/monitoring.go
  pkg/operation/botanist/component/kubeapiserver/monitoring_test.go
Labels: kind/enhancement, size/M, area/monitoring, cla: yes, lgtm, approved

#7655 Update v1.26 conformance test coverage
  README.md
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved

#7660 Drop stale condition from extension status
  extensions/pkg/controller/healthcheck/controller.go
  extensions/pkg/controller/healthcheck/reconciler.go
  pkg/provider-local/controller/healthcheck/add.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#7664 Allow pod-to-pod communication across node boundaries in local dev setup.
  docs/extensions/provider-local.md
  example/provider-local/garden/base/kustomization.yaml
  example/provider-local/garden/base/patch-controller-deployment.yaml
  example/provider-local/garden/base/patch-controller-registrations.yaml
  example/provider-local/managedseeds/shoot-managedseed.yaml
  example/provider-local/shoot.yaml
  hack/local-development/start-extension-provider-local
  pkg/provider-local/webhook/shoot/add.go
  pkg/provider-local/webhook/shoot/coredns.go
  pkg/provider-local/webhook/shoot/mutator_with_shoot_client.go
  test/e2e/gardener/common.go
Labels: kind/enhancement, area/dev-productivity, size/L, area/networking, cla: yes, lgtm, approved

#7659 Add `make gardener-dev` as a skaffold-based dev experience
  Makefile
  docs/concepts/operator.md
  docs/deployment/getting_started_locally.md
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#7650 Set `large_dir` option on the loki data disk
  charts/images.yaml
  charts/seed-bootstrap/charts/loki/templates/hvpa.yaml
  charts/seed-bootstrap/charts/loki/templates/statefulset.yaml
  charts/seed-bootstrap/charts/loki/values.yaml
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/logging.go
  pkg/operation/botanist/logging_test.go
  pkg/utils/images/images.go
Labels: kind/enhancement, size/M, area/logging, cla: yes, lgtm, approved

#7662 CVE Rescoring for nginx-ingress-controller-seed & ingress-default-backend
  charts/images.yaml
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#7678 Move a required dependency to the first `require` block, move indirect dependency to the 2nd `require` block
  go.mod
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#7670 Remove unused tenants config from fluent-bit
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/component/clusterautoscaler/logging.go
  pkg/operation/botanist/component/clusterautoscaler/logging_test.go
  pkg/operation/botanist/component/coredns/logging_test.go
  pkg/operation/botanist/component/dependencywatchdog/logging_test.go
  pkg/operation/botanist/component/etcd/logging_test.go
  pkg/operation/botanist/component/hvpa/logging_test.go
  pkg/operation/botanist/component/kubeapiserver/logging.go
  pkg/operation/botanist/component/kubeapiserver/logging_test.go
  pkg/operation/botanist/component/kubecontrollermanager/logging.go
  pkg/operation/botanist/component/kubecontrollermanager/logging_test.go
  pkg/operation/botanist/component/kubeproxy/logging_test.go
  pkg/operation/botanist/component/kubernetesdashboard/logging.go
  pkg/operation/botanist/component/kubernetesdashboard/logging_test.go
  pkg/operation/botanist/component/kubescheduler/logging.go
  pkg/operation/botanist/component/kubescheduler/logging_test.go
  pkg/operation/botanist/component/kubestatemetrics/logging_test.go
  pkg/operation/botanist/component/logging/eventlogger/logging.go
  pkg/operation/botanist/component/logging/eventlogger/logging_test.go
  pkg/operation/botanist/component/machinecontrollermanager/logging.go
  pkg/operation/botanist/component/machinecontrollermanager/logging_test.go
  pkg/operation/botanist/component/metricsserver/logging_test.go
  pkg/operation/botanist/component/nodeproblemdetector/logging_test.go
  pkg/operation/botanist/component/types.go
  pkg/operation/botanist/component/vpa/logging.go
  pkg/operation/botanist/component/vpa/logging_test.go
  pkg/operation/botanist/component/vpnseedserver/logging_test.go
  pkg/operation/botanist/component/vpnshoot/logging_test.go
Labels: size/L, area/logging, kind/cleanup, cla: yes, lgtm, approved

#7682 Make botanist code related to rotation of ETCD encryption key and `ServiceAccount` signing key reusable
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/secrets_test.go
  pkg/utils/gardener/secretsrotation/constants.go
  pkg/utils/gardener/secretsrotation/etcd.go
  pkg/utils/gardener/secretsrotation/etcd_test.go
  pkg/utils/gardener/secretsrotation/secretsrotation_suite_test.go
  pkg/utils/gardener/secretsrotation/serviceaccounts.go
  pkg/utils/gardener/secretsrotation/serviceaccounts_test.go
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#7686 Switched from DockerHub to Gardener GCR
  charts/images.yaml
Labels: kind/enhancement, area/networking, size/S, ok-to-test, cla: yes, lgtm, approved

#7684 Remove provider-local limitation with regards to multiple nodes.
  docs/extensions/provider-local.md
  example/provider-local/garden/base/kustomization.yaml
  example/provider-local/managedseeds/shoot-managedseed.yaml
  example/provider-local/shoot.yaml
  hack/kind-up.sh
  test/e2e/gardener/common.go
Labels: kind/enhancement, area/dev-productivity, size/M, area/networking, cla: yes, lgtm, approved

#7691 Harmonize licences headers in `pkg/utils/gardener/secretsrotation`
  pkg/utils/gardener/secretsrotation/constants.go
  pkg/utils/gardener/secretsrotation/etcd.go
  pkg/utils/gardener/secretsrotation/etcd_test.go
  pkg/utils/gardener/secretsrotation/secretsrotation_suite_test.go
  pkg/utils/gardener/secretsrotation/serviceaccounts.go
  pkg/utils/gardener/secretsrotation/serviceaccounts_test.go
Labels: kind/enhancement, size/S, area/compliance, cla: yes, lgtm, approved

#7692 `hack/check-license-header.sh` ignores folders related to development
  hack/add-license-header.sh
  hack/check-license-header.sh
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#7694 Fix excessive memory usage by `managedresources.NewRegistry`
  pkg/utils/managedresources/registry.go
Labels: kind/bug, area/performance, area/quality, size/S, cla: yes, lgtm, approved

#7702 Fix empty default `SEED_NAME` and `SEED_KUBECONFIG` in provider-extensions scenario
  Makefile
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7697 Align downtime validator with `kube-apiserver` readiness probe
  hack/ci-e2e-kind-upgrade.sh
  test/utils/shoots/update/highavailability/upgrade.go
Labels: size/XS, kind/test, area/testing, kind/flake, cla: yes, lgtm, approved

#7698 [GEP-21] Adapt documentation to docker hub image copying, drop `docker.io` registry mirror
  docs/development/component-checklist.md
  docs/proposals/21-ipv6-singlestack-local.md
  docs/usage/ipv6.md
  example/gardener-local/kind/cluster/templates/_containerd_config_patches.tpl
  example/gardener-local/registry/docker/kustomization.yaml
  example/gardener-local/registry/kustomization.yaml
  pkg/provider-local/imagevector/images.yaml
  pkg/provider-local/webhook/controlplane/templates/scripts/configure-containerd.tpl.sh
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved

#7687 [operator] Add missing validation for `Garden` credentials rotation operation annotations
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#7709 Fix early exit of `check-apidiff.sh`
  hack/check-apidiff.sh
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7711 Simplify apidiff check by using shell variable substitution instead of if-else block
  hack/check-apidiff.sh
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7715 Update metrics-server
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/open-source, cla: yes, lgtm, approved

#7710 Fix secret manager adoption of existing secrets
  docs/development/secrets_management.md
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#7714 Use `etcd-main` endpoint for full snapshots
  charts/gardener/gardenlet/templates/deployment.yaml
  pkg/client/kubernetes/mock/doc.go
  pkg/client/kubernetes/mock/mocks_pods.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/etcd/mock/mocks.go
  pkg/operation/botanist/etcd.go
  pkg/utils/gardener/secretsrotation/etcd_test.go
Labels: size/L, kind/technical-debt, area/control-plane, cla: yes, lgtm, approved

#7713 Improve wording and settings
  docs/usage/shoot_high_availability_best_practices.md
Labels: kind/enhancement, size/M, cla: yes, lgtm, approved

#7731 Switch from loki to logging service - stage 2
  charts/seed-bootstrap/charts/fluent-bit/templates/_fluent-bit-config.tpl
  charts/seed-bootstrap/templates/aggregate-prometheus/config.yaml
  charts/seed-bootstrap/templates/grafana/_helpers.tpl
  charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  charts/seed-monitoring/charts/grafana/templates/_helpers.tpl
  docs/usage/logging.md
Labels: kind/enhancement, size/M, area/logging, cla: yes, lgtm, approved

#7734 [operator] Consider name prefix for KAPI server certificate
  pkg/operation/botanist/component/kubeapiserver/secrets.go
Labels: kind/enhancement, area/usability, size/S, cla: yes, lgtm, approved

#7735 Also add `.cluster.local` suffix to KAPI server cert SANS
  example/90-shoot.yaml
  pkg/operation/botanist/component/kubeapiserver/secrets.go
Labels: kind/enhancement, size/XS, area/usability, cla: yes, lgtm, approved, area/ipcei

#7736 Add back `--use-env` in `prepare-envtest.sh`
  hack/prepare-envtest.sh
Labels: area/dev-productivity, size/XS, kind/regression, cla: yes, lgtm, approved

#7729 Add support for topology-aware traffic routing in the garden runtime cluster
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/service.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/service.yaml
  charts/gardener/controlplane/values.yaml
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/operator.md
  docs/concepts/operator.md
  docs/usage/topology_aware_routing.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/core/validation/seed_test.go
  pkg/apis/operator/v1alpha1/helper/helper.go
  pkg/apis/operator/v1alpha1/helper/helper_test.go
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/controller/garden/components.go
  test/e2e/operator/garden/common.go
Labels: kind/enhancement, size/L, area/networking, area/high-availability, cla: yes, lgtm, approved

#7739 Add webhook handlers to all GOP instances
  cmd/gardener-operator/app/app.go
  skaffold-operator.yaml
Labels: kind/bug, area/robustness, size/S, cla: yes, lgtm, approved, area/ipcei

#7741 Bump `nginx-ingress-controller-seed` to `v1.7.0` for `1.24.x+` seeds
  charts/images.yaml
Labels: kind/enhancement, area/open-source, size/S, area/control-plane, cla: yes, lgtm, approved

#7740 Change `update-local-ca-certificates` script path
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/rootcertificates/component_test.go
Labels: kind/enhancement, area/security, size/XS, area/compliance, cla: yes, lgtm, approved

#7738 Update to alpine 3.15.8
  charts/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#7737 Update local-setup to `kind@v0.17.0`
  hack/kind-up.sh
  hack/tools.mk
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved
