Repository gardener/gardener, pull requests merged in 2023-02, with the labels that each got.

#7404 Fix bug in `seed-lifecycle` controller changing conditions of `Shoot` to `Unknown` too fast
  pkg/controllermanager/controller/seed/lifecycle/reconciler.go
  test/integration/controllermanager/seed/lifecycle/lifecycle_test.go
Labels: kind/bug, area/ops-productivity, size/XS, cla: yes, lgtm, approved

#7416 Adapt GRM `networkpolicy` and `health` controller to use controller builder
  pkg/resourcemanager/controller/health/health/add.go
  pkg/resourcemanager/controller/networkpolicy/add.go
Labels: area/quality, size/M, kind/cleanup, area/control-plane, cla: yes, lgtm, approved

#7411 Fix `ssh-keypair` secrets deletion when `SSHAccess` is disabled
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/secrets_test.go
Labels: kind/bug, area/security, size/XS, cla: yes, lgtm, approved

#7403 Reintroduce seed zones admission checks
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
  plugin/pkg/seed/validator/admission.go
  plugin/pkg/seed/validator/admission_test.go
  plugin/pkg/utils/miscellaneous.go
  plugin/pkg/utils/miscellaneous_test.go
Labels: kind/api-change, size/L, kind/technical-debt, area/high-availability, cla: yes, lgtm, approved

#7409 Build dedicated Schemes in tests
  pkg/client/kubernetes/types.go
  test/integration/gardenlet/backupbucket/backupbucket_suite_test.go
  test/integration/gardenlet/backupentry/backupentry/backupentry_suite_test.go
  test/integration/gardenlet/backupentry/migration/migration_suite_test.go
  test/integration/gardenlet/bastion/bastion_suite_test.go
  test/integration/gardenlet/controllerinstallation/care/care_suite_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go
  test/integration/gardenlet/controllerinstallation/required/required_suite_test.go
  test/integration/gardenlet/managedseed/managedseed_suite_test.go
  test/integration/gardenlet/seed/care/care_suite_test.go
  test/integration/gardenlet/seed/lease/lease_suite_test.go
  test/integration/gardenlet/seed/seed/seed_suite_test.go
  test/integration/gardenlet/shoot/care/care_suite_test.go
  test/integration/gardenlet/shootstate/extensions/extensions_suite_test.go
  test/integration/gardenlet/shootstate/secret/secret_suite_test.go
Labels: kind/bug, size/L, area/testing, cla: yes, lgtm, approved

#7424 Revert "Configure shoot worker pool labels via `--node-labels` (#7202)"
  docs/extensions/worker.md
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/components.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/cliflags.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/cliflags_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/operation/botanist/component/extensions/worker/worker.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/worker.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/bug, size/L, cla: yes, lgtm, approved

#7425 Revert "Configure shoot worker pool labels via `--node-labels` (#7202)"
  docs/extensions/worker.md
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/components.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/cliflags.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/cliflags_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/operation/botanist/component/extensions/worker/worker.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/worker.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/bug, size/L, cla: yes, lgtm, approved

#7418 Fix bug where `sshd-ensurer` kills processes other than `sshd` when `SSHAccess` for worker nodes is disabled
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/sshdensurer/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/sshdensurer/templates/scripts/disable-sshd.tpl.sh
Labels: kind/bug, area/security, size/XS, area/compliance, cla: yes, lgtm, approved

#7408 Move logic of `networkpolicies` component into `gardenlet`'s `NetworkPolicy` controller
  docs/development/seed_network_policies.md
  hack/test-e2e-local.sh
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/networkpolicy/add.go
  pkg/gardenlet/controller/networkpolicy/add_test.go
  pkg/gardenlet/controller/networkpolicy/peers.go
  pkg/gardenlet/controller/networkpolicy/reconciler.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/component/coredns/constants/constants.go
  pkg/operation/botanist/component/coredns/coredns.go
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/networkpolicy.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/networkpolicy.yaml
  pkg/operation/botanist/component/istio/istiod.go
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/istio/networkpolicies.go
  pkg/operation/botanist/component/networkpolicies/bootstrap.go
  pkg/operation/botanist/component/networkpolicies/bootstrap_test.go
  pkg/operation/botanist/component/networkpolicies/global.go
  pkg/operation/botanist/component/networkpolicies/global_test.go
  pkg/operation/botanist/component/networkpolicies/networkpolicies.go
  pkg/operation/botanist/component/networkpolicies/networkpolicies_test.go
  pkg/operation/botanist/component/networkpolicies/peers_test.go
  pkg/operation/botanist/component/nodelocaldns/constants/constants.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns_test.go
  pkg/operation/botanist/component/shootsystem/shootsystem.go
  pkg/operation/botanist/monitoring_test.go
  pkg/operation/botanist/networkpolicies.go
  pkg/operation/botanist/networkpolicies_test.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/operation_test.go
  pkg/operation/shoot/shoot.go
  skaffold.yaml
  test/integration/gardenlet/networkpolicy/networkpolicy_suite_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
Labels: area/dev-productivity, kind/cleanup, area/networking, cla: yes, lgtm, approved, size/XXL

#7316 Local Provider: Fix containerd configuration for registry mirrors
  docs/usage/custom-containerd-config.md
  pkg/provider-local/webhook/controlplane/ensurer.go
  pkg/provider-local/webhook/controlplane/templates/scripts/configure-containerd.tpl.sh
Labels: kind/bug, area/dev-productivity, size/L, cla: yes, lgtm, approved

#7429 Cleanup of old/unusable istio configuration flags/options.
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/configmap.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/deployment.yaml
  pkg/operation/botanist/component/istio/istiod_test.go
Labels: size/M, kind/cleanup, area/networking, cla: yes, lgtm, approved

#7433 Clean up the loki PriorityClass
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile_test.go
Labels: size/M, kind/cleanup, cla: yes, lgtm, approved

#7412 Enhance `gardener-resource-manager`'s `NetworkPolicy` controller to allow simple "ingress-from-world" policy management
  docs/concepts/resource-manager.md
  pkg/apis/resources/v1alpha1/types.go
  pkg/resourcemanager/controller/networkpolicy/add.go
  pkg/resourcemanager/controller/networkpolicy/add_test.go
  pkg/resourcemanager/controller/networkpolicy/reconciler.go
  test/integration/resourcemanager/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, area/networking, cla: yes, lgtm, approved

#7428 Update etcd-druid CRDs to v0.15.3
  pkg/operation/botanist/component/etcd/crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  pkg/operation/botanist/component/etcd/crds/templates/crd-druid.gardener.cloud_etcds.yaml
Labels: kind/enhancement, size/L, cla: yes, lgtm, approved

#7436 Deploy `cluster-identity` managed resource on the seed conditionally
  cmd/gardener-apiserver/app/gardener_apiserver.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/component/clusteridentity/clusteridentity.go
  pkg/operation/botanist/component/clusteridentity/clusteridentity_test.go
  pkg/operation/care/seed_health.go
  test/integration/gardenlet/seed/seed/seed_test.go
Labels: size/L, area/robustness, kind/technical-debt, cla: yes, lgtm, approved

#7431 Simplify debugging integration tests
  Makefile
  docs/development/testing.md
  hack/prepare-envtest.sh
  hack/start-envtest.sh
  hack/test-integration.sh
  test/start-envtest/main.go
Labels: kind/enhancement, size/L, area/testing, cla: yes, lgtm, approved

#7426 Configure shoot worker pool labels via `--node-labels`
  docs/extensions/worker.md
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/components.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/cliflags.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/cliflags_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/operation/botanist/component/extensions/worker/worker.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/worker.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  pkg/utils/kubernetes/node.go
  pkg/utils/kubernetes/node_test.go
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_update_delete.go
  vendor/k8s.io/kubelet/pkg/apis/well_known_labels.go
  vendor/modules.txt
Labels: kind/enhancement, size/XL, area/robustness, cla: yes, lgtm, approved

#7434 Use `to-seed-apiserver` label for ETCD
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
Labels: kind/bug, area/robustness, size/S, area/high-availability, cla: yes, lgtm, approved

#7437 Enhance `gardener-resource-manager`'s `NetworkPolicy` controller to allow custom pod label selector
  docs/concepts/resource-manager.md
  pkg/apis/resources/v1alpha1/types.go
  pkg/resourcemanager/controller/networkpolicy/add.go
  pkg/resourcemanager/controller/networkpolicy/add_test.go
  pkg/resourcemanager/controller/networkpolicy/reconciler.go
  test/integration/resourcemanager/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, area/networking, cla: yes, lgtm, approved

#7446 Use dynamic base id for apiserver-proxy to allow running multiple envoy proxy processes.
  charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-daemonset.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#7441 Bump VPA to 0.13.0
  charts/images.yaml
  go.mod
  go.sum
  pkg/operation/botanist/component/vpa/templates/crd-verticalpodautoscalercheckpoints.tpl.yaml
  pkg/operation/botanist/component/vpa/templates/crd-verticalpodautoscalers.tpl.yaml
  pkg/operation/botanist/component/vpa/vpa_test.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
  vendor/modules.txt
Labels: kind/enhancement, size/L, area/auto-scaling, cla: yes, lgtm, approved

#7450 Remove EvictionRequirements from VPA CRD
  pkg/operation/botanist/component/vpa/templates/crd-verticalpodautoscalers.tpl.yaml
  pkg/operation/botanist/component/vpa/vpa_test.go
Labels: kind/bug, size/M, area/auto-scaling, cla: yes, lgtm, approved

#7448 Website Cleanup Part 5 - Monitoring
  docs/development/monitoring-stack.md
  docs/monitoring/alerting.md
  docs/monitoring/connectivity.md
  docs/monitoring/profiling.md
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#7435 Drop HVPA job from shoot Prometheus
  charts/seed-monitoring/charts/core/charts/prometheus/templates/allow-prometheus-network-policy.yaml
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/component/hvpa/hvpa.go
  pkg/operation/botanist/component/hvpa/mock/mocks.go
  pkg/operation/botanist/component/hvpa/monitoring.go
  pkg/operation/botanist/component/hvpa/monitoring_test.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/monitoring_test.go
  pkg/operation/shoot/types.go
Labels: size/L, area/monitoring, kind/cleanup, cla: yes, lgtm, approved

#7368 Make `.spec.networking.nodes` in `Shoot`s mutable
  docs/api-reference/core.md
  docs/deployment/feature_gates.md
  example/gardener-local/controlplane/values.yaml
  hack/local-development/start-apiserver
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/seedmanagement/validation/managedseedset_test.go
  pkg/apis/seedmanagement/validation/validation_suite_test.go
  pkg/apiserver/features/features.go
  pkg/features/features.go
  pkg/openapi/openapi_generated.go
  plugin/pkg/shoot/managedseed/admission.go
  plugin/pkg/shoot/managedseed/admission_test.go
Labels: kind/enhancement, size/L, area/networking, cla: yes, lgtm, approved

#7453 Fix failing logging integration tests against arm flavors
  test/framework/resources/templates/logger-app.yaml.tpl
  test/framework/resources/templates/vpntunnel.yaml.tpl
Labels: kind/bug, size/M, area/testing, cla: yes, lgtm, approved

#7440 Allow vpn-client in kube-apiserver to talk to seed apiserver in case of HA VPN.
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
Labels: kind/bug, size/M, area/networking, cla: yes, lgtm, approved

#7447 Update shoot_high_availability.md
  docs/usage/shoot_high_availability.md
Labels: kind/enhancement, size/XS, ok-to-test, cla: yes, lgtm, approved

#7457 Update `calico` manifests to `v3.25.0`
  example/gardener-local/calico/base/kustomization.yaml
Labels: kind/enhancement, size/XS, area/testing, cla: yes, lgtm, approved

#7373 Deflake `Seed` controller integration test
  test/integration/gardenlet/seed/seed/seed_suite_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden_suite_test.go
  test/integration/operator/garden/garden_test.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#7461 Only setup IPv6 loopback device when env varible is set
  hack/kind-up.sh
Labels: kind/bug, area/dev-productivity, size/XS, ok-to-test, cla: yes, lgtm, approved

#7454 Use a single dash for the ingress prefix of Grafana: "gu-" vs. "gu--"
  hack/test-e2e-local.sh
  pkg/operation/botanist/monitoring_test.go
  pkg/operation/operation.go
  pkg/operation/operation_test.go
Labels: kind/bug, size/M, area/monitoring, cla: yes, lgtm, approved

#7459 Fix network policy for exposure classes.
  pkg/gardenlet/controller/networkpolicy/reconciler.go
Labels: kind/bug, size/XS, area/networking, cla: yes, lgtm, approved

#7399 Drop `shootDNS` field from Seed API
  docs/api-reference/core.md
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.pb.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_seed.go
  pkg/apis/core/v1alpha1/types_seed_test.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/types_seed_test.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: kind/api-change, kind/cleanup, area/control-plane, cla: yes, lgtm, approved, size/XXL

#7007 Unify the user and operator Grafana deployments
  charts/seed-monitoring/charts/alertmanager/templates/ingress.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/ingress.yaml
  charts/seed-monitoring/charts/grafana/dashboards/owners/client-go.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/cluster-overview-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/controller-details.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/controllers.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/etcd-backup-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/etcd-cluster-details-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/etcd-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/istio/apiserver-proxy-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-api-server-watches-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-daemonsets-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-deployments-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-pods-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/kubernetes-statefulsets-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/prometheus-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/vpn-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/vpn-seed-server/envoy-proxy-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/vpn-seed-server/vpn-seed-server-dashboard.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/webhook-details.json
  charts/seed-monitoring/charts/grafana/dashboards/owners/webhooks.json
  charts/seed-monitoring/charts/grafana/templates/_helpers.tpl
  charts/seed-monitoring/charts/grafana/templates/grafana-dashboard-providers-configmap.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-dashboards-configmap.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-datasources-configmap.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-deployment.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-ingress.yaml
  charts/seed-monitoring/charts/grafana/templates/grafana-service.yaml
  charts/seed-monitoring/charts/grafana/values.yaml
  docs/deployment/getting_started_locally.md
  docs/development/getting_started_locally.md
  docs/development/priority-classes.md
  docs/extensions/logging-and-monitoring.md
  docs/usage/logging.md
  docs/usage/shoot_credentials_rotation.md
  docs/usage/trusted-tls-for-control-planes.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/seed/seed/nginxingress.go
  pkg/operation/botanist/monitoring.go
  pkg/operation/botanist/monitoring_test.go
  pkg/operation/care/checker.go
  pkg/operation/care/health_check_test.go
  pkg/operation/common/types.go
  pkg/operation/common/utils.go
  pkg/operation/operation.go
  test/integration/gardenlet/shoot/care/care_test.go
  test/testmachinery/shoots/logging/loki_tenant.go
  test/testmachinery/shoots/logging/seed_logging_stack.go
Labels: kind/enhancement, size/L, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#7465 Allow vpn-client in kube-apiserver to talk to seed apiserver in case of HA VPN
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
Labels: kind/bug, size/M, cla: yes, lgtm, approved

#7466 Allow vpn-client in kube-apiserver to talk to seed apiserver in case of HA VPN
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
Labels: kind/bug, size/M, cla: yes, lgtm, approved

#7470 Revert "Reintroduce seed zones admission checks #7403"
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
  plugin/pkg/seed/validator/admission.go
  plugin/pkg/seed/validator/admission_test.go
  plugin/pkg/utils/miscellaneous.go
  plugin/pkg/utils/miscellaneous_test.go
Labels: kind/enhancement, size/L, cla: yes, lgtm, approved

#7469 Improve docs for accessing shoot in `provider-local` setup
  docs/deployment/getting_started_locally.md
  docs/development/getting_started_locally.md
Labels: kind/enhancement, area/documentation, size/S, cla: yes, lgtm, approved

#7474 "NET_RAW" capability for the vpn-seed-server
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server_test.go
Labels: kind/bug, size/XS, area/networking, ok-to-test, cla: yes, lgtm, approved

#7464 Improve logging in `ManagedResource` controller
  pkg/resourcemanager/controller/managedresource/reconciler.go
Labels: kind/enhancement, area/ops-productivity, area/logging, size/S, cla: yes, lgtm, approved

#7397 Prefactorings for `Istio` component
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/envoy-filter.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/proxy-protocol-envoyfilter.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/proxy-protocol-gateway.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/proxy-protocol-virtualservice.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/vpn-envoy-filter.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/vpn-gateway.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/values.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/autoscale.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/clusterrole.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/clusterrolebinding.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/configmap.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/destinationrule.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/namespace.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/peerauthentication.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/poddisruptionbudget.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/role.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/rolebinding.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/service.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/serviceaccount.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/sidecar.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/templates/validatingwebhookconfiguration.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-istiod/values.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-proxy-protocol/Chart.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-proxy-protocol/values.yaml
  pkg/operation/botanist/component/istio/crds.go
  pkg/operation/botanist/component/istio/crds_test.go
  pkg/operation/botanist/component/istio/ingress_gateway.go
  pkg/operation/botanist/component/istio/istiod.go
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/istio/proxy_protocol.go
  pkg/operation/care/seed_health.go
  pkg/operation/care/seed_health_test.go
  test/integration/gardenlet/seed/care/care_test.go
Labels: kind/enhancement, kind/cleanup, area/control-plane, cla: yes, lgtm, approved, size/XXL

#7460 Remove DockerHub IPv6 Registry
  docs/development/component-checklist.md
  docs/proposals/21-ipv6-singlestack-local.md
  docs/usage/ipv6.md
  example/gardener-local/kind/cluster/templates/_containerd_config_patches.tpl
  example/gardener-local/registry/docker-ipv6/kustomization.yaml
  example/gardener-local/registry/kustomization.yaml
  pkg/provider-local/webhook/controlplane/templates/scripts/configure-containerd.tpl.sh
Labels: kind/bug, area/dev-productivity, size/M, ok-to-test, cla: yes, lgtm, approved

#7480 Improve the prerequisite step in `getting_started_locally_with_extensions.md`
  docs/deployment/getting_started_locally_with_extensions.md
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7467 Check `ResourcesApplied` condition first while reporting MR health
  pkg/operation/care/checker.go
  pkg/operation/care/health_check_test.go
Labels: kind/enhancement, area/ops-productivity, size/M, cla: yes, lgtm, approved

#7463 Remove useless replaces in `go.mod`
  go.mod
  go.sum
  vendor/golang.org/x/crypto/AUTHORS
  vendor/golang.org/x/crypto/CONTRIBUTORS
  vendor/golang.org/x/crypto/chacha20/chacha_generic.go
  vendor/golang.org/x/crypto/cryptobyte/builder.go
  vendor/golang.org/x/crypto/cryptobyte/string.go
  vendor/golang.org/x/crypto/curve25519/curve25519.go
  vendor/golang.org/x/crypto/internal/alias/alias.go
  vendor/golang.org/x/crypto/internal/alias/alias_purego.go
  vendor/golang.org/x/crypto/nacl/secretbox/secretbox.go
  vendor/golang.org/x/crypto/openpgp/packet/opaque.go
  vendor/golang.org/x/crypto/openpgp/packet/private_key.go
  vendor/golang.org/x/crypto/openpgp/packet/symmetrically_encrypted.go
  vendor/golang.org/x/crypto/openpgp/packet/userattribute.go
  vendor/golang.org/x/crypto/openpgp/packet/userid.go
  vendor/golang.org/x/crypto/openpgp/s2k/s2k.go
  vendor/golang.org/x/crypto/openpgp/write.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/connection.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/session.go
  vendor/modules.txt
Labels: size/XL, area/quality, kind/cleanup, cla: yes, lgtm, approved

#7479 Minor Makefile enhancement
  Makefile
  hack/kind-extensions-up.sh
  hack/tools.mk
Labels: kind/enhancement, area/quality, size/S, cla: yes, lgtm, approved

#7483 Website Cleanup Part 6 - Proposals (Part 1)
  docs/proposals/01-extensibility.md
  docs/proposals/02-backupinfra.md
  docs/proposals/03-networking-extensibility.md
  docs/proposals/04-new-core-gardener-cloud-apis.md
  docs/proposals/05-versioning-policy.md
  docs/proposals/06-etcd-druid.md
  docs/proposals/07-shoot-control-plane-migration.md
  docs/proposals/08-shoot-apiserver-via-sni.md
  docs/proposals/09-test-framework.md
  docs/proposals/10-shoot-additional-container-runtimes.md
  docs/proposals/11-apiserver-network-proxy.md
  docs/proposals/12-oidc-webhook-authenticator.md
  docs/proposals/13-automated-seed-management.md
  docs/proposals/assets/02-backupinfra-migration.svg
  docs/proposals/assets/02-backupinfra-provisioning-sequence-diagram.svg
  docs/proposals/assets/02-backupinfra-provisioning-with-deletion-job.svg
Labels: kind/enhancement, size/XL, area/documentation, cla: yes, lgtm, approved

#7482 Deflake `E2E Operator` test
  hack/test-e2e-local.sh
  test/e2e/gardener/shoot/internal/rotation/certificate_authorities.go
  test/e2e/gardener/shoot/internal/rotation/etcd_encryption_key.go
  test/e2e/gardener/shoot/internal/rotation/service_account_key.go
  test/e2e/operator/garden/create_delete.go
  test/e2e/operator/garden/create_rotate_delete.go
  test/e2e/operator/garden/internal/rotation/certificate_authorities.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#7472 Validate `PodSecurity` kube-apiserver admission plugin config
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/utils/validation/admissionplugins/admissionplugins.go
  pkg/utils/validation/admissionplugins/admissionplugins_test.go
  pkg/utils/version/version.go
Labels: kind/enhancement, area/usability, area/quality, size/L, cla: yes, lgtm, approved

#7406 Wait for node-critical pods before scheduling workload pods
  charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml
  charts/gardener/resource-manager/values.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-daemonset.yaml
  docs/README.md
  docs/concepts/resource-manager.md
  docs/development/component-checklist.md
  docs/development/new-kubernetes-version.md
  docs/development/testing.md
  docs/usage/node-readiness.md
  example/resource-manager/10-componentconfig.yaml
  pkg/api/indexer/gardener_core.go
  pkg/api/indexer/gardener_core_test.go
  pkg/api/indexer/gardener_operations.go
  pkg/api/indexer/gardener_operations_test.go
  pkg/api/indexer/gardener_seedmanagement.go
  pkg/api/indexer/gardener_seedmanagement_test.go
  pkg/api/indexer/kubernetes_core.go
  pkg/api/indexer/kubernetes_core_test.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/client/kubernetes/types.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
  pkg/operation/botanist/component/kubeproxy/kube_proxy_test.go
  pkg/operation/botanist/component/kubeproxy/resources.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns.go
  pkg/operation/botanist/component/nodelocaldns/nodelocaldns_test.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/resourcemanager/apis/config/types.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults_test.go
  pkg/resourcemanager/apis/config/v1alpha1/types.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/resourcemanager/apis/config/zz_generated.deepcopy.go
  pkg/resourcemanager/controller/add.go
  pkg/resourcemanager/controller/node/add.go
  pkg/resourcemanager/controller/node/add_test.go
  pkg/resourcemanager/controller/node/helper/daemon_controller.go
  pkg/resourcemanager/controller/node/node_suite_test.go
  pkg/resourcemanager/controller/node/reconciler.go
  pkg/resourcemanager/controller/node/reconciler_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go
  test/e2e/gardener/shoot/internal/node/node.go
  test/integration/resourcemanager/node/node_suite_test.go
  test/integration/resourcemanager/node/node_test.go
  vendor/k8s.io/component-helpers/scheduling/corev1/doc.go
  vendor/k8s.io/component-helpers/scheduling/corev1/helpers.go
  vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go
  vendor/modules.txt
Labels: kind/enhancement, area/robustness, cla: yes, lgtm, approved, size/XXL

#7478 Add response rewrite to dns-search-path-optimization.
  docs/usage/dns-search-path-optimization.md
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/operation/botanist/component/coredns/coredns.go
  pkg/operation/botanist/component/coredns/coredns_test.go
  plugin/pkg/shoot/dnsrewriting/apis/shootdnsrewriting/validation/validation_test.go
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved

#7489 Remove the Proposals section from the public website
  .docforge/manifest.yaml
Labels: kind/enhancement, area/documentation, size/S, cla: yes, lgtm, approved

#7462 Consider all MR in `shoot` namespace in `seed` for health check except one having class seed
  docs/extensions/healthcheck-library.md
  docs/extensions/shoot-health-status-conditions.md
  pkg/operation/care/health.go
  test/integration/gardenlet/shoot/care/care_suite_test.go
  test/integration/gardenlet/shoot/care/care_test.go
Labels: kind/enhancement, area/quality, size/L, area/control-plane, cla: yes, lgtm, approved

#7491 Use previous minor version of Gardener for upgrade tests
  hack/ci-e2e-kind-upgrade.sh
Labels: kind/bug, kind/test, area/robustness, size/S, area/testing, cla: yes, lgtm, approved

#7493 Remove High Availability annotation support
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
Labels: size/L, kind/cleanup, area/high-availability, cla: yes, lgtm, approved

#7494 Remove limit defaults from helm charts for controlplane components
  charts/gardener/controlplane/values.yaml
Labels: kind/enhancement, size/XS, area/control-plane, area/auto-scaling, cla: yes, lgtm, approved

#7490 Bump `nginx-ingress-controller-seed` to `v1.6.4` for 1.23+ seeds
  charts/images.yaml
  pkg/operation/botanist/component/nginxingress/nginxingress.go
  pkg/operation/botanist/component/nginxingress/nginxingress_test.go
Labels: kind/enhancement, area/open-source, size/M, area/control-plane, cla: yes, lgtm, approved

#7439 Update `kubectl wait` command to handle multiple conditions correctly
  docs/deployment/getting_started_locally.md
  docs/development/getting_started_locally.md
  example/gardener-local/kind/cluster/templates/cluster.yaml
  hack/ci-e2e-kind-upgrade.sh
  hack/usage/wait-for.sh
  skaffold.yaml
  test/utils/shoots/update/highavailability/upgrade.go
Labels: kind/bug, size/L, kind/test, area/testing, cla: yes, lgtm, approved

#7484 Adapt `NetworkPolicy`s for components scraped by Prometheis in shoot namespaces
  charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/service.yaml
  charts/seed-bootstrap/charts/loki/templates/allow-prometheus-to-loki-telegraf.yaml
  charts/seed-bootstrap/charts/loki/templates/service.yaml
  charts/seed-bootstrap/charts/loki/templates/statefulset.yaml
  charts/seed-bootstrap/charts/loki/values.yaml
  charts/seed-monitoring/charts/alertmanager/templates/alertmanager.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/allow-prometheus-network-policy.yaml
  charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  docs/concepts/resource-manager.md
  docs/development/seed_network_policies.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/networkpolicy/reconciler.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go
  pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler_test.go
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/component/istio/networkpolicies.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/networkpolicies.go
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_service.go
  pkg/operation/botanist/component/kubeapiserverexposure/kube_apiserver_service_test.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go
  pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler.go
  pkg/operation/botanist/component/kubescheduler/kube_scheduler_test.go
  pkg/operation/botanist/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/operation/botanist/component/kubestatemetrics/resources.go
  pkg/operation/botanist/component/logging/eventlogger/event_logger.go
  pkg/operation/botanist/component/logging/eventlogger/event_logger_test.go
  pkg/operation/botanist/component/monitoring/blackbox_exporter.go
  pkg/operation/botanist/component/monitoring/prometheus.go
  pkg/operation/botanist/component/resourcemanager/resource_manager.go
  pkg/operation/botanist/component/resourcemanager/resource_manager_test.go
  pkg/operation/botanist/component/vpa/recommender.go
  pkg/operation/botanist/component/vpa/updater.go
  pkg/operation/botanist/component/vpa/vpa_test.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server_test.go
  pkg/operation/botanist/logging.go
  pkg/operation/botanist/logging_test.go
  pkg/provider-local/controller/infrastructure/actuator.go
  pkg/utils/gardener/networkpolicy.go
  pkg/utils/gardener/networkpolicy_test.go
  pkg/utils/miscellaneous.go
  pkg/utils/miscellaneous_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
  test/integration/operator/garden/garden_test.go
Labels: kind/enhancement, area/security, size/XL, area/networking, cla: yes, lgtm, approved

#7498 Support kubeconfigs for admission plugin configurations for `kube-apiserver`
  pkg/operation/botanist/component/kubeapiserver/configmaps.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/secrets.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
Labels: kind/enhancement, size/XL, area/usability, cla: yes, lgtm, approved

#7502 `hack/format.sh` now supports custom options for goimports-reviser
  hack/format.sh
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#7520 Add responsibles to networking components.
  charts/images.yaml
Labels: kind/enhancement, area/documentation, area/networking, size/S, area/compliance, cla: yes, lgtm, approved

#7524 Docs: use `brew --prefix` instead of hardcoded path
  docs/development/local_setup.md
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#7526 Fix `make kind2-up` locally
  example/gardener-local/kind/local2/values.yaml
  pkg/gardenlet/controller/managedseed/add.go
  pkg/operation/care/checker.go
Labels: kind/bug, area/dev-productivity, size/S, cla: yes, lgtm, approved

#7495 Use `shoots/adminkubeconfig` subresource for the Shoot kubeconfig downloaded during the Shoot creation test
  test/framework/k8s_utils.go
  test/framework/shootcreationframework.go
Labels: size/M, kind/cleanup, area/testing, cla: yes, lgtm, approved

#7514 Enhance etcd deploy flow to consider existing peer secrets when setting peer secrets
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
Labels: kind/bug, size/L, area/high-availability, area/control-plane, cla: yes, lgtm, approved

#7518 Support TLS SNI configurations for `kube-apiserver`
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/kubeapiserver/secrets.go
Labels: kind/enhancement, area/usability, size/L, area/networking, cla: yes, lgtm, approved

#7523 Remove user tenants logs, adjust testmachinery and rename docker_id
  charts/images.yaml
  charts/seed-bootstrap/charts/fluent-bit/values.yaml
  docs/extensions/logging-and-monitoring.md
  test/testmachinery/shoots/logging/seed_logging_stack.go
  test/testmachinery/shoots/logging/shoot_logging.go
  test/testmachinery/shoots/logging/utils.go
Labels: size/L, area/logging, kind/cleanup, cla: yes, lgtm, approved

#7503 Disable the static token kubeconfig in the shoot template used for TM integration tests
  test/framework/resources/templates/default-shoot.yaml
Labels: size/XS, kind/cleanup, area/testing, cla: yes, lgtm, approved

#7533 Fixed `wait-for.sh` not to exit script for `kubectl` errors until it reaches timeout
  hack/usage/wait-for.sh
Labels: size/XS, kind/test, area/robustness, area/testing, cla: yes, lgtm, approved

#7504 Export resource YAMLs of `seeds`, `shoots`, `etcds` for prow jobs
  Makefile
  hack/ci-common.sh
  hack/ci-e2e-kind-ha-multi-zone.sh
  hack/ci-e2e-kind-ha-single-zone.sh
  hack/ci-e2e-kind-migration.sh
  hack/ci-e2e-kind-operator.sh
  hack/ci-e2e-kind-upgrade.sh
  hack/ci-e2e-kind.sh
Labels: size/M, kind/test, area/robustness, area/testing, cla: yes, lgtm, approved

#7536 Fix the `should download shoot kubeconfig successfully` integration test
  docs/api-reference/core.md
  docs/concepts/gardenlet.md
  docs/usage/shoot_status.md
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_cloudprofile.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/openapi/openapi_generated.go
  test/testmachinery/shoots/applications/shoot_app.go
Labels: kind/bug, size/S, area/testing, cla: yes, lgtm, approved

#7537 Update golangci-lint to v1.51.2 to support go 1.20
  hack/tools.mk
  hack/tools/gomegacheck/go.mod
  hack/tools/gomegacheck/go.sum
  hack/tools/logcheck/go.mod
  hack/tools/logcheck/go.sum
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#7516 `ManagedResource` controller should recreate `ConfigMap`s/`Secret`s on invalid update
  pkg/resourcemanager/controller/managedresource/reconciler.go
  test/integration/resourcemanager/managedresource/resource_suite_test.go
  test/integration/resourcemanager/managedresource/resource_test.go
Labels: kind/enhancement, area/ops-productivity, size/M, cla: yes, lgtm, approved

#7542 Update to Go 1.19.6
  .test-defs/CreateShoot.yaml
  .test-defs/DeleteShoot.yaml
  .test-defs/HibernateShoot.yaml
  .test-defs/MigrateShoot.yaml
  .test-defs/ReconcileShoots.yaml
  .test-defs/ShootKubernetesUpdateTest.yaml
  .test-defs/TestSuiteGardenerBeta.yaml
  .test-defs/TestSuiteGardenerBetaSerial.yaml
  .test-defs/TestSuiteGardenerDefault.yaml
  .test-defs/TestSuiteGardenerDefaultSerial.yaml
  .test-defs/TestSuiteGardenerRelease.yaml
  .test-defs/TestSuiteGardenerReleaseSerial.yaml
  .test-defs/TestSuiteShootBeta.yaml
  .test-defs/TestSuiteShootBetaDisruptive.yaml
  .test-defs/TestSuiteShootBetaSerial.yaml
  .test-defs/TestSuiteShootDefault.yaml
  .test-defs/TestSuiteShootDefaultDisruptive.yaml
  .test-defs/TestSuiteShootDefaultSerial.yaml
  .test-defs/TestSuiteShootRelease.yaml
  .test-defs/TestSuiteShootReleaseDisruptive.yaml
  .test-defs/TestSuiteShootReleaseSerial.yaml
  .test-defs/WakeUpShoot.yaml
  Dockerfile
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#7528 Document that 127.0.0.2 has to be added to the loopback interface
  docs/deployment/getting_started_locally.md
  docs/development/getting_started_locally.md
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved

#7551 Use `adminkubeconfig` in migration test
  test/framework/shootmigrationtest.go
Labels: kind/bug, size/S, cla: yes, lgtm, approved

#7555 Revert "Disable the static token kubeconfig in the shoot template used for TM integration tests"
  test/framework/resources/templates/default-shoot.yaml
Labels: kind/bug, size/S, area/testing, cla: yes, lgtm, approved

#7554 Fix `etcd` peer-tls configuration
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
  pkg/operator/controller/garden/components.go
Labels: kind/bug, size/L, cla: yes, lgtm, approved

#7552 Updates etcd-druid CRDs to v0.16.0
  pkg/operation/botanist/component/etcd/crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  pkg/operation/botanist/component/etcd/crds/templates/crd-druid.gardener.cloud_etcds.yaml
Labels: kind/enhancement, size/M, cla: yes, lgtm, approved

#7562 Fix NetworkPolicy labels for HA VPN
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/vpn-envoy-filter.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/templates/vpn-gateway.yaml
  pkg/operation/botanist/component/istio/charts/istio/istio-ingress/values.yaml
  pkg/operation/botanist/component/istio/ingress_gateway.go
  pkg/operation/botanist/component/istio/istiod_test.go
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
  pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
  pkg/operation/shoot/shoot.go
Labels: kind/bug, area/security, size/M, area/high-availability, cla: yes, lgtm, approved

#7560 [release-v1.64] Fix `etcd` peer-tls configuration
  pkg/operation/botanist/component/etcd/etcd.go
  pkg/operation/botanist/component/etcd/etcd_test.go
  pkg/operation/botanist/etcd.go
  pkg/operation/botanist/etcd_test.go
  pkg/operator/controller/garden/components.go
Labels: kind/bug, size/L, area/high-availability, cla: yes, lgtm, approved

#7564 Increase fluent-bit memory request and limit
  charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#7543 Removes `BackupEntry` and `Shoot` migration reconcilers and the `ForceRestore` feature gate
  charts/gardener/gardenlet/templates/_helpers.tpl
  charts/gardener/gardenlet/values.yaml
  docs/concepts/gardenlet.md
  docs/deployment/feature_gates.md
  example/20-componentconfig-gardenlet.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/features/features.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/backupentry/add.go
  pkg/gardenlet/controller/backupentry/add_test.go
  pkg/gardenlet/controller/backupentry/backupentry/add.go
  pkg/gardenlet/controller/backupentry/backupentry_suite_test.go
  pkg/gardenlet/controller/backupentry/migration/add.go
  pkg/gardenlet/controller/backupentry/migration/reconciler.go
  pkg/gardenlet/controller/backupentry/reconciler.go
  pkg/gardenlet/controller/backupentry/reconciler_test.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/gardenlet/controller/shoot/add.go
  pkg/gardenlet/controller/shoot/migration/add.go
  pkg/gardenlet/controller/shoot/migration/reconciler.go
  pkg/gardenlet/features/features.go
  skaffold.yaml
  test/integration/gardenlet/backupentry/backupentry/backupentry_suite_test.go
  test/integration/gardenlet/backupentry/backupentry/backupentry_test.go
  test/integration/gardenlet/backupentry/migration/migration_suite_test.go
  test/integration/gardenlet/backupentry/migration/migration_test.go
  test/integration/gardenlet/shoot/migration/migration_suite_test.go
  test/integration/gardenlet/shoot/migration/migration_test.go
Labels: kind/cleanup, area/control-plane-migration, cla: yes, lgtm, approved, size/XXL

#7547 Refactor `apiserver-proxy` Helm chart into Golang component
  charts/shoot-core/components/charts/apiserver-proxy/templates/_helpers.tpl
  charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-daemonset.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-pod-mutatingwebhook.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-service.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-serviceaccount.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/proxy-configmap.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/psp/apiserver-proxy-clusterrole.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/psp/apiserver-proxy-psp.yaml
  charts/shoot-core/components/charts/apiserver-proxy/templates/psp/apiserver-proxy-rolebinding.yaml
  charts/shoot-core/components/charts/apiserver-proxy/values.yaml
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/apiserver_proxy.go
  pkg/operation/botanist/botanist.go
  pkg/operation/botanist/component/apiserverproxy/apiserver_proxy.go
  pkg/operation/botanist/component/apiserverproxy/apiserver_proxy_suite_test.go
  pkg/operation/botanist/component/apiserverproxy/apiserver_proxy_test.go
  pkg/operation/botanist/component/apiserverproxy/templates/envoy.yaml.tpl
  pkg/operation/shoot/types.go
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, area/quality, area/robustness, cla: yes, lgtm, approved, size/XXL

#7557 Fixed the golang error in remote-local-setup and made improvements
  docs/deployment/content/remote-local-setup.yaml
  docs/development/content/remote-local-setup.yaml
Labels: kind/bug, area/dev-productivity, size/M, area/testing, cla: yes, lgtm, approved

#7559 Add additional information about custom server config to custom-dns-config docs.
  docs/usage/custom-dns-config.md
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#7534 Prepare for the removal of the `enableBasicAuthentication` field
  docs/api-reference/core.md
  example/90-shoot.yaml
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1alpha1/defaults.go
  pkg/apis/core/v1alpha1/defaults_test.go
  pkg/apis/core/v1alpha1/generated.proto
  pkg/apis/core/v1alpha1/types_shoot.go
  pkg/apis/core/v1beta1/defaults.go
  pkg/apis/core/v1beta1/defaults_test.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/openapi/openapi_generated.go
  pkg/operation/botanist/component/kubernetesdashboard/kubernetes_dashboard_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  test/framework/resources/templates/default-shoot.yaml
Labels: size/L, kind/cleanup, cla: yes, lgtm, approved

#7569 Migration step 2 for deploying `cluster-identity` managed resource on the seed conditionally
  cmd/gardener-apiserver/app/gardener_apiserver.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/component/clusteridentity/clusteridentity.go
  test/integration/gardenlet/seed/seed/seed_test.go
Labels: size/M, area/robustness, kind/technical-debt, cla: yes, lgtm, approved

#7571 Update goimports-reviser to v3.3.1
  hack/tools.mk
Labels: area/dev-productivity, size/XS, kind/cleanup, cla: yes, lgtm, approved

#7567 Support specifying resources to store in `etcd-events` for `kube-apiserver`
  pkg/operation/botanist/component/kubeapiserver/deployment.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
Labels: kind/enhancement, area/usability, size/M, cla: yes, lgtm, approved

#7563 Validate updates of the `AuditPolicy` against the `k8s` version of `Shoot`s
  pkg/admissioncontroller/webhook/admission/auditpolicy/handler.go
  pkg/admissioncontroller/webhook/admission/auditpolicy/handler_test.go
Labels: kind/bug, size/M, area/control-plane, area/audit-logging, cla: yes, lgtm, approved

#7575 Update docs that logging is a config option (not a feature gate)
  docs/extensions/logging-and-monitoring.md
Labels: size/XS, area/documentation, kind/cleanup, cla: yes, lgtm, approved

#7574 Drop no longer required `shoot-addons` Helm chart
  charts/shoot-addons/Chart.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/Chart.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/charts/utils-templates
  charts/shoot-addons/charts/kubernetes-dashboard/templates/configmap.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/deployment-dashboard.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/deployment-metrics-scraper.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/namespace.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/rbac.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/secret.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/service-dashboard.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/service-metrics-scraper.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/serviceaccount.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/templates/vpa.yaml
  charts/shoot-addons/charts/kubernetes-dashboard/values.yaml
  charts/shoot-addons/charts/nginx-ingress/Chart.yaml
  charts/shoot-addons/charts/nginx-ingress/charts/utils-templates
  charts/shoot-addons/charts/nginx-ingress/templates/clusterrole.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/clusterrolebinding.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-configmap.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-deployment.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/controller-service.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/default-backend-deployment.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/default-backend-service.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/ingressclass.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/psp/nginx-ingress-rolebinding-privileged.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/role.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/rolebinding.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/serviceaccount.yaml
  charts/shoot-addons/charts/nginx-ingress/templates/vpa.yaml
  pkg/operation/botanist/addons.go
  pkg/operation/botanist/addons_test.go
  pkg/operation/botanist/nginxingress.go
  pkg/operation/botanist/nginxingress_test.go
  pkg/operation/botanist/operatingsystemconfig.go
  pkg/operation/botanist/waiter.go
Labels: area/dev-productivity, kind/cleanup, cla: yes, lgtm, approved, size/XXL
