Repository gardener/gardener, pull requests merged in 2024-10, with the labels that each got.

#10592 [release-v1.104] update dependency gardener/etcd-druid to v0.22.7
  imagevector/containers.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#10593 provider-extensions setup: Disable Seed VPA by default
  example/provider-extensions/gardenlet/values.yaml.tmpl
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#10594 Clarify documentation regarding Managed Service Account Issuer enablement
  docs/usage/shoot_serviceaccounts.md
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#10537 [GEP-27] Add extensions bastion util function
  extensions/pkg/bastion/bastion_suite_test.go
  extensions/pkg/bastion/machine.go
  extensions/pkg/bastion/machine_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#10587 [GEP-26] Grant gardener users with access to CredentialsBindings and WorkloadIdentities
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
  pkg/component/garden/system/virtual/virtual.go
  pkg/component/garden/system/virtual/virtual_test.go
Labels: kind/enhancement, area/security, size/M, area/user-management, cla: yes, lgtm, approved, area/ipcei, ipcei/workload-identity

#10605 Fix extracting the `go` binaries in the remote local setup
  docs/deployment/content/remote-local-setup.yaml
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#10599 Promote `VPAForETCD` and `VPAAndHPAForAPIServer` feature gates to GA
  docs/deployment/feature_gates.md
  docs/development/autoscaling-specifics-for-components.md
  pkg/features/features.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
Labels: kind/enhancement, size/L, area/auto-scaling, cla: yes, lgtm, approved

#10608 Drop `TopologySpreadConstraint`s special case
  docs/concepts/resource-manager.md
  pkg/utils/kubernetes/highavailability.go
  pkg/utils/kubernetes/highavailability_test.go
  test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_test.go
Labels: kind/enhancement, size/M, area/high-availability, cla: yes, lgtm, approved

#10600 Prepare next Dev Cycle v1.106.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#10566 local setup: Disable the HVPA feature gates
  charts/gardener/operator/values.yaml
  docs/deployment/deploy_gardenlet_manually.md
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/gardenlet/values.yaml
  example/operator/10-componentconfig.yaml
  test/e2e/operator/garden/create_delete.go
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#10562 Add Garden condition alert and accompanying dashboard
  pkg/component/observability/monitoring/prometheus/garden/prometheusrules.go
  pkg/component/observability/plutono/dashboards/garden/garden-resource.json
  pkg/component/observability/plutono/plutono_test.go
Labels: kind/enhancement, size/XL, area/monitoring, cla: yes, lgtm, approved

#10603 Backdate generated certificates slightly (1 min) to allow a certain clock skew of clients.
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  extensions/pkg/util/secret/manager/manager_test.go
  pkg/apiserver/registry/core/shoot/storage/kubeconfig_test.go
  pkg/utils/secrets/certificate.go
  pkg/utils/secrets/manager/generate_test.go
Labels: kind/enhancement, area/security, area/ops-productivity, size/M, area/robustness, cla: yes, lgtm, approved

#10517 Collect `vpa-recommender` metrics in separate prometheus instances
  pkg/component/autoscaling/vpa/recommender.go
  pkg/component/autoscaling/vpa/vpa.go
  pkg/component/autoscaling/vpa/vpa_test.go
  pkg/component/observability/plutono/dashboards/common/vpa/vpa-recommender.json
  pkg/component/observability/plutono/dashboards/seed/vpa-recommender.json
  pkg/component/observability/plutono/plutono.go
  pkg/component/observability/plutono/plutono_test.go
  pkg/gardenlet/controller/seed/seed/components.go
Labels: kind/enhancement, area/monitoring, area/auto-scaling, cla: yes, lgtm, approved, size/XXL

#10472 Support for Kubernetes v1.31
  README.md
  docs/development/new-kubernetes-version.md
  docs/extensions/operatingsystemconfig.md
  docs/usage/supported_k8s_versions.md
  example/operator/20-garden.yaml
  example/provider-extensions/garden/configure-admission.sh
  example/provider-local/garden/base/cloudprofile.yaml
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler_test.go
  pkg/gardenlet/operation/botanist/operatingsystemconfig.go
  pkg/provider-local/webhook/controlplane/ensurer.go
  pkg/resourcemanager/controller/node/criticalcomponents/helper/daemon_controller.go
  pkg/utils/kubernetes/controllers.go
  pkg/utils/validation/admissionplugins/admissionplugins.go
  pkg/utils/validation/apigroups/apigroups.go
  pkg/utils/validation/apigroups/apigroups_test.go
  pkg/utils/validation/features/featuregates.go
  pkg/utils/validation/kubernetesversion/version.go
  pkg/utils/validation/kubernetesversion/version_test.go
  pkg/utils/version/version.go
  pkg/utils/version/version_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
  test/utils/shoots/update/update.go
Labels: kind/enhancement, size/XL, area/open-source, cla: yes, lgtm, approved

#10597 Remove obsolete migration code from the monitoring component
  pkg/component/observability/monitoring/kubestatemetrics/kubestatemetrics.go
  pkg/component/observability/monitoring/kubestatemetrics/kubestatemetrics_test.go
  pkg/component/observability/monitoring/kubestatemetrics/resources.go
  pkg/component/observability/plutono/dashboards/common/vpa/vpa-dashboard.json
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
Labels: kind/enhancement, size/L, area/monitoring, cla: yes, lgtm, approved

#10604 CIS 4.1.5 ensure kubelet config has permissions set to 600
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
Labels: kind/enhancement, size/XS, area/compliance, ok-to-test, cla: yes, lgtm, approved

#10318 [GEP-27] Add CloudProfile Bastion Validation
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#10622 set correct IPFamilies value for vpn-client apiserver sidecar
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
Labels: kind/bug, size/XS, area/networking, cla: yes, lgtm, approved

#10630 docs: Use correct emoji name
  docs/proposals/01-extensibility.md
Labels: area/documentation, kind/cleanup, size/S, cla: yes, lgtm, approved

#10625 Fix cAdvisor network metric relabeling config
  pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/cadvisor.yaml
  pkg/component/observability/monitoring/prometheus/cache/scrapeconfigs_test.go
  pkg/component/observability/monitoring/prometheus/shoot/scrapeconfigs.go
  pkg/component/observability/monitoring/prometheus/shoot/scrapeconfigs_test.go
Labels: area/monitoring, kind/regression, size/S, cla: yes, lgtm, approved

#10558 Update istio to version 1.23.2
  go.mod
  go.sum
  imagevector/containers.yaml
  pkg/component/networking/istio/charts/istio/README.md
  pkg/component/networking/istio/charts/istio/istio-ingress/values.yaml
  pkg/component/networking/istio/test_charts/ingress_autoscaler.yaml
  pkg/component/networking/istio/test_charts/ingress_deployment.yaml
  pkg/component/networking/istio/test_charts/ingress_service.yaml
  pkg/component/networking/istio/test_charts/ingress_service_dualstack.yaml
  pkg/component/networking/istio/test_charts/ingress_service_dualstack_etp.yaml
  pkg/component/networking/istio/test_charts/ingress_service_etp_cluster.yaml
  pkg/component/networking/istio/test_charts/ingress_service_etp_local.yaml
  pkg/component/networking/istio/test_charts/ingress_serviceaccount.yaml
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved

#10642 Allow `gosec` to be consumed by extensions via vgo
  hack/tools.mk
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#10641 [NewVPN] Enable IPv6 for HA if needed.
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/seedserver/seedserver_test.go
Labels: kind/enhancement, size/M, area/control-plane, cla: yes, lgtm, approved

#10572 Adapt gardener-dashboard component
  docs/concepts/operator.md
  pkg/component/gardener/dashboard/config/config.go
  pkg/component/gardener/dashboard/configmap.go
  pkg/component/gardener/dashboard/dashboard.go
  pkg/component/gardener/dashboard/dashboard_test.go
  pkg/component/gardener/dashboard/deployment.go
  pkg/component/gardener/dashboard/rbac.go
  pkg/component/gardener/dashboard/secrets.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#10649 Add Tobias to `OWNER_ALIASES`
  OWNERS_ALIASES
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#10647 Fix Authenticationconfig admission webhook and use `v1beta1`
  docs/usage/shoot_access.md
  pkg/admissioncontroller/webhook/admission/authenticationconfig/handler.go
  pkg/admissioncontroller/webhook/admission/authenticationconfig/handler_test.go
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/authentication.go
  pkg/component/kubernetes/apiserver/authentication_test.go
Labels: kind/bug, area/security, size/L, cla: yes, lgtm, approved

#10549 [node-agent-authorizer] auto-approve `gardener-node-agent` CSRs in `gardener-resource-manager`
  charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml
  charts/gardener/resource-manager/values.yaml
  docs/concepts/resource-manager.md
  example/resource-manager/10-componentconfig.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/gardener/resourcemanager/resource_manager.go
  pkg/component/gardener/resourcemanager/resource_manager_test.go
  pkg/resourcemanager/apis/config/types.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults_test.go
  pkg/resourcemanager/apis/config/v1alpha1/types.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/resourcemanager/apis/config/validation/validation.go
  pkg/resourcemanager/apis/config/validation/validation_test.go
  pkg/resourcemanager/apis/config/zz_generated.deepcopy.go
  pkg/resourcemanager/controller/add.go
  pkg/resourcemanager/controller/csrapprover/add.go
  pkg/resourcemanager/controller/csrapprover/reconciler.go
  test/integration/resourcemanager/csrapprover/csrapprover_suite_test.go
  test/integration/resourcemanager/csrapprover/csrapprover_test.go
Labels: kind/enhancement, area/security, size/XL, cla: yes, lgtm, approved

#10658 Updated file name for "High Availability of Deployed Components" topic
  docs/README.md
  docs/concepts/resource-manager.md
  docs/development/autoscaling-specifics-for-components.md
  docs/development/component-checklist.md
  docs/development/high-availability-of-components.md
  docs/extensions/conventions.md
  docs/operations/topology_aware_routing.md
  pkg/gardenlet/operation/botanist/kubeapiserver.go
Labels: kind/enhancement, area/documentation, size/S, cla: yes, lgtm, approved

#10659 Deprecate `HVPA` and `HVPAForShootedSeed` feature gates
  docs/deployment/feature_gates.md
  docs/development/autoscaling-specifics-for-components.md
  pkg/features/features.go
  pkg/features/features_test.go
  pkg/gardenlet/operation/botanist/etcd_test.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
  pkg/operator/controller/garden/care/health_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden/garden_test.go
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#10668 Prepare next Dev Cycle v1.107.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#10240 Propagate `Infrastructure.status.egressCIDRs` to `Shoot.status.networking.egressCIDRs`
  docs/api-reference/core.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/api_violations.report
  pkg/apiserver/openapi/openapi_generated.go
  pkg/gardenlet/operation/botanist/infrastructure.go
  pkg/gardenlet/operation/botanist/infrastructure_test.go
  pkg/provider-local/controller/infrastructure/actuator.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/enhancement, size/XL, area/usability, area/networking, cla: yes, lgtm, approved

#10660 Clean up migration logic for the clean up of the stale alertmanager VPA resources
  cmd/gardenlet/app/migration.go
  pkg/operator/controller/garden/care/care_suite_test.go
Labels: size/M, area/monitoring, kind/cleanup, area/auto-scaling, cla: yes, lgtm, approved

#10662 [GEP-26] Promote ShootCredentialsBinding to beta
  docs/deployment/feature_gates.md
  example/gardener-local/controlplane/values.yaml
  pkg/features/features.go
Labels: kind/enhancement, area/security, size/XS, cla: yes, lgtm, approved, area/ipcei, ipcei/workload-identity

#10672 [GEP-26] Fix bug where shoot care controller uses outdated credentials config
  pkg/gardenlet/controller/shoot/care/types.go
  pkg/gardenlet/operation/operation.go
  pkg/gardenlet/operation/shoot/shoot.go
Labels: kind/bug, kind/enhancement, area/security, size/S, cla: yes, lgtm, approved, area/ipcei, ipcei/workload-identity

#10654 Support shoot access restriction configurations in `CloudProfile`, `Seed`, and `Shoot` APIs
  docs/README.md
  docs/api-reference/core.md
  docs/concepts/scheduler.md
  docs/usage/shoot/access_restrictions.md
  example/30-cloudprofile.yaml
  example/50-seed.yaml
  example/90-shoot.yaml
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types.go
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/types_seed.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/api_violations.report
  pkg/apiserver/openapi/openapi_generated.go
  pkg/apiserver/registry/core/cloudprofile/strategy.go
  pkg/apiserver/registry/core/cloudprofile/strategy_test.go
  pkg/apiserver/registry/core/seed/strategy.go
  pkg/apiserver/registry/core/seed/strategy_test.go
  pkg/apiserver/registry/core/shoot/strategy.go
  pkg/apiserver/registry/core/shoot/strategy_test.go
  pkg/scheduler/controller/shoot/reconciler.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  test/integration/scheduler/shoot/shoot_test.go
Labels: kind/enhancement, kind/api-change, area/usability, cla: yes, lgtm, approved, size/XXL

#10648 Make ManagedSeed's `.spec.gardenlet` field a required field
  docs/api-reference/seedmanagement.md
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler.go
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler_test.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_managedseed.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
  pkg/apis/seedmanagement/helper/helper.go
  pkg/apis/seedmanagement/helper/helper_test.go
  pkg/apis/seedmanagement/types_managedseed.go
  pkg/apis/seedmanagement/v1alpha1/conversions.go
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseed.go
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseed_test.go
  pkg/apis/seedmanagement/v1alpha1/generated.pb.go
  pkg/apis/seedmanagement/v1alpha1/generated.proto
  pkg/apis/seedmanagement/v1alpha1/helper/helper.go
  pkg/apis/seedmanagement/v1alpha1/helper/helper_test.go
  pkg/apis/seedmanagement/v1alpha1/types_managedseed.go
  pkg/apis/seedmanagement/v1alpha1/zz_generated.conversion.go
  pkg/apis/seedmanagement/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/seedmanagement/v1alpha1/zz_generated.defaults.go
  pkg/apis/seedmanagement/validation/managedseed.go
  pkg/apis/seedmanagement/validation/managedseed_test.go
  pkg/apis/seedmanagement/validation/managedseedset_test.go
  pkg/apis/seedmanagement/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/apiserver/registry/seedmanagement/managedseed/storage/tableconvertor.go
  pkg/controller/gardenletdeployer/actuator_test.go
  pkg/controllermanager/controller/managedseedset/replica.go
  pkg/controllermanager/controller/managedseedset/replica_test.go
  pkg/gardenlet/controller/managedseed/reconciler.go
  pkg/gardenlet/controller/managedseed/reconciler_test.go
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
  plugin/pkg/shoot/managedseed/admission.go
  plugin/pkg/shoot/managedseed/admission_test.go
  test/e2e/gardener/managedseed/create_rotate_delete.go
  test/integration/controllermanager/managedseedset/managedseedset_test.go
  test/integration/controllermanager/seed/lifecycle/lifecycle_test.go
  test/integration/controllermanager/shoot/conditions/conditions_test.go
  test/integration/gardenlet/managedseed/managedseed_test.go
Labels: kind/enhancement, size/XL, area/quality, cla: yes, lgtm, approved

#10676 [release-v1.103] [GEP-26] Fix bug where shoot care controller uses outdated credentials config
  pkg/gardenlet/controller/shoot/care/types.go
  pkg/gardenlet/operation/operation.go
  pkg/gardenlet/operation/shoot/shoot.go
Labels: kind/bug, area/security, size/S, cla: yes, lgtm, approved, area/ipcei, ipcei/workload-identity

#10681 `WithoutShootCredentials` uses empty secret instead of nil object
  pkg/gardenlet/operation/shoot/shoot.go
Labels: kind/bug, size/XS, area/quality, cla: yes, lgtm, approved

#10674 [release-v1.105] [GEP-26] Fix bug where shoot care controller uses outdated credentials config
  pkg/gardenlet/controller/shoot/care/types.go
  pkg/gardenlet/operation/operation.go
  pkg/gardenlet/operation/shoot/shoot.go
Labels: kind/bug, area/security, size/S, cla: yes, lgtm, approved, area/ipcei, ipcei/workload-identity

#10673 [release-v1.106] [GEP-26] Fix bug where shoot care controller uses outdated credentials config
  pkg/gardenlet/controller/shoot/care/types.go
  pkg/gardenlet/operation/operation.go
  pkg/gardenlet/operation/shoot/shoot.go
Labels: kind/bug, area/security, size/S, cla: yes, lgtm, approved, area/ipcei, ipcei/workload-identity

#10675 [release-v1.104] [GEP-26] Fix bug where shoot care controller uses outdated credentials config
  pkg/gardenlet/controller/shoot/care/types.go
  pkg/gardenlet/operation/operation.go
  pkg/gardenlet/operation/shoot/shoot.go
Labels: kind/bug, area/security, size/S, cla: yes, lgtm, approved, area/ipcei, ipcei/workload-identity

#10585 [operator] Cleanup webhook configuration from virtual cluster when removing admission deployment
  charts/gardener/admission-local/charts/runtime/templates/deployment.yaml
  charts/gardener/admission-local/charts/runtime/values.yaml
  extensions/pkg/webhook/cmd/options.go
  extensions/pkg/webhook/registration.go
  pkg/operator/controller/extension/admission/admission.go
  pkg/operator/controller/extension/admission/admission_test.go
  pkg/operator/controller/garden/garden/reconciler_delete.go
Labels: kind/enhancement, area/ops-productivity, size/L, cla: yes, lgtm, approved

#10688 provider-local/node: Bump `kindest/node` image to v1.31.1
  pkg/provider-local/node/Dockerfile
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#10689 Allow Service Account Managed Issuer feature for workerless shoots
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved, area/ipcei, ipcei/oidc

#10535 [node-agent-authorizer] Introduce `node-agent-authorizer` webhook in `gardener-resource-manager`
  charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml
  charts/gardener/resource-manager/values.yaml
  docs/concepts/resource-manager.md
  example/resource-manager/10-componentconfig.yaml
  pkg/admissioncontroller/webhook/add.go
  pkg/admissioncontroller/webhook/auth/seed/add.go
  pkg/admissioncontroller/webhook/auth/seed/webhook.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/resourcemanager/apis/config/types.go
  pkg/resourcemanager/apis/config/v1alpha1/types.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/resourcemanager/apis/config/validation/validation.go
  pkg/resourcemanager/apis/config/validation/validation_test.go
  pkg/resourcemanager/apis/config/zz_generated.deepcopy.go
  pkg/resourcemanager/webhook/add.go
  pkg/resourcemanager/webhook/nodeagentauthorizer/add.go
  pkg/resourcemanager/webhook/nodeagentauthorizer/authorizer.go
  pkg/resourcemanager/webhook/nodeagentauthorizer/authorizer_test.go
  pkg/resourcemanager/webhook/nodeagentauthorizer/identity.go
  pkg/resourcemanager/webhook/nodeagentauthorizer/identity_test.go
  pkg/resourcemanager/webhook/nodeagentauthorizer/nodeagentauthorizer_suite_test.go
  pkg/resourcemanager/webhook/nodeagentauthorizer/webhook.go
  pkg/webhook/authorizer/attributes.go
  pkg/webhook/authorizer/attributes_test.go
  pkg/webhook/authorizer/authorizer_suite_test.go
  pkg/webhook/authorizer/handler.go
  pkg/webhook/authorizer/handler_test.go
  pkg/webhook/authorizer/response.go
  pkg/webhook/authorizer/response_test.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL

#10694 make generate
  pkg/apiserver/openapi/openapi_generated.go
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#10693 Do not overwrite machine state with nil data
  pkg/utils/gardener/shootstate/shootstate.go
  pkg/utils/gardener/shootstate/shootstate_test.go
  test/integration/gardenlet/shoot/state/state_test.go
Labels: kind/bug, size/M, area/control-plane-migration, cla: yes, lgtm, approved

#10700 Update ca version for k8s 1.29
  imagevector/containers.yaml
Labels: kind/enhancement, size/XS, area/control-plane, area/auto-scaling, cla: yes, lgtm, approved

#10492 Add label selector to ShootResourceReservation plugin
  docs/concepts/apiserver-admission-plugins.md
  example/20-admissionconfig.yaml
  plugin/pkg/shoot/resourcereservation/admission.go
  plugin/pkg/shoot/resourcereservation/admission_test.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/types.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/defaults.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/defaults_test.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/types.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/v1alpha1_suite_test.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/zz_generated.conversion.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/zz_generated.deepcopy.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/zz_generated.defaults.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/zz_generated.deepcopy.go
Labels: kind/enhancement, size/L, area/robustness, cla: yes, lgtm, approved

#10678 ipv6 support for node-local-dns
  pkg/component/networking/nodelocaldns/constants/constants.go
  pkg/component/networking/nodelocaldns/mock/mocks.go
  pkg/component/networking/nodelocaldns/nodelocaldns.go
  pkg/component/networking/nodelocaldns/nodelocaldns_test.go
  pkg/controller/networkpolicy/reconciler.go
  pkg/gardenlet/operation/botanist/nodelocaldns.go
  pkg/gardenlet/operation/botanist/nodelocaldns_test.go
  pkg/gardenlet/operation/botanist/operatingsystemconfig.go
  pkg/gardenlet/operation/botanist/operatingsystemconfig_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, size/L, area/networking, cla: yes, lgtm, approved

#10704 e2e tests: Bump the Shoot Kubernetes version to 1.31.1
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/enhancement, size/XS, area/testing, cla: yes, lgtm, approved

#10632 Create Resources folder in the Extensions directory
  docs/README.md
  docs/concepts/backup-restore.md
  docs/concepts/etcd.md
  docs/concepts/gardenlet.md
  docs/concepts/node-agent.md
  docs/concepts/operator.md
  docs/concepts/resource-manager.md
  docs/extensions/cluster.md
  docs/extensions/controlplane-webhooks.md
  docs/extensions/healthcheck-library.md
  docs/extensions/referenced-resources.md
  docs/extensions/resources/backupbucket.md
  docs/extensions/resources/backupentry.md
  docs/extensions/resources/bastion.md
  docs/extensions/resources/containerruntime.md
  docs/extensions/resources/controlplane-exposure.md
  docs/extensions/resources/controlplane.md
  docs/extensions/resources/dnsrecord.md
  docs/extensions/resources/extension.md
  docs/extensions/resources/infrastructure.md
  docs/extensions/resources/network.md
  docs/extensions/resources/operatingsystemconfig.md
  docs/extensions/resources/worker.md
  docs/proposals/15-manage-bastions-and-ssh-key-pair-rotation.md
  docs/usage/shoot/shoot_workerless.md
  pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit.go
Labels: kind/enhancement, area/documentation, size/L, cla: yes, lgtm, approved

#10257 Tag images with `garden.local.gardener.cloud` instead of `localhost` for local setup
  Makefile
  docs/deployment/getting_started_locally.md
  docs/deployment/getting_started_locally_with_extensions.md
  hack/ci-common.sh
  hack/ci-e2e-kind-ha-multi-zone.sh
  hack/ci-e2e-kind-ha-single-zone.sh
  hack/ci-e2e-kind-migration-ha-single-zone.sh
  hack/ci-e2e-kind-migration.sh
  hack/ci-e2e-kind-operator-seed.sh
  hack/ci-e2e-kind-operator.sh
  hack/ci-e2e-kind-upgrade.sh
  hack/ci-e2e-kind.sh
  hack/gardener-extensions-up.sh
  hack/kind-up.sh
  hack/push-helm.sh
  hack/test-e2e-local.sh
  pkg/provider-local/webhook/controlplane/ensurer.go
  pkg/utils/oci/helmregistry.go
  pkg/utils/oci/helmregistry_test.go
  skaffold-operator-garden.yaml
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved, area/ipcei

#10706 Deprecate `gardener/controlplane` Helm chart in favor of `gardener-operator`
  charts/gardener/controlplane/Chart.yaml
  charts/gardener/controlplane/README.md
  docs/deployment/setup_gardener.md
Labels: kind/enhancement, area/dev-productivity, area/open-source, size/S, cla: yes, lgtm, approved

#10713 Ignore completed `Pod`s in health check
  pkg/utils/kubernetes/health/deployment.go
  pkg/utils/kubernetes/health/deployment_test.go
  pkg/utils/kubernetes/health/pod.go
  pkg/utils/kubernetes/health/pod_test.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#10721 Deflake `operator/gardenlet` integration test
  test/integration/operator/gardenlet/gardenlet_test.go
Labels: area/dev-productivity, size/XS, kind/flake, cla: yes, lgtm, approved

#10719 docs: Document debugging in GoLand and VS Code
  docs/deployment/getting_started_locally.md
Labels: kind/enhancement, area/dev-productivity, area/documentation, size/S, cla: yes, lgtm, approved

#10730 chore: Add marc1404 to OWNER_ALIASES
  OWNERS_ALIASES
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#10526 Update module and dependency gardener/etcd-druid to `v0.23.1`
  example/seed-crds/10-crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  example/seed-crds/10-crd-druid.gardener.cloud_etcds.yaml
  go.mod
  go.sum
  hack/generate-crds.sh
  imagevector/containers.yaml
  pkg/component/etcd/etcd/bootstrap.go
  pkg/component/etcd/etcd/bootstrap_test.go
  pkg/component/etcd/etcd/crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  pkg/component/etcd/etcd/crds/templates/crd-druid.gardener.cloud_etcds.yaml
  pkg/component/etcd/etcd/etcd.go
  pkg/component/etcd/etcd/etcd_test.go
  pkg/component/etcd/etcd/waiter.go
  pkg/component/etcd/etcd/waiter_test.go
  pkg/component/shared/etcd_druid.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/operator/controller/garden/garden/components.go
  pkg/provider-local/controller/backupentry/actuator.go
  pkg/provider-local/controller/backupoptions/options.go
Labels: kind/enhancement, size/XL, area/backup, area/quality, area/control-plane, cla: yes, lgtm, approved

#10716 Remove feature gate `IPv6SingleStack`.
  docs/deployment/deploy_gardenlet_manually.md
  docs/deployment/feature_gates.md
  docs/development/ipv6.md
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/controlplane/values.yaml
  example/gardener-local/gardenlet/values.yaml
  pkg/apis/core/validation/seed_test.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/validation/utils.go
  pkg/apis/core/validation/utils_test.go
  pkg/apiserver/features/features.go
  pkg/features/features.go
  pkg/gardenlet/features/features.go
  skaffold.yaml
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved

#10733 Add dual-stack support for coredns
  pkg/component/networking/coredns/coredns.go
  pkg/component/networking/coredns/coredns_test.go
  pkg/component/networking/coredns/mock/mocks.go
  pkg/gardenlet/operation/botanist/coredns.go
  pkg/gardenlet/operation/botanist/coredns_test.go
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved

#10520 [GEP-26] Gardener with extensions dev setup now supports deploying the gardener discovery server
  Makefile
  docs/deployment/getting_started_locally_with_extensions.md
  example/provider-extensions/garden/controlplane/.gitignore
  example/provider-extensions/garden/controlplane/workload-identity-issuer.yaml.tmpl
  example/provider-extensions/gardener-discovery-server/deploy.sh
  example/provider-extensions/gardener-discovery-server/load-balancer/resources.yaml
  example/provider-extensions/gardener-discovery-server/rbac/clusterrole.yaml
  example/provider-extensions/gardener-discovery-server/rbac/clusterrolebinding.yaml
  example/provider-extensions/gardener-discovery-server/rbac/role.yaml
  example/provider-extensions/gardener-discovery-server/rbac/rolebinding.yaml
  example/provider-extensions/gardener-discovery-server/rbac/serviceaccount.yaml
  example/provider-extensions/gardener-discovery-server/server/server.yaml
  example/provider-extensions/gardener-discovery-server/server/serviceaccount.yaml
  example/provider-extensions/seed/configure-discovery-server.sh
  example/provider-extensions/seed/configure-seed.sh
  hack/gardener-down.sh
  hack/gardener-extensions-down.sh
  hack/gardener-extensions-up.sh
  hack/tools.mk
  hack/tools/oidcmeta/main.go
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved, area/ipcei, ipcei/workload-identity

#10749 Group etcd-druid dependency updates
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#10536 [GEP-28] Autonomous Shoot Clusters
  docs/README.md
  docs/proposals/28-autonomous-shoot-clusters.md
  docs/proposals/assets/28-overview.png
  logo/gardenadm-large.png
  logo/gardenadm.svg
Labels: kind/enhancement, size/XL, area/documentation, cla: yes, lgtm, approved

#10711 Allow viewers `pods/log` access
  pkg/component/shoot/system/system.go
  pkg/component/shoot/system/system_test.go
Labels: kind/enhancement, area/usability, size/S, cla: yes, lgtm, approved

#10742 Add type label to `NamespacedCloudProfile`s in admission
  plugin/pkg/global/extensionlabels/admission.go
  plugin/pkg/global/extensionlabels/admission_test.go
Labels: kind/enhancement, area/usability, size/M, cla: yes, lgtm, approved

#10744 Fix `/etc/hosts` configuration in the remote local setup
  docs/deployment/content/remote-local-setup.yaml
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#10720 Allow garden prometheus to scrape extensions outside of garden namespace
  docs/extensions/logging-and-monitoring.md
  docs/operations/network_policies.md
  pkg/operator/controller/garden/garden/components.go
Labels: kind/enhancement, area/monitoring, area/networking, size/S, cla: yes, lgtm, approved

#10710 chore: Introduce Make target `operator-seed-dev`
  Makefile
  docs/deployment/getting_started_locally.md
  skaffold.yaml
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#10723 kind: Bump `kindest/node` image to v1.31.1
  example/gardener-local/kind/cluster/templates/_kubeadm_config_patches.tpl
  example/gardener-local/kind/cluster/values.yaml
  hack/kind-up.sh
Labels: kind/enhancement, size/M, cla: yes, lgtm, approved

#10756 Change `etcd-druid` webhook server port to `10250`
  pkg/component/etcd/etcd/bootstrap.go
  pkg/component/etcd/etcd/bootstrap_test.go
Labels: kind/bug, size/S, area/control-plane, cla: yes, lgtm, approved

#10655 `ManagedSeed` defaults Ingress kind to `nginx` when `seedSpec` is not specified
  docs/operations/managed_seed.md
  example/provider-local/managedseeds/managedseed.yaml
  pkg/apis/seedmanagement/v1alpha1/defaults_gardenlet_test.go
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseed_test.go
  pkg/apis/seedmanagement/validation/managedseed.go
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
Labels: kind/enhancement, area/quality, size/M, cla: yes, lgtm, approved

#10743 Add check for using plain http on helm push only if registry is glgc
  hack/push-helm.sh
Labels: area/dev-productivity, size/XS, kind/regression, cla: yes, lgtm, approved

#10757 Fix Prometheus rule `shoot-kube-proxy` (kube-proxy.rules)
  pkg/component/kubernetes/proxy/proxy.go
  pkg/component/kubernetes/proxy/proxy_test.go
Labels: kind/bug, area/monitoring, size/S, cla: yes, lgtm, approved

#10754 Prepare next dev cycle v1.108.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#10762 Several `renovate` tuning measurements
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#10760 Fix index out of range error in access restriction handling
  pkg/apiserver/registry/core/shoot/strategy.go
  pkg/apiserver/registry/core/shoot/strategy_test.go
Labels: kind/bug, area/robustness, size/S, cla: yes, lgtm, approved

#10768 Fix network validation for Shoot control plane migration case.
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/bug, size/S, area/control-plane-migration, cla: yes, lgtm, approved

#10772 Revert "chore(deps): update dependency kyverno/kyverno to v1.13.0 (#10746)"
  example/provider-extensions/kyverno/kustomization.yaml
Labels: area/dev-productivity, size/XS, kind/regression, cla: yes, lgtm, approved

#10773 Support VGO in environments where `$GOPATH` is not set and Go `bin` directories are not part of `$PATH`
  hack/vgopath-setup.sh
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved
