Repository gardener/gardener, pull requests merged in 2024-02, with the labels that each got.

#9094 Remove the GA-ed `WorkerlessShoots` feature gate
  docs/deployment/feature_gates.md
  pkg/apiserver/features/features.go
  pkg/features/features.go
  pkg/registry/core/shoot/strategy_test.go
Labels: kind/cleanup, size/S, cla: yes, lgtm, approved

#9069 Set Shoot K8s version for e2e tests to Kubernetes v1.29
  example/gardener-local/kind/cluster/values.yaml
  hack/kind-up.sh
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/enhancement, area/open-source, size/S, cla: yes, lgtm, approved

#9075 Fix missing update of botanist state with dynamic node network CIDR determined by infrastructure provider
  pkg/component/coredns/coredns.go
  pkg/component/coredns/mock/mocks.go
  pkg/component/kubeapiserver/kube_apiserver.go
  pkg/component/kubeapiserver/mock/mocks.go
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/component/vpnseedserver/mock/mocks.go
  pkg/component/vpnseedserver/vpn_seed_server.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/operation/botanist/coredns.go
  pkg/operation/botanist/coredns_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/kubeapiserver_test.go
  pkg/operation/botanist/vpnseedserver.go
  pkg/operation/botanist/vpnseedserver_test.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
Labels: kind/bug, size/L, area/networking, area/high-availability, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#9084 Added descriptions to the concept topics
  docs/concepts/admission-controller.md
  docs/concepts/apiserver.md
  docs/concepts/apiserver_admission_plugins.md
  docs/concepts/architecture.md
  docs/concepts/backup-restore.md
  docs/concepts/cluster-api.md
  docs/concepts/controller-manager.md
  docs/concepts/etcd.md
  docs/concepts/gardenlet.md
  docs/concepts/node-agent.md
  docs/concepts/operator.md
  docs/concepts/resource-manager.md
  docs/concepts/scheduler.md
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#9101 Make ClientMap accessible
  pkg/client/kubernetes/clientmap/alias.go
  pkg/client/kubernetes/clientmap/builder/garden_builder.go
  pkg/client/kubernetes/clientmap/builder/shoot_builder.go
  pkg/client/kubernetes/clientmap/clientmap_suite_test.go
  pkg/client/kubernetes/clientmap/garden_clientmap.go
  pkg/client/kubernetes/clientmap/garden_clientmap_test.go
  pkg/client/kubernetes/clientmap/generic_clientmap.go
  pkg/client/kubernetes/clientmap/generic_clientmap_test.go
  pkg/client/kubernetes/clientmap/keys/keys.go
  pkg/client/kubernetes/clientmap/keys/keys_test.go
  pkg/client/kubernetes/clientmap/shoot_clientmap.go
  pkg/client/kubernetes/clientmap/shoot_clientmap_test.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/open-source, size/L, cla: yes, lgtm, approved

#9079 Allow additional or custom permissions for extensions in garden cluster defined via RBAC
  docs/concepts/controller-manager.md
  docs/concepts/resource-manager.md
  docs/extensions/garden-api-access.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/resources/v1alpha1/types.go
  pkg/controller/tokenrequestor/reconciler.go
  pkg/controllermanager/controller/controllerregistration/add.go
  pkg/controllermanager/controller/controllerregistration/extensionclusterrole/add.go
  pkg/controllermanager/controller/controllerregistration/extensionclusterrole/add_test.go
  pkg/controllermanager/controller/controllerregistration/extensionclusterrole/extensionclusterrole_suite_test.go
  pkg/controllermanager/controller/controllerregistration/extensionclusterrole/reconciler.go
  pkg/controllermanager/controller/seed/secrets/reconciler.go
  pkg/controllermanager/controller/seed/secrets/reconciler_test.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/controllermanager/controllerregistration/extensionclusterrole/extensionclusterrole_suite_test.go
  test/integration/controllermanager/controllerregistration/extensionclusterrole/extensionclusterrole_test.go
  test/integration/controllermanager/controllerregistration/seed/seed_suite_test.go
  test/integration/controllermanager/controllerregistration/seed/seed_test.go
  test/integration/controllermanager/seed/secrets/secrets_test.go
  test/integration/resourcemanager/tokenrequestor/tokenrequestor_test.go
Labels: kind/enhancement, area/security, area/usability, cla: yes, lgtm, approved, size/XXL

#9102 Change dnsLookupFamily to ALL in vpn seed envoy config.
  pkg/component/vpnseedserver/vpn_seed_server.go
  pkg/component/vpnseedserver/vpn_seed_server_test.go
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#9110 [node-agent] `worker.gardener.cloud/kubernetes-version` should be a label
  pkg/nodeagent/controller/operatingsystemconfig/reconciler.go
  test/integration/nodeagent/operatingsystemconfig/operatingsystemconfig_test.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#9109 fix: also configure snapshots as component-prefix
  hack/.ci/component_descriptor
Labels: kind/bug, area/delivery, size/XS, cla: yes, lgtm, approved

#9114 [node-agent] Log `hostname` in `gardener-node-agent`
  cmd/gardener-node-agent/app/app.go
Labels: kind/enhancement, area/ops-productivity, size/XS, cla: yes, lgtm, approved

#9120 Bump up fluent-bit to v2.2.2
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#9118 Remove SAP news from documentation
  README.md
Labels: size/XS, area/documentation, kind/cleanup, ok-to-test, cla: yes, lgtm, approved

#9121 Add `extensionswebhook.EnsureUnitWithName` func to add unit to OSC units
  extensions/pkg/webhook/utils.go
  extensions/pkg/webhook/utils_test.go
  go.mod
  go.sum
Labels: kind/enhancement, size/L, cla: yes, lgtm, approved

#9125 [release-v1.86] Bump `nginx-ingress-controller` image to `v1.9.6`
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/open-source, area/control-plane, cla: yes, lgtm, approved

#9077 [node-agent] Create `gardener` Linux user when nodes are bootstrapping
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/provider-local/controller/operatingsystemconfig/actuator.go
Labels: kind/enhancement, area/ops-productivity, size/L, cla: yes, lgtm, approved

#9124 Bump `nginx-ingress-controller` image to `v1.9.6`
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/open-source, area/control-plane, cla: yes, lgtm, approved

#9024 [GEP-24] Shoot OIDC Issuer
  docs/proposals/24-shoot-oidc-issuer.md
Labels: kind/enhancement, area/security, area/usability, size/L, cla: yes, lgtm, approved, area/ipcei

#9119 Update various tools
  hack/tools.mk
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved

#9129 Prepare next Dev Cycle v1.89.0-dev
  VERSION
Labels: kind/enhancement, size/XS, area/open-source, cla: yes, lgtm, approved

#9133 [release-v1.87] Bump `nginx-ingress-controller` image to `v1.9.6`
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/open-source, area/control-plane, cla: yes, lgtm, approved

#9106 Drop remaining usages of docker CRI
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/core.md
  docs/extensions/operatingsystemconfig.md
  docs/usage/shoot_operations.md
  example/30-cloudprofile.yaml
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/provider-local/garden/base/cloudprofile.yaml
  extensions/pkg/controller/worker/machines.go
  extensions/pkg/controller/worker/machines_test.go
  pkg/apis/core/types_common.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/defaults_cloudprofile.go
  pkg/apis/core/v1beta1/defaults_cloudprofile_test.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_common.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/cliflags.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/cliflags_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler_test.go
  pkg/openapi/openapi_generated.go
  test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_suite_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
  test/integration/scheduler/shoot/shoot_test.go
Labels: size/XL, kind/cleanup, cla: yes, lgtm, approved

#9038 Drop `nginx-ingress` load balancer in favor of `Istio`
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/operator.md
  example/gardener-local/kind/cluster/templates/_extra_port_mappings.tpl
  example/gardener-local/kind/cluster/templates/cluster.yaml
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/component/kubeapiserverexposure/kube_apiserver_sni.go
  pkg/component/nginxingress/nginxingress.go
  pkg/component/nginxingress/nginxingress_test.go
  pkg/component/shared/istio.go
  pkg/component/shared/istio_test.go
  pkg/component/shared/nginx_ingress.go
  pkg/controller/service/reconciler.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/nginxingress.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/webhook/validation/handler_test.go
  pkg/provider-local/controller/service/add.go
  pkg/utils/istio/destinationrule.go
  pkg/utils/istio/destinationrule_test.go
  pkg/utils/istio/gateway.go
  pkg/utils/istio/gateway_test.go
  pkg/utils/istio/istio_suite_test.go
  pkg/utils/istio/virtualservice.go
  pkg/utils/istio/virtualservice_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/e2e/operator/garden/common.go
  test/e2e/operator/garden/create_rotate_delete.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/care/care_test.go
  test/integration/operator/garden/garden/garden_test.go
  test/integration/operator/garden/reference/reference_test.go
  test/utils/rotation/observability.go
Labels: kind/enhancement, area/networking, cla: yes, lgtm, approved, size/XXL

#9122 [Documentation] Defaulting guidelines
  docs/README.md
  docs/development/defaulting.md
Labels: area/documentation, size/M, kind/technical-debt, cla: yes, lgtm, approved

#9123 Sync cluster CA to `ConfigMap` and use it in `shoots/{admin,viewer}kubeconfig` subresource
  docs/usage/shoot_credentials_rotation.md
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler.go
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler_test.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer_test.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_shoot.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operation/botanist/plutono.go
  pkg/operation/botanist/secrets.go
  pkg/operation/botanist/secrets_test.go
  pkg/registry/core/rest/storage_core.go
  pkg/registry/core/shoot/storage/admin_kubeconfig.go
  pkg/registry/core/shoot/storage/kubeconfig.go
  pkg/registry/core/shoot/storage/kubeconfig_test.go
  pkg/registry/core/shoot/storage/storage.go
  pkg/registry/core/shoot/storage/viewer_kubeconfig.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  pkg/utils/secrets/certificate.go
  test/e2e/gardener/shoot/create_rotate_delete.go
  test/e2e/gardener/shoot/internal/rotation/certificate_authorities.go
  test/e2e/gardener/shoot/internal/rotation/kubeconfig.go
  test/e2e/gardener/shoot/internal/rotation/ssh_keypair.go
  test/testmachinery/shoots/operations/operations.go
  test/utils/access/statictokenkubeconfig.go
Labels: kind/enhancement, area/security, size/XL, area/usability, cla: yes, lgtm, approved

#9143 [release-v1.88] Allow `docker` CRI to be specified in the cloudprofile for one more version
  example/provider-local/garden/base/cloudprofile.yaml
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved

#9134 Update golang variants, add golang 1.22
  hack/tools/image/variants.yaml
Labels: kind/enhancement, size/XS, area/testing, ok-to-test, cla: yes, lgtm, approved

#9139 Annotate `kube-apiserver` deployment after labeling the resources for encryption
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  pkg/utils/gardener/secretsrotation/constants.go
  pkg/utils/gardener/secretsrotation/etcd.go
  pkg/utils/gardener/secretsrotation/etcd_test.go
Labels: kind/bug, area/security, size/M, area/control-plane, cla: yes, lgtm, approved

#9144 Remove `ConditionPathExists` from `valitail` systemd unit
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config_test.go
Labels: kind/bug, area/ops-productivity, size/XS, cla: yes, lgtm, approved

#9146 🔎 Enable `unconvert` and `unparam` linters
  .golangci.yaml
  extensions/pkg/controller/healthcheck/message_util.go
  extensions/pkg/controller/healthcheck/reconciler.go
  extensions/pkg/webhook/cmd/factory_test.go
  extensions/pkg/webhook/network/network.go
  extensions/pkg/webhook/shoot/shoot.go
  pkg/admissioncontroller/webhook/admission/namespacedeletion/handler_test.go
  pkg/apis/core/v1beta1/helper/errors_test.go
  pkg/apis/core/validation/quota.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/client/kubernetes/chartapplier_test.go
  pkg/client/kubernetes/runtime_client.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/component/kubecontrollermanager/kube_controller_manager_test.go
  pkg/component/kubescheduler/kube_scheduler_test.go
  pkg/component/logging/vali/vali.go
  pkg/component/logging/vali/vali_test.go
  pkg/component/resourcemanager/resource_manager_test.go
  pkg/component/vpa/vpa_test.go
  pkg/component/vpnshoot/vpnshoot.go
  pkg/controllermanager/controller/seed/secrets/reconciler_test.go
  pkg/controllerutils/finalizers_test.go
  pkg/gardenlet/controller/seed/seed/reconciler.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/shoot/care/health_test.go
  pkg/gardenlet/controller/shoot/care/webhook_remediation_test.go
  pkg/nodeagent/registry/containerd_extractor_test.go
  pkg/operation/botanist/extension.go
  pkg/operation/botanist/secrets_test.go
  pkg/operator/controller/garden/care/health_test.go
  pkg/resourcemanager/controller/garbagecollector/reconciler_test.go
  pkg/resourcemanager/webhook/crddeletionprotection/handler_test.go
  pkg/utils/imagevector/imagevector.go
  pkg/utils/kubernetes/health/checker/checker_test.go
  pkg/utils/validation/cidr/cidr_test.go
  pkg/utils/validation/cidr/helper_test.go
  plugin/pkg/shoot/managedseed/admission.go
  test/integration/resourcemanager/health/health_test.go
  test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_test.go
  test/integration/scheduler/shoot/shoot_test.go
  test/testmachinery/shoots/logging/utils.go
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#9156 Change license headers to SPDX format
  hack/.ci/component_descriptor
  hack/.ci/doc.go
  hack/.ci/prepare_release
  hack/.ci/set_dependency_version
  hack/generate-controller-registration.sh
Labels: size/M, kind/cleanup, area/compliance, cla: yes, lgtm, approved, area/ipcei

#9160 Only wait for`PersistentVolume` to be `Available` when `.spec.claimRef` was removed
  pkg/component/monitoring/prometheus/migration.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#9153 tools: drop yaml2json dependency in favour of yq
  Makefile
  docs/monitoring/operator_alerts.md
  go.mod
  go.sum
  hack/generate-imagename-constants.sh
  hack/generate-monitoring-docs.sh
  hack/tools.go
  hack/tools.mk
  pkg/component/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/rules/worker/kube-pods.rules.yaml
Labels: area/quality, kind/cleanup, size/S, ok-to-test, cla: yes, lgtm, approved

#9155 Update to `kindest/node:v1.29.0`
  example/gardener-local/kind/cluster/templates/_kubeadm_config_patches.tpl
  hack/kind-up.sh
Labels: kind/task, size/S, area/testing, cla: yes, lgtm, approved

#9165 Update containerd registry configuration docs
  docs/usage/containerd-registry-configuration.md
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#9007 Enhance `Ensure_` functions from `extensions/pkg/webhook` package
  extensions/pkg/webhook/controlplane/test/matchers.go
  extensions/pkg/webhook/utils.go
  extensions/pkg/webhook/utils_test.go
Labels: kind/enhancement, area/quality, cla: yes, lgtm, approved, size/XXL

#9161 Promote `UseGardenerNodeAgent` feature gate to beta
  docs/deployment/feature_gates.md
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/extensions/operatingsystemconfig/original/original_test.go
  pkg/features/features.go
  pkg/operation/botanist/operatingsystemconfig_test.go
  pkg/operation/botanist/worker_test.go
Labels: kind/enhancement, area/open-source, size/L, cla: yes, lgtm, approved

#9141 Align controllerregistration documentation with the implementation
  docs/extensions/controllerregistration.md
Labels: kind/enhancement, area/documentation, size/S, cla: yes, lgtm, approved

#9168 adapt configure-admission.sh for new provider-extensions
  example/provider-extensions/garden/configure-admission.sh
Labels: area/dev-productivity, size/XS, kind/technical-debt, cla: yes, lgtm, approved

#9170 Add GEP-24 to the index of all GEPs
  docs/README.md
Labels: kind/bug, size/XS, area/documentation, cla: yes, lgtm, approved

#9127 Add Prometheus alert for nodes not ready on seeds
  pkg/component/monitoring/charts/bootstrap/aggregate-prometheus-rules/seed.rules.yaml
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#9158 Align component management in seed controller with component management in garden controller
  pkg/gardenlet/controller/seed/seed/add.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/nginxingress.go
  pkg/gardenlet/controller/seed/seed/reconciler.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
Labels: area/dev-productivity, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#9163 [GEP-19] Extend health checks of `gardener-resource-manager` for new `Prometheus` and `Alertmanager` resources
  pkg/resourcemanager/client/scheme.go
  pkg/resourcemanager/controller/health/progressing/add.go
  pkg/resourcemanager/controller/health/progressing/reconciler.go
  pkg/resourcemanager/controller/health/utils/health_checker.go
  pkg/resourcemanager/controller/health/utils/health_checker_test.go
  pkg/utils/kubernetes/health/monitoring.go
  pkg/utils/kubernetes/health/monitoring_test.go
  test/integration/resourcemanager/health/health_suite_test.go
  test/integration/resourcemanager/health/health_test.go
Labels: kind/enhancement, size/XL, area/ops-productivity, area/monitoring, cla: yes, lgtm, approved

#9175 Fix VPA for seed prometheus
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/prometheus-vpa.yaml
Labels: kind/bug, area/monitoring, size/S, cla: yes, lgtm, approved

#9173 Add container resource policies for HA VPN containers to hvpa resource of kube-apiserver.
  pkg/component/kubeapiserver/deployment.go
  pkg/component/kubeapiserver/hvpa.go
Labels: kind/enhancement, area/robustness, area/networking, size/S, area/control-plane, area/auto-scaling, cla: yes, lgtm, approved

#9145 🧹 Cleanup a few `TODO`s
  cmd/gardenlet/app/app.go
  cmd/gardenlet/app/app_test.go
  docs/api-reference/core.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/component/machinecontrollermanager/bootstrap.go
  pkg/component/machinecontrollermanager/machine_controller_manager.go
  pkg/component/machinecontrollermanager/machine_controller_manager_test.go
  pkg/openapi/openapi_generated.go
  test/framework/shoot_utils.go
Labels: area/dev-productivity, size/XL, kind/cleanup, cla: yes, lgtm, approved

#9181 Update `machine-controller-manager-provider-local` to the lastet version
  pkg/provider-local/imagevector/images.yaml
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9179 [GEP-19] Fix cache Prometheus scrape config for `kube-state-metrics`
  pkg/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/component/kubestatemetrics/resources.go
Labels: kind/bug, area/dev-productivity, size/L, area/monitoring, cla: yes, lgtm, approved

#9178 Fix go toolchain for `golang-test` image
  go.mod
  hack/tools/image/Dockerfile
  hack/tools/image/variants.yaml
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9177 Fix Fallback Client scheme usage
  pkg/client/kubernetes/client.go
  pkg/extensions/customresources.go
Labels: kind/bug, size/XS, area/open-source, area/robustness, cla: yes, lgtm, approved

#9183 Handle multiple potentially overlapping wildcard ingress domains in istio.
  pkg/component/nginxingress/nginxingress.go
  pkg/component/nginxingress/nginxingress_test.go
Labels: kind/enhancement, size/M, area/robustness, area/networking, cla: yes, lgtm, approved

#9188 Fix VPA for Prometheis managed by `prometheus-operator`
  pkg/component/monitoring/prometheus/prometheus.go
  pkg/component/monitoring/prometheus/prometheus_test.go
  pkg/component/monitoring/prometheus/vpa.go
Labels: kind/bug, size/S, area/scalability, cla: yes, lgtm, approved

#9189 Seed care controller incorporates health of `prometheus-cache` and `alertmanager-seed` `ManagedResource`s
  pkg/gardenlet/controller/seed/care/health.go
  pkg/gardenlet/controller/seed/care/health_test.go
  pkg/gardenlet/controller/seed/care/reconciler.go
  pkg/gardenlet/controller/seed/care/reconciler_test.go
  pkg/gardenlet/controller/seed/care/types.go
  test/integration/gardenlet/seed/care/care_suite_test.go
  test/integration/gardenlet/seed/care/care_test.go
Labels: kind/enhancement, area/ops-productivity, size/L, cla: yes, lgtm, approved

#9180 [GEP-19] Migrate seed Prometheus deployment and configuration
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  charts/gardener/operator/templates/clusterrole.yaml
  docs/extensions/logging-and-monitoring.md
  pkg/component/kubestatemetrics/kube_state_metrics_test.go
  pkg/component/kubestatemetrics/resources.go
  pkg/component/monitoring/bootstrap.go
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/Chart.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/seed-prometheus-rules/.gitkeep
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/clusterrolebinding.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/config.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/helpers.tpl
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/prometheus-vpa.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/rules.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/service.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/serviceaccount.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/templates/statefulset.yaml
  pkg/component/monitoring/charts/bootstrap/charts/monitoring/values.yaml
  pkg/component/monitoring/prometheus/component.go
  pkg/component/monitoring/prometheus/prometheus.go
  pkg/component/monitoring/prometheus/prometheus_test.go
  pkg/component/monitoring/prometheus/seed/constants.go
  pkg/component/monitoring/prometheus/seed/podmonitors.go
  pkg/component/monitoring/prometheus/seed/podmonitors_test.go
  pkg/component/monitoring/prometheus/seed/scrapeconfigs.go
  pkg/component/monitoring/prometheus/seed/scrapeconfigs_test.go
  pkg/component/monitoring/prometheus/seed/seed_suite_test.go
  pkg/component/monitoring/prometheus/vpa.go
  pkg/component/resourcemanager/resource_manager.go
  pkg/component/resourcemanager/resource_manager_test.go
  pkg/component/vpa/recommender.go
  pkg/component/vpa/vpa.go
  pkg/component/vpa/vpa_test.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/seed/care/health.go
  pkg/gardenlet/controller/seed/care/health_test.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/gardenlet/seed/care/care_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
Labels: kind/enhancement, area/dev-productivity, area/monitoring, cla: yes, lgtm, approved, size/XXL

#9187 Prepare next Dev Cycle v1.90.0-dev
  VERSION
Labels: kind/enhancement, area/delivery, size/XS, cla: yes, lgtm, approved

#9192 Remove catch-all containername matching from prometheus VPAs
  pkg/component/monitoring/alertmanager/alertmanager_test.go
  pkg/component/monitoring/alertmanager/vpa.go
  pkg/component/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus-vpa.yaml
  pkg/component/monitoring/prometheus/prometheus_test.go
  pkg/component/monitoring/prometheus/vpa.go
Labels: kind/bug, size/S, area/auto-scaling, cla: yes, lgtm, approved

#9193 Do no longer delete `prometheus-seed` `ClusterRoleBinding`
  pkg/component/monitoring/prometheus/prometheus_test.go
  pkg/component/monitoring/prometheus/rbac.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
Labels: kind/bug, size/XS, area/usability, cla: yes, lgtm, approved

#9198 Fix seed-ingress not being updated properly
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
Labels: kind/bug, area/networking, size/S, cla: yes, lgtm, approved

#9195 Update Plutono config for targeting seed Prometheus
  pkg/component/plutono/plutono.go
  pkg/component/plutono/plutono_test.go
Labels: kind/bug, area/usability, size/S, cla: yes, lgtm, approved

#9205 Remove memory limits from Prometheis
  pkg/component/monitoring/prometheus/prometheus.go
  pkg/component/monitoring/prometheus/prometheus_test.go
Labels: kind/bug, size/XS, area/scalability, cla: yes, lgtm, approved

#9211 Extend health checks of `gardener-resource-manager` for new `VerticalPodAutoscaler` resources
  pkg/resourcemanager/client/scheme.go
  pkg/resourcemanager/controller/health/utils/health_checker.go
  pkg/resourcemanager/controller/health/utils/health_checker_test.go
  pkg/utils/kubernetes/health/vpa.go
  pkg/utils/kubernetes/health/vpa_test.go
Labels: kind/enhancement, area/ops-productivity, size/L, cla: yes, lgtm, approved

#9214 Promote `APIServerFastRollout` feature gate to GA
  docs/deployment/feature_gates.md
  pkg/component/kubeapiserver/deployment.go
  pkg/component/kubeapiserver/kube_apiserver.go
  pkg/component/kubeapiserver/kube_apiserver_test.go
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/features/features.go
  pkg/operation/botanist/kubeapiserver.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/enhancement, area/open-source, size/L, cla: yes, lgtm, approved

#9213 Nit: Update istio.io/api to a semver tag
  go.mod
  go.sum
Labels: size/XS, kind/cleanup, cla: yes, lgtm, approved

#9216 Remove unnecessary spaces in license headers added via "hack/add-license-header.sh"
  hack/add-license-header.sh
Labels: size/XS, kind/cleanup, area/compliance, cla: yes, lgtm, approved

#8909 Fix hook-me.sh script
  hack/hook-me.sh
Labels: kind/bug, area/dev-productivity, size/L, cla: yes, lgtm, approved

#9208 Promote `UseGardenerNodeAgent` feature gate to GA
  docs/deployment/feature_gates.md
  pkg/component/extensions/operatingsystemconfig/downloader/downloader_test.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config_test.go
  pkg/features/features.go
  pkg/gardenlet/controller/shoot/care/health_test.go
  pkg/operation/botanist/operatingsystemconfig_test.go
  pkg/operation/botanist/worker_test.go
Labels: kind/enhancement, size/XL, area/open-source, cla: yes, lgtm, approved

#9243 Update Conformance tests status
  README.md
Labels: kind/task, size/S, cla: yes, lgtm, approved

#9244 Set correct labels to shoot prometheus vpa
  pkg/component/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus-vpa.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#9212 `Shoot` API: Forbid adding or changing `.spec.seedSelector` when `.spec.seedName` is set
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: kind/enhancement, area/usability, size/M, cla: yes, lgtm, approved

#9191 Set vpa webhook `reinvocationPolicy: IfNeeded`
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  pkg/component/vpa/general.go
  pkg/component/vpa/vpa.go
  pkg/component/vpa/vpa_test.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#9072 [manual:component:github.com/gardener/dependency-watchdog:v1.1.2->v1.2.1]
  cmd/gardenlet/app/app.go
  go.mod
  go.sum
  imagevector/images.yaml
  pkg/component/dependencywatchdog/access.go
  pkg/component/dependencywatchdog/access_test.go
  pkg/component/dependencywatchdog/bootstrap_test.go
  pkg/component/kubecontrollermanager/kube_controller_manager.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/operation/botanist/dependency_watchdog.go
  pkg/operation/botanist/resource_manager.go
Labels: kind/enhancement, size/L, area/scalability, cla: yes, lgtm, approved

#9264 Change ETCD VPA MaxAllowed memory value to 28Gb
  pkg/component/etcd/etcd.go
  pkg/component/etcd/etcd_test.go
Labels: kind/bug, size/XS, area/control-plane, area/auto-scaling, cla: yes, lgtm, approved

#9142 [GEP-25] Namespaced Cloud Profiles
  docs/README.md
  docs/proposals/25-namespaced-cloud-profiles.md
Labels: kind/enhancement, area/ops-productivity, area/usability, size/L, ok-to-test, cla: yes, lgtm, approved

#9269 Ignore dependency updates from `k8s.io/kube-openapi` because it depends on `k8s.io/apiserver`
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9273 Remove `allow-privileged-containers` flag from test definition
  .test-defs/CreateShoot.yaml
Labels: size/XS, kind/cleanup, area/testing, cla: yes, lgtm, approved

#9271 Update image references in `example/*` directory with `renovate`
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9250 Reduce resource requests of istio ingress gateway and adapt autoscaling accordingly.
  pkg/component/istio/charts/istio/istio-ingress/templates/autoscale.yaml
  pkg/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/component/istio/test_charts/ingress_autoscaler.yaml
  pkg/component/istio/test_charts/ingress_deployment.yaml
Labels: kind/enhancement, area/cost, size/M, area/networking, area/auto-scaling, cla: yes, lgtm, approved

#9276 Fix fetching CA bundle secret in DWD migration function
  cmd/gardenlet/app/app.go
  pkg/component/dependencywatchdog/access.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#9280 [node-agent] Introduce `hostname-check` controller
  cmd/gardener-node-agent/app/app.go
  pkg/nodeagent/controller/add.go
  pkg/nodeagent/controller/healthcheck/add.go
  pkg/nodeagent/controller/hostnamecheck/add.go
  pkg/nodeagent/controller/hostnamecheck/hostnamecheck_suite_test.go
  pkg/nodeagent/controller/hostnamecheck/reconciler.go
  pkg/nodeagent/controller/hostnamecheck/reconciler_test.go
  pkg/nodeagent/hostname.go
  pkg/nodeagent/hostname_test.go
  skaffold.yaml
Labels: kind/bug, area/usability, size/L, cla: yes, lgtm, approved

#9245 Added autoscaler options to worker groups
  docs/api-reference/core.md
  docs/api-reference/extensions.md
  docs/extensions/worker.md
  docs/usage/shoot_autoscaling.md
  example/90-shoot.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_workers.yaml
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/machines.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/extensions/v1alpha1/helper/helper.go
  pkg/apis/extensions/v1alpha1/helper/helper_test.go
  pkg/apis/extensions/v1alpha1/types_worker.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_workers.yaml
  pkg/component/extensions/worker/worker.go
  pkg/component/extensions/worker/worker_test.go
  pkg/openapi/openapi_generated.go
  pkg/provider-local/controller/worker/machines.go
Labels: kind/api-change, area/auto-scaling, cla: yes, lgtm, approved, size/XXL

#9283 Use `ShootScheme` and `ShootCodec` for apiserverProxy
  pkg/component/apiserverproxy/apiserver_proxy.go
Labels: kind/bug, size/XS, cla: yes, lgtm, approved

#9284 Fix `make generate`
  hack/update-codegen.sh
Labels: kind/bug, size/XS, area/open-source, cla: yes, lgtm, approved

#9293 Nit: Fix a typo in the cluster-autoscaler docs
  docs/development/defaulting.md
  docs/usage/shoot_autoscaling.md
  docs/usage/shoot_credentials_rotation.md
Labels: size/XS, kind/cleanup, cla: yes, lgtm, approved
