Repository gardener/gardener, pull requests merged in 2024-05, with the labels that each got.

#9668 Cleanup some TODOs
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  cmd/gardenlet/app/migration.go
  pkg/component/observability/monitoring/alertmanager/alertmanager.go
  pkg/component/observability/monitoring/alertmanager/component.go
  pkg/component/shared/alertmanager.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/monitoring.go
  pkg/operator/controller/garden/garden/components.go
Labels: area/dev-productivity, size/XL, kind/cleanup, cla: yes, lgtm, approved

#9688 federate additional metrics in the Prometheus longterm instance
  pkg/component/observability/monitoring/prometheus/longterm/scrapeconfigs.go
  pkg/component/observability/monitoring/prometheus/longterm/scrapeconfigs_test.go
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#9693 Allow easy IPv6-only prow tests
  Makefile
  hack/test-e2e-local.sh
  test/e2e/gardener/common.go
  test/e2e/gardener/managedseed/create_rotate_delete.go
  test/e2e/gardener/shoot/internal/node/node.go
Labels: kind/enhancement, area/dev-productivity, area/quality, size/M, area/robustness, area/networking, area/testing, cla: yes, lgtm, approved

#9703 Don't do HVPA specific things for etcd when `VPAForETCD` is enabled
  pkg/component/etcd/etcd/etcd.go
  pkg/component/etcd/etcd/etcd_test.go
Labels: kind/bug, size/L, area/auto-scaling, cla: yes, lgtm, approved

#9713 Update CI Build link
  README.md
Labels: size/XS, kind/task, cla: yes, lgtm, approved

#9709 [provider-local] Drop MCM logging config
  charts/gardener/provider-local/templates/configmap-logging.yaml
  example/provider-local/garden/base/controller-registration.yaml
Labels: area/dev-productivity, size/M, kind/cleanup, cla: yes, lgtm, approved

#9721 Fix example github `apiURL` in documentation
  example/operator/20-garden.yaml
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#9714 Validation of DNSRecords: allow domain names starting with an underscore "_"
  pkg/apis/extensions/validation/dnsrecord.go
  pkg/apis/extensions/validation/dnsrecord_test.go
Labels: kind/enhancement, size/S, area/control-plane, cla: yes, lgtm, approved

#9718 Prevent generation of new `managedresource-shoot-core-system-*` `Secret`s on each `Shoot` reconciliation
  pkg/component/shoot/system/system.go
  pkg/component/shoot/system/system_test.go
Labels: kind/bug, area/ops-productivity, size/XS, cla: yes, lgtm, approved

#9611 Drop HVPA for the `vali` StatefulSet and use VPA instead
  pkg/component/observability/logging/vali/vali.go
  pkg/component/observability/logging/vali/vali_test.go
  pkg/component/shared/vali.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/operation/botanist/logging.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/enhancement, size/XL, area/logging, cla: yes, lgtm, approved

#9698 Drop HVPA for KCM and use VPA instead
  pkg/component/kubernetes/controllermanager/controllermanager.go
  pkg/component/kubernetes/controllermanager/controllermanager_test.go
  pkg/component/shared/kubecontrollermanager.go
  pkg/gardenlet/operation/botanist/kubecontrollermanager.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/enhancement, size/L, area/auto-scaling, cla: yes, lgtm, approved

#9722 Introduce `.spec.pools[].userDataSecretRef` to prevent inlining the entire user data
  docs/api-reference/extensions.md
  docs/extensions/worker.md
  example/seed-crds/10-crd-extensions.gardener.cloud_workers.yaml
  extensions/pkg/controller/worker/machines.go
  extensions/pkg/controller/worker/machines_test.go
  pkg/apis/extensions/v1alpha1/types_worker.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/extensions/validation/worker.go
  pkg/apis/extensions/validation/worker_test.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_workers.yaml
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/extensions/worker/worker.go
  pkg/component/extensions/worker/worker_test.go
  pkg/provider-local/controller/worker/machine_images.go
  pkg/provider-local/controller/worker/machines.go
Labels: kind/enhancement, size/L, area/scalability, cla: yes, lgtm, approved

#9723 Omit useless data from `OperatingSystemConfig` in `Secret`s reconciled by `gardener-node-agent`
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/secrets.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/secrets_test.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#9730 Add CVE categorisation labels for the node-problem-detector image
  imagevector/images.yaml
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved

#9728 Extend image pattern in kyverno policy to support `snapshots` and `public` registries.
  example/provider-extensions/kyverno-policies/gardener-image-pull-policy.yaml
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9689 Support for Kubernetes v1.30
  .golangci.yaml.in
  README.md
  docs/development/new-kubernetes-version.md
  docs/usage/supported_k8s_versions.md
  example/provider-local/garden/base/cloudprofile.yaml
  hack/compute-k8s-controllers.sh
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/component/shoot/system/system.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/resourcemanager/controller/node/criticalcomponents/helper/daemon_controller.go
  pkg/utils/kubernetes/controllers.go
  pkg/utils/validation/admissionplugins/admissionplugins.go
  pkg/utils/validation/apigroups/apigroups.go
  pkg/utils/validation/features/featuregates.go
  pkg/utils/validation/kubernetesversion/version.go
  pkg/utils/validation/kubernetesversion/version_test.go
  pkg/utils/version/version.go
  pkg/utils/version/version_test.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
Labels: kind/enhancement, size/XL, area/open-source, cla: yes, lgtm, approved

#9754 Optimise plutono and vali resource requests
  pkg/component/observability/logging/vali/vali.go
  pkg/component/observability/logging/vali/vali_test.go
  pkg/component/observability/plutono/plutono.go
  pkg/component/observability/plutono/plutono_test.go
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#9678 Introduce a new autoscaling mode (`VPAAndHPA`) for Shoot Kubernetes API servers
  docs/README.md
  docs/concepts/apiserver-admission-plugins.md
  docs/concepts/etcd.md
  docs/deployment/feature_gates.md
  docs/development/autoscaling-specifics-for-components.md
  pkg/component/apiserver/types.go
  pkg/component/gardener/apiserver/apiserver_test.go
  pkg/component/gardener/apiserver/hvpa.go
  pkg/component/gardener/apiserver/vpa.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/horizontalpodautoscaler.go
  pkg/component/kubernetes/apiserver/hvpa.go
  pkg/component/kubernetes/apiserver/verticalpodautoscaler.go
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/features/features.go
  pkg/gardenlet/features/features.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/enhancement, size/XL, area/auto-scaling, cla: yes, lgtm, approved

#9764 Fix shoot control plane federation regression
  pkg/component/observability/monitoring/prometheus/component.go
  pkg/component/observability/monitoring/prometheus/prometheus.go
  pkg/component/observability/monitoring/prometheus/prometheus_test.go
  pkg/gardenlet/operation/botanist/monitoring.go
Labels: kind/bug, size/M, area/monitoring, cla: yes, lgtm, approved

#9769 Fix shoot control plane federation regression (2)
  pkg/component/observability/monitoring/prometheus/prometheus.go
  pkg/component/observability/monitoring/prometheus/prometheus_test.go
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved

#9745 Set e2e test shoot k8s version to `v1.30.0`
  example/gardener-local/kind/cluster/values.yaml
  hack/kind-up.sh
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved

#9748 Fix flaky test for EvictionRequirementsController
  pkg/controller/vpaevictionrequirements/reconciler_test.go
Labels: size/M, area/auto-scaling, kind/flake, cla: yes, lgtm, approved

#9784 [GEP-26] Remove unused packages
  extensions/pkg/util/index/index.go
  extensions/pkg/util/index/index_test.go
  extensions/pkg/util/secret/secret.go
  extensions/pkg/util/secret/secret_test.go
Labels: size/L, kind/cleanup, cla: yes, lgtm, approved, area/ipcei

#9717 [operator] Make `controllerregistrar` reconciler generic
  pkg/operator/controller/add.go
  pkg/operator/controller/controllerregistrar/reconciler.go
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#9770 extensions lib: Drop the `EnsureKubeAPIServerService` func from the controlplane `Ensurer`
  extensions/pkg/webhook/controlplane/genericmutator/mock/mocks.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator.go
  extensions/pkg/webhook/controlplane/genericmutator/mutator_test.go
  extensions/pkg/webhook/controlplane/genericmutator/noopensurer.go
Labels: size/M, kind/cleanup, area/scalability, cla: yes, lgtm, approved

#9785 Remove resource limits for the observability components
  pkg/component/observability/monitoring/blackboxexporter/blackboxexporter.go
  pkg/component/observability/monitoring/blackboxexporter/blackboxexporter_test.go
  pkg/component/observability/monitoring/nodeexporter/nodeexporter.go
  pkg/component/observability/monitoring/nodeexporter/nodeexporter_test.go
  pkg/component/observability/monitoring/prometheusoperator/deployment.go
  pkg/component/observability/monitoring/prometheusoperator/prometheus_operator_test.go
  pkg/component/observability/plutono/plutono.go
  pkg/component/observability/plutono/plutono_test.go
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#9797 node-problem-detector: Do not consider VPAEnabled for setting memory limits
  pkg/component/nodemanagement/nodeproblemdetector/node_problem_detector.go
  pkg/component/nodemanagement/nodeproblemdetector/node_problem_detector_test.go
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#9806 [renovate] Exclude `sigs.k8s.io/controller-runtime/tools/setup-envtest`
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9802 Fix plutono dashboard `ConfigMap` update
  pkg/component/observability/plutono/plutono.go
Labels: area/monitoring, kind/regression, size/S, cla: yes, lgtm, approved

#9814 Since go-1.22 math/rand/v2 should be used
  pkg/controller/service/reconciler.go
  pkg/utils/random.go
Labels: kind/enhancement, size/XS, area/quality, ok-to-test, cla: yes, lgtm, approved

#9716 Configure Cache Prometheus to scrape kubelet and cadvisor metrics directly
  example/gardener-local/kind/cluster/templates/_kubeadm_config_patches.tpl
  hack/kind-up.sh
  pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/cadvisor.yaml
  pkg/component/observability/monitoring/prometheus/cache/assets/scrapeconfigs/kubelet.yaml
  pkg/component/observability/monitoring/prometheus/cache/networkpolicy.go
  pkg/component/observability/monitoring/prometheus/cache/networkpolicy_test.go
  pkg/component/observability/monitoring/prometheus/cache/scrapeconfigs.go
  pkg/component/observability/monitoring/prometheus/cache/scrapeconfigs_test.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/operation/seed/seed.go
  pkg/gardenlet/operation/seed/seed_test.go
  test/integration/gardenlet/seed/seed/seed_suite_test.go
Labels: kind/enhancement, size/L, area/monitoring, cla: yes, lgtm, approved

#9818 Introduce `shoot_dashboard_url` label
  pkg/component/observability/monitoring/prometheus/component.go
  pkg/component/observability/monitoring/prometheus/prometheus.go
  pkg/component/observability/monitoring/prometheus/prometheus_test.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/enhancement, size/M, area/monitoring, cla: yes, lgtm, approved

#9820 Promote feature gate `CoreDNSQueryRewriting` to beta and enable by default
  docs/deployment/feature_gates.md
  pkg/features/features.go
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#9827 Fix cluster overview dashboard
  pkg/component/observability/plutono/dashboards/shoot/owners/worker/cluster-overview-dashboard.json
  pkg/component/observability/plutono/dashboards/shoot/owners/workerless/cluster-overview-dashboard.json
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved

#9822 Update CA image for k8s `1.29`
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/control-plane, cla: yes, lgtm, approved

#9824 Promote feature gate `MutableShootSpecNetworkingNodes` to beta and enable it by default
  docs/deployment/feature_gates.md
  pkg/apis/core/validation/shoot_test.go
  pkg/features/features.go
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#9819 Secrets manager: Custom early renewal of certificates.
  docs/development/secrets_management.md
  pkg/utils/secrets/manager/generate.go
  pkg/utils/secrets/manager/generate_test.go
  pkg/utils/secrets/manager/manager.go
Labels: kind/enhancement, size/L, area/robustness, cla: yes, lgtm, approved

#9828 [renovate] Add release notes for docker and github-releases
  .github/renovate.json5
Labels: kind/enhancement, area/delivery, size/S, cla: yes, lgtm, approved

#9831 Redirect non-vpn traffic on port 8132 of istio ingress gateway to https port
  pkg/component/networking/istio/charts/istio/istio-ingress/templates/vpn-envoy-filter.yaml
  pkg/component/networking/istio/test_charts/ingress_vpn_envoy_filter.yaml
Labels: kind/enhancement, area/security, size/M, area/networking, cla: yes, lgtm, approved

#9757 Label nodes with expected OperatingSystemConfig name
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/extensions/worker/worker.go
  pkg/component/extensions/worker/worker_test.go
  pkg/gardenlet/operation/botanist/operatingsystemconfig.go
  pkg/gardenlet/operation/botanist/operatingsystemconfig_test.go
  pkg/gardenlet/operation/botanist/worker.go
  pkg/gardenlet/operation/botanist/worker_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
Labels: kind/enhancement, size/L, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#9829 [provider-local] Increase workers for `Extension` controllers
  pkg/provider-local/controller/extension/seed/add.go
  pkg/provider-local/controller/extension/shoot/add.go
  pkg/provider-local/controller/extension/shootafterworker/actuator.go
  pkg/provider-local/controller/extension/shootafterworker/add.go
Labels: area/dev-productivity, size/M, kind/test, cla: yes, lgtm, approved

#9817 PVC migration: Remove `.spec.claimRef` only after new PVC got created
  pkg/component/observability/monitoring/migration.go
Labels: kind/bug, size/M, area/monitoring, area/storage, cla: yes, lgtm, approved

#9782 Move `machine-controller-manager-provider-local` into `gardener/gardener`
  Makefile
  charts/gardener/provider-local/values.yaml
  cmd/machine-controller-manager-provider-local/main.go
  docs/README.md
  docs/extensions/machine-controller-provider-local.md
  example/provider-extensions/kyverno-policies/gardener-image-pull-policy.yaml
  example/provider-local/garden/base/.gitignore
  example/provider-local/garden/base/cloudprofile.yaml
  example/provider-local/garden/base/controller-registration.yaml
  example/provider-local/garden/base/kustomization.yaml
  go.mod
  go.sum
  hack/check-skaffold-deps-for-binary.sh
  hack/check-skaffold-deps.sh
  hack/kind-up.sh
  hack/tools.mk
  hack/tools/logcheck/pkg/logcheck/logcheck.go
  hack/tools/logcheck/pkg/logcheck/testdata/src/use-logr/helper/funcs.go
  hack/tools/logcheck/pkg/logcheck/testdata/src/use-logr/use_logr.go
  pkg/component/nodemanagement/machinecontrollermanager/provider.go
  pkg/component/nodemanagement/machinecontrollermanager/provider_test.go
  pkg/provider-local/imagevector/images.yaml
  pkg/provider-local/machine-provider/api/v1alpha1/doc.go
  pkg/provider-local/machine-provider/api/v1alpha1/provider_spec.go
  pkg/provider-local/machine-provider/api/validation/validation.go
  pkg/provider-local/machine-provider/local/create_machine.go
  pkg/provider-local/machine-provider/local/delete_machine.go
  pkg/provider-local/machine-provider/local/driver.go
  pkg/provider-local/machine-provider/local/get_machine_status.go
  pkg/provider-local/machine-provider/local/get_volume_ids.go
  pkg/provider-local/machine-provider/local/list_machines.go
  pkg/provider-local/node/Dockerfile
  pkg/provider-local/node/run-userdata.service
  pkg/provider-local/node/run-userdata.sh
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#9839 [renovate] Add `**Release note:**` heading and a `NONE` default release note
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9746 [GEP-24] Manage Gardener Discovery Server via Gardener Operator
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/operator.md
  docs/concepts/operator.md
  docs/development/priority-classes.md
  docs/usage/shoot_serviceaccounts.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  imagevector/images.go
  imagevector/images.yaml
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/component/gardener/discoveryserver/deployment.go
  pkg/component/gardener/discoveryserver/discoveryserver.go
  pkg/component/gardener/discoveryserver/discoveryserver_suite_test.go
  pkg/component/gardener/discoveryserver/discoveryserver_test.go
  pkg/component/gardener/discoveryserver/ingress.go
  pkg/component/gardener/discoveryserver/poddisruptionbudget.go
  pkg/component/gardener/discoveryserver/rbac.go
  pkg/component/gardener/discoveryserver/secrets.go
  pkg/component/gardener/discoveryserver/service.go
  pkg/component/gardener/discoveryserver/servicemonitor.go
  pkg/component/gardener/discoveryserver/vpa.go
  pkg/component/observability/monitoring/blackboxexporter/garden/config.go
  pkg/component/observability/monitoring/blackboxexporter/garden/config_test.go
  pkg/component/observability/monitoring/blackboxexporter/garden/scrapeconfig.go
  pkg/component/observability/monitoring/blackboxexporter/garden/scrapeconfig_test.go
  pkg/component/observability/monitoring/prometheus/garden/assets/prometheusrules/garden.yaml
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/garden/garden/reconciler_delete.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  skaffold-operator.yaml
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL, area/ipcei, ipcei/oidc

#9750 Rework seed alerts to consider all possible conditions
  pkg/component/observability/monitoring/prometheus/garden/assets/prometheusrules/seed.yaml
  pkg/component/observability/monitoring/prometheus/garden/prometheusrules_test.go
  pkg/component/observability/monitoring/prometheus/garden/testdata/seed.prometheusrule.test.yaml
Labels: kind/enhancement, size/L, area/monitoring, cla: yes, lgtm, approved

#9852 Include `provider-local`s image vector for Renovate updates
  .github/renovate.json5
  pkg/provider-local/imagevector/images.yaml
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#9823 Allow `ControllerDeployment` to reference chart from an OCI Repository
  .golangci.yaml.in
  charts/gardener/provider-local/Chart.yaml
  charts/gardener/provider-local/doc.go
  charts/gardener/provider-local/templates/coredns/service.yaml
  charts/gardener/provider-local/values.yaml
  docs/api-reference/core-v1.md
  docs/api-reference/core.md
  docs/extensions/controllerregistration.md
  example/25-controllerdeployment.yaml
  example/provider-local/garden/base/controller-registration.yaml
  example/provider-local/garden/base/controllerdeployment.yaml
  example/provider-local/garden/base/controllerregistration.yaml
  example/provider-local/garden/base/kustomization.yaml
  example/provider-local/garden/base/patch-controller-registrations.yaml
  example/provider-local/garden/dual/patch-controller-deployment.yaml
  go.mod
  go.sum
  hack/push-helm.sh
  pkg/apis/core/conversion_roundtrip_controllerdeployment_test.go
  pkg/apis/core/types_controllerdeployment.go
  pkg/apis/core/v1/conversion_controllerdeployment_test.go
  pkg/apis/core/v1/generated.pb.go
  pkg/apis/core/v1/generated.proto
  pkg/apis/core/v1/types_controllerdeployment.go
  pkg/apis/core/v1/zz_generated.conversion.go
  pkg/apis/core/v1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/conversions_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_controllerdeployment.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/controllerdeployment.go
  pkg/apis/core/validation/controllerdeployment_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/add.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/utils/oci/cache.go
  pkg/utils/oci/cache_test.go
  pkg/utils/oci/fake/fake_registry.go
  pkg/utils/oci/helmregistry.go
  pkg/utils/oci/helmregistry_test.go
  pkg/utils/oci/oci_suite_test.go
  pkg/utils/oci/testdata/README.md
  pkg/utils/oci/testdata/example-0.1.0.tgz
  pkg/utils/test/port/port.go
  skaffold.yaml
  test/envtest/apiserver.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: kind/enhancement, area/control-plane, ok-to-test, cla: yes, lgtm, approved, size/XXL

#9752 [provider-local] Harmonize local VPN setup with real-world scenario
  charts/gardener/provider-local/templates/rbac.yaml
  cmd/gardener-extension-provider-local/app/options.go
  cmd/gardenlet/app/bootstrappers/seed_config.go
  docs/operations/network_policies.md
  example/provider-local/managedseeds/shoot-managedseed.yaml
  example/provider-local/shoot-ipv6.yaml
  example/provider-local/shoot.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/seedserver/seedserver_test.go
  pkg/controller/networkpolicy/reconciler.go
  pkg/provider-local/controller/infrastructure/actuator.go
  pkg/provider-local/controller/worker/machines.go
  pkg/provider-local/machine-provider/local/create_machine.go
  pkg/provider-local/machine-provider/local/driver.go
  pkg/provider-local/webhook/controlplane/ensurer.go
  pkg/provider-local/webhook/machinecontrollermanager/add.go
  pkg/provider-local/webhook/machinecontrollermanager/mutator.go
  skaffold.yaml
  test/e2e/gardener/common.go
  test/e2e/gardener/upgrade/upgrade.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#9800 Fix `Secret etcd-backup not found`
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
Labels: kind/bug, size/XS, area/quality, cla: yes, lgtm, approved

#9780 [GEP-26] Add `WorkloadIdentity` API
  docs/api-reference/security.md
  docs/proposals/26-workload-identity.md
  example/70-workloadidentity-provider.yaml
  pkg/apis/security/register.go
  pkg/apis/security/types_workloadidentity.go
  pkg/apis/security/v1alpha1/conversions.go
  pkg/apis/security/v1alpha1/conversions_test.go
  pkg/apis/security/v1alpha1/generated.pb.go
  pkg/apis/security/v1alpha1/generated.proto
  pkg/apis/security/v1alpha1/register.go
  pkg/apis/security/v1alpha1/types_workloadidentity.go
  pkg/apis/security/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/security/v1alpha1/zz_generated.conversion.go
  pkg/apis/security/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/security/validation/workloadidentity.go
  pkg/apis/security/validation/workloadidentity_test.go
  pkg/apis/security/zz_generated.deepcopy.go
  pkg/apiserver/openapi/api_violations.report
  pkg/apiserver/openapi/openapi_generated.go
  pkg/apiserver/registry/security/rest/storage_security.go
  pkg/apiserver/registry/security/workloadidentity/storage/storage.go
  pkg/apiserver/registry/security/workloadidentity/storage/tableconvertor.go
  pkg/apiserver/registry/security/workloadidentity/strategy.go
  pkg/apiserver/registry/security/workloadidentity/strategy_test.go
  pkg/apiserver/registry/security/workloadidentity/workloadidentity_suite_test.go
  pkg/client/security/clientset/versioned/typed/security/v1alpha1/fake/fake_security_client.go
  pkg/client/security/clientset/versioned/typed/security/v1alpha1/fake/fake_workloadidentity.go
  pkg/client/security/clientset/versioned/typed/security/v1alpha1/generated_expansion.go
  pkg/client/security/clientset/versioned/typed/security/v1alpha1/security_client.go
  pkg/client/security/clientset/versioned/typed/security/v1alpha1/workloadidentity.go
  pkg/client/security/informers/externalversions/generic.go
  pkg/client/security/informers/externalversions/security/v1alpha1/interface.go
  pkg/client/security/informers/externalversions/security/v1alpha1/workloadidentity.go
  pkg/client/security/listers/security/v1alpha1/expansion_generated.go
  pkg/client/security/listers/security/v1alpha1/workloadidentity.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL, area/ipcei, ipcei/workload-identity

#9869 VPN sidecar containers: Disable autoscaling and reduce resource requests
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/kubernetes/apiserver/hvpa.go
  pkg/component/shared/kubeapiserver.go
Labels: kind/bug, size/M, area/networking, area/auto-scaling, cla: yes, lgtm, approved

#9870 The shoot control plane Prometheus forwards its alerts to the seed alertmanager
  pkg/component/observability/monitoring/prometheus/component.go
  pkg/component/observability/monitoring/prometheus/prometheus.go
  pkg/component/observability/monitoring/prometheus/prometheus_test.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/operation/botanist/monitoring.go
  pkg/operator/controller/garden/garden/components.go
Labels: size/L, area/monitoring, kind/regression, cla: yes, lgtm, approved

#9881 Increase VPA admission-controller QPS values
  pkg/component/autoscaling/vpa/admissioncontroller.go
  pkg/component/autoscaling/vpa/vpa_test.go
Labels: kind/bug, size/XS, area/auto-scaling, cla: yes, lgtm, approved

#9872 Register `Node` tains with Kubelet
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/original/components/components.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
Labels: kind/enhancement, size/M, area/robustness, cla: yes, lgtm, approved

#9884 [release-v1.95] Automated cherry pick of #9870: The shoot control plane Prometheus forwards its alerts to the seed alertmanager
  pkg/component/observability/monitoring/prometheus/component.go
  pkg/component/observability/monitoring/prometheus/prometheus.go
  pkg/component/observability/monitoring/prometheus/prometheus_test.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/operation/botanist/monitoring.go
  pkg/operator/controller/garden/garden/components.go
Labels: size/L, area/monitoring, kind/regression, cla: yes, lgtm, approved
