Repository gardener/gardener, pull requests merged in 2024-01, with the labels that each got.

#8994 Upgrade prometheus version
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#8986 Added ignore-daemonsets-utilization flag and verbosity to CA
  docs/api-reference/core.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/component/clusterautoscaler/cluster_autoscaler.go
  pkg/component/clusterautoscaler/cluster_autoscaler_test.go
  pkg/openapi/openapi_generated.go
Labels: kind/enhancement, area/auto-scaling, cla: yes, lgtm, approved, size/XXL

#8996 Added default values for CA flags
  docs/api-reference/core.md
  example/90-shoot.yaml
  pkg/apis/core/v1beta1/defaults_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot_test.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/component/clusterautoscaler/cluster_autoscaler.go
  pkg/component/clusterautoscaler/cluster_autoscaler_test.go
  pkg/openapi/openapi_generated.go
Labels: area/documentation, area/open-source, size/M, kind/technical-debt, cla: yes, lgtm, approved

#8997 Bump `nginx-ingress-controller` image to `v1.9.5`
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/open-source, area/control-plane, cla: yes, lgtm, approved

#8968 switch GCR -> Artifact-Registry
  Makefile
  charts/gardener/controlplane/values.yaml
  charts/gardener/gardenlet/values.yaml
  charts/gardener/operator/values.yaml
  charts/gardener/provider-local/values.yaml
  charts/gardener/resource-manager/values.yaml
  docs/development/component-checklist.md
  docs/development/testmachinery_tests.md
  docs/proposals/13-automated-seed-management.md
  docs/proposals/21-ipv6-singlestack-local.md
  example/55-managedseed-gardenlet.yaml
  example/provider-local/garden/base/controller-registration.yaml
  hack/.ci/component_descriptor
  imagevector/images.yaml
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/logging/eventlogger/event_logger_test.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/gardenlet/controller/managedseed/valueshelper_test.go
  pkg/operation/botanist/operatingsystemconfig_test.go
  pkg/provider-local/imagevector/images.yaml
  skaffold-operator.yaml
  skaffold.yaml
Labels: area/delivery, size/L, kind/technical-debt, cla: yes, lgtm, approved, ¯\_(ツ)_/¯

#8998 Only set external traffic policy to local in local setup for multi-zone kind clusters.
  pkg/controller/service/reconciler.go
  pkg/operator/controller/add.go
  pkg/provider-local/controller/service/add.go
  pkg/provider-local/controller/service/add_test.go
  pkg/provider-local/controller/service/service_suite_test.go
Labels: area/dev-productivity, size/L, kind/regression, area/networking, kind/flake, cla: yes, lgtm, approved

#8934 tests: Drop no longer used repositories.yaml file
  docs/development/testmachinery_tests.md
  test/framework/resources/repository/repositories.yaml
Labels: kind/cleanup, size/S, cla: yes, lgtm, approved

#9004 Log node before printing containerd mirror logs in local setup
  hack/kind-up.sh
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9003 [Flaky Test] Run difference after eventually assert
  pkg/utils/flow/taskfn_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#9008 fix: avoid erroneously detecting images as components
  hack/.ci/component_descriptor
Labels: area/delivery, size/XS, kind/regression, cla: yes, lgtm, approved

#9010 Bump observability components, plutono to 7.5.28, vali and valitail to v2.2.13
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/monitoring, area/logging, cla: yes, lgtm, approved

#8912 Clear GRM secret finalizer from hibernated or broken clusters
  cmd/gardenlet/app/app.go
  pkg/resourcemanager/controller/secret/reconciler.go
Labels: area/quality, size/M, kind/cleanup, cla: yes, lgtm, approved

#9013 Swap release responsible shifts
  docs/development/process.md
Labels: size/XS, kind/task, cla: yes, lgtm, approved

#9017 Update the registry image to the AR one
  example/gardener-local/registry/base/registry.yaml
  example/provider-extensions/registry-seed/registry/registry.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#9018 Change image pattern in kyverno policy.
  example/provider-extensions/kyverno-policies/gardener-image-pull-policy.yaml
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9022 Check for the rest of the MR secrets even though one is not found
  cmd/gardenlet/app/app.go
Labels: kind/bug, size/XS, cla: yes, lgtm, approved

#9019 Upgrade to golang 1.20.13-bookworm and 1.21.6-bookworm
  hack/tools/image/variants.yaml
Labels: kind/enhancement, size/XS, area/testing, ok-to-test, cla: yes, lgtm, approved

#9001 [Operator] Clean up technical debt in defaulting code
  pkg/operator/apis/config/v1alpha1/defaults.go
  pkg/operator/apis/config/v1alpha1/defaults_test.go
  pkg/operator/apis/config/v1alpha1/register.go
Labels: area/dev-productivity, size/L, kind/technical-debt, cla: yes, lgtm, approved

#9014 Fix broken links - 2024.01
  docs/README.md
  docs/extensions/logging-and-monitoring.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#9028 update the etcd-druid dependency version in go.mod
  go.mod
  go.sum
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8916 [admissioncontroller] Clean up technical debt in defaulting code
  pkg/admissioncontroller/apis/config/v1alpha1/defaults.go
  pkg/admissioncontroller/apis/config/v1alpha1/defaults_test.go
  pkg/admissioncontroller/apis/config/v1alpha1/register.go
  pkg/admissioncontroller/apis/config/v1alpha1/zz_generated.defaults.go
Labels: area/dev-productivity, size/L, kind/technical-debt, cla: yes, lgtm, approved

#9000 Run kube-proxy in non-privileged mode for Kubernetes >= 1.29
  pkg/component/kubeproxy/kube_proxy_test.go
  pkg/component/kubeproxy/resources.go
Labels: kind/enhancement, area/security, size/L, cla: yes, lgtm, approved

#9031 Bump up container images: fluent-bit to v2.2.0 and fluent-operator to v2.7.0
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#9034 [release-v1.86] [ci:component:github.com/gardener/etcd-druid:v0.21.0->v0.21.1]
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#8886 Enhance `gardener-resource-manager`'s class filter and the corresponding unit tests
  docs/concepts/resource-manager.md
  pkg/resourcemanager/controller/health/health/reconciler.go
  pkg/resourcemanager/controller/health/progressing/reconciler.go
  pkg/resourcemanager/controller/managedresource/reconciler.go
  pkg/resourcemanager/predicate/class_filter.go
  pkg/resourcemanager/predicate/class_filter_test.go
Labels: kind/enhancement, area/quality, size/L, cla: yes, lgtm, approved

#8970 Spread Istio Ingress Gateway pods across hosts via topology spread constraints
  docs/concepts/resource-manager.md
  pkg/apis/resources/v1alpha1/types.go
  pkg/component/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/component/istio/charts/istio/istio-ingress/values.yaml
  pkg/component/istio/ingress_gateway.go
  pkg/component/resourcemanager/resource_manager.go
  pkg/component/shared/istio.go
  pkg/component/shared/istio_test.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operator/controller/garden/garden/components.go
  pkg/resourcemanager/webhook/highavailabilityconfig/handler.go
  pkg/utils/kubernetes/highavailability.go
  pkg/utils/kubernetes/highavailability_test.go
Labels: kind/enhancement, size/L, area/robustness, area/networking, area/high-availability, cla: yes, lgtm, approved

#9036 Add `patch` cluster role permission to `dependency-watchdog-prober`
  pkg/component/dependencywatchdog/bootstrap.go
  pkg/component/dependencywatchdog/bootstrap_test.go
Labels: kind/enhancement, size/XS, area/control-plane, cla: yes, lgtm, approved

#9044 Delay removal of cleanup code in the extension library from 1.86 to 1.89
  extensions/pkg/webhook/shoot/webhook.go
Labels: size/XS, kind/cleanup, cla: yes, lgtm, approved

#8877 Upgrade helm
  extensions/pkg/terraformer/chart_test.go
  go.mod
  go.sum
  pkg/chartrenderer/default.go
  pkg/chartrenderer/default_test.go
  pkg/chartrenderer/renderer.go
  pkg/chartrenderer/sorter.go
  pkg/chartrenderer/testdata/alpine/templates/alpine-pod.yaml
  pkg/client/kubernetes/chartapplier_test.go
  pkg/client/kubernetes/testdata/render-test-v1/Chart.yaml
  pkg/client/kubernetes/testdata/render-test-v1/templates/configmap.yaml
  pkg/client/kubernetes/testdata/render-test-v1/values.yaml
  pkg/client/kubernetes/testdata/render-test-v2/Chart.yaml
  pkg/client/kubernetes/testdata/render-test-v2/templates/configmap.yaml
  pkg/client/kubernetes/testdata/render-test-v2/values.yaml
  pkg/component/istio/istio_test.go
  pkg/component/istio/test_charts/ingress_autoscaler.yaml
  pkg/component/istio/test_charts/ingress_deployment.yaml
  pkg/component/istio/test_charts/ingress_envoyfilter.yaml
  pkg/component/istio/test_charts/ingress_poddisruptionbudget.yaml
  pkg/component/istio/test_charts/ingress_poddisruptionbudget_less126.yaml
  pkg/component/istio/test_charts/ingress_role.yaml
  pkg/component/istio/test_charts/ingress_rolebinding.yaml
  pkg/component/istio/test_charts/ingress_service.yaml
  pkg/component/istio/test_charts/ingress_serviceaccount.yaml
  pkg/component/istio/test_charts/ingress_vpn_envoy_filter.yaml
  pkg/component/istio/test_charts/ingress_vpn_gateway.yaml
  pkg/component/istio/test_charts/istio_clusterrole.yaml
  pkg/component/istio/test_charts/istio_clusterrolebinding.yaml
  pkg/component/istio/test_charts/istiod_autoscale.yaml
  pkg/component/istio/test_charts/istiod_configmap.yaml
  pkg/component/istio/test_charts/istiod_deployment.yaml
  pkg/component/istio/test_charts/istiod_destinationrule.yaml
  pkg/component/istio/test_charts/istiod_poddisruptionbudget.yaml
  pkg/component/istio/test_charts/istiod_poddisruptionbudget_less126.yaml
  pkg/component/istio/test_charts/istiod_role.yaml
  pkg/component/istio/test_charts/istiod_rolebinding.yaml
  pkg/component/istio/test_charts/istiod_service.yaml
  pkg/component/istio/test_charts/istiod_serviceaccount.yaml
  pkg/component/istio/test_charts/istiod_validationwebhook.yaml
  pkg/component/istio/test_charts/proxyprotocol_envoyfilter.yaml
  pkg/component/istio/test_charts/proxyprotocol_gateway.yaml
  pkg/component/istio/test_charts/proxyprotocol_virtualservice.yaml
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/resourcemanager/controller/managedresource/sort.go
Labels: kind/enhancement, size/XL, area/open-source, cla: yes, lgtm, approved

#9046 Retry `shoots/binding` update during migration test
  test/framework/gardener_utils.go
Labels: kind/bug, size/M, area/testing, cla: yes, lgtm, approved

#9051 pkg/utils/flow: refactor Parallel() to use ParallelN()
  pkg/utils/flow/taskfn.go
Labels: area/quality, kind/cleanup, size/S, ok-to-test, cla: yes, lgtm, approved

#9053 Fix naming for multiple resources present in one file
  pkg/chartrenderer/default.go
  pkg/chartrenderer/default_test.go
  pkg/chartrenderer/testdata/alpine/templates/alpine-resources.yaml
Labels: kind/enhancement, area/open-source, size/M, cla: yes, lgtm, approved

#9054 Deflake `Renew gardenlet kubeconfig` e2e test
  test/e2e/gardener/managedseed/create_rotate_delete.go
  test/e2e/gardener/seed/renew_garden_access_secrets.go
  test/e2e/gardener/seed/renew_gardenlet_kubeconfig.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#9057 update docs
  docs/extensions/network.md
  docs/proposals/03-networking-extensibility.md
Labels: kind/bug, size/XS, area/networking, cla: yes, lgtm, approved

#9032 Add zero line per default for tcp traffic per istio namespace in the ingress dashboard.
  pkg/component/plutono/dashboards/seed/istio/istio-ingress-gateway-dashboard.json
Labels: area/ops-productivity, size/XS, area/monitoring, kind/cleanup, area/networking, cla: yes, lgtm, approved

#9061 Replace deprecated `.Capabilities.KubeVersion.GitVersion` with `.Capabilities.KubeVersion.Version` in helm charts
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/poddisruptionbudget.yaml
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/service.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/poddisruptionbudget.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/service.yaml
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/poddisruptionbudget.yaml
  charts/gardener/controlplane/charts/runtime/templates/scheduler/poddisruptionbudget.yaml
  charts/gardener/gardenlet/templates/poddisruptionbudget.yaml
  charts/gardener/operator/templates/poddisruptionbudget.yaml
  charts/gardener/provider-local/templates/poddisruptionbudget.yaml
  example/provider-local/garden/base/controller-registration.yaml
  hack/tools.mk
  pkg/component/istio/charts/istio/istio-ingress/templates/poddisruptionbudget.yaml
  pkg/component/istio/charts/istio/istio-istiod/templates/poddisruptionbudget.yaml
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved

#9060 Improved error reporting using `ERR_CLEANUP_CLUSTER_RESOURCES` when hibernating a cluster
  pkg/operation/botanist/waiter.go
  pkg/operation/botanist/waiter_test.go
Labels: kind/enhancement, area/ops-productivity, size/L, ok-to-test, cla: yes, lgtm, approved

#8999 Remove migration code for Plutono and Vali
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  example/gardener-local/gardenlet/values-ipv6.yaml
  pkg/component/logging/vali/vali.go
  pkg/component/logging/vali/vali_test.go
  pkg/component/plutono/testdata/configmap.yaml
  pkg/component/shared/vali.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operation/botanist/logging.go
  pkg/operation/botanist/logging_test.go
  pkg/operation/botanist/plutono.go
  pkg/operation/common/utils.go
  skaffold.yaml
  test/testmachinery/shoots/logging/utils.go
Labels: size/XL, area/monitoring, kind/cleanup, cla: yes, lgtm, approved

#8748 use artifact registry for IPv6 support
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#9062 Prepare next Dev Cycle v1.88.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#9048 Enable `gardener-node-agent` in `provider-extensions` setup
  docs/deployment/getting_started_locally_with_extensions.md
  example/gardener-local/gardenlet/values-provider-extensions.yaml
  example/provider-extensions/kyverno-policies/add-registry-to-osc.yaml
  example/provider-extensions/kyverno-policies/kustomization.yaml
  example/provider-extensions/registry-seed/deploy-registry.sh
  pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit_test.go
  pkg/component/extensions/operatingsystemconfig/nodeinit/templates/scripts/init.tpl.sh
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#9064 Fix nil pointer panic
  pkg/chartrenderer/default.go
  pkg/chartrenderer/default_test.go
  pkg/chartrenderer/testdata/alpine/templates/alpine-resources.yaml
Labels: kind/enhancement, area/open-source, size/M, cla: yes, lgtm, approved

#9058 Remove the GA-ed `ContainerdRegistryHostsDir` feature gate
  docs/deployment/feature_gates.md
  pkg/features/features.go
  pkg/gardenlet/features/features.go
Labels: size/M, kind/cleanup, cla: yes, lgtm, approved

#9063 Don't add error code for dashboard namespace pods
  pkg/operation/botanist/waiter.go
  pkg/operation/botanist/waiter_test.go
Labels: kind/enhancement, area/ops-productivity, size/S, cla: yes, lgtm, approved

#9080 `gardener-operator`: Allow project admins and viewers to create read-only kubeconfigs
  pkg/component/gardensystem/virtual/virtual.go
  pkg/component/gardensystem/virtual/virtual_test.go
Labels: kind/bug, size/S, area/user-management, cla: yes, lgtm, approved

#9081 Prevent excessive network traffic by avoiding unnecessary shoot updates in the `status.constraints[]` fields
  pkg/gardenlet/controller/shoot/care/constraints.go
  pkg/gardenlet/controller/shoot/care/constraints_test.go
Labels: area/cost, kind/regression, size/S, area/scalability, cla: yes, lgtm, approved

#9067 [GEP-19] Introduce `prometheus-operator` in garden and seed clusters
  docs/concepts/operator.md
  docs/development/priority-classes.md
  example/seed-crds/10-crd-monitoring.coreos.com_alertmanagerconfigs.yaml
  example/seed-crds/10-crd-monitoring.coreos.com_alertmanagers.yaml
  example/seed-crds/10-crd-monitoring.coreos.com_podmonitors.yaml
  example/seed-crds/10-crd-monitoring.coreos.com_probes.yaml
  example/seed-crds/10-crd-monitoring.coreos.com_prometheusagents.yaml
  example/seed-crds/10-crd-monitoring.coreos.com_prometheuses.yaml
  example/seed-crds/10-crd-monitoring.coreos.com_prometheusrules.yaml
  example/seed-crds/10-crd-monitoring.coreos.com_scrapeconfigs.yaml
  example/seed-crds/10-crd-monitoring.coreos.com_servicemonitors.yaml
  example/seed-crds/10-crd-monitoring.coreos.com_thanosrulers.yaml
  example/seed-crds/doc.go
  go.mod
  go.sum
  hack/generate-crds.sh
  imagevector/images.go
  imagevector/images.yaml
  pkg/client/kubernetes/types.go
  pkg/component/monitoring/prometheusoperator/crd.go
  pkg/component/monitoring/prometheusoperator/crd_test.go
  pkg/component/monitoring/prometheusoperator/deployment.go
  pkg/component/monitoring/prometheusoperator/prometheus_operator.go
  pkg/component/monitoring/prometheusoperator/prometheus_operator_suite_test.go
  pkg/component/monitoring/prometheusoperator/prometheus_operator_test.go
  pkg/component/monitoring/prometheusoperator/rbac.go
  pkg/component/monitoring/prometheusoperator/service.go
  pkg/component/monitoring/prometheusoperator/serviceaccount.go
  pkg/component/monitoring/prometheusoperator/templates/crd-monitoring.coreos.com_alertmanagerconfigs.yaml
  pkg/component/monitoring/prometheusoperator/templates/crd-monitoring.coreos.com_alertmanagers.yaml
  pkg/component/monitoring/prometheusoperator/templates/crd-monitoring.coreos.com_podmonitors.yaml
  pkg/component/monitoring/prometheusoperator/templates/crd-monitoring.coreos.com_probes.yaml
  pkg/component/monitoring/prometheusoperator/templates/crd-monitoring.coreos.com_prometheusagents.yaml
  pkg/component/monitoring/prometheusoperator/templates/crd-monitoring.coreos.com_prometheuses.yaml
  pkg/component/monitoring/prometheusoperator/templates/crd-monitoring.coreos.com_prometheusrules.yaml
  pkg/component/monitoring/prometheusoperator/templates/crd-monitoring.coreos.com_scrapeconfigs.yaml
  pkg/component/monitoring/prometheusoperator/templates/crd-monitoring.coreos.com_servicemonitors.yaml
  pkg/component/monitoring/prometheusoperator/templates/crd-monitoring.coreos.com_thanosrulers.yaml
  pkg/component/monitoring/prometheusoperator/templates/doc.go
  pkg/component/monitoring/prometheusoperator/vpa.go
  pkg/component/shared/prometheus_operator.go
  pkg/gardenlet/controller/seed/care/health.go
  pkg/gardenlet/controller/seed/care/health_test.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operator/client/scheme.go
  pkg/operator/controller/garden/care/health.go
  pkg/operator/controller/garden/care/health_test.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/garden/garden/reconciler_delete.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  skaffold-operator.yaml
  skaffold.yaml
  test/e2e/operator/garden/create_delete.go
  test/integration/gardenlet/seed/care/care_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/care/care_test.go
  test/integration/operator/garden/garden/garden_test.go
Labels: kind/enhancement, area/dev-productivity, area/monitoring, cla: yes, lgtm, approved, size/XXL

#9073 Adapt `gardenlet` health checks to consider `gardener-node-agent`'s `Lease` object for the `EveryNodeReady` condition
  cmd/gardener-node-agent/app/app.go
  pkg/gardenlet/controller/shoot/care/health.go
  pkg/gardenlet/controller/shoot/care/health_test.go
  pkg/nodeagent/controller/lease/reconciler.go
  pkg/nodeagent/controller/lease/reconciler_test.go
  pkg/utils/gardener/machines.go
Labels: kind/enhancement, size/L, area/robustness, ok-to-test, cla: yes, lgtm, approved

#9076 Fix code smell and missing tests in `waiter.go`
  pkg/operation/botanist/waiter.go
  pkg/operation/botanist/waiter_test.go
Labels: area/quality, size/L, kind/technical-debt, area/testing, ok-to-test, cla: yes, lgtm, approved

#9085 Rename the Selector field of `extensionswebhook.Webhook` to NamespaceSelector
  extensions/pkg/webhook/cloudprovider/cloudprovider.go
  extensions/pkg/webhook/controlplane/controlplane.go
  extensions/pkg/webhook/network/network.go
  extensions/pkg/webhook/registration.go
  extensions/pkg/webhook/registration_test.go
  extensions/pkg/webhook/shoot/shoot.go
  extensions/pkg/webhook/webhook.go
  extensions/pkg/webhook/webhook_test.go
  pkg/provider-local/webhook/networkpolicy/add.go
  pkg/provider-local/webhook/nodeagentosc/add.go
Labels: size/L, kind/cleanup, cla: yes, lgtm, approved

#9037 Enhance shoot validation error message
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
Labels: kind/bug, area/usability, size/S, cla: yes, lgtm, approved

#9023 Fix remote-local setup
  docs/deployment/content/remote-local-setup.yaml
Labels: kind/bug, area/dev-productivity, size/XS, area/quality, ok-to-test, cla: yes, lgtm, approved

#9033 [SeedManagement] Clean up technical debt in defaulting code
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseed.go
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseed_test.go
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseedset_test.go
  pkg/apis/seedmanagement/v1alpha1/register.go
Labels: area/dev-productivity, size/L, kind/technical-debt, cla: yes, lgtm, approved

#9089 [gardenlet] Leverage server-side filtering for watches for `Shoot`s
  cmd/gardenlet/app/app.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/shoot/care/add.go
  pkg/gardenlet/controller/shoot/shoot/add.go
  pkg/gardenlet/controller/shoot/state/add.go
  pkg/gardenlet/controller/shoot/state/add_test.go
  pkg/registry/core/backupentry/strategy.go
  pkg/registry/core/backupentry/strategy_test.go
  pkg/registry/core/shoot/strategy.go
  pkg/registry/core/shoot/strategy_test.go
  pkg/utils/gardener/identity.go
  pkg/utils/gardener/identity_test.go
Labels: kind/enhancement, area/dev-productivity, area/cost, size/L, area/scalability, cla: yes, lgtm, approved

#9096 [node-agent] Disable and stop `gardener-node-init.service` when gardener-node-agent is active
  pkg/nodeagent/controller/operatingsystemconfig/reconciler.go
Labels: kind/enhancement, area/robustness, size/S, cla: yes, lgtm, approved
