Repository gardener/gardener, pull requests merged in 2024-03, with the labels that each got.

#9294 Enhance error msg when trying to change `.spec.seedName` by patching a shoot
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, area/usability, size/S, cla: yes, lgtm, approved

#9289 Add IP Stack to `DNSRecord` resources
  pkg/component/extensions/dnsrecord/dnsrecord.go
  pkg/component/extensions/dnsrecord/dnsrecord_test.go
  pkg/gardenlet/controller/seed/seed/nginxingress.go
  pkg/gardenlet/operation/botanist/dnsrecord.go
  pkg/gardenlet/operation/botanist/dnsrecord_test.go
  pkg/gardenlet/operation/botanist/nginxingress.go
  pkg/gardenlet/operation/botanist/nginxingress_test.go
  pkg/utils/gardener/dns.go
  pkg/utils/gardener/seed.go
  pkg/utils/gardener/seed_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
Labels: kind/enhancement, size/L, area/networking, cla: yes, lgtm, approved

#9209 Fix leak of `extension-controlplane-shoot-webhooks` ManagedResource
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/webhook/shoot/webhook.go
  extensions/pkg/webhook/shoot/webhook_test.go
  pkg/utils/managedresources/builder/managedresources.go
  pkg/utils/managedresources/builder/resourcemanager_test.go
  pkg/utils/managedresources/builder/secrets.go
  pkg/utils/managedresources/managedresources.go
  pkg/utils/managedresources/managedresources_test.go
  test/integration/extensions/webhook/certificates/certificates_test.go
Labels: kind/bug, area/ops-productivity, area/usability, size/L, cla: yes, lgtm, approved

#9298 [GEP-19] Set `replicas=1` for seed alertmanager
  pkg/gardenlet/controller/seed/seed/components.go
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved

#9279 Add cpu target percentile parameter to VPA options in Shoot spec
  docs/api-reference/core.md
  docs/usage/shoot_autoscaling.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/component/autoscaling/vpa/recommender.go
  pkg/component/autoscaling/vpa/vpa_test.go
  pkg/gardenlet/operation/botanist/vpa.go
Labels: kind/enhancement, area/auto-scaling, cla: yes, lgtm, approved, size/XXL

#9299 [GEP-19] Delete `networkingv1.Ingress` instead of `networkingv1beta1.Ingress`
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved

#9303 Remove redundant doc for autoscaling configuration
  docs/usage/shoot_autoscaling.md
Labels: kind/enhancement, area/documentation, size/S, area/auto-scaling, cla: yes, lgtm, approved

#9310 Upgrade mcm to `0.52.0`
  example/seed-crds/10-crd-machine.sapcloud.io_machineclasses.yaml
  example/seed-crds/10-crd-machine.sapcloud.io_machines.yaml
  go.mod
  go.sum
  pkg/component/nodemanagement/machinecontrollermanager/templates/crd-machine.sapcloud.io_machineclasses.yaml
  pkg/component/nodemanagement/machinecontrollermanager/templates/crd-machine.sapcloud.io_machines.yaml
Labels: kind/enhancement, size/S, area/control-plane, cla: yes, lgtm, approved

#9302 Prepare next Dev Cycle v1.91.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#9196 [GEP-24] Configure KAPI managed issuer & JWKS URL
  cmd/gardener-apiserver/app/gardener_apiserver.go
  docs/api-reference/core.md
  docs/operations/configuration.md
  example/10-secret-shoot-service-account-issuer.yaml
  pkg/apis/core/helper/helpers.go
  pkg/apis/core/helper/helpers_test.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/apiserver/registry/core/shoot/storage/kubeconfig.go
  pkg/apiserver/registry/core/shoot/storage/kubeconfig_test.go
  pkg/component/kubernetes/apiserver/apiserver.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  pkg/gardenlet/operation/botanist/advertisedaddresses.go
  pkg/gardenlet/operation/botanist/advertisedaddresses_test.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
  pkg/gardenlet/operation/operation.go
  pkg/gardenlet/operation/operation_test.go
  pkg/gardenlet/operation/shoot/shoot.go
  pkg/gardenlet/operation/shoot/types.go
  pkg/gardenlet/operation/types.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  pkg/utils/gardener/garden.go
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL

#9311 NodeNotHealthy prometheus alert
  pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go
  pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules_test.go
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved

#9312 Bump alpine to 3.19.1
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, area/compliance, cla: yes, lgtm, approved

#9266 Consider errors from configValidator for ErrorCodes
  extensions/pkg/controller/infrastructure/controller.go
  extensions/pkg/controller/infrastructure/reconciler.go
Labels: kind/enhancement, area/ops-productivity, size/S, cla: yes, lgtm, approved

#9274 Drop deprecated `allowPrivilegedContainers` field from the Shoot API
  docs/api-reference/core.md
  docs/usage/openidconnect-presets.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/types_shoot_test.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/cleanup, cla: yes, lgtm, approved, size/XXL

#9297 Fix hanging of shoot force-deletion in case DNS records fails with invalid credentials
  pkg/gardenlet/controller/shoot/shoot/cleaner.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_force_delete.go
  test/e2e/gardener/shoot/create_and_force_delete.go
  test/framework/gardener_utils.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#9319 Save a few allocations
  pkg/component/shoot/system/system.go
Labels: kind/enhancement, area/quality, size/S, cla: yes, lgtm, approved

#9323 Sort skaffold dependencies
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#9309 Reconcile extension `Backupbucket` and `Backupentry` if lastOperation is nil
  pkg/gardenlet/controller/backupbucket/reconciler.go
  pkg/gardenlet/controller/backupentry/reconciler.go
Labels: kind/bug, size/XS, area/backup, cla: yes, lgtm, approved

#9325 Promote `ShootForceDeletion` feature gate to beta
  docs/deployment/feature_gates.md
  pkg/features/features.go
Labels: kind/enhancement, size/XS, area/open-source, cla: yes, lgtm, approved

#9327 Downgrade skaffold to v2.9.0
  hack/tools.mk
Labels: area/dev-productivity, size/XS, kind/regression, cla: yes, lgtm, approved

#9304 Add support for migration of istio ingress namespaces.
  pkg/gardenlet/controller/seed/seed/components.go
Labels: kind/enhancement, area/ops-productivity, size/M, area/networking, area/high-availability, cla: yes, lgtm, approved

#8945 update coredns to v1.11.1
  charts/gardener/provider-local/templates/coredns/deployment.yaml
  example/provider-local/garden/base/controller-registration.yaml
  imagevector/images.yaml
  pkg/component/networking/coredns/coredns.go
  pkg/component/networking/coredns/coredns_test.go
Labels: kind/enhancement, area/networking, size/S, cla: yes, lgtm, approved

#9335 [GEP-19] [shoot-care] Check for `alertmanager-shoot` when Gardener `>= 1.90`
  pkg/gardenlet/controller/shoot/care/health.go
  pkg/gardenlet/controller/shoot/care/health_test.go
Labels: kind/bug, area/ops-productivity, size/M, cla: yes, lgtm, approved

#9301 [GEP-19] Integrate Alertmanager deployment into `Garden` controller
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  charts/gardener/operator/templates/clusterrole.yaml
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/operator.md
  docs/concepts/operator.md
  docs/development/priority-classes.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/component/observability/monitoring/alertmanager/alertmanager.go
  pkg/component/observability/monitoring/alertmanager/alertmanager_test.go
  pkg/component/observability/monitoring/alertmanager/component.go
  pkg/component/observability/monitoring/alertmanager/ingress.go
  pkg/component/observability/monitoring/alertmanager/poddisruptionbudget.go
  pkg/component/observability/monitoring/migration.go
  pkg/component/observability/monitoring/prometheus/component.go
  pkg/component/shared/alertmanager.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/operation/botanist/monitoring.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/garden/garden/reconciler.go
  pkg/operator/controller/garden/garden/reconciler_delete.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  test/e2e/operator/garden/create_delete.go
  test/integration/operator/garden/garden/garden_test.go
Labels: kind/enhancement, area/dev-productivity, size/XL, area/monitoring, cla: yes, lgtm, approved

#9344 [GEP-19] Add dedicated namespace label for PVCs in migration
  cmd/gardenlet/app/app.go
  pkg/component/observability/monitoring/migration.go
Labels: kind/bug, size/M, area/monitoring, cla: yes, lgtm, approved

#9339 Injected new reference annotations when updating grm cm on gardenlet startup
  cmd/gardenlet/app/app.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#9349 Parallelize orphaned node `Lease` deletion
  pkg/gardenlet/controller/shoot/care/garbage_collection.go
Labels: kind/bug, area/usability, size/S, cla: yes, lgtm, approved

#9353 [release-v1.89] Automated cherry pick of #9349: Parallelize orphaned node `Lease` deletion
  pkg/gardenlet/controller/shoot/care/garbage_collection.go
Labels: kind/bug, area/usability, size/S, cla: yes, lgtm, approved

#9342 Fix and improve Gardener Operator documentation
  docs/concepts/operator.md
Labels: kind/bug, area/documentation, size/S, cla: yes, lgtm, approved

#9352 [release-v1.88] Automated cherry pick of #9349: Parallelize orphaned node `Lease` deletion
  pkg/gardenlet/controller/shoot/care/garbage_collection.go
Labels: kind/bug, area/usability, size/S, cla: yes, lgtm, approved

#9332 Redirect all non-vpn traffic on port 8132 of istio ingress gateway to https port.
  pkg/component/networking/istio/charts/istio/istio-ingress/templates/vpn-envoy-filter.yaml
  pkg/component/networking/istio/test_charts/ingress_vpn_envoy_filter.yaml
Labels: kind/enhancement, area/security, size/M, area/networking, cla: yes, lgtm, approved

#9300 Replace `Ingress` resources for `kube apiserver` with direct `Istio` exposure
  pkg/component/kubernetes/apiserverexposure/ingress.go
  pkg/component/kubernetes/apiserverexposure/ingress_test.go
  pkg/component/kubernetes/apiserverexposure/internal_name_service.go
  pkg/component/kubernetes/apiserverexposure/internal_name_service_test.go
  pkg/component/shared/istio.go
  pkg/component/shared/istio_test.go
  pkg/component/test/istiocomponent.go
  pkg/controller/networkpolicy/reconciler.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/operation/botanist/kubeapiserverexposure.go
  pkg/gardenlet/operation/botanist/kubeapiserverexposure_test.go
  pkg/utils/istio/destinationrule.go
  pkg/utils/istio/destinationrule_test.go
  pkg/utils/istio/gateway.go
  pkg/utils/istio/gateway_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
Labels: kind/enhancement, size/XL, area/networking, cla: yes, lgtm, approved

#9357 Improve API discovery for generating read-only `ClusterRole` for `shoots/viewerkubeconfig` subresource
  pkg/gardenlet/operation/botanist/shootsystem.go
  pkg/gardenlet/operation/botanist/shootsystem_test.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#9360 Add disallowed transition to HA shoot control planes documentation
  docs/usage/shoot_high_availability.md
Labels: kind/enhancement, size/XS, area/documentation, area/high-availability, cla: yes, lgtm, approved

#9358 [operator] Prevent crashing when no `Garden` exists
  pkg/operator/controller/garden/care/add.go
  pkg/operator/controller/garden/care/reconciler.go
Labels: kind/enhancement, area/usability, size/S, cla: yes, lgtm, approved

#9380 [release-v1.90] Cleanup `PodSecurityPolicy` admission plugin from Shoot for one more release
  pkg/apiserver/registry/core/shoot/strategy.go
  pkg/apiserver/registry/core/shoot/strategy_test.go
Labels: area/usability, size/M, kind/cleanup, cla: yes, lgtm, approved

#9354 [GEP-24] Sync service account public keys to Garden cluster
  example/gardener-local/controlplane/service-account-issuer-secret.yaml
  example/provider-local/shoot.yaml
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler.go
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler_test.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_shoot.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_force_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/serviceaccountkeys.go
  pkg/gardenlet/operation/botanist/serviceaccountkeys_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  skaffold.yaml
  test/e2e/gardener/common.go
Labels: kind/enhancement, area/security, size/XL, area/usability, cla: yes, lgtm, approved

#9365 Remove unsupported feature gates and admission plugins from the Shoot during force upgrades
  pkg/component/nodemanagement/dependencywatchdog/access_test.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler_test.go
  pkg/gardenlet/operation/botanist/kubeapiserverexposure_test.go
  pkg/utils/gardener/secretsrotation/etcd_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
Labels: kind/enhancement, size/XL, area/ops-productivity, cla: yes, lgtm, approved

#9376 Enhance `shoot-care` controller with additional checks related to actions of `dependency-watchdog-prober`
  pkg/component/nodemanagement/dependencywatchdog/bootstrap.go
  pkg/gardenlet/controller/shoot/care/health.go
  pkg/gardenlet/controller/shoot/care/health_test.go
  pkg/gardenlet/controller/shoot/care/reconciler.go
  pkg/gardenlet/controller/shoot/care/reconciler_test.go
  pkg/gardenlet/controller/shoot/care/types.go
Labels: kind/enhancement, area/ops-productivity, size/L, cla: yes, lgtm, approved

#9388 Migrate deprecated `failure-domain.beta.kubernetes.io` labels to `topology.kubernetes.io`
  cmd/gardenlet/app/app.go
  cmd/gardenlet/app/migration.go
Labels: kind/bug, size/XL, area/usability, cla: yes, lgtm, approved

#9419 [release-v1.89] Automated cherry pick of #9387: [GEP-19] Fix the match expression in the alertmanager configuration
  pkg/component/monitoring/alertmanager/alertmanager_test.go
  pkg/component/monitoring/alertmanager/config.go
Labels: size/XS, area/monitoring, kind/regression, cla: yes, lgtm, approved

#9387 [GEP-19] Fix the match expression in the alertmanager configuration
  pkg/component/observability/monitoring/alertmanager/alertmanager_test.go
  pkg/component/observability/monitoring/alertmanager/config.go
Labels: area/monitoring, kind/regression, size/S, cla: yes, lgtm, approved

#9409 Improve `renovate` handling of `imagevector/images.yaml` updates
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#9381 Update `Nodes marked unhealthy` dashboard query to match `NodeNotHealthy` alert
  pkg/component/observability/plutono/dashboards/shoot/owners/worker/node-pool-dashboard.json
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#9416 [GEP-19] Ensure legacy resource cleanup for shoot Alertmanager is executed
  pkg/gardenlet/operation/botanist/monitoring.go
  pkg/gardenlet/operation/botanist/monitoring_test.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#9423 Fix istio ingress gateway labels for zonal istio ingress migration.
  pkg/gardenlet/controller/seed/seed/components.go
Labels: kind/bug, area/networking, size/S, cla: yes, lgtm, approved

#9415 [release-v1.88] Automated cherry pick of #9388: Migrate deprecated `failure-domain.beta.kubernetes.io` labels to `topology.kubernetes.io`
  cmd/gardenlet/app/app.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#9385 Adds common label key to the observability applications
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/observability/logging/vali/vali.go
  pkg/component/observability/logging/vali/vali_test.go
  pkg/component/observability/monitoring/alertmanager/alertmanager.go
  pkg/component/observability/monitoring/alertmanager/alertmanager_test.go
  pkg/component/observability/monitoring/alertmanager/vpa.go
  pkg/component/observability/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus-vpa.yaml
  pkg/component/observability/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  pkg/component/observability/monitoring/prometheus/prometheus.go
  pkg/component/observability/monitoring/prometheus/prometheus_test.go
  pkg/component/observability/monitoring/prometheus/vpa.go
  pkg/component/observability/plutono/plutono.go
  pkg/component/observability/plutono/plutono_test.go
Labels: kind/enhancement, size/M, area/monitoring, area/logging, cla: yes, lgtm, approved

#9414 [release-v1.89] Automated cherry pick of #9388: Migrate deprecated `failure-domain.beta.kubernetes.io` labels to `topology.kubernetes.io`
  cmd/gardenlet/app/app.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#9363 local-path provisioner with support for volume resizing
  Makefile
  hack/kind-up.sh
  hack/tools.mk
  pkg/provider-local/charts/shoot-storageclasses/templates/storageclasses.yaml
Labels: kind/enhancement, size/L, kind/poc, area/control-plane, area/auto-scaling, cla: yes, lgtm, approved, area/ipcei

#9443 Use `0755` permissions when `gardener-node-agent`'s OSC reconciler creates dirs
  pkg/nodeagent/controller/operatingsystemconfig/reconciler.go
Labels: kind/enhancement, size/XS, area/os, cla: yes, lgtm, approved

#9422 Add plutono dashboard for image pull duration
  pkg/component/observability/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/templates/config.yaml
  pkg/component/observability/plutono/dashboards/shoot/owners/worker/container-images.json
  pkg/component/observability/plutono/plutono_test.go
Labels: kind/enhancement, size/L, area/monitoring, cla: yes, lgtm, approved

#9446 Set ENV `GOTOOLCHAIN=auto` in `golang-test` image
  hack/tools/image/Dockerfile
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9393 Fix kube-apiserver service exposure after replacement of ingress resources with direct istio exposure.
  pkg/gardenlet/operation/botanist/kubeapiserverexposure.go
  pkg/gardenlet/operation/istio_config.go
Labels: kind/bug, area/networking, size/S, cla: yes, lgtm, approved

#9441 Prepare next Dev Cycle `v1.92.0-dev`
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#9457 Fix race condition in istio zone migration.
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
Labels: kind/bug, area/networking, size/S, cla: yes, lgtm, approved

#9447 Drop deprecated `.spec.runtimeCuster.ingress.domain` field from Garden API
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/operator.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/controller/garden/garden/components.go
Labels: size/L, kind/technical-debt, area/networking, cla: yes, lgtm, approved

#9459 [node-agent] Support restarting systemd units via annotation without `.service` suffix
  pkg/nodeagent/controller/node/reconciler.go
  test/integration/nodeagent/node/node_test.go
Labels: kind/bug, area/ops-productivity, size/XS, cla: yes, lgtm, approved

#9458 Fix `logcheck` build
  .github/renovate.json5
  hack/tools.mk
  hack/tools/logcheck/go.mod
Labels: kind/bug, area/dev-productivity, size/S, cla: yes, lgtm, approved

#9462 Restore `etcd` with 1 replica and scale it up after `kapi` deployment for HA shoots
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/etcd.go
  pkg/gardenlet/operation/botanist/etcd_test.go
Labels: kind/enhancement, size/M, area/control-plane-migration, cla: yes, lgtm, approved

#9421 Add custom `matcher` for `ManagedResource`s
  go.mod
  pkg/component/autoscaling/hvpa/hvpa_test.go
  pkg/component/autoscaling/vpa/vpa_test.go
  pkg/component/garden/system/virtual/virtual_test.go
  pkg/component/gardener/admissioncontroller/admission_controller_test.go
  pkg/component/gardener/apiserver/apiserver_test.go
  pkg/component/gardener/controllermanager/controller_manager_test.go
  pkg/component/gardener/scheduler/scheduler_test.go
  pkg/component/observability/logging/eventlogger/event_logger_test.go
  pkg/component/observability/logging/fluentoperator/fluent_bit_test.go
  pkg/component/observability/logging/fluentoperator/fluentoperator_test.go
  pkg/component/observability/logging/vali/vali_test.go
  pkg/component/observability/monitoring/alertmanager/alertmanager_test.go
  pkg/component/observability/monitoring/gardenermetricsexporter/gardener_metrics_exporter_test.go
  pkg/component/observability/monitoring/kubestatemetrics/kubestatemetrics_test.go
  pkg/component/observability/monitoring/prometheus/prometheus_test.go
  pkg/component/observability/monitoring/prometheusoperator/prometheus_operator_test.go
  pkg/utils/test/matchers/managedresource.go
  pkg/utils/test/matchers/managedresource_test.go
  pkg/utils/test/matchers/matchers.go
  pkg/utils/test/runtime/seralize.go
Labels: kind/enhancement, area/dev-productivity, area/testing, cla: yes, lgtm, approved, size/XXL

#9450 Drop graduated `MachineControllerManagerDeployment` feature gate
  docs/deployment/feature_gates.md
  pkg/features/features.go
  pkg/gardenlet/features/features.go
Labels: area/open-source, size/M, kind/cleanup, cla: yes, lgtm, approved

#9476 Fix cncf image link
  README.md
Labels: kind/bug, size/XS, area/documentation, cla: yes, lgtm, approved

#9386 [Cleanup] Drop VPN Diffie–Hellman parameters
  docs/operations/configuration.md
  example/10-secret-openvpn-diffie-hellman.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/networking/vpn/seedserver/mock/mocks.go
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/seedserver/seedserver_test.go
  pkg/component/networking/vpn/shoot/shoot.go
  pkg/gardenlet/operation/botanist/vpnseedserver.go
  pkg/gardenlet/operation/botanist/vpnseedserver_test.go
  pkg/utils/gardener/garden.go
Labels: area/quality, size/L, kind/cleanup, cla: yes, lgtm, approved

#9471 Deprecate `shoot.spec.dns.providers` handling
  docs/api-reference/core.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/resourcemanager/webhook/highavailabilityconfig/handler.go
Labels: kind/api-change, size/M, cla: yes, lgtm, approved

#9478 Remove graduated `APIServerFastRollout` feature gate
  docs/deployment/feature_gates.md
  pkg/features/features.go
  pkg/gardenlet/features/features.go
Labels: area/open-source, kind/cleanup, size/S, cla: yes, lgtm, approved

#9470 Fix NodeNotHealthy alert with correct NodeNotReady taint
  pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go
  pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules_test.go
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved
