Repository gardener/gardener, pull requests merged in 2024-12, with the labels that each got.

#10896 Cleanup provider type predicate in favor of provider label
  extensions/pkg/predicate/predicate.go
  extensions/pkg/predicate/predicate_test.go
  pkg/api/core/accessor_test.go
  pkg/api/security/accessor_test.go
  pkg/apis/core/types.go
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/types_namespacedcloudprofile.go
  pkg/apis/core/types_secretbinding.go
  pkg/apis/core/types_secretbinding_test.go
  pkg/apis/core/types_seed.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/types_namespacedcloudprofile.go
  pkg/apis/core/v1beta1/types_secretbinding.go
  pkg/apis/core/v1beta1/types_secretbinding_test.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/security/types.go
  pkg/apis/security/types_credentialsbinding.go
  pkg/apis/security/v1alpha1/types_credentialsbinding.go
  pkg/provider-local/admission/mutator/webhook.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: area/usability, size/L, kind/cleanup, cla: yes, lgtm, approved

#10957 chore: Run `make generate` for grouped Renovate updates
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#10961 Check for pod's condition.Reason for pod completeness condition
  pkg/utils/kubernetes/health/deployment_test.go
  pkg/utils/kubernetes/health/pod.go
  pkg/utils/kubernetes/health/pod_test.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#10937 Use `NamespacedCloudProfile` status handler properly
  pkg/apis/core/validation/cloudprofile.go
  pkg/apiserver/registry/core/namespacedcloudprofile/strategy.go
  pkg/apiserver/registry/core/namespacedcloudprofile/strategy_test.go
  pkg/controllermanager/controller/namespacedcloudprofile/reconciler.go
  pkg/controllermanager/controller/namespacedcloudprofile/reconciler_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#10986 Remove OwnerReference from EnvoyFilter for apiserver-proxy in `apiserverexposure` package
  pkg/component/kubernetes/apiserverexposure/sni.go
  pkg/component/kubernetes/apiserverexposure/sni_test.go
  pkg/component/kubernetes/apiserverexposure/templates/envoyfilter.yaml
  pkg/gardenlet/operation/botanist/kubeapiserverexposure.go
Labels: area/quality, kind/cleanup, area/networking, size/S, cla: yes, lgtm, approved

#10991 local-setup: Fix Shoot Node logging
  charts/gardener/provider-local/templates/coredns/configmap.yaml
  pkg/provider-local/controller/infrastructure/actuator.go
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#10955 Use Subresource client for `serviceaccounts/token`
  pkg/controller/gardenletdeployer/actuator.go
  pkg/controller/tokenrequestor/add.go
  pkg/controller/tokenrequestor/reconciler.go
  pkg/controller/tokenrequestor/reconciler_test.go
  pkg/gardenlet/bootstrap/util/util.go
  pkg/gardenlet/bootstrap/util/util_test.go
Labels: kind/enhancement, size/L, area/robustness, cla: yes, lgtm, approved

#10990 Fix `make check` when running a shoot in dev setup
  hack/check-plutono-dashboards.sh
Labels: kind/bug, area/dev-productivity, size/XS, ok-to-test, cla: yes, lgtm, approved

#10998 docs: Introduce section headings for prepare and complete of credential rotation
  docs/usage/shoot-operations/shoot_credentials_rotation.md
Labels: kind/enhancement, area/documentation, size/S, cla: yes, lgtm, approved

#10663 [operator] Improve `Gardenlet` watch handling
  docs/concepts/operator.md
  extensions/pkg/util/clientset.go
  pkg/client/kubernetes/client.go
  pkg/client/kubernetes/clientmap/garden_clientmap.go
  pkg/client/kubernetes/clientmap/garden_clientmap_test.go
  pkg/client/kubernetes/options.go
  pkg/operator/controller/add.go
  pkg/operator/controller/controllerregistrar/reconciler.go
  pkg/operator/controller/extension/extension/reconciler.go
  pkg/operator/controller/garden/garden/reconciler.go
  pkg/operator/controller/virtual/access/access_suite_test.go
  pkg/operator/controller/virtual/access/add.go
  pkg/operator/controller/virtual/access/add_test.go
  pkg/operator/controller/virtual/access/reconciler.go
  pkg/operator/controller/virtual/add.go
  pkg/operator/controller/virtual/cluster/add.go
  pkg/operator/controller/virtual/cluster/add_test.go
  pkg/operator/controller/virtual/cluster/cluster_suite_test.go
  pkg/operator/controller/virtual/cluster/reconciler.go
  pkg/utils/gardener/garden_status.go
  pkg/utils/gardener/garden_status_test.go
  skaffold-operator.yaml
  test/integration/operator/virtual/access/access_suite_test.go
  test/integration/operator/virtual/access/access_test.go
  test/integration/operator/virtual/cluster/cluster_suite_test.go
  test/integration/operator/virtual/cluster/cluster_test.go
Labels: kind/bug, area/ops-productivity, cla: yes, lgtm, approved, size/XXL, area/ipcei

#10958 fix: Implement script for augmenting Skaffold's --cache-artifact CLI flag
  Makefile
  hack/get-skaffold-cache-artifacts.sh
Labels: kind/bug, area/dev-productivity, size/M, cla: yes, lgtm, approved

#10923 Update custom CAs on existing nodes
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component_test.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/ops-productivity, size/M, cla: yes, lgtm, approved

#10970 Set env variables for dual-stack in kube-apiserver.
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
Labels: kind/enhancement, size/L, area/networking, cla: yes, lgtm, approved

#11002 chore: add gardener logo variants
  logo/horizontal/black/gardener-brand-horizontal-black.png
  logo/horizontal/black/gardener-brand-horizontal-black.svg
  logo/horizontal/color/gardener-brand-horizontal-color.png
  logo/horizontal/color/gardener-brand-horizontal-color.svg
  logo/horizontal/white/gardener-brand-horizontal-white.png
  logo/horizontal/white/gardener-brand-horizontal-white.svg
  logo/icon/black/gardener-brand-icon-black.png
  logo/icon/black/gardener-brand-icon-black.svg
  logo/icon/color/gardener-brand-icon-color.png
  logo/icon/color/gardener-brand-icon-color.svg
  logo/icon/white/gardener-brand-icon-white.png
  logo/icon/white/gardener-brand-icon-white.svg
  logo/stacked/black/gardener-brand-stacked-black.png
  logo/stacked/black/gardener-brand-stacked-black.svg
  logo/stacked/color/gardener-brand-stacked-color.png
  logo/stacked/color/gardener-brand-stacked-color.svg
  logo/stacked/white/gardener-brand-stacked-white.png
  logo/stacked/white/gardener-brand-stacked-white.svg
Labels: kind/enhancement, size/L, cla: yes, lgtm, approved

#10988 `token-requestor`: Optionally support injecting CABundle into the secret
  docs/concepts/resource-manager.md
  pkg/apis/resources/v1alpha1/types.go
  pkg/controller/tokenrequestor/add.go
  pkg/controller/tokenrequestor/reconciler.go
  pkg/controller/tokenrequestor/reconciler_test.go
  test/integration/resourcemanager/tokenrequestor/tokenrequestor_test.go
Labels: kind/enhancement, area/usability, size/L, ok-to-test, cla: yes, lgtm, approved

#10703 Introduce integration test for `node-agent-authorizer` webhook
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/operator/controller/garden/garden/components.go
  test/integration/resourcemanager/csrapprover/csrapprover_suite_test.go
  test/integration/resourcemanager/nodeagentauthorizer/nodeagentauthorizer_suite_test.go
  test/integration/resourcemanager/nodeagentauthorizer/nodeagentauthorizer_test.go
Labels: kind/enhancement, size/XL, area/testing, cla: yes, lgtm, approved

#11014 Use `SingleObjectCache` for `NamespacedCloudProfile`s
  cmd/gardenlet/app/app.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer_test.go
Labels: kind/enhancement, area/usability, size/S, cla: yes, lgtm, approved

#10997 NewVPN feature: ensure `IPv6` is enabled for non-HA case
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/seedserver/seedserver_test.go
Labels: kind/enhancement, size/M, area/control-plane, cla: yes, lgtm, approved

#10994 Fix `CalculateMaxNodesForShoot` for `cluster-autoscaler` in dual-stack case.
  pkg/gardenlet/operation/botanist/clusterautoscaler.go
  pkg/gardenlet/operation/botanist/clusterautoscaler_test.go
Labels: kind/bug, size/M, area/networking, cla: yes, lgtm, approved

#10984 Switch local KinD clusters to Structured Authorization
  example/gardener-local/kind/cluster/templates/_extra_mounts.tpl
  example/gardener-local/kind/cluster/templates/_kubeadm_config_patches.tpl
  example/gardener-local/kind/cluster/templates/cluster.yaml
  example/gardener-local/kube-apiserver/authz-config-with-seedauthorizer.yaml
  example/gardener-local/kube-apiserver/authz-config-without-seedauthorizer.yaml
  example/gardener-local/kube-apiserver/authz-webhook-kubeconfig-ipv4.yaml
  example/gardener-local/kube-apiserver/authz-webhook-kubeconfig-ipv6.yaml
  hack/kind-up.sh
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#11004 🧹 No Longer Generate Empty `Secret` For `reconcile` `OperatingSystemConfig`s
  docs/api-reference/extensions.md
  example/seed-crds/10-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  extensions/pkg/controller/operatingsystemconfig/reconciler.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
Labels: area/dev-productivity, size/M, kind/cleanup, cla: yes, lgtm, approved

#10964 Collect performance metrics from e2e tests in prow cluster
  charts/gardener/provider-local/templates/deployment.yaml
  charts/gardener/provider-local/values.yaml
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-extension-provider-local/app/options.go
  example/provider-local/garden/local/.gitignore
  example/provider-local/garden/local/kustomization.yaml
  example/provider-local/garden/operator/.gitignore
  example/provider-local/garden/operator/kustomization.yaml
  hack/generate-kustomize-patch-controllerdeployment-provider-local-prow.sh
  hack/generate-kustomize-patch-controllerdeployment-provider-local.sh
  hack/generate-kustomize-patch-extension-provider-local-prow.sh
  hack/kind-up.sh
  pkg/provider-local/webhook/prometheus/add.go
  pkg/provider-local/webhook/prometheus/mutator.go
  pkg/provider-local/webhook/prometheus/options.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#10949 do not leak api-server cluster ip from seed to shoot
  docs/usage/networking/shoot_networking.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
  pkg/gardenlet/operation/botanist/kubeapiserverexposure.go
  pkg/utils/validation/cidr/cidr.go
  pkg/utils/validation/cidr/cidr_test.go
  pkg/utils/validation/cidr/disjoint.go
  pkg/utils/validation/cidr/disjoint_test.go
Labels: size/L, kind/cleanup, area/networking, cla: yes, lgtm, approved

#11040 [GEP-28] Generate CLI reference for `gardenadm`
  cmd/gardenadm/main.go
  docs/README.md
  docs/cli-reference/README.md
  docs/cli-reference/gardenadm/gardenadm.md
  docs/cli-reference/gardenadm/gardenadm_bootstrap.md
  docs/cli-reference/gardenadm/gardenadm_connect.md
  docs/cli-reference/gardenadm/gardenadm_discover.md
  docs/cli-reference/gardenadm/gardenadm_init.md
  docs/cli-reference/gardenadm/gardenadm_join.md
  docs/cli-reference/gardenadm/gardenadm_token.md
  docs/cli-reference/gardenadm/gardenadm_token_create.md
  docs/cli-reference/gardenadm/gardenadm_token_delete.md
  docs/cli-reference/gardenadm/gardenadm_token_generate.md
  docs/cli-reference/gardenadm/gardenadm_token_list.md
  docs/cli-reference/gardenadm/gardenadm_version.md
  go.mod
  go.sum
  hack/clean.sh
  hack/tools/cli-reference-generator/main.go
Labels: kind/enhancement, area/documentation, size/L, cla: yes, lgtm, approved

#11037 Fix empty image-vector overwrite for `machine-controller-manager-provider-local`
  Makefile
  hack/generate-kustomize-patch-controllerdeployment-provider-local-prow.sh
  hack/generate-kustomize-patch-extension-provider-local-prow.sh
  hack/get-skaffold-cache-artifacts.sh
  skaffold-gardenadm.yaml
Labels: area/dev-productivity, kind/regression, size/S, cla: yes, lgtm, approved

#10910 Make dropping versions from `NamespacedCloudProfile` idempotent
  pkg/apiserver/registry/core/namespacedcloudprofile/strategy.go
  pkg/apiserver/registry/core/namespacedcloudprofile/strategy_test.go
  plugin/pkg/namespacedcloudprofile/validator/admission.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#11057 Fix e2e tests: Revert "chore(deps): update kindest/node docker tag to v1.31.4 (#11030)"
  example/gardener-local/kind/cluster/values.yaml
  pkg/provider-local/node/Dockerfile
Labels: size/XS, kind/regression, area/testing, cla: yes, lgtm, approved

#10954 Fallback machine image version if omitted or only provided partly
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, area/usability, size/L, area/os, cla: yes, lgtm, approved

#11047 🧹 Cleanup some `TODO`s
  cmd/gardenlet/app/migration.go
  docs/api-reference/seedmanagement.md
  pkg/apis/seedmanagement/types_managedseed.go
  pkg/apis/seedmanagement/v1alpha1/generated.pb.go
  pkg/apis/seedmanagement/v1alpha1/generated.proto
  pkg/apis/seedmanagement/v1alpha1/types_managedseed.go
  pkg/apis/seedmanagement/v1alpha1/zz_generated.conversion.go
  pkg/apis/seedmanagement/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/seedmanagement/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/apiserver/registry/core/shoot/storage/kubeconfig.go
  pkg/gardenlet/operation/botanist/secrets.go
  pkg/gardenlet/operation/botanist/worker.go
  pkg/gardenlet/operation/botanist/worker_test.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#10959 Add vpa histogram decay options
  docs/api-reference/core.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/component/autoscaling/vpa/recommender.go
  pkg/component/autoscaling/vpa/vpa_test.go
  pkg/gardenlet/operation/botanist/vpa.go
Labels: kind/enhancement, area/auto-scaling, cla: yes, lgtm, approved, size/XXL

#11056 Drop internal version of `extensions/pkg/apis/config` API
  .golangci.yaml.in
  extensions/pkg/apis/config/doc.go
  extensions/pkg/apis/config/types.go
  extensions/pkg/apis/config/zz_generated.deepcopy.go
  extensions/pkg/controller/healthcheck/controller.go
  extensions/pkg/controller/healthcheck/healthcheck_actuator.go
  extensions/pkg/util/shoot_clients.go
  extensions/pkg/webhook/handler_shootclient.go
  pkg/provider-local/controller/healthcheck/add.go
  pkg/provider-local/controller/worker/actuator.go
  skaffold-gardenadm.yaml
  skaffold-operator.yaml
  skaffold.yaml
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#11059 Fix flake of `NamespacedCloudProfile` + `Shoot` creation in e2e tests
  test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go
Labels: size/M, kind/test, area/robustness, cla: yes, lgtm, approved

#11058 [operator] Trigger restart when `garden` is deleted
  cmd/gardener-operator/app/app.go
  pkg/gardenlet/bootstrap/certificate/certificate_rotation.go
  pkg/operator/controller/add.go
  pkg/operator/controller/controllerregistrar/add.go
  pkg/operator/controller/controllerregistrar/reconciler.go
  test/integration/operator/controllerregistrar/controllerregistrar_suite_test.go
  test/integration/operator/controllerregistrar/controllerregistrar_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#11074 Enable Gardener scheduler to schedule Shoot with initial NamespacedCloudProfile reference successfully
  pkg/component/gardener/scheduler/rbac.go
  pkg/component/gardener/scheduler/scheduler_test.go
Labels: kind/bug, size/XS, area/usability, cla: yes, lgtm, approved

#11064 feat: add WatchBuilder to extension controller
  extensions/pkg/controller/extension/controller.go
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#11052 Use external version of `k8s.io/component-base/config.ClientConnectionConfiguration`
  .golangci.yaml.in
  charts/gardener/gardenlet/test/test.go
  cmd/gardener-admission-controller/app/app.go
  cmd/gardener-controller-manager/app/app.go
  cmd/gardener-extension-admission-local/app/app.go
  cmd/gardener-node-agent/app/app.go
  cmd/gardener-operator/app/app.go
  cmd/gardener-resource-manager/app/app.go
  cmd/gardener-scheduler/app/app.go
  cmd/gardenlet/app/app.go
  extensions/pkg/util/clientset.go
  pkg/client/kubernetes/client.go
  pkg/client/kubernetes/clientmap/builder/garden_builder.go
  pkg/client/kubernetes/clientmap/builder/garden_builder_test.go
  pkg/client/kubernetes/clientmap/builder/shoot_builder.go
  pkg/client/kubernetes/clientmap/builder/shoot_builder_test.go
  pkg/client/kubernetes/clientmap/garden_clientmap.go
  pkg/client/kubernetes/clientmap/garden_clientmap_test.go
  pkg/client/kubernetes/clientmap/shoot_clientmap.go
  pkg/client/kubernetes/clientmap/shoot_clientmap_test.go
  pkg/client/kubernetes/options.go
  pkg/gardenlet/bootstrap/certificate/certificate_rotation.go
  pkg/operator/controller/virtual/cluster/reconciler.go
  test/e2e/gardenadm/common/client.go
  test/e2e/operator/garden/common.go
  test/framework/gardenerframework.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#11077 temp: Add temporary debug output to flaky script
  hack/generate-kustomize-patch-gardenlet.sh
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#11038 Allow deletion and migration of never-created clusters with dynamic node network
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#11073 chore: Group Istio Renovate updates in one PR
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#10969 `gardener-node-agent`: Persist applied changes after each step
  pkg/nodeagent/controller/operatingsystemconfig/changes.go
  pkg/nodeagent/controller/operatingsystemconfig/containerd.go
  pkg/nodeagent/controller/operatingsystemconfig/osc_changes.go
  pkg/nodeagent/controller/operatingsystemconfig/reconciler.go
  pkg/nodeagent/dbus/fake/fake_dbus.go
  test/integration/nodeagent/operatingsystemconfig/operatingsystemconfig_test.go
Labels: kind/enhancement, size/XL, area/robustness, ok-to-test, cla: yes, lgtm, approved

#11080 [operator] Fix Structured Authn for Dashboard
  charts/gardener/operator/templates/crd-gardens.yaml
  docs/api-reference/operator.md
  docs/concepts/operator.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/operator/v1alpha1/types_garden.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/bug, area/security, kind/api-change, size/L, cla: yes, lgtm, approved, area/ipcei
