Repository gardener/gardener, pull requests merged in 2024-06, with the labels that each got.

#9890 Promote `MutableShootSpecNetworkingNodes` feature gate to GA
  docs/api-reference/core.md
  docs/deployment/feature_gates.md
  example/gardener-local/controlplane/values.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/seedmanagement/validation/managedseedset_test.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/features/features.go
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved

#9889 Promote `CoreDNSQueryRewriting` feature gate to GA
  docs/deployment/feature_gates.md
  docs/usage/dns-search-path-optimization.md
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/gardenlet/values.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/component/networking/coredns/coredns.go
  pkg/component/networking/coredns/coredns_test.go
  pkg/features/features.go
  pkg/gardenlet/operation/botanist/coredns.go
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved

#9899 Links for additional primary DNS provider extensions
  extensions/README.md
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#9885 🧹 Cleanup some `TODOs`
  cmd/gardenlet/app/migration.go
  docs/api-reference/extensions.md
  example/seed-crds/10-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/extensions/validation/operatingsystemconfig_test.go
  pkg/apiserver/registry/core/shoot/storage/kubeconfig.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/kubernetes/apiserver/apiserver.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/shoot_resources.go
  pkg/component/kubernetes/apiserverexposure/ingress.go
  pkg/component/kubernetes/controllermanager/controllermanager.go
  pkg/component/kubernetes/controllermanager/controllermanager_test.go
  pkg/component/kubernetes/proxy/proxy_test.go
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager_test.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/kubeapiserverexposure_test.go
  pkg/gardenlet/operation/botanist/operatingsystemconfig_test.go
  pkg/gardenlet/operation/botanist/secrets.go
  pkg/gardenlet/operation/botanist/worker.go
  pkg/gardenlet/operation/botanist/worker_test.go
  pkg/operator/controller/garden/garden/components.go
  skaffold.yaml
  test/e2e/gardener/common.go
  test/e2e/gardener/upgrade/upgrade.go
Labels: area/dev-productivity, size/XL, kind/cleanup, cla: yes, lgtm, approved

#9894 `gardenlet`'s pod garbage collector considers pods with reason `NodeAffinity`
  docs/concepts/gardenlet.md
  pkg/gardenlet/controller/shoot/care/garbage_collection.go
Labels: kind/enhancement, area/ops-productivity, size/XS, cla: yes, lgtm, approved

#9891 Fix scrapeconfigs syntax
  pkg/component/observability/monitoring/prometheus/longterm/scrapeconfigs.go
  pkg/component/observability/monitoring/prometheus/longterm/scrapeconfigs_test.go
Labels: size/XS, area/monitoring, kind/regression, cla: yes, lgtm, approved

#9900 [GEP-24] Fix: Configure DiscoveryServerDown alert only when discovery server is enabled
  pkg/component/observability/monitoring/blackboxexporter/garden/config.go
  pkg/component/observability/monitoring/blackboxexporter/garden/config_test.go
  pkg/component/observability/monitoring/prometheus/garden/assets/prometheusrules/garden.yaml
  pkg/component/observability/monitoring/prometheus/garden/prometheusrules.go
  pkg/component/observability/monitoring/prometheus/garden/prometheusrules_test.go
  pkg/operator/controller/garden/garden/components.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/bug, size/L, cla: yes, lgtm, approved, area/ipcei, ipcei/oidc

#9903 Fix the `normalizeAlertingRules` func
  pkg/gardenlet/operation/botanist/monitoring.go
Labels: size/XS, area/monitoring, kind/regression, cla: yes, lgtm, approved

#9813 [GEP-26] Add `TokenRequest` API and `workloadidentities/token` subresource
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/values.yaml
  docs/api-reference/security.md
  docs/proposals/26-workload-identity.md
  example/gardener-local/controlplane/values.yaml
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/security/register.go
  pkg/apis/security/types_tokenrequest.go
  pkg/apis/security/v1alpha1/defaults_tokenrequest.go
  pkg/apis/security/v1alpha1/generated.pb.go
  pkg/apis/security/v1alpha1/generated.proto
  pkg/apis/security/v1alpha1/register.go
  pkg/apis/security/v1alpha1/types_tokenrequest.go
  pkg/apis/security/v1alpha1/zz_generated.conversion.go
  pkg/apis/security/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/security/v1alpha1/zz_generated.defaults.go
  pkg/apis/security/validation/tokenrequest.go
  pkg/apis/security/validation/tokenrequest_test.go
  pkg/apis/security/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/openapi/api_violations.report
  pkg/apiserver/openapi/openapi_generated.go
  pkg/apiserver/registry/security/rest/storage_security.go
  pkg/apiserver/registry/security/workloadidentity/storage/storage.go
  pkg/apiserver/registry/security/workloadidentity/storage/tokenrequest.go
  pkg/component/gardener/apiserver/apiserver.go
  pkg/component/gardener/apiserver/apiserver_test.go
  pkg/component/gardener/apiserver/deployment.go
  pkg/component/shared/gardenerapiserver.go
  pkg/component/shared/gardenerapiserver_test.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL, area/ipcei, ipcei/workload-identity

#9920 [release-v1.95] Automated cherry pick of #9903: Fix the `normalizeAlertingRules` func
  pkg/gardenlet/operation/botanist/monitoring.go
Labels: size/XS, area/monitoring, kind/regression, cla: yes, lgtm, approved

#9846 Introduce secret to track hash version used by OperatingSystemConfig
  cmd/gardenlet/app/migration.go
  pkg/component/extensions/operatingsystemconfig/mock/mocks.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/extensions/worker/mock/mocks.go
  pkg/component/extensions/worker/worker.go
  pkg/component/extensions/worker/worker_test.go
  pkg/gardenlet/controller/shoot/care/health_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/operatingsystemconfig.go
  pkg/gardenlet/operation/botanist/operatingsystemconfig_test.go
  pkg/gardenlet/operation/botanist/worker.go
  pkg/gardenlet/operation/botanist/worker_test.go
  pkg/utils/gardener/shootstate/shootstate.go
  pkg/utils/gardener/shootstate/shootstate_test.go
  test/framework/shootmigrationtest.go
  test/integration/gardenlet/shoot/state/state_test.go
  test/testmachinery/system/shoot_cp_migration/migrate_test.go
Labels: kind/enhancement, size/XL, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#9922 Fix some Plutono dashboards
  pkg/component/observability/plutono/dashboards/seed/systemd-logs.json
  pkg/component/observability/plutono/dashboards/shoot/owners/prometheus-dashboard.json
Labels: area/monitoring, kind/regression, cla: yes, lgtm, approved, size/XXL

#9921 Refine documentation for ManagedIssuer feature
  docs/usage/shoot_serviceaccounts.md
Labels: kind/enhancement, size/XS, area/documentation, ok-to-test, cla: yes, lgtm, approved

#9923 Clarify the importance of correct discovery hostname config
  docs/operations/configuration.md
Labels: kind/enhancement, area/security, size/XS, area/documentation, cla: yes, lgtm, approved, area/ipcei

#9925 Move "list `MachineDeployment`s" call right before its first usage in generic `Worker` actuator
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
Labels: kind/bug, area/usability, size/S, cla: yes, lgtm, approved

#9873 Promote feature gate `VPAForETCD` to beta status
  docs/deployment/feature_gates.md
  docs/development/autoscaling-specifics-for-components.md
  pkg/features/features.go
Labels: kind/enhancement, size/S, area/auto-scaling, cla: yes, lgtm, approved

#9763 [provider-local] Use `gardener-operator` for local development setup
  Makefile
  charts/gardener/provider-local/templates/deployment.yaml
  docs/concepts/operator.md
  docs/deployment/getting_started_locally.md
  example/gardener-local/gardenlet/values-operator.yaml
  example/gardener-local/kind/cluster/templates/_extra_port_mappings.tpl
  example/operator/20-garden.yaml
  example/operator/virtual-garden/.gitignore
  example/provider-local/managedseeds/shoot-managedseed.yaml
  example/provider-local/seed-operator/base/.gitignore
  example/provider-local/seed-operator/base/kustomization.yaml
  example/provider-local/seed-operator/skaffold/kustomization.yaml
  hack/ci-e2e-kind-operator-seed.sh
  hack/kind-up.sh
  hack/operator-seed-down.sh
  hack/test-e2e-local.sh
  pkg/component/kubernetes/apiserverexposure/service.go
  pkg/component/kubernetes/apiserverexposure/service_test.go
  pkg/component/networking/istio/charts/istio/istio-ingress/templates/service.yaml
  pkg/component/networking/istio/test_charts/ingress_service.yaml
  pkg/component/networking/istio/test_charts/ingress_service_dualstack.yaml
  pkg/component/networking/istio/test_charts/ingress_service_dualstack_etp.yaml
  pkg/component/networking/istio/test_charts/ingress_service_etp_cluster.yaml
  pkg/component/networking/istio/test_charts/ingress_service_etp_local.yaml
  pkg/controller/service/reconciler.go
  pkg/gardenlet/operation/botanist/kubeapiserverexposure.go
  pkg/operator/controller/add.go
  pkg/operator/controller/garden/garden/components.go
  pkg/provider-local/webhook/dnsconfig/mutator.go
  skaffold-operator-garden.yaml
  skaffold.yaml
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#9947 [release-v1.95] Update gardener-dashboard
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#9948 [release-v1.94] Update gardener-dashboard
  imagevector/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#9953 conntrack-fix container: Disable autoscaling
  pkg/component/kubernetes/proxy/proxy_test.go
  pkg/component/kubernetes/proxy/resources.go
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#9945 Update maintenance state of shoot if current maintenance but last maintenance was failed
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  test/integration/controllermanager/shoot/maintenance/maintenance_test.go
Labels: kind/bug, area/quality, size/M, cla: yes, lgtm, approved

#9961 Prepare next Dev Cycle v1.98.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#9924 Introduce operator extension API types
  docs/api-reference/operator.md
  example/operator/10-crd-operator.gardener.cloud_extensions.yaml
  example/operator/15-extension.yaml
  pkg/apis/operator/v1alpha1/types_extension.go
  pkg/apis/operator/v1alpha1/types_garden.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
Labels: kind/enhancement, area/control-plane, cla: yes, lgtm, approved, size/XXL

#9963 Fix etcd alerts for the virtual Garden cluster
  pkg/component/observability/monitoring/prometheus/garden/assets/prometheusrules/etcd.yaml
  pkg/component/observability/monitoring/prometheus/garden/prometheusrules_test.go
  pkg/component/observability/monitoring/prometheus/garden/testdata/etcd.prometheusrule.test.yaml
Labels: size/L, area/monitoring, kind/regression, cla: yes, lgtm, approved

#9975 Add warning to kind-up if non-gnu tools were detected
  hack/kind-up.sh
Labels: kind/enhancement, area/dev-productivity, size/M, ok-to-test, cla: yes, lgtm, approved

#9983 [release-v1.94] Fix etcd alerts for the virtual Garden cluster
  pkg/component/observability/monitoring/prometheus/garden/assets/prometheusrules/etcd.yaml
  pkg/component/observability/monitoring/prometheus/garden/prometheusrules_test.go
  pkg/component/observability/monitoring/prometheus/garden/testdata/etcd.prometheusrule.test.yaml
Labels: size/L, area/monitoring, kind/regression, cla: yes, lgtm, approved

#9982 [release-v1.95] Fix etcd alerts for the virtual Garden cluster
  pkg/component/observability/monitoring/prometheus/garden/assets/prometheusrules/etcd.yaml
  pkg/component/observability/monitoring/prometheus/garden/prometheusrules_test.go
  pkg/component/observability/monitoring/prometheus/garden/testdata/etcd.prometheusrule.test.yaml
Labels: size/L, area/monitoring, kind/regression, cla: yes, lgtm, approved

#9959 Introduce `gosec` for Static Application Security Testing (SAST)
  .gitignore
  Makefile
  extensions/pkg/webhook/certificates/certificates.go
  hack/sast.sh
  hack/tools.mk
  hack/tools/install-gosec.sh
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/component/apiserver/admission.go
  pkg/component/apiserver/audit.go
  pkg/component/etcd/etcd/etcd.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/gardener/dashboard/dashboard_test.go
  pkg/component/kubernetes/apiserver/apiserver.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/kubernetes/apiserver/secrets.go
  pkg/component/kubernetes/scheduler/scheduler.go
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/shoot/shoot.go
  pkg/component/shared/etcd.go
  pkg/component/test/prometheusrule.go
  pkg/controller/service/reconciler.go
  pkg/gardenlet/controller/managedseed/add.go
  pkg/gardenlet/controller/managedseed/valueshelper.go
  pkg/resourcemanager/webhook/highavailabilityconfig/handler.go
  pkg/utils/encoding.go
  pkg/utils/encoding_test.go
  pkg/utils/gardener/secrets.go
  pkg/utils/gardener/secrets_test.go
  pkg/utils/imagevector/imagevector.go
  pkg/utils/imagevector/imagevector_components.go
  pkg/utils/random.go
  pkg/utils/secrets/basic_auth.go
  pkg/utils/secrets/basic_auth_test.go
  pkg/utils/secrets/certificate.go
  pkg/utils/secrets/static_token.go
  pkg/utils/test/test_resources.go
  test/e2e/gardener/managedseed/create_rotate_delete.go
  test/envtest/aggregator.go
  test/envtest/apiserver.go
  test/framework/http_utils.go
  test/framework/k8s_utils.go
  test/framework/reporter/esreporter.go
  test/framework/shootcreationframework.go
  test/framework/shootframework.go
  test/framework/utils.go
  test/testmachinery/extensions/generator/helper.go
  test/testmachinery/shoots/operations/operations.go
  test/utils/rotation/observability.go
Labels: kind/enhancement, area/security, size/L, area/compliance, cla: yes, lgtm, approved

#9962 Specify args instead of command for etcd-druid
  pkg/component/etcd/etcd/bootstrap.go
  pkg/component/etcd/etcd/bootstrap_test.go
Labels: kind/enhancement, size/S, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#9979 Fix `fluent-bit` source repository
  .github/renovate.json5
  imagevector/images.yaml
Labels: kind/bug, area/open-source, size/M, cla: yes, lgtm, approved

#9997 Fix etcd-druid alert
  pkg/component/observability/monitoring/prometheus/shoot/assets/prometheusrules/prometheus.yaml
Labels: size/XS, area/monitoring, kind/regression, cla: yes, lgtm, approved

#9853 [GEP-26] Allow replacing SecretBindingName with CredentialsBindingName in Shoot spec (Part 1)
  charts/gardener/controlplane/charts/application/templates/clusterrole-admission-controller.yaml
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  docs/api-reference/core.md
  docs/deployment/feature_gates.md
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_shoot.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
  pkg/admissioncontroller/webhook/auth/seed/graph/vertices.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/features/features.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/apiserver/registry/core/shoot/strategy.go
  pkg/apiserver/registry/core/shoot/strategy_test.go
  pkg/component/gardener/controllermanager/configmaps.go
  pkg/component/gardener/controllermanager/controller_manager_test.go
  pkg/controllermanager/apis/config/types.go
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/defaults_test.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/controllermanager/apis/config/zz_generated.deepcopy.go
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/credentialsbinding/add.go
  pkg/controllermanager/controller/credentialsbinding/credentialsbinding_suite_test.go
  pkg/controllermanager/controller/credentialsbinding/reconciler.go
  pkg/controllermanager/controller/credentialsbinding/reconciler_test.go
  pkg/controllermanager/controller/secretbinding/reconciler.go
  pkg/controllerutils/associations.go
  pkg/controllerutils/associations_test.go
  pkg/features/features.go
  pkg/gardenlet/controller/managedseed/actuator.go
  pkg/gardenlet/controller/managedseed/actuator_test.go
  pkg/gardenlet/operation/shoot/shoot.go
  pkg/gardenlet/operation/shoot/types.go
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/global/resourcereferencemanager/admission_test.go
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/managedseed/validator/admission_test.go
  plugin/pkg/shoot/quotavalidator/admission.go
  plugin/pkg/shoot/quotavalidator/admission_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/controllermanager/credentialsbinding/credentialsbinding_suite_test.go
  test/integration/controllermanager/credentialsbinding/credentialsbinding_test.go
  test/integration/envtest/environment_test.go
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL, area/ipcei, ipcei/workload-identity

#10004 Drop custom `durationDeref` func in favor of `ptr.Deref`
  pkg/component/autoscaling/vpa/recommender.go
  pkg/component/autoscaling/vpa/updater.go
  pkg/component/autoscaling/vpa/vpa.go
Labels: kind/cleanup, size/S, area/auto-scaling, cla: yes, lgtm, approved

#10007 Remove Docker container again after kind-operator-down
  Makefile
Labels: size/XS, area/open-source, kind/cleanup, cla: yes, lgtm, approved

#9933 Expose and scrape metrics from `machine-controller-manager-provider-xxx`
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager_test.go
  pkg/component/nodemanagement/machinecontrollermanager/provider.go
  pkg/component/nodemanagement/machinecontrollermanager/provider_test.go
Labels: kind/enhancement, size/L, area/monitoring, cla: yes, lgtm, approved

#10009 Fix shoot:apiserver_latency_seconds:quantile federation configuration
  pkg/component/observability/monitoring/prometheus/aggregate/servicemonitors.go
  pkg/component/observability/monitoring/prometheus/aggregate/servicemonitors_test.go
  pkg/component/observability/plutono/dashboards/garden-shoot/apiserver-overview.json
  pkg/component/observability/plutono/dashboards/shoot/owners/kubernetes-api-server-details.json
  pkg/component/observability/plutono/dashboards/shoot/owners/worker/kubernetes-control-plane-status-dashboard.json
  pkg/component/observability/plutono/dashboards/shoot/owners/workerless/kubernetes-control-plane-status-dashboard.json
Labels: area/monitoring, kind/regression, size/S, cla: yes, lgtm, approved

#9865 Add new WorkerPoolHash calculation to rotate nodes on OSCKey change
  docs/api-reference/extensions.md
  docs/deployment/feature_gates.md
  docs/extensions/worker.md
  docs/usage/shoot_updates.md
  example/gardener-local/gardenlet/values.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_workers.yaml
  extensions/pkg/controller/worker/machines.go
  extensions/pkg/controller/worker/machines_test.go
  pkg/apis/core/v1beta1/helper/helper.go
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/extensions/v1alpha1/types_worker.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_workers.yaml
  pkg/component/extensions/operatingsystemconfig/mock/mocks.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/extensions/worker/worker.go
  pkg/features/features.go
  pkg/gardenlet/features/features.go
  pkg/gardenlet/operation/botanist/operatingsystemconfig.go
  pkg/provider-local/controller/worker/machines.go
  test/e2e/gardener/upgrade/upgrade.go
Labels: kind/enhancement, size/XL, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#9980 Renovate the remote local setup
  docs/deployment/content/remote-local-setup.yaml
  docs/deployment/getting_started_locally.md
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#10005 Cleanup provider-local CtrlDeploy
  example/provider-local/garden/base/controllerdeployment.yaml
  skaffold.yaml
Labels: size/XS, area/quality, kind/cleanup, needs-ok-to-test, cla: yes, lgtm, approved

#10015 Revert "chore(deps): update quay.io/kiwigrid/k8s-sidecar docker tag to v1.27.4 (#9943)"
  imagevector/images.yaml
Labels: area/security, size/XS, kind/regression, cla: yes, lgtm, approved

#10023 Fix cluster name in `Getting Started Locally With Extensions`
  docs/deployment/getting_started_locally_with_extensions.md
Labels: kind/bug, size/XS, area/documentation, cla: yes, lgtm, approved

#9935 [GEP-28] Add Optional Bastion Section To `CloudProfile`
  docs/proposals/27-cloudprofile-bastion-section.md
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#10003 Destroy shoot access for DWD if Shoot is workerless
  cmd/gardenlet/app/app.go
  cmd/gardenlet/app/migration.go
  pkg/component/nodemanagement/dependencywatchdog/access.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/botanist.go
Labels: area/quality, size/M, kind/cleanup, cla: yes, lgtm, approved

#9981 Add object selector to provider extension controlplane webhooks
  docs/extensions/controlplane-webhooks.md
  extensions/pkg/webhook/controlplane/controlplane.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/kubernetes/controllermanager/controllermanager.go
  pkg/component/kubernetes/controllermanager/controllermanager_test.go
  pkg/component/kubernetes/scheduler/scheduler.go
  pkg/component/kubernetes/scheduler/scheduler_test.go
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/seedserver/seedserver_test.go
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager_test.go
  pkg/gardenlet/controller/backupentry/reconciler.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/provider-local/webhook/controlplane/add.go
Labels: kind/enhancement, area/open-source, size/L, area/control-plane, area/scalability, cla: yes, lgtm, approved

#9739 Prometheus alerts for when `etcd-druid`'s snapshot compaction jobs fail above a certain rate
  pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go
  pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules_test.go
  pkg/component/observability/monitoring/prometheus/aggregate/scrapeconfigs.go
  pkg/component/observability/monitoring/prometheus/aggregate/scrapeconfigs_test.go
Labels: kind/enhancement, area/monitoring, size/S, area/control-plane, cla: yes, lgtm, approved

#10026 extensions lib: Add ObjectSelector arg to the shoot webhook
  extensions/pkg/webhook/shoot/shoot.go
Labels: kind/enhancement, size/XS, area/scalability, cla: yes, lgtm, approved

#9971 kube-apiserver: Increase HPA's max replicas count from 3 to 6 in `VPAAndHPA` autoscaling mode
  docs/development/autoscaling-specifics-for-components.md
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#10011 Ignore `status` subresources and `metadata.managedFields` for resource size limit admission
  docs/concepts/admission-controller.md
  pkg/admissioncontroller/webhook/admission/resourcesize/handler.go
  pkg/admissioncontroller/webhook/admission/resourcesize/handler_test.go
Labels: kind/enhancement, area/open-source, size/M, area/robustness, cla: yes, lgtm, approved

#9985 Mark `shoot.spec.kubernetes.kubelet.systemReserved` as deprecated
  docs/api-reference/core.md
  docs/deployment/feature_gates.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/features/features.go
Labels: kind/cleanup, size/S, area/control-plane, needs-ok-to-test, cla: yes, lgtm, approved

#10027 cloudprovider webhook: Enforce object selector unconditionally
  extensions/pkg/webhook/cloudprovider/cloudprovider.go
  extensions/pkg/webhook/controlplane/controlplane.go
  extensions/pkg/webhook/network/network.go
  extensions/pkg/webhook/shoot/shoot.go
  test/integration/extensions/webhook/cloudprovider/cloudprovider_suite_test.go
Labels: kind/enhancement, size/M, area/scalability, cla: yes, lgtm, approved

#10035 Fix regex for service discovery of vpn-seedserver.
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/seedserver/seedserver_test.go
  pkg/component/observability/plutono/dashboards/shoot/owners/worker/vpn-seed-server/envoy-proxy/envoy-proxy-dashboard.json
  pkg/component/observability/plutono/plutono.go
  pkg/component/observability/plutono/plutono_test.go
Labels: kind/bug, area/networking, size/S, cla: yes, lgtm, approved

#9957 [OPERATOR] Optional deployment of cert-management component
  charts/gardener/operator/templates/customresouredefintion.yaml
  docs/api-reference/operator.md
  docs/concepts/operator.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  imagevector/images.go
  imagevector/images.yaml
  pkg/apis/operator/v1alpha1/types_garden.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/client/kubernetes/types.go
  pkg/component/certmanagement/assets/crd-cert.gardener.cloud_certificaterevocations.yaml
  pkg/component/certmanagement/assets/crd-cert.gardener.cloud_certificates.yaml
  pkg/component/certmanagement/assets/crd-cert.gardener.cloud_issuers.yaml
  pkg/component/certmanagement/assets/doc.go
  pkg/component/certmanagement/certmanagement.go
  pkg/component/certmanagement/certmanagement_suite_test.go
  pkg/component/certmanagement/certmanagement_test.go
  pkg/component/certmanagement/crd.go
  pkg/component/certmanagement/issuers.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/garden/garden/reconciler_delete.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  skaffold-operator.yaml
  test/e2e/operator/garden/common.go
  test/e2e/operator/garden/create_delete.go
  test/e2e/operator/garden/create_rotate_delete.go
  test/integration/operator/garden/garden/garden_test.go
Labels: kind/enhancement, area/control-plane, cla: yes, lgtm, approved, size/XXL

#10045 Revert "chore(deps): update dependency gardener/logging to v0.55.7 (#9993)"
  imagevector/images.yaml
Labels: area/logging, kind/regression, size/S, cla: yes, lgtm, approved
