Repository gardener/gardener, pull requests merged in 2024-04, with the labels that each got.

#9483 Deploy a service for the Node Problem Detector component
  pkg/component/nodemanagement/nodeproblemdetector/logging.go
  pkg/component/nodemanagement/nodeproblemdetector/node_problem_detector.go
  pkg/component/nodemanagement/nodeproblemdetector/node_problem_detector_test.go
Labels: kind/enhancement, size/M, area/monitoring, cla: yes, lgtm, approved

#9498 Streamline `WithServiceAccountIssuerHostname`
  pkg/gardenlet/operation/shoot/shoot.go
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#9472 Add new Extension Lifecycle Strategy `AfterWorker`
  cmd/gardener-extension-provider-local/app/options.go
  docs/extensions/controllerregistration.md
  docs/extensions/provider-local.md
  example/provider-local/garden/base/kustomization.yaml
  pkg/apis/core/types_controllerregistration.go
  pkg/apis/core/v1beta1/types_controllerregistration.go
  pkg/apis/core/validation/controllerregistration.go
  pkg/apis/core/validation/controllerregistration_test.go
  pkg/component/extensions/extension/extension.go
  pkg/component/extensions/extension/extension_test.go
  pkg/component/extensions/extension/filters.go
  pkg/component/extensions/extension/mock/mocks.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/extension.go
  pkg/provider-local/controller/extension/shootafterworker/actuator.go
  pkg/provider-local/controller/extension/shootafterworker/add.go
  skaffold.yaml
  test/e2e/gardener/common.go
Labels: kind/enhancement, size/XL, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#9496 Add main packages to skaffold `ko` dependencies
  hack/check-skaffold-deps-for-binary.sh
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/bug, area/dev-productivity, size/S, cla: yes, lgtm, approved

#9499 FIx dependency-watchdog permissions
  pkg/component/nodemanagement/dependencywatchdog/access.go
  pkg/component/nodemanagement/dependencywatchdog/access_test.go
Labels: kind/bug, area/ops-productivity, area/disaster-recovery, area/quality, size/M, cla: yes, lgtm, approved

#9479 🧹 Cleanup a few `TODOs`
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/controller/controlplane/genericactuator/actuator_test.go
  extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  extensions/pkg/controller/worker/genericactuator/actuator_restore_test.go
  extensions/pkg/webhook/certificates/reconciler.go
  extensions/pkg/webhook/cmd/options.go
  extensions/pkg/webhook/shoot/webhook.go
  extensions/pkg/webhook/shoot/webhook_test.go
  pkg/component/extensions/worker/worker.go
  pkg/component/extensions/worker/worker_test.go
  pkg/component/observability/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
  pkg/nodeagent/controller/operatingsystemconfig/reconciler.go
  pkg/utils/gardener/shootstate/machines.go
  pkg/utils/gardener/shootstate/shootstate.go
  pkg/utils/gardener/shootstate/shootstate_test.go
  test/integration/extensions/webhook/certificates/certificates_test.go
Labels: area/open-source, size/L, kind/cleanup, cla: yes, lgtm, approved

#9440 [GEP-25] Add `NamespacedCloudProfile` API and validations
  docs/api-reference/core.md
  docs/concepts/apiserver.md
  docs/deployment/feature_gates.md
  example/35-namespacedcloudprofile.yaml
  pkg/apis/core/register.go
  pkg/apis/core/types_namespacedcloudprofile.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/register.go
  pkg/apis/core/v1beta1/types_namespacedcloudprofile.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/zz_generated.defaults.go
  pkg/apis/core/validation/namespacedcloudprofile.go
  pkg/apis/core/validation/namespacedcloudprofile_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/features/features.go
  pkg/apiserver/openapi/api_violations.report
  pkg/apiserver/openapi/openapi_generated.go
  pkg/apiserver/plugins.go
  pkg/apiserver/registry/core/namespacedcloudprofile/namespacedcloudprofile_suite_test.go
  pkg/apiserver/registry/core/namespacedcloudprofile/storage/storage.go
  pkg/apiserver/registry/core/namespacedcloudprofile/storage/tableconvertor.go
  pkg/apiserver/registry/core/namespacedcloudprofile/strategy.go
  pkg/apiserver/registry/core/namespacedcloudprofile/strategy_test.go
  pkg/apiserver/registry/core/rest/storage_core.go
  pkg/apiserver/registry/core/shoot/strategy.go
  pkg/apiserver/registry/core/shoot/strategy_test.go
  pkg/client/core/clientset/versioned/typed/core/v1beta1/core_client.go
  pkg/client/core/clientset/versioned/typed/core/v1beta1/fake/fake_core_client.go
  pkg/client/core/clientset/versioned/typed/core/v1beta1/fake/fake_namespacedcloudprofile.go
  pkg/client/core/clientset/versioned/typed/core/v1beta1/generated_expansion.go
  pkg/client/core/clientset/versioned/typed/core/v1beta1/mock/mocks.go
  pkg/client/core/clientset/versioned/typed/core/v1beta1/namespacedcloudprofile.go
  pkg/client/core/informers/externalversions/core/v1beta1/interface.go
  pkg/client/core/informers/externalversions/core/v1beta1/namespacedcloudprofile.go
  pkg/client/core/informers/externalversions/generic.go
  pkg/client/core/listers/core/v1beta1/expansion_generated.go
  pkg/client/core/listers/core/v1beta1/namespacedcloudprofile.go
  pkg/features/features.go
  plugin/pkg/namespacedcloudprofile/validator/admission.go
  plugin/pkg/namespacedcloudprofile/validator/admission_test.go
  plugin/pkg/namespacedcloudprofile/validator/validator_suite_test.go
  plugin/pkg/plugins.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/api-change, area/control-plane, ok-to-test, cla: yes, lgtm, approved, size/XXL, area/ipcei

#9495 Add `rate` to istio mesh dashboard metrics
  pkg/component/observability/plutono/dashboards/seed/istio/istio-mesh-dashboard.json
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#9510 docs: Add yq as a local setup prerequisite
  docs/development/local_setup.md
Labels: kind/enhancement, area/documentation, size/S, ok-to-test, cla: yes, lgtm, approved

#9490 Remove resource-manager's secret reconciler
  charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml
  charts/gardener/resource-manager/values.yaml
  cmd/gardenlet/app/migration.go
  docs/concepts/resource-manager.md
  example/resource-manager/10-componentconfig.yaml
  pkg/resourcemanager/apis/config/types.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults.go
  pkg/resourcemanager/apis/config/v1alpha1/defaults_test.go
  pkg/resourcemanager/apis/config/v1alpha1/types.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/resourcemanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/resourcemanager/apis/config/validation/validation.go
  pkg/resourcemanager/apis/config/validation/validation_test.go
  pkg/resourcemanager/apis/config/zz_generated.deepcopy.go
  pkg/resourcemanager/controller/add.go
  pkg/resourcemanager/controller/secret/add.go
  pkg/resourcemanager/controller/secret/add_test.go
  pkg/resourcemanager/controller/secret/reconciler.go
  pkg/resourcemanager/controller/secret/reconciler_test.go
  pkg/resourcemanager/controller/secret/secret_suite_test.go
  pkg/resourcemanager/predicate/has_finalizer.go
  pkg/resourcemanager/predicate/has_finalizer_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/resourcemanager/secret/secret_suite_test.go
  test/integration/resourcemanager/secret/secret_test.go
Labels: kind/cleanup, cla: yes, lgtm, approved, size/XXL

#9509 Release responsible schedule for v1.94 until v1.102
  docs/development/process.md
Labels: kind/enhancement, area/delivery, size/S, cla: yes, lgtm, approved

#9506 Prepare next Dev Cycle `v1.93.0-dev`
  VERSION
Labels: kind/enhancement, area/delivery, size/XS, cla: yes, lgtm, approved

#9501 🧹 Drop completed TODO
  cmd/gardenlet/app/migration.go
Labels: kind/cleanup, size/S, cla: yes, lgtm, approved

#9260 [GEP-26] Workload Identity - Trust Based Authentication
  docs/README.md
  docs/proposals/26-workload-identity.md
Labels: kind/enhancement, area/security, kind/api-change, size/XL, cla: yes, lgtm, approved

#9520 Add `NamespacedCloudProfileValidator` to admission doc
  docs/concepts/apiserver_admission_plugins.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#9525 Don't depoy vali-specific ClusterOutputs when vali is disabled
  pkg/component/observability/logging/fluentoperator/custom_resources.go
  pkg/component/observability/logging/fluentoperator/fluent_bit.go
  pkg/component/observability/logging/fluentoperator/fluent_bit_test.go
  pkg/component/shared/fluent_bit.go
  pkg/component/shared/fluent_operator_custom_resources.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/bug, size/M, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#9533 Do not append reason to `lastMaintenance.description` if no feature gates or admission plugins are removed
  docs/usage/shoot_versions.md
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler_test.go
Labels: kind/bug, area/quality, size/M, cla: yes, lgtm, approved

#9536 Replace topology labels when `PersistentVolume` has no node affinity
  cmd/gardenlet/app/migration.go
Labels: kind/bug, area/usability, size/S, cla: yes, lgtm, approved

#9544 [release-v1.89] Automated cherry pick of #9536: Replace topology labels when `PersistentVolume` has no node affinity
  cmd/gardenlet/app/app.go
Labels: kind/bug, area/usability, size/S, cla: yes, lgtm, approved

#9489 [GEP-24] Introduce `ShootManagedIssuer` feature gate
  docs/deployment/feature_gates.md
  docs/operations/configuration.md
  example/20-componentconfig-gardenlet.yaml
  example/gardener-local/gardenlet/values.yaml
  pkg/controllermanager/controller/controllerregistration/seed/reconciler.go
  pkg/features/features.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/gardenlet/controller/shoot/care/reconciler.go
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/features/features.go
  pkg/gardenlet/operation/botanist/advertisedaddresses_test.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
  pkg/utils/gardener/garden.go
Labels: kind/enhancement, area/security, area/usability, size/L, cla: yes, lgtm, approved

#9555 Fix kube-apiserver advertise address for ipv6 local setup.
  pkg/gardenlet/operation/botanist/kubeapiserverexposure.go
Labels: kind/bug, size/XS, area/networking, cla: yes, lgtm, approved

#9553 Group istio module updates in one PR
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9559 provider-local: Update machine-controller-manager-provider-local image
  pkg/provider-local/imagevector/images.go
  pkg/provider-local/imagevector/images.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#9564 Use `x.y.0` versions of the Go Toolchain only
  .github/renovate.json5
  go.mod
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#9560 Update Istio to v1.21.1
  go.mod
  go.sum
  imagevector/images.yaml
  pkg/component/networking/istio/charts/istio/istio-crds/templates/crd-all.gen.yaml
  pkg/component/networking/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/component/networking/istio/charts/istio/istio-ingress/values.yaml
  pkg/component/networking/istio/charts/istio/istio-istiod/templates/deployment.yaml
  pkg/component/networking/istio/test_charts/ingress_autoscaler.yaml
  pkg/component/networking/istio/test_charts/ingress_deployment.yaml
  pkg/component/networking/istio/test_charts/ingress_service.yaml
  pkg/component/networking/istio/test_charts/ingress_service_dualstack.yaml
  pkg/component/networking/istio/test_charts/ingress_service_dualstack_etp.yaml
  pkg/component/networking/istio/test_charts/ingress_service_etp_cluster.yaml
  pkg/component/networking/istio/test_charts/ingress_service_etp_local.yaml
  pkg/component/networking/istio/test_charts/ingress_serviceaccount.yaml
  pkg/component/networking/istio/test_charts/istiod_deployment.yaml
Labels: kind/enhancement, area/networking, cla: yes, lgtm, approved, size/XXL

#9526 support proxy protocol on load balancers
  pkg/component/networking/istio/charts/istio/istio-ingress/templates/proxy-protocol-envoyfilter.yaml
  pkg/component/networking/istio/istio_test.go
  pkg/component/networking/istio/test_charts/proxyprotocol_envoyfilter.yaml
  pkg/component/networking/istio/test_charts/proxyprotocol_envoyfilter_sni.yaml
  pkg/component/networking/istio/test_charts/proxyprotocol_envoyfilter_vpn.yaml
Labels: kind/enhancement, size/L, area/networking, cla: yes, lgtm, approved

#9574 Group `prometheus-operator` image updates in one PR
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9569 [release-v1.91] Automated cherry pick of #9564: Use `x.y.0` versions of the Go Toolchain only
  .github/renovate.json5
  go.mod
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#9578 Prevent GNA image tag defaulting with K8s version
  pkg/gardenlet/operation/botanist/operatingsystemconfig.go
Labels: area/usability, kind/regression, size/S, cla: yes, lgtm, approved

#9449 Implement (optional) machine-type dependent resource reservations
  Makefile
  docs/concepts/apiserver_admission_plugins.md
  example/20-admissionconfig.yaml
  hack/update-codegen.sh
  pkg/apis/core/v1beta1/defaults_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot_test.go
  pkg/apiserver/plugins.go
  plugin/pkg/plugins.go
  plugin/pkg/shoot/resourcereservation/admission.go
  plugin/pkg/shoot/resourcereservation/admission_test.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/doc.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/install/install.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/register.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/types.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/defaults.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/doc.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/register.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/types.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/zz_generated.conversion.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/zz_generated.deepcopy.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/v1alpha1/zz_generated.defaults.go
  plugin/pkg/shoot/resourcereservation/apis/shootresourcereservation/zz_generated.deepcopy.go
  plugin/pkg/shoot/resourcereservation/config.go
  plugin/pkg/shoot/resourcereservation/resourcereservation_suite_test.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/robustness, ok-to-test, cla: yes, lgtm, approved, size/XXL

#9588 docs: add missing `resources.gardener.cloud/class` label
  docs/concepts/operator.md
Labels: kind/bug, size/XS, area/documentation, cla: yes, lgtm, approved

#9587 [GEP-19] Allow public network access for Garden Prometheus
  pkg/operator/controller/garden/garden/components.go
Labels: kind/bug, size/XS, area/networking, cla: yes, lgtm, approved

#9590 Fix `minAllowed` of VPA resource for `vpn-seed-server` containers.
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/seedserver/seedserver_test.go
Labels: kind/enhancement, area/robustness, area/networking, size/S, area/auto-scaling, cla: yes, lgtm, approved

#9591 [GEP-19] Support Prometheus PVC migration w/o subpath
  pkg/component/observability/monitoring/migration.go
  pkg/component/observability/monitoring/prometheus/prometheus.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/enhancement, area/usability, size/S, cla: yes, lgtm, approved

#9593 diagnostic log for machinedeployment replicas on change
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
Labels: kind/enhancement, size/XS, area/logging, cla: yes, lgtm, approved

#9595 [GEP-19] Slightly improve the formatting in the Gardener alerts
  pkg/component/observability/monitoring/prometheus/garden/assets/prometheusrules/seed.yaml
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#9596 Fix istio-ingress dashboard
  pkg/component/observability/plutono/dashboards/seed/istio/istio-ingress-gateway-dashboard.json
Labels: kind/bug, size/XS, area/monitoring, area/networking, cla: yes, lgtm, approved

#9605 Set kubeApiserver `maxReplicas: 3`
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
Labels: kind/enhancement, size/S, area/auto-scaling, cla: yes, lgtm, approved

#9594 Prepare next Dev Cycle `v1.94.0-dev`
  VERSION
Labels: kind/enhancement, area/delivery, size/XS, cla: yes, lgtm, approved

#9589 Enhance makefile tools binaries to be system and arch independent
  .ci/verify
  .dockerignore
  .gitignore
  .golangci.yaml.in
  Makefile
  docs/development/testing.md
  hack/tools.mk
  hack/tools/image/Dockerfile
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#9610 Use existing constants for `controller-manager` and `scheduler`
  pkg/component/gardener/controllermanager/controller_manager.go
  pkg/component/gardener/scheduler/scheduler.go
  pkg/component/kubernetes/controllermanager/controllermanager.go
  pkg/component/kubernetes/controllermanager/waiter.go
  pkg/component/kubernetes/scheduler/scheduler.go
Labels: area/dev-productivity, kind/cleanup, size/S, cla: yes, lgtm, approved

#9613 Fix the `backup.gardener.cloud/created-by` annotation not being added on existing etcd-backup Secrets
  extensions/pkg/controller/backupentry/genericactuator/actuator.go
  extensions/pkg/controller/backupentry/genericactuator/actuator_test.go
Labels: kind/bug, area/quality, size/M, cla: yes, lgtm, approved

#9625 Align `pkg/component/observability/logging` structure with `pkg/component/observability/monitoring`
  pkg/component/observability/logging/fluentbit/fluentbit.go
  pkg/component/observability/logging/fluentbit/fluentbit_suite_test.go
  pkg/component/observability/logging/fluentbit/fluentbit_test.go
  pkg/component/observability/logging/fluentbit/testdata/fluent-bit.prometheusrule.test.yaml
  pkg/component/observability/logging/fluentcustomresources/cluster_filters.go
  pkg/component/observability/logging/fluentcustomresources/cluster_filters_test.go
  pkg/component/observability/logging/fluentcustomresources/cluster_inputs.go
  pkg/component/observability/logging/fluentcustomresources/cluster_inputs_test.go
  pkg/component/observability/logging/fluentcustomresources/cluster_outputs.go
  pkg/component/observability/logging/fluentcustomresources/cluster_outputs_test.go
  pkg/component/observability/logging/fluentcustomresources/cluster_parsers.go
  pkg/component/observability/logging/fluentcustomresources/cluster_parsers_test.go
  pkg/component/observability/logging/fluentcustomresources/custom_resources.go
  pkg/component/observability/logging/fluentcustomresources/custom_resources_test.go
  pkg/component/observability/logging/fluentcustomresources/fluentcustomresources_suite_test.go
  pkg/component/observability/logging/fluentoperator/customresources/cluster_fluent_bit_config.go
  pkg/component/observability/logging/fluentoperator/customresources/cluster_fluent_bit_config_test.go
  pkg/component/observability/logging/fluentoperator/customresources/fluent_bit.go
  pkg/component/observability/logging/fluentoperator/customresources/fluent_bit_test.go
  pkg/component/observability/logging/fluentoperator/fluentoperator.go
  pkg/component/shared/fluent_bit.go
  pkg/component/shared/fluent_custom_resources.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/operator/controller/garden/garden/components.go
  skaffold-operator.yaml
  skaffold.yaml
Labels: area/dev-productivity, size/XL, kind/cleanup, cla: yes, lgtm, approved

#9633 change ctr path in deploy-registry
  example/provider-extensions/registry-seed/deploy-registry.sh
Labels: kind/bug, area/dev-productivity, size/S, cla: yes, lgtm, approved

#9632 Drop `Infrastructure Cleanup Wait Period` during shoot deletion
  docs/usage/shoot_cleanup.md
  example/provider-local/managedseeds/shoot-managedseed.yaml
  example/provider-local/shoot-ipv6.yaml
  example/provider-local/shoot.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  test/e2e/gardener/common.go
Labels: area/usability, size/M, kind/cleanup, cla: yes, lgtm, approved

#9644 Only update network policy `allow-to-runtime-apiserver` after resolver has been synced
  pkg/controller/networkpolicy/hostnameresolver/resolver.go
  pkg/controller/networkpolicy/hostnameresolver/resolver_test.go
  pkg/controller/networkpolicy/reconciler.go
Labels: kind/bug, size/S, area/control-plane, cla: yes, lgtm, approved

#9641 Test `AfterWorker` Lifecycle Strategy in Upgrade tests
  test/e2e/gardener/common.go
Labels: kind/cleanup, size/S, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#9653 Minor fixes for the `dashboard` component
  pkg/component/gardener/dashboard/configmaps.go
  pkg/component/gardener/dashboard/dashboard_test.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/bug, size/XS, area/usability, cla: yes, lgtm, approved

#9599 Replace worker node count validation by `max-nodes-total` functionality of `cluster-autoscaler`
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apiserver/registry/core/shoot/strategy.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
  pkg/component/autoscaling/clusterautoscaler/monitoring_test.go
  pkg/gardenlet/operation/botanist/clusterautoscaler.go
  pkg/gardenlet/operation/botanist/clusterautoscaler_test.go
Labels: kind/enhancement, size/L, area/auto-scaling, cla: yes, lgtm, approved

#9606 [GEP-19] Integrate long-term Prometheus deployment into `Garden` controller
  docs/concepts/operator.md
  docs/development/priority-classes.md
  imagevector/images.go
  imagevector/images.yaml
  pkg/component/observability/monitoring/prometheus/component.go
  pkg/component/observability/monitoring/prometheus/cortex.go
  pkg/component/observability/monitoring/prometheus/longterm/assets/prometheusrules/recording.yaml
  pkg/component/observability/monitoring/prometheus/longterm/assets/prometheusrules/sla.yaml
  pkg/component/observability/monitoring/prometheus/longterm/longterm_suite_test.go
  pkg/component/observability/monitoring/prometheus/longterm/prometheusrules.go
  pkg/component/observability/monitoring/prometheus/longterm/prometheusrules_test.go
  pkg/component/observability/monitoring/prometheus/longterm/scrapeconfigs.go
  pkg/component/observability/monitoring/prometheus/longterm/scrapeconfigs_test.go
  pkg/component/observability/monitoring/prometheus/prometheus.go
  pkg/component/observability/monitoring/prometheus/prometheus_test.go
  pkg/component/observability/monitoring/prometheus/service.go
  pkg/component/observability/monitoring/prometheus/vpa.go
  pkg/component/observability/plutono/dashboards/garden/global/container-runtime.json
  pkg/component/observability/plutono/dashboards/garden/global/shoot-sla-dashboard.json
  pkg/component/observability/plutono/dashboards/garden/global/shoot-sli-dashboard.json
  pkg/component/observability/plutono/plutono.go
  pkg/component/observability/plutono/plutono_test.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/garden/garden/reconciler_delete.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  skaffold-operator.yaml
  test/e2e/operator/garden/create_delete.go
  test/integration/operator/garden/garden/garden_test.go
Labels: kind/enhancement, area/dev-productivity, area/monitoring, cla: yes, lgtm, approved, size/XXL

#9650 Use `ingress-nginx` `v1.9.6` for `1.25.x` Shoots
  imagevector/images.yaml
Labels: kind/enhancement, area/open-source, size/S, cla: yes, lgtm, approved

#9640 Validate that containers run as `non-root`
  charts/gardener/gardenlet/templates/deployment.yaml
  pkg/component/kubernetes/dashboard/dashboard.go
  pkg/component/kubernetes/dashboard/dashboard_test.go
  pkg/component/networking/nginxingress/nginxingress.go
  pkg/component/networking/nginxingress/nginxingress_test.go
  pkg/component/observability/logging/fluentoperator/fluentoperator.go
  pkg/component/observability/logging/fluentoperator/fluentoperator_test.go
  pkg/component/observability/monitoring/blackboxexporter/blackboxexporter.go
  pkg/component/observability/monitoring/blackboxexporter/blackboxexporter_test.go
  pkg/component/observability/monitoring/metricsserver/metricsserver.go
  pkg/component/observability/monitoring/metricsserver/metricsserver_test.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
Labels: kind/enhancement, area/security, area/quality, size/M, cla: yes, lgtm, approved

#9658 Enable `gardener-operator` to reconcile shoot-specific `NetworkPolicy`s
  charts/gardener/operator/templates/clusterrole.yaml
  pkg/operator/client/scheme.go
Labels: kind/bug, area/usability, size/S, cla: yes, lgtm, approved

#9657 Prefer SNI hostname for dashboard API server URL
  pkg/component/gardener/dashboard/config/config.go
  pkg/component/gardener/dashboard/configmaps.go
  pkg/component/gardener/dashboard/dashboard.go
  pkg/component/gardener/dashboard/dashboard_test.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
Labels: kind/bug, area/usability, size/M, cla: yes, lgtm, approved

#9624 [GEP-19] Add sidecar to Plutono for fetching dashboard `ConfigMap`s dynamically
  docs/concepts/operator.md
  docs/extensions/logging-and-monitoring.md
  imagevector/images.go
  imagevector/images.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/observability/plutono/dashboards/garden/alerts-dashboard.json
  pkg/component/observability/plutono/dashboards/garden/container-runtime.json
  pkg/component/observability/plutono/dashboards/garden/garden-alertmanager-dashboard.json
  pkg/component/observability/plutono/dashboards/garden/garden-availability-dashboard.json
  pkg/component/observability/plutono/dashboards/garden/gardener-admission-controller-dashboard.json
  pkg/component/observability/plutono/dashboards/garden/gardener-admission-controller-seedauthorizer-details.json
  pkg/component/observability/plutono/dashboards/garden/gardener-controlplane.json
  pkg/component/observability/plutono/dashboards/garden/kubernetes-pods-dashboard.json
  pkg/component/observability/plutono/dashboards/garden/seed-resource-usage-dashboard.json
  pkg/component/observability/plutono/dashboards/garden/shoot-availability-dashboard.json
  pkg/component/observability/plutono/dashboards/garden/shoot-details-dashboard.json
  pkg/component/observability/plutono/dashboards/garden/shoot-sla-dashboard.json
  pkg/component/observability/plutono/dashboards/garden/shoot-sli-dashboard.json
  pkg/component/observability/plutono/dashboards/garden/virtual-garden-etcd-backup-dashboard.json
  pkg/component/observability/plutono/dashboards/garden/virtual-garden-etcd-dashboard.json
  pkg/component/observability/plutono/plutono.go
  pkg/component/observability/plutono/plutono_suite_test.go
  pkg/component/observability/plutono/plutono_test.go
  pkg/component/shared/plutono.go
Labels: kind/enhancement, size/XL, area/monitoring, cla: yes, lgtm, approved

#9661 Cleanup some no longer needed pointer functions
  pkg/apis/core/v1beta1/helper/helper_test.go
  pkg/apis/core/validation/controllerregistration_test.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/validation/utils_test.go
  pkg/apis/operator/v1alpha1/helper/helper_test.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
  pkg/component/autoscaling/hvpa/hvpa.go
  pkg/component/autoscaling/vpa/admissioncontroller.go
  pkg/component/autoscaling/vpa/general.go
  pkg/component/autoscaling/vpa/recommender.go
  pkg/component/etcd/etcd/bootstrap.go
  pkg/component/etcd/etcd/etcd.go
  pkg/component/gardener/admissioncontroller/admission_controller_test.go
  pkg/component/gardener/admissioncontroller/poddisruptionbudget.go
  pkg/component/gardener/admissioncontroller/service.go
  pkg/component/gardener/apiserver/apiserver_test.go
  pkg/component/gardener/apiserver/deployment.go
  pkg/component/gardener/apiserver/poddisruptionbudget.go
  pkg/component/gardener/apiserver/service.go
  pkg/component/gardener/controllermanager/controller_manager_test.go
  pkg/component/gardener/controllermanager/poddisruptionbudget.go
  pkg/component/gardener/dashboard/dashboard_test.go
  pkg/component/gardener/dashboard/poddisruptionbudget.go
  pkg/component/gardener/resourcemanager/resource_manager.go
  pkg/component/gardener/scheduler/poddisruptionbudget.go
  pkg/component/gardener/scheduler/scheduler_test.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/poddisruptionbudget.go
  pkg/component/kubernetes/apiserverexposure/service.go
  pkg/component/kubernetes/controllermanager/controllermanager.go
  pkg/component/kubernetes/scheduler/scheduler.go
  pkg/component/networking/coredns/coredns.go
  pkg/component/networking/nginxingress/nginxingress.go
  pkg/component/networking/vpn/authzserver/authzserver.go
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/shoot/shoot.go
  pkg/component/nodemanagement/dependencywatchdog/bootstrap.go
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager_test.go
  pkg/component/observability/logging/vali/vali.go
  pkg/component/observability/monitoring/alertmanager/alertmanager_test.go
  pkg/component/observability/monitoring/alertmanager/poddisruptionbudget.go
  pkg/component/observability/monitoring/blackboxexporter/blackboxexporter.go
  pkg/component/observability/monitoring/kubestatemetrics/resources.go
  pkg/component/observability/monitoring/metricsserver/metricsserver.go
  pkg/component/observability/monitoring/prometheus/cache/networkpolicy.go
  pkg/component/observability/monitoring/prometheus/cache/networkpolicy_test.go
  pkg/component/observability/monitoring/prometheus/poddisruptionbudget.go
  pkg/component/observability/monitoring/prometheus/prometheus_test.go
  pkg/component/observability/monitoring/prometheus/service.go
  pkg/controller/networkpolicy/reconciler.go
  pkg/provider-local/controller/networkpolicy/reconciler.go
  pkg/utils/gardener/networkpolicy_test.go
  pkg/utils/miscellaneous.go
  pkg/utils/miscellaneous_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#9651 Wait until extensions are deleted before deleting `Extension` resources
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
Labels: kind/bug, size/XS, area/control-plane-migration, cla: yes, lgtm, approved

#9659 Allow configuration of pod labels for `provider-local` via Helm chart
  charts/gardener/provider-local/templates/deployment.yaml
  charts/gardener/provider-local/values.yaml
  example/provider-local/garden/base/controller-registration.yaml
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#9630 [node-agent] Delete leftover `*.tmp` files from failed copy attempts
  pkg/nodeagent/files/files.go
  pkg/nodeagent/files/files_test.go
Labels: kind/enhancement, area/robustness, size/S, cla: yes, lgtm, approved

#9669 Run gardenlet as `nonroot` user and group `65532`
  Dockerfile
  charts/gardener/gardenlet/templates/deployment.yaml
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
Labels: kind/bug, kind/enhancement, area/security, size/XS, area/quality, cla: yes, lgtm, approved

#9646 [operator] Manage Dashboard Web Terminal Controller Manager
  docs/concepts/operator.md
  docs/development/priority-classes.md
  go.mod
  go.sum
  hack/generate-crds.sh
  imagevector/images.go
  imagevector/images.yaml
  pkg/component/gardener/dashboard/configmap.go
  pkg/component/gardener/dashboard/dashboard_test.go
  pkg/component/gardener/dashboard/terminal/assets/crd-dashboard.gardener.cloud_terminals.yaml
  pkg/component/gardener/dashboard/terminal/assets/doc.go
  pkg/component/gardener/dashboard/terminal/configmap.go
  pkg/component/gardener/dashboard/terminal/crd.go
  pkg/component/gardener/dashboard/terminal/deployment.go
  pkg/component/gardener/dashboard/terminal/poddisruptionbudget.go
  pkg/component/gardener/dashboard/terminal/rbac.go
  pkg/component/gardener/dashboard/terminal/secrets.go
  pkg/component/gardener/dashboard/terminal/service.go
  pkg/component/gardener/dashboard/terminal/servicemonitor.go
  pkg/component/gardener/dashboard/terminal/terminal.go
  pkg/component/gardener/dashboard/terminal/terminal_suite_test.go
  pkg/component/gardener/dashboard/terminal/terminal_test.go
  pkg/component/gardener/dashboard/terminal/vpa.go
  pkg/component/gardener/dashboard/terminal/webhookconfigurations.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/garden/garden/reconciler_delete.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  skaffold-operator.yaml
  test/e2e/operator/garden/common.go
  test/e2e/operator/garden/create_delete.go
  test/integration/operator/garden/garden/garden_test.go
Labels: kind/enhancement, area/usability, cla: yes, lgtm, approved, size/XXL

#9673 Remove mention of auditlog components from doc
  docs/development/priority-classes.md
Labels: size/XS, kind/cleanup, area/audit-logging, cla: yes, lgtm, approved

#8984 Introduce new feature gate `VPAForETCD` to use VPA for etcd autoscaling
  charts/gardener/gardenlet/templates/helpers.tpl
  charts/gardener/gardenlet/values.yaml
  charts/gardener/operator/templates/_helpers.tpl
  charts/gardener/operator/values.yaml
  docs/concepts/gardenlet.md
  docs/concepts/operator.md
  docs/deployment/feature_gates.md
  example/20-componentconfig-gardenlet.yaml
  example/operator/10-componentconfig.yaml
  example/seed-crds/10-crd-autoscaling.k8s.io_verticalpodautoscalers.yaml
  go.mod
  go.sum
  imagevector/images.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/component/autoscaling/vpa/templates/crd-autoscaling.k8s.io_verticalpodautoscalers.yaml
  pkg/component/etcd/etcd/etcd.go
  pkg/component/etcd/etcd/etcd_test.go
  pkg/component/etcd/etcd/mock/mocks.go
  pkg/component/etcd/etcd/waiter_test.go
  pkg/controller/vpaevictionrequirements/add.go
  pkg/controller/vpaevictionrequirements/reconciler.go
  pkg/controller/vpaevictionrequirements/reconciler_test.go
  pkg/controller/vpaevictionrequirements/vpaevictionrequirements_suite_test.go
  pkg/features/features.go
  pkg/gardenlet/apis/config/types.go
  pkg/gardenlet/apis/config/v1alpha1/defaults.go
  pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/managedseed/charttest/charttest.go
  pkg/gardenlet/controller/managedseed/charttest/gardenlet_chart_test.go
  pkg/gardenlet/controller/vpaevictionrequirements/add.go
  pkg/gardenlet/features/features.go
  pkg/gardenlet/operation/botanist/etcd.go
  pkg/gardenlet/operation/botanist/etcd_test.go
  pkg/operator/apis/config/types.go
  pkg/operator/apis/config/v1alpha1/types.go
  pkg/operator/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/operator/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/apis/config/zz_generated.deepcopy.go
  pkg/operator/controller/add.go
  pkg/operator/controller/controllerregistrar/add.go
  pkg/operator/controller/controllerregistrar/controllerregistrar_suite_test.go
  pkg/operator/controller/controllerregistrar/reconciler.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/networkpolicyregistrar/reconciler.go
  pkg/operator/features/features.go
  pkg/utils/timewindow/timewindow.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/gardenlet/vpaevictionrequirements/vpaevictionrequirements_suite_test.go
  test/integration/gardenlet/vpaevictionrequirements/vpaevictionrequirements_test.go
Labels: kind/enhancement, area/control-plane, area/auto-scaling, cla: yes, lgtm, approved, size/XXL

#9676 make repo reuse compliant
  .reuse/dep5
  LICENSE
  LICENSE.md
  LICENSES/Apache-2.0.txt
  LICENSES/CC-BY-4.0.txt
  LICENSES/MIT.txt
  README.md
  SECURITY.md
  pkg/admissioncontroller/webhook/auth/seed/attributes.go
  pkg/admissioncontroller/webhook/auth/seed/graph/doc.go
  pkg/controllermanager/controller/certificatesigningrequest/reconciler.go
  pkg/gardenlet/bootstrap/certificate/certificate_util.go
  pkg/gardenlet/operation/botanist/matchers/rule_matcher.go
  pkg/resourcemanager/controller/node/helper/daemon_controller.go
  pkg/utils/validation/kubernetes/core/helpers.go
  pkg/utils/validation/kubernetes/core/validation.go
  pkg/utils/validation/kubernetes/core/validation_test.go
  test/envtest/port.go
  test/framework/cleanup.go
Labels: kind/cleanup, area/compliance, cla: yes, lgtm, approved, size/XXL

#9679 Fix various typos in markdown files
  docs/concepts/controller-manager.md
  docs/concepts/gardenlet.md
  docs/concepts/node-agent.md
  docs/concepts/scheduler.md
  docs/deployment/authentication_gardener_control_plane.md
  docs/deployment/deploy_gardenlet.md
  docs/deployment/secret_binding_provider_controller.md
  docs/development/component-checklist.md
  docs/development/dependencies.md
  docs/development/high-availability.md
  docs/development/monitoring-stack.md
  docs/development/new-cloud-provider.md
  docs/development/testing.md
  docs/extensions/logging-and-monitoring.md
  docs/operations/seed_settings.md
  docs/proposals/26-workload-identity.md
  docs/proposals/README.md
  docs/usage/shoot_autoscaling.md
  docs/usage/shoot_cleanup.md
  docs/usage/shoot_maintenance.md
Labels: area/documentation, size/M, kind/cleanup, cla: yes, lgtm, approved

#9643 [GEP-23] Add "Resource usage by container" dashboard to garden/plutono
  pkg/component/observability/plutono/dashboards/garden/resource-usage-by-container.json
  pkg/component/observability/plutono/plutono_test.go
Labels: kind/enhancement, size/XL, area/monitoring, cla: yes, lgtm, approved

#9681 Delete orphaned vali VPAs
  cmd/gardenlet/app/migration.go
Labels: kind/bug, size/M, area/logging, cla: yes, lgtm, approved

#9683 No longer make Plutono dashboard `ConfigMap` unique
  pkg/component/observability/plutono/plutono.go
  pkg/component/observability/plutono/plutono_test.go
Labels: kind/bug, size/M, area/monitoring, cla: yes, lgtm, approved

#9687 Prepare next Dev Cycle v1.95.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#9690 Switch from `purpose` to `is_seed` for Seed alerts
  pkg/component/observability/monitoring/prometheus/garden/assets/prometheusrules/seed.yaml
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved

#9684 Update `MCM` metrics scraped by prometheus.
  pkg/component/nodemanagement/machinecontrollermanager/monitoring.go
  pkg/component/nodemanagement/machinecontrollermanager/monitoring_test.go
Labels: kind/enhancement, size/L, area/monitoring, cla: yes, lgtm, approved

#9680 `Shoot` Deletion with 👀+👀 Principle
  docs/api-reference/core.md
  docs/concepts/apiserver_admission_plugins.md
  docs/usage/projects.md
  example/05-project-dev.yaml
  pkg/apis/core/types_project.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_project.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/project.go
  pkg/apis/core/validation/project_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/api_violations.report
  pkg/apiserver/openapi/openapi_generated.go
  pkg/component/extensions/backupentry/backupentry_test.go
  pkg/component/extensions/containerruntime/containerruntime_test.go
  pkg/component/extensions/infrastructure/infrastructure_test.go
  pkg/component/extensions/network/network_test.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/controllermanager/controller/managedseedset/replica.go
  pkg/controllermanager/controller/managedseedset/replica_test.go
  pkg/controllermanager/controller/project/stale/reconciler_test.go
  pkg/provider-local/controller/ingress/reconciler.go
  pkg/resourcemanager/webhook/crddeletionprotection/handler_test.go
  pkg/utils/gardener/deletion_confirmation.go
  pkg/utils/gardener/deletion_confirmation_test.go
  plugin/pkg/global/deletionconfirmation/admission.go
  plugin/pkg/global/deletionconfirmation/admission_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  test/framework/gardener_utils.go
  test/integration/resourcemanager/crddeletionprotection/crddeletionprotection_test.go
Labels: kind/enhancement, area/ops-productivity, cla: yes, lgtm, approved, size/XXL

#9686 Enable access log in istio ingress gateway for apiserver-proxy connections
  pkg/component/kubernetes/apiserverexposure/templates/envoyfilter.yaml
Labels: kind/enhancement, area/networking, size/S, cla: yes, lgtm, approved
