Repository gardener/gardener, pull requests merged in 2025-04, with the labels that each got.

#11768 Revert "Promote feature gate RemoveAPIServerProxyLegacyPort to beta (#11734)"
  docs/deployment/feature_gates.md
  example/gardener-local/gardenlet/values.yaml
  pkg/features/features.go
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#11789 Fix provider-extensions setup
  example/gardener-local/gardenlet/values-provider-extensions.yaml
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#11793 Only set static pod path in `kubelet` config for control plane worker pools
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
Labels: kind/enhancement, area/usability, size/S, cla: yes, lgtm, approved

#11794 Fix the Shoot logging TM test
  test/framework/resources/templates/logger-app.yaml.tpl
  test/framework/resources/templates/vpntunnel.yaml.tpl
Labels: kind/regression, size/S, area/testing, cla: yes, lgtm, approved

#11795 Prepare next Dev Cycle v1.117.0-dev
  VERSION
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#11788 Improve logging documentation
  docs/development/logging.md
  docs/usage/observability/logging.md
Labels: area/documentation, size/L, kind/cleanup, cla: yes, lgtm, approved

#11800 Fix the `should copy data to pod` VPN tunnel TM test
  test/framework/k8s_utils.go
  test/framework/resources/templates/simple-load-deployment.yaml.tpl
  test/framework/resources/templates/vpntunnel-copy.yaml.tpl
  test/testmachinery/shoots/vpntunnel/vpntunnel.go
Labels: kind/regression, size/S, area/testing, cla: yes, lgtm, approved

#11780 [resource-manager] Prevent infinite `NetworkPolicy` controller failures when the computed pod label selector has keys exceeding 63 characters
  pkg/resourcemanager/controller/networkpolicy/add.go
  pkg/resourcemanager/controller/networkpolicy/reconciler.go
  test/integration/resourcemanager/networkpolicy/networkpolicy_suite_test.go
  test/integration/resourcemanager/networkpolicy/networkpolicy_test.go
  test/utils/namespacefinalizer/namespacefinalizer.go
Labels: kind/bug, area/usability, size/L, cla: yes, lgtm, approved

#11810 Make the deployment of the source `BackupEntry` dependant on the deployment of the `Shoot`'s control plane namespace
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
Labels: kind/bug, size/XS, area/control-plane-migration, cla: yes, lgtm, approved

#11773 🧹 Cleanup a few `TODO`s
  cmd/gardener-controller-manager/app/app.go
  cmd/gardenlet/app/app.go
  extensions/pkg/controller/operatingsystemconfig/reconciler.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/managedseed/add.go
  pkg/gardenlet/controller/managedseed/add_test.go
  skaffold.yaml
  test/integration/gardenlet/managedseed/managedseed_suite_test.go
Labels: area/dev-productivity, size/XL, kind/cleanup, cla: yes, lgtm, approved

#11819 Fix malformed file path error on `go get github.com/gardener/gardener@v1.116.0`
  Makefile
  hack/check-file-names.sh
  pkg/provider-local/node/Dockerfile
  pkg/provider-local/node/containerd/garden.local.gardener.cloud_5001/hosts.toml
Labels: area/dev-productivity, size/M, kind/impediment, cla: yes, lgtm, approved

#11817 Add /run/udev/data to the node exporter configuration
  pkg/component/observability/monitoring/nodeexporter/nodeexporter.go
  pkg/component/observability/monitoring/nodeexporter/nodeexporter_test.go
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#11781 docs: Add conformance test badges for Kubernetes v1.32
  README.md
Labels: area/documentation, area/open-source, kind/task, size/S, cla: yes, lgtm, approved

#11747 Remove `removeContainerdInit` tagged to be dropped with `v1.114`
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/initializer.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/initializer_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/containerd/templates/scripts/init.sh
  pkg/component/extensions/operatingsystemconfig/original/original.go
  pkg/component/extensions/operatingsystemconfig/original/original_test.go
  pkg/nodeagent/controller/operatingsystemconfig/changes.go
  skaffold-gardenadm.yaml
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/nodeagent/operatingsystemconfig/operatingsystemconfig_test.go
Labels: area/quality, size/L, kind/cleanup, cla: yes, lgtm, approved

#11754 Minimize wildcards in RBAC roles
  charts/gardener/controlplane/charts/application/templates/clusterrole-apiserver.yaml
  charts/gardener/controlplane/charts/application/templates/clusterrole-controller-manager.yaml
  charts/gardener/controlplane/charts/application/templates/clusterrole-scheduler.yaml
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
  pkg/component/garden/system/virtual/virtual.go
  pkg/component/garden/system/virtual/virtual_test.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/shoot_resources.go
Labels: kind/enhancement, area/security, size/L, area/compliance, cla: yes, lgtm, approved

#11802 Cleanup `service-account` token invalidation handling for KCM controllers
  docs/development/new-kubernetes-version.md
  hack/compare-k8s-controllers.sh
  pkg/component/shoot/system/system.go
  pkg/component/shoot/system/system_test.go
Labels: size/L, kind/cleanup, cla: yes, lgtm, approved

#11774 Update VPA to 1.3.0
  example/seed-crds/10-crd-autoscaling.k8s.io_verticalpodautoscalercheckpoints.yaml
  example/seed-crds/10-crd-autoscaling.k8s.io_verticalpodautoscalers.yaml
  go.mod
  go.sum
  hack/generate-crds.sh
  imagevector/containers.yaml
  pkg/component/autoscaling/vpa/recommender.go
  pkg/component/autoscaling/vpa/templates/crd-autoscaling.k8s.io_verticalpodautoscalercheckpoints.yaml
  pkg/component/autoscaling/vpa/templates/crd-autoscaling.k8s.io_verticalpodautoscalers.yaml
  pkg/component/autoscaling/vpa/templates/doc.go
  pkg/component/autoscaling/vpa/vpa_test.go
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#11796 Add ability to increase `maxNodesTotal` limit in `NamespacedCloudProfile`
  docs/api-reference/core.md
  docs/usage/project/namespaced-cloud-profiles.md
  docs/usage/shoot/shoot_limits.md
  pkg/apis/core/types_namespacedcloudprofile.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_namespacedcloudprofile.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/controllermanager/controller/namespacedcloudprofile/reconciler.go
  pkg/controllermanager/controller/namespacedcloudprofile/reconciler_test.go
  plugin/pkg/global/customverbauthorizer/admission.go
  plugin/pkg/global/customverbauthorizer/admission_test.go
  plugin/pkg/namespacedcloudprofile/validator/admission.go
  plugin/pkg/namespacedcloudprofile/validator/admission_test.go
  test/integration/controllermanager/namespacedcloudprofile/namespacedcloudprofile_test.go
  test/integration/controllermanager/project/project/project_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#11832 Overwrite existing cloud provider secret data when using workload identity config
  pkg/gardenlet/operation/botanist/secrets_test.go
  pkg/utils/workloadidentity/secret.go
  pkg/utils/workloadidentity/secret_test.go
Labels: kind/bug, area/security, size/M, cla: yes, lgtm, approved, area/ipcei, ipcei/workload-identity

#11839 Switch Slack references to Gardener workspace
  .github/ISSUE_TEMPLATE/support.md
  README.md
  extensions/README.md
Labels: kind/enhancement, area/open-source, size/S, cla: yes, lgtm, approved

#11801 Enhance extension documentation
  docs/README.md
  docs/concepts/controller-manager.md
  docs/concepts/operator.md
  docs/deployment/setup_gardener.md
  docs/extensions/controllerregistration.md
  docs/extensions/conventions.md
  docs/extensions/garden-api-access.md
  docs/extensions/overview.md
  docs/extensions/provider-local.md
  docs/extensions/registration.md
  docs/extensions/resources/extension.md
Labels: kind/enhancement, size/XL, area/documentation, cla: yes, lgtm, approved

#11846 Install setup-envtest from release downloads
  .github/renovate.json5
  go.mod
  go.sum
  hack/tools.go
  hack/tools.mk
Labels: area/dev-productivity, kind/cleanup, size/S, cla: yes, lgtm, approved

#11562 e2e: Refactor `Create Rotate Delete Shoot` test to ordered containers
  test/e2e/gardener/shoot/common.go
  test/e2e/gardener/shoot/create_rotate_delete.go
  test/e2e/gardener/shoot/internal/rotation/certificate_authorities.go
  test/e2e/gardener/shoot/internal/rotation/shoot_access.go
  test/e2e/gardener/shoot/internal/rotation/ssh_keypair.go
  test/e2e/operation.go
  test/e2e/operator/garden/create_rotate_delete.go
  test/utils/rotation/etcd_encryption_key.go
  test/utils/rotation/service_account_key.go
  test/utils/rotation/verifier.go
Labels: kind/enhancement, area/dev-productivity, cla: yes, lgtm, approved, size/XXL

#11828 Add capability matching rules to GEP-33
  docs/proposals/33-machine-image-capabilities.md
Labels: kind/discussion, area/documentation, size/M, cla: yes, lgtm, approved

#11855 Add network policy label when deploying gardenlet
  docs/deployment/deploy_gardenlet_via_operator.md
  example/gardener-local/gardenlet/operator/gardenlet.yaml
  pkg/controller/gardenletdeployer/actuator.go
  pkg/controller/gardenletdeployer/actuator_test.go
  skaffold-operator.yaml
Labels: kind/enhancement, area/ops-productivity, area/usability, size/L, cla: yes, lgtm, approved

#11582 feat: Allow CIDR overlap for non-HA VPN shoots
  docs/usage/networking/shoot_networking.md
  imagevector/containers.yaml
  pkg/apis/core/helper/shoot.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/helper/shoot.go
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/seedserver/seedserver_test.go
  pkg/component/networking/vpn/seedserver/templates/envoy.yaml.tpl
  pkg/component/networking/vpn/shoot/mock/doc.go
  pkg/component/networking/vpn/shoot/mock/mocks.go
  pkg/component/networking/vpn/shoot/shoot.go
  pkg/component/networking/vpn/shoot/shoot_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/vpnseedserver.go
  pkg/gardenlet/operation/botanist/vpnseedserver_test.go
  pkg/gardenlet/operation/botanist/vpnshoot.go
  pkg/gardenlet/operation/botanist/vpnshoot_test.go
  pkg/gardenlet/operation/shoot/shoot.go
  pkg/gardenlet/operation/shoot/types.go
  pkg/scheduler/controller/shoot/reconciler.go
  pkg/scheduler/controller/shoot/reconciler_test.go
  pkg/utils/net/ipnet.go
  pkg/utils/net/ipnet_test.go
  pkg/utils/validation/cidr/disjoint.go
  pkg/utils/validation/cidr/disjoint_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  skaffold-gardenadm.yaml
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/enhancement, area/networking, cla: yes, lgtm, approved, size/XXL

#11779 Add `CheckNodesScaling`
  pkg/gardenlet/controller/shoot/care/health.go
  pkg/gardenlet/controller/shoot/care/health_test.go
Labels: kind/enhancement, size/XL, area/quality, cla: yes, lgtm, approved

#11824 Add `Extension` update validation
  docs/concepts/operator.md
  pkg/apis/core/validation/controllerregistration.go
  pkg/apis/core/validation/controllerregistration_test.go
  pkg/apis/operator/v1alpha1/validation/extension.go
  pkg/apis/operator/v1alpha1/validation/extension_test.go
  pkg/apis/operator/v1alpha1/validation/garden.go
  pkg/apis/operator/v1alpha1/validation/garden_test.go
  pkg/operator/webhook/add.go
  pkg/operator/webhook/defaulting/extension/handler.go
  pkg/operator/webhook/defaulting/extension/handler_test.go
  pkg/operator/webhook/validation/extension/handler.go
  pkg/operator/webhook/validation/extension/handler_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#11771 Enhance Etcd Compaction Job Monitoring with Detailed Failure Reasons
  pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go
  pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules_test.go
  pkg/component/observability/plutono/dashboards/shoot/owners/etcd-compaction-job-dashboard.json
Labels: kind/enhancement, size/L, area/monitoring, area/control-plane, cla: yes, lgtm, approved

#11866 Increase CPU requests of istio-ingress gateway when `IstioTLSTermination` feature gate is enabled
  pkg/component/networking/istio/charts/istio/istio-ingress/templates/deployment.yaml
  pkg/component/networking/istio/charts/istio/istio-ingress/values.yaml
  pkg/component/networking/istio/ingress_gateway.go
  pkg/component/networking/istio/istio_test.go
  pkg/component/networking/istio/test_charts/ingress_deployment.yaml
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#11769 [operator] Introduce extension care controller
  docs/concepts/operator.md
  example/operator/10-componentconfig.yaml
  pkg/apis/operator/v1alpha1/helper/extension.go
  pkg/apis/operator/v1alpha1/helper/extension_test.go
  pkg/apis/operator/v1alpha1/types_extension.go
  pkg/apis/operator/v1alpha1/validation/garden.go
  pkg/operator/apis/config/v1alpha1/defaults.go
  pkg/operator/apis/config/v1alpha1/defaults_test.go
  pkg/operator/apis/config/v1alpha1/types.go
  pkg/operator/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/operator/controller/add.go
  pkg/operator/controller/extension/care/add.go
  pkg/operator/controller/extension/care/add_test.go
  pkg/operator/controller/extension/care/care_suite_test.go
  pkg/operator/controller/extension/care/health.go
  pkg/operator/controller/extension/care/health_test.go
  pkg/operator/controller/extension/care/reconciler.go
  pkg/operator/controller/extension/care/types.go
  pkg/operator/controller/extension/extension/admission/admission.go
  pkg/operator/controller/extension/extension/reconciler.go
  pkg/operator/controller/extension/extension/reconciler_delete.go
  pkg/operator/controller/extension/extension/reconciler_reconcile.go
  pkg/operator/controller/extension/extension/runtime/runtime.go
  pkg/operator/controller/extension/required/runtime/add.go
  pkg/operator/controller/extension/required/runtime/reconciler.go
  pkg/operator/controller/extension/required/virtual/add.go
  pkg/operator/controller/extension/required/virtual/add_test.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  pkg/operator/controller/virtual/add.go
  pkg/operator/mapper/extension.go
  pkg/operator/mapper/extension_test.go
  pkg/operator/mapper/mapper_suite_test.go
  pkg/utils/gardener/garden.go
  pkg/utils/gardener/garden_test.go
  pkg/utils/gardener/operator/extension.go
  pkg/utils/gardener/operator/extension_test.go
  pkg/utils/gardener/operator/garden.go
  pkg/utils/gardener/operator/garden_status.go
  pkg/utils/gardener/operator/garden_status_test.go
  pkg/utils/gardener/operator/garden_test.go
  pkg/utils/gardener/operator/operator_suite_test.go
  pkg/utils/kubernetes/health/checker/checker.go
  pkg/utils/kubernetes/health/checker/checker_test.go
  pkg/utils/miscellaneous_test.go
  skaffold-gardenadm.yaml
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/operator/extension/care/care_suite_test.go
  test/integration/operator/extension/care/care_test.go
Labels: kind/enhancement, area/ops-productivity, cla: yes, lgtm, approved, size/XXL

#11879 Increase MCM processing throughput
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager_test.go
Labels: kind/enhancement, area/performance, size/XS, cla: yes, lgtm, approved

#11872 chore: Prepare next dev cycle v1.118.0-dev
  VERSION
Labels: area/delivery, size/XS, kind/task, cla: yes, lgtm, approved

#11809 Add optional virtualCapacity field to extensions/NodeTemplate on WorkerConfig
  docs/api-reference/extensions.md
  docs/extensions/resources/worker.md
  example/seed-crds/10-crd-extensions.gardener.cloud_workers.yaml
  pkg/apis/extensions/v1alpha1/types_worker.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_workers.yaml
Labels: kind/enhancement, size/M, area/auto-scaling, cla: yes, lgtm, approved

#11874 [GEP-30] Adapt RemoveAPIServerProxyLegacyPort feature gate validation
  cmd/gardenlet/app/migration.go
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#11583 [GEP-26] Use WorkloadIdentity for ETCD backup - part 1
  docs/api-reference/core.md
  docs/concepts/apiserver-admission-plugins.md
  docs/deployment/deploy_gardenlet_manually.md
  docs/deployment/deploy_gardenlet_via_operator.md
  example/50-seed.yaml
  example/gardener-local/gardenlet/operator/gardenlet.yaml
  example/gardener-local/gardenlet/values.yaml
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler.go
  pkg/admissioncontroller/webhook/admission/seedrestriction/handler_test.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_gardenlet.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_managedseed.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_seed.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
  pkg/apis/core/types_seed.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/seed.go
  pkg/apis/core/v1beta1/helper/seed_test.go
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/secretbinding.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
  pkg/apis/core/validation/utils.go
  pkg/apis/core/validation/utils_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/security/validation/credentialsbinding.go
  pkg/apis/security/validation/credentialsbinding_test.go
  pkg/apis/seedmanagement/v1alpha1/defaults_gardenlet_test.go
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseed.go
  pkg/apis/seedmanagement/v1alpha1/defaults_managedseed_test.go
  pkg/apis/seedmanagement/validation/gardenlet_test.go
  pkg/apis/seedmanagement/validation/managedseed_test.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/apiserver/registry/core/seed/storage/storage.go
  pkg/apiserver/registry/core/seed/strategy.go
  pkg/apiserver/registry/core/seed/strategy_test.go
  pkg/apiserver/registry/seedmanagement/gardenlet/storage/storage.go
  pkg/apiserver/registry/seedmanagement/gardenlet/strategy.go
  pkg/apiserver/registry/seedmanagement/internal/utils/utils.go
  pkg/apiserver/registry/seedmanagement/managedseed/storage/storage.go
  pkg/apiserver/registry/seedmanagement/managedseed/strategy.go
  pkg/controller/gardenletdeployer/actuator.go
  pkg/controller/gardenletdeployer/actuator_test.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operator/controller/gardenlet/reconciler.go
  pkg/utils/kubernetes/secretref.go
  pkg/utils/kubernetes/secretref_test.go
  plugin/pkg/seed/validator/admission.go
  plugin/pkg/seed/validator/admission_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/gardenlet/managedseed/managedseed_test.go
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL, area/ipcei

#11873 chore: Remove deprecated containerd localhost config
  hack/kind-up.sh
Labels: area/dev-productivity, size/XS, kind/task, kind/cleanup, cla: yes, lgtm, approved

#11618 e2e: `Refactor Create Rotate Delete Garden` test to ordered containers
  test/e2e/operator/garden/common.go
  test/e2e/operator/garden/create_rotate_delete.go
  test/e2e/operator/garden/internal/garden.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#11692 Enable migration from single-stack IPv4 to dual-stack IPv4, IPv6.
  docs/README.md
  docs/api-reference/extensions.md
  docs/extensions/resources/network.md
  docs/usage/networking/dual-stack-networking-migration.md
  example/seed-crds/10-crd-extensions.gardener.cloud_networks.yaml
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/extensions/v1alpha1/types_network.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/extensions/validation/network.go
  pkg/apis/extensions/validation/network_test.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_networks.yaml
  pkg/component/extensions/network/mock/mocks.go
  pkg/component/extensions/network/network.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/dualstackmigration.go
  pkg/gardenlet/operation/botanist/dualstackmigration_test.go
  pkg/gardenlet/operation/shoot/shoot.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, size/XL, area/networking, cla: yes, lgtm, approved

#11863 e2e: Refactor `renew_gardenlet_kubeconfig` test to ordered containers
  test/e2e/gardener/context.go
  test/e2e/gardener/seed/renew_gardenlet_kubeconfig.go
  test/e2e/gardener/seed/seed.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#11882 Deploy apiserver-proxy envoy filter only when apiserver-proxy is required
  pkg/component/kubernetes/apiserverexposure/sni.go
  pkg/component/kubernetes/apiserverexposure/sni_test.go
  pkg/component/kubernetes/apiserverexposure/templates/envoyfilter-apiserver-proxy.yaml
  pkg/gardenlet/operation/botanist/kubeapiserverexposure.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#11853 [GEP-28] Deploy `gardener-resource-manager` and extension controllers (in bootstrap mode)
  example/gardenadm-local/high-touch/machine.yaml
  example/provider-local/gardenadm/.gitignore
  example/provider-local/gardenadm/kustomization.yaml
  example/provider-local/gardenadm/patch-controllerdeployment-provider-local-disable-coredns.yaml
  extensions/pkg/controller/worker/genericactuator/actuator.go
  hack/check-skaffold-deps.sh
  hack/generate-gardenadm-imagevector-overwrite.sh
  hack/generate-kustomize-patch-controllerdeployment-provider-local-gardenadm.sh
  pkg/component/gardener/resourcemanager/constants/constants.go
  pkg/component/gardener/resourcemanager/mock/mocks.go
  pkg/component/gardener/resourcemanager/resource_manager.go
  pkg/component/gardener/resourcemanager/resource_manager_test.go
  pkg/component/kubernetes/apiserver/secrets.go
  pkg/component/shared/resourcemanager.go
  pkg/gardenadm/botanist/botanist.go
  pkg/gardenadm/botanist/extensions.go
  pkg/gardenadm/botanist/extensions_test.go
  pkg/gardenadm/cmd/init/init.go
  pkg/gardenadm/resources.go
  pkg/gardenadm/resources_test.go
  pkg/gardenadm/staticpod/translator.go
  pkg/gardenadm/staticpod/translator_test.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/add.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler_test.go
  pkg/gardenlet/controller/gardenlet/add.go
  pkg/gardenlet/operation/botanist/resource_manager.go
  pkg/operator/controller/extension/extension/add.go
  pkg/operator/controller/gardenlet/add.go
  pkg/provider-local/controller/worker/actuator.go
  pkg/resourcemanager/apis/config/v1alpha1/types.go
  pkg/resourcemanager/predicate/class_filter.go
  pkg/resourcemanager/predicate/class_filter_test.go
  pkg/resourcemanager/webhook/kubernetesservicehost/handler.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  pkg/utils/kubernetes/pod.go
  pkg/utils/kubernetes/pod_test.go
  pkg/utils/oci/helmregistry.go
  pkg/utils/secrets/kubeconfig.go
  pkg/utils/secrets/kubeconfig_test.go
  skaffold-gardenadm.yaml
  test/e2e/gardenadm/hightouch/gardenadm.go
Labels: kind/enhancement, cla: yes, lgtm, approved, size/XXL, area/ipcei

#11878 fix: support multiple containers per pod when dumping logs
  test/framework/dump.go
Labels: kind/bug, size/S, area/testing, cla: yes, lgtm, approved

#11736 [GEP-33] Introduce Capabilities support to CloudProfile API
  docs/api-reference/core.md
  docs/deployment/feature_gates.md
  example/30-cloudprofile.yaml
  example/gardener-local/controlplane/values.yaml
  extensions/pkg/bastion/machine.go
  pkg/apis/core/helper/cloudprofile.go
  pkg/apis/core/helper/cloudprofile_test.go
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/types_test.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/defaults_cloudprofile.go
  pkg/apis/core/v1beta1/defaults_cloudprofile_test.go
  pkg/apis/core/v1beta1/defaults_namespacedcloudprofile_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/cloudprofile.go
  pkg/apis/core/v1beta1/helper/cloudprofile_test.go
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/apis/core/v1beta1/types_test.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/zz_generated.defaults.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/validation/namespacedcloudprofile.go
  pkg/apis/core/validation/utils.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/features/features.go
  pkg/apiserver/openapi/api_violations.report
  pkg/apiserver/openapi/openapi_generated.go
  pkg/apiserver/registry/core/cloudprofile/strategy.go
  pkg/apiserver/registry/core/cloudprofile/strategy_test.go
  pkg/controllermanager/controller/namespacedcloudprofile/reconciler.go
  pkg/controllermanager/controller/namespacedcloudprofile/reconciler_test.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/features/features.go
  plugin/pkg/namespacedcloudprofile/validator/admission.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/utils/cloudprofile.go
  plugin/pkg/utils/cloudprofile_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/framework/worker_utils.go
Labels: kind/enhancement, area/usability, area/os, cla: yes, lgtm, approved, size/XXL

#11892 [GEP-28] Handle networking and control plane components
  charts/gardener/provider-local/templates/deployment.yaml
  charts/gardener/provider-local/values.yaml
  cmd/gardenadm/main.go
  cmd/gardener-extension-admission-local/app/app.go
  cmd/gardener-extension-provider-local/app/app.go
  docs/extensions/registration.md
  docs/extensions/shoot-webhooks.md
  example/gardenadm-local/high-touch/kustomization.yaml
  example/gardenadm-local/high-touch/machine.yaml
  example/gardenadm-local/high-touch/service.yaml
  example/provider-local/gardenadm/shoot.yaml
  extensions/pkg/controller/cmd/options.go
  extensions/pkg/controller/controlplane/genericactuator/actuator.go
  extensions/pkg/webhook/cmd/options.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/extensions/validation/operatingsystemconfig.go
  pkg/apis/extensions/validation/operatingsystemconfig_test.go
  pkg/component/etcd/bootstrap/etcd.go
  pkg/component/etcd/bootstrap/etcd_test.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/gardener/resourcemanager/resource_manager.go
  pkg/component/gardener/resourcemanager/resource_manager_test.go
  pkg/component/kubernetes/proxy/proxy_test.go
  pkg/component/kubernetes/proxy/resources.go
  pkg/component/networking/coredns/coredns.go
  pkg/component/shared/resourcemanager.go
  pkg/controller/networkpolicy/reconciler.go
  pkg/extensions/customresources.go
  pkg/gardenadm/botanist/botanist.go
  pkg/gardenadm/botanist/controlplane.go
  pkg/gardenadm/botanist/extensions.go
  pkg/gardenadm/botanist/extensions_test.go
  pkg/gardenadm/botanist/network.go
  pkg/gardenadm/botanist/network_test.go
  pkg/gardenadm/botanist/operatingsystemconfig.go
  pkg/gardenadm/cmd/init/init.go
  pkg/gardenadm/staticpod/translator.go
  pkg/gardenadm/staticpod/translator_test.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/kubecontrollermanager.go
  pkg/gardenlet/operation/botanist/kubescheduler.go
  pkg/gardenlet/operation/botanist/namespaces.go
  pkg/gardenlet/operation/botanist/namespaces_test.go
  pkg/gardenlet/operation/botanist/secrets.go
  pkg/provider-local/charts/shoot-system-components/charts/local-path-provisioner/templates/deployment.yaml
  pkg/provider-local/webhook/controlplane/ensurer.go
  pkg/provider-local/webhook/shoot/add.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  skaffold-gardenadm.yaml
  test/e2e/gardenadm/hightouch/gardenadm.go
  test/integration/extensions/webhook/certificates/certificates_test.go
  test/integration/extensions/webhook/cloudprovider/cloudprovider_suite_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: kind/enhancement, cla: yes, lgtm, approved, size/XXL, area/ipcei

#11713 [GEP-31] Adapt `Worker` reconciler for in-place update
  docs/api-reference/extensions.md
  example/seed-crds/10-crd-extensions.gardener.cloud_workers.yaml
  extensions/pkg/controller/worker/controller.go
  extensions/pkg/controller/worker/controller_test.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile_test.go
  extensions/pkg/controller/worker/helper/helper.go
  extensions/pkg/controller/worker/machines.go
  extensions/pkg/controller/worker/mapper.go
  extensions/pkg/controller/worker/mapper_test.go
  pkg/apis/core/helper/shoot.go
  pkg/apis/core/helper/shoot_test.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/helper/shoot.go
  pkg/apis/core/v1beta1/helper/shoot_test.go
  pkg/apis/extensions/v1alpha1/types_worker.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_workers.yaml
  pkg/component/extensions/worker/mock/mocks.go
  pkg/component/extensions/worker/worker.go
  pkg/component/extensions/worker/worker_test.go
  pkg/gardenlet/operation/botanist/worker.go
  pkg/provider-local/controller/worker/add.go
  pkg/provider-local/controller/worker/machines.go
  pkg/utils/gardener/machines.go
  pkg/utils/gardener/machines_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  pkg/utils/kubernetes/health/machinedeployment.go
  pkg/utils/kubernetes/health/machinedeployment_test.go
  pkg/utils/miscellaneous_test.go
Labels: kind/enhancement, area/delivery, area/open-source, area/control-plane, area/scalability, cla: yes, lgtm, approved, size/XXL

#11843 [GEP-31] Adapt `Shoot` reconciler for in-place update
  docs/api-reference/core.md
  docs/usage/shoot-operations/shoot_operations.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/api_violations.report
  pkg/apiserver/openapi/openapi_generated.go
  pkg/apiserver/registry/core/shoot/strategy.go
  pkg/apiserver/registry/core/shoot/strategy_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_test.go
  pkg/gardenlet/operation/botanist/botanist.go
  pkg/gardenlet/operation/botanist/botanist_test.go
Labels: kind/enhancement, area/delivery, area/open-source, area/control-plane, area/scalability, cla: yes, lgtm, approved, size/XXL

#11844 [GEP-31] Introduce `Shoot` status reconciler for maintaining in-place update status
  charts/gardener/gardenlet/templates/helpers.tpl
  charts/gardener/gardenlet/test/chart_test.go
  charts/gardener/gardenlet/test/test.go
  charts/gardener/gardenlet/values.yaml
  docs/concepts/gardenlet.md
  docs/usage/shoot/shoot_status.md
  example/20-componentconfig-gardenlet.yaml
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/gardenlet/controller/shoot/add.go
  pkg/gardenlet/controller/shoot/care/constraints.go
  pkg/gardenlet/controller/shoot/care/constraints_test.go
  pkg/gardenlet/controller/shoot/care/health.go
  pkg/gardenlet/controller/shoot/care/reconciler_test.go
  pkg/gardenlet/controller/shoot/status/add.go
  pkg/gardenlet/controller/shoot/status/add_test.go
  pkg/gardenlet/controller/shoot/status/reconciler.go
  pkg/gardenlet/controller/shoot/status/status_suite_test.go
  skaffold.yaml
  test/integration/gardenlet/shoot/status/status_suite_test.go
  test/integration/gardenlet/shoot/status/status_test.go
Labels: kind/enhancement, area/delivery, area/open-source, area/control-plane, area/scalability, cla: yes, lgtm, approved, size/XXL

#11912 docs: Update Kubernetes conformance to v1.32
  README.md
Labels: size/XS, area/documentation, area/open-source, kind/task, cla: yes, lgtm, approved

#11903 chore: Update github.com/gardener/autoscaler to v1.32.0
  imagevector/containers.yaml
Labels: size/XS, area/open-source, kind/task, area/control-plane, cla: yes, lgtm, approved

#11914 Deflake `node-agent` integration test
  pkg/nodeagent/controller/operatingsystemconfig/reconciler.go
  pkg/nodeagent/controller/operatingsystemconfig/reconciler_test.go
  test/integration/nodeagent/operatingsystemconfig/operatingsystemconfig_suite_test.go
  test/integration/nodeagent/operatingsystemconfig/operatingsystemconfig_test.go
Labels: size/L, kind/cleanup, area/testing, cla: yes, lgtm, approved

#11913 Cleanup legacy EU access-only sync mechanism
  pkg/apiserver/registry/core/cloudprofile/strategy.go
  pkg/apiserver/registry/core/cloudprofile/strategy_test.go
  pkg/apiserver/registry/core/seed/strategy.go
  pkg/apiserver/registry/core/seed/strategy_test.go
  pkg/apiserver/registry/core/shoot/strategy.go
  pkg/apiserver/registry/core/shoot/strategy_test.go
Labels: kind/api-change, size/XL, area/usability, cla: yes, lgtm, approved

#11837 Add option to set `injectGardenKubeconfig: true` when generating `ControllerDeployment`s and `Extension`s
  example/provider-local/garden/operator/extension.yaml
  hack/generate-controller-registration.sh
  hack/tools/extension-generator/extension.go
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved

#11906 Add Capabilities tests for NamespacedCloudProfile
  plugin/pkg/namespacedcloudprofile/validator/admission.go
  plugin/pkg/namespacedcloudprofile/validator/admission_test.go
Labels: size/L, kind/test, area/testing, cla: yes, lgtm, approved

#11917 [GEP-30] Deploy proxy-protocol envoy filters if proxy-protocol is enabled for the seed
  pkg/component/networking/istio/charts/istio/istio-ingress/templates/proxy-protocol-envoyfilter.yaml
  pkg/component/networking/istio/istio_test.go
Labels: kind/bug, area/networking, size/S, cla: yes, lgtm, approved

#11891 Adapt `vpa`, `istio` and `etcd` CRDs to generic `CRDDeployer`
  pkg/component/autoscaling/vpa/crd.go
  pkg/component/autoscaling/vpa/crd_test.go
  pkg/component/autoscaling/vpa/vpa.go
  pkg/component/etcd/etcd/crd.go
  pkg/component/etcd/etcd/crd_test.go
  pkg/component/networking/istio/charts/istio/istio-crds/Chart.yaml
  pkg/component/networking/istio/charts/istio/istio-crds/README.md
  pkg/component/networking/istio/charts/istio/istio-crds/crd-all.gen.yaml
  pkg/component/networking/istio/charts/istio/istio-crds/values.yaml
  pkg/component/networking/istio/crds.go
  pkg/component/networking/istio/crds_test.go
  pkg/gardenadm/botanist/customresourcedefinitions.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/garden/garden/reconciler_delete.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  skaffold-gardenadm.yaml
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/resourcemanager/crddeletionprotection/crddeletionprotection_test.go
Labels: size/L, area/robustness, kind/cleanup, cla: yes, lgtm, approved

#11916 Sync kubelet CA bundle to project namespace
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/operation/botanist/secrets.go
  pkg/gardenlet/operation/botanist/secrets_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#11926 `gardener-controller-manager` patches objects only when legacy seed labels have been removed
  cmd/gardener-controller-manager/app/app.go
Labels: kind/bug, area/robustness, size/S, cla: yes, lgtm, approved

#11865 e2e: Refactor `renew_garden_access_secret` test to ordered containers
  test/e2e/gardener/seed/common.go
  test/e2e/gardener/seed/renew_garden_access_secrets.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#11925 [docs] Enhance cloud provider credentials rotation
  docs/operations/configuration.md
  docs/usage/shoot-operations/shoot_credentials_rotation.md
Labels: kind/enhancement, area/documentation, size/S, cla: yes, lgtm, approved

#11935 No longer set by default the `--audit-log-(path|maxsize|maxbackups)` flags on gardener/kubernetes apiservers
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/values.yaml
  example/gardener-local/controlplane/values.yaml
  pkg/component/apiserver/audit.go
  pkg/component/apiserver/audit_test.go
  pkg/component/gardener/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
Labels: kind/enhancement, area/security, size/M, area/audit-logging, cla: yes, lgtm, approved

#11412 [GEP-30] Drop ext-authz-server component
  imagevector/containers.go
  imagevector/containers.yaml
  pkg/component/networking/vpn/authzserver/authzserver.go
  pkg/component/networking/vpn/authzserver/authzserver_suite_test.go
  pkg/component/networking/vpn/authzserver/authzserver_test.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  skaffold.yaml
Labels: area/security, size/XL, kind/cleanup, area/networking, cla: yes, lgtm, approved

#11951 Fix non-working `AuthenticationConfiguration` config example
  docs/usage/shoot/shoot_access.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#11954 e2e: move helper functions out of internal package
  test/e2e/gardener/project/project.go
  test/e2e/gardener/project/project_roles.go
  test/e2e/operator/garden/create_delete.go
  test/e2e/operator/garden/create_rotate_delete.go
  test/e2e/operator/garden/garden.go
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#11959 [gardenet] Sync seed backup credentials on start-up
  cmd/gardenlet/app/migration.go
  cmd/gardenlet/app/options.go
Labels: kind/bug, area/security, size/M, cla: yes, lgtm, approved, area/ipcei

#11964 Add `pod` cache to `gardener-node-agent` only when `nodeName` is present
  cmd/gardener-node-agent/app/app.go
Labels: kind/bug, size/M, cla: yes, lgtm, approved

#11971 [GEP-28] Do not watch `Machine`s in `Worker` controller
  cmd/gardener-extension-provider-local/app/app.go
  extensions/pkg/controller/worker/controller.go
  pkg/provider-local/controller/worker/add.go
Labels: kind/bug, size/M, cla: yes, lgtm, approved, area/ipcei

#11979 e2e: Fix flake in `ManagedSeed` create-rotate-delete test
  test/e2e/gardener/managedseed/create_rotate_delete.go
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#11980 Add instruction in component checklist to not set `podAntiAffinity`
  docs/development/component-checklist.md
Labels: size/XS, area/documentation, kind/cleanup, area/high-availability, cla: yes, lgtm, approved

#11983 [GEP-26] Do not try to copy infra creds for backup if workload identity is used
  pkg/controller/gardenletdeployer/actuator.go
  pkg/controller/gardenletdeployer/actuator_test.go
  pkg/gardenlet/controller/managedseed/reconciler.go
Labels: kind/bug, area/security, size/M, cla: yes, lgtm, approved

#11966 Cache sync health check with deadline
  cmd/gardener-admission-controller/app/app.go
  cmd/gardener-controller-manager/app/app.go
  cmd/gardener-extension-admission-local/app/app.go
  cmd/gardener-extension-provider-local/app/app.go
  cmd/gardener-node-agent/app/app.go
  cmd/gardener-operator/app/app.go
  cmd/gardener-resource-manager/app/app.go
  cmd/gardener-scheduler/app/app.go
  cmd/gardenlet/app/app.go
  pkg/healthz/informer.go
  pkg/healthz/informer_test.go
Labels: kind/enhancement, size/L, area/robustness, cla: yes, lgtm, approved

#11973 etcd-druid: Remove resource limits
  pkg/component/etcd/etcd/bootstrap.go
  pkg/component/etcd/etcd/bootstrap_test.go
Labels: kind/enhancement, size/S, area/auto-scaling, cla: yes, lgtm, approved

#11975 [GEP-28] Move `KUBECONFIG` from machine level to `~/.bashrc`
  example/gardenadm-local/high-touch/machine.yaml
  skaffold-gardenadm.yaml
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved, area/ipcei

#11955 Remove empty cidr check
  pkg/scheduler/controller/shoot/reconciler.go
  pkg/scheduler/controller/shoot/reconciler_test.go
  pkg/utils/validation/cidr/disjoint.go
  pkg/utils/validation/cidr/disjoint_test.go
  plugin/pkg/shoot/validator/admission.go
Labels: kind/bug, size/L, area/networking, cla: yes, lgtm, approved

#11962 [GEP-26] Stale project controller considers workload identities
  docs/concepts/controller-manager.md
  pkg/controllermanager/controller/project/stale/reconciler.go
  pkg/controllermanager/controller/project/stale/reconciler_test.go
Labels: kind/enhancement, area/security, area/quality, size/L, cla: yes, lgtm, approved
