Repository gardener/gardener, pull requests merged in 2025-08, with the labels that each got.

#12652 Fix seed registration for `ManagedSeed`s
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_managedseed.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_seed.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
Labels: kind/bug, area/security, size/M, cla: yes, lgtm, approved

#12654 Cluster overview dashboard fix
  pkg/component/observability/plutono/dashboards/shoot/owners/worker/cluster-overview-dashboard.json
Labels: kind/bug, size/L, area/monitoring, cla: yes, lgtm, approved

#12548 Fix updates to CA annotation on `MachineDeployment` upon change in worker specific options
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile_test.go
  pkg/apis/extensions/v1alpha1/helper/worker.go
  pkg/apis/extensions/v1alpha1/helper/worker_test.go
Labels: kind/bug, size/L, area/auto-scaling, cla: yes, lgtm, approved

#12519 [GEP-26] Prepare local setup with extensions for WorkloadIdentities
  docs/deployment/getting_started_locally_with_extensions.md
  example/provider-extensions/garden/project/credentials/.gitignore
  example/provider-extensions/garden/project/credentials/credentialsbindings.yaml.tmpl
  example/provider-extensions/garden/project/credentials/infrastructure-workloadidentities.yaml.tmpl
  example/provider-extensions/garden/project/kustomization.yaml
  example/provider-extensions/seed/configure-seed.sh
Labels: kind/enhancement, area/dev-productivity, area/security, lifecycle/stale, area/documentation, size/M, cla: yes, lgtm, approved, area/ipcei, ipcei/workload-identity

#12529 [GEP-33] Add Capabilities support to Worker MachineImage Version defaulting
  pkg/controllermanager/controller/shoot/maintenance/helper/helper.go
  pkg/controllermanager/controller/shoot/maintenance/helper/helper_test.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
  test/utils/shoots/update/update.go
Labels: kind/enhancement, area/usability, size/L, area/os, cla: yes, lgtm, approved

#12657 [GEP-28] Make provider-local machine hostnames resolvable
  docs/extensions/provider-local.md
  pkg/gardenadm/botanist/extensions.go
  pkg/provider-local/controller/bastion/actuator.go
  pkg/provider-local/controller/worker/machines.go
  pkg/provider-local/machine-provider/local/create_machine.go
  pkg/provider-local/machine-provider/local/driver.go
  test/e2e/gardener/shoot/internal/bastion/bastion.go
Labels: kind/enhancement, size/L, cla: yes, lgtm, approved, area/ipcei

#12627 Move the `do not use` note from the `FeatureGates` field to the `KubernetesConfig` type
  charts/gardener/operator/templates/crd-gardens.yaml
  docs/api-reference/core.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_workers.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_workers.yaml
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#12666 Harden `(Namespaced)CloudProfile` field validation
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/validation/utils.go
  pkg/apis/core/validation/utils_test.go
Labels: kind/enhancement, area/security, area/usability, size/L, area/robustness, cla: yes, lgtm, approved

#12684 Prepare next Dev Cycle v1.126.0-dev
  VERSION
Labels: area/delivery, size/XS, kind/task, cla: yes, lgtm, approved

#12673 Grant Viewer/Admin permissions in the shoot to new groups "gardener.cloud:(project|system):(admins|viewers)"
  cmd/gardenlet/app/migration.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apiserver/registry/core/shoot/storage/viewer_kubeconfig.go
  pkg/component/shoot/system/system.go
  pkg/component/shoot/system/system_test.go
Labels: kind/enhancement, area/security, size/L, cla: yes, lgtm, approved, area/ipcei

#12550 Promote Feature Gate `NewWorkerPoolHash` to `Beta` and default to `true`
  dev-setup/gardenlet/base/gardenlet.yaml
  docs/deployment/feature_gates.md
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/features/features.go
Labels: kind/enhancement, size/M, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#12677 Configure `vpa-updater` with a `ServiceMonitor` to allow metrics scraping
  pkg/component/autoscaling/vpa/updater.go
  pkg/component/autoscaling/vpa/vpa_test.go
Labels: kind/enhancement, size/L, area/auto-scaling, cla: yes, lgtm, approved

#12725 [release-v1.124] Update dependency gardener/vpn2 to v0.40.1
  imagevector/containers.yaml
Labels: kind/bug, size/XS, area/networking, cla: yes, lgtm, approved

#12706 Update Setup Guide to include Cert Management for Garden
  docs/deployment/setup_gardener.md
Labels: kind/enhancement, area/documentation, size/L, cla: yes, lgtm, approved

#12704 Clean up the obsolete `.ci/get_latest_release_component_descriptor` script
  .ci/get_latest_release_component_descriptor
Labels: size/M, kind/cleanup, area/testing, cla: yes, lgtm, approved

#12109 Reintroduce `compare-k8s-feature-gates.sh`
  docs/development/new-kubernetes-version.md
  hack/compare-k8s-feature-gates.sh
  pkg/utils/validation/features/featuregates.go
Labels: kind/enhancement, area/quality, size/L, cla: yes, lgtm, approved

#12747 chore: Use Renovate preset for grouping Go updates
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#12754 chore(renovate): Drop inline package rule for grouping Go updates
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#12758 Clean up TODOs
  Makefile
  dev-setup/extensions/provider-local/components/extension/kustomization.yaml
  dev-setup/gardenlet/base/gardenlet.yaml
  pkg/apis/seedmanagement/validation/managedseedset.go
Labels: area/dev-productivity, kind/cleanup, size/S, cla: yes, lgtm, approved

#12728 Remove init container and annotation used for Prometheus volume cleanup migration
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  cmd/gardenlet/app/migration.go
  pkg/apis/resources/v1alpha1/types.go
  pkg/component/observability/monitoring/prometheus/component.go
  pkg/component/observability/monitoring/prometheus/prometheus.go
Labels: kind/enhancement, size/L, area/monitoring, cla: yes, lgtm, approved

#12686 [GEP-28] `gardenadm bootstrap`: Connect to first control plane machine and copy manifests
  REUSE.toml
  go.mod
  go.sum
  pkg/gardenadm/botanist/botanist.go
  pkg/gardenadm/botanist/ssh.go
  pkg/gardenadm/cmd/bootstrap/bootstrap.go
  pkg/gardenadm/resources.go
  pkg/provider-local/controller/infrastructure/actuator.go
  pkg/provider-local/machine-provider/local/create_machine.go
  pkg/utils/ssh/connection.go
  pkg/utils/ssh/prefixed_writer.go
  test/e2e/gardenadm/mediumtouch/exec.go
  test/e2e/gardenadm/mediumtouch/gardenadm.go
Labels: kind/enhancement, size/L, cla: yes, lgtm, approved, area/ipcei

#12709 Switch local IPv6 setup to `gardener-operator`
  Makefile
  dev-setup/extensions/provider-local/overlays/operator-ipv6/kustomization.yaml
  dev-setup/extensions/provider-local/overlays/operator-ipv6/patch-ipv6.yaml
  dev-setup/garden/components/ipv6/kustomization.yaml
  dev-setup/garden/overlays/multi-node-ipv6/kustomization.yaml
  dev-setup/garden/overlays/multi-zone-ipv6/kustomization.yaml
  dev-setup/garden/overlays/single-node-ipv6/kustomization.yaml
  dev-setup/gardenlet/components/ipv6/kustomization.yaml
  dev-setup/gardenlet/overlays/multi-node-ipv6/kustomization.yaml
  dev-setup/gardenlet/overlays/multi-zone-ipv6/kustomization.yaml
  dev-setup/gardenlet/overlays/single-node-ipv6/kustomization.yaml
  dev-setup/scenario.sh
  dev-setup/seed.sh
  docs/deployment/getting_started_locally.md
  docs/development/ipv6.md
  example/gardener-local/gardenlet/values-ipv6.yaml
  example/gardener-local/kind/cluster/templates/_extra_port_mappings.tpl
  example/gardener-local/kind/cluster/values-ipv6.yaml
  example/gardener-local/kind/cluster/values.yaml
  example/provider-local/garden/ipv6/kustomization.yaml
  example/provider-local/garden/ipv6/patch-controller-deployment.yaml
  hack/ci-e2e-kind.sh
  hack/kind-up.sh
  pkg/operator/controller/add.go
  pkg/operator/controller/garden/garden/reconciler.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  pkg/provider-local/controller/service/add.go
  skaffold-operator.yaml
  skaffold-seed.yaml
  skaffold.yaml
  test/e2e/gardener/context.go
  test/e2e/gardener/seed/renew_garden_access_secrets.go
  test/e2e/gardener/seed/renew_gardenlet_kubeconfig.go
  test/e2e/gardener/seed/seed.go
  test/e2e/gardener/shoot/create_authenticate_delete.go
  test/e2e/gardener/shoot/create_delete_hibernated.go
  test/e2e/gardener/shoot/create_delete_unprivileged.go
  test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go
  test/e2e/gardener/shoot/create_migrate_delete.go
  test/e2e/gardener/shoot/create_rotate_delete.go
  test/e2e/gardener/shoot/create_update-in-place_delete.go
  test/e2e/gardener/shoot/create_update_delete.go
  test/e2e/gardener/shoot/gardenerupgrade/create_upgrade_delete.go
  test/e2e/gardener/shoot/gardenerupgrade/create_upgrade_update-to-ha_delete.go
  test/e2e/gardener/shoot/logging.go
  test/e2e/gardener/shoot/shoot.go
  test/e2e/gardener/shoot/update-to-ha.go
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#12769 fix: Propagate error in Worker reconciliation
  pkg/component/extensions/worker/worker.go
  pkg/component/extensions/worker/worker_test.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#12777 Adapt Shoot example to new CredentialsBinding
  example/90-shoot.yaml
Labels: size/XS, area/usability, kind/cleanup, cla: yes, lgtm, approved

#12771 Add sources to all Helm charts
  charts/gardener/admission-local/charts/application/Chart.yaml
  charts/gardener/admission-local/charts/runtime/Chart.yaml
  charts/gardener/controlplane/Chart.yaml
  charts/gardener/controlplane/charts/application/Chart.yaml
  charts/gardener/controlplane/charts/runtime/Chart.yaml
  charts/gardener/gardenlet/Chart.yaml
  charts/gardener/operator/Chart.yaml
  charts/gardener/provider-local/Chart.yaml
  charts/gardener/resource-manager/Chart.yaml
  charts/gardener/resource-manager/charts/application/Chart.yaml
  charts/gardener/resource-manager/charts/runtime/Chart.yaml
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#12422 enable/disable node-local-dns without rolling nodes
  docs/usage/shoot-operations/shoot_updates.md
  extensions/pkg/controller/worker/machines.go
  extensions/pkg/controller/worker/machines_test.go
  imagevector/containers.go
  imagevector/containers.yaml
  pkg/apis/core/helper/shoot.go
  pkg/apis/core/helper/shoot_test.go
  pkg/apis/core/v1beta1/helper/shoot.go
  pkg/apis/core/v1beta1/helper/shoot_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/networking/nodelocaldns/mock/mocks.go
  pkg/component/networking/nodelocaldns/nodelocaldns.go
  pkg/component/networking/nodelocaldns/nodelocaldns_test.go
  pkg/component/networking/nodelocaldns/resources.go
  pkg/component/networking/nodelocaldns/resources/cleanup.sh
  pkg/gardenlet/operation/botanist/nodelocaldns.go
  pkg/gardenlet/operation/botanist/nodelocaldns_test.go
  pkg/gardenlet/operation/botanist/operatingsystemconfig.go
  skaffold-gardenadm.yaml
  skaffold-seed.yaml
  skaffold.yaml
Labels: kind/enhancement, area/networking, cla: yes, lgtm, approved, size/XXL

#12759 Document the admission plugin types
  docs/concepts/apiserver-admission-plugins.md
  plugin/pkg/backupbucket/validator/admission.go
  plugin/pkg/bastion/validator/admission.go
  plugin/pkg/controllerregistration/resources/admission.go
  plugin/pkg/global/customverbauthorizer/admission.go
  plugin/pkg/global/deletionconfirmation/admission.go
  plugin/pkg/global/extensionlabels/admission.go
  plugin/pkg/global/extensionvalidation/admission.go
  plugin/pkg/global/finalizerremoval/admission.go
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/managedseed/shoot/admission.go
  plugin/pkg/managedseed/validator/admission.go
  plugin/pkg/namespacedcloudprofile/validator/admission.go
  plugin/pkg/project/validator/admission.go
  plugin/pkg/seed/mutator/admission.go
  plugin/pkg/seed/validator/admission.go
  plugin/pkg/seed/validator/admission_test.go
  plugin/pkg/shoot/dns/admission.go
  plugin/pkg/shoot/dnsrewriting/admission.go
  plugin/pkg/shoot/exposureclass/admission.go
  plugin/pkg/shoot/managedseed/admission.go
  plugin/pkg/shoot/nodelocaldns/admission.go
  plugin/pkg/shoot/oidc/clusteropenidconnectpreset/admission.go
  plugin/pkg/shoot/oidc/openidconnectpreset/admission.go
  plugin/pkg/shoot/quotavalidator/admission.go
  plugin/pkg/shoot/resourcereservation/admission.go
  plugin/pkg/shoot/tolerationrestriction/admission.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/vpa/admission.go
Labels: kind/enhancement, area/documentation, size/L, cla: yes, lgtm, approved

#12784 Move the Validation of a `Project` resource's `.spec.namespace` field to the Storage Layer
  docs/concepts/apiserver-admission-plugins.md
  pkg/apis/core/validation/project.go
  pkg/apis/core/validation/project_test.go
  plugin/pkg/project/validator/admission.go
  plugin/pkg/project/validator/admission_test.go
Labels: area/security, size/L, kind/cleanup, cla: yes, lgtm, approved

#12801 Drop `maxprocs` from `gardener-controller-manager`
  cmd/gardener-controller-manager/app/app.go
  go.mod
Labels: area/robustness, kind/cleanup, size/S, cla: yes, lgtm, approved

#12807 Clean up the `NewVPN` feature gate
  docs/deployment/feature_gates.md
  pkg/component/networking/vpn/seedserver/seedserver_test.go
  pkg/features/features.go
  pkg/features/features_test.go
  pkg/gardenlet/features/features.go
Labels: size/M, kind/cleanup, area/networking, cla: yes, lgtm, approved

#12568 [GEP-34] Route Shoot Logs Through OpenTelemetry Collector
  example/gardener-local/gardenlet/values.yaml
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config.go
  pkg/component/observability/logging/vali/vali.go
  pkg/component/observability/logging/vali/vali_suite_test.go
  pkg/component/observability/logging/vali/vali_test.go
  pkg/component/observability/opentelemetry/collector/collector.go
  pkg/component/observability/opentelemetry/collector/collector_test.go
  pkg/component/observability/opentelemetry/collector/constants/constants.go
  pkg/component/observability/opentelemetry/collector/logging.go
  pkg/component/observability/opentelemetry/collector/mock/doc.go
  pkg/component/observability/opentelemetry/collector/mock/mocks.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/operation/botanist/logging.go
  pkg/gardenlet/operation/botanist/logging_test.go
  pkg/gardenlet/operation/shoot/types.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
  skaffold-gardenadm.yaml
  skaffold-operator.yaml
  skaffold-seed.yaml
  skaffold.yaml
Labels: kind/enhancement, area/logging, cla: yes, lgtm, approved, size/XXL

#12809 docs(development): Add guidance for updating Go
  docs/development/dependencies.md
Labels: kind/enhancement, area/dev-productivity, area/documentation, size/S, cla: yes, lgtm, approved

#12786 Make the `FinalizerRemoval` admission plugin validating
  docs/concepts/apiserver-admission-plugins.md
  plugin/pkg/global/finalizerremoval/admission.go
  plugin/pkg/global/finalizerremoval/admission_test.go
Labels: kind/enhancement, area/security, size/M, cla: yes, lgtm, approved

#12823 Fix condition status for emergency stop of Shoot reconciliations
  pkg/gardenlet/controller/seed/care/health.go
  pkg/gardenlet/controller/seed/care/reconciler_test.go
Labels: kind/bug, size/XS, area/quality, cla: yes, lgtm, approved

#12816 Add migration of kube-dns service to dual-stack.
  docs/usage/networking/dual-stack-networking-migration.md
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/coredns.go
  pkg/gardenlet/operation/botanist/coredns_test.go
  pkg/gardenlet/operation/botanist/dualstackmigration.go
  pkg/gardenlet/operation/botanist/dualstackmigration_test.go
Labels: kind/enhancement, size/L, area/networking, cla: yes, lgtm, approved
