Repository gardener/gardener, pull requests merged in 2025-10, with the labels that each got.

#13061 Add missing json tags to extensionsv1alpha1.BastionList
  pkg/apis/extensions/v1alpha1/types_bastion.go
  pkg/apis/extensions/v1alpha1/types_cluster.go
  pkg/apis/extensions/v1alpha1/types_controlplane.go
  pkg/apis/extensions/v1alpha1/types_dnsrecord.go
Labels: kind/bug, size/S, area/control-plane, cla: yes, lgtm, approved

#13057 Remove unnecessary fields from `ShootMigrationConfig` struct and fix node checks
  test/framework/shootmigrationtest.go
Labels: kind/bug, size/M, kind/cleanup, area/testing, area/control-plane-migration, cla: yes, lgtm, approved

#12844 Improve input validation of various Shoot `.spec` fields
  pkg/apis/core/validation/project.go
  pkg/apis/core/validation/project_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/validation/utils.go
  test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_suite_test.go
  test/integration/apiserver/admissionplugins/shootvalidator/shootvalidator_test.go
  test/integration/controllermanager/controllerregistration/seed/seed_test.go
Labels: kind/enhancement, area/security, area/quality, size/L, cla: yes, lgtm, approved

#13060 [GEP-26] Handle properly backup WorkloadIdentity credentials in gardenletdeployer actuator
  pkg/controller/gardenletdeployer/actuator.go
  pkg/controller/gardenletdeployer/actuator_test.go
  pkg/operator/controller/gardenlet/reconciler.go
Labels: kind/bug, area/security, size/M, cla: yes, lgtm, approved, area/ipcei, ipcei/workload-identity

#13049 docs: Order gardener-apiserver admission plugins alphabetically
  docs/concepts/apiserver-admission-plugins.md
Labels: kind/enhancement, area/security, size/L, cla: yes, lgtm, approved

#13034 [GEP-28] Enable bootstrap procedure and `Gardenlet` controller for self-upgrades
  Makefile
  charts/gardener/controlplane/charts/application/templates/clusterrole-seed-bootstrapper.yaml
  charts/gardener/gardenlet/templates/configmap-selfupgrade-config.yaml
  charts/gardener/gardenlet/test/chart_test.go
  charts/gardener/gardenlet/values.yaml
  cmd/gardenlet/app/app.go
  docs/concepts/controller-manager.md
  docs/concepts/operator.md
  pkg/admissioncontroller/webhook/admission/shootrestriction/handler.go
  pkg/admissioncontroller/webhook/admission/shootrestriction/handler_test.go
  pkg/admissioncontroller/webhook/auth/authorizer.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer_test.go
  pkg/admissioncontroller/webhook/auth/shoot/add.go
  pkg/admissioncontroller/webhook/auth/shoot/authorizer.go
  pkg/admissioncontroller/webhook/auth/shoot/authorizer_test.go
  pkg/component/garden/system/virtual/virtual.go
  pkg/component/garden/system/virtual/virtual_test.go
  pkg/component/shoot/system/system.go
  pkg/component/shoot/system/system_test.go
  pkg/controller/gardenletdeployer/actuator.go
  pkg/controller/gardenletdeployer/actuator_test.go
  pkg/controllermanager/controller/certificatesigningrequest/reconciler.go
  pkg/controllermanager/controller/certificatesigningrequest/reconciler_test.go
  pkg/gardenadm/botanist/nodeagent.go
  pkg/gardenlet/bootstrap/bootstrap.go
  pkg/gardenlet/bootstrap/bootstrap_test.go
  pkg/gardenlet/bootstrap/certificate/certificate_rotation.go
  pkg/gardenlet/bootstrappers/garden_kubeconfig.go
  pkg/gardenlet/bootstrappers/garden_kubeconfig_test.go
  pkg/gardenlet/controller/add.go
  pkg/gardenlet/controller/gardenlet/add.go
  pkg/gardenlet/controller/gardenlet/reconciler.go
  pkg/operator/controller/gardenlet/add.go
  pkg/operator/controller/gardenlet/add_test.go
  pkg/resourcemanager/controller/csrapprover/reconciler.go
  pkg/utils/gardener/csr.go
  pkg/utils/gardener/csr_test.go
  pkg/utils/gardener/gardenlet/gardenlet.go
  pkg/utils/gardener/gardenlet/gardenlet_test.go
  pkg/utils/gardener/seed.go
  pkg/utils/gardener/seed_test.go
  pkg/utils/graph/eventhandler_certificatesigningrequest.go
  pkg/utils/graph/eventhandler_gardenlet.go
  pkg/utils/graph/graph.go
  pkg/utils/graph/graph_test.go
  pkg/webhook/authorizer/fake/withselectors.go
  skaffold-gardenadm.yaml
  skaffold-operator.yaml
  skaffold.yaml
  test/e2e/gardenadm/hightouch/gardenadm.go
  test/integration/controllermanager/certificatesigningrequest/certificatesigningrequest_suite_test.go
  test/integration/controllermanager/certificatesigningrequest/certificatesigningrequest_test.go
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL, area/ipcei

#13055 Fix wildcardConfiguration for exposure classes.
  pkg/gardenlet/operation/botanist/kubeapiserverexposure.go
  pkg/gardenlet/operation/istio_config.go
  pkg/gardenlet/operation/istio_config_test.go
Labels: kind/bug, size/M, area/networking, cla: yes, lgtm, approved

#13043 feat: configurable advertised addresses for shoot ingress endpoints
  docs/README.md
  docs/development/shoot-advertised-addresses.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/gardenlet/operation/botanist/advertisedaddresses.go
  pkg/gardenlet/operation/botanist/advertisedaddresses_test.go
Labels: kind/enhancement, area/usability, size/L, area/control-plane, cla: yes, lgtm, approved

#13106 Update opentelemetry operator image to v0.136.0
  imagevector/containers.yaml
  pkg/component/observability/opentelemetry/operator/operator.go
  pkg/component/observability/opentelemetry/operator/operator_test.go
Labels: kind/enhancement, area/logging, size/S, cla: yes, lgtm, approved

#13031 [GEP-28] `gardenadm bootstrap`: Initialize control plane
  dev-setup/gardenadm/resources/base/shoot.yaml
  dev-setup/gardenadm/resources/overlays/medium-touch/kustomization.yaml
  docs/cli-reference/gardenadm/gardenadm_bootstrap.md
  docs/deployment/getting_started_locally_with_gardenadm.md
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/gardenadm/botanist/botanist.go
  pkg/gardenadm/botanist/botanist_test.go
  pkg/gardenadm/botanist/controlplane.go
  pkg/gardenadm/botanist/ssh.go
  pkg/gardenadm/cmd/bootstrap/bootstrap.go
  pkg/gardenadm/cmd/bootstrap/options.go
  pkg/gardenadm/cmd/bootstrap/options_test.go
  pkg/gardenadm/resources.go
  pkg/gardenadm/resources_test.go
  pkg/utils/gardener/shoot.go
  pkg/utils/ssh/connection.go
  pkg/utils/ssh/prefixed_writer.go
  test/e2e/gardenadm/mediumtouch/gardenadm.go
  test/e2e/gardener/shoot/internal/bastion/bastion.go
Labels: kind/enhancement, size/XL, cla: yes, lgtm, approved, area/ipcei
