Repository gardener/gardener, pull requests merged in 2025-02, with the labels that each got.

#11215 Add VPA memory histogram options
  docs/api-reference/core.md
  example/90-shoot.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/component/autoscaling/vpa/recommender.go
  pkg/component/autoscaling/vpa/vpa_test.go
  pkg/gardenlet/operation/botanist/vpa.go
Labels: kind/enhancement, area/auto-scaling, cla: yes, lgtm, approved, size/XXL

#11260 Rewrite Setup Gardener document
  README.md
  docs/deployment/content/extensions.png
  docs/deployment/content/garden.png
  docs/deployment/content/gardener-setup.png
  docs/deployment/content/gardenlet.png
  docs/deployment/content/managedseed.png
  docs/deployment/setup_gardener.md
Labels: kind/enhancement, area/documentation, size/L, cla: yes, lgtm, approved

#11284 Do not skip KCM deployment in Shoot deletion flow if controlplane is deployed
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
Labels: kind/bug, area/ops-productivity, size/XS, cla: yes, lgtm, approved

#11273 Fix worker priority configuration
  go.mod
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
Labels: kind/enhancement, area/quality, size/S, cla: yes, lgtm, approved

#11281 Ensure `node-agent-authorizer` webhook configuration is added exactly once
  pkg/component/kubernetes/apiserver/apiserver.go
  pkg/component/kubernetes/apiserver/mock/mocks.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
Labels: kind/bug, size/L, area/robustness, cla: yes, lgtm, approved

#11304 Fix nil pointer exception in shoot deletion and migration flows if `shoot.status.networking == nil`
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
Labels: size/XS, area/robustness, kind/regression, cla: yes, lgtm, approved

#11291 Document how the ManagedResource Secret data can be decompressed
  docs/concepts/resource-manager.md
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#11292 chore: Enhance release notes for grouped Renovate PRs
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#11289 Graduate feature gate `UseNamespacedCloudProfile` to `Beta`
  docs/api-reference/core.md
  docs/deployment/feature_gates.md
  example/gardener-local/controlplane/values.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/features/features.go
Labels: kind/enhancement, area/usability, size/S, cla: yes, lgtm, approved

#11308 [release-v1.110] Automated cherry pick of #11281: Ensure `node-agent-authorizer` webhook configuration is added exactly once
  pkg/component/kubernetes/apiserver/apiserver.go
  pkg/component/kubernetes/apiserver/mock/mocks.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
Labels: kind/bug, size/L, area/robustness, cla: yes, lgtm, approved

#11309 [release-v1.109] Automated cherry pick of #11281: Ensure `node-agent-authorizer` webhook configuration is added exactly once
  pkg/component/kubernetes/apiserver/apiserver.go
  pkg/component/kubernetes/apiserver/mock/mocks.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
Labels: kind/bug, size/L, area/robustness, cla: yes, lgtm, approved

#11310 Prepare next Dev Cycle v1.113.0-dev
  VERSION
Labels: area/delivery, size/XS, kind/task, cla: yes, lgtm, approved

#11317 remove namespace from generated CA-ConfigMap
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
Labels: kind/enhancement, size/XS, area/quality, cla: yes, lgtm, approved

#11286 Rescore nginx ingress controller
  imagevector/containers.yaml
Labels: kind/enhancement, area/security, size/S, cla: yes, lgtm, approved

#10971 Metrics for shoot operation times including dashboard
  pkg/component/observability/plutono/dashboards/seed/shoot-operation-duration.json
  pkg/component/observability/plutono/plutono_test.go
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  pkg/gardenlet/metrics/metrics.go
  pkg/provider-local/webhook/prometheus/mutator.go
  skaffold.yaml
Labels: kind/enhancement, size/L, area/monitoring, ok-to-test, cla: yes, lgtm, approved

#11306 chore: Change debug output for `generate-kustomize-patch-gardenlet.sh`
  hack/generate-kustomize-patch-gardenlet.sh
Labels: area/dev-productivity, kind/task, size/S, area/testing, cla: yes, lgtm, approved

#11321 Accept `client.Reader` instead of `client.Client` in the `managedresources.WaitUntilHealthy` func
  pkg/utils/managedresources/managedresources.go
  test/integration/gardenlet/seed/seed/seed_test.go
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved

#11314 Minimize wildcards in RBAC roles
  charts/gardener/provider-local/templates/rbac.yaml
  docs/development/component-checklist.md
  pkg/component/autoscaling/clusterautoscaler/bootstrap.go
  pkg/component/autoscaling/clusterautoscaler/bootstrap_test.go
  pkg/component/nodemanagement/machinecontrollermanager/bootstrap.go
  pkg/component/nodemanagement/machinecontrollermanager/bootstrap_test.go
  pkg/component/observability/monitoring/prometheusoperator/prometheus_operator_test.go
  pkg/component/observability/monitoring/prometheusoperator/rbac.go
Labels: kind/enhancement, area/security, size/M, area/compliance, cla: yes, lgtm, approved

#11241 Forbid privilege escalation for Shoot system and Shoot control plane components
  docs/development/component-checklist.md
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
  pkg/component/autoscaling/vpa/admissioncontroller.go
  pkg/component/autoscaling/vpa/recommender.go
  pkg/component/autoscaling/vpa/updater.go
  pkg/component/autoscaling/vpa/vpa_test.go
  pkg/component/gardener/dashboard/terminal/deployment.go
  pkg/component/gardener/dashboard/terminal/terminal_test.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/kubernetes/controllermanager/controllermanager.go
  pkg/component/kubernetes/controllermanager/controllermanager_test.go
  pkg/component/kubernetes/dashboard/dashboard_test.go
  pkg/component/kubernetes/proxy/proxy_test.go
  pkg/component/kubernetes/proxy/resources.go
  pkg/component/kubernetes/scheduler/scheduler.go
  pkg/component/kubernetes/scheduler/scheduler_test.go
  pkg/component/networking/apiserverproxy/apiserver_proxy.go
  pkg/component/networking/apiserverproxy/apiserver_proxy_test.go
  pkg/component/networking/coredns/coredns.go
  pkg/component/networking/nodelocaldns/nodelocaldns.go
  pkg/component/networking/nodelocaldns/nodelocaldns_test.go
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/seedserver/seedserver_test.go
  pkg/component/networking/vpn/shoot/shoot.go
  pkg/component/networking/vpn/shoot/shoot_test.go
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager_test.go
  pkg/component/nodemanagement/machinecontrollermanager/provider.go
  pkg/component/nodemanagement/machinecontrollermanager/provider_test.go
  pkg/component/observability/logging/eventlogger/event_logger.go
  pkg/component/observability/logging/eventlogger/event_logger_test.go
  pkg/component/observability/logging/vali/vali.go
  pkg/component/observability/logging/vali/vali_test.go
  pkg/component/observability/monitoring/blackboxexporter/blackboxexporter.go
  pkg/component/observability/monitoring/blackboxexporter/blackboxexporter_test.go
  pkg/component/observability/monitoring/kubestatemetrics/kubestatemetrics_test.go
  pkg/component/observability/monitoring/kubestatemetrics/resources.go
  pkg/component/observability/monitoring/metricsserver/metricsserver.go
  pkg/component/observability/monitoring/metricsserver/metricsserver_test.go
  pkg/component/observability/monitoring/nodeexporter/nodeexporter.go
  pkg/component/observability/monitoring/nodeexporter/nodeexporter_test.go
  pkg/component/observability/monitoring/prometheusoperator/deployment.go
  pkg/component/observability/monitoring/prometheusoperator/prometheus_operator_test.go
  pkg/component/observability/plutono/plutono.go
  pkg/component/observability/plutono/plutono_test.go
Labels: kind/enhancement, area/security, size/L, area/compliance, cla: yes, lgtm, approved

#11191 [GEP 31] Introduce API changes for supporting InPlaceUpdate
  docs/api-reference/core.md
  docs/api-reference/extensions.md
  docs/deployment/feature_gates.md
  docs/extensions/resources/operatingsystemconfig.md
  docs/proposals/31-inplace-node-update.md
  example/30-cloudprofile.yaml
  example/90-shoot.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_workers.yaml
  pkg/apis/core/helper/shoot.go
  pkg/apis/core/helper/shoot_test.go
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/validation/utils.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/apis/extensions/v1alpha1/types_worker.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/features/features.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_workers.yaml
  pkg/features/features.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, area/delivery, area/open-source, area/control-plane, area/scalability, cla: yes, lgtm, approved, size/XXL

#11150 Use rand.Read for etcd key generation
  pkg/component/apiserver/apiserver_suite_test.go
  pkg/component/apiserver/encryptionconfiguration.go
  pkg/component/apiserver/encryptionconfiguration_test.go
  pkg/component/gardener/apiserver/apiserver_suite_test.go
  pkg/component/gardener/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/utils/secrets/alias.go
  pkg/utils/secrets/etcd_encryption_key.go
  pkg/utils/secrets/etcd_encryption_key_test.go
  pkg/utils/secrets/secrets_suite_test.go
  test/utils/rotation/etcd_encryption_key.go
Labels: kind/enhancement, area/security, size/L, area/compliance, cla: yes, lgtm, approved

#11339 [renovate] Fix `allowedVersions` regex
  .github/renovate.json5
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#11342 fix(renovate): Fix `allowedVersions` (again)
  .github/renovate.json5
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#11360 Do not specify `command` for the containers of the VPA components
  pkg/component/autoscaling/vpa/admissioncontroller.go
  pkg/component/autoscaling/vpa/recommender.go
  pkg/component/autoscaling/vpa/updater.go
  pkg/component/autoscaling/vpa/vpa_test.go
Labels: size/L, kind/cleanup, area/auto-scaling, cla: yes, lgtm, approved

#11279 Allow configuring a maximum node count per shoot
  docs/README.md
  docs/api-reference/core.md
  docs/usage/shoot/shoot_limits.md
  example/30-cloudprofile.yaml
  pkg/apis/core/types_cloudprofile.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_cloudprofile.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
  pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
  pkg/gardenlet/operation/botanist/clusterautoscaler.go
  pkg/gardenlet/operation/botanist/clusterautoscaler_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, area/usability, area/robustness, cla: yes, lgtm, approved, size/XXL

#11359 Fix `Seed` labels in `ManagedSeed` spec
  pkg/apis/core/helper/seed.go
  pkg/apis/core/helper/seed_test.go
Labels: kind/bug, area/ops-productivity, size/S, cla: yes, lgtm, approved

#11287 [GEP-30] e2e: verify in-cluster access to API server
  test/e2e/gardener/shoot/create_and_delete_unprivileged.go
  test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go
  test/e2e/gardener/shoot/create_migrate_delete.go
  test/e2e/gardener/shoot/create_rotate_delete.go
  test/e2e/gardener/shoot/create_update_delete.go
  test/e2e/gardener/shoot/internal/inclusterclient/inclusterclient.go
  test/e2e/gardener/shoot/internal/node/node.go
  test/e2e/gardener/shoot/upgrade_non-ha_to_node.go
  test/e2e/gardener/shoot/upgrade_non-ha_to_zone.go
Labels: size/L, kind/test, area/networking, cla: yes, lgtm, approved

#11361 Add Viktor to OWNER_ALIASES
  OWNERS_ALIASES
  docs/development/process.md
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#11369 Build `golang-test` images for Go 1.24
  hack/tools/image/variants.yaml
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#11332 Update etcd-druid to `v0.27.0`
  example/seed-crds/10-crd-druid.gardener.cloud_etcds.yaml
  go.mod
  go.sum
  imagevector/containers.yaml
  pkg/component/etcd/etcd/crds/templates/crd-druid.gardener.cloud_etcds.yaml
  pkg/component/etcd/etcd/etcd.go
  pkg/component/etcd/etcd/etcd_test.go
  pkg/component/etcd/etcd/waiter.go
  pkg/component/etcd/etcd/waiter_test.go
  pkg/gardenlet/operation/botanist/etcd.go
  pkg/gardenlet/operation/botanist/etcd_test.go
  pkg/operator/controller/garden/garden/components.go
  pkg/utils/kubernetes/health/checker/checker.go
  test/framework/gardener_utils.go
  test/integration/operator/garden/care/care_test.go
  test/integration/operator/garden/garden/garden_test.go
Labels: kind/bug, kind/enhancement, area/backup, area/quality, size/L, area/control-plane, cla: yes, lgtm, approved

#11364 [GEP-30] Drop proxy protocol from API server proxy
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/component/networking/apiserverproxy/apiserver_proxy.go
  pkg/component/networking/apiserverproxy/apiserver_proxy_test.go
  pkg/component/networking/apiserverproxy/templates/envoy.yaml.tpl
  pkg/component/networking/istio/charts/istio/istio-ingress/templates/vpn-envoy-filter.yaml
  pkg/component/networking/istio/test_charts/ingress_vpn_envoy_filter.yaml
  pkg/gardenlet/operation/botanist/apiserverproxy.go
  pkg/gardenlet/operation/botanist/apiserverproxy_test.go
  pkg/gardenlet/operation/operation.go
  pkg/gardenlet/operation/types.go
Labels: kind/enhancement, size/L, area/networking, cla: yes, lgtm, approved

#11377 chore: Ignore .git folder when checking license headers
  hack/check-license-header.sh
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#11343 [GEP-28] Prepare `gardener/resourcemanager` component for "bootstrap control plane" case
  pkg/component/gardener/resourcemanager/resource_manager.go
  pkg/component/gardener/resourcemanager/resource_manager_test.go
  pkg/component/shared/resourcemanager.go
  pkg/component/shared/resourcemanager_test.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/operation/botanist/resource_manager.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/enhancement, cla: yes, lgtm, approved, size/XXL, area/ipcei

#11389 Increase bit size of rsa key in unit test
  pkg/utils/secrets/rsa_private_key_test.go
Labels: kind/enhancement, size/XS, area/testing, cla: yes, lgtm, approved

#11251 Add dual-stack support to `Garden` resource and gardener-operator
  charts/gardener/operator/templates/crd-gardens.yaml
  docs/api-reference/operator.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/operator/v1alpha1/types_garden.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/controller/add.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  pkg/operator/webhook/validation/handler_test.go
  test/e2e/operator/garden/common.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
  test/integration/gardenlet/networkpolicy/networkpolicy_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/controllerregistrar/controllerregistrar_test.go
  test/integration/operator/extension/extension/extension_test.go
  test/integration/operator/garden/care/care_test.go
  test/integration/operator/garden/garden/garden_test.go
  test/integration/operator/garden/reference/reference_test.go
Labels: kind/enhancement, size/XL, area/networking, cla: yes, lgtm, approved

#11395 Remove typos code smells in test cases
  pkg/apis/core/helper/common_test.go
  pkg/apis/core/helper/seed_test.go
  pkg/apis/core/v1beta1/defaults_shoot_test.go
  pkg/apis/core/v1beta1/helper/condition_builder_test.go
  pkg/apis/core/v1beta1/helper/condition_test.go
  pkg/apis/core/v1beta1/helper/seed_test.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/validation/namespacedcloudprofile_test.go
  pkg/apis/core/validation/shoot_test.go
  plugin/pkg/shoot/tolerationrestriction/admission_test.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: area/quality, size/L, kind/cleanup, cla: yes, lgtm, approved

#11380 [GEP-30] Add RemoveAPIServerProxyLegacyPort feature gate
  cmd/gardenlet/app/app.go
  cmd/gardenlet/app/migration.go
  docs/deployment/feature_gates.md
  pkg/component/kubernetes/apiserverexposure/sni.go
  pkg/component/kubernetes/apiserverexposure/sni_test.go
  pkg/features/features.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/features/features.go
  pkg/gardenlet/operation/botanist/kubeapiserverexposure.go
Labels: kind/enhancement, size/L, area/networking, cla: yes, lgtm, approved

#11397 Scale kube-apiserver after switching to node-agent-authorizer
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#11399 [operator/garden Integration Test] Make `ManagedResource`s only healthy when they exist
  test/integration/operator/garden/garden/garden_test.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#11424 [release-v1.111] Automated cherry pick of #11397: Scale kube-apiserver after switching to node-agent-authorizer
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
Labels: kind/bug, size/XS, area/control-plane, cla: yes, lgtm, approved

#11420 Increase log output when adding to/checking `/etc/hosts`
  hack/ci-common.sh
  hack/kind-up.sh
Labels: size/XS, area/testing, kind/flake, cla: yes, lgtm, approved

#11372 Deprecate the `shoot.gardener.cloud/managed-seed-api-server` annotation
  docs/operations/managed_seed.md
  pkg/api/core/shoot/warnings.go
  pkg/api/core/shoot/warnings_test.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/helper/managedseed.go
Labels: size/M, kind/cleanup, area/auto-scaling, cla: yes, lgtm, approved

#11413 Fix the `shoot-annotated-seed-service-endpoints` scrape configuration
  pkg/component/observability/monitoring/prometheus/shoot/scrapeconfigs.go
  pkg/component/observability/monitoring/prometheus/shoot/scrapeconfigs_test.go
Labels: kind/enhancement, size/XS, area/monitoring, cla: yes, lgtm, approved

#11422 Start refactoring e2e tests to ordered containers
  .golangci.yaml.in
  test/e2e/gardener/common.go
  test/e2e/gardener/context.go
  test/e2e/gardener/managedseed/create_rotate_delete.go
  test/e2e/gardener/shoot/common.go
  test/e2e/gardener/shoot/create_and_delete_failed.go
  test/e2e/gardener/shoot/create_and_delete_unprivileged.go
  test/e2e/gardener/shoot/internal/shoot.go
  test/e2e/ginkgo.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#11426 Make observability components deployment depending on GRM
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
Labels: kind/test, size/S, area/testing, cla: yes, lgtm, approved

#11344 Align some resources for proper garbage-collection
  pkg/component/observability/logging/fluentbit/fluentbit.go
  pkg/component/observability/logging/fluentbit/fluentbit_test.go
  pkg/component/observability/monitoring/kubestatemetrics/customresourcestate.go
  pkg/component/observability/monitoring/kubestatemetrics/kubestatemetrics_test.go
  pkg/component/observability/monitoring/kubestatemetrics/resources.go
  pkg/component/observability/monitoring/prometheus/prometheus.go
  pkg/component/observability/monitoring/prometheus/prometheus_test.go
  pkg/resourcemanager/controller/garbagecollector/reconciler.go
  pkg/resourcemanager/controller/garbagecollector/references/references.go
  pkg/resourcemanager/controller/garbagecollector/references/references_test.go
  test/integration/resourcemanager/garbagecollector/garbagecollector_suite_test.go
  test/integration/resourcemanager/garbagecollector/garbagecollector_test.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#11434 Auto-remediate duplicate node ports in same service
  pkg/controller/service/reconciler.go
Labels: size/XS, area/testing, kind/flake, cla: yes, lgtm, approved

#11429 [GEP-30] Prevent ACL extension incompatibility
  docs/proposals/30-apiserver-proxy.md
  pkg/component/networking/apiserverproxy/apiserver_proxy_test.go
  pkg/component/networking/apiserverproxy/templates/envoy.yaml.tpl
  pkg/component/networking/istio/charts/istio/istio-ingress/templates/vpn-envoy-filter.yaml
  pkg/component/networking/istio/test_charts/ingress_vpn_envoy_filter.yaml
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved

#11430 Consistently set shoot creation timeout to `30m` for all e2e tests
  test/e2e/gardener/managedseed/create_rotate_delete.go
  test/e2e/gardener/shoot/create_and_delete_hibernated.go
  test/e2e/gardener/shoot/create_and_force_delete.go
  test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go
  test/e2e/gardener/shoot/create_migrate_delete.go
  test/e2e/gardener/shoot/create_rotate_delete.go
  test/e2e/gardener/shoot/create_update_delete.go
  test/e2e/gardener/shoot/internal/shoot.go
  test/e2e/gardener/shoot/upgrade_non-ha_to_node.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#11394 [resource-manager] Set sync period to `1h` for all deployments
  pkg/component/gardener/resourcemanager/resource_manager.go
  pkg/component/gardener/resourcemanager/resource_manager_test.go
  pkg/component/shared/resourcemanager.go
  pkg/component/shared/resourcemanager_test.go
Labels: kind/enhancement, size/S, area/scalability, cla: yes, lgtm, approved

#11431 Fix interval parameter for `gardenlet` certificate rotation retrier
  pkg/gardenlet/bootstrap/bootstrap_test.go
  pkg/gardenlet/bootstrap/certificate/certificate_rotation.go
  pkg/gardenlet/bootstrap/certificate/certificate_rotation_test.go
  pkg/utils/kubernetes/certificatesigningrequest/certificate.go
  pkg/utils/kubernetes/certificatesigningrequest/certificate_test.go
  test/integration/nodeagent/certificate/certificate_test.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#11437 Delay `Shoot` maintenance for e2e tests
  test/e2e/gardener/common.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#11436 [GEP-30] Add `UseUnifiedHTTPProxyPort` feature gate to rollout plan
  docs/proposals/30-apiserver-proxy.md
Labels: kind/enhancement, area/networking, size/S, cla: yes, lgtm, approved

#11451 [release-v1.112] Automated cherry pick of #11421: fix(deps): update machine-controller-manager to v0.56.1 (patch) - autoclosed
  go.mod
  go.sum
  imagevector/containers.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#11453 [release-v1.111] Automated cherry pick of #11400: Fix availability of Gardener `APIService`s
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/kubernetes/controllermanager/controllermanager.go
  pkg/component/kubernetes/controllermanager/controllermanager_test.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#11325 Revisit the `VerticalPodAutoscalerCappedRecommendation` alert
  pkg/component/observability/monitoring/kubestatemetrics/kubestatemetrics_test.go
  pkg/component/observability/monitoring/kubestatemetrics/resources.go
  pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go
  pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules_test.go
  pkg/component/observability/monitoring/prometheus/garden/assets/prometheusrules/seed.yaml
  pkg/component/observability/monitoring/prometheus/garden/assets/prometheusrules/shoot.yaml
  pkg/component/observability/monitoring/prometheus/garden/prometheusrules.go
  pkg/component/observability/monitoring/prometheus/garden/testdata/seed.prometheusrule.test.yaml
  pkg/component/observability/monitoring/prometheus/garden/testdata/shoot.prometheusrule.test.yaml
  pkg/component/observability/monitoring/prometheus/shoot/assets/prometheusrules/verticalpodautoscaler.yaml
  pkg/component/observability/monitoring/prometheus/shoot/testdata/verticalpodautoscaler.prometheusrule.test.yaml
Labels: kind/enhancement, size/L, area/monitoring, cla: yes, lgtm, approved

#11442 e2e: refactor `Create and Delete Hibernated Shoot` test to ordered containers
  test/e2e/gardener/context.go
  test/e2e/gardener/shoot/create_and_delete_failed.go
  test/e2e/gardener/shoot/create_and_delete_hibernated.go
  test/e2e/gardener/shoot/create_and_delete_unprivileged.go
  test/e2e/gardener/shoot/internal/shoot.go
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#11443 Fix flaky CSINode test
  test/e2e/gardener/shoot/internal/node/node.go
Labels: kind/test, area/robustness, size/S, area/testing, cla: yes, lgtm, approved

#11447 Use lock file as mutex to only write imagevector override patch file sequentially
  hack/generate-kustomize-patch-controllerdeployment-provider-local-prow.sh
  hack/generate-kustomize-patch-controllerdeployment-provider-local.sh
  hack/generate-kustomize-patch-extension-provider-local-prow.sh
  hack/generate-kustomize-patch-extension-provider-local.sh
  hack/generate-kustomize-patch-gardenlet.sh
  hack/lockfile.sh
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#11452 [release-v1.110] Automated cherry pick of #11400: Fix availability of Gardener `APIService`s
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/kubernetes/controllermanager/controllermanager.go
  pkg/component/kubernetes/controllermanager/controllermanager_test.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#11432 Use proper field path for dashboard oidc config
  charts/gardener/operator/templates/crd-gardens.yaml
  docs/api-reference/operator.md
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  pkg/apis/operator/v1alpha1/types_garden.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/bug, area/quality, size/M, cla: yes, lgtm, approved

#11454 [release-v1.112] Automated cherry pick of #11400: Fix availability of Gardener `APIService`s
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/kubernetes/controllermanager/controllermanager.go
  pkg/component/kubernetes/controllermanager/controllermanager_test.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#11450 Append to exported test resources instead of replacing
  hack/ci-common.sh
  hack/ci-e2e-kind-ha-multi-zone.sh
  hack/ci-e2e-kind-ha-single-zone.sh
  hack/ci-e2e-kind-migration-ha-single-zone.sh
  hack/ci-e2e-kind-migration.sh
  hack/ci-e2e-kind-operator-seed.sh
  hack/ci-e2e-kind-upgrade.sh
  hack/ci-e2e-kind.sh
Labels: kind/enhancement, size/M, area/testing, cla: yes, lgtm, approved

#11446 [GEP-28] Refactor gardenadm unit tests to `gbytes.Buffer`
  pkg/gardenadm/cmd/bootstrap/bootstrap_test.go
  pkg/gardenadm/cmd/connect/connect_test.go
  pkg/gardenadm/cmd/discover/discover_test.go
  pkg/gardenadm/cmd/init/init_test.go
  pkg/gardenadm/cmd/join/join_test.go
  pkg/gardenadm/cmd/options.go
  pkg/gardenadm/cmd/options_test.go
  pkg/gardenadm/cmd/token/create/create_test.go
  pkg/gardenadm/cmd/token/delete/delete_test.go
  pkg/gardenadm/cmd/token/generate/generate_test.go
  pkg/gardenadm/cmd/token/list/list_test.go
  pkg/gardenadm/cmd/token/token_test.go
  pkg/gardenadm/cmd/version/version_test.go
  pkg/utils/test/cli/cli.go
Labels: kind/enhancement, size/L, cla: yes, lgtm, approved, area/ipcei

#11455 Increase timeout for migration to `20m`
  test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go
  test/e2e/gardener/shoot/create_migrate_delete.go
  test/e2e/gardener/shoot/internal/shoot.go
  test/e2e/gardener/shoot/upgrade_non-ha_to_node.go
  test/e2e/gardener/upgrade/upgrade.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#11463 Fix calculation maintenance time window in e2e tests
  test/e2e/gardener/common.go
Labels: size/XS, kind/regression, area/testing, cla: yes, lgtm, approved

#11460 [operator] Ensure Garden environment is clean when `Garden` is deleted
  pkg/component/observability/plutono/plutono.go
  pkg/component/observability/plutono/plutono_test.go
  pkg/operator/controller/garden/garden/reconciler_delete.go
  pkg/provider-local/controller/backupbucket/actuator.go
  test/e2e/operator/garden/common.go
  test/e2e/operator/garden/create_delete.go
  test/e2e/operator/garden/create_rotate_delete.go
  test/integration/operator/garden/garden/garden_test.go
Labels: kind/enhancement, area/usability, size/L, kind/flake, cla: yes, lgtm, approved

#11458 Prepare next Dev Cycle v1.114.0-dev
  VERSION
Labels: area/delivery, size/XS, kind/task, cla: yes, lgtm, approved

#11465 Prevent concurrent map read/writes in `Extension` deployer component
  pkg/component/extensions/extension/extension.go
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#11449 Stop skipping extension `BackupEntry` reconciliation for failed `Shoot`s and Improve core `BackupEntry` predicate
  extensions/pkg/controller/backupentry/reconciler.go
  pkg/controllerutils/predicate/predicate.go
  pkg/controllerutils/predicate/predicate_test.go
  pkg/gardenlet/controller/backupentry/add.go
  pkg/gardenlet/controller/backupentry/add_test.go
Labels: kind/bug, area/ops-productivity, size/L, cla: yes, lgtm, approved

#11475 chore(deps): bump up logging to 0.65.0 with fluent-bit 3.2.5
  imagevector/containers.yaml
Labels: kind/enhancement, area/logging, size/S, cla: yes, lgtm, approved

#11470 Recheck `cancelFunc` has been called in `OperatingSystemConfig` test
  test/integration/nodeagent/operatingsystemconfig/operatingsystemconfig_test.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#11471 Use `MergeFromWithOptimisticLock` for patching the node object in node agent reconciliation delay
  pkg/resourcemanager/controller/node/agentreconciliationdelay/reconciler.go
Labels: size/XS, area/testing, kind/flake, cla: yes, lgtm, approved

#11338 [GEP-30] Destroy ext-authz-server deployment
  docs/development/priority-classes.md
  imagevector/containers.yaml
  pkg/component/networking/vpn/authzserver/authzserver.go
  pkg/component/shared/istio.go
  pkg/component/shared/istio_test.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  skaffold-operator.yaml
Labels: area/security, kind/cleanup, area/networking, size/S, ok-to-test, cla: yes, lgtm, approved

#11479 Rename `seed.gardener.cloud/` prefix to `name.seed.gardener.cloud/`
  cmd/gardener-controller-manager/app/app.go
  cmd/gardenlet/app/app.go
  docs/concepts/apiserver-admission-plugins.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apiserver/registry/core/backupentry/strategy_test.go
  pkg/apiserver/registry/core/shoot/strategy_test.go
  pkg/utils/gardener/identity_test.go
  plugin/pkg/managedseed/validator/admission_test.go
  plugin/pkg/seed/mutator/admission_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: area/usability, size/L, kind/regression, cla: yes, lgtm, approved

#11481 Install `runc` from container filesystem when running in prow
  hack/kind-up.sh
Labels: kind/enhancement, size/XS, area/testing, cla: yes, lgtm, approved

#11393 [GEP-31] Adapt `OperatingSystemConfig` reconciler and extension to populate fields related to in-place update
  docs/api-reference/extensions.md
  example/90-shoot.yaml
  example/seed-crds/10-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  extensions/pkg/controller/operatingsystemconfig/actuator.go
  extensions/pkg/controller/operatingsystemconfig/reconciler.go
  pkg/apis/core/v1beta1/helper/shoot.go
  pkg/apis/core/v1beta1/helper/shoot_test.go
  pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/components_suite_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/secrets.go
  pkg/provider-local/controller/operatingsystemconfig/actuator.go
  pkg/utils/gardener/shoot.go
  pkg/utils/gardener/shoot_test.go
Labels: kind/enhancement, cla: yes, lgtm, approved, size/XXL

#11482 [GEP-30] Fix stuck gardenlet with feature gate RemoveAPIServerProxyLegacyPort
  cmd/gardenlet/app/migration.go
Labels: kind/bug, area/robustness, area/networking, size/S, cla: yes, lgtm, approved

#11483 [GEP-30] e2e: retry pod creation until env var is injected
  test/e2e/gardener/shoot/internal/inclusterclient/inclusterclient.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#11472 skaffold: Eliminate the machine-controller-manager-provider-local post-build hooks
  charts/gardener/provider-local/templates/configmap-imagevector-overwrite.yaml
  charts/gardener/provider-local/values.yaml
  example/provider-local/garden/local/.gitignore
  example/provider-local/garden/local/controllerdeployment.yaml
  example/provider-local/garden/local/kustomization.yaml
  example/provider-local/garden/operator/.gitignore
  example/provider-local/garden/operator/extension.yaml
  example/provider-local/garden/operator/kustomization.yaml
  hack/generate-kustomize-patch-controllerdeployment-provider-local.sh
  hack/generate-kustomize-patch-extension-provider-local.sh
  hack/get-skaffold-cache-artifacts.sh
  skaffold-gardenadm.yaml
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/bug, area/dev-productivity, size/L, cla: yes, lgtm, approved

#11484 Remove `lastOperation=Create Pending` from `Shoot` when seed is assigned
  pkg/apiserver/registry/core/shoot/strategy.go
  pkg/apiserver/registry/core/shoot/strategy_test.go
Labels: size/L, area/testing, kind/flake, cla: yes, lgtm, approved

#11493 Improve managed issuer enablement documentation
  docs/usage/security/shoot_serviceaccounts.md
Labels: kind/enhancement, area/documentation, size/S, cla: yes, lgtm, approved

#11494 [provider-local] Improve logging for node port auto-remediation
  pkg/controller/service/reconciler.go
Labels: size/XS, area/testing, kind/flake, cla: yes, lgtm, approved

#11495 [e2e] Increase timeout for credentials rotation w/o workers rollout test
  test/e2e/gardener/shoot/create_rotate_delete.go
Labels: size/XS, area/testing, kind/flake, cla: yes, lgtm, approved

#11498 e2e: refactor `VerifyInClusterAccessToAPIServer` to ordered containers
  test/e2e/gardener/shoot/create_and_delete_unprivileged.go
  test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go
  test/e2e/gardener/shoot/create_migrate_delete.go
  test/e2e/gardener/shoot/create_rotate_delete.go
  test/e2e/gardener/shoot/create_update_delete.go
  test/e2e/gardener/shoot/internal/inclusterclient/inclusterclient.go
  test/e2e/gardener/shoot/internal/shoot.go
  test/e2e/gardener/shoot/upgrade_non-ha_to_node.go
  test/e2e/gardener/shoot/upgrade_non-ha_to_zone.go
Labels: kind/enhancement, size/L, area/testing, cla: yes, lgtm, approved

#11499 [release-v1.110] Automated cherry pick of #11479: Rename `seed.gardener.cloud/` prefix to `name.seed.gardener.cloud/`
  cmd/gardener-controller-manager/app/app.go
  cmd/gardenlet/app/app.go
  docs/concepts/apiserver-admission-plugins.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apiserver/registry/core/backupentry/strategy_test.go
  pkg/apiserver/registry/core/shoot/strategy_test.go
  pkg/utils/gardener/identity_test.go
Labels: area/usability, size/L, kind/regression, cla: yes, lgtm, approved

#11492 [release-v1.111] Automated cherry pick of #11479: Rename `seed.gardener.cloud/` prefix to `name.seed.gardener.cloud/`
  cmd/gardener-controller-manager/app/app.go
  cmd/gardenlet/app/app.go
  docs/concepts/apiserver-admission-plugins.md
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apiserver/registry/core/backupentry/strategy_test.go
  pkg/apiserver/registry/core/shoot/strategy_test.go
  pkg/utils/gardener/identity.go
  pkg/utils/gardener/identity_test.go
Labels: area/usability, size/L, kind/regression, cla: yes, lgtm, approved

#11507 Make sure flags come before arguments in calls to `ctr` to be compatible with containerd 2.0
  pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit_test.go
  pkg/component/extensions/operatingsystemconfig/nodeinit/templates/scripts/init.tpl.sh
  skaffold-gardenadm.yaml
Labels: kind/enhancement, size/XS, area/os, cla: yes, lgtm, approved

#11501 Add missing `pod` variable to API server dashboard
  pkg/component/observability/plutono/dashboards/garden-shoot/apiserver-overview.json
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved

#11500 Refactor e2e test `create_migrate_delete` to use ordered `It` containers
  test/e2e/gardener/shoot/create_migrate_delete.go
  test/e2e/gardener/shoot/internal/inclusterclient/inclusterclient.go
  test/framework/shootmigrationtest.go
Labels: kind/enhancement, size/L, area/testing, cla: yes, lgtm, approved

#11508 Fix the example `NamespacedCloudProfile` to be directly applicable
  example/35-namespacedcloudprofile.yaml
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#11329 Add convenience to generate `Extension` examples
  Makefile
  example/provider-local/garden/operator/doc.go
  example/provider-local/garden/operator/extension-patch.yaml
  example/provider-local/garden/operator/extension.yaml
  example/provider-local/garden/operator/kustomization.yaml
  hack/check-generate.sh
  hack/tools.mk
  hack/tools/extension-generator/extension.go
  hack/tools/extension-generator/main.go
  hack/tools/extension-generator/options.go
Labels: kind/enhancement, area/dev-productivity, area/delivery, area/ops-productivity, size/L, cla: yes, lgtm, approved

#11509 fix gardenlet crash when force deleting workerless shoot
  pkg/gardenlet/controller/shoot/shoot/reconciler_force_delete.go
Labels: kind/bug, size/XS, area/robustness, area/control-plane, cla: yes, lgtm, approved

#11456 e2e: Refactor `Create Force Delete Shoot` test to ordered containers
  test/e2e/gardener/shoot/create_and_force_delete.go
  test/e2e/gardener/shoot/internal/shoot.go
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#11503 Increase timeout for waiting until CRD gets ready significantly to reduce random test failures.
  pkg/utils/kubernetes/crd.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden/garden_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#11510 chore: Update kindest/node from v1.31 to v1.32
  example/gardener-local/kind/cluster/values.yaml
  hack/ci-e2e-kind-gardenadm.sh
  pkg/provider-local/node/Dockerfile
  test/e2e/gardener/common.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: area/open-source, kind/test, size/S, cla: yes, lgtm, approved

#11502 Add `deny-all` network policy to `Shoot`'s `kube-system` namespace
  docs/README.md
  docs/development/new-kubernetes-version.md
  docs/usage/shoot/shoot_kubernetes_versions.md
  pkg/component/shoot/system/system.go
  pkg/component/shoot/system/system_test.go
  pkg/utils/version/version.go
  pkg/utils/version/version_test.go
Labels: kind/enhancement, area/security, size/L, area/networking, area/compliance, cla: yes, lgtm, approved

#11391 Add `VPA` dashboards to `plutono` running in a `Garden` cluster with enabled VPA
  pkg/component/observability/plutono/plutono.go
  pkg/component/observability/plutono/plutono_test.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#11521 Consider `status.seedName` instead of `spec.seedName`
  pkg/controllermanager/controller/seed/lifecycle/reconciler.go
  pkg/controllermanager/controller/shoot/migration/reconciler.go
  pkg/gardenlet/controller/shoot/care/add.go
  pkg/gardenlet/controller/shoot/care/add_test.go
  pkg/gardenlet/controller/shoot/care/reconciler.go
  pkg/gardenlet/controller/shoot/care/reconciler_test.go
  pkg/gardenlet/controller/shoot/care/types.go
  pkg/gardenlet/controller/shoot/shoot/reconciler.go
  test/integration/controllermanager/seed/lifecycle/lifecycle_suite_test.go
  test/integration/controllermanager/seed/lifecycle/lifecycle_test.go
  test/integration/gardenlet/shoot/care/care_test.go
Labels: kind/bug, size/L, area/control-plane-migration, cla: yes, lgtm, approved

#11538 fix: SSH tunnel livenessProbe no longer fails with slow DNS
  example/provider-extensions/ssh-reverse-tunnel/base/ssh/ssh_deployment.yaml
Labels: area/dev-productivity, size/XS, kind/impediment, area/robustness, cla: yes, lgtm, approved
