Repository gardener/gardener, pull requests merged in 2025-07, with the labels that each got.

#12410 Change permissions of /host/etc/sysctl.d/ to fix local-setup with Cilium
  pkg/provider-local/node/Dockerfile
Labels: kind/bug, size/XS, area/networking, cla: yes, lgtm, approved

#12431 Fix nil pointer dereference
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
Labels: kind/bug, size/XS, area/networking, cla: yes, lgtm, approved

#11996 Set default garden cluster address and update Garden cluster CA for gardenlets
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
  cmd/gardenlet/app/app.go
  dev-setup/gardenlet/base/gardenlet.yaml
  docs/deployment/deploy_gardenlet_via_operator.md
  example/gardener-local/kind/cluster/templates/_kubeadm_config_patches.tpl
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/helper/shoot.go
  pkg/apis/operator/v1alpha1/helper/garden.go
  pkg/apis/operator/v1alpha1/helper/garden_test.go
  pkg/apis/operator/v1alpha1/validation/garden.go
  pkg/apis/operator/v1alpha1/validation/garden_test.go
  pkg/component/garden/system/virtual/virtual.go
  pkg/component/garden/system/virtual/virtual_test.go
  pkg/controller/gardenletdeployer/actuator.go
  pkg/controller/gardenletdeployer/actuator_test.go
  pkg/gardenlet/apis/config/v1alpha1/types.go
  pkg/gardenlet/bootstrap/util/util.go
  pkg/gardenlet/bootstrap/util/util_test.go
  pkg/gardenlet/bootstrappers/garden_kubeconfig.go
  pkg/gardenlet/bootstrappers/garden_kubeconfig_test.go
  pkg/gardenlet/controller/managedseed/add.go
  pkg/gardenlet/controller/managedseed/reconciler.go
  pkg/gardenlet/controller/managedseed/reconciler_test.go
  pkg/gardenlet/operation/botanist/advertisedaddresses.go
  pkg/gardenlet/operation/botanist/blackboxexporter.go
  pkg/gardenlet/operation/botanist/dnsrecord.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserverexposure.go
  pkg/gardenlet/operation/shoot/shoot.go
  pkg/operator/controller/add.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/garden/garden/components_test.go
  pkg/operator/controller/gardenlet/add.go
  pkg/operator/controller/gardenlet/reconciler.go
  pkg/utils/gardener/dns.go
  pkg/utils/gardener/gardenlet/gardenlet.go
  pkg/utils/gardener/gardenlet/gardenlet_test.go
  test/integration/gardenlet/managedseed/managedseed_suite_test.go
  test/integration/operator/gardenlet/gardenlet_suite_test.go
Labels: kind/enhancement, size/XL, area/ops-productivity, cla: yes, lgtm, approved

#12317 Deflake `operator/garden` integration test
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  charts/gardener/gardenlet/test/test.go
  pkg/component/crddeployer/crd.go
  pkg/component/extensions/crds/crds.go
  pkg/gardenlet/controller/seed/seed/reconciler_delete.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operator/controller/garden/garden/reconciler_delete.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  pkg/utils/gardener/operator/garden.go
  pkg/utils/kubernetes/crd.go
  pkg/utils/managedresources/managedresources.go
  pkg/utils/test/matchers/matchers.go
  pkg/utils/test/matchers/matchers_test.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden/garden_suite_test.go
  test/integration/operator/garden/garden/garden_test.go
  test/utils/managedresource/managedresource.go
Labels: size/XL, area/testing, kind/flake, cla: yes, lgtm, approved

#12451 Fix BackupBucket reconciliation error by replacing `StrategicMergePatch` with `MergePatch`
  pkg/component/garden/backupbucket/backupbucket.go
  pkg/component/garden/backupbucket/backupbucket_test.go
Labels: area/usability, kind/regression, size/S, cla: yes, lgtm, approved

#12457 Allow `gardener-metrics-exporter` to access `CredentialsBindings`
  pkg/component/observability/monitoring/gardenermetricsexporter/gardener_metrics_exporter_test.go
  pkg/component/observability/monitoring/gardenermetricsexporter/rbac.go
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#12407 [GEP-28] `gardenadm bootstrap`: Deploy and connect to `Bastion`
  docs/cli-reference/gardenadm/gardenadm_bootstrap.md
  pkg/component/extensions/bastion/bastion.go
  pkg/component/extensions/bastion/bastion_suite_test.go
  pkg/component/extensions/bastion/bastion_test.go
  pkg/gardenadm/botanist/bastion.go
  pkg/gardenadm/botanist/botanist.go
  pkg/gardenadm/cmd/bootstrap/bootstrap.go
  pkg/gardenadm/cmd/bootstrap/bootstrap_test.go
  pkg/gardenadm/cmd/bootstrap/options.go
  pkg/gardenadm/cmd/bootstrap/options_test.go
  pkg/utils/publicip/detector.go
  pkg/utils/publicip/detector_test.go
  pkg/utils/publicip/publicip_suite_test.go
  skaffold-gardenadm.yaml
  test/e2e/gardenadm/mediumtouch/gardenadm.go
Labels: kind/enhancement, cla: yes, lgtm, approved, size/XXL, area/ipcei

#12458 Clean up and rename `Default` to `LockedValue` in `FeatureGateVersionRange`
  pkg/utils/validation/features/featuregates.go
Labels: kind/enhancement, area/quality, size/L, cla: yes, lgtm, approved

#12466 [Fix] Allow Uppercase region names
  pkg/component/shared/istio.go
  pkg/component/shared/istio_test.go
Labels: kind/bug, size/XS, area/control-plane, ok-to-test, cla: yes, lgtm, approved

#12316 Add information for upgrading from OIDC to Structured Authentication config
  docs/usage/shoot/shoot_access.md
  docs/usage/shoot/shoot_kubernetes_versions.md
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#12471 [GEP-28] `make gardenadm-up SCENARIO=connect` deploys a Gardener locally
  dev-setup/garden.sh
  dev-setup/gardenadm.sh
  docs/deployment/getting_started_locally_with_gardenadm.md
  hack/usage/generate-virtual-garden-admin-kubeconf.sh
  pkg/gardenadm/cmd/connect/connect.go
  pkg/gardenadm/cmd/connect/connect_test.go
Labels: kind/enhancement, size/M, cla: yes, lgtm, approved, area/ipcei

#12479 Fixed broken links - 2025.07
  docs/extensions/overview.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#12465 Remove `globallyEnabled` field
  charts/gardener/operator/templates/crd-extensions.yaml
  docs/api-reference/core.md
  example/operator/10-crd-operator.gardener.cloud_extensions.yaml
  pkg/apis/core/types_controllerregistration.go
  pkg/apis/core/v1beta1/defaults_controllerregistration.go
  pkg/apis/core/v1beta1/defaults_controllerregistration_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_controllerregistration.go
  pkg/apis/core/v1beta1/types_controllerregistration_test.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/controllerregistration.go
  pkg/apis/core/validation/controllerregistration_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/apiserver/registry/core/controllerregistration/strategy.go
  pkg/apiserver/registry/core/controllerregistration/strategy_test.go
  pkg/operator/webhook/defaulting/extension/handler.go
  pkg/operator/webhook/defaulting/extension/handler_test.go
Labels: area/usability, kind/cleanup, cla: yes, lgtm, approved, size/XXL

#12475 Prepare next Dev Cycle v1.124.0-dev
  VERSION
Labels: kind/enhancement, area/delivery, size/XS, cla: yes, lgtm, approved

#12508 Forbid container privilege escalation for otel-operator
  pkg/component/observability/opentelemetry/operator/operator.go
  pkg/component/observability/opentelemetry/operator/operator_test.go
Labels: kind/enhancement, area/security, size/XS, area/compliance, cla: yes, lgtm, approved

#12510 Update dependency gardener/dashboard to v1.81.0
  imagevector/containers.yaml
  pkg/component/gardener/dashboard/dashboard_test.go
  pkg/component/gardener/dashboard/deployment.go
Labels: size/XS, kind/task, area/control-plane, cla: yes, lgtm, approved

#12516 [GEP-26] Fix WorkloadIdenity token context resolving for BackuEntry when the Shoot is gone
  pkg/apiserver/registry/security/workloadidentity/storage/jwt.go
  pkg/apiserver/registry/security/workloadidentity/storage/jwt_test.go
Labels: kind/bug, area/security, size/M, cla: yes, lgtm, approved, area/ipcei, ipcei/workload-identity

#12473 [GEP-33] Introduce Capabilities validation during Shoot admission
  pkg/apis/core/v1beta1/helper/cloudprofile.go
  pkg/apis/core/v1beta1/helper/cloudprofile_test.go
  plugin/pkg/shoot/validator/admission.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, size/XL, area/usability, area/os, cla: yes, lgtm, approved

#12526 Exclude `gardener-resource-manager` from `pod-kube-apiserver-load-balancing` webhook when running in runtime cluster
  pkg/component/gardener/resourcemanager/resource_manager.go
  pkg/component/gardener/resourcemanager/resource_manager_test.go
  pkg/operator/controller/garden/garden/components.go
  test/integration/resourcemanager/podkubeapiserverloadbalancing/podkubeapiserverloadbalancing_suite_test.go
Labels: kind/bug, size/M, area/scalability, cla: yes, lgtm, approved

#12515 fix: remove limits on vpn-shoot
  pkg/component/networking/vpn/shoot/shoot.go
  pkg/component/networking/vpn/shoot/shoot_test.go
Labels: size/M, kind/cleanup, area/networking, cla: yes, lgtm, approved

#12478 Add validation for `Quota.spec.clusterLifetimeDays`
  pkg/apis/core/helper/quota.go
  pkg/apis/core/validation/quota.go
  pkg/apis/core/validation/quota_test.go
Labels: kind/enhancement, size/M, area/robustness, cla: yes, lgtm, approved

#12534 fix: remove limits on vpn envoy
  pkg/component/networking/vpn/envoy/envoy.go
Labels: size/XS, kind/cleanup, area/networking, cla: yes, lgtm, approved

#12524 Remove `ShootAPIServerProxyUsesHTTPProxy` constraint
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/gardenlet/operation/botanist/apiserverproxy.go
  pkg/gardenlet/operation/botanist/apiserverproxy_test.go
Labels: kind/enhancement, size/M, area/networking, cla: yes, lgtm, approved

#12540 Forbid container privilege escalation for prometheus `cleanup-obsolete-folder` container
  cmd/gardenlet/app/migration.go
  pkg/component/observability/monitoring/prometheus/prometheus.go
Labels: kind/enhancement, area/security, size/XS, area/compliance, cla: yes, lgtm, approved

#12541 Fix missing traffic distribution policy for `istio-ingress-gateway` internal service on certain Kubernetes versions
  pkg/component/networking/istio/charts/istio/istio-ingress/templates/service-internal.yaml
Labels: kind/bug, size/XS, area/scalability, cla: yes, lgtm, approved

#12428 [GEP-34] OpenTelemetry Collector for Shoots
  docs/deployment/feature_gates.md
  imagevector/containers.go
  imagevector/containers.yaml
  pkg/component/extensions/operatingsystemconfig/original/components/valitail/config.go
  pkg/component/observability/logging/vali/constants/constants.go
  pkg/component/observability/logging/vali/vali.go
  pkg/component/observability/opentelemetry/collector/collector.go
  pkg/component/observability/opentelemetry/collector/collector_suite_test.go
  pkg/component/observability/opentelemetry/collector/collector_test.go
  pkg/features/features.go
  pkg/gardenlet/features/features.go
  pkg/gardenlet/operation/botanist/botanist.go
  pkg/gardenlet/operation/botanist/logging.go
  pkg/gardenlet/operation/botanist/logging_test.go
  pkg/gardenlet/operation/shoot/types.go
  skaffold-gardenadm.yaml
  skaffold-seed.yaml
  skaffold.yaml
Labels: kind/enhancement, size/XL, area/logging, cla: yes, lgtm, approved

#12557 `gardener-resource-manager`: Explicitly filter for `kube-system` namespace when listing `Pod`s
  cmd/gardener-resource-manager/app/app.go
  pkg/resourcemanager/controller/node/criticalcomponents/reconciler.go
  test/integration/resourcemanager/node/criticalcomponents/criticalcomponents_suite_test.go
Labels: kind/bug, area/ops-productivity, size/S, cla: yes, lgtm, approved

#12556 Fix Flaking E2E Shoot Logging Test
  test/e2e/gardener/shoot/internal/observability/vali.go
Labels: size/XS, area/logging, kind/flake, cla: yes, lgtm, approved

#12552 Extract a script which can be used to re-add loopback IP addresses for kind containers
  docs/deployment/getting_started_locally.md
  hack/kind-extensions-up.sh
  hack/kind-setup-loopback-devices.sh
  hack/kind-up.sh
Labels: kind/enhancement, area/dev-productivity, size/L, cla: yes, lgtm, approved

#12480 Update opentelemetry-operator module, CRDs & image version
  go.mod
  go.sum
  imagevector/containers.yaml
  pkg/component/observability/opentelemetry/operator/assets/crd-opentelemetry.io_instrumentations.yaml
  pkg/component/observability/opentelemetry/operator/assets/crd-opentelemetry.io_opampbridges.yaml
  pkg/component/observability/opentelemetry/operator/assets/crd-opentelemetry.io_opentelemetrycollectors.yaml
  pkg/component/observability/opentelemetry/operator/assets/crd-opentelemetry.io_targetallocators.yaml
Labels: size/L, kind/task, area/logging, cla: yes, lgtm, approved

#12307 [GEP-28] `gardenadm bootstrap`: Wait for `Worker`
  dev-setup/gardenadm/resources/overlays/medium-touch/kustomization.yaml
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager_test.go
  pkg/component/nodemanagement/machinecontrollermanager/provider_test.go
  pkg/gardenadm/cmd/bootstrap/bootstrap.go
  pkg/provider-local/machine-provider/local/create_machine.go
  test/e2e/gardenadm/mediumtouch/gardenadm.go
Labels: kind/enhancement, size/L, cla: yes, lgtm, approved, area/ipcei

#12553 fix(hack): explicitly set umask in generate-controller-registration.sh
  hack/generate-controller-registration.sh
Labels: kind/bug, area/dev-productivity, size/XS, ok-to-test, cla: yes, lgtm, approved

#12577 Add in-place update filtering for machine images in maintenance controller
  pkg/controllermanager/controller/shoot/maintenance/reconciler.go
  pkg/controllermanager/controller/shoot/maintenance/reconciler_test.go
Labels: kind/enhancement, area/usability, area/quality, size/M, cla: yes, lgtm, approved

#11816 Proceed with replacement of Shoot `.spec.cloudProfileName` field in favor of `shoot.spec.cloudProfile` with new Kubernetes versions
  docs/api-reference/core.md
  docs/usage/shoot/shoot_kubernetes_versions.md
  pkg/api/core/shoot/warnings.go
  pkg/api/core/shoot/warnings_test.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/utils/gardener/cloudprofile.go
  pkg/utils/gardener/cloudprofile_test.go
  pkg/utils/version/version.go
  pkg/utils/version/version_test.go
Labels: kind/enhancement, area/usability, size/L, kind/cleanup, cla: yes, lgtm, approved

#12576 Remove `NodeAgentAuthorizer` feature gate
  cmd/gardener-node-agent/app/app.go
  docs/deployment/feature_gates.md
  pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit.go
  pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit_test.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/rbac.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/rbac_test.go
  pkg/features/features.go
  pkg/gardenadm/botanist/controlplane.go
  pkg/gardenadm/cmd/init/init.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/gardenlet/features/features.go
  pkg/gardenlet/operation/botanist/operatingsystemconfig.go
  pkg/gardenlet/operation/botanist/operatingsystemconfig_test.go
  pkg/nodeagent/apis/config/v1alpha1/types.go
  pkg/nodeagent/controller/add.go
  pkg/nodeagent/controller/operatingsystemconfig/changes.go
  pkg/nodeagent/controller/operatingsystemconfig/changes_test.go
  pkg/nodeagent/features/features.go
  pkg/resourcemanager/controller/csrapprover/reconciler.go
  test/integration/resourcemanager/csrapprover/csrapprover_suite_test.go
  test/integration/resourcemanager/csrapprover/csrapprover_test.go
Labels: kind/enhancement, area/security, size/XL, cla: yes, lgtm, approved

#12523 Enhance docs for dual-stack migration and add validation for update of ipFamilies.
  docs/api-reference/core.md
  docs/usage/networking/dual-stack-networking-migration.md
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/extensions/validation/network.go
  pkg/apis/extensions/validation/network_test.go
  pkg/apiserver/openapi/openapi_generated.go
Labels: kind/enhancement, area/documentation, size/M, area/networking, cla: yes, lgtm, approved

#12603 [release-v1.123] Replace DeepEqual with set equality for encrypted resources
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
Labels: kind/bug, size/S, cla: yes, lgtm, approved

#12601 chore: Disable major updates of go-toml by Renovate
  .github/renovate.json5
Labels: area/dev-productivity, area/open-source, kind/task, size/S, cla: yes, lgtm, approved

#12211 Allow gardener admins to manage services and endpoints in the virtual cluster
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
  pkg/component/garden/system/virtual/virtual.go
  pkg/component/garden/system/virtual/virtual_test.go
Labels: kind/enhancement, area/security, size/S, cla: yes, lgtm, approved

#12481 Add VPA maxAllowed field to the Shoot, Seed and Garden resources
  charts/gardener/operator/templates/crd-gardens.yaml
  docs/api-reference/core.md
  docs/api-reference/operator.md
  docs/usage/autoscaling/shoot_pod_autoscaling_best_practices.md
  example/50-seed.yaml
  example/90-shoot.yaml
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/core/types_seed.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/helper/seed.go
  pkg/apis/core/v1beta1/helper/seed_test.go
  pkg/apis/core/v1beta1/types_seed.go
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/helper/garden.go
  pkg/apis/operator/v1alpha1/helper/garden_test.go
  pkg/apis/operator/v1alpha1/types_garden.go
  pkg/apis/operator/v1alpha1/validation/garden.go
  pkg/apis/operator/v1alpha1/validation/garden_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/component/autoscaling/vpa/recommender.go
  pkg/component/autoscaling/vpa/vpa_test.go
  pkg/component/shared/vpa.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/operation/botanist/vpa.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/enhancement, area/auto-scaling, cla: yes, lgtm, approved, size/XXL

#12592 migrate CICD-Pipeline to GitHub-Actions
  .ci/component_descriptor
  .ci/pipeline_definitions
  .github/workflows/build.yaml
  .github/workflows/non-release.yaml
  .github/workflows/release.yaml
  .ocm/base-component.yaml
Labels: area/delivery, size/L, kind/task, kind/technical-debt, cla: yes, lgtm, approved

#12631 Run Github Release jobs from release branches only
  .github/workflows/release.yaml
Labels: kind/enhancement, area/delivery, size/XS, cla: yes, lgtm, approved

#12620 Graduate `UseNamespacedCloudProfile` feature gate to GA
  docs/deployment/feature_gates.md
  pkg/apiserver/registry/core/shoot/strategy_test.go
  pkg/features/features.go
  pkg/utils/gardener/cloudprofile.go
  pkg/utils/gardener/cloudprofile_test.go
  skaffold-gardenadm.yaml
  skaffold-operator.yaml
  skaffold-seed.yaml
  skaffold.yaml
  test/integration/controllermanager/namespacedcloudprofile/namespacedcloudprofile_suite_test.go
  test/integration/controllermanager/project/project/project_suite_test.go
Labels: kind/enhancement, area/usability, size/L, cla: yes, lgtm, approved

#12632 Update the build badge from Concourse to GitHub Actions
  README.md
Labels: area/delivery, size/XS, kind/cleanup, cla: yes, lgtm, approved

#12636 Build artifacts only on head update of `master` and `release` branches
  .github/workflows/non-release.yaml
Labels: kind/enhancement, area/delivery, area/cost, size/XS, cla: yes, lgtm, approved

#12634 gardenadm: Ignore hidden files and folders when loading manifests
  pkg/gardenadm/resources.go
  pkg/gardenadm/resources_test.go
Labels: kind/enhancement, size/S, cla: yes, lgtm, approved, area/ipcei

#12635 Fix many-to-many matching error in istio dashboards
  pkg/component/observability/plutono/dashboards/garden-seed/istio/istio-service-dashboard.json
  pkg/component/observability/plutono/dashboards/garden-seed/istio/istio-workload-dashboard.json
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved

#12630 Clean up annotations of kube-apiserver service to purge old load balancer annotations.
  pkg/component/kubernetes/apiserverexposure/service.go
  pkg/component/kubernetes/apiserverexposure/service_test.go
Labels: size/XS, area/robustness, kind/cleanup, area/networking, area/control-plane, cla: yes, lgtm, approved

#12639 export testresults as inlined ocm-resource
  .github/workflows/build.yaml
Labels: kind/task, size/S, area/compliance, cla: yes, lgtm, approved

#12589 Prevent `gardener-node-agent` entering crash-loop on breaking changes to config
  cmd/gardener-node-agent/app/app.go
  cmd/gardener-node-agent/app/options.go
  pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit.go
  pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit_test.go
  pkg/component/extensions/operatingsystemconfig/nodeinit/templates/scripts/init.tpl.sh
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component_test.go
  pkg/gardenadm/botanist/operatingsystemconfig.go
  pkg/gardenadm/botanist/operatingsystemconfig_test.go
  pkg/nodeagent/apis/config/v1alpha1/helper/utils.go
  pkg/nodeagent/apis/config/v1alpha1/types.go
  pkg/nodeagent/bootstrap/bootstrap_test.go
  pkg/nodeagent/certificate.go
  pkg/nodeagent/certificate_test.go
  pkg/nodeagent/controller/add.go
  pkg/nodeagent/controller/certificate/reconciler.go
  pkg/nodeagent/controller/operatingsystemconfig/reconciler.go
  pkg/nodeagent/controller/operatingsystemconfig/reconciler_test.go
  skaffold-gardenadm.yaml
  skaffold-seed.yaml
  skaffold.yaml
  test/integration/nodeagent/operatingsystemconfig/operatingsystemconfig_test.go
Labels: kind/bug, size/L, area/robustness, cla: yes, lgtm, approved

#12643 fix: Maintain feature gate `ValidatingAdmissionPolicy` as removed with Kubernetes v1.32
  pkg/utils/validation/features/featuregates.go
Labels: kind/bug, size/XS, area/usability, area/quality, cla: yes, lgtm, approved

#12651 [release-v1.122] fix: Maintain feature gate ValidatingAdmissionPolicy as removed with Kubernetes v1.32
  pkg/utils/validation/features/featuregates.go
Labels: kind/bug, size/XS, area/usability, area/quality, cla: yes, lgtm, approved
