Repository gardener/gardener, pull requests merged in 2025-03, with the labels that each got.

#11532 [Flaky Tests] Update/revert `kindest/node` to `v1.32.0`
  .github/renovate.json5
  example/gardener-local/kind/cluster/values.yaml
  hack/kind-up.sh
  pkg/provider-local/node/.gitignore
  pkg/provider-local/node/Dockerfile
  pkg/provider-local/node/get-runc.sh
Labels: size/M, area/testing, kind/flake, cla: yes, lgtm, approved

#11540 Refactor `create_update_delete` Shoot e2e test to ordered `It` containers
  test/e2e/gardener/shoot/create_update_delete.go
  test/utils/shoots/update/update.go
Labels: kind/enhancement, size/L, area/testing, cla: yes, lgtm, approved

#11560 Drop obsolete linter exclude
  .golangci.yaml.in
Labels: size/XS, kind/cleanup, cla: yes, lgtm, approved

#11564 chore: Restrict Renovate kindest/node updates
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#11565 Start using shared renovate config presets
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#11515 Fix shoot care controller removing conditions/constraints
  pkg/gardenlet/controller/shoot/care/reconciler.go
  pkg/gardenlet/controller/shoot/care/reconciler_test.go
Labels: kind/bug, size/L, area/robustness, cla: yes, lgtm, approved

#11252 Add `minAllowed` configuration option to `Shoot`
  charts/gardener/operator/templates/crd-gardens.yaml
  docs/api-reference/core.md
  docs/api-reference/operator.md
  docs/development/autoscaling-specifics-for-components.md
  example/90-shoot.yaml
  example/operator/10-crd-operator.gardener.cloud_gardens.yaml
  example/operator/20-garden.yaml
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/types_garden.go
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/component/apiserver/types.go
  pkg/component/etcd/etcd/etcd.go
  pkg/component/etcd/etcd/etcd_test.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/verticalpodautoscaler.go
  pkg/gardenlet/operation/botanist/etcd.go
  pkg/gardenlet/operation/botanist/etcd_test.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
  pkg/operator/controller/garden/garden/components.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/kubernetes_test.go
Labels: kind/enhancement, area/auto-scaling, cla: yes, lgtm, approved, size/XXL

#11376 chore: Improve `get-skaffold-cache-artifacts.sh`
  Makefile
  hack/get-skaffold-cache-artifacts.sh
Labels: kind/enhancement, area/dev-productivity, size/M, cla: yes, lgtm, approved

#11561 Fix flake in CSINode test
  test/e2e/gardener/shoot/internal/node/node.go
Labels: area/dev-productivity, size/XS, area/robustness, kind/flake, cla: yes, lgtm, approved

#11555 Reintroduce an e2e test with a shoot using L4 load balancing
  docs/deployment/content/remote-local-setup.yaml
  hack/test-e2e-local.sh
  test/e2e/gardener/shoot/create_authenticate_delete.go
  test/e2e/gardener/shoot/create_update_delete.go
Labels: kind/enhancement, size/L, area/testing, cla: yes, lgtm, approved

#11128 Align `CRD` deployment to use the `CRDDeployer`
  charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
  charts/gardener/gardenlet/test/test.go
  pkg/component/crddeployer/crd.go
  pkg/component/crddeployer/crd_test.go
  pkg/component/extensions/crds/crds.go
  pkg/component/extensions/crds/crds_test.go
  pkg/component/nodemanagement/machinecontrollermanager/crd.go
  pkg/component/nodemanagement/machinecontrollermanager/crd_test.go
  pkg/component/observability/logging/fluentoperator/crds.go
  pkg/component/observability/logging/fluentoperator/crds_test.go
  pkg/component/observability/monitoring/prometheusoperator/crd.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
  pkg/operator/controller/garden/garden/components.go
  skaffold-gardenadm.yaml
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/resourcemanager/crddeletionprotection/crddeletionprotection_test.go
Labels: size/L, area/robustness, kind/cleanup, cla: yes, lgtm, approved

#11566 Automerge patch and `k8s.io/utils` updates
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#11580 Fix `Gardenlet` Reconciliation
  pkg/controller/gardenletdeployer/actuator.go
  pkg/controller/gardenletdeployer/actuator_test.go
  pkg/gardenlet/controller/managedseed/reconciler.go
  pkg/operator/controller/gardenlet/add.go
  pkg/operator/controller/gardenlet/reconciler.go
Labels: kind/bug, area/delivery, size/S, cla: yes, lgtm, approved

#11523 [operator] Wait for required `Extension`s
  docs/concepts/operator.md
  docs/development/testing.md
  pkg/apis/operator/v1alpha1/helper/extension.go
  pkg/apis/operator/v1alpha1/helper/extension_test.go
  pkg/apis/operator/v1alpha1/helper/garden.go
  pkg/apis/operator/v1alpha1/helper/garden_test.go
  pkg/gardenlet/controller/controllerinstallation/required/add.go
  pkg/operator/controller/extension/extension/runtime/runtime.go
  pkg/operator/controller/extension/required/runtime/add.go
  pkg/operator/controller/extension/required/runtime/add_test.go
  pkg/operator/controller/extension/required/runtime/reconciler.go
  pkg/operator/controller/garden/garden/reconciler.go
  pkg/operator/controller/garden/garden/reconciler_delete.go
  pkg/operator/controller/garden/garden/reconciler_reconcile.go
  pkg/utils/gardener/garden.go
  pkg/utils/gardener/garden_test.go
  pkg/utils/gardener/seed.go
  pkg/utils/gardener/seed_test.go
  skaffold-gardenadm.yaml
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/operator/extension/required/runtime/runtime_suite_test.go
  test/integration/operator/extension/required/runtime/runtime_test.go
  test/integration/operator/garden/garden/garden_suite_test.go
  test/integration/operator/garden/garden/garden_test.go
Labels: kind/enhancement, area/robustness, cla: yes, lgtm, approved, size/XXL

#11559 Prepare next Dev Cycle `v1.115.0-dev`
  VERSION
Labels: area/delivery, size/XS, kind/task, cla: yes, lgtm, approved

#11526 Issue 11505: CoreDNS not truly configurable / import *.override not working as intended
  docs/usage/networking/custom-dns-config.md
  pkg/component/networking/coredns/coredns.go
  pkg/component/networking/coredns/coredns_test.go
Labels: kind/enhancement, size/M, area/networking, ok-to-test, cla: yes, lgtm, approved

#11587 Fix `apiserver-proxy` connectivity when using feature gates `IstioTLSTermination` and `RemoveAPIServerProxyLegacyPort`
  pkg/component/kubernetes/apiserverexposure/sni.go
  pkg/component/kubernetes/apiserverexposure/templates/envoyfilter-apiserver-proxy.yaml
Labels: kind/bug, area/robustness, area/networking, size/S, cla: yes, lgtm, approved

#11591 Automerge non-major golang.org/x Renovate updates
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#11586 Fixes restoration of multi-node etcds during control plane migration of HA `Shoot`s
  pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
Labels: kind/bug, size/S, area/control-plane-migration, cla: yes, lgtm, approved

#11550 Override machine image `updateStrategy` from `NamespacedCloudProfile`
  docs/usage/project/namespaced-cloud-profiles.md
  example/35-namespacedcloudprofile.yaml
  pkg/apis/core/helper/cloudprofile.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/cloudprofile_test.go
  pkg/apis/core/validation/namespacedcloudprofile.go
  pkg/apis/core/validation/namespacedcloudprofile_test.go
  pkg/apis/core/validation/utils.go
  pkg/apiserver/registry/core/namespacedcloudprofile/strategy.go
  pkg/apiserver/registry/core/namespacedcloudprofile/strategy_test.go
  pkg/controllermanager/controller/namespacedcloudprofile/reconciler.go
  pkg/controllermanager/controller/namespacedcloudprofile/reconciler_test.go
  plugin/pkg/namespacedcloudprofile/validator/admission.go
  plugin/pkg/namespacedcloudprofile/validator/admission_test.go
Labels: kind/enhancement, area/ops-productivity, area/usability, size/L, area/os, cla: yes, lgtm, approved

#11593 Make garden access for extensions an explicit opt-in feature
  charts/gardener/operator/templates/crd-extensions.yaml
  docs/api-reference/core-v1.md
  docs/api-reference/core.md
  docs/api-reference/operator.md
  docs/deployment/setup_gardener.md
  docs/extensions/garden-api-access.md
  example/25-controllerdeployment.yaml
  example/operator/10-crd-operator.gardener.cloud_extensions.yaml
  example/operator/15-extension.yaml
  example/provider-local/garden/local/controllerdeployment.yaml
  example/provider-local/garden/operator/extension-patch.yaml
  pkg/apis/core/types_controllerdeployment.go
  pkg/apis/core/v1/generated.pb.go
  pkg/apis/core/v1/generated.proto
  pkg/apis/core/v1/types_controllerdeployment.go
  pkg/apis/core/v1/zz_generated.conversion.go
  pkg/apis/core/v1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_controllerdeployment.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/types_extension.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go
  pkg/operator/controller/extension/extension/controllerregistration/controllerregistration.go
  pkg/operator/controller/extension/extension/controllerregistration/controllerregistration_test.go
  pkg/utils/gardener/secrets.go
  pkg/utils/gardener/secrets_test.go
  skaffold.yaml
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
  test/integration/gardenlet/controllerinstallation/controllerinstallation/testdata/chart-with-garden-kubeconfig/Chart.yaml
  test/integration/gardenlet/controllerinstallation/controllerinstallation/testdata/chart-with-garden-kubeconfig/templates/config.yaml
  test/integration/gardenlet/controllerinstallation/controllerinstallation/testdata/chart-with-garden-kubeconfig/templates/deployment.yaml
  test/integration/gardenlet/controllerinstallation/controllerinstallation/testdata/chart-without-garden-kubeconfig/Chart.yaml
  test/integration/gardenlet/controllerinstallation/controllerinstallation/testdata/chart-without-garden-kubeconfig/templates/config.yaml
  test/integration/gardenlet/controllerinstallation/controllerinstallation/testdata/chart-without-garden-kubeconfig/templates/deployment.yaml
Labels: kind/enhancement, area/security, cla: yes, lgtm, approved, size/XXL

#11604 Improve printer columns for `operator.gardener.cloud/v1alpha1.Extension`
  charts/gardener/operator/templates/crd-extensions.yaml
  example/operator/10-crd-operator.gardener.cloud_extensions.yaml
  pkg/apis/operator/v1alpha1/types_extension.go
Labels: kind/enhancement, area/usability, size/S, cla: yes, lgtm, approved

#11605 Prevent reconciliation errors in `NetworkPolicy` controller when `Namespace` is terminating
  pkg/resourcemanager/controller/networkpolicy/reconciler.go
Labels: kind/enhancement, area/ops-productivity, size/S, cla: yes, lgtm, approved

#11608 Update go version in `go.mod`
  go.mod
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#11480 [GEP-30] Enable `RemoveAPIServerProxyLegacyPort` feature gate for local setup
  example/gardener-local/gardenlet/values.yaml
  test/utils/shoots/update/highavailability/upgrade.go
Labels: kind/enhancement, size/M, area/networking, area/testing, cla: yes, lgtm, approved

#11609 Document how to federate metrics from the shoot Prometheus
  docs/monitoring/README.md
Labels: kind/enhancement, area/documentation, size/M, cla: yes, lgtm, approved

#11606 [operator] Add deletion protection for `Extension`s
  cmd/gardener-operator/app/app.go
  docs/concepts/operator.md
  hack/operator-seed-down.sh
  pkg/operator/webhook/add.go
  pkg/operator/webhook/defaulting/add.go
  pkg/operator/webhook/defaulting/garden/garden_suite_test.go
  pkg/operator/webhook/defaulting/garden/handler.go
  pkg/operator/webhook/defaulting/garden/handler_test.go
  pkg/operator/webhook/defaulting/handler.go
  pkg/operator/webhook/validation/add.go
  pkg/operator/webhook/validation/extension/add.go
  pkg/operator/webhook/validation/extension/extension_suite_test.go
  pkg/operator/webhook/validation/extension/handler.go
  pkg/operator/webhook/validation/extension/handler_test.go
  pkg/operator/webhook/validation/garden/add.go
  pkg/operator/webhook/validation/garden/garden_suite_test.go
  pkg/operator/webhook/validation/garden/handler.go
  pkg/operator/webhook/validation/garden/handler_test.go
  skaffold-operator.yaml
Labels: kind/enhancement, size/XL, area/robustness, cla: yes, lgtm, approved

#11613 [renovate] Rebase PRs on conflicts only
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#11617 Add missing `g.` to `Expect`s in `ControllerInstallation` integration test
  test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#11614 [GEP-28] Add bootstrap etcd component for deploying etcd to bootstrap a control plane node in the autonomous shoot cluster scenario.
  pkg/component/etcd/bootstrap/etcd.go
  pkg/component/etcd/bootstrap/etcd_suite_test.go
  pkg/component/etcd/bootstrap/etcd_test.go
  pkg/component/etcd/etcd/etcd.go
Labels: kind/enhancement, size/L, cla: yes, lgtm, approved, area/ipcei

#11539 refactor validateProvider in the shoot admission plugin
  plugin/pkg/shoot/validator/admission.go
Labels: area/dev-productivity, size/L, kind/cleanup, cla: yes, lgtm, approved

#11616 Refactor `seed` integration test not to use `gstruct` Matcher
  pkg/utils/test/objectnames.go
  test/integration/gardenlet/seed/seed/seed_test.go
  test/integration/operator/garden/garden/garden_test.go
Labels: size/L, kind/cleanup, area/testing, cla: yes, lgtm, approved

#11637 `CreateShoot` testdefinition exposes `minAllowed` options for control plane
  .test-defs/CreateShoot.yaml
  test/framework/shoot_utils.go
  test/framework/shootcreationframework.go
Labels: kind/enhancement, size/L, area/testing, cla: yes, lgtm, approved

#11638 Fix `check-generate` script for extensions
  hack/check-generate.sh
Labels: kind/bug, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#11642 local setup: Remove wrongly added stale files
  example/provider-local/garden/local/patch-imagevector-overwrite.yaml
  example/provider-local/garden/operator/patch-imagevector-overwrite.yaml
Labels: area/dev-productivity, kind/cleanup, size/S, cla: yes, lgtm, approved

#11624 Release responsible schedule for v1.117 until v1.129
  docs/development/process.md
Labels: kind/enhancement, area/delivery, size/L, cla: yes, lgtm, approved

#11178 Use ServiceTrafficDistribution to make Services topology-aware when runtime Kubernetes >= 1.31
  charts/gardener/admission-local/charts/runtime/templates/service.yaml
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/service.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/service.yaml
  docs/concepts/gardenlet.md
  docs/concepts/resource-manager.md
  docs/operations/topology_aware_routing.md
  pkg/component/autoscaling/vpa/admissioncontroller.go
  pkg/component/autoscaling/vpa/vpa_test.go
  pkg/component/etcd/etcd/etcd.go
  pkg/component/etcd/etcd/etcd_test.go
  pkg/component/gardener/admissioncontroller/admission_controller.go
  pkg/component/gardener/admissioncontroller/admission_controller_test.go
  pkg/component/gardener/admissioncontroller/service.go
  pkg/component/gardener/apiserver/service.go
  pkg/component/gardener/dashboard/terminal/service.go
  pkg/component/gardener/dashboard/terminal/terminal.go
  pkg/component/gardener/dashboard/terminal/terminal_test.go
  pkg/component/gardener/resourcemanager/resource_manager.go
  pkg/component/kubernetes/apiserverexposure/service.go
  pkg/component/kubernetes/apiserverexposure/service_test.go
  pkg/gardenadm/botanist.go
  pkg/gardenlet/controller/seed/seed/components.go
  pkg/gardenlet/operation/botanist/etcd.go
  pkg/gardenlet/operation/botanist/etcd_test.go
  pkg/gardenlet/operation/botanist/resource_manager.go
  pkg/operator/controller/garden/garden/components.go
  pkg/utils/gardener/topology_aware_routing.go
  pkg/utils/gardener/topology_aware_routing_test.go
  pkg/utils/version/version.go
  pkg/utils/version/version_test.go
Labels: kind/enhancement, size/XL, area/networking, area/high-availability, cla: yes, lgtm, approved

#11659 Set `revisionHistoryLimit=2` also for `DaemonSet`s
  docs/development/component-checklist.md
  pkg/component/kubernetes/proxy/proxy_test.go
  pkg/component/kubernetes/proxy/resources.go
  pkg/component/networking/apiserverproxy/apiserver_proxy.go
  pkg/component/networking/apiserverproxy/apiserver_proxy_test.go
  pkg/component/networking/nodelocaldns/nodelocaldns.go
  pkg/component/networking/nodelocaldns/nodelocaldns_test.go
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/seedserver/seedserver_test.go
  pkg/component/nodemanagement/nodeproblemdetector/node_problem_detector.go
  pkg/component/nodemanagement/nodeproblemdetector/node_problem_detector_test.go
  pkg/component/observability/monitoring/nodeexporter/nodeexporter.go
  pkg/component/observability/monitoring/nodeexporter/nodeexporter_test.go
Labels: kind/enhancement, size/S, area/scalability, cla: yes, lgtm, approved

#11636 [renovate] Disable major updates of jsonpatch/v2
  .github/renovate.json5
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#11646 Update dependency gardener/autoscaler to `v1.31.0`
  imagevector/containers.yaml
Labels: kind/enhancement, size/XS, area/control-plane, cla: yes, lgtm, approved

#11651 docs: Extend Kubernetes release responsible tasks
  docs/development/new-kubernetes-version.md
Labels: kind/enhancement, area/dev-productivity, area/open-source, size/S, cla: yes, lgtm, approved

#11655 Simplify admission plugin enablement for kube-apiserver
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/utils/kubernetes/admissionplugins.go
  pkg/utils/kubernetes/admissionplugins_test.go
Labels: area/quality, size/L, kind/technical-debt, kind/cleanup, cla: yes, lgtm, approved

#11603 e2e: Refactor `Create Delete Garden` test to ordered containers
  test/e2e/gardener/context.go
  test/e2e/operator/garden/create_delete.go
  test/e2e/operator/garden/internal/garden.go
Labels: kind/enhancement, area/dev-productivity, size/XL, cla: yes, lgtm, approved

#11623 Enable Gardener Node Agent to properly configure containerd 2.0 which introduced v3 of its config file
  pkg/nodeagent/controller/operatingsystemconfig/containerd.go
  pkg/nodeagent/controller/operatingsystemconfig/containerd_config.go
  pkg/nodeagent/controller/operatingsystemconfig/containerd_config_test.go
  pkg/nodeagent/controller/operatingsystemconfig/testfiles/containerd-config.toml-v2
  pkg/nodeagent/controller/operatingsystemconfig/testfiles/containerd-config.toml-v3
  test/integration/nodeagent/operatingsystemconfig/operatingsystemconfig_test.go
Labels: kind/enhancement, area/os, cla: yes, lgtm, approved, size/XXL

#11622 Enable the `VerticalPodAutoscalerCappedRecommendation` alerts
  pkg/component/observability/monitoring/prometheus/garden/assets/prometheusrules/seed.yaml
  pkg/component/observability/monitoring/prometheus/garden/assets/prometheusrules/shoot.yaml
  pkg/component/observability/monitoring/prometheus/garden/prometheusrules.go
  pkg/component/observability/monitoring/prometheus/garden/testdata/seed.prometheusrule.test.yaml
  pkg/component/observability/monitoring/prometheus/garden/testdata/shoot.prometheusrule.test.yaml
Labels: kind/enhancement, area/monitoring, size/S, cla: yes, lgtm, approved

#11662 ssh reverse tunnel: Exit on error
  example/provider-extensions/ssh-reverse-tunnel/base/sshd/files/entrypoint.sh
Labels: kind/enhancement, area/dev-productivity, size/XS, cla: yes, lgtm, approved

#11667 Fix authentication panel in API server dashboard
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/servicemonitor.go
Labels: kind/bug, size/XS, area/monitoring, cla: yes, lgtm, approved

#11669 Fixed broken links - 2025.03
  docs/development/new-kubernetes-version.md
  docs/extensions/resources/backupentry.md
  docs/extensions/resources/worker.md
  docs/usage/autoscaling/shoot_pod_autoscaling_best_practices.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#11676 Fix a broken link
  docs/concepts/gardenlet.md
Labels: size/XS, area/documentation, kind/cleanup, cla: yes, lgtm, approved

#11631 [GEP 31] Adapt API changes for `machine-controller-manager`
  docs/api-reference/core.md
  example/seed-crds/10-crd-extensions.gardener.cloud_workers.yaml
  extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  extensions/pkg/controller/worker/machines.go
  pkg/apis/core/types_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot.go
  pkg/apis/core/v1beta1/defaults_shoot_test.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_shoot.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/shoot.go
  pkg/apis/core/validation/shoot_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/api_violations.report
  pkg/apiserver/openapi/openapi_generated.go
  pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_workers.yaml
  pkg/component/extensions/worker/worker.go
  pkg/component/extensions/worker/worker_test.go
  pkg/provider-local/controller/worker/machines.go
Labels: kind/enhancement, area/delivery, area/open-source, area/control-plane, area/scalability, cla: yes, lgtm, approved, size/XXL

#11682 Update list of gardener extensions
  extensions/README.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#11549 e2e: Refactor update-Shoot-to-HA (and Gardener upgrade) e2e tests to ordered `It` containers
  Makefile
  hack/ci-e2e-kind-upgrade.sh
  test/e2e/gardener/common.go
  test/e2e/gardener/e2e_suite_test.go
  test/e2e/gardener/shoot/create_delete_failed.go
  test/e2e/gardener/shoot/create_delete_hibernated.go
  test/e2e/gardener/shoot/create_delete_unprivileged.go
  test/e2e/gardener/shoot/create_force-delete.go
  test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go
  test/e2e/gardener/shoot/create_update_delete.go
  test/e2e/gardener/shoot/gardenerupgrade/create_hibernate_upgrade_wakeup_delete.go
  test/e2e/gardener/shoot/gardenerupgrade/create_upgrade_delete.go
  test/e2e/gardener/shoot/gardenerupgrade/create_upgrade_update-to-ha_delete.go
  test/e2e/gardener/shoot/gardenerupgrade/upgrade.go
  test/e2e/gardener/shoot/internal/highavailability/highavailability.go
  test/e2e/gardener/shoot/internal/shoot.go
  test/e2e/gardener/shoot/internal/zerodowntimevalidator/validator.go
  test/e2e/gardener/shoot/update-to-ha.go
  test/e2e/gardener/shoot/upgrade_non-ha_to_node.go
  test/e2e/gardener/shoot/upgrade_non-ha_to_zone.go
  test/e2e/gardener/upgrade/upgrade.go
  test/utils/shoots/update/highavailability/upgrade.go
  test/utils/shoots/update/update.go
Labels: kind/enhancement, area/testing, cla: yes, lgtm, approved, size/XXL

#11519 Forbid container privilege escalations for Seed and Garden cluster components
  charts/gardener/admission-local/charts/runtime/templates/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/admission-controller/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/deployment.yaml
  charts/gardener/controlplane/charts/runtime/templates/scheduler/deployment.yaml
  charts/gardener/gardenlet/templates/deployment.yaml
  charts/gardener/gardenlet/test/test.go
  charts/gardener/operator/templates/deployment.yaml
  charts/gardener/provider-local/templates/deployment.yaml
  charts/gardener/resource-manager/charts/runtime/templates/deployment.yaml
  example/gardener-local/etcd/statefulset.yaml
  example/gardener-local/registry/base/registry.yaml
  example/provider-extensions/gardener-discovery-server/server/server.yaml
  example/provider-extensions/registry-seed/registry/registry.yaml
  pkg/component/etcd/etcd/bootstrap.go
  pkg/component/etcd/etcd/bootstrap_test.go
  pkg/component/gardener/admissioncontroller/admission_controller_test.go
  pkg/component/gardener/admissioncontroller/deployment.go
  pkg/component/gardener/apiserver/apiserver_test.go
  pkg/component/gardener/apiserver/deployment.go
  pkg/component/gardener/controllermanager/controller_manager_test.go
  pkg/component/gardener/controllermanager/deployment.go
  pkg/component/gardener/dashboard/dashboard_test.go
  pkg/component/gardener/dashboard/deployment.go
  pkg/component/gardener/discoveryserver/deployment.go
  pkg/component/gardener/discoveryserver/discoveryserver_test.go
  pkg/component/gardener/resourcemanager/resource_manager.go
  pkg/component/gardener/resourcemanager/resource_manager_test.go
  pkg/component/gardener/scheduler/deployment.go
  pkg/component/gardener/scheduler/scheduler_test.go
  pkg/component/networking/nginxingress/nginxingress.go
  pkg/component/networking/nginxingress/nginxingress_test.go
  pkg/component/networking/vpn/authzserver/authzserver.go
  pkg/component/networking/vpn/authzserver/authzserver_test.go
  pkg/component/nodemanagement/dependencywatchdog/bootstrap.go
  pkg/component/nodemanagement/dependencywatchdog/bootstrap_test.go
  pkg/component/observability/logging/fluentbit/fluentbit.go
  pkg/component/observability/logging/fluentoperator/fluentoperator.go
  pkg/component/observability/logging/fluentoperator/fluentoperator_test.go
  pkg/component/observability/monitoring/gardenermetricsexporter/deployment.go
  pkg/component/observability/monitoring/gardenermetricsexporter/gardener_metrics_exporter_test.go
  pkg/component/observability/monitoring/prometheus/cortex.go
  pkg/component/observability/monitoring/prometheus/prometheus_test.go
  pkg/component/seed/system/system.go
  pkg/component/seed/system/system_test.go
  pkg/provider-local/charts/shoot-system-components/charts/local-path-provisioner/templates/deployment.yaml
Labels: kind/enhancement, area/security, size/L, area/compliance, cla: yes, lgtm, approved

#11647 Allow override of maximum node count per shoot from `CloudProfile` in `NamespacedCloudProfile`
  docs/api-reference/core.md
  docs/usage/shoot/shoot_limits.md
  example/35-namespacedcloudprofile.yaml
  pkg/apis/core/types_namespacedcloudprofile.go
  pkg/apis/core/v1beta1/generated.pb.go
  pkg/apis/core/v1beta1/generated.proto
  pkg/apis/core/v1beta1/types_namespacedcloudprofile.go
  pkg/apis/core/v1beta1/zz_generated.conversion.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apis/core/validation/cloudprofile.go
  pkg/apis/core/validation/namespacedcloudprofile.go
  pkg/apis/core/validation/namespacedcloudprofile_test.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apiserver/openapi/openapi_generated.go
  pkg/controllermanager/controller/namespacedcloudprofile/reconciler.go
  pkg/controllermanager/controller/namespacedcloudprofile/reconciler_test.go
  pkg/gardenlet/operation/botanist/clusterautoscaler.go
  pkg/gardenlet/operation/botanist/clusterautoscaler_test.go
  pkg/utils/numbers.go
  pkg/utils/numbers_test.go
  plugin/pkg/global/resourcereferencemanager/admission.go
  plugin/pkg/global/resourcereferencemanager/admission_test.go
  plugin/pkg/namespacedcloudprofile/validator/admission.go
  plugin/pkg/namespacedcloudprofile/validator/admission_test.go
  test/integration/controllermanager/namespacedcloudprofile/namespacedcloudprofile_test.go
Labels: kind/enhancement, area/usability, area/robustness, cla: yes, lgtm, approved, size/XXL

#11668 Fix `kube-proxy` race condition
  pkg/component/kubernetes/proxy/proxy_test.go
  pkg/component/kubernetes/proxy/resources.go
Labels: kind/bug, kind/enhancement, area/quality, size/M, cla: yes, lgtm, approved

#11675 Keep envoyfilters for L7 load-balancing unless no shoot is using this feature anymore
  pkg/component/kubernetes/apiserverexposure/sni.go
  pkg/component/networking/istio/ingress_gateway.go
  pkg/component/networking/istio/istio_test.go
  pkg/component/networking/istio/istiod.go
Labels: kind/bug, size/M, area/control-plane, cla: yes, lgtm, approved

#11695 Use explicit verbs for role(bindings) permissions in gardener.cloud:admin role
  charts/gardener/controlplane/charts/application/templates/rbac-user.yaml
  pkg/component/garden/system/virtual/virtual.go
  pkg/component/garden/system/virtual/virtual_test.go
Labels: kind/enhancement, area/security, size/S, cla: yes, lgtm, approved

#11671 Fix wildcard certificate endpoints of shoots and virtual-garden
  pkg/component/kubernetes/apiserverexposure/sni.go
  pkg/component/kubernetes/apiserverexposure/sni_test.go
  pkg/gardenlet/operation/botanist/kubeapiserverexposure.go
  pkg/operator/controller/garden/garden/components.go
  pkg/operator/controller/garden/garden/components_test.go
Labels: kind/bug, size/XL, area/control-plane, cla: yes, lgtm, approved

#11665 [GEP-28] Add support for `kubelet` bootstrap kubeconfig handling
  pkg/admissioncontroller/webhook/auth/seed/authorizer.go
  pkg/admissioncontroller/webhook/auth/seed/authorizer_test.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_gardenlet.go
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_managedseed.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
  pkg/controller/gardenletdeployer/actuator.go
  pkg/controller/gardenletdeployer/actuator_test.go
  pkg/gardenadm/cmd/init/kubelet.go
  pkg/gardenadm/cmd/init/kubelet_test.go
  pkg/gardenlet/bootstrap/util/util.go
  pkg/gardenlet/bootstrap/util/util_test.go
  pkg/utils/kubernetes/bootstraptoken/bootstraptoken.go
  pkg/utils/kubernetes/bootstraptoken/bootstraptoken_suite_test.go
  pkg/utils/kubernetes/bootstraptoken/bootstraptoken_test.go
  skaffold-gardenadm.yaml
Labels: kind/enhancement, size/L, cla: yes, lgtm, approved, area/ipcei

#11698 [Flaky Test] Wrap create calls in Eventually blocks.
  test/integration/controllermanager/namespacedcloudprofile/namespacedcloudprofile_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#11684 Remove `HPA` from `gardener-apiserver`
  docs/development/autoscaling-specifics-for-components.md
  pkg/component/apiserver/types.go
  pkg/component/gardener/apiserver/apiserver.go
  pkg/component/gardener/apiserver/apiserver_test.go
  pkg/component/gardener/apiserver/deployment.go
  pkg/component/gardener/apiserver/hpa.go
  pkg/component/gardener/apiserver/vpa.go
  pkg/component/kubernetes/apiserver/apiserver.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/shared/gardenerapiserver.go
  pkg/component/shared/gardenerapiserver_test.go
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/kubeapiserver_test.go
  pkg/operator/controller/garden/garden/components.go
Labels: kind/enhancement, size/L, area/control-plane, area/auto-scaling, cla: yes, lgtm, approved

#11706 Fix func IsServedByGardenerAPIServer to check all served groups
  pkg/apis/operator/v1alpha1/validation/validation.go
  pkg/apis/operator/v1alpha1/validation/validation_test.go
  pkg/utils/gardener/garden.go
  pkg/utils/gardener/garden_test.go
  skaffold-gardenadm.yaml
  skaffold-operator.yaml
  skaffold.yaml
Labels: kind/bug, size/M, cla: yes, lgtm, approved

#11705 [resource-manager] Ignore "not found" errors when listing non-existent CRDs
  pkg/resourcemanager/controller/garbagecollector/reconciler.go
Labels: kind/bug, area/usability, size/S, cla: yes, lgtm, approved

#11702 Reuse `generate-crds.sh` for foreign packages
  hack/generate-crds.sh
Labels: kind/enhancement, area/dev-productivity, size/S, cla: yes, lgtm, approved

#11714 Graduate feature gate 'NewVPN' to 'GA'
  docs/deployment/feature_gates.md
  docs/usage/networking/shoot_networking.md
  imagevector/containers.go
  imagevector/containers.yaml
  pkg/apis/core/v1beta1/constants/types_constants.go
  pkg/apis/core/validation/seed.go
  pkg/apis/core/validation/seed_test.go
  pkg/component/kubernetes/apiserver/apiserver.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/networking/vpn/seedserver/seedserver.go
  pkg/component/networking/vpn/seedserver/seedserver_test.go
  pkg/component/networking/vpn/shoot/shoot.go
  pkg/component/networking/vpn/shoot/shoot_test.go
  pkg/component/shared/kubeapiserver.go
  pkg/features/features.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/botanist/vpnseedserver.go
  pkg/gardenlet/operation/botanist/vpnshoot.go
  pkg/gardenlet/operation/shoot/shoot.go
  pkg/gardenlet/operation/shoot/types.go
  pkg/utils/validation/cidr/disjoint.go
  pkg/utils/validation/cidr/disjoint_test.go
  plugin/pkg/shoot/validator/admission_test.go
Labels: kind/enhancement, size/XL, area/networking, cla: yes, lgtm, approved

#11696 Keep extension.operator as `RequiredRuntime` until extension.extension deleted
  pkg/operator/controller/extension/required/runtime/add.go
  pkg/operator/controller/extension/required/runtime/add_test.go
  pkg/operator/controller/extension/required/runtime/reconciler.go
  skaffold-operator.yaml
  test/integration/operator/extension/required/runtime/runtime_suite_test.go
  test/integration/operator/extension/required/runtime/runtime_test.go
Labels: kind/bug, size/L, area/control-plane, cla: yes, lgtm, approved

#11728 remove istio loadbalancer annotations from kapi service
  pkg/component/kubernetes/apiserverexposure/service.go
  pkg/component/kubernetes/apiserverexposure/service_test.go
  pkg/gardenlet/operation/botanist/kubeapiserverexposure.go
  pkg/gardenlet/operation/istio_config.go
  pkg/gardenlet/operation/istio_config_test.go
  pkg/operator/controller/garden/garden/components.go
  test/integration/operator/garden/garden/garden_test.go
Labels: kind/enhancement, size/M, area/control-plane, cla: yes, lgtm, approved

#11461 Update authorisation graph for shoot after recreating secret- or credentialbinding
  pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_shoot.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph.go
  pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go
Labels: kind/enhancement, size/M, area/control-plane, cla: yes, lgtm, approved

#11744 Update documentation for installing `hub`
  docs/development/process.md
Labels: kind/enhancement, size/XS, area/documentation, cla: yes, lgtm, approved

#11745 [release-v1.113] Automated cherry pick of #11733: Update registry.k8s.io/ingress-nginx/controller-chroot Docker tag to v1.11.5
  imagevector/containers.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#11729 Increase timeout for long-running step in seed test
  test/integration/gardenlet/seed/seed/seed_test.go
Labels: size/XS, area/robustness, kind/flake, cla: yes, lgtm, approved

#11734 Promote feature gate RemoveAPIServerProxyLegacyPort to beta
  docs/deployment/feature_gates.md
  example/gardener-local/gardenlet/values.yaml
  pkg/features/features.go
Labels: kind/enhancement, size/XS, area/networking, cla: yes, lgtm, approved

#11753 [release-v1.113] Automated cherry pick of #11628: Update quay.io/kiwigrid/k8s-sidecar Docker tag to v1.30.2
  imagevector/containers.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#11746 [release-v1.113] Automated cherry pick of #11732: Update registry.k8s.io/ingress-nginx/controller-chroot Docker tag to v1.12.1
  imagevector/containers.yaml
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved

#11701 [GEP-28] Bring up control plane as static pods
  cmd/gardenadm/app/app.go
  example/gardenadm-local/.gitignore
  example/gardenadm-local/high-touch/machine.yaml
  example/provider-local/gardenadm/shoot.yaml
  hack/check-skaffold-deps.sh
  imagevector/containers.go
  imagevector/containers.yaml
  pkg/apis/core/v1beta1/helper/shoot.go
  pkg/apis/core/v1beta1/helper/shoot_test.go
  pkg/component/apiserver/deployment.go
  pkg/component/apiserver/types.go
  pkg/component/etcd/bootstrap/etcd.go
  pkg/component/etcd/bootstrap/etcd_test.go
  pkg/component/etcd/etcd/constants/constants.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  pkg/component/extensions/operatingsystemconfig/original/components/kubelet/config_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component_test.go
  pkg/component/gardener/resourcemanager/resource_manager.go
  pkg/component/gardener/resourcemanager/resource_manager_test.go
  pkg/component/kubernetes/apiserver/apiserver.go
  pkg/component/kubernetes/apiserver/apiserver_test.go
  pkg/component/kubernetes/apiserver/deployment.go
  pkg/component/kubernetes/apiserver/mock/mocks.go
  pkg/component/kubernetes/apiserver/secrets.go
  pkg/component/shared/kubeapiserver.go
  pkg/component/shared/kubeapiserver_test.go
  pkg/gardenadm/botanist/botanist.go
  pkg/gardenadm/botanist/botanist_suite_test.go
  pkg/gardenadm/botanist/controlplane.go
  pkg/gardenadm/botanist/kubelet.go
  pkg/gardenadm/botanist/kubelet_test.go
  pkg/gardenadm/botanist/operatingsystemconfig.go
  pkg/gardenadm/cmd/init/init.go
  pkg/gardenadm/cmd/init/kubelet_test.go
  pkg/gardenadm/staticpod/translator.go
  pkg/gardenadm/staticpod/translator_test.go
  pkg/gardenlet/operation/botanist/kubeapiserver.go
  pkg/gardenlet/operation/shoot/shoot.go
  pkg/gardenlet/operation/shoot/shoot_test.go
  pkg/operator/controller/garden/garden/components.go
  pkg/provider-local/node/Dockerfile
  pkg/provider-local/node/containerd/europe-docker.pkg.dev/hosts.toml
  pkg/provider-local/node/containerd/garden.local.gardener.cloud:5001/hosts.toml
  pkg/provider-local/node/containerd/gcr.io/hosts.toml
  pkg/provider-local/node/containerd/quay.io/hosts.toml
  pkg/provider-local/node/containerd/registry.k8s.io/hosts.toml
  pkg/provider-local/webhook/controlplane/ensurer.go
  pkg/provider-local/webhook/nodeagentosc/mutator.go
  skaffold-gardenadm.yaml
  test/e2e/gardenadm/hightouch/gardenadm.go
Labels: kind/enhancement, cla: yes, lgtm, approved, size/XXL, area/ipcei

#11748 Increase VPA client-side rate limits
  pkg/component/autoscaling/vpa/admissioncontroller.go
  pkg/component/autoscaling/vpa/recommender.go
  pkg/component/autoscaling/vpa/updater.go
  pkg/component/autoscaling/vpa/vpa_test.go
Labels: kind/enhancement, size/S, area/auto-scaling, cla: yes, lgtm, approved

#11750 Remove label `topology-spread-constraints.resources.gardener.cloud/skip` under `Remove this label in gardener v1.116.0`
  charts/gardener/gardenlet/templates/deployment.yaml
  charts/gardener/gardenlet/test/chart_test.go
  charts/gardener/operator/templates/deployment.yaml
  example/provider-extensions/kyverno/kyverno-deployment.yaml
  example/provider-extensions/registry-seed/registry/registry.yaml
  example/provider-extensions/ssh-reverse-tunnel/base/sshd/sshd_deployment.yaml
Labels: area/quality, kind/cleanup, size/S, cla: yes, lgtm, approved

#11763 Fix flake in nscpfl integration test.
  test/integration/controllermanager/namespacedcloudprofile/namespacedcloudprofile_test.go
Labels: size/S, area/testing, kind/flake, cla: yes, lgtm, approved

#11749 [GEP-28] Bootstrap `kubelet` and make `gardenadm init` idempotent
  pkg/client/kubernetes/pods.go
  pkg/component/etcd/bootstrap/etcd.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/rbac.go
  pkg/component/kubernetes/apiserver/secrets.go
  pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
  pkg/component/nodemanagement/machinecontrollermanager/mock/mocks.go
  pkg/extensions/cluster.go
  pkg/extensions/cluster_test.go
  pkg/gardenadm/botanist/botanist.go
  pkg/gardenadm/botanist/controlplane.go
  pkg/gardenadm/botanist/customresourcedefinitions.go
  pkg/gardenadm/botanist/customresourcedefinitions_test.go
  pkg/gardenadm/botanist/kubelet.go
  pkg/gardenadm/botanist/kubelet_test.go
  pkg/gardenadm/botanist/secrets.go
  pkg/gardenadm/botanist/secrets_test.go
  pkg/gardenadm/cmd/init/init.go
  pkg/gardenadm/staticpod/translator.go
  pkg/gardenadm/staticpod/translator_test.go
  pkg/gardenlet/operation/botanist/botanist.go
  pkg/gardenlet/operation/botanist/infrastructure_test.go
  pkg/gardenlet/operation/botanist/machinecontrollermanager.go
  pkg/gardenlet/operation/botanist/machinecontrollermanager_test.go
  skaffold-gardenadm.yaml
  test/e2e/gardenadm/hightouch/gardenadm.go
Labels: kind/enhancement, cla: yes, lgtm, approved, size/XXL, area/ipcei

#11757 Promote `NodeAgentAuthorizer` feature gate to beta
  docs/deployment/feature_gates.md
  example/gardener-local/gardenlet/values.yaml
  pkg/component/extensions/operatingsystemconfig/nodeinit/nodeinit_test.go
  pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component_test.go
  pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/rbac_test.go
  pkg/features/features.go
Labels: kind/enhancement, area/security, size/L, cla: yes, lgtm, approved

#11491 Add `ShootState` controller managing the object deletion with additional `finalizer`
  charts/gardener/controlplane/charts/runtime/templates/controller-manager/configmap-componentconfig.yaml
  charts/gardener/controlplane/values.yaml
  docs/concepts/controller-manager.md
  example/20-componentconfig-gardener-controller-manager.yaml
  pkg/controllermanager/apis/config/v1alpha1/defaults.go
  pkg/controllermanager/apis/config/v1alpha1/defaults_test.go
  pkg/controllermanager/apis/config/v1alpha1/types.go
  pkg/controllermanager/apis/config/v1alpha1/validation/validation.go
  pkg/controllermanager/apis/config/v1alpha1/validation/validation_test.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/controllermanager/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/controllermanager/controller/add.go
  pkg/controllermanager/controller/shootstate/add.go
  pkg/controllermanager/controller/shootstate/add_test.go
  pkg/controllermanager/controller/shootstate/reconciler.go
  pkg/controllermanager/controller/shootstate/shootstate_suite_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/integration/controllermanager/shootstate/shootstate_suite_test.go
  test/integration/controllermanager/shootstate/shootstate_test.go
Labels: kind/bug, size/XL, area/control-plane-migration, cla: yes, lgtm, approved
